Repository cockroachdb/cockroach, pull requests merged in 2019-01, with the labels that each got.

#33571 sql: Add spans to flow diagrams for TableReader operations
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/distsqlpb/flow_diagram.go
  pkg/sql/logictest/testdata/logic_test/explain_analyze_plans
  pkg/sql/logictest/testdata/logic_test/zigzag_join
  pkg/sql/logictest/testdata/planner_test/distsql_agg
  pkg/sql/logictest/testdata/planner_test/distsql_auto_mode
  pkg/sql/logictest/testdata/planner_test/distsql_distinct_on
  pkg/sql/logictest/testdata/planner_test/distsql_indexjoin
  pkg/sql/logictest/testdata/planner_test/distsql_interleaved_join
  pkg/sql/logictest/testdata/planner_test/distsql_join
  pkg/sql/logictest/testdata/planner_test/distsql_lookup_join
  pkg/sql/logictest/testdata/planner_test/distsql_misc
  pkg/sql/logictest/testdata/planner_test/distsql_numtables
  pkg/sql/logictest/testdata/planner_test/distsql_sort
  pkg/sql/logictest/testdata/planner_test/distsql_srfs
  pkg/sql/logictest/testdata/planner_test/distsql_subquery
  pkg/sql/logictest/testdata/planner_test/distsql_union
  pkg/sql/logictest/testdata/planner_test/distsql_window
  pkg/sql/logictest/testdata/planner_test/insert
  pkg/sql/opt/exec/execbuilder/testdata/distsql_agg
  pkg/sql/opt/exec/execbuilder/testdata/distsql_distinct_on
  pkg/sql/opt/exec/execbuilder/testdata/distsql_indexjoin
  pkg/sql/opt/exec/execbuilder/testdata/distsql_interleaved_join
  pkg/sql/opt/exec/execbuilder/testdata/distsql_join
  pkg/sql/opt/exec/execbuilder/testdata/distsql_misc
  pkg/sql/opt/exec/execbuilder/testdata/distsql_numtables
  pkg/sql/opt/exec/execbuilder/testdata/distsql_union
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
Labels: first-pr

#34075 sql: allow specifying scan direction in index hint
  pkg/sql/logictest/testdata/logic_test/select_index_flags
  pkg/sql/logictest/testdata/planner_test/select_index_flags
  pkg/sql/opt/exec/execbuilder/testdata/select_index_flags
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/testdata/select
  pkg/sql/opt/ordering/scan.go
  pkg/sql/opt/xform/testdata/rules/limit
  pkg/sql/opt_index_selection.go
  pkg/sql/parser/parse_test.go
  pkg/sql/parser/sql.y
  pkg/sql/scan.go
  pkg/sql/sem/tree/select.go
Labels: backport-2.1.x, docs-todo

#34123 opt: add rule to simplify DistinctOn with no grouping columns
  pkg/sql/logictest/testdata/logic_test/distinct_on
  pkg/sql/opt/exec/execbuilder/relational_builder.go
  pkg/sql/opt/exec/execbuilder/testdata/distinct_on
  pkg/sql/opt/norm/groupby.go
  pkg/sql/opt/norm/rules/groupby.opt
  pkg/sql/opt/norm/testdata/rules/decorrelate
  pkg/sql/opt/norm/testdata/rules/groupby
  pkg/sql/opt/norm/testdata/rules/select
  pkg/sql/opt/xform/optimizer.go
Labels: backport-2.1.x

#34386 changefeed: add EXPERIMENTAL to the sinkless syntax
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/sql/parser/parse_test.go
  pkg/sql/parser/sql.y
  pkg/sql/sem/tree/changefeed.go
  pkg/sql/sem/tree/stmt.go
Labels: docs-todo
