Repository cockroachdb/cockroach, pull requests merged in 2019-10, with the labels that each got.

#41129 distsql: put the SQL into diagrams
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/distsql_running.go
  pkg/sql/execinfrapb/flow_diagram.go
  pkg/sql/execinfrapb/flow_diagram_test.go
  pkg/sql/explain_distsql.go
  pkg/sql/logictest/testdata/logic_test/dist_vectorize
  pkg/sql/logictest/testdata/logic_test/exec_merge_join
  pkg/sql/logictest/testdata/logic_test/exec_merge_join_dist
  pkg/sql/logictest/testdata/logic_test/explain
  pkg/sql/logictest/testdata/logic_test/explain_analyze_plans
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/logictest/testdata/logic_test/vectorize
  pkg/sql/opt/exec/execbuilder/testdata/distsql_agg
  pkg/sql/opt/exec/execbuilder/testdata/distsql_auto_mode
  pkg/sql/opt/exec/execbuilder/testdata/distsql_distinct_on
  pkg/sql/opt/exec/execbuilder/testdata/distsql_indexjoin
  pkg/sql/opt/exec/execbuilder/testdata/distsql_interleaved_join
  pkg/sql/opt/exec/execbuilder/testdata/distsql_join
  pkg/sql/opt/exec/execbuilder/testdata/distsql_misc
  pkg/sql/opt/exec/execbuilder/testdata/distsql_numtables
  pkg/sql/opt/exec/execbuilder/testdata/distsql_ordinality
  pkg/sql/opt/exec/execbuilder/testdata/distsql_union
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
Labels: backport-19.1.x

#26433 sql: support max_identifier_length variable
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/vars.go
Labels: X-noremind

#41479 backupccl: fix sanitizeLocalityKV() char handling
  pkg/ccl/backupccl/backup.go
Labels: backport-19.2.x

#33655 storage: skip TestWedgedReplicaDetection on test short
  pkg/storage/client_raft_test.go
Labels: X-noremind

#41685 opt: don't generate lookup joins with no key columns
  pkg/sql/opt/xform/custom_funcs.go
  pkg/sql/opt/xform/testdata/rules/join
Labels: backport-19.2.x

#41712 opt: clear column stats from prepared memo
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/norm/factory.go
Labels: backport-19.2.x

#41732 opt: support selecting any table column when grouping by PK
  pkg/sql/logictest/testdata/logic_test/aggregate
  pkg/sql/opt/optbuilder/groupby.go
  pkg/sql/opt/optbuilder/scalar.go
  pkg/sql/opt/optbuilder/scope.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/testdata/aggregate
  pkg/sql/opt/optbuilder/testdata/having
  pkg/sql/opt/optbuilder/window.go
Labels: backport-19.2.x

#40970 ui: fix mixed units in tooltips
  pkg/ui/src/util/format.spec.ts
  pkg/ui/src/util/format.ts
  pkg/ui/src/views/cluster/util/graphs.ts
Labels: first-pr

#41970 distsql: populate EvalCtx.Txn early in remote flows
  pkg/sql/distsql/server.go
  pkg/sql/flowinfra/cluster_test.go
Labels: backport-19.2.x

#41995 sql: fix planning issue with UNION ALL
  pkg/sql/colexec/execplan.go
  pkg/sql/distsql_physical_planner.go
  pkg/sql/logictest/testdata/logic_test/union
  pkg/sql/opt/exec/execbuilder/testdata/distsql_union
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
Labels: backport-19.2.x
