Repository cockroachdb/cockroach, pull requests merged in 2019-12, with the labels that each got.

#42616 colexec: skip over unneeded columns in cfetcher
  pkg/col/coldata/batch.go
  pkg/col/coldata/unknown_vec.go
  pkg/col/coldata/vec.go
  pkg/sql/colexec/allocator.go
  pkg/sql/colexec/cfetcher.go
  pkg/sql/logictest/testdata/logic_test/vectorize_types
  pkg/sql/opt/exec/execbuilder/testdata/scalar
  pkg/sql/opt/exec/execbuilder/testdata/select
Labels: backport-19.2.x

#42916 opt: fix selectivity calculation for multiple predicates
  pkg/sql/opt/memo/testdata/stats/select
  pkg/sql/opt/props/statistics.go
Labels: backport-19.2.x

#42968 colexec: check for unsupported output type of a builtin
  pkg/sql/colexec/builtin_funcs.go
  pkg/sql/colexec/builtin_funcs_test.go
  pkg/sql/colexec/execplan.go
  pkg/sql/logictest/testdata/logic_test/vectorize_types
Labels: backport-19.2.x

#43099 docs: fix diagrams for 'table_name @ index_name' syntax
  docs/generated/sql/bnf/alter_index_partition_by.bnf
  docs/generated/sql/bnf/drop_index.bnf
  docs/generated/sql/bnf/rename_index.bnf
  docs/generated/sql/bnf/split_index_at.bnf
  docs/generated/sql/bnf/unsplit_index_at.bnf
  pkg/cmd/docgen/diagrams.go
Labels: fixitday

#43213 ui: add changefeed retryable errors graph to web ui
  pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/changefeeds.tsx
Labels: docs-todo

#43296 sql: support EXPLAIN with AS OF SYSTEM TIME
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/as_of
Labels: backport-19.2.x

#43465 opt: add FD equivalency for semi-passthrough projection columns
  pkg/sql/opt/exec/execbuilder/testdata/fk_opt
  pkg/sql/opt/exec/execbuilder/testdata/orderby
  pkg/sql/opt/memo/logical_props_builder.go
  pkg/sql/opt/memo/testdata/logprops/groupby
  pkg/sql/opt/memo/testdata/logprops/project
  pkg/sql/opt/memo/testdata/stats/groupby
  pkg/sql/opt/norm/testdata/rules/decorrelate
  pkg/sql/opt/norm/testdata/rules/prune_cols
  pkg/sql/opt/norm/testdata/rules/set
  pkg/sql/opt/optbuilder/testdata/fk-checks-update
  pkg/sql/opt/optbuilder/testdata/select
  pkg/sql/opt/optbuilder/testdata/sequence
  pkg/sql/opt/xform/testdata/physprops/ordering
Labels: backport-19.2.x

#43557 colexec: plan CAST operator for CASE arms when types are mismatched
  pkg/sql/colexec/execplan.go
  pkg/sql/logictest/testdata/logic_test/vectorize
Labels: backport-19.2.x
