Repository cockroachdb/cockroach, pull requests merged in 2019-07, with the labels that each got.

#38713 ui: copy update for Login Page
  pkg/ui/src/views/login/loginPage.styl
  pkg/ui/src/views/login/loginPage.tsx
Labels: A-webui-layout-and-style

#38880 opt: fix incorrect span boundary from ConsolidateSpans
  pkg/sql/logictest/testdata/logic_test/select_index
  pkg/sql/opt/constraint/constraint.go
  pkg/sql/opt/constraint/constraint_test.go
  pkg/sql/opt/idxconstraint/testdata/strings
Labels: backport-19.1.x, backport-2.1.x

#27505 admin: Add Chart Catalog infrastructure
  pkg/server/admin.go
  pkg/server/serverpb/admin.pb.go
  pkg/server/serverpb/admin.pb.gw.go
  pkg/server/serverpb/admin.proto
  pkg/server/status_test.go
  pkg/ts/catalog/catalog_generator.go
  pkg/ts/catalog/chart_catalog.go
  pkg/ts/catalog/chart_catalog.pb.go
  pkg/ts/catalog/chart_catalog.proto
Labels: X-noremind

#39016 opt: improve per-ON condition cost adjustment for lookup join
  pkg/sql/opt/memo/testdata/stats_quality/tpcc
  pkg/sql/opt/optgen/exprgen/testdata/join
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/testdata/coster/join
  pkg/sql/opt/xform/testdata/coster/zone
  pkg/sql/opt/xform/testdata/external/tpcc
  pkg/sql/opt/xform/testdata/external/tpcc-no-stats
  pkg/sql/opt/xform/testdata/rules/join
Labels: backport-19.1.x

#35312 workload: support loading initial data using IMPORT in `run` and `init`
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/changefeedccl/encoder_test.go
  pkg/ccl/changefeedccl/validations_test.go
  pkg/ccl/importccl/exportcsv_test.go
  pkg/ccl/workloadccl/allccl/all_test.go
  pkg/ccl/workloadccl/bench_test.go
  pkg/ccl/workloadccl/cliccl/fixtures.go
  pkg/ccl/workloadccl/fixture.go
  pkg/ccl/workloadccl/fixture_test.go
  pkg/cli/demo.go
  pkg/workload/cli/run.go
  pkg/workload/workload.go
  pkg/workload/workloadsql/dataload.go
  pkg/workload/workloadsql/workloadsql.go
  pkg/workload/workloadsql/workloadsql_test.go
Labels: X-noremind

#39141 cli: adds \d, \dt, \du, \l metacommands to sql shell
  pkg/cli/interactive_tests/test_sql_version_reporting.tcl
  pkg/cli/sql.go
  pkg/cli/sql_test.go
Labels: first-pr
