Repository cockroachdb/cockroach, pull requests merged in 2019-11, with the labels that each got.

#42082 opt: eliminate duplicate expressions in a Range operator
  pkg/sql/opt/norm/custom_funcs.go
  pkg/sql/opt/norm/factory_test.go
  pkg/sql/opt/norm/testdata/rules/select
Labels: backport-19.2.x

#42158 opt: fix bug in GenerateConstrainedScans related to partitioning
  pkg/sql/opt/xform/custom_funcs.go
  pkg/sql/opt/xform/testdata/rules/partitioned
Labels: backport-19.2.x

#42159 opt: don't zigzag redundantly
  pkg/sql/opt/xform/custom_funcs.go
  pkg/sql/opt/xform/testdata/rules/join
Labels: backport-19.2.x

#42228 build: improve teamcity-testrace script
  build/teamcity-support.sh
Labels: backport-19.2.x

#42357 sql,stats: only sample columns needed for histogram creation
  pkg/sql/execinfrapb/processors_table_stats.pb.go
  pkg/sql/execinfrapb/processors_table_stats.proto
  pkg/sql/rowexec/sample_aggregator.go
  pkg/sql/rowexec/sampler.go
  pkg/sql/rowexec/sampler_test.go
  pkg/sql/stats/row_sampling.go
  pkg/sql/stats/row_sampling_test.go
Labels: backport-19.2.x

#42372 stats: deep-copy datums during sampling to allow GC of kv batch
  pkg/sql/stats/row_sampling.go
Labels: backport-19.2.x

#42447 opt: support grouping by aliases
  pkg/sql/opt/optbuilder/groupby.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/testdata/aggregate
Labels: backport-19.2.x

#42406 ui: Show livenes status icons for Nodes List table (Cluster Overiew)
  pkg/ui/src/views/cluster/containers/nodesOverview/index.tsx
  pkg/ui/src/views/cluster/containers/nodesOverview/nodes.styl
Labels: first-pr

#42760 opt: fix incorrect lax key calculation
  pkg/sql/opt/memo/testdata/logprops/index-join
  pkg/sql/opt/memo/testdata/logprops/scan
  pkg/sql/opt/props/func_dep.go
  pkg/sql/opt/props/func_dep_test.go
Labels: backport-19.1.x, backport-19.2.x, backport-2.1.x

#42831 colexec: fix a bug with top K sort not handling K > 1024
  pkg/sql/colexec/sort_test.go
  pkg/sql/colexec/sorttopk.go
  pkg/sql/logictest/testdata/logic_test/vectorize
Labels: backport-19.2.x
