Repository cockroachdb/cockroach, pull requests merged in 2019-05, with the labels that each got.

#37208 opt: check validation status of FK constraints
  pkg/sql/logictest/testdata/logic_test/fk
  pkg/sql/opt/cat/index.go
  pkg/sql/opt/cat/table.go
  pkg/sql/opt/exec/execbuilder/testdata/fk
  pkg/sql/opt/norm/join.go
  pkg/sql/opt/testutils/testcat/create_table.go
  pkg/sql/opt_catalog.go
Labels: backport-19.1.x

#36883 release-19.1: sql: fix multiple UX shortcomings with zone configs
  docs/generated/sql/bnf/alter_zone_index_stmt.bnf
  docs/generated/sql/bnf/show_zone_stmt.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/ccl/logictestccl/testdata/logic_test/zone
  pkg/sql/parser/parse_test.go
  pkg/sql/parser/sql.y
  pkg/sql/sem/tree/zone.go
  pkg/sql/show_zone_config.go
Labels: docs-todo

#37578 opt, sql: fix type inference of TypeCheck for subqueries
  pkg/sql/logictest/testdata/logic_test/subquery-opt
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/opt/optbuilder/builder.go
  pkg/sql/opt/optbuilder/explain.go
  pkg/sql/opt/optbuilder/scope.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/subquery.go
  pkg/sql/opt/optbuilder/testdata/subquery
  pkg/sql/sem/tree/expr.go
  pkg/sql/sem/tree/type_check.go
Labels: backport-19.1.x

#31713 sql: don't re-decode index keys when unnecessary
  pkg/bench/bench_test.go
  pkg/sql/row/fetcher.go
  pkg/sql/row/fetcher_mvcc_test.go
Labels: X-noremind

#37775 tree: handle null in suboperator expressions
  pkg/sql/sem/tree/eval.go
  pkg/sql/sem/tree/testdata/eval/any_some_all
Labels: first-pr
