Repository cockroachdb/cockroach, pull requests merged in 2020-05, with the labels that each got.

#46840 sql: fix the telemetry for conn+audit logs
  pkg/sql/authorization.go
  pkg/sql/logictest/testdata/logic_test/feature_counts
  pkg/sql/pgwire/conn.go
  pkg/sql/pgwire/server.go
  pkg/sql/set_cluster_setting.go
  pkg/sql/sqltelemetry/iam.go
  pkg/sql/sqltelemetry/scalar.go
Labels: backport-20.1

#48126 sql: populate pg_catalog.pg_aggregate table
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/orms
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
  pkg/sql/sqlbase/constants.go
Labels: X-blathers-triaged

#47605 release-20.1: sqltelemetry: add CANCEL QUERIES and CANCEL SESSIONS telemetry
  pkg/sql/opt/exec/execbuilder/statement.go
  pkg/sql/sqltelemetry/planning.go
Labels: do-not-merge

#48351 sql: remove typo in pg_catalog.pg_aggregate table population.
  pkg/sql/pg_catalog.go
Labels: X-blathers-triaged

#48298 opt: add rule to fold remappings of ValuesExpr columns
  pkg/sql/opt/memo/testdata/stats/groupby
  pkg/sql/opt/norm/custom_funcs.go
  pkg/sql/opt/norm/rules/project.opt
  pkg/sql/opt/norm/testdata/rules/project
  pkg/sql/opt/norm/testdata/rules/with
  pkg/sql/opt/xform/testdata/external/trading
  pkg/sql/opt/xform/testdata/external/trading-mutation
Labels: X-blathers-untriaged

#48483 release-19.1: server: properly set up new pipes on every loopback connection
  pkg/server/loopback.go
  pkg/server/server.go
  pkg/util/netutil/net.go
Labels: X-blathers-silence

#48497 colrpc: wrap batch serialization with panic catcher in outbox
  pkg/sql/colflow/colrpc/outbox.go
Labels: backport-19.2.x, backport-20.1

#48580 opt: fix bug in histogram filtering code for uuid and string predicates
  pkg/sql/opt/memo/testdata/stats/scan
  pkg/sql/opt/memo/testdata/stats/select
  pkg/sql/opt/memo/testdata/stats_quality/tpch/q01
  pkg/sql/opt/props/histogram.go
  pkg/sql/opt/props/histogram_test.go
Labels: backport-19.2.x, backport-20.1

#48582 kvserver: make two settings public
  docs/generated/settings/settings.html
  pkg/kv/kvserver/replica_split_load.go
Labels: backport-20.1

#48593 importccl: fix bug where GC job would not operate on any tables
  pkg/ccl/importccl/import_stmt.go
  pkg/ccl/importccl/import_stmt_test.go
  pkg/jobs/registry.go
Labels: backport-20.1

#48659 colexec: fix type schema for LEFT SEMI and LEFT ANTI joins
  pkg/sql/colexec/execplan.go
  pkg/sql/logictest/testdata/logic_test/merge_join
Labels: backport-20.1

#48688 cli: fix dump with interleaved primary keys
  pkg/cli/dump_test.go
  pkg/cli/testdata/dump/interleave_index
  pkg/sql/crdb_internal.go
Labels: backport-19.2.x, backport-20.1

#48510 sql: preserve zone configurations after a primary key change
  pkg/ccl/logictestccl/testdata/logic_test/zone
  pkg/ccl/partitionccl/partition_test.go
  pkg/sql/schema_changer.go
Labels: backport-20.1

#48687 cli: fix `cockroach dump` with collated strings
  pkg/cli/dump.go
  pkg/cli/testdata/dump/row
Labels: backport-19.2.x, backport-20.1

#48823 sqlmigrations: fix handling of mutations in schema change job migration
  pkg/sql/schema_change_migrations_test.go
  pkg/sqlmigrations/migrations.go
Labels: backport-20.1

#48862 opt: fix costing of lookup join with limit hint
  pkg/sql/opt/memo/testdata/memo
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/testdata/coster/join
  pkg/sql/opt/xform/testdata/external/trading
  pkg/sql/opt/xform/testdata/external/trading-mutation
Labels: backport-20.1.x

#48167 backupccl,sql: do not include comments in SHOW BACKUP SCHEMAS
  pkg/ccl/backupccl/show.go
  pkg/ccl/backupccl/show_test.go
  pkg/sql/crdb_internal.go
  pkg/sql/planhook.go
  pkg/sql/show_create.go
Labels: backport-20.1.x

#49125 sql: delete public schema on DROP DATABASE
  pkg/sql/drop_database.go
  pkg/sql/drop_test.go
Labels: backport-20.1.x

#48849 sql: add job ID to queued schema change log
  pkg/sql/table.go
Labels: backport-20.1.x

#48520 sql: add EnsureUpsertDistinctOn operator
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/memo/check_expr.go
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/memo/logical_props_builder.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/logprops/join
  pkg/sql/opt/memo/testdata/logprops/upsert
  pkg/sql/opt/memo/testdata/stats/upsert
  pkg/sql/opt/norm/custom_funcs.go
  pkg/sql/opt/norm/groupby.go
  pkg/sql/opt/norm/rules/groupby.opt
  pkg/sql/opt/norm/testdata/rules/groupby
  pkg/sql/opt/norm/testdata/rules/prune_cols
  pkg/sql/opt/ops/relational.opt
  pkg/sql/opt/optbuilder/distinct.go
  pkg/sql/opt/optbuilder/insert.go
  pkg/sql/opt/optbuilder/testdata/fk-checks-upsert
  pkg/sql/opt/optbuilder/testdata/upsert
  pkg/sql/opt/optgen/lang/support/textmate/OptGen.tmbundle/Syntaxes/optgen.tmLanguage
  pkg/sql/opt/optgen/lang/support/vim/cropt.vim
  pkg/sql/opt/optgen/lang/support/vscode/cockroachdb.optgen-1.0.0/syntaxes/optgen.tmLanguage
  pkg/sql/opt/ordering/ordering.go
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/custom_funcs.go
  pkg/sql/opt/xform/rules/groupby.opt
  pkg/sql/opt/xform/testdata/external/trading
  pkg/sql/opt/xform/testdata/external/trading-mutation
  pkg/sql/opt/xform/testdata/physprops/ordering
  pkg/sql/opt/xform/testdata/rules/groupby
Labels: X-blathers-untriaged

#45866 backupccl: set DescIDGenerator directly in full-cluster restore
  pkg/ccl/backupccl/full_cluster_backup_restore_test.go
  pkg/ccl/backupccl/restore_planning.go
Labels: backport-20.1.x

#49101 changefeedccl: fix memory leak in rowFetcherCache
  pkg/ccl/changefeedccl/rowfetcher_cache.go
Labels: A-cdc, C-bug, backport-19.1.x, backport-19.2.x, backport-20.1.x

#49151 opt: refactor custom_funcs to make reusable functions easier to find
  pkg/sql/opt/norm/README.md
  pkg/sql/opt/norm/bool_funcs.go
  pkg/sql/opt/norm/comp_funcs.go
  pkg/sql/opt/norm/custom_funcs.go
  pkg/sql/opt/norm/decorrelate_funcs.go
  pkg/sql/opt/norm/decorrelate_funcs_test.go
  pkg/sql/opt/norm/fold_constants_funcs.go
  pkg/sql/opt/norm/general_funcs.go
  pkg/sql/opt/norm/general_funcs_test.go
  pkg/sql/opt/norm/groupby_funcs.go
  pkg/sql/opt/norm/inline_funcs.go
  pkg/sql/opt/norm/join_funcs.go
  pkg/sql/opt/norm/limit_funcs.go
  pkg/sql/opt/norm/ordering_funcs.go
  pkg/sql/opt/norm/project_funcs.go
  pkg/sql/opt/norm/project_set_funcs.go
  pkg/sql/opt/norm/prune_cols_funcs.go
  pkg/sql/opt/norm/reject_nulls_funcs.go
  pkg/sql/opt/norm/rules/limit.opt
  pkg/sql/opt/norm/rules/numeric.opt
  pkg/sql/opt/norm/rules/scalar.opt
  pkg/sql/opt/norm/scalar_funcs.go
  pkg/sql/opt/norm/select_funcs.go
  pkg/sql/opt/norm/set_funcs.go
  pkg/sql/opt/norm/window_funcs.go
  pkg/sql/opt/norm/with_funcs.go
  pkg/sql/opt/optgen/cmd/optgen/testdata/explorer
  pkg/sql/opt/xform/rules/limit.opt
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community

#49133 ui: restore preset options in metrics timepicker
  pkg/ui/src/views/cluster/components/range/index.tsx
  pkg/ui/src/views/cluster/components/range/range.spec.tsx
Labels: backport-20.1.x

#49169 geo/geomfn: implement ST_SRID({geometry})
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community, X-blathers-triaged

#49287 opt: throw error if ordered-set aggregate is malformed
  pkg/sql/logictest/testdata/logic_test/aggregate
  pkg/sql/opt/optbuilder/scope.go
Labels: O-community, X-blathers-triaged

#49223 colmem: reset flat bytes vector when reused
  pkg/sql/colexec/execplan.go
  pkg/sql/colexec/operator.go
  pkg/sql/colmem/allocator.go
  pkg/sql/logictest/testdata/logic_test/vectorize
Labels: backport-20.1.x

#49490 opt: fix _func file nits
  pkg/sql/opt/norm/bool_funcs.go
  pkg/sql/opt/norm/comp_funcs.go
  pkg/sql/opt/norm/general_funcs.go
  pkg/sql/opt/norm/limit_funcs.go
  pkg/sql/opt/norm/project_funcs.go
  pkg/sql/opt/norm/project_set_funcs.go
  pkg/sql/opt/norm/scalar_funcs.go
  pkg/sql/opt/norm/select_funcs.go
  pkg/sql/opt/norm/set_funcs.go
  pkg/sql/opt/norm/window_funcs.go
  pkg/sql/opt/norm/with_funcs.go
Labels: O-community

#49487 backport-20.1: opt: refactor custom_funcs to make reusable functions easier to find
  pkg/sql/opt/norm/README.md
  pkg/sql/opt/norm/bool_funcs.go
  pkg/sql/opt/norm/comp_funcs.go
  pkg/sql/opt/norm/custom_funcs.go
  pkg/sql/opt/norm/decorrelate_funcs.go
  pkg/sql/opt/norm/decorrelate_funcs_test.go
  pkg/sql/opt/norm/fold_constants_funcs.go
  pkg/sql/opt/norm/general_funcs.go
  pkg/sql/opt/norm/general_funcs_test.go
  pkg/sql/opt/norm/groupby_funcs.go
  pkg/sql/opt/norm/inline_funcs.go
  pkg/sql/opt/norm/join_funcs.go
  pkg/sql/opt/norm/limit_funcs.go
  pkg/sql/opt/norm/ordering_funcs.go
  pkg/sql/opt/norm/project_funcs.go
  pkg/sql/opt/norm/prune_cols_funcs.go
  pkg/sql/opt/norm/reject_nulls_funcs.go
  pkg/sql/opt/norm/rules/limit.opt
  pkg/sql/opt/norm/rules/numeric.opt
  pkg/sql/opt/norm/scalar_funcs.go
  pkg/sql/opt/norm/select_funcs.go
  pkg/sql/opt/norm/set_funcs.go
  pkg/sql/opt/norm/window_funcs.go
  pkg/sql/opt/norm/with_funcs.go
  pkg/sql/opt/optgen/cmd/optgen/testdata/explorer
  pkg/sql/opt/xform/rules/limit.opt
Labels: O-community

#49489 Backport19.1 49151: opt: refactor custom_funcs to make reusable functions easier to find
  pkg/sql/opt/norm/README.md
  pkg/sql/opt/norm/bool_funcs.go
  pkg/sql/opt/norm/comp_funcs.go
  pkg/sql/opt/norm/custom_funcs.go
  pkg/sql/opt/norm/decorrelate_funcs.go
  pkg/sql/opt/norm/decorrelate_funcs_test.go
  pkg/sql/opt/norm/fold_constants_funcs.go
  pkg/sql/opt/norm/general_funcs.go
  pkg/sql/opt/norm/groupby_funcs.go
  pkg/sql/opt/norm/inline_funcs.go
  pkg/sql/opt/norm/join_funcs.go
  pkg/sql/opt/norm/limit_funcs.go
  pkg/sql/opt/norm/ordering_funcs.go
  pkg/sql/opt/norm/project_funcs.go
  pkg/sql/opt/norm/prune_cols_funcs.go
  pkg/sql/opt/norm/reject_nulls_funcs.go
  pkg/sql/opt/norm/scalar_funcs.go
  pkg/sql/opt/norm/select_funcs.go
  pkg/sql/opt/norm/set_funcs.go
  pkg/sql/opt/xform/custom_funcs.go
Labels: O-community

#49488 Backport19.2 49151: opt: refactor custom_funcs to make reusable functions easier to find
  pkg/sql/opt/norm/README.md
  pkg/sql/opt/norm/bool_funcs.go
  pkg/sql/opt/norm/comp_funcs.go
  pkg/sql/opt/norm/custom_funcs.go
  pkg/sql/opt/norm/decorrelate_funcs.go
  pkg/sql/opt/norm/decorrelate_funcs_test.go
  pkg/sql/opt/norm/fold_constants_funcs.go
  pkg/sql/opt/norm/general_funcs.go
  pkg/sql/opt/norm/groupby_funcs.go
  pkg/sql/opt/norm/inline_funcs.go
  pkg/sql/opt/norm/join_funcs.go
  pkg/sql/opt/norm/limit_funcs.go
  pkg/sql/opt/norm/ordering_funcs.go
  pkg/sql/opt/norm/project_funcs.go
  pkg/sql/opt/norm/prune_cols_funcs.go
  pkg/sql/opt/norm/reject_nulls_funcs.go
  pkg/sql/opt/norm/scalar_funcs.go
  pkg/sql/opt/norm/select_funcs.go
  pkg/sql/opt/norm/set_funcs.go
  pkg/sql/opt/norm/window_funcs.go
  pkg/sql/opt/norm/with_funcs.go
Labels: O-community

#49547 serverutils: change StartTenant to start a tenant with a given tenant ID
  pkg/server/server_sql_test.go
  pkg/server/testserver.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/aggregate
  pkg/sql/logictest/testdata/logic_test/alias_types
  pkg/sql/logictest/testdata/logic_test/alter_column_type
  pkg/sql/logictest/testdata/logic_test/array
  pkg/sql/logictest/testdata/logic_test/bit
  pkg/sql/logictest/testdata/logic_test/case_sensitive_names
  pkg/sql/logictest/testdata/logic_test/check_constraints
  pkg/sql/logictest/testdata/logic_test/collatedstring
  pkg/sql/logictest/testdata/logic_test/computed
  pkg/sql/logictest/testdata/logic_test/create_as
  pkg/sql/logictest/testdata/logic_test/create_index
  pkg/sql/logictest/testdata/logic_test/create_table
  pkg/sql/logictest/testdata/logic_test/distsql_join
  pkg/sql/logictest/testdata/logic_test/hash_sharded_index
  pkg/sql/logictest/testdata/logic_test/insert
  pkg/sql/logictest/testdata/logic_test/int_size
  pkg/sql/logictest/testdata/logic_test/interleaved
  pkg/sql/logictest/testdata/logic_test/interleaved_join
  pkg/sql/logictest/testdata/logic_test/inverted_index
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/logictest/testdata/logic_test/name_escapes
  pkg/sql/logictest/testdata/logic_test/namespace
  pkg/sql/logictest/testdata/logic_test/ordinality
  pkg/sql/logictest/testdata/logic_test/partial_txn_commit
  pkg/sql/logictest/testdata/logic_test/privileges_database
  pkg/sql/logictest/testdata/logic_test/rename_constraint
  pkg/sql/logictest/testdata/logic_test/select_index
  pkg/sql/logictest/testdata/logic_test/sequences
  pkg/sql/logictest/testdata/logic_test/serial
  pkg/sql/logictest/testdata/logic_test/show_create
  pkg/sql/logictest/testdata/logic_test/subquery
  pkg/sql/logictest/testdata/logic_test/system
  pkg/sql/logictest/testdata/logic_test/system_namespace
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/logictest/testdata/logic_test/temp_table
  pkg/sql/logictest/testdata/logic_test/tenant
  pkg/sql/logictest/testdata/logic_test/tenant_unsupported
  pkg/sql/logictest/testdata/logic_test/update
  pkg/sql/logictest/testdata/logic_test/upsert
  pkg/sql/logictest/testdata/logic_test/views
  pkg/sql/opt/exec/execbuilder/testdata/geospatial
  pkg/testutils/serverutils/test_server_shim.go
Labels: A-multitenancy

#49550 sql: prohibit phase 2 tenants from setting cluster settings
  pkg/base/test_server_args.go
  pkg/base/testing_knobs.go
  pkg/server/server_sql.go
  pkg/server/server_sql_test.go
  pkg/server/testserver.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/jobs
  pkg/sql/logictest/testdata/logic_test/privileges_comments
  pkg/sql/logictest/testdata/logic_test/tenant
  pkg/sql/set_cluster_setting.go
  pkg/testutils/serverutils/test_server_shim.go
Labels: A-multitenancy

#49326 backupccl: add gzip compression for Manifest and PartitionDescriptor
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/manifest_handling.go
Labels: first-pr

#49591 backupccl: all full cluster restore of backup with no user data
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/full_cluster_backup_restore_test.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_planning.go
Labels: backport-20.1.x

#49457 roachpb: implement SafeMessager interface in RangeDescriptor
  pkg/roachpb/metadata.go
  pkg/roachpb/metadata_test.go
Labels: first-pr

#49333 colexec: fix premature calls to IdempotentClose in hash router outputs
  pkg/sql/colexec/routers.go
  pkg/sql/colexec/routers_test.go
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/colflow/vectorized_flow_shutdown_test.go
Labels: backport-20.1.x

#49585 sql: use SQLInstanceID in EXPLAIN instead of OptionalNodeIDErr
  pkg/sql/explain_distsql.go
  pkg/sql/explain_plan.go
  pkg/sql/logictest/testdata/logic_test/rename_column
  pkg/sql/logictest/testdata/logic_test/rename_index
  pkg/sql/logictest/testdata/logic_test/values
Labels: A-multitenancy

#48859 pgwire: trim statements past the conn executor's rewind pos eagerly
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_test.go
  pkg/sql/conn_io.go
  pkg/sql/exec_util.go
Labels: A-sql-pgwire

#49459 server: trim deps in StartTenant
  pkg/base/config.go
  pkg/base/test_server_args.go
  pkg/ccl/changefeedccl/bench_test.go
  pkg/ccl/changefeedccl/sink_cloudstorage_test.go
  pkg/ccl/cliccl/load.go
  pkg/ccl/importccl/import_processor_test.go
  pkg/ccl/importccl/load.go
  pkg/cli/context.go
  pkg/cli/flags.go
  pkg/cli/flags_test.go
  pkg/cli/start.go
  pkg/cmd/roachtest/kv.go
  pkg/jobs/registry_external_test.go
  pkg/rpc/context.go
  pkg/server/config.go
  pkg/server/node.go
  pkg/server/server.go
  pkg/server/server_sql.go
  pkg/server/testserver.go
  pkg/sql/stats/automatic_stats_manual_test.go
  pkg/storage/cloud/external_storage.go
  pkg/storage/cloud/external_storage_test.go
  pkg/storage/cloud/gcs_storage.go
  pkg/storage/cloud/gcs_storage_test.go
  pkg/storage/cloud/http_storage_test.go
  pkg/storage/cloud/nodelocal_storage_test.go
  pkg/storage/cloud/s3_storage.go
  pkg/storage/cloud/s3_storage_test.go
Labels: A-multitenancy

#49644 geo/geomfn: implement ST_AsHexEWKB({geometry,text}), ST_AsHexEWKB({ge…
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community, X-blathers-triaged

#49634 opt: fix incorrect join simplification in cross join input case
  pkg/sql/logictest/testdata/logic_test/join
  pkg/sql/opt/norm/join_funcs.go
Labels: O-community

#49633 opt: fix incorrect join simplification in match simple case
  pkg/sql/logictest/testdata/logic_test/fk
  pkg/sql/opt/norm/join_funcs.go
Labels: O-community

#49732 Backport19.2 49633: opt: fix incorrect join simplification in match simple case
  pkg/sql/logictest/testdata/logic_test/fk
  pkg/sql/opt/norm/join_funcs.go
Labels: O-community

#49733 Backport19.1 49633: opt: fix incorrect join simplification in match simple case
  pkg/sql/logictest/testdata/logic_test/fk
  pkg/sql/opt/norm/join_funcs.go
Labels: O-community

#49731 Backport19.1 49634: opt: fix incorrect join simplification in cross join input case
  pkg/sql/logictest/testdata/logic_test/join
  pkg/sql/opt/norm/join_funcs.go
Labels: O-community

#49730 Backport19.2 49634: opt: fix incorrect join simplification in cross join input case
  pkg/sql/logictest/testdata/logic_test/join
  pkg/sql/opt/norm/join_funcs.go
Labels: O-community

#49687 opt: fold join simplification rules
  pkg/sql/opt/norm/rules/join.opt
  pkg/sql/opt/norm/testdata/rules/join
Labels: O-community
