Repository cockroachdb/cockroach, pull requests merged in 2020-03, with the labels that each got.

#45621 sql: allow inverted indexes on mixed-case cols
  pkg/sql/backfill.go
  pkg/sql/logictest/testdata/logic_test/inverted_index
Labels: backport-19.1.x, backport-19.2.x

#43114 *: allow periods (.) in usernames
  pkg/cli/cli_test.go
  pkg/sql/create_user.go
  pkg/sql/create_user_test.go
  pkg/sql/logictest/testdata/logic_test/drop_user
  pkg/sql/logictest/testdata/logic_test/user
Labels: A-security

#45127 server: make UI customizations work for non-admin users
  pkg/server/admin.go
  pkg/server/admin_test.go
  pkg/testutils/serverutils/test_server_shim.go
Labels: backport-19.1.x, backport-19.2.x, backport-2.1.x

#44666 opt, tree: window functions fixes in some edge cases
  pkg/sql/logictest/testdata/logic_test/window
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/factory.go
  pkg/sql/opt/ops/relational.opt
  pkg/sql/opt/optbuilder/window.go
  pkg/sql/opt_exec_factory.go
  pkg/sql/sem/tree/window_funcs.go
  pkg/sql/sem/tree/window_funcs_test.go
Labels: backport-19.1.x, backport-19.2.x

#45119 server: fix broken /health
  pkg/cli/init.go
  pkg/cli/zip.go
  pkg/server/admin.go
  pkg/server/admin_test.go
  pkg/server/grpc_server.go
  pkg/server/server.go
  pkg/server/serverpb/admin.pb.go
  pkg/server/serverpb/admin.pb.gw.go
  pkg/server/serverpb/admin.proto
  pkg/server/serverpb/status.pb.go
  pkg/server/serverpb/status.pb.gw.go
  pkg/server/serverpb/status.proto
  pkg/server/status.go
  pkg/server/status_test.go
Labels: backport-19.1.x, backport-19.2.x

#46042 sql: Move RBAC into the BSL license.
  docs/generated/sql/bnf/alter_role_stmt.bnf
  docs/generated/sql/bnf/create_role_stmt.bnf
  docs/generated/sql/bnf/drop_role_stmt.bnf
  docs/generated/sql/bnf/drop_stmt.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/ccl/backupccl/full_cluster_backup_restore_test.go
  pkg/ccl/ccl_init.go
  pkg/ccl/importccl/import_stmt_test.go
  pkg/ccl/logictestccl/testdata/logic_test/role
  pkg/ccl/roleccl/main_test.go
  pkg/ccl/roleccl/role.go
  pkg/cli/cli_test.go
  pkg/cmd/docgen/diagrams.go
  pkg/sql/alter_role.go
  pkg/sql/create_role.go
  pkg/sql/drop_role.go
  pkg/sql/grant_role.go
  pkg/sql/logictest/testdata/logic_test/ccl
  pkg/sql/logictest/testdata/logic_test/role
  pkg/sql/opaque.go
  pkg/sql/parser/help_test.go
  pkg/sql/parser/parse_test.go
  pkg/sql/parser/sql.y
  pkg/sql/plan.go
  pkg/sql/planhook.go
  pkg/sql/revoke_role.go
  pkg/sql/sem/tree/create.go
  pkg/sql/sem/tree/drop.go
  pkg/sql/sem/tree/stmt.go
  pkg/sql/walk.go
Labels: docs-todo

#46229 opt: add safe logging to new test code
  pkg/sql/opt/memo/check_expr.go
Labels: backport-19.2.x

#46360 colexec: support concurrent DrainMeta and Next calls in the Columnarizer
  pkg/sql/colexec/columnarizer.go
  pkg/sql/colexec/columnarizer_test.go
Labels: backport-19.2.x

#46483 release-19.2: cli/start: remove the 1-minute hard shutdown timeout
  pkg/cli/start.go
Labels: docs-todo

#46570 sql: fix bug with decoding descending collated strings
  pkg/sql/logictest/testdata/logic_test/collatedstring
  pkg/sql/sqlbase/column_type_encoding.go
Labels: backport-19.1.x, backport-19.2.x

#46545 sem/builtins: account for internal memory of some aggregates
  pkg/sql/sem/builtins/aggregate_builtins.go
  pkg/sql/sem/tree/aggregate_funcs.go
Labels: backport-19.2.x

#46649 sql: fix type checking code for aggregate functions
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/opt/optbuilder/testdata/aggregate
  pkg/sql/sem/tree/type_check.go
Labels: backport-19.2.x

#46724 colrpc: reduce Outbox Next error logging verbosity
  pkg/sql/colflow/colrpc/outbox.go
Labels: backport-19.2.x
