Repository cockroachdb/cockroach, pull requests merged in 2020-02, with the labels that each got.

#44349 ui: reserve the statements endpoint to admin users
  pkg/server/statements.go
Labels: A-security, C-bug

#44560 stats: fix flaky test TestDefaultColumns
  pkg/sql/stats/automatic_stats_test.go
Labels: backport-19.1.x, backport-19.2.x

#44692 opt: fix internal error when aggregating on a virtual table
  pkg/sql/opt/optbuilder/groupby.go
  pkg/sql/opt/optbuilder/testdata/aggregate
Labels: backport-19.2.x

#44756 colexec: disallow planning CASE operators with unknown WHEN type
  pkg/sql/colexec/execplan.go
  pkg/sql/logictest/testdata/logic_test/vectorize
Labels: backport-19.2.x

#44697 engine: Handle put when all writes are ignored and there are no committed values
  pkg/storage/engine/mvcc.go
  pkg/storage/engine/testdata/mvcc_histories/ignored_seq_nums_cput
  pkg/storage/engine/testdata/mvcc_histories/put_after_rollback
Labels: A-kv-transactions, C-bug

#35294 roachprod: add a max-concurrency flag with a default of 32
  pkg/cmd/roachprod/install/cluster_synced.go
  pkg/cmd/roachprod/main.go
Labels: X-noremind

#44872 opt: don't modify withProps.Binding.Stats in-place
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/memo
  pkg/sql/opt/memo/testdata/stats/delete
  pkg/sql/opt/memo/testdata/stats/groupby
  pkg/sql/opt/memo/testdata/stats/insert
  pkg/sql/opt/memo/testdata/stats/select
  pkg/sql/opt/memo/testdata/stats/update
  pkg/sql/opt/memo/testdata/stats/upsert
  pkg/sql/opt/memo/testdata/stats/with
  pkg/sql/opt/props/col_stats_map.go
  pkg/sql/opt/props/col_stats_map_test.go
  pkg/sql/opt/props/histogram.go
  pkg/sql/opt/props/statistics.go
  pkg/sql/opt/xform/testdata/external/tpcc
  pkg/sql/opt/xform/testdata/external/tpcc-later-stats
  pkg/sql/opt/xform/testdata/external/tpcc-no-stats
  pkg/sql/plan_opt_test.go
Labels: backport-19.2.x

#44887 colexec: fix substring operator for mixed type int arguments
  Makefile
  pkg/sql/colexec/.gitignore
  pkg/sql/colexec/builtin_funcs.go
  pkg/sql/colexec/builtin_funcs_test.go
  pkg/sql/colexec/execgen/cmd/execgen/substring_gen.go
  pkg/sql/colexec/substring_tmpl.go
  pkg/sql/logictest/testdata/logic_test/tpch_vec
  pkg/sql/logictest/testdata/logic_test/vectorize
Labels: backport-19.2.x

#44890 opt: fix deduplication of impure expressions
  pkg/sql/logictest/testdata/logic_test/impure
  pkg/sql/opt/optbuilder/distinct.go
  pkg/sql/opt/optbuilder/orderby.go
  pkg/sql/opt/optbuilder/project.go
  pkg/sql/opt/optbuilder/scope.go
  pkg/sql/opt/optbuilder/testdata/aggregate
  pkg/sql/opt/optbuilder/testdata/projection-reuse
  pkg/sql/opt/optbuilder/window.go
Labels: backport-19.1.x, backport-19.2.x

#44930 colflow: error out when phys types mismatch when setting up a flow
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/distsql/server.go
  pkg/sql/distsql_running.go
  pkg/sql/explain_plan.go
  pkg/sql/explain_vec.go
  pkg/sql/logictest/testdata/logic_test/vectorize_types
Labels: backport-19.2.x

#44931 sql: wrap iteration over OpNodes in explain_vec with panic catcher
  pkg/sql/explain_vec.go
Labels: backport-19.2.x

#45042 colflow: check that physical types match on the ends of streams
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/logictest/testdata/logic_test/vectorize_types
Labels: backport-19.2.x

#45200 log: include secondary log files in ListLogFiles
  pkg/util/log/file.go
  pkg/util/log/secondary_log_test.go
Labels: backport-19.2.x

#45536 colexec: make Materializer perform deep copies of decimal before returning row
  pkg/col/coldata/batch.go
  pkg/col/coldata/vec_tmpl.go
  pkg/sql/colexec/buffered_batch.go
  pkg/sql/colexec/vec_elem_to_datum.go
  pkg/sql/logictest/testdata/logic_test/vectorize
Labels: backport-19.2.x
