Repository cockroachdb/cockroach, pull requests merged in 2020-12, with the labels that each got.

#56587 importccl: Added row limit option for importing bundle formats
  pkg/ccl/importccl/import_processor.go
  pkg/ccl/importccl/import_stmt.go
  pkg/ccl/importccl/import_stmt_test.go
  pkg/ccl/importccl/read_import_mysql.go
  pkg/ccl/importccl/read_import_mysql_test.go
  pkg/ccl/importccl/read_import_pgdump.go
  pkg/roachpb/io-formats.pb.go
  pkg/roachpb/io-formats.proto
Labels: A-bulkio

#57212 builtins: add uuid_generate_v4 builtin alias
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/impure
  pkg/sql/sem/builtins/builtins.go
Labels: O-community, X-blathers-triaged

#57026 opt: add rule to normalize @> to false when const array contains NULLs
  pkg/sql/opt/exec/execbuilder/testdata/inverted_index
  pkg/sql/opt/memo/constraint_builder.go
  pkg/sql/opt/memo/testdata/logprops/constraints
  pkg/sql/opt/optgen/lang/doc.go
Labels: O-community

#57423 docs: Update the `Follower Reads RFC` link.
  docs/RFCS/20181227_follower_reads_implementation.md
Labels: O-community

#57524 opt: fix bug in ExtractJoinEqualities rule
  pkg/sql/opt/norm/join_funcs.go
Labels: backport-20.1.x, backport-20.2.x

#57609 sql: Add information_schema.collations table
  pkg/sql/catalog/catconstants/constants.go
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/schema
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/vtable/information_schema.go
Labels: O-community, X-blathers-triaged

#57587 jobs: invert status predicate to improve query plan
  pkg/jobs/adopt.go
  pkg/jobs/registry.go
Labels: backport-20.2.x

#57568 sql: disallow admins from dropping system tables
  pkg/sql/authorization.go
  pkg/sql/drop_table.go
  pkg/sql/logictest/testdata/logic_test/system
Labels: backport-20.2.x

#52745 rfc: Non-Blocking Transactions
  docs/RFCS/20200811_non_blocking_txns.md
Labels: A-multiregion

#57648 sql: add force flag overloads to crdb_internal.unsafe_.* builtins
  pkg/sql/faketreeeval/evalctx.go
  pkg/sql/repair.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/tree/eval.go
  pkg/sql/tests/repair_test.go
Labels: A-schema-descriptors, backport-20.2.x

#57583 builtins: implement regr_avgy
  docs/generated/sql/aggregates.md
  pkg/sql/distsql/columnar_operators_test.go
  pkg/sql/execinfrapb/processors_sql.pb.go
  pkg/sql/execinfrapb/processors_sql.proto
  pkg/sql/logictest/testdata/logic_test/aggregate
  pkg/sql/logictest/testdata/logic_test/distsql_agg
  pkg/sql/opt/exec/execbuilder/testdata/aggregate
  pkg/sql/opt/operator.go
  pkg/sql/opt/ops/scalar.opt
  pkg/sql/opt/optbuilder/groupby.go
  pkg/sql/opt/optbuilder/testdata/aggregate
  pkg/sql/sem/builtins/aggregate_builtins.go
  pkg/sql/sem/builtins/aggregate_builtins_test.go
  scripts/crlogictest.vim
Labels: O-community

#57730 docs: Correct the word "receiving".
  docs/RFCS/20181227_follower_reads_implementation.md
Labels: O-community, X-blathers-untriaged

#57387 hlc: handle synthetic bit in timestamp.{Forward,Backward}
  pkg/util/hlc/timestamp.go
  pkg/util/hlc/timestamp_test.go
Labels: A-multiregion

#57598 sql: fix bugs in adding foreign keys
  pkg/sql/backfill.go
  pkg/sql/logictest/testdata/logic_test/schema_change_in_txn
  pkg/sql/schema_changer.go
  pkg/sql/schema_changer_test.go
Labels: backport-20.2.x

#56843 pkg/sql: implement levenshtein
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/fuzzystrmatch
  pkg/sql/sem/builtins/BUILD.bazel
  pkg/sql/sem/builtins/builtins.go
  pkg/util/fuzzystrmatch/BUILD.bazel
  pkg/util/fuzzystrmatch/leven.go
  pkg/util/fuzzystrmatch/leven_test.go
Labels: O-community, X-blathers-triaged

#57146 sql: use constraint name when adding a primary key constraint
  pkg/sql/alter_primary_key.go
  pkg/sql/alter_table.go
  pkg/sql/catalog/descpb/structured.pb.go
  pkg/sql/catalog/descpb/structured.proto
  pkg/sql/catalog/tabledesc/structured.go
  pkg/sql/logictest/testdata/logic_test/alter_primary_key
  pkg/sql/sem/tree/alter_table.go
Labels: O-community, X-blathers-triaged

#57240 sql: populated pg_depend with table and view dependencies
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: X-blathers-triaged

#57615 builtins: add fuzzystrmatch soundex and difference builtin functions
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/fuzzystrmatch
  pkg/sql/sem/builtins/builtins.go
  pkg/util/fuzzystrmatch/BUILD.bazel
  pkg/util/fuzzystrmatch/soundex.go
  pkg/util/fuzzystrmatch/soundex_test.go
Labels: O-community, X-blathers-triaged

#57749 sql: fix bug in SHOW TABLES FROM <db> hiding non-public tables
  pkg/sql/delegate/show_tables.go
  pkg/sql/logictest/testdata/logic_test/schema
Labels: backport-20.2.x

#57697 geo: add st_orientedenvelope builtin
  docs/generated/sql/functions.md
  pkg/geo/geomfn/topology_operations.go
  pkg/geo/geomfn/topology_operations_test.go
  pkg/geo/geomfn/voronoi.go
  pkg/geo/geos/geos.cc
  pkg/geo/geos/geos.go
  pkg/geo/geos/geos.h
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community, X-blathers-untriaged

#57828 sql: fix a race in cancelation of virtual table generators
  pkg/sql/tests/BUILD.bazel
  pkg/sql/tests/virtual_table_test.go
  pkg/sql/virtual_table.go
Labels: backport-20.2.x

#57927 opt: fix panic caused by some DDL statements and CTEs
  pkg/sql/opt/memo/logical_props_builder.go
  pkg/sql/opt/memo/testdata/logprops/with
Labels: backport-20.1.x, backport-20.2.x

#57966 geo/geomfn: fix SIGFPE in ST_FrechetDistance for very small densifyFrac
  docs/generated/sql/functions.md
  pkg/geo/geomfn/distance.go
  pkg/geo/geomfn/distance_test.go
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community, X-blathers-triaged

#56529 server: delete node status entries during decommissioning
  docs/generated/http/full.md
  docs/generated/settings/settings.html
  pkg/cli/interactive_tests/test_demo_node_cmds.tcl
  pkg/clusterversion/cockroach_versions.go
  pkg/clusterversion/key_string.go
  pkg/kv/BUILD.bazel
  pkg/kv/batch.go
  pkg/kv/client_test.go
  pkg/kv/db.go
  pkg/kv/db_test.go
  pkg/kv/kvserver/batcheval/cmd_conditional_put.go
  pkg/roachpb/api.go
  pkg/roachpb/api.pb.go
  pkg/roachpb/api.proto
  pkg/server/BUILD.bazel
  pkg/server/decommission_test.go
  pkg/server/node.go
  pkg/server/server.go
  pkg/server/serverpb/status.pb.go
  pkg/server/serverpb/status.proto
  pkg/server/status/BUILD.bazel
  pkg/server/status/recorder.go
  pkg/server/testserver.go
Labels: A-multiregion, O-community, X-blathers-triaged

#55065 kubernetes: move to rbac.authorization.k8s.io/v1
  cloud/kubernetes/bring-your-own-certs/cockroachdb-statefulset.yaml
  cloud/kubernetes/cockroachdb-statefulset-secure.yaml
  cloud/kubernetes/multiregion/cockroachdb-statefulset-secure.yaml
  cloud/kubernetes/multiregion/eks/cockroachdb-statefulset-secure-eks.yaml
  cloud/kubernetes/multiregion/external-name-svc.yaml
  cloud/kubernetes/performance/cockroachdb-daemonset-secure.yaml
  cloud/kubernetes/performance/cockroachdb-statefulset-secure.yaml
  cloud/kubernetes/prometheus/prometheus.yaml
Labels: O-community, X-blathers-untriaged

#58087 protoreflect,types,cli,builtins: fix json for types, plumb emitDefaults
  docs/generated/sql/functions.md
  pkg/cli/debug.go
  pkg/cli/decode.go
  pkg/cli/decode_test.go
  pkg/sql/logictest/logic.go
  pkg/sql/protoreflect/BUILD.bazel
  pkg/sql/protoreflect/utils_test.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/tests/repair_test.go
  pkg/sql/types/BUILD.bazel
  pkg/sql/types/types_jsonpb.go
  pkg/testutils/lint/lint_test.go
Labels: backport-20.2.x

#57922 release-20.2: sql: fix bug in temp object cleaner
  pkg/sql/temporary_schema.go
  pkg/sql/temporary_schema_test.go
Labels: backport-20.1.x

#57837 sql: Add information_schema.session_variables table
  pkg/sql/catalog/catconstants/constants.go
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/vtable/information_schema.go
Labels: O-community, X-blathers-triaged

#58208 sql: fix crash when explaining a constrained virtual table scan
  pkg/sql/explain_plan.go
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/exec/execbuilder/testdata/scalar
  pkg/sql/opt/exec/explain/emit.go
  pkg/sql/rowenc/index_encoding.go
Labels: backport-20.2.x

#58221 sql: catch panics from SHOW STATISTICS code
  pkg/sql/show_stats.go
  pkg/sql/stats/json.go
Labels: backport-20.1.x, backport-20.2.x

#58210 release-20.2: sql: safeguard against nil fetcher in GetBytesRead
  pkg/sql/row/kv_fetcher.go
Labels: backport-20.1.x

#58153 sql: fix crash with deletes in edge cases
  pkg/sql/backfill.go
  pkg/sql/logictest/testdata/logic_test/alter_primary_key
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/opt_exec_factory.go
  pkg/sql/row/deleter.go
  pkg/sql/row/updater.go
  pkg/sql/truncate.go
Labels: backport-20.1.x, backport-20.2.x

#58251 sql: fix a panic when showing statistics on a table with enums
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/show_stats.go
  pkg/sql/stats/json.go
Labels: O-community, X-blathers-triaged

#58085 opt: extend SplitScanIntoUnionScans to handle longer keys
  pkg/sql/opt/constraint/key.go
  pkg/sql/opt/constraint/span.go
  pkg/sql/opt/constraint/span_test.go
  pkg/sql/opt/constraint/spans.go
  pkg/sql/opt/constraint/spans_test.go
  pkg/sql/opt/exec/execbuilder/testdata/limit
  pkg/sql/opt/xform/limit_funcs.go
  pkg/sql/opt/xform/testdata/rules/limit
Labels: O-community

#58207 coldata: generate vec.eg.go within the bazel sandbox
  pkg/col/coldata/BUILD.bazel
  pkg/col/coldata/vec.eg.go
  pkg/col/coldata/vec_tmpl.go
Labels: O-community, X-blathers-untriaged

#58321 opt: simplify IS filters for selects and joins
  pkg/sql/opt/memo/testdata/stats/join
  pkg/sql/opt/norm/rules/join.opt
  pkg/sql/opt/norm/rules/select.opt
  pkg/sql/opt/norm/select_funcs.go
  pkg/sql/opt/norm/testdata/rules/join
  pkg/sql/opt/norm/testdata/rules/select
Labels: O-community

#56965 dev: introduce a general purpose dev-tool for crdb engineers
  Makefile
  pkg/cmd/dev/BUILD.bazel
  pkg/cmd/dev/bench.go
  pkg/cmd/dev/build.go
  pkg/cmd/dev/generate.go
  pkg/cmd/dev/lint.go
  pkg/cmd/dev/main.go
  pkg/cmd/dev/test.go
  pkg/cmd/dev/util.go
Labels: A-build-system
