Repository cockroachdb/cockroach, pull requests merged in 2020-11, with the labels that each got.

#55563 release-20.2: rowexec: fix metadata propagation in zigzag joiner
  pkg/sql/colflow/colbatch_scan_test.go
  pkg/sql/rowexec/interleaved_reader_joiner_test.go
  pkg/sql/rowexec/inverted_joiner_test.go
  pkg/sql/rowexec/joinreader_test.go
  pkg/sql/rowexec/processors_test.go
  pkg/sql/rowexec/tablereader_test.go
  pkg/sql/rowexec/zigzagjoiner.go
  pkg/sql/rowexec/zigzagjoiner_test.go
  pkg/util/cancelchecker/cancel_checker.go
Labels: do-not-merge

#56080 importccl: add row_limit option for importing CSVs
  pkg/ccl/importccl/import_stmt.go
  pkg/ccl/importccl/import_stmt_test.go
  pkg/ccl/importccl/read_import_base.go
  pkg/ccl/importccl/read_import_csv.go
  pkg/roachpb/io-formats.pb.go
  pkg/roachpb/io-formats.proto
Labels: A-bulkio

#55945 sql: create event log entry for role events
  pkg/server/admin_test.go
  pkg/sql/alter_role.go
  pkg/sql/create_role.go
  pkg/sql/drop_role.go
  pkg/sql/event_log.go
  pkg/sql/logictest/testdata/logic_test/event_log
  pkg/ui/src/util/eventTypes.ts
  pkg/ui/src/util/events.ts
Labels: O-community

#56246 bazel: moving out c-deps from Root BUILD
  BUILD.bazel
  c-deps/BUILD.bazel
  pkg/cli/BUILD.bazel
  pkg/geo/geoproj/BUILD.bazel
  pkg/server/status/BUILD.bazel
  pkg/storage/BUILD.bazel
Labels: O-community

#56198 geo/geomfn: implement ST_TransScale({geometry,float8,float8,float8,float8})
  docs/generated/sql/functions.md
  pkg/geo/geomfn/affine_transforms.go
  pkg/geo/geomfn/affine_transforms_test.go
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community, X-blathers-triaged

#56021 backupccl: fix bug where restore would try to start rolled-back jobs
  pkg/ccl/backupccl/restore_job.go
Labels: backport-20.1.x

#56126 changefeedccl: support skipping client-side TLS verification of Kafka
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/options.go
  pkg/ccl/changefeedccl/sink.go
Labels: backport-20.2.x

#56296 builtins: implement regr_intercept, regr_r2, and regr_slope aggregation functions
  docs/generated/sql/aggregates.md
  pkg/sql/distsql/columnar_operators_test.go
  pkg/sql/execinfrapb/processors_sql.pb.go
  pkg/sql/execinfrapb/processors_sql.proto
  pkg/sql/logictest/testdata/logic_test/aggregate
  pkg/sql/logictest/testdata/logic_test/distsql_agg
  pkg/sql/opt/exec/execbuilder/testdata/aggregate
  pkg/sql/opt/operator.go
  pkg/sql/opt/ops/scalar.opt
  pkg/sql/opt/optbuilder/groupby.go
  pkg/sql/opt/optbuilder/testdata/aggregate
  pkg/sql/sem/builtins/aggregate_builtins.go
  pkg/sql/sem/builtins/aggregate_builtins_test.go
  pkg/sql/sem/tree/casts.go
  pkg/sql/sem/tree/eval.go
  scripts/crlogictest.vim
Labels: O-community

#56242 roachpb: add test for Key.Format with non-UTF8 characters
  pkg/roachpb/data_test.go
Labels: O-community, X-blathers-triaged

#56585 builtins: implement regr_sxx, regr_sxy, and regr_syy aggregation functions
  docs/generated/sql/aggregates.md
  pkg/sql/distsql/columnar_operators_test.go
  pkg/sql/execinfrapb/processors_sql.pb.go
  pkg/sql/execinfrapb/processors_sql.proto
  pkg/sql/logictest/testdata/logic_test/aggregate
  pkg/sql/logictest/testdata/logic_test/distsql_agg
  pkg/sql/opt/exec/execbuilder/testdata/aggregate
  pkg/sql/opt/operator.go
  pkg/sql/opt/ops/scalar.opt
  pkg/sql/opt/optbuilder/groupby.go
  pkg/sql/opt/optbuilder/testdata/aggregate
  pkg/sql/sem/builtins/aggregate_builtins.go
  pkg/sql/sem/builtins/aggregate_builtins_test.go
  scripts/crlogictest.vim
Labels: O-community

#56189 Makefile: fix output for useful variables
  Makefile
Labels: O-community, X-blathers-untriaged

#55961 opt: transform InnerJoin + Values to Project
  pkg/sql/opt/memo/testdata/logprops/join
  pkg/sql/opt/memo/testdata/stats/join
  pkg/sql/opt/norm/join_funcs.go
  pkg/sql/opt/norm/rules/join.opt
  pkg/sql/opt/norm/testdata/rules/decorrelate
  pkg/sql/opt/norm/testdata/rules/inline
  pkg/sql/opt/norm/testdata/rules/join
  pkg/sql/opt/norm/testdata/rules/limit
  pkg/sql/opt/norm/testdata/rules/reject_nulls
  pkg/sql/opt/norm/testdata/rules/scalar
  pkg/sql/opt/norm/testdata/rules/with
Labels: O-community

#55325 ui: Transactions link between Sessions and Statements
  pkg/ui/src/views/app/components/layoutSidebar/index.tsx
Labels: backport-20.2.x

#56619 geo: add limit to quad_segs for ST_Buffer, points for ST_Interpolate
  pkg/geo/geo.go
  pkg/geo/geogfn/segmentize.go
  pkg/geo/geogfn/segmentize_test.go
  pkg/geo/geomfn/buffer.go
  pkg/geo/geomfn/buffer_test.go
  pkg/geo/geomfn/linear_reference.go
  pkg/geo/geomfn/linear_reference_test.go
  pkg/geo/geomfn/segmentize.go
  pkg/geo/geomfn/segmentize_test.go
  pkg/geo/geosegmentize/geosegmentize.go
Labels: backport-20.2.x

#56324 importccl: always ignore PGDUMP statements in ignorelist
  pkg/ccl/importccl/import_stmt_test.go
  pkg/ccl/importccl/read_import_pgdump.go
Labels: backport-20.2.x

#56768 sql: fix panic when getting support bundle
  pkg/sql/explain_bundle.go
Labels: backport-20.1.x, backport-20.2.x

#55500 release-20.2: jobs: add metrics around job state changes
  pkg/jobs/jobs_test.go
  pkg/jobs/jobspb/wrap.go
  pkg/jobs/metrics.go
  pkg/jobs/registry.go
  pkg/ts/catalog/chart_catalog.go
  pkg/util/metric/registry.go
  pkg/util/metric/registry_test.go
Labels: O-sre

#56708 util/hlc: add lock-free Clock.Update() fast path for old wall times
  pkg/util/hlc/hlc.go
  pkg/util/hlc/hlc_test.go
Labels: O-community, X-blathers-triaged

#55166 server: ensure settings are up-to-date.
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/keys/keys.go
  pkg/keys/keys_test.go
  pkg/keys/printer.go
  pkg/keys/printer_test.go
  pkg/kv/kvserver/store.go
  pkg/server/BUILD.bazel
  pkg/server/init.go
  pkg/server/server.go
  pkg/server/settings_cache.go
  pkg/server/settings_cache_test.go
  pkg/server/settingsworker.go
Labels: O-community, X-blathers-triaged

#55513 sql: properly handle cases where marking a job as canceled fails
  pkg/jobs/registry.go
  pkg/jobs/registry_external_test.go
  pkg/jobs/registry_test.go
  pkg/jobs/testing_knobs.go
  pkg/jobs/update.go
  pkg/server/server_sql.go
  pkg/sql/schema_changer.go
  pkg/sql/schema_changer_test.go
Labels: backport-20.2.x

#56653 sql: Create empty table pg_opclass to improve postgress compatibility
  pkg/sql/catalog/catconstants/constants.go
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/pg_catalog.go
  pkg/sql/vtable/pg_catalog.go
Labels: O-community, X-blathers-triaged

#56827 sql: Enabled correct pg_class.relPersistence for temporary tables
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: O-community, X-blathers-untriaged

#57041 jobs: paginate job deletions
  pkg/jobs/registry.go
  pkg/jobs/registry_test.go
Labels: backport-20.2.x

#54943 ui: Update empty states for table components
  pkg/ui/assets/emptyState/empty-list-results.svg
  pkg/ui/assets/emptyState/empty-table-results.svg
  pkg/ui/assets/emptyState/magnifying-glass.svg
  pkg/ui/assets/emptyState/not-found-404.svg
  pkg/ui/src/components/anchor/anchor.tsx
  pkg/ui/src/components/table/table.styl
  pkg/ui/src/components/table/table.tsx
  pkg/ui/src/interfaces/assets.d.ts
  pkg/ui/src/views/jobs/jobTable.tsx
  pkg/ui/src/views/reports/containers/statementDiagnosticsHistory/index.tsx
  pkg/ui/src/views/sessions/sessionsPage.tsx
  pkg/ui/src/views/shared/components/sortabletable/index.tsx
  pkg/ui/src/views/shared/components/sortabletable/sortabletable.stories.tsx
  pkg/ui/src/views/shared/components/sortedtable/index.tsx
  pkg/ui/src/views/statements/diagnostics/diagnosticsView.spec.tsx
  pkg/ui/src/views/statements/diagnostics/diagnosticsView.tsx
Labels: backport-20.2.x

#56975 sql: fix for column type for pg_constraint.confkey to smallint[]
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: O-community, X-blathers-untriaged

#56822 builtins: implement regr_count
  docs/generated/sql/aggregates.md
  pkg/sql/distsql/columnar_operators_test.go
  pkg/sql/execinfrapb/processors_sql.pb.go
  pkg/sql/execinfrapb/processors_sql.proto
  pkg/sql/logictest/testdata/logic_test/aggregate
  pkg/sql/logictest/testdata/logic_test/distsql_agg
  pkg/sql/opt/exec/execbuilder/testdata/aggregate
  pkg/sql/opt/norm/general_funcs.go
  pkg/sql/opt/norm/rules/groupby.opt
  pkg/sql/opt/norm/testdata/rules/agg
  pkg/sql/opt/norm/testdata/rules/groupby
  pkg/sql/opt/operator.go
  pkg/sql/opt/ops/scalar.opt
  pkg/sql/opt/optbuilder/groupby.go
  pkg/sql/opt/optbuilder/testdata/aggregate
  pkg/sql/sem/builtins/aggregate_builtins.go
  pkg/sql/sem/builtins/aggregate_builtins_test.go
  scripts/crlogictest.vim
Labels: O-community, X-blathers-untriaged

#56953 sql: Add information_schema.character_sets table
  pkg/sql/catalog/catconstants/constants.go
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/vtable/information_schema.go
Labels: O-community, X-blathers-triaged
