Repository cockroachdb/cockroach, pull requests merged in 2020-08, with the labels that each got.

#52045 release-20.1: rowflow: make routers propagate errors to all non-closed outputs
  pkg/sql/rowflow/routers.go
  pkg/sql/rowflow/routers_test.go
Labels: backport-19.1.x, backport-19.2.x

#51483 geo/geomfn: implement ST_Translate
  docs/generated/sql/functions.md
  pkg/geo/geomfn/translate.go
  pkg/geo/geomfn/translate_test.go
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community, X-blathers-untriaged

#52538 sql: new statement `SHOW ENUMS`
  docs/generated/sql/bnf/show_var.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/delegate/delegate.go
  pkg/sql/delegate/show_enums.go
  pkg/sql/logictest/testdata/logic_test/enums
  pkg/sql/parser/help_test.go
  pkg/sql/parser/parse_test.go
  pkg/sql/parser/sql.y
  pkg/sql/sem/tree/show.go
  pkg/sql/sem/tree/stmt.go
Labels: O-community, X-blathers-triaged

#52562 sql: strip tenant ID from key before calling IndexKeyEquivSignature
  pkg/sql/logictest/testdata/logic_test/cascade
  pkg/sql/logictest/testdata/logic_test/delete
  pkg/sql/row/fetcher.go
  pkg/sql/sqlbase/index_encoding.go
Labels: A-multitenancy

#52350 geo/geomfn: implement ST_Scale
  docs/generated/sql/functions.md
  pkg/geo/geomfn/scale.go
  pkg/geo/geomfn/scale_test.go
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community

#52203 sql: improve SHOW TABLES to show row count
  pkg/cli/zip_test.go
  pkg/server/admin.go
  pkg/sql/catalog/catconstants/constants.go
  pkg/sql/crdb_internal.go
  pkg/sql/delegate/show_tables.go
  pkg/sql/logictest/testdata/logic_test/alter_table_mixed_19.2_20.1
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/drop_index
  pkg/sql/logictest/testdata/logic_test/drop_table
  pkg/sql/logictest/testdata/logic_test/drop_view
  pkg/sql/logictest/testdata/logic_test/fk
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/namespace
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/rename_database
  pkg/sql/logictest/testdata/logic_test/rename_table
  pkg/sql/logictest/testdata/logic_test/rename_view
  pkg/sql/logictest/testdata/logic_test/role
  pkg/sql/logictest/testdata/logic_test/save_table
  pkg/sql/logictest/testdata/logic_test/select_search_path
  pkg/sql/logictest/testdata/logic_test/set
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/logictest/testdata/logic_test/system
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/pgwire/pgwire_test.go
Labels: O-community, X-blathers-triaged

#52564 sql: remove usage of OptionalNodeIDErr in createPlanForInterleavedJoin
  pkg/sql/distsql_plan_join.go
  pkg/sql/logictest/testdata/logic_test/interleaved_join
Labels: A-multitenancy

#52589 server: add end-to-end tenant authentication test
  pkg/base/test_server_args.go
  pkg/ccl/kvccl/kvtenantccl/proxy.go
  pkg/ccl/serverccl/server_sql_test.go
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvclient/kvcoord/range_cache.go
  pkg/kv/kvclient/kvcoord/range_iter.go
  pkg/roachpb/errors.go
  pkg/rpc/context.go
  pkg/server/config.go
  pkg/server/server_sql.go
  pkg/server/testserver.go
  pkg/util/grpcutil/grpc_util.go
Labels: A-multitenancy

#52592 kv: reject admin KV requests from tenant SQL processes
  pkg/ccl/kvccl/kvtenantccl/proxy.go
  pkg/ccl/kvccl/kvtenantccl/proxy_test.go
  pkg/ccl/logictestccl/testdata/logic_test/tenant_unsupported
  pkg/rpc/auth_tenant.go
  pkg/rpc/auth_test.go
  pkg/sql/backfill.go
  pkg/sql/logictest/testdata/logic_test/select_index_span_ranges
  pkg/sql/logictest/testdata/logic_test/subquery
  pkg/sql/opt_exec_factory.go
  pkg/sql/scatter.go
  pkg/sql/sem/builtins/generator_builtins.go
Labels: A-multitenancy

#52599 kv/kvtenant: rename Proxy to Connector
  pkg/ccl/kvccl/kvtenantccl/connector.go
  pkg/ccl/kvccl/kvtenantccl/connector_test.go
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/kv/kvclient/kvtenant/proxy.go
  pkg/server/server_sql.go
  pkg/server/testserver.go
Labels: A-multitenancy

#52560 sql: skip tenant prefix in spans in EXPLAIN
  pkg/sql/conn_executor_exec.go
  pkg/sql/explain_plan.go
  pkg/sql/logictest/testdata/logic_test/alter_primary_key
  pkg/sql/logictest/testdata/logic_test/family
  pkg/sql/plan.go
Labels: A-multitenancy

#52621 flowinfra: replace ConcurrentExecution with ConcurrentTxnUse
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/distsql/server.go
  pkg/sql/distsql_running.go
  pkg/sql/execinfra/base.go
  pkg/sql/execinfra/processorsbase.go
  pkg/sql/flowinfra/flow.go
  pkg/sql/flowinfra/flow_scheduler_test.go
  pkg/sql/logictest/testdata/logic_test/enums
  pkg/sql/logictest/testdata/logic_test/owner
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/rowexec/processors_test.go
  pkg/sql/rowexec/sample_aggregator.go
  pkg/sql/rowexec/sampler.go
Labels: A-multitenancy

#52677 logictest: run SQLLite logic tests with 3node-tenant
  build/teamcity-sqllogictest.sh
  pkg/ccl/logictestccl/logic_test.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/logic_test.go
Labels: A-multitenancy

#52641 authors: add jramos-crl to authors
  AUTHORS
Labels: O-community, X-blathers-untriaged

#52680 logictest: swap directives with default config when possible
  pkg/sql/logictest/testdata/logic_test/as_of
  pkg/sql/logictest/testdata/logic_test/ccl
  pkg/sql/logictest/testdata/logic_test/database
  pkg/sql/logictest/testdata/logic_test/distsql_automatic_stats
  pkg/sql/logictest/testdata/logic_test/distsql_event_log
  pkg/sql/logictest/testdata/logic_test/distsql_join
  pkg/sql/logictest/testdata/logic_test/drop_database
  pkg/sql/logictest/testdata/logic_test/drop_index
  pkg/sql/logictest/testdata/logic_test/drop_table
  pkg/sql/logictest/testdata/logic_test/drop_user
  pkg/sql/logictest/testdata/logic_test/drop_view
  pkg/sql/logictest/testdata/logic_test/edge
  pkg/sql/logictest/testdata/logic_test/explain_analyze
  pkg/sql/logictest/testdata/logic_test/fk
  pkg/sql/logictest/testdata/logic_test/grant_database
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/interleaved_join
  pkg/sql/logictest/testdata/logic_test/locality
  pkg/sql/logictest/testdata/logic_test/notice
  pkg/sql/logictest/testdata/logic_test/partitioning
  pkg/sql/logictest/testdata/logic_test/reset
  pkg/sql/logictest/testdata/logic_test/save_table
  pkg/sql/logictest/testdata/logic_test/scatter
  pkg/sql/logictest/testdata/logic_test/target_names
  pkg/sql/logictest/testdata/logic_test/txn_as_of
  pkg/sql/logictest/testdata/logic_test/txn_retry
  pkg/sql/logictest/testdata/logic_test/txn_stats
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/logictest/testdata/logic_test/update_from
  pkg/sql/logictest/testdata/logic_test/vectorize_shutdown
  pkg/sql/logictest/testdata/logic_test/vectorize_sqllite
  pkg/sql/logictest/testdata/logic_test/vectorize_types
  pkg/sql/logictest/testdata/logic_test/vectorize_unsupported
  pkg/sql/logictest/testdata/logic_test/window
  pkg/sql/logictest/testdata/logic_test/zigzag_join
Labels: A-multitenancy

#52765 logictest: add 3node-tenant directive to logictests with non-default configs
  pkg/ccl/logictestccl/logic_test.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/column_families
  pkg/sql/logictest/testdata/logic_test/inv_stats
  pkg/sql/logictest/testdata/logic_test/orms
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/prepare
  pkg/sql/logictest/testdata/logic_test/role
  pkg/sql/logictest/testdata/logic_test/statement_statistics
  pkg/sql/logictest/testdata/logic_test/user
  pkg/sql/logictest/testdata/logic_test/vectorize
Labels: A-multitenancy

#52834 geo/geomfn: implement ST_Reverse
  docs/generated/sql/functions.md
  pkg/geo/geomfn/reverse.go
  pkg/geo/geomfn/reverse_test.go
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community, X-blathers-triaged

#52598 kv: mask system config gossip info in tenant GossipSubscription stream
  pkg/config/system_mask.go
  pkg/config/system_test.go
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/server/node.go
Labels: A-multitenancy

#52508 rpc: serve tenants and node using single cert and port
  c-deps/libroach/protos/roachpb/metadata.pb.cc
  c-deps/libroach/protos/roachpb/metadata.pb.h
  pkg/base/addr_validation.go
  pkg/base/addr_validation_test.go
  pkg/base/config.go
  pkg/cli/cliflags/flags.go
  pkg/cli/flags.go
  pkg/cli/flags_test.go
  pkg/cli/mt_cert.go
  pkg/cmd/roachtest/multitenant.go
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/roachpb/metadata.go
  pkg/roachpb/metadata.pb.go
  pkg/roachpb/metadata.proto
  pkg/rpc/auth.go
  pkg/rpc/auth_tenant.go
  pkg/rpc/auth_test.go
  pkg/rpc/context.go
  pkg/rpc/tls.go
  pkg/security/auth.go
  pkg/security/certificate_loader.go
  pkg/security/certificate_manager.go
  pkg/security/certs.go
  pkg/security/certs_tenant_test.go
  pkg/security/certs_test.go
  pkg/security/securitytest/embedded.go
  pkg/security/securitytest/test_certs/client-tenant.10.crt
  pkg/security/securitytest/test_certs/client-tenant.10.key
  pkg/security/securitytest/test_certs/client-tenant.11.crt
  pkg/security/securitytest/test_certs/client-tenant.11.key
  pkg/security/securitytest/test_certs/client-tenant.20.crt
  pkg/security/securitytest/test_certs/client-tenant.20.key
  pkg/security/tls.go
  pkg/security/tls_test.go
  pkg/security/x509.go
  pkg/server/authentication_test.go
  pkg/server/drain.go
  pkg/server/grpc_server.go
  pkg/server/node.go
  pkg/server/server.go
  pkg/server/server_test.go
  pkg/server/status/recorder.go
  pkg/server/status/recorder_test.go
  pkg/server/testserver.go
  pkg/testutils/serverutils/test_server_shim.go
Labels: A-multitenancy

#52096 backupccl: include all tenants in full cluster backup
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/targets.go
  pkg/cmd/roachtest/versionupgrade.go
  pkg/sqlmigrations/migrations.go
Labels: A-multitenancy

#52639 backupccl: fix flake in backup stats tests
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/full_cluster_backup_restore_test.go
  pkg/ccl/backupccl/helpers_test.go
Labels: backport-19.2.x, backport-20.1.x

#52818 gcjob: handle missing tables when refreshing status
  pkg/sql/gcjob/gc_job.go
  pkg/sql/gcjob/refresh_statuses.go
  pkg/sql/gcjob_test/gc_job_test.go
Labels: A-schema-descriptors, backport-20.1.x

#51076 builder: upgrade to autouseradd 1.2.0
  build/builder.sh
  build/builder/Dockerfile
Labels: O-community

#52984 sql: make RemoveIndexZoneConfigs a noop when run on behalf of a tenant
  pkg/sql/logictest/testdata/logic_test/alter_primary_key
  pkg/sql/schema_changer.go
  pkg/sql/set_zone_config.go
Labels: A-multitenancy

#53020 logictest: move remaining kv trace assertions to execbuilder tests
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/logictest/testdata/logic_test/select_index
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
  pkg/sql/opt/exec/execbuilder/testdata/select_index
Labels: A-multitenancy

#53048 logictest: skip cascade if run with 3node-tenant
  pkg/sql/logictest/testdata/logic_test/cascade
Labels: A-multitenancy

#52622 cli: add debug doctor command
  pkg/cli/cli_test.go
  pkg/cli/debug.go
  pkg/cli/doctor.go
  pkg/cli/doctor_test.go
  pkg/cli/flags.go
  pkg/cli/testdata/doctor/debugzip/system.descriptor.txt
  pkg/cli/testdata/doctor/testcluster
  pkg/cli/testdata/doctor/testzipdir
  pkg/sql/doctor/doctor.go
  pkg/sql/doctor/doctor_test.go
  pkg/sql/sqlbase/descriptor.go
  pkg/sql/sqlbase/structured.go
  pkg/sql/sqlbase/structured_test.go
  pkg/sql/sqlbase/table_desc.go
Labels: O-community

#53244 geo/geomfn: implement ST_RemovePoint
  docs/generated/sql/functions.md
  pkg/geo/geomfn/linestring.go
  pkg/geo/geomfn/linestring_test.go
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community, X-blathers-triaged

#53636 geo/geomfn: implement ST_SymDifference
  docs/generated/sql/functions.md
  pkg/geo/geomfn/topology_operations.go
  pkg/geo/geomfn/topology_operations_test.go
  pkg/geo/geos/geos.cc
  pkg/geo/geos/geos.go
  pkg/geo/geos/geos.h
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community, X-blathers-triaged
