Repository cockroachdb/cockroach, pull requests merged in 2020-04, with the labels that each got.

#46749 opt: telemetry improvements (index hints, joins, FKs)
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/telemetry
  pkg/sql/opt/ops/relational.opt
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/opt/optbuilder/mutation_builder_fk.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/telemetry.go
  pkg/sql/sqltelemetry/opt.go
  pkg/sql/sqltelemetry/planning.go
Labels: backport-20.1

#46913 demo: display connection urls for nodes in the demo cluster
  pkg/cli/demo.go
  pkg/cli/interactive_tests/test_demo.tcl
Labels: backport-20.1

#46872 sql: make iteration over all databases take fewer round trips
  pkg/sql/table.go
Labels: backport-19.2.x, backport-20.1

#46934 opt: reduce allocations in optbuilder
  pkg/sql/opt/optbuilder/alter_table.go
  pkg/sql/opt/optbuilder/create_table.go
  pkg/sql/opt/optbuilder/create_view.go
  pkg/sql/opt/optbuilder/explain.go
  pkg/sql/opt/optbuilder/export.go
  pkg/sql/opt/optbuilder/misc_statements.go
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/opt/optbuilder/select.go
Labels: backport-20.1

#46952 kv: batch ranged intent resolution
  pkg/internal/client/requestbatcher/batcher.go
  pkg/internal/client/requestbatcher/batcher_test.go
  pkg/kv/client_test.go
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
  pkg/kv/kvserver/intentresolver/intent_resolver.go
  pkg/kv/kvserver/intentresolver/intent_resolver_test.go
  pkg/roachpb/api.go
  pkg/roachpb/api.pb.go
  pkg/roachpb/api.proto
  pkg/roachpb/api_test.go
  pkg/roachpb/batch.go
  pkg/sql/conn_io_test.go
  pkg/sql/pgwire/conn_test.go
  pkg/testutils/error.go
Labels: release-blocker

#45149 cli,server: make quit/drain more friendly to clusters with many ranges
  docs/generated/settings/settings.html
  pkg/cli/cli_test.go
  pkg/cli/cliflags/flags.go
  pkg/cli/context.go
  pkg/cli/demo_cluster.go
  pkg/cli/flags.go
  pkg/cli/interactive_tests/test_missing_log_output.tcl
  pkg/cli/node.go
  pkg/cli/quit.go
  pkg/cli/start.go
  pkg/cmd/roachtest/quit.go
  pkg/cmd/roachtest/registry.go
  pkg/kv/kvserver/client_raft_test.go
  pkg/kv/kvserver/client_replica_test.go
  pkg/kv/kvserver/helpers_test.go
  pkg/kv/kvserver/node_liveness.go
  pkg/kv/kvserver/node_liveness_test.go
  pkg/kv/kvserver/replica_proposal.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/store.go
  pkg/server/admin.go
  pkg/server/drain.go
  pkg/server/drain_test.go
  pkg/server/grpc_server.go
  pkg/server/node.go
  pkg/server/server.go
  pkg/server/serverpb/admin.pb.go
  pkg/server/serverpb/admin.proto
  pkg/server/testserver.go
  pkg/sql/distsql/server.go
  pkg/sql/distsql/sync_flow_after_drain_test.go
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/flowinfra/flow_registry.go
  pkg/sql/flowinfra/flow_registry_test.go
  pkg/sql/lease.go
  pkg/sql/lease_test.go
  pkg/sql/pgwire/helpers_test.go
  pkg/sql/pgwire/pgwire_test.go
  pkg/sql/pgwire/server.go
Labels: backport-19.1.x, backport-19.2.x, docs-todo

#47165 execerror: catch panics from sql/colcontainer package
  pkg/sql/colexec/execerror/error.go
  pkg/testutils/lint/lint_test.go
Labels: backport-20.1

#47492 kv: respect exhausted key limit during ranged intent resolution
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvserver/replica_evaluate.go
  pkg/kv/kvserver/replica_evaluate_test.go
  pkg/kv/kvserver/replica_test.go
  pkg/storage/mvcc.go
  pkg/storage/mvcc_history_test.go
Labels: release-blocker

#47500 sql: fix panic when SHOW RANGES is called with a virtual table
  pkg/sql/delegate/show_range_for_row.go
  pkg/sql/delegate/show_ranges.go
  pkg/sql/logictest/testdata/logic_test/ranges
Labels: backport-19.2.x, backport-20.1

#47466 rowexec: release buckets from hash aggregator eagerly
  pkg/cmd/roachtest/alterpk.go
  pkg/sql/rowexec/aggregator.go
Labels: backport-19.1.x, backport-19.2.x, backport-20.1

#46778 sqltelemetry: add CANCEL QUERIES and CANCEL SESSIONS telemetry
  pkg/sql/opt/exec/execbuilder/statement.go
  pkg/sql/sqltelemetry/planning.go
Labels: backport-20.1

#47641 sql: introduce a default transaction priority setting
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/prepare
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/logictest/testdata/logic_test/txn
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/sem/tree/txn.go
  pkg/sql/sessiondata/session_data.go
  pkg/sql/set_default_isolation.go
  pkg/sql/vars.go
Labels: docs-todo

#47709 opt: fix in-place modification of window definition in optbuilder
  pkg/sql/logictest/testdata/logic_test/views
  pkg/sql/opt/optbuilder/scope.go
  pkg/sql/sem/tree/select.go
Labels: backport-19.2.x, backport-20.1

#47755 logictest: add 3node-tenant configuration
  pkg/server/server_sql.go
  pkg/server/testserver.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/tenant_unsupported
Labels: A-multitenancy

#47951 sql: fix explain output for subqueries/postqueries
  pkg/sql/explain_plan.go
  pkg/sql/opt/exec/execbuilder/testdata/insert
  pkg/sql/opt/exec/execbuilder/testdata/scalar
  pkg/sql/opt/exec/execbuilder/testdata/srfs
  pkg/sql/opt/exec/execbuilder/testdata/subquery
  pkg/sql/opt/exec/execbuilder/testdata/update
  pkg/sql/opt/exec/execbuilder/testdata/upsert
  pkg/sql/opt/exec/execbuilder/testdata/window
  pkg/sql/opt/exec/execbuilder/testdata/with
  pkg/sql/testdata/explain_tree
Labels: backport-20.1

#47972 sql: mark use of Gossip as deprecated
  pkg/ccl/backupccl/backup_job.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/changefeedccl/bench_test.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/kvfeed/scanner.go
  pkg/gossip/gossip.go
  pkg/server/server.go
  pkg/server/server_sql.go
  pkg/server/testserver.go
  pkg/sql/alter_table.go
  pkg/sql/cancel_queries.go
  pkg/sql/cancel_sessions.go
  pkg/sql/conn_executor.go
  pkg/sql/crdb_internal.go
  pkg/sql/distsql/server.go
  pkg/sql/distsql_physical_planner.go
  pkg/sql/distsql_plan_csv.go
  pkg/sql/exec_util.go
  pkg/sql/execinfra/server_config.go
  pkg/sql/gcjob/gc_job.go
  pkg/sql/gcjob/refresh_statuses.go
  pkg/sql/logictest/testdata/logic_test/tenant_unsupported
  pkg/sql/opt_catalog.go
  pkg/sql/pgwire/pgerror/errors.go
  pkg/sql/relocate.go
  pkg/sql/rowexec/sample_aggregator.go
  pkg/sql/rowexec/sample_aggregator_test.go
  pkg/sql/set_zone_config.go
  pkg/sql/temporary_schema.go
  pkg/util/errorutil/tenant.go
  pkg/util/errorutil/tenant_deprecated_wrapper.go
Labels: A-multitenancy

#48073 cli/zip: skip over decommissioned nodes
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/partial2
  pkg/cli/testdata/zip/specialnames
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/unavailable
  pkg/cli/zip.go
  pkg/cli/zip_test.go
Labels: backport-19.2.x, backport-20.1

#48096 cli/zip: avoid buffering SQL data in RAM
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/unavailable
  pkg/cli/zip.go
Labels: backport-19.2.x, backport-20.1
