Repository cockroachdb/cockroach, pull requests merged in 2021-04, with the labels that each got.

#62658 log,importccl,backupccl: add event logs for import and restore jobs
  Makefile
  docs/generated/eventlog.md
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/testutils.go
  pkg/ccl/importccl/BUILD.bazel
  pkg/ccl/importccl/import_stmt.go
  pkg/ccl/importccl/import_stmt_test.go
  pkg/jobs/jobs.go
  pkg/sql/event_log.go
  pkg/ui/src/util/eventTypes.ts
  pkg/ui/src/util/events.ts
  pkg/util/log/eventpb/BUILD.bazel
  pkg/util/log/eventpb/eventlog_channels_generated.go
  pkg/util/log/eventpb/events.go
  pkg/util/log/eventpb/events.pb.go
  pkg/util/log/eventpb/events.proto
  pkg/util/log/eventpb/gen.go
  pkg/util/log/eventpb/job_events.pb.go
  pkg/util/log/eventpb/job_events.proto
  pkg/util/log/eventpb/json_encode_generated.go
Labels: backport-21.1.x

#62921 opt: fix internal error when calculating stats for mutation passthrough cols
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/testdata/stats/update
Labels: backport-20.1.x, backport-20.2.x, backport-21.1.x

#62816 importccl: clear range when reverting IMPORT INTO of empty tables
  pkg/ccl/importccl/import_stmt.go
Labels: backport-20.2.x, backport-21.1.x

#62479 bazel: Expose bazel build info (tag, rev, utcTime, typ)
  .bazelrc.ci
  build-rev.sh
  pkg/build/BUILD.bazel
Labels: O-community, X-blathers-triaged

#62379 importccl,backupccl: create job record in planner txn
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/importccl/import_stmt.go
Labels: backport-21.1.x

#63037 ccl/changfeedccl: fix changefeed processors shutdown
  pkg/ccl/changefeedccl/changefeed_processors.go
Labels: backport-20.1.x, backport-20.2.x, backport-21.1.x

#59079 kv: fix wrong comment for RaftTransport.stats
  pkg/kv/kvserver/raft_transport.go
Labels: O-community, X-blathers-untriaged

#62572 backupccl: only backup public indexes
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/helpers_test.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_mid_schema_change_test.go
Labels: backport-19.2.x, backport-20.1.x, backport-20.2.x, backport-21.1.x

#63119 sql: fix drop schema bug which corrupts schemas using the name of the db
  pkg/sql/drop_schema.go
  pkg/sql/logictest/testdata/logic_test/schema
  pkg/sql/tests/rsg_test.go
  pkg/sql/tests/testdata/rsg/sql.y
Labels: backport-20.2.x, backport-21.1.x

#62279 backupccl: disallow cluster restore between tenants
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/helpers_test.go
  pkg/ccl/backupccl/restore_job.go
Labels: backport-21.1.x

#63194 opt: fix UPSERT error with REGIONAL BY ROW tables
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row
  pkg/sql/opt/optbuilder/insert.go
Labels: backport-21.1.x

#63052 sql: support alter column SET VISIBLE and NOT VISIBLE to unhide or hide column
  docs/generated/sql/bnf/alter_column.bnf
  docs/generated/sql/bnf/alter_table.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/ccl/importccl/import_stmt_test.go
  pkg/ccl/importccl/read_import_pgdump.go
  pkg/sql/alter_table.go
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/parser/sql.y
  pkg/sql/sem/tree/alter_table.go
  pkg/sql/sem/tree/stmt.go
Labels: O-community

#63137 uuid: fix parsing for different uuid formats
  pkg/acceptance/testdata/java/src/main/java/MainTest.java
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/logictest/testdata/logic_test/uuid
  pkg/util/uuid/codec.go
  pkg/util/uuid/codec_test.go
  pkg/util/uuid/uuid.go
Labels: O-community, X-blathers-triaged

#63326 sql: return a SQL Notice if "CREATE TYPE IF NOT EXISTS" command is used to create a type and the type's already existed.
  pkg/sql/create_type.go
  pkg/sql/logictest/testdata/logic_test/alter_type
Labels: O-community, X-blathers-triaged

#63121 backupccl: re-backup spans that come online during incremental backups
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/full_cluster_backup_restore_test.go
  pkg/ccl/backupccl/import_spans_test.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/targets.go
Labels: backport-20.1.x

#63302 raftentry: fix accidental no-op in truncateFrom
  pkg/kv/kvserver/raftentry/BUILD.bazel
  pkg/kv/kvserver/raftentry/cache.go
  pkg/kv/kvserver/raftentry/cache_test.go
  pkg/kv/kvserver/raftentry/ring_buffer.go
  pkg/kv/kvserver/raftentry/ring_buffer_test.go
  pkg/kv/kvserver/replica_raft.go
Labels: backport-20.1.x, backport-20.2.x, backport-21.1.x

#63404 sql/table: returns notice when table already exist in case of CREATE TABLE IF NOT EXISTS
  pkg/sql/create_table.go
  pkg/sql/logictest/testdata/logic_test/alter_table
Labels: O-community, X-blathers-triaged

#63493 sql,docs: hide UNIQUE WITHOUT INDEX from the docs
  docs/generated/sql/bnf/col_qualification.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  docs/generated/sql/bnf/table_constraint.bnf
  pkg/sql/parser/sql.y
Labels: backport-21.1.x

#63144 sql: refactoring virtualSchemaTable.allTableNames into undefinedTables
  pkg/sql/BUILD.bazel
  pkg/sql/information_schema.go
  pkg/sql/pg_catalog.go
  pkg/sql/pg_metadata_test.go
  pkg/sql/virtual_schema.go
  pkg/sql/virtual_schema_test.go
Labels: O-community

#63327 timeutil: Throw parsing error in case of wrong Julian date format
  pkg/util/timeutil/pgdate/BUILD.bazel
  pkg/util/timeutil/pgdate/field_extract.go
  pkg/util/timeutil/pgdate/field_extract_test.go
  pkg/util/timeutil/pgdate/fields.go
Labels: O-community, X-blathers-triaged

#63306 changefeedccl: disallow changfeeds on regional by row tables
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/validate.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/schemafeed/schematestutils/schema_test_utils.go
  pkg/ccl/changefeedccl/schemafeed/table_event_filter.go
  pkg/ccl/changefeedccl/schemafeed/table_event_filter_test.go
Labels: backport-21.1.x

#62440 builtins: add ulid functionality
  docs/generated/sql/functions.md
  pkg/BUILD.bazel
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/sem/builtins/BUILD.bazel
  pkg/sql/sem/builtins/builtins.go
  pkg/util/ulid/BUILD.bazel
  pkg/util/ulid/ulid.go
  pkg/util/ulid/ulid_test.go
Labels: O-community, X-blathers-triaged

#62783 tenantrate: switch to a single token bucket
  pkg/kv/kvserver/client_tenant_test.go
  pkg/kv/kvserver/tenantrate/BUILD.bazel
  pkg/kv/kvserver/tenantrate/factory.go
  pkg/kv/kvserver/tenantrate/helpers_test.go
  pkg/kv/kvserver/tenantrate/limiter.go
  pkg/kv/kvserver/tenantrate/limiter_test.go
  pkg/kv/kvserver/tenantrate/settings.go
  pkg/kv/kvserver/tenantrate/testdata/basic
  pkg/kv/kvserver/tenantrate/testdata/burst
  pkg/kv/kvserver/tenantrate/testdata/cancel
  pkg/kv/kvserver/tenantrate/testdata/estimate_iops
  pkg/kv/kvserver/tenantrate/testdata/reads
  pkg/kv/kvserver/tenantrate/testdata/update
  pkg/sql/logictest/logic.go
  pkg/util/quotapool/BUILD.bazel
  pkg/util/quotapool/config.go
  pkg/util/quotapool/int_rate.go
  pkg/util/quotapool/quotapool.go
  pkg/util/quotapool/token_bucket.go
  pkg/util/quotapool/token_bucket_test.go
Labels: backport-21.1.x

#63351 Updating syntax diagram for EXPLAIN ANALYZE (PLAN).
  docs/generated/sql/bnf/explain_analyze_stmt.bnf
  pkg/cmd/docgen/diagrams.go
Labels: A-explain, A-sql-syntax, C-enhancement, backport-21.1.x

#63609 release-21.1: tabledesc: MakeFirstMutationPublic should ignore PK swaps
  pkg/ccl/backupccl/restore_mid_schema_change_test.go
  pkg/sql/backfill.go
  pkg/sql/backfill/BUILD.bazel
  pkg/sql/backfill/backfill.go
  pkg/sql/catalog/descriptor.go
  pkg/sql/catalog/tabledesc/structured.go
  pkg/sql/rowexec/indexbackfiller.go
Labels: GA-blocker

#63760 geomfn: fix st_simplify with NaN
  pkg/geo/geomfn/topology_operations.go
  pkg/geo/geomfn/topology_operations_test.go
Labels: O-community, X-blathers-triaged

#63574 sql: fix index out of range error in inverted filterer
  pkg/sql/inverted/expression.go
  pkg/sql/inverted/testdata/expression
  pkg/sql/logictest/testdata/logic_test/inverted_index
  pkg/sql/opt/xform/testdata/rules/select
Labels: backport-20.2.x, backport-21.1.x

#63467 filetable: fix NPE when an empty file is downloaded from userfile
  pkg/cli/userfiletable_test.go
  pkg/storage/cloudimpl/filetable/file_table_read_writer.go
Labels: backport-21.1.x

#63830 opt: reduce cost of locality optimized anti join
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_tpcc
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/testdata/coster/zone
Labels: backport-21.1.x

#63665 sql: Don't clear zone configs on indexes during a RBR transition
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs
  pkg/config/zonepb/zone.go
  pkg/sql/region_util.go
  pkg/sql/schema_changer.go
Labels: backport-21.1.x

#63934 sql: properly classify errors for duplicate index names for UNIQUE indexes
  pkg/sql/alter_table.go
  pkg/sql/create_table.go
  pkg/sql/descriptor_mutation_test.go
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/logictest/testdata/logic_test/create_table
Labels: backport-20.2.x, backport-21.1.x

#59302 sql: code generation for missing pg_catalog columns
  pkg/cmd/generate-postgres-metadata-tables/main.go
  pkg/sql/pg_metadata_diff.go
  pkg/sql/pg_metadata_test.go
  pkg/sql/testdata/information_schema_tables.json
  pkg/sql/testdata/pg_catalog_tables.json
Labels: O-community

#63772 colflow: cancel flow on ungraceful stream shutdown in outbox
  pkg/col/coldatatestutils/random_testutils.go
  pkg/sql/colcontainer/diskqueue_test.go
  pkg/sql/colexec/colexecutils/spilling_queue_test.go
  pkg/sql/colflow/colrpc/BUILD.bazel
  pkg/sql/colflow/colrpc/colrpc_test.go
  pkg/sql/colflow/colrpc/inbox.go
  pkg/sql/colflow/colrpc/inbox_test.go
  pkg/sql/colflow/colrpc/outbox.go
  pkg/sql/colflow/colrpc/outbox_test.go
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/colflow/vectorized_flow_shutdown_test.go
  pkg/sql/flowinfra/flow.go
  pkg/sql/rowflow/routers.go
  pkg/sql/rowflow/routers_test.go
  pkg/sql/rowflow/test_utils.go
Labels: backport-20.2.x, backport-21.1.x

#64060 kvserver: fix delaying of splits with uninitialized followers
  pkg/kv/kvserver/BUILD.bazel
  pkg/kv/kvserver/client_split_burst_test.go
  pkg/kv/kvserver/client_split_test.go
  pkg/kv/kvserver/replica_raft.go
  pkg/kv/kvserver/split_delay_helper.go
  pkg/kv/kvserver/split_delay_helper_test.go
Labels: backport-21.1.x

#64278 release-21.1: opt: disallow fast path for cascading deletes with subqueries
  pkg/sql/logictest/testdata/logic_test/cascade
  pkg/sql/opt/optbuilder/fk_cascade.go
  pkg/sql/opt/optbuilder/testdata/fk-on-delete-cascade
Labels: release-blocker

#64345 release-20.2: tree: make password formatting anonymization round-trippable
  pkg/sql/sem/tree/create.go
  pkg/sql/sem/tree/format_test.go
Labels: backport-20.1.x

#63963 sql: mapping postgres unimplemented type into crdb implemented types
  pkg/cmd/generate-postgres-metadata-tables/BUILD.bazel
  pkg/cmd/generate-postgres-metadata-tables/main.go
  pkg/sql/pg_metadata_diff.go
  pkg/sql/testdata/information_schema_tables.json
  pkg/sql/testdata/information_schema_test_expected_diffs.json
  pkg/sql/testdata/pg_catalog_tables.json
  pkg/sql/testdata/pg_catalog_test_expected_diffs.json
Labels: O-community

#64219 release-21.1: colflow: cancel flow on ungraceful stream shutdown in outbox
  pkg/col/coldatatestutils/random_testutils.go
  pkg/sql/colcontainer/diskqueue_test.go
  pkg/sql/colexec/colexecutils/spilling_queue_test.go
  pkg/sql/colflow/colrpc/BUILD.bazel
  pkg/sql/colflow/colrpc/colrpc_test.go
  pkg/sql/colflow/colrpc/inbox.go
  pkg/sql/colflow/colrpc/inbox_test.go
  pkg/sql/colflow/colrpc/outbox.go
  pkg/sql/colflow/colrpc/outbox_test.go
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/colflow/vectorized_flow_shutdown_test.go
  pkg/sql/flowinfra/flow.go
  pkg/sql/rowflow/routers.go
  pkg/sql/rowflow/routers_test.go
  pkg/sql/rowflow/test_utils.go
Labels: GA-blocker
