Repository cockroachdb/cockroach, pull requests merged in 2021-11, with the labels that each got.

#72238 sql: populate indexprs column of pg_catalog.pg_index
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: backport-21.2.x

#71688 sql: support `"{}"` format for array column in COPY FROM STDIN WITH CSV
  pkg/sql/copy.go
  pkg/sql/pgwire/testdata/pgtest/copy
Labels: backport-21.2.x

#72274 authors: add Chengxiong Ruan to authors
  AUTHORS
Labels: O-community, X-blathers-untriaged

#72126 coldata: optimize some methods on Bytes to inline them
  pkg/col/coldata/bytes.go
Labels: backport-21.2.x

#72406 catalog/descs: hydrate types for tuples
  pkg/sql/catalog/descs/dist_sql_type_resolver.go
  pkg/sql/catalog/typedesc/table_implicit_record_type.go
  pkg/sql/catalog/typedesc/type_desc.go
  pkg/sql/logictest/testdata/logic_test/enums
Labels: backport-21.1.x, backport-21.2.x

#71597 sql: remove diagnostics.sql_stat_reset.interval
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/server/stats_test.go
  pkg/settings/registry.go
  pkg/sql/conn_executor.go
  pkg/sql/sqlstats/cluster_settings.go
  pkg/sql/sqlstats/persistedsqlstats/provider.go
  pkg/sql/sqlstats/sslocal/sql_stats.go
  pkg/sql/sqlstats/sslocal/sql_stats_test.go
  pkg/sql/sqlstats/sslocal/sslocal_provider.go
Labels: backport-21.2.x

#72594 roachprod: upgrade slack-go module
  DEPS.bzl
  go.mod
  go.sum
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/slack.go
  pkg/cmd/skipped-tests/BUILD.bazel
  pkg/cmd/skipped-tests/main.go
  pkg/kv/kvserver/replica_raftstorage.go
  pkg/roachprod/cloud/BUILD.bazel
  pkg/roachprod/cloud/gc.go
Labels: C-bug, A-roachprod, T-dev-inf

#72587 sql: plumb sessiondata into schemaexpr.FormatExprForDisplay
  pkg/ccl/importccl/read_import_mysql_test.go
  pkg/sql/alter_table.go
  pkg/sql/backfill.go
  pkg/sql/catalog/catformat/BUILD.bazel
  pkg/sql/catalog/catformat/index.go
  pkg/sql/catalog/catformat/index_test.go
  pkg/sql/catalog/schemaexpr/column.go
  pkg/sql/catalog/schemaexpr/expr.go
  pkg/sql/check.go
  pkg/sql/crdb_internal.go
  pkg/sql/information_schema.go
  pkg/sql/insert.go
  pkg/sql/logictest/testdata/logic_test/datetime
  pkg/sql/pg_catalog.go
  pkg/sql/show_create.go
  pkg/sql/show_create_clauses.go
  pkg/sql/update.go
  pkg/sql/upsert.go
Labels: backport-21.2.x

#72006 release-21.2: Add Rows Written to Transaction and Statement pages
  pkg/roachpb/app_stats.go
  pkg/roachpb/app_stats.pb.go
  pkg/roachpb/app_stats.proto
  pkg/sql/conn_executor_exec.go
  pkg/sql/executor_statement_metrics.go
  pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go
  pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go
  pkg/sql/sqlstats/ssmemstorage/ss_mem_writer.go
  pkg/sql/sqlstats/ssprovider.go
  pkg/ui/workspaces/cluster-ui/src/barCharts/barCharts.module.scss
  pkg/ui/workspaces/cluster-ui/src/barCharts/barCharts.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx
  pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactions.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts
  pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsBarCharts.ts
  pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsTable.tsx
  pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.spec.ts
  pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts
  pkg/ui/workspaces/cluster-ui/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/util/appStats.spec.ts
  pkg/ui/workspaces/db-console/src/util/appStats.ts
  pkg/ui/workspaces/db-console/src/views/statements/statements.spec.tsx
Labels: do-not-merge

#71969 release-21.2: cli: add \statement-diag SQL shell command
  pkg/ccl/logictestccl/testdata/logic_test/tenant_unsupported
  pkg/cli/clisqlclient/BUILD.bazel
  pkg/cli/clisqlclient/statement_diag.go
  pkg/cli/clisqlshell/BUILD.bazel
  pkg/cli/clisqlshell/sql.go
  pkg/cli/clisqlshell/statement_diag.go
  pkg/cli/flags.go
  pkg/cli/interactive_tests/common.tcl
  pkg/cli/interactive_tests/test_demo_node_cmds.tcl
  pkg/cli/interactive_tests/test_explain_analyze_debug.tcl
  pkg/cli/mt_start_sql.go
  pkg/cli/statement_diag.go
  pkg/cli/statement_diag_test.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/explain_bundle.go
  pkg/sql/logictest/testdata/logic_test/explain_analyze
  pkg/sql/logictest/testdata/logic_test/explain_analyze_system_tenant
Labels: A-multitenancy

#72362 release-21.2: tabledesc: fix bug involving DEFAULT exprs in MakeColumnDefDescs
  pkg/ccl/changefeedccl/avro_test.go
  pkg/sql/add_column.go
  pkg/sql/catalog/tabledesc/table.go
  pkg/sql/crdb_internal_test.go
  pkg/sql/create_table.go
  pkg/sql/create_view.go
  pkg/sql/logictest/testdata/logic_test/on_update
  pkg/sql/schemachanger/scbuild/table.go
Labels: do-not-merge

#70594 [CC-4714] ui: fix drag-to-zoom granularity issue
  pkg/ui/workspaces/db-console/src/views/shared/containers/metricDataProvider/index.tsx
Labels: backport-21.2.x

#72723 ui: fix initial load graph's data on Metrics page
  pkg/ui/workspaces/db-console/src/redux/timewindow.ts
Labels: backport-21.2.x

#57339 sql: Added CREATE SEQUENCE ... AS <typename> option.
  docs/generated/sql/bnf/alter_sequence.bnf
  docs/generated/sql/bnf/create_sequence_stmt.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/alter_sequence.go
  pkg/sql/catalog/descpb/structured.pb.go
  pkg/sql/catalog/descpb/structured.proto
  pkg/sql/create_sequence.go
  pkg/sql/logictest/testdata/logic_test/alter_sequence
  pkg/sql/logictest/testdata/logic_test/sequences
  pkg/sql/parser/parse_test.go
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/create_sequence
  pkg/sql/sem/tree/create.go
  pkg/sql/sequence.go
  pkg/sql/show_create_clauses.go
  pkg/sql/show_test.go
Labels: A-sql-sequences

#72966 tree: fix panic when using UDTs for GENERATED ... IDENTITY columns
  pkg/sql/logictest/testdata/logic_test/create_table
  pkg/sql/opt/optbuilder/testdata/create_table
  pkg/sql/parser/testdata/alter_table
  pkg/sql/parser/testdata/create_table
  pkg/sql/sem/tree/create.go
Labels: backport-21.2.x

#73020 kvserver: fix envvar in closed timestamp regression error hint
  pkg/kv/kvserver/replica_application_state_machine.go
Labels: backport-21.1.x, backport-21.2.x

#73023 kvserver: don't allow manually enqueueing uninitialized replicas
  pkg/kv/kvserver/store.go
  pkg/kv/kvserver/store_test.go
Labels: backport-21.1.x, backport-21.2.x

#73017 changefeedccl: Relax error checking condition in the test.
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport-21.2.x

#73040 opt: fix incorrect planning of locality optimized semi join
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/sql/opt/xform/join_funcs.go
  pkg/sql/opt/xform/rules/join.opt
  pkg/sql/opt/xform/testdata/rules/join
Labels: backport-21.2.x

#73114 kvserver: remove above-raft closedts assertion
  pkg/kv/kvserver/replica_application_state_machine.go
  pkg/kv/kvserver/replica_proposal_buf.go
Labels: backport-21.1.x, backport-21.2.x

#73191 jobs: Add jitter to job scheduler.
  pkg/jobs/job_scheduler.go
  pkg/jobs/job_scheduler_test.go
Labels: backport-21.2.x

#72748 kvprober: add feature to bypass admission queue
  pkg/kv/db.go
  pkg/kv/kvprober/kvprober.go
  pkg/kv/kvprober/kvprober_test.go
  pkg/kv/kvprober/planner.go
  pkg/kv/kvprober/settings.go
  pkg/kv/txn.go
  pkg/kv/txn_test.go
Labels: backport-21.2.x

#68432 gceworker: update ubuntu to 20.04
  build/bootstrap/bootstrap-debian.sh
  scripts/gceworker.sh
Labels: C-enhancement, A-build-system, T-dev-inf

#72928 GRANT, REVOKE diagram update
  docs/generated/sql/bnf/grant_stmt.bnf
  docs/generated/sql/bnf/revoke_stmt.bnf
  pkg/cmd/docgen/diagrams.go
Labels: backport-21.2.x
