Repository cockroachdb/cockroach, pull requests merged in 2021-09, with the labels that each got.

#69722 sql: alter ALTER TYPE ... OWNER TO ... for multi-region enum
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/sql/alter_type.go
Labels: backport-21.1.x

#69968 build: disable required release justifications
  build/teamcity-check.sh
  githooks/commit-msg
  githooks/prepare-commit-msg
Labels: backport-21.2.x

#70053 ui: update error messages on date picker
  pkg/ui/workspaces/cluster-ui/src/dateRange/dateRange.tsx
Labels: backport-21.2.x

#70065 ui: add tooltip and make sql box scrollable on database page
  pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx
  pkg/ui/workspaces/cluster-ui/src/sql/sqlhighlight.module.scss
  pkg/ui/workspaces/db-console/src/views/shared/components/sql/sqlhighlight.module.styl
Labels: backport-21.2.x

#69895 tenantcostclient: tenant-side throttling
  pkg/ccl/multitenantccl/tenantcostclient/BUILD.bazel
  pkg/ccl/multitenantccl/tenantcostclient/limiter.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side_test.go
  pkg/ccl/multitenantccl/tenantcostclient/test_utils.go
  pkg/ccl/multitenantccl/tenantcostclient/testdata/consumption
  pkg/ccl/multitenantccl/tenantcostclient/testdata/large-request
  pkg/ccl/multitenantccl/tenantcostclient/testdata/low-ru-race
  pkg/ccl/multitenantccl/tenantcostclient/testdata/throttling
  pkg/ccl/multitenantccl/tenantcostclient/token_bucket.go
  pkg/ccl/multitenantccl/tenantcostclient/token_bucket_test.go
  pkg/ccl/multitenantccl/tenantcostserver/system_table.go
  pkg/ccl/multitenantccl/tenantcostserver/testdata/instances
  pkg/ccl/multitenantccl/tenantcostserver/testdata/metrics
  pkg/ccl/multitenantccl/tenantcostserver/testdata/requests
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/multitenant/cost_controller.go
  pkg/server/tenant.go
  pkg/util/timeutil/manual_time.go
  pkg/util/timeutil/manual_time_test.go
  pkg/util/timeutil/time_source.go
Labels: backport-21.2.x

#70174 execbuilder: restore auto commit for internal queries
  pkg/sql/opt/exec/execbuilder/builder.go
Labels: release-blocker, backport-21.2.x

#70163 multitenant: implement a fallback rate
  pkg/ccl/multitenantccl/tenantcostclient/BUILD.bazel
  pkg/ccl/multitenantccl/tenantcostclient/limiter.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side_test.go
  pkg/ccl/multitenantccl/tenantcostclient/test_utils.go
  pkg/ccl/multitenantccl/tenantcostclient/testdata/fallback
  pkg/ccl/multitenantccl/tenantcostclient/testdata/fallback-throttled
  pkg/ccl/multitenantccl/tenantcostclient/testdata/large-request
  pkg/ccl/multitenantccl/tenantcostclient/testdata/throttling
  pkg/ccl/multitenantccl/tenantcostserver/server_test.go
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/tenant_token_bucket.go
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/tenant_token_bucket_test.go
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/testdata/fallback
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/testdata/request
  pkg/ccl/multitenantccl/tenantcostserver/testdata/requests
  pkg/roachpb/api.pb.go
  pkg/roachpb/api.proto
Labels: backport-21.2.x

#70139 sql: reduce TTL for tenant_usage
  pkg/ccl/logictestccl/testdata/logic_test/zone
  pkg/cmd/roachtest/tests/gossip.go
  pkg/sql/catalog/bootstrap/metadata.go
  pkg/sql/catalog/systemschema/system.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/system
  pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant
  pkg/sql/tests/system_table_test.go
  pkg/sql/tests/testdata/initial_keys
Labels: backport-21.2.x

#69215 doc: fix typo in txn_coord_sender.md
  docs/tech-notes/txn_coord_sender.md
Labels: O-community, X-blathers-untriaged

#70265 jobs: add nil reference check when updating job run stats
  pkg/jobs/helpers_test.go
  pkg/jobs/jobs.go
  pkg/jobs/registry_external_test.go
Labels: backport-21.2.x

#70267 storage: override MVCCMetadata.TxnDidNotUpdateMeta in mixed version c…
  pkg/ccl/storageccl/engineccl/encrypted_fs_test.go
  pkg/kv/kvserver/rangefeed/BUILD.bazel
  pkg/kv/kvserver/rangefeed/catchup_scan_bench_test.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/spanset/batch.go
  pkg/storage/engine.go
  pkg/storage/mvcc.go
  pkg/storage/mvcc_history_test.go
  pkg/storage/pebble.go
  pkg/storage/pebble_batch.go
  pkg/storage/sst_writer.go
  pkg/storage/testdata/mvcc_histories/conditional_put_with_txn_enable_separated_mixed_cluster
  pkg/storage/testdata/mvcc_histories/intent_history_enable_separated_mixed_cluster
  pkg/storage/testdata/mvcc_histories/intent_with_write_tracing_enable_separated_mixed_cluster
  pkg/storage/testdata/mvcc_histories/no_read_after_abort_enable_separated_mixed_cluster
  pkg/storage/testdata/mvcc_histories/read_after_write_enable_separated_mixed_cluster
Labels: backport-21.2.x

#70339 sql: fixing panic on forEachRole function
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/pg_catalog
Labels: O-community

#70375 sql: preserve tuple types when decoding
  pkg/sql/colencoding/value_encoding_test.go
  pkg/sql/rowenc/column_type_encoding.go
  pkg/sql/rowenc/column_type_encoding_test.go
Labels: backport-21.1.x, backport-21.2.x

#70112 changefeedccl: don't call encoder Ping() during validation
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/encoder.go
  pkg/ccl/changefeedccl/encoder_test.go
  pkg/ccl/changefeedccl/schema_registry.go
  pkg/ccl/changefeedccl/schema_registry_test.go
Labels: backport-21.2.x

#70368 release-21.2: backupccl: fix restore aost bug with dropped desc revisions
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/manifest_handling.go
Labels: GA-blocker, branch-release-21.2

#70341 release-21.2: server: get rid of end-user mechanism to enable span configs
  pkg/base/test_server_args.go
  pkg/cli/testdata/doctor/test_examine_cluster
  pkg/clusterversion/clusterversion.go
  pkg/kv/kvserver/store.go
  pkg/server/config.go
  pkg/server/server.go
  pkg/server/server_sql.go
  pkg/server/testserver.go
  pkg/settings/version.go
  pkg/spanconfig/spanconfigkvaccessor/BUILD.bazel
  pkg/spanconfig/spanconfigkvaccessor/disabled.go
  pkg/spanconfig/spanconfigkvaccessor/kvaccessor.go
  pkg/spanconfig/spanconfigkvaccessor/kvaccessor_test.go
  pkg/spanconfig/spanconfigmanager/BUILD.bazel
  pkg/spanconfig/spanconfigmanager/manager.go
  pkg/spanconfig/spanconfigmanager/manager_test.go
  pkg/spanconfig/testing_knobs.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/auto_span_config_reconciliation_job
  pkg/sql/logictest/testdata/logic_test/jobs
Labels: GA-blocker

#70017 rpc: avoid network IO in `Dialer.ConnHealth`
  pkg/rpc/context.go
  pkg/rpc/nodedialer/nodedialer.go
  pkg/rpc/nodedialer/nodedialer_test.go
  pkg/sql/distsql_physical_planner.go
Labels: backport-20.2.x, backport-21.1.x, backport-21.2.x

#70533 sql: permit VISIBLE to be used as a table/col name
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/create_table
Labels: backport-21.1.x, backport-21.2.x

#70534 ui: add unavailable message to statement details
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
Labels: backport-21.2.x

#70584 sql: change grant on database deprecation notice
  pkg/ccl/backupccl/testdata/backup-restore/backup-permissions
  pkg/sql/grant_revoke.go
Labels: backport-21.2.x

#70639 ui: fix tooltip text on statement and transaction table columns
  pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx
Labels: backport-21.2.x

#70723 kv: deflake TestTenantRateLimiter
  pkg/kv/kvserver/client_tenant_test.go
Labels: backport-21.2.x

#70251 cli: improve unsafe-remove-dead-replicas
  pkg/cli/debug.go
Labels: backport-21.2.x

#70740 util/encoding: support deep copying when decoding bytes ascending
  pkg/sql/colencoding/key_encoding.go
  pkg/sql/rowenc/column_type_encoding.go
  pkg/util/encoding/encoding.go
Labels: backport-21.2.x

#70788 sql: fix ZM dimensions for pg_extension
  pkg/sql/logictest/testdata/logic_test/pg_extension
  pkg/sql/pg_extension.go
Labels: backport-21.1.x, backport-21.2.x

#70754 tracing: don't expose span before fully initialized
  pkg/util/tracing/BUILD.bazel
  pkg/util/tracing/crdbspan.go
  pkg/util/tracing/span_inner.go
  pkg/util/tracing/tracer.go
  pkg/util/tracing/tracer_test.go
Labels: backport-21.2.x

#70741 rangecache: improve tracing of range descriptor lookups
  pkg/kv/bulk/sst_batcher_test.go
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvclient/rangecache/range_cache.go
  pkg/kv/kvclient/rangecache/range_cache_test.go
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/rowexec/tablereader_test.go
Labels: backport-21.1.x, backport-21.2.x

#70581 sql: disallow cross-database sequence references
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/drop_database
  pkg/sql/logictest/testdata/logic_test/drop_sequence
  pkg/sql/logictest/testdata/logic_test/rename_database
  pkg/sql/logictest/testdata/logic_test/sequences
  pkg/sql/logictest/testdata/logic_test/sequences_regclass
  pkg/sql/rename_table.go
  pkg/sql/sequence.go
Labels: backport-21.2.x

#70778 sql: change system.tenant_usage to use a single consumption column
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/backupccl/backup_planning_tenant.go
  pkg/ccl/multitenantccl/tenantcostserver/BUILD.bazel
  pkg/ccl/multitenantccl/tenantcostserver/system_table.go
  pkg/cli/zip_test.go
  pkg/clusterversion/cockroach_versions.go
  pkg/clusterversion/key_string.go
  pkg/migration/migrations/migrations.go
  pkg/migration/migrations/tenant_usage.go
  pkg/sql/catalog/catconstants/constants.go
  pkg/sql/catalog/systemschema/system.go
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_tenant
  pkg/sql/logictest/testdata/logic_test/create_statements
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_builtins
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/tenant.go
Labels: backport-21.2.x

#70858 roachtest: deflake autoupgrade
  pkg/cmd/roachtest/tests/autoupgrade.go
Labels: backport-21.1.x, backport-21.2.x

#70842 sql: correct CLUSTER SETTING hint for sql.defaults.datestyle.enabled
  pkg/sql/exec_util.go
  pkg/sql/vars.go
Labels: backport-21.2.x

#69630 kvserver: avoid retaining memory in rangefeed catch up scan
  pkg/kv/kvserver/rangefeed/catchup_scan.go
Labels: backport-21.1.x, backport-21.2.x

#70932 sql: disallow non-system tenants from running EXPLAIN ANALYZE (DEBUG)
  pkg/ccl/logictestccl/testdata/logic_test/tenant_unsupported
  pkg/sql/conn_executor_exec.go
  pkg/sql/logictest/testdata/logic_test/explain_analyze
  pkg/sql/logictest/testdata/logic_test/explain_analyze_system_tenant
Labels: backport-21.2.x
