Repository cockroachdb/cockroach, pull requests merged in 2021-02, with the labels that each got.

#59479 sql: add escape_string_warning session variable for compatibility
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/set
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/unsupported_vars.go
  pkg/sql/vars.go
Labels: O-community, X-blathers-triaged

#59654 opt: exclude implicit partitioning columns from UPSERT key
  pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row
  pkg/sql/opt/cat/index.go
  pkg/sql/opt/optbuilder/insert.go
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/opt_catalog.go
Labels: docs-todo

#59735 Re-enable parallel lints
  pkg/testutils/lint/lint_test.go
Labels: O-community, X-blathers-untriaged

#58923 sql: support NOT VISIBLE in CREATE TABLE for user-defined hidden columns
  docs/generated/sql/bnf/col_qualification.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/catalog/schemaexpr/column.go
  pkg/sql/catalog/tabledesc/table.go
  pkg/sql/create_table.go
  pkg/sql/logictest/testdata/logic_test/hidden_columns
  pkg/sql/parser/parse_test.go
  pkg/sql/parser/sql.y
  pkg/sql/sem/tree/create.go
  pkg/sql/sem/tree/pretty.go
Labels: O-community, X-blathers-untriaged

#57413 sql: Diff tool to verify pg_catalog between postgres and crdb
  pkg/cmd/generate-pg-catalog/BUILD.bazel
  pkg/cmd/generate-pg-catalog/main.go
  pkg/sql/BUILD.bazel
  pkg/sql/pg_catalog_diff.go
  pkg/sql/pg_catalog_test.go
  pkg/sql/testdata/pg_catalog_tables.json
  pkg/sql/testdata/pg_catalog_test_expected_diffs.json
  pkg/testutils/lint/lint_test.go
Labels: O-community, X-blathers-triaged, X-blathers-untriaged

#59743 sql/tenant: add idle detection and exit flag
  pkg/base/config.go
  pkg/base/test_server_args.go
  pkg/ccl/serverccl/server_sql_test.go
  pkg/cli/cliflags/flags.go
  pkg/cli/flags.go
  pkg/server/BUILD.bazel
  pkg/server/idle_monitor.go
  pkg/server/idle_monitor_test.go
  pkg/server/testserver.go
  pkg/server/testserver_test.go
  pkg/sql/exec_util.go
Labels: O-community

#59973 builtins: Check max allowed points for st_generatepoints
  docs/generated/sql/functions.md
  pkg/geo/geomfn/generate_points.go
  pkg/geo/geomfn/generate_points_test.go
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community, X-blathers-triaged

#60516 opt: fix stats bug causing unconstrained partial index scan
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/stats/partial-index-scan
  pkg/sql/opt/xform/testdata/rules/select
Labels: backport-20.2.x

#60570 sql/sem/tree: parse ISO8601 format with decimal places for interval types
  pkg/sql/sem/tree/interval.go
  pkg/sql/sem/tree/interval_test.go
Labels: O-community, X-blathers-triaged

#60592 sql: Forbid setting of zone config for non physical tables
  pkg/sql/drop_test.go
  pkg/sql/logictest/testdata/logic_test/zone_config
  pkg/sql/set_zone_config.go
Labels: O-community, X-blathers-untriaged

#56954 sql: implement sequence caching and cached sequence serial normalization
  docs/generated/settings/settings.html
  pkg/sql/alter_sequence.go
  pkg/sql/catalog/descpb/structured.go
  pkg/sql/catalog/descpb/structured.pb.go
  pkg/sql/catalog/descpb/structured.proto
  pkg/sql/catalog/systemschema/system.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/sequences
  pkg/sql/logictest/testdata/logic_test/serial
  pkg/sql/planner.go
  pkg/sql/sequence.go
  pkg/sql/sequence_test.go
  pkg/sql/serial.go
  pkg/sql/sessiondata/BUILD.bazel
  pkg/sql/sessiondata/sequence_cache.go
  pkg/sql/sessiondata/session_data.go
Labels: O-community

#60705 server: added initial cert utilities for automatic cert generation
  pkg/security/BUILD.bazel
  pkg/security/auto_tls_init.go
  pkg/security/auto_tls_init_test.go
  pkg/security/certificate_manager.go
  pkg/server/BUILD.bazel
  pkg/server/auto_tls_init.go
  pkg/server/auto_tls_init_test.go
Labels: A-security

#60954 release-20.2: logictest: use the latest builder image for logictests
  build/builder.sh
  build/teamcity-sqllogictest.sh
Labels: do-not-merge

#60926 release-20.1: changefeedccl: send resolved timestamps newest to oldest
  pkg/ccl/changefeedccl/changefeed_processors.go
Labels: T-cdc

#60925 release-20.2: changefeedccl: send resolved timestamps newest to oldest
  pkg/ccl/changefeedccl/changefeed_processors.go
Labels: A-cdc, T-cdc

#60590 sql: fix SHOW CREATE output for partitioned and interleaved partial indexes
  pkg/ccl/importccl/read_import_mysql_test.go
  pkg/ccl/logictestccl/testdata/logic_test/partitioning_index
  pkg/ccl/multiregionccl/show_test.go
  pkg/sql/catalog/catformat/index.go
  pkg/sql/catalog/catformat/index_test.go
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/show_create
  pkg/sql/show_create.go
Labels: backport-20.2.x

#61135 sql: dropping and creating view in a single transaction behaves wrong.
  pkg/sql/create_sequence.go
  pkg/sql/create_table.go
  pkg/sql/create_view.go
  pkg/sql/drop_test.go
  pkg/sql/logictest/testdata/logic_test/sequences
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/logictest/testdata/logic_test/views
  pkg/sql/schema_changer_test.go
Labels: backport-20.1.x, backport-20.2.x

#61139 sql: fixed information_schema.columns.udt_schema for enum types
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/information_schema
Labels: O-community

#61101 server: bug fix to correct path checks for existing certificates prior to generation
  pkg/security/certificate_manager.go
  pkg/server/auto_tls_init.go
Labels: A-security
