Repository cockroachdb/cockroach, pull requests merged in 2021-05, with the labels that each got.

#64136 importccl: add more errors to transient retryable error list
  pkg/ccl/backupccl/backup_job.go
  pkg/ccl/backupccl/backup_processor.go
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/importccl/import_stmt.go
  pkg/ccl/importccl/import_stmt_test.go
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/errors.go
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/sql/flowinfra/flow_registry.go
Labels: backport-21.1.x

#64655 importccl: add `chunk_size` option to EXPORT CSV
  pkg/ccl/importccl/exportcsv.go
  pkg/ccl/importccl/exportcsv_test.go
  pkg/sql/distsql_physical_planner.go
  pkg/sql/execinfrapb/processors_bulk_io.pb.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
  pkg/sql/export.go
Labels: backport-20.2.x, backport-21.1.x

#64035 sql: adding new tables at pg_catalog
  pkg/sql/catalog/catconstants/constants.go
  pkg/sql/logictest/testdata/logic_test/create_statements
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/exec/execbuilder/testdata/virtual
  pkg/sql/opt/xform/testdata/external/pgjdbc
  pkg/sql/pg_catalog.go
  pkg/sql/testdata/pg_catalog_tables.json
  pkg/sql/testdata/pg_catalog_test_expected_diffs.json
  pkg/sql/vtable/pg_catalog.go
Labels: O-community

#55055 release-20.2: cli: fix default value in help text of max-disk-temp-storage flag
  pkg/cli/flags_test.go
  pkg/cli/flags_util.go
  pkg/util/humanizeutil/humanize.go
Labels: X-noremind

#64507 build: make the whole build use vendored modules
  Makefile
Labels: O-community, X-blathers-triaged

#64845 duration,builtins: fix DST boundary handling
  pkg/sql/logictest/testdata/logic_test/timestamp
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/builtins_test.go
  pkg/util/duration/BUILD.bazel
  pkg/util/duration/duration.go
  pkg/util/duration/duration_test.go
Labels: backport-20.2.x, backport-21.1.x

#20293 rfcs: Repairing SQL errors
  docs/RFCS/20171025_scrub_sql_consistency_check_command.md
  docs/RFCS/20171213_repairing_sql_errors.md
Labels: X-noremind

#64892 sql: fix ordered set aggregates with constant ORDER BY expressions
  pkg/sql/logictest/testdata/logic_test/aggregate
  pkg/sql/opt/optbuilder/scope.go
Labels: backport-20.2.x, backport-21.1.x

#64887 add generate_series for timestampTZ values
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/sem/builtins/generator_builtins.go
Labels: O-community, X-blathers-triaged

#64991 sql: Fix TestTelemetry in cases where retries occur
  pkg/ccl/telemetryccl/testdata/telemetry/multiregion
Labels: backport-21.1.x

#64760 sql/pgwire: change formatting of floating point infinity values
  pkg/cmd/generate-binary/main.go
  pkg/sql/pgwire/testdata/encodings.json
  pkg/sql/pgwire/types.go
Labels: O-community, X-blathers-triaged

#64940 colrpc: shut down outbox tree on a graceful termination of a stream
  pkg/sql/colflow/colrpc/colrpc_test.go
  pkg/sql/colflow/colrpc/outbox.go
Labels: backport-20.2.x, backport-21.1.x

#65019 tree: make string concat do a normal cast
  pkg/sql/randgen/mutator.go
  pkg/sql/sem/tree/eval.go
  pkg/sql/sem/tree/expr_test.go
  pkg/sql/sem/tree/testdata/eval/concat
Labels: backport-21.1.x

#64555 ui: refactor info tooltip usages into info tooltip component
  pkg/ui/src/components/infoTooltip/index.tsx
  pkg/ui/src/components/infoTooltip/infoTooltip.styl
  pkg/ui/src/components/infoTooltip/infoTooltip.tsx
  pkg/ui/src/views/app/containers/layout/layout.styl
  pkg/ui/src/views/cluster/components/visualization/index.tsx
  pkg/ui/src/views/cluster/components/visualization/visualizations.styl
  pkg/ui/src/views/cluster/containers/dataDistribution/index.tsx
  pkg/ui/src/views/shared/components/summaryBar/index.tsx
Labels: O-community, X-blathers-untriaged

#65071 opt: reduce the cost of locality optimized scan
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/testdata/coster/zone
Labels: backport-21.1.x

#64997 geo/geomfn: implement ST_LineCrossingDirection
  docs/generated/sql/functions.md
  pkg/geo/geomfn/BUILD.bazel
  pkg/geo/geomfn/line_crossing_direction.go
  pkg/geo/geomfn/line_crossing_direction_test.go
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community, X-blathers-triaged

#64788 builtins: Added pg_relation_is_updatable and pg_column_is_updatable builtins
  docs/generated/sql/functions.md
  pkg/sql/catalog/tabledesc/table_desc.go
  pkg/sql/logictest/testdata/logic_test/pg_builtins
  pkg/sql/sem/builtins/BUILD.bazel
  pkg/sql/sem/builtins/pg_builtins.go
Labels: O-community, X-blathers-triaged

#64738 release-21.1: opt: fix null reject rule cycle
  pkg/sql/opt/norm/norm_test.go
  pkg/sql/opt/norm/reject_nulls_funcs.go
  pkg/sql/opt/norm/testdata/ruleprops/reject-nulls
Labels: do-not-merge

#64750 release-21.1: ui: add average number of runnable goroutines to the runtime graphs
  pkg/BUILD.bazel
  pkg/server/status/BUILD.bazel
  pkg/server/status/runtime.go
  pkg/testutils/lint/lint_test.go
  pkg/ts/catalog/chart_catalog.go
  pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/runtime.tsx
  pkg/util/goschedstats/BUILD.bazel
  pkg/util/goschedstats/runnable.go
  pkg/util/goschedstats/runnable_test.go
  pkg/util/goschedstats/runtime_go1.15.go
Labels: do-not-merge

#64360 release-21.1: sql: use a range feed for refreshing the table stats cache
  pkg/kv/kvclient/rangefeed/rangefeed.go
  pkg/server/server_sql.go
  pkg/server/testserver.go
  pkg/sql/catalog/lease/lease.go
  pkg/sql/create_stats.go
  pkg/sql/stats/BUILD.bazel
  pkg/sql/stats/automatic_stats_test.go
  pkg/sql/stats/delete_stats_test.go
  pkg/sql/stats/gossip_invalidation_test.go
  pkg/sql/stats/main_test.go
  pkg/sql/stats/stats_cache.go
  pkg/sql/stats/stats_cache_test.go
  pkg/testutils/serverutils/test_server_shim.go
Labels: do-not-merge

#63256 release-21.1: sqlsmith: fix INSERTs for rand-tables
  pkg/internal/sqlsmith/relational.go
  pkg/internal/sqlsmith/schema.go
Labels: do-not-merge

#63866 release-21.1: opt: allow IN subquery to be converted to lookup join
  pkg/sql/opt/norm/rules/scalar.opt
  pkg/sql/opt/norm/scalar_funcs.go
  pkg/sql/opt/norm/testdata/rules/assign_placeholders
  pkg/sql/opt/norm/testdata/rules/scalar
  pkg/sql/opt/testutils/opttester/BUILD.bazel
  pkg/sql/opt/testutils/opttester/memo_groups.go
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/testdata/rules/join
Labels: do-not-merge

#63790 release-21.1: opt: rework opt/bench
  pkg/sql/opt/bench/BUILD.bazel
  pkg/sql/opt/bench/bench_test.go
Labels: do-not-merge

#64481 release-21.1: opt: do not provide project ordering for columns removed when simplified
  pkg/sql/logictest/testdata/logic_test/sqlsmith
  pkg/sql/opt/ordering/project.go
  pkg/sql/opt/ordering/project_test.go
Labels: do-not-merge

#65101 sql: changed pg_catalog data type columns to "char" to match postgres
  pkg/sql/logictest/testdata/logic_test/create_statements
  pkg/sql/testdata/pg_catalog_test_expected_diffs.json
  pkg/sql/vtable/pg_catalog.go
Labels: O-community, X-blathers-triaged

#65154 sql: fixed information_schema.columns.data_type for enum type columns
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/types/types.go
Labels: O-community, X-blathers-triaged

#65173 opt: change SplitScanIntoUnionScans to use UnionAll operators
  pkg/sql/logictest/testdata/logic_test/limit
  pkg/sql/opt/exec/execbuilder/testdata/limit
  pkg/sql/opt/xform/limit_funcs.go
  pkg/sql/opt/xform/rules/limit.opt
  pkg/sql/opt/xform/testdata/external/trading
  pkg/sql/opt/xform/testdata/external/trading-mutation
  pkg/sql/opt/xform/testdata/physprops/ordering
  pkg/sql/opt/xform/testdata/rules/limit
Labels: backport-20.2.x, backport-21.1.x

#65282 opt: add support for SplitScanIntoUnionScans with enum columns
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row
  pkg/sql/opt/constraint/BUILD.bazel
  pkg/sql/opt/constraint/span.go
  pkg/sql/opt/constraint/span_test.go
  pkg/sql/opt/exec/execbuilder/testdata/enums
Labels: backport-21.1.x

#65275 sql: add a hint for string-to-timestamp cast error
  pkg/sql/logictest/testdata/logic_test/computed
  pkg/sql/sem/tree/type_check.go
Labels: backport-20.2.x, backport-21.1.x

#65063 pgwire: only show TZ minutes offset if non-zero
  pkg/cli/cli_test.go
  pkg/cli/sql_util.go
  pkg/cmd/generate-binary/main.go
  pkg/sql/pgwire/pgwirebase/encoding.go
  pkg/sql/pgwire/testdata/encodings.json
  pkg/sql/pgwire/testdata/pgtest/timezone
  pkg/sql/pgwire/types.go
  pkg/util/timeutil/timeutil.go
Labels: backport-20.2.x, backport-21.1.x

#65350 opt: support SplitScanIntoUnionScans for exclusive constraint boundaries
  pkg/sql/opt/constraint/span.go
  pkg/sql/opt/constraint/span_test.go
  pkg/sql/opt/xform/testdata/rules/limit
Labels: backport-21.1.x

#65370 builtins: mark ST_GeomFromGeoJSON(string) as preferred
  pkg/sql/pgwire/testdata/pgtest/placeholder
  pkg/sql/sem/builtins/geo_builtins.go
  pkg/sql/sem/tree/type_check_test.go
Labels: backport-20.2.x, backport-21.1.x

#65387 release-21.1: changefeedccl: Treat memory monitor errors as retryable.
  pkg/ccl/changefeedccl/bench_test.go
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/kvfeed/buffer.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed_test.go
  pkg/ccl/changefeedccl/testing_knobs.go
Labels: T-cdc

#64394 kvcoord: fix sorting of replicas
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/replica_slice.go
  pkg/kv/kvclient/kvcoord/replica_slice_test.go
  pkg/sql/physicalplan/replicaoracle/oracle_test.go
Labels: backport-20.2.x, backport-21.1.x

#65437 opt: normalize CollateExpr Locale
  pkg/sql/lex/encode.go
  pkg/sql/opt/exec/execbuilder/testdata/virtual_columns
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/optbuilder/BUILD.bazel
  pkg/sql/opt/optbuilder/scalar.go
  pkg/sql/opt/optbuilder/testdata/scalar
Labels: backport-21.1.x

#65323 util/ring: Reduce the time cost by TestRingBuffer
  pkg/util/ring/BUILD.bazel
  pkg/util/ring/ring_buffer_test.go
Labels: O-community, X-blathers-triaged

#65354 changefeedccl: Merge adjacent spans in the frontier.
  pkg/ccl/changefeedccl/bench_test.go
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/sink_cloudstorage_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go
  pkg/kv/kvclient/rangefeed/rangefeed.go
  pkg/kv/kvnemesis/watcher.go
  pkg/util/span/BUILD.bazel
  pkg/util/span/frontier.go
  pkg/util/span/frontier_test.go
Labels: T-cdc

#64894 sql/event_log: reduce tech debt, simplify and fix bugs
  pkg/server/node.go
  pkg/server/server.go
  pkg/sql/create_stats.go
  pkg/sql/event_log.go
  pkg/sql/exec_log.go
  pkg/sql/grant_revoke.go
Labels: backport-21.1.x

#65056 changefeedccl: randomly run sinkless tests on tenant
  pkg/base/test_server_args.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/ccl/changefeedccl/nemeses_test.go
  pkg/ccl/changefeedccl/validations_test.go
  pkg/testutils/serverutils/test_server_shim.go
Labels: T-cdc

#65382 release-21.1: roachtest: upgrade to confluent 6 in cdc roachtests
  pkg/cmd/roachtest/cdc.go
Labels: T-cdc

#65547 opt: copy LimitExpr input FDs regardless of limit value
  pkg/sql/opt/memo/logical_props_builder.go
  pkg/sql/opt/memo/testdata/logprops/limit
  pkg/sql/opt/norm/testdata/rules/decorrelate
  pkg/sql/opt/xform/testdata/physprops/limit_hint
Labels: backport-21.1.x

#65431 changefeedccl: Add query parameter for specifying certificates for schema registries
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/cdctest/BUILD.bazel
  pkg/ccl/changefeedccl/cdctest/schema_registry.go
  pkg/ccl/changefeedccl/cdctest/tls_util.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/options.go
  pkg/ccl/changefeedccl/encoder.go
  pkg/ccl/changefeedccl/encoder_test.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/tls.go
  pkg/util/httputil/client.go
Labels: A-cdc, T-cdc

#65620 sql: prevent assertion due to bad use of leases in bind
  pkg/kv/txn.go
  pkg/sql/conn_executor_prepare.go
  pkg/sql/tests/enum_test.go
Labels: backport-20.2.x, backport-21.1.x

#65686 geo/geomfn: fix Node if the LineString is the same point
  pkg/geo/geomfn/node.go
  pkg/geo/geomfn/node_test.go
Labels: backport-21.1.x

#65530 cli: stop attributing time spent running schema changes to network lat
  pkg/cli/sql_util.go
  pkg/sql/catalog/colinfo/result_columns.go
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/conn_executor_test.go
  pkg/sql/executor_statement_metrics.go
Labels: backport-21.1.x

#65673 backupccl: fix include interleaved tables option for scheduled backup
  pkg/ccl/backupccl/create_scheduled_backup.go
  pkg/ccl/backupccl/create_scheduled_backup_test.go
Labels: backport-20.2.x, backport-21.1.x

#65679 sql/pgwire: add telemetry for pgwire extended protcol
  pkg/sql/pgwire/conn.go
  pkg/sql/sqltelemetry/pgwire.go
Labels: O-community, backport-20.2.x, backport-21.1.x

#65769 settings: add `backup.table_statistics.enabled` to retired settings
  pkg/settings/registry.go
Labels: backport-20.2.x, backport-21.1.x

#65774 importccl: add IMPORT INTO telemetry
  pkg/ccl/importccl/import_stmt.go
Labels: backport-20.2.x, backport-21.1.x

#65819 colexecutils: make closure of nil spilling queue a no-op
  pkg/sql/colexec/colexecutils/spilling_queue.go
  pkg/sql/colexec/colexecwindow/buffered_window.go
  pkg/sql/colexec/colexecwindow/relative_rank.eg.go
  pkg/sql/colexec/colexecwindow/relative_rank_tmpl.go
Labels: backport-20.2.x, backport-21.1.x

#65775 changefeedccl: refactor schema registry code to fail early
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/cdctest/schema_registry.go
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/encoder.go
  pkg/ccl/changefeedccl/encoder_test.go
  pkg/ccl/changefeedccl/schema_registry.go
  pkg/ccl/changefeedccl/schema_registry_test.go
  pkg/ccl/changefeedccl/sink_test.go
Labels: T-cdc

#65800 backupccl: fix cluster restore progress logging
  pkg/ccl/backupccl/restore_job.go
Labels: backport-21.1.x

#65371 sql: remove transactional meta scan in TRUNCATE
  pkg/sql/drop_index.go
  pkg/sql/drop_table.go
  pkg/sql/pgwire/testdata/pgtest/notice
  pkg/sql/truncate.go
Labels: backport-20.2.x, backport-21.1.x

#65584 kvserver: fix bug obstructing range merges on multi-store clusters
  pkg/kv/kvserver/allocator.go
  pkg/kv/kvserver/allocator_scorer.go
  pkg/kv/kvserver/allocator_test.go
  pkg/kv/kvserver/client_relocate_range_test.go
  pkg/kv/kvserver/replica_command.go
  pkg/kv/kvserver/store_rebalancer.go
  pkg/server/testserver.go
Labels: backport-20.2.x, backport-21.1.x

#65592 kvcoord: prevent concurrent EndTxn requests
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater_test.go
  pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go
  pkg/kv/kvserver/intent_resolver_integration_test.go
Labels: backport-20.2.x, backport-21.1.x
