Repository cockroachdb/cockroach, pull requests merged in 2021-06, with the labels that each got.

#65876 colbuilder: improve logging of planning for traces
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/colflow/vectorized_flow.go
Labels: backport-21.1.x

#65972 colbuilder: optimize casting in edge cases
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/colexec/colexecbase/cast.eg.go
  pkg/sql/colexec/colexecbase/cast_tmpl.go
Labels: backport-21.1.x

#66030 README.md: fix Build an App with CockroachDB link
  README.md
Labels: O-community, X-blathers-untriaged

#66068 sql: add logic test for previously fixed casting bug
  pkg/sql/logictest/testdata/logic_test/cast
Labels: backport-21.1.x

#66092 util/limit: replace unfair semaphore with fair quotapool
  pkg/ccl/storageccl/export.go
  pkg/kv/kvserver/replica_rangefeed.go
  pkg/kv/kvserver/store_send.go
  pkg/util/limit/BUILD.bazel
  pkg/util/limit/limiter.go
  pkg/util/limit/limiter_test.go
Labels: backport-21.1.x

#66106 colcontainer: fix intra-query memory leak
  pkg/sql/colcontainer/diskqueue.go
Labels: backport-20.2.x, backport-21.1.x

#65329 security: Add version number to base64 form of join tokens
  pkg/cli/connect_join_test.go
  pkg/security/join_token.go
  pkg/security/join_token_test.go
Labels: O-community, X-blathers-untriaged

#65776 cloud: use (*http.Transport).Clone() to create http Transport
  pkg/storage/cloud/cloud_io.go
Labels: T-cdc

#66200 tenantrate: add old settings to retiredSettings
  pkg/settings/registry.go
Labels: backport-21.1.x

#65495 sql: pg_rewrite implemented for table-view dependencies
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: O-community, X-blathers-triaged

#66225 sql: stop creating superfluous indexes after primary key change
  pkg/sql/alter_primary_key.go
  pkg/sql/logictest/testdata/logic_test/alter_primary_key
Labels: backport-21.1.x

#66272 compare_test: add fixes to postgres compare test
  pkg/internal/sqlsmith/sqlsmith.go
  pkg/sql/logictest/testdata/logic_test/fuzzystrmatch
  pkg/sql/randgen/mutator.go
  pkg/sql/sem/builtins/builtins.go
Labels: backport-21.1.x

#66254 cli/sql: fix the handling of client-side commands
  pkg/cli/context.go
  pkg/cli/sql.go
  pkg/cli/sql_test.go
Labels: backport-21.1.x

#65653 kvserver: actually renew expiration-based leases
  pkg/kv/kvserver/BUILD.bazel
  pkg/kv/kvserver/replica_lease_renewal_test.go
  pkg/kv/kvserver/store.go
  pkg/kv/kvserver/testing_knobs.go
Labels: backport-20.2.x, backport-21.1.x

#65209 sql: use of constraint columns in FK can differ from order in PK definition
  pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit
  pkg/sql/catalog/descpb/BUILD.bazel
  pkg/sql/catalog/descpb/index.go
  pkg/sql/catalog/descpb/structured.go
  pkg/sql/catalog/descpb/structured_test.go
  pkg/sql/logictest/testdata/logic_test/fk
Labels: O-community, X-blathers-triaged, X-blathers-untriaged

#63545 release-21.1: sql: add crdb_internal.get_vmodule
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_tenant
  pkg/sql/sem/builtins/builtins.go
  pkg/util/log/vmodule.go
Labels: T-cdc

#65789 changefeedccl: don't return without calling ctxgroup.Wait()
  pkg/ccl/changefeedccl/kvfeed/BUILD.bazel
  pkg/ccl/changefeedccl/kvfeed/scanner.go
Labels: T-cdc

#62716 release-21.1: Fix some nilness linter findings
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/smithtest/main.go
  pkg/geo/geomfn/linestring.go
  pkg/jobs/job_scheduler.go
  pkg/jobs/registry.go
  pkg/server/init.go
  pkg/server/init_handshake.go
  pkg/sql/alter_sequence.go
  pkg/sql/alter_table.go
  pkg/sql/opt/optbuilder/orderby.go
  pkg/sql/pgwire/conn.go
  pkg/sql/sem/tree/create.go
  pkg/storage/cloudimpl/workload_storage.go
  pkg/util/encoding/encoding.go
  pkg/util/json/encoded.go
Labels: T-cdc

#65661 changefeedccl: add mvcc_timestamp option
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/options.go
  pkg/ccl/changefeedccl/encoder.go
  pkg/ccl/changefeedccl/kvfeed/buffer.go
Labels: T-cdc

#66264 Update README.md
  README.md
Labels: O-community, X-blathers-untriaged

#66346 colbuilder: fix recently introduced bug in an edge case
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/logictest/testdata/logic_test/dist_vectorize
Labels: backport-21.1.x

#66345 util: Fix interval division with float rounds differently from PostgreSQL
  pkg/sql/logictest/testdata/logic_test/datetime
  pkg/sql/logictest/testdata/logic_test/interval
  pkg/util/duration/duration.go
  pkg/util/duration/duration_test.go
Labels: O-community, X-blathers-triaged

#66380 opt: fix qualified star expansion after joins
  pkg/sql/logictest/testdata/logic_test/join
  pkg/sql/opt/optbuilder/BUILD.bazel
  pkg/sql/opt/optbuilder/distinct.go
  pkg/sql/opt/optbuilder/join.go
  pkg/sql/opt/optbuilder/name_resolution_test.go
  pkg/sql/opt/optbuilder/scope.go
  pkg/sql/opt/optbuilder/scope_column.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/testdata/join
  pkg/sql/opt/optbuilder/util.go
Labels: backport-20.2.x, backport-21.1.x

#66569 colexec: fix a crash with EXPLAIN (VEC) and some mutations
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/colexec/materializer.go
  pkg/sql/logictest/testdata/logic_test/vectorize_local
Labels: backport-21.1.x

#66571 opt: fix partial index implication for prepared statements
  pkg/sql/opt/BUILD.bazel
  pkg/sql/opt/exec/execbuilder/testdata/partial_index
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/metadata.go
  pkg/sql/opt/metadata_test.go
  pkg/sql/opt/norm/factory.go
  pkg/sql/opt/table_meta.go
Labels: backport-20.2.x, backport-21.1.x

#66536 util: Fix a duplicated comment on the documentation
  docs/generated/logging.md
  pkg/util/log/channel/channel_generated.go
  pkg/util/log/log_channels_generated.go
  pkg/util/log/logpb/log.pb.go
  pkg/util/log/logpb/log.proto
Labels: O-community, X-blathers-untriaged

#66578 sem: Support similar_escape() function from Postgres
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/tree/eval.go
Labels: O-community, X-blathers-triaged

#62713 release-21.1: roachtest: handle transient error when downloading bumptime
  pkg/cmd/roachtest/clock_util.go
Labels: T-cdc

#66150 backupccl: add cluster setting to disable GCS chunking
  pkg/storage/cloud/gcp/BUILD.bazel
  pkg/storage/cloud/gcp/gcs_storage.go
Labels: backport-20.2.x, backport-21.1.x

#66422 sql: "char" is supposed to truncate long values
  pkg/sql/delegate/show_table.go
  pkg/sql/logictest/testdata/logic_test/collatedstring
  pkg/sql/sem/tree/casts.go
  pkg/sql/sem/tree/constant.go
  pkg/sql/sem/tree/testdata/eval/cast
Labels: O-community, X-blathers-triaged

#66656 sql: add zone partitions when using ADD COLUMN UNIQUE on RBR
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row
  pkg/sql/add_column.go
Labels: backport-21.1.x

#66645 ts: fix a bug of chart catalog admin API
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/serverccl/admin_test.go
Labels: O-community, X-blathers-untriaged

#66865 sql: fix regular explression operator parser(#66861)
  pkg/sql/parser/parse_test.go
  pkg/sql/parser/sql.y
Labels: O-community

#66497 changefeedccl: webhook sink implementation
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/bench_test.go
  pkg/ccl/changefeedccl/cdctest/BUILD.bazel
  pkg/ccl/changefeedccl/cdctest/mock_webhook_sink.go
  pkg/ccl/changefeedccl/cdctest/testfeed.go
  pkg/ccl/changefeedccl/cdctest/tls_util.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/options.go
  pkg/ccl/changefeedccl/encoder.go
  pkg/ccl/changefeedccl/encoder_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/ccl/changefeedccl/nemeses_test.go
  pkg/ccl/changefeedccl/show_changefeed_jobs_test.go
  pkg/ccl/changefeedccl/sink.go
  pkg/ccl/changefeedccl/sink_cloudstorage.go
  pkg/ccl/changefeedccl/sink_cloudstorage_test.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_webhook.go
  pkg/ccl/changefeedccl/sink_webhook_test.go
  pkg/ccl/changefeedccl/testfeed_test.go
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cdc.go
Labels: T-cdc

#66910 kvcoord: fix rangefeed retries on transport errors
  build/bazelutil/check.sh
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go
  pkg/kv/kvclient/kvcoord/mocks_generated.go
  pkg/kv/kvclient/kvcoord/transport.go
  pkg/kv/kvclient/rangecache/BUILD.bazel
  pkg/kv/kvclient/rangecache/mocks_generated.go
  pkg/kv/kvclient/rangecache/range_cache.go
  pkg/kv/kvclient/rangefeed/BUILD.bazel
  pkg/kv/kvclient/rangefeed/mocks_generated.go
  pkg/kv/kvclient/rangefeed/rangefeed.go
  pkg/kv/kvclient/rangefeed/rangefeed_mock_test.go
  pkg/roachpb/BUILD.bazel
  pkg/roachpb/api.go
  pkg/roachpb/mocks_generated.go
Labels: backport-20.2.x, backport-21.1.x
