Repository cockroachdb/cockroach, pull requests merged in 2021-08, with the labels that each got.

#68329 roachtest: use activerecord 6.1.3
  pkg/cmd/roachtest/tests/activerecord.go
Labels: backport-20.2.x, backport-21.1.x

#67994 importccl: fail PGDUMP IMPORT if we see a UDT
  pkg/ccl/importccl/import_stmt.go
  pkg/ccl/importccl/import_stmt_test.go
  pkg/ccl/importccl/import_table_creation.go
  pkg/ccl/importccl/read_import_mysql.go
  pkg/ccl/importccl/read_import_pgdump.go
Labels: backport-21.1.x

#68502 kv: version gate new error types to avoid fatal in the client
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/clusterversion/cockroach_versions.go
  pkg/clusterversion/key_string.go
  pkg/kv/kvserver/replica_rangefeed.go
Labels: backport-21.1.x

#68476 sqlliveness/slstorage: record and log when deleting a session
  pkg/sql/sqlliveness/slstorage/slstorage.go
  pkg/sql/sqlliveness/slstorage/slstorage_test.go
Labels: backport-20.2.x, backport-21.1.x

#64156 roachprod: adding unit test and renaming ssh.go
  pkg/BUILD.bazel
  pkg/cmd/roachprod/ssh/BUILD.bazel
  pkg/cmd/roachprod/ssh/io.go
  pkg/cmd/roachprod/ssh/io_test.go
Labels: O-community

#68699 workload: fix generation of part table column values in TPC-H
  pkg/ccl/workloadccl/allccl/all_test.go
  pkg/workload/tpch/random.go
Labels: backport-20.2.x, backport-21.1.x

#69040 sql: fix deadlock when updating backfill progress
  pkg/sql/backfill.go
Labels: backport-21.1.x

#68018 sql: implemented pg_shdepend
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: O-community

#67953 sql, kv: add sql.mutations.max_row_size guardrails
  docs/generated/eventlog.md
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/backupccl/testdata/backup-restore/max-row-size
  pkg/ccl/importccl/import_processor_test.go
  pkg/ccl/importccl/import_stmt.go
  pkg/kv/batch.go
  pkg/kv/db.go
  pkg/kv/db_test.go
  pkg/kv/kvserver/replica.go
  pkg/kv/txn.go
  pkg/sql/BUILD.bazel
  pkg/sql/backfill.go
  pkg/sql/backfill/backfill.go
  pkg/sql/create_table.go
  pkg/sql/event_log_test.go
  pkg/sql/gcjob/BUILD.bazel
  pkg/sql/gcjob/table_garbage_collection.go
  pkg/sql/internal.go
  pkg/sql/opt_exec_factory.go
  pkg/sql/planner.go
  pkg/sql/row/BUILD.bazel
  pkg/sql/row/deleter.go
  pkg/sql/row/helper.go
  pkg/sql/row/inserter.go
  pkg/sql/row/row_converter.go
  pkg/sql/row/updater.go
  pkg/sql/row/writer.go
  pkg/sql/schema_changer.go
  pkg/sql/sessiondatapb/session_data.pb.go
  pkg/sql/sessiondatapb/session_data.proto
  pkg/sql/truncate.go
  pkg/util/log/eventpb/BUILD.bazel
  pkg/util/log/eventpb/eventlog_channels_generated.go
  pkg/util/log/eventpb/json_encode_generated.go
  pkg/util/log/eventpb/sql_audit_events.go
  pkg/util/log/eventpb/sql_audit_events.pb.go
  pkg/util/log/eventpb/sql_audit_events.proto
Labels: backport-21.1.x

#69432 storage: use unencrypted FS for ballast, min version file
  pkg/storage/file_util.go
  pkg/storage/min_version.go
  pkg/storage/min_version_test.go
  pkg/storage/pebble.go
Labels: branch-master, release-blocker
