Repository cockroachdb/cockroach, pull requests merged in 2021-10, with the labels that each got.

#70959 serverccl: support ListContentionEvents RPC endpoint for Serverless
  docs/generated/http/full.md
  pkg/ccl/serverccl/BUILD.bazel
  pkg/ccl/serverccl/tenant_status_test.go
  pkg/rpc/auth_tenant.go
  pkg/server/serverpb/status.pb.go
  pkg/server/serverpb/status.proto
  pkg/server/status_test.go
  pkg/server/tenant_status.go
  pkg/sql/contention/registry.go
Labels: backport-21.2.x

#70955 cluster-ui: hide terminate session / query buttons
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetailsConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPageConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx
Labels: backport-21.2.x

#70948 ui: update styles for stmt, txn and sessions pages
  pkg/ui/workspaces/cluster-ui/src/button/button.module.scss
  pkg/ui/workspaces/cluster-ui/src/multiSelectCheckbox/multiSelectCheckbox.tsx
  pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.tsx
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx
  pkg/ui/workspaces/cluster-ui/src/sql/sqlhighlight.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.module.scss
  pkg/ui/workspaces/cluster-ui/src/summaryCard/summaryCard.module.scss
  pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.module.scss
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.modules.scss
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageClasses.ts
  pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsCells/transactionsCells.module.scss
  pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts
  pkg/ui/workspaces/db-console/src/components/button/button.module.styl
  pkg/ui/workspaces/db-console/src/views/jobs/jobDetails.tsx
Labels: backport-21.2.x

#71027 rpc: allow CombinedStatementStats RPC endpoint for tenant
  pkg/rpc/auth_tenant.go
Labels: backport-21.2.x

#66903 importccl: respect storage options on PGDUMP index creation
  pkg/ccl/importccl/read_import_pgdump.go
  pkg/ccl/importccl/testdata/pgdump/geo_ogr2ogr.sql
Labels: branch-release-20.2, branch-release-21.1

#70856 sql: correct ZM coordinates for geometry_columns/geography_columns
  pkg/sql/logictest/testdata/logic_test/pg_extension
  pkg/sql/pg_extension.go
Labels: backport-21.1.x, backport-21.2.x

#70865 sql: adding empty stubs for missing tables on pg_catalog
  pkg/sql/catalog/catconstants/constants.go
  pkg/sql/logictest/testdata/logic_test/create_statements
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/opt/exec/execbuilder/testdata/scalar
  pkg/sql/opt/exec/execbuilder/testdata/virtual
  pkg/sql/opt/xform/testdata/coster/join
  pkg/sql/opt/xform/testdata/external/pgjdbc
  pkg/sql/pg_catalog.go
  pkg/sql/testdata/postgres_test_expected_diffs_on_pg_catalog.json
  pkg/sql/vtable/pg_catalog.go
Labels: O-community

#71038 multitenant: exempt sqlliveness operations from cost control
  pkg/ccl/multitenantccl/tenantcostclient/BUILD.bazel
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side_test.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go
  pkg/multitenant/cost_controller.go
  pkg/sql/sqlinstance/instancestorage/BUILD.bazel
  pkg/sql/sqlinstance/instancestorage/instancestorage.go
  pkg/sql/sqlliveness/slstorage/BUILD.bazel
  pkg/sql/sqlliveness/slstorage/slstorage.go
  pkg/testutils/serverutils/test_server_shim.go
Labels: backport-21.2.x

#71078 kvcoord: deflake `TestAsyncAbortPoisons`
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
Labels: backport-21.1.x, backport-21.2.x

#70942 sql: fix cast from int to char by interpreting integer as ASCII byte
  pkg/cmd/generate-binary/main.go
  pkg/sql/logictest/testdata/logic_test/cast
  pkg/sql/pgwire/pgwirebase/encoding.go
  pkg/sql/pgwire/testdata/encodings.json
  pkg/sql/pgwire/testdata/pgtest/char
  pkg/sql/pgwire/types.go
  pkg/sql/sem/tree/casts.go
  pkg/sql/sem/tree/eval.go
  pkg/sql/sem/tree/testdata/eval/cast
Labels: O-community, X-blathers-triaged

#70883 sql: improve error message for ON UPDATE with FK ON UPDATE
  pkg/sql/catalog/tabledesc/validate.go
  pkg/sql/logictest/testdata/logic_test/on_update
Labels: backport-21.2.x

#71134 security: remove the node TLS client cert exemption
  pkg/acceptance/cluster/certs.go
  pkg/acceptance/compose/gss/docker-compose-python.yml
  pkg/acceptance/compose/gss/docker-compose.yml
  pkg/acceptance/compose/gss/psql/gss_test.go
  pkg/acceptance/compose/gss/psql/start.sh
  pkg/acceptance/compose/gss/python/Dockerfile
  pkg/acceptance/compose/gss/python/start.sh
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
  pkg/security/auth.go
  pkg/security/auth_test.go
Labels: backport-21.2.x
