Repository cockroachdb/cockroach, pull requests merged in 2021-03, with the labels that each got.

#61280 cli: add scheduled_jobs table to the debug zip
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/partial1_excluded
  pkg/cli/testdata/zip/partial2
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/unavailable
  pkg/cli/zip_cluster_wide.go
  pkg/cli/zip_test.go
Labels: backport-20.2.x

#61416 sql: fix UPSERT with columns after partial index PUT and DEL columns
  pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row
  pkg/sql/delete.go
  pkg/sql/insert.go
  pkg/sql/logictest/testdata/logic_test/partial_index
  pkg/sql/update.go
  pkg/sql/upsert.go
Labels: backport-20.2.x

#61251 cli: Hide pprof port flag in workload init and run
  pkg/workload/cli/run.go
Labels: O-community, X-blathers-triaged

#61420 backupccl: make backup and restore more defensive to stats collections failures
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/backup_job.go
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/restore_job.go
Labels: backport-21.1.x

#61584 sql: add tests for prepared EXPLAIN and EXPLAIN ANALYZE
  pkg/sql/explain_test.go
Labels: backport-21.1.x

#61641 backupccl: fix TestProtectedTimestampSpanSelectionDuringBackup
  pkg/ccl/backupccl/backup_test.go
Labels: backport-21.1.x

#61317 colexec: check that Init is always called before Next and DrainMeta
  pkg/sql/colexec/BUILD.bazel
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/colexec/colexecargs/op_creation.go
  pkg/sql/colexec/colexecutils/operator.go
  pkg/sql/colexec/invariants_checker.go
  pkg/sql/colexec/parallel_unordered_synchronizer_test.go
  pkg/sql/colflow/BUILD.bazel
  pkg/sql/colflow/invariants_checker.go
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/colflow/vectorized_flow_space_test.go
  pkg/sql/colflow/vectorized_flow_test.go
  pkg/sql/execinfra/server_config.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/dist_vectorize
Labels: backport-21.1.x

#61680 opt: increase cost of full scans
  pkg/sql/logictest/testdata/logic_test/prepare
  pkg/sql/logictest/testdata/logic_test/vectorize_local
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/exec/execbuilder/testdata/fk
  pkg/sql/opt/exec/execbuilder/testdata/inverted_index
  pkg/sql/opt/exec/execbuilder/testdata/stats
  pkg/sql/opt/memo/testdata/format
  pkg/sql/opt/memo/testdata/memo
  pkg/sql/opt/memo/testdata/stats/inverted-geo
  pkg/sql/opt/memo/testdata/stats/join
  pkg/sql/opt/norm/testdata/rules/combo
  pkg/sql/opt/norm/testdata/rules/prune_cols
  pkg/sql/opt/norm/testdata/rules/with
  pkg/sql/opt/optbuilder/testdata/aggregate
  pkg/sql/opt/optgen/exprgen/testdata/explain
  pkg/sql/opt/optgen/exprgen/testdata/join
  pkg/sql/opt/optgen/exprgen/testdata/limit
  pkg/sql/opt/optgen/exprgen/testdata/scan
  pkg/sql/opt/testutils/opttester/testdata/opt-steps
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/testdata/coster/groupby
  pkg/sql/opt/xform/testdata/coster/join
  pkg/sql/opt/xform/testdata/coster/perturb-cost
  pkg/sql/opt/xform/testdata/coster/project
  pkg/sql/opt/xform/testdata/coster/scan
  pkg/sql/opt/xform/testdata/coster/select
  pkg/sql/opt/xform/testdata/coster/set
  pkg/sql/opt/xform/testdata/coster/sort
  pkg/sql/opt/xform/testdata/coster/virtual-scan
  pkg/sql/opt/xform/testdata/coster/zone
  pkg/sql/opt/xform/testdata/physprops/ordering
  pkg/sql/opt/xform/testdata/rules/groupby
  pkg/sql/opt/xform/testdata/rules/join
  pkg/sql/opt/xform/testdata/rules/join_order
  pkg/sql/opt/xform/testdata/rules/limit
  pkg/sql/opt/xform/testdata/rules/scan
  pkg/sql/opt/xform/testdata/rules/select
Labels: backport-21.1.x

#61337 sql,jobs: stop depending on streamingccl
  pkg/ccl/streamingccl/streamclient/random_stream_client.go
  pkg/ccl/streamingccl/streamingest/BUILD.bazel
  pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_planning.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_test.go
  pkg/jobs/jobspb/BUILD.bazel
  pkg/jobs/jobspb/jobs.pb.go
  pkg/jobs/jobspb/jobs.proto
  pkg/sql/BUILD.bazel
  pkg/sql/exec_util.go
  pkg/sql/execinfra/server_config.go
  pkg/sql/execinfrapb/BUILD.bazel
  pkg/sql/execinfrapb/processors_bulk_io.pb.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
Labels: backport-21.1.x

#61787 flowinfra: set flow stats only when collecting stats
  pkg/sql/flowinfra/flow.go
Labels: backport-21.1.x

#61732 sql: add json{,b}_extract_path_text
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/json_builtins
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/sem/builtins/builtins.go
Labels: O-community, X-blathers-triaged

#61719 ui: add contention graph to SQL metrics overview page
  pkg/ui/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx
Labels: backport-21.1.x

#61863 sql: don't save memo unnecessarily
  pkg/sql/instrumentation.go
  pkg/sql/plan.go
  pkg/sql/plan_opt.go
Labels: backport-21.1.x

#61578 opt: fix non-existent columns due to mutation rounding
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/opt/optbuilder/testdata/partial-indexes
  pkg/sql/opt/optbuilder/testdata/update_from
Labels: backport-20.1.x, backport-20.2.x, backport-21.1.x

#61858 sql: show time since table stats were collected in EXPLAIN
  pkg/sql/conn_executor_exec.go
  pkg/sql/distsql_physical_planner.go
  pkg/sql/exec_util.go
  pkg/sql/explain_test.go
  pkg/sql/instrumentation.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/vectorize_local
  pkg/sql/logictest/testdata/logic_test/vectorize_threshold
  pkg/sql/opt/cat/table.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/distsql_misc
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/exec/execbuilder/testdata/fk
  pkg/sql/opt/exec/execbuilder/testdata/limit
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
  pkg/sql/opt/exec/execbuilder/testdata/prepare
  pkg/sql/opt/exec/execbuilder/testdata/select_index
  pkg/sql/opt/exec/execbuilder/testdata/stats
  pkg/sql/opt/exec/execbuilder/testdata/unique
  pkg/sql/opt/exec/explain/BUILD.bazel
  pkg/sql/opt/exec/explain/emit.go
  pkg/sql/opt/exec/explain/flags.go
  pkg/sql/opt/exec/explain/output.go
  pkg/sql/opt/exec/factory.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt_exec_factory.go
  pkg/util/humanizeutil/duration.go
  pkg/util/humanizeutil/duration_test.go
Labels: backport-21.1.x

#61777 sql: only create real spans when session tracing/sampling
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_util.go
  pkg/sql/instrumentation.go
  pkg/sql/logictest/testdata/logic_test/contention_event
  pkg/sql/logictest/testdata/logic_test/inflight_trace_spans
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/txn_state.go
  pkg/sql/txn_state_test.go
  pkg/util/tracing/span.go
  pkg/util/tracing/span_inner.go
Labels: O-community

#61820 sql/catalog/descs: use allDescriptors as a negative cache for by-ID lookups
  pkg/bench/ddl_analysis/testdata/benchmark_expectations
  pkg/sql/catalog/descs/collection.go
  pkg/sql/resolver.go
Labels: backport-21.1.x

#61741 sql: disallow table/view/sequence rename from making cross DB references
  pkg/sql/logictest/testdata/logic_test/rename_table
  pkg/sql/rename_table.go
Labels: backport-21.1.x

#61761 sqlsmith: add inverted indexes and more column types
  pkg/sql/rowenc/testutils.go
Labels: backport-21.1.x

#61941 opt: expand set expression and Max1Row FD sets
  pkg/sql/opt/memo/logical_props_builder.go
  pkg/sql/opt/memo/testdata/logprops/max1row
  pkg/sql/opt/memo/testdata/logprops/set
  pkg/sql/opt/norm/testdata/rules/decorrelate
  pkg/sql/opt/norm/testdata/rules/join
  pkg/sql/opt/norm/testdata/rules/reject_nulls
  pkg/sql/opt/norm/testdata/rules/scalar
  pkg/sql/opt/norm/testdata/rules/select
  pkg/sql/opt/props/func_dep.go
  pkg/sql/opt/props/func_dep_test.go
  pkg/sql/opt/xform/testdata/external/tpce
  pkg/sql/opt/xform/testdata/external/tpce-no-stats
  pkg/sql/opt/xform/testdata/rules/join_order
  pkg/sql/opt/xform/testdata/rules/select
Labels: backport-21.1.x

#62051 sql: prevent dropping regions when regions <= 3 on SURVIVE REGION FAILURE
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs
  pkg/sql/BUILD.bazel
  pkg/sql/alter_database.go
  pkg/sql/catalog/multiregion/BUILD.bazel
  pkg/sql/catalog/multiregion/multiregion.go
  pkg/sql/catalog/typedesc/type_desc.go
  pkg/sql/descriptor.go
  pkg/sql/region_util.go
Labels: backport-21.1.x

#62054 sql: clear zone configs on final DROP REGION of a multi-region database
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs
  pkg/sql/alter_database.go
  pkg/sql/region_util.go
Labels: backport-21.1.x

#62163 contention: properly protect AddContentionEvent by mutex
  pkg/sql/contention/registry.go
Labels: backport-21.1.x

#62050 sql: allow VIEW and SEQUENCEs for multi-region databases
  pkg/ccl/importccl/import_stmt_test.go
  pkg/ccl/importccl/read_import_mysql.go
  pkg/ccl/importccl/read_import_pgdump.go
  pkg/ccl/importccl/testdata/mysqldump/views_and_sequences.sql
  pkg/ccl/importccl/testdata/pgdump/views_and_sequences.sql
  pkg/ccl/importccl/testutils_test.go
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/sql/add_column.go
  pkg/sql/create_sequence.go
  pkg/sql/create_table.go
  pkg/sql/create_view.go
  pkg/sql/testutils.go
  pkg/sql/virtual_schema.go
Labels: backport-21.1.x

#62122 sql: set locality to GLOBAL for materialized views
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/sql/alter_database.go
  pkg/sql/catalog/tabledesc/validate.go
  pkg/sql/create_view.go
Labels: backport-21.1.x

#61968 Fix missing node of sqlWalker in reducesql.go
  pkg/testutils/reduce/reducesql/reducesql.go
Labels: O-community, X-blathers-untriaged

#62121 sql: remove global zone configs on final DROP REGION
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/sql/alter_database.go
  pkg/sql/region_util.go
Labels: backport-21.1.x

#61266 bazel: Stringer missing files.
  BUILD.bazel
  pkg/sql/schemachanger/scop/BUILD.bazel
  pkg/workload/schemachange/BUILD.bazel
  pkg/workload/schemachange/schemachange.go
Labels: O-community, X-blathers-triaged

#62228 importccl: log all ignored pgdump stmts in different log files
  pkg/ccl/importccl/import_processor.go
  pkg/ccl/importccl/import_stmt.go
  pkg/ccl/importccl/import_stmt_test.go
  pkg/ccl/importccl/read_import_pgdump.go
Labels: backport-21.1.x

#62280 sql: make zone configs much cheaper
  pkg/bench/ddl_analysis/testdata/benchmark_expectations
  pkg/sql/zone_config.go
Labels: backport-20.2.x, backport-21.1.x

#62149 kvclient: don't route to followers if closed_timestmap.target_duration == 0
  pkg/ccl/kvccl/kvfollowerreadsccl/BUILD.bazel
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads.go
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go
Labels: first-pr

#62209 opt: add a regression test for INSERT ON CONFLICT with ORDER BY
  pkg/sql/logictest/testdata/logic_test/upsert
Labels: backport-21.1.x

#61333 rpc: install custom proto codec
  pkg/rpc/BUILD.bazel
  pkg/rpc/codec.go
  pkg/rpc/codec_test.go
  pkg/rpc/context.go
  pkg/testutils/lint/lint_test.go
Labels: T-cdc

#62109 opt: make opt tests work in bazel
  pkg/sql/opt/memo/BUILD.bazel
  pkg/sql/opt/norm/BUILD.bazel
  pkg/sql/opt/testutils/opttester/BUILD.bazel
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/BUILD.bazel
Labels: O-community

#62386 colbuilder: minor optimization of removing redundant allocations
  pkg/sql/colexec/colbuilder/execplan.go
Labels: backport-21.1.x

#62507 opt: fix issue with dangling pointer in statisticsBuilder
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/stats/inverted-geo
Labels: backport-20.2.x, backport-21.1.x

#62628 backupccl: Add `as_json` option to `SHOW BACKUP`
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/show.go
  pkg/sql/sem/tree/show.go
Labels: backport-20.2.x, backport-21.1.x

#62680 changefeedccl: Disable sinkful changefeeds when external io is disabled.
  pkg/ccl/changefeedccl/changefeed_stmt.go
Labels: backport-21.1.x

#61053 sql: add crdb_internal.get_vmodule
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_tenant
  pkg/sql/sem/builtins/builtins.go
  pkg/util/log/vmodule.go
Labels: T-cdc

#62173 sql: improve statisticsMutator
  pkg/sql/mutations/BUILD.bazel
  pkg/sql/mutations/mutations.go
Labels: backport-21.1.x

#62579 lease: remove code from 20.1->20.2 migration
  pkg/server/server_sql.go
  pkg/sql/catalog/lease/BUILD.bazel
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_test.go
Labels: backport-21.1.x

#62732 sql: fix error when adding and dropping a constraint in same txn.
  pkg/sql/catalog/tabledesc/structured.go
  pkg/sql/logictest/testdata/logic_test/alter_table
Labels: backport-20.1.x, backport-20.2.x, backport-21.1.x

#62808 opt: allow casts in initial CTE expression
  pkg/sql/logictest/testdata/logic_test/with
  pkg/sql/opt/optbuilder/testdata/with
  pkg/sql/opt/optbuilder/with.go
Labels: backport-20.2.x, backport-21.1.x

#62843 sql: fix ALTER PRIMARY KEY with virtual columns on the table
  pkg/sql/alter_primary_key.go
  pkg/sql/logictest/testdata/logic_test/alter_primary_key
Labels: backport-21.1.x

#62546 catalog: add telemetry for descriptor validation errors
  pkg/server/telemetry/BUILD.bazel
  pkg/server/telemetry/features.go
  pkg/sql/catalog/BUILD.bazel
  pkg/sql/catalog/catalogkv/catalogkv.go
  pkg/sql/catalog/catconstants/constants.go
  pkg/sql/catalog/dbdesc/database_test.go
  pkg/sql/catalog/descs/collection.go
  pkg/sql/catalog/schemadesc/schema_desc_test.go
  pkg/sql/catalog/tabledesc/validate_test.go
  pkg/sql/catalog/validate.go
  pkg/sql/doctor/doctor.go
  pkg/sql/testdata/telemetry/error
Labels: backport-21.1.x
