Repository cockroachdb/cockroach, pull requests merged in 2022-04, with the labels that each got.

#79115 sql/rowexec: subject column backfills to admission control
  pkg/kv/BUILD.bazel
  pkg/kv/db.go
  pkg/kv/txn.go
  pkg/sql/rowexec/BUILD.bazel
  pkg/sql/rowexec/columnbackfiller.go
Labels: backport-21.2.x, backport-22.1.x

#77952 backupccl: report row and byte size in SHOW BACKUP for tenant backups
  pkg/ccl/backupccl/show.go
  pkg/ccl/backupccl/show_test.go
Labels: A-bulkio, T-bulkio, backport-21.2.x, backport-22.1.x

#79256 sql: version gate usage of super regions
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/clusterversion/cockroach_versions.go
  pkg/clusterversion/key_string.go
  pkg/sql/alter_database.go
  pkg/sql/logictest/testdata/logic_test/super_regions_mixed_version
Labels: backport-22.1.x

#74303 opt: split a disjunction of equijoin predicates into a union of joins
  pkg/sql/logictest/testdata/logic_test/disjunction_in_join
  pkg/sql/logictest/testdata/logic_test/inner-join
  pkg/sql/logictest/testdata/logic_test/subquery
  pkg/sql/opt/exec/execbuilder/testdata/inner-join
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/stats/join
  pkg/sql/opt/norm/general_funcs.go
  pkg/sql/opt/props/selectivity.go
  pkg/sql/opt/xform/general_funcs.go
  pkg/sql/opt/xform/join_funcs.go
  pkg/sql/opt/xform/rules/join.opt
  pkg/sql/opt/xform/scan_funcs.go
  pkg/sql/opt/xform/testdata/rules/disjunction_in_join
  pkg/sql/opt/xform/testdata/rules/join
Labels: O-community, X-blathers-untriaged

#79116 release-22.1: add deperacation for old SHOW BACKUP syntax and refactor SHOW BACKUP parser
  docs/generated/sql/bnf/show_backup.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/ccl/backupccl/show.go
  pkg/ccl/backupccl/show_test.go
  pkg/ccl/backupccl/testdata/backup-restore/feature-flags
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/backup_restore
  pkg/sql/sem/tree/show.go
Labels: A-bulkio, T-bulkio

#79011 sql: various logging improvements
  pkg/sql/conn_executor.go
  pkg/sql/conn_io.go
  pkg/sql/pgwire/conn.go
Labels: backport-22.1.x

#78549 sql: Show direction (ASC/DESC) of inverted index columns in SHOW CREATE TABLE output.
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_backup
  pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit
  pkg/ccl/logictestccl/testdata/logic_test/partitioning_index
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_rename_column
  pkg/sql/catalog/catformat/index.go
  pkg/sql/catalog/catformat/index_test.go
  pkg/sql/logictest/testdata/logic_test/alter_primary_key
  pkg/sql/logictest/testdata/logic_test/create_table
  pkg/sql/logictest/testdata/logic_test/expression_index
  pkg/sql/logictest/testdata/logic_test/geospatial_index
  pkg/sql/logictest/testdata/logic_test/inverted_index
  pkg/sql/logictest/testdata/logic_test/inverted_index_multi_column
  pkg/sql/logictest/testdata/logic_test/pg_catalog
Labels: O-community

#78965 changefeedccl: enable distribution over tenant pods
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_dist.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeeddist/BUILD.bazel
  pkg/ccl/changefeedccl/changefeeddist/distflow.go
  pkg/ccl/changefeedccl/changefeeddist/testing_knobs.go
  pkg/ccl/changefeedccl/testing_knobs.go
  pkg/server/serverpb/status.go
Labels: backport-22.1.x

#79301 sql: fix `SHOW SCHEMAS FROM` to include user-defined schemas
  pkg/sql/delegate/show_schemas.go
  pkg/sql/logictest/testdata/logic_test/database
Labels: backport-21.1.x, backport-21.2.x, backport-22.1.x

#78218 kv: scan empty right-hand side of split for stats
  pkg/kv/kvserver/batcheval/cmd_end_transaction.go
  pkg/kv/kvserver/batcheval/split_stats_helper.go
Labels: backport-22.1.x

#79293 sql/importer: re-validate unique constraints after IMPORT
  pkg/ccl/importerccl/ccl_test.go
  pkg/sql/check.go
  pkg/sql/importer/import_job.go
Labels: backport-21.2.x, backport-22.1.x

#79086 backupccl: mark backup ExportRequests as Bulk priority
  pkg/ccl/backupccl/backup_processor.go
  pkg/util/admission/work_queue.go
Labels: backport-21.2.x, backport-22.1.x

#79347 release-21.2: backupccl: report row and byte size in SHOW BACKUP for tenant backups
  pkg/ccl/backupccl/show.go
  pkg/ccl/backupccl/show_test.go
Labels: A-bulkio, T-bulkio

#79339 release-22.1: backupccl: report row and byte size in SHOW BACKUP for tenant backups
  pkg/ccl/backupccl/show.go
  pkg/ccl/backupccl/show_test.go
Labels: A-bulkio, T-bulkio

#79336 sql/rowexec: use `BulkNormalPri` for column backfills
  pkg/sql/rowexec/columnbackfiller.go
Labels: backport-22.1.x

#78983 sql: fix decode_plan_gists doc string
  docs/generated/sql/functions.md
  pkg/sql/sem/builtins/generator_builtins.go
Labels: backport-22.1.x

#79406 batcheval: disable assettions on addsstable above scan
  pkg/kv/kvserver/batcheval/cmd_add_sstable.go
Labels: backport-22.1.x

#79186 changefeedccl: send different column families to different topics
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/alter_changefeed_test.go
  pkg/ccl/changefeedccl/avro.go
  pkg/ccl/changefeedccl/bench_test.go
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/encoder.go
  pkg/ccl/changefeedccl/encoder_test.go
  pkg/ccl/changefeedccl/show_changefeed_jobs_test.go
  pkg/ccl/changefeedccl/sink.go
  pkg/ccl/changefeedccl/sink_cloudstorage.go
  pkg/ccl/changefeedccl/sink_cloudstorage_test.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_pubsub.go
  pkg/ccl/changefeedccl/sink_sql.go
  pkg/ccl/changefeedccl/sink_test.go
  pkg/ccl/changefeedccl/testfeed_test.go
  pkg/ccl/changefeedccl/topic.go
Labels: backport-22.1.x

#79350 roachtest: update liquibase test harness and blocklist
  pkg/cmd/roachtest/tests/liquibase.go
  pkg/cmd/roachtest/tests/liquibase_blocklist.go
Labels: backport-21.2.x, backport-22.1.x

#78982 DOC-1573: Expose SET VISIBLE/NOT VISIBLE in grammar diagrams
  docs/generated/sql/bnf/alter_column.bnf
  docs/generated/sql/bnf/alter_table.bnf
  pkg/cmd/docgen/diagrams.go
Labels: backport-21.1.x, backport-21.2.x, backport-22.1.x

#78423 sql: fix ColumnAccessExpr.Eval with NULL inner expression
  pkg/sql/logictest/testdata/logic_test/tuple
  pkg/sql/sem/tree/eval.go
  pkg/sql/sem/tree/type_check.go
Labels: backport-21.1.x, backport-21.2.x, backport-22.1.x

#79554 bulk: don't scatter after pre-splitting on table boundaries
  pkg/sql/importer/import_processor_planning.go
Labels: backport-22.1.x

#79500 changefeedccl: add version gate for new changefeed options
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeedbase/BUILD.bazel
  pkg/ccl/changefeedccl/changefeedbase/options.go
  pkg/ccl/logictestccl/testdata/logic_test/create_changefeed_mixed_versions
  pkg/clusterversion/cockroach_versions.go
  pkg/clusterversion/key_string.go
Labels: backport-22.1.x

#79628 logictest: deflake tests with async statements
  pkg/sql/logictest/logic.go
Labels: backport-22.1.x

#79447 backupccl: add deprecation notice for backup cmd with explicit subdir
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/testdata/backup-restore/feature-flags
Labels: A-bulkio, T-bulkio, backport-22.1.x

#79525 changefeedccl: fix rangefeed resume off-by-one timestamp
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
Labels: backport-22.1.x

#78044 sql: introduce multi-region zone config extension descriptor changes
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/multiregionccl/BUILD.bazel
  pkg/ccl/multiregionccl/multiregion.go
  pkg/ccl/schemachangerccl/testdata/end_to_end/drop_multiregion
  pkg/sql/catalog/descpb/BUILD.bazel
  pkg/sql/catalog/descpb/structured.proto
  pkg/sql/catalog/descriptor.go
  pkg/sql/catalog/multiregion/BUILD.bazel
  pkg/sql/catalog/multiregion/region_config.go
  pkg/sql/catalog/multiregion/region_config_test.go
  pkg/sql/catalog/typedesc/table_implicit_record_type.go
  pkg/sql/catalog/typedesc/type_desc.go
  pkg/sql/region_util.go
  pkg/sql/region_util_test.go
Labels: backport-22.1.x

#77418 opt: index accelerate && (overlaps) expressions for array inverted indexes
  pkg/sql/logictest/testdata/logic_test/inverted_index
  pkg/sql/opt/exec/execbuilder/testdata/inverted_index
  pkg/sql/opt/invertedidx/json_array.go
  pkg/sql/opt/invertedidx/json_array_test.go
  pkg/sql/opt/xform/testdata/rules/select
  pkg/sql/rowenc/index_encoding.go
  pkg/sql/rowenc/index_encoding_test.go
  pkg/sql/sem/tree/eval.go
Labels: O-community

#79730 backupccl: only scatter empty ranges
  pkg/ccl/backupccl/split_and_scatter_processor.go
Labels: backport-22.1.x

#79513 changefeedccl: add structured logging for changefeed create and failed
  docs/generated/eventlog.md
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/errors.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/util/log/eventpb/eventlog_channels_generated.go
  pkg/util/log/eventpb/events.proto
  pkg/util/log/eventpb/json_encode_generated.go
  pkg/util/log/eventpb/telemetry.proto
Labels: backport-22.1.x

#78608 kvserver: check L0 sub-levels on allocation
  pkg/kv/kvserver/allocator.go
  pkg/kv/kvserver/allocator_scorer.go
  pkg/kv/kvserver/allocator_scorer_test.go
  pkg/kv/kvserver/allocator_test.go
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica_command.go
  pkg/kv/kvserver/replicate_queue.go
  pkg/kv/kvserver/store.go
  pkg/kv/kvserver/store_pool.go
  pkg/kv/kvserver/store_rebalancer.go
  pkg/kv/kvserver/store_rebalancer_test.go
  pkg/ts/catalog/chart_catalog.go
  pkg/ts/catalog/metrics.go
Labels: backport-22.1.x

#79803 colfetcher: no index join batch size randomization when non-metamorphic
  pkg/sql/colfetcher/index_join.go
Labels: backport-21.2.x, backport-22.1.x

#79811 log: remove spurious error logging from ETag handler
  pkg/util/httputil/BUILD.bazel
  pkg/util/httputil/handlers.go
Labels: backport-21.2.x, backport-22.1.x

#79843 ci: run Make and Publish Build without dependencies
  build/teamcity/internal/release/process/make-and-publish-build-artifacts.sh
  build/teamcity/internal/release/process/make-and-publish-build-tagging.sh
Labels: C-enhancement, T-dev-inf, A-ci

#79865 sql: fix overflow for soft limits
  pkg/sql/distsql_physical_planner.go
  pkg/sql/distsql_spec_exec_factory.go
  pkg/sql/index_join.go
  pkg/sql/logictest/testdata/logic_test/limit
  pkg/sql/lookup_join.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/factory.opt
  pkg/sql/opt/props/physical/required.go
  pkg/sql/opt_exec_factory.go
Labels: backport-21.2.x, backport-22.1.x

#79897 changefeedccl: tolerate nil error message keys in kafkfa sink
  pkg/ccl/changefeedccl/sink_kafka.go
Labels: backport-22.1.x

#78637 pgwire: add detailed error message for index out of bounds in decodeBinaryTuple
  pkg/sql/pgwire/pgwirebase/encoding.go
  pkg/sql/pgwire/testdata/pgtest/tuple
Labels: backport-21.1.x, backport-21.2.x, backport-22.1.x

#79906 sql/schemachanger: track jobs created to use better jobs API
  pkg/ccl/schemachangerccl/testdata/end_to_end/drop_multiregion
  pkg/sql/schemachanger/scdeps/exec_deps.go
  pkg/sql/schemachanger/scdeps/run_deps.go
  pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go
  pkg/sql/schemachanger/scdeps/sctestdeps/test_state.go
  pkg/sql/schemachanger/scexec/dependencies.go
  pkg/sql/schemachanger/testdata/alter_table_add_column
  pkg/sql/schemachanger/testdata/drop
  pkg/sql/schemachanger/testdata/index
Labels: backport-22.1.x

#79867 schemachanger: improve observability
  pkg/ccl/schemachangerccl/testdata/end_to_end/drop_multiregion
  pkg/sql/explain_ddl.go
  pkg/sql/logictest/testdata/logic_test/new_schema_changer
  pkg/sql/opt/optbuilder/explain.go
  pkg/sql/schemachanger/BUILD.bazel
  pkg/sql/schemachanger/scbackup/job.go
  pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go
  pkg/sql/schemachanger/scdeps/sctestutils/sctestutils.go
  pkg/sql/schemachanger/scexec/exec_mutation.go
  pkg/sql/schemachanger/scexec/scmutationexec/dependencies.go
  pkg/sql/schemachanger/scexec/scmutationexec/schema_change_job.go
  pkg/sql/schemachanger/schemachanger_test.go
  pkg/sql/schemachanger/scop/mutation.go
  pkg/sql/schemachanger/scplan/internal/scstage/build.go
  pkg/sql/schemachanger/scplan/internal/scstage/stage.go
  pkg/sql/schemachanger/scplan/plan_explain.go
  pkg/sql/schemachanger/scplan/testdata/alter_table
  pkg/sql/schemachanger/scplan/testdata/create_index
  pkg/sql/schemachanger/scplan/testdata/drop_database
  pkg/sql/schemachanger/scplan/testdata/drop_schema
  pkg/sql/schemachanger/scplan/testdata/drop_sequence
  pkg/sql/schemachanger/scplan/testdata/drop_table
  pkg/sql/schemachanger/scplan/testdata/drop_type
  pkg/sql/schemachanger/scplan/testdata/drop_view
  pkg/sql/schemachanger/scrun/scrun.go
  pkg/sql/schemachanger/testdata/alter_table_add_column
  pkg/sql/schemachanger/testdata/drop
  pkg/sql/schemachanger/testdata/index
  pkg/sql/sem/tree/explain.go
  pkg/sql/sqltelemetry/planning.go
Labels: backport-22.1.x

#79929 bazel: fix `nogo` config
  build/bazelutil/nogo_config.json
  pkg/ccl/changefeedccl/avro.go
  pkg/ccl/gssapiccl/get_user.go
  pkg/cmd/release/orchestration.go
  pkg/server/server_http.go
  pkg/sql/distsql_physical_planner.go
  pkg/util/log/eventpb/gen.go
  pkg/util/log/logconfig/gen.go
  pkg/util/targz/targz.go
Labels: backport-22.1.x

#79925 logictest: fix potential race with async statements
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/cluster_locks
Labels: backport-22.1.x

#79671 server: fix APIv2 error handling
  pkg/server/api_v2.go
Labels: backport-21.2.x, backport-22.1.x

#79977 roachtest: improve WaitForUpdatedReplicationReport
  pkg/cmd/roachtest/tests/util.go
Labels: backport-22.1.x

#79871 logictest: support async queries in logictests
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/cluster_locks
Labels: backport-22.1.x

#79536 sql: gate tenant's multi-region abstraction usage behind cluster setting
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/backup_tenant_test.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_default_primary_region
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_drop_region
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_privileges
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_secondary_tenants_abstractions_disallowed
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_show
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_auto_rehoming
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_placement_restricted
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_rename_column
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_table_placement_restricted
  pkg/sql/descriptor.go
  pkg/sql/logictest/logic.go
Labels: backport-22.1.x

#79958 server: ignore `ErrAbortHandler` panic in http server
  pkg/server/server_http.go
Labels: backport-22.1.x

#80134 ci: build `//pkg/sql/schemachanger/scpb:gen-elements-uml` in CI
  build/bazelutil/checked_in_genfiles.txt
Labels: backport-22.1.x

#79799 backupccl: add UX guardrails during backup subdirectory resolution
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/backupccl/backup_destination.go
  pkg/ccl/backupccl/backup_destination_test.go
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/testdata/backup-restore/feature-flags
  pkg/ccl/backupccl/testdata/backup-restore/mismatched-localities
  pkg/jobs/jobspb/jobs.proto
Labels: A-bulkio, T-bulkio, backport-22.1.x

#80132 sql: always return "public" for ResolveSchemaNameByID with ID 29
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/public_schema_migration_changefeed_external_test.go
  pkg/migration/migrations/public_schema_migration_external_test.go
  pkg/sql/catalog/catconstants/BUILD.bazel
  pkg/sql/catalog/catconstants/schemas.go
  pkg/sql/catalog/resolver/BUILD.bazel
  pkg/sql/catalog/resolver/resolver.go
  pkg/sql/temporary_schema.go
Labels: GA-blocker, backport-22.1.x

#80136 geomfn: ensure NaN never intersects/covers/within
  pkg/geo/geomfn/point_polygon_optimization.go
  pkg/geo/geomfn/topology_operations.go
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/sem/builtins/geo_builtins.go
Labels: backport-21.2.x, backport-22.1.x

#80193 kvserver: change default for kv.raft_log.loosely_coupled_truncation.e…
  pkg/kv/kvserver/raft_log_queue.go
Labels: backport-22.1.x, backport-22.1.0

#80261 cloud: add read rate limiters
  pkg/ccl/storageccl/external_sst_reader.go
  pkg/cloud/impl_registry.go
  pkg/util/quotapool/int_rate.go
Labels: backport-22.1.x

#80284 ci: ensure nightlies have all the env vars they need to post issues
  build/teamcity/cockroach/nightlies/lint_urls.sh
  build/teamcity/cockroach/nightlies/optimizer_tests.sh
  build/teamcity/cockroach/nightlies/random_syntax_tests.sh
  build/teamcity/cockroach/nightlies/sqlite_logic_test.sh
Labels: backport-22.1.x

#79121 backupccl: allow user to run SHOW BACKUP on locality aware backups
  docs/generated/sql/bnf/show_backup.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/manifest_handling.go
  pkg/ccl/backupccl/show.go
  pkg/sql/parser/sql.y
  pkg/sql/sem/tree/show.go
Labels: A-bulkio, T-bulkio, backport-22.1.x

#80221 sql: show ttl_job_cron if ttl_job_cron is not explicitly set
  pkg/ccl/backupccl/testdata/backup-restore/row_level_ttl
  pkg/sql/alter_table.go
  pkg/sql/catalog/catpb/BUILD.bazel
  pkg/sql/catalog/catpb/ttl.go
  pkg/sql/catalog/tabledesc/structured.go
  pkg/sql/create_table.go
  pkg/sql/logictest/testdata/logic_test/row_level_ttl
  pkg/sql/schema_changer_test.go
  pkg/sql/show_test.go
Labels: backport-22.1.x

#80307 tree: fix format for `FOR ALL ROLES` in default privileges
  pkg/sql/parser/testdata/alter_default_privileges
  pkg/sql/sem/tree/alter_default_privileges.go
Labels: backport-21.2.x, backport-22.1.x

#79994 cli: mark the `--multitenant` flag as hidden
  pkg/cli/flags.go
Labels: T-server-and-security, backport-22.1.x

#80337 Make create-docs-issue.sh executable
  build/teamcity/cockroach/create-docs-issue.sh
Labels: backport-22.1.x

#80036 docker: fix docker image to suit storage in memory
  build/deploy/cockroach.sh
  pkg/testutils/docker/single_node_docker_test.go
Labels: backport-22.1.x

#80287 release-21.2: backupccl: ensure AOST incremental backup ends after previous backup
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/backup_test.go
Labels: A-bulkio, T-bulkio, backport-21.1.x

#80399 roachtest: configure ORM tests to use SCRAM
  pkg/cmd/roachtest/tests/orm_helpers.go
Labels: backport-22.1.x, backport-22.1.0

#80403 backupccl,sql/importer: pause jobs on exhausting retries
  pkg/ccl/backupccl/backup_job.go
  pkg/ccl/backupccl/restore_job.go
  pkg/sql/importer/import_job.go
Labels: backport-22.1.x

#80405 sql: fix "no user specified" errors in statement bundles
  pkg/sql/explain_bundle_test.go
  pkg/sql/instrumentation.go
Labels: backport-22.1.x, backport-22.1.0

#80300 kv/bulk: warn instead of fail on failed initial split
  pkg/kv/bulk/buffering_adder.go
Labels: backport-22.1.x

#80473 ui: update width of timescale component
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScale.module.scss
Labels: backport-22.1.x, backport-22.1.0

#79550 roachtest: rewrite backup/mixed-version roachtest
  pkg/cmd/roachtest/tests/backup.go
Labels: backport-22.1.x

#80470 kvserver/loqrecovery: persist new replica ID in `RaftReplicaID`
  pkg/cli/debug.go
  pkg/kv/kvserver/loqrecovery/apply.go
  pkg/kv/kvserver/loqrecovery/recovery_env_test.go
  pkg/kv/kvserver/loqrecovery/testdata/learners_lose
  pkg/kv/kvserver/loqrecovery/testdata/max_applied_voter_wins
  pkg/kv/kvserver/loqrecovery/testdata/max_store_voter_wins
  pkg/kv/kvserver/loqrecovery/testdata/no_change_when_no_dead_peers
  pkg/kv/kvserver/loqrecovery/testdata/no_change_when_quorum
Labels: backport-22.1.x, backport-22.1.0

#78961 DOC-950: Updated SQL diagrams for PARTITION ALL BY
  docs/generated/sql/bnf/alter_table_partition_by.bnf
  docs/generated/sql/bnf/create_index_stmt.bnf
  docs/generated/sql/bnf/create_inverted_index_stmt.bnf
  docs/generated/sql/bnf/index_def.bnf
  docs/generated/sql/bnf/table_constraint.bnf
  pkg/cmd/docgen/diagrams.go
Labels: backport-21.1.x, backport-21.2.x, backport-22.1.x

#80606 kvtenantccl: fix tenant upgrade test on new versions
  pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go
Labels: backport-22.1.x, backport-22.1.0
