Repository cockroachdb/cockroach, pull requests merged in 2022-08, with the labels that each got.

#84211 kv: raft closed timestamp is no longer nullable
  pkg/kv/kvserver/below_raft_protos_test.go
  pkg/kv/kvserver/raft_log_truncator_test.go
  pkg/kv/kvserver/replica_application_state_machine.go
  pkg/kv/kvserver/stateloader/stateloader.go
  pkg/kv/kvserver/store_split.go
  pkg/storage/enginepb/mvcc3.proto
Labels: O-community, X-blathers-triaged

#83807 sql, telemetry: show correctly redacted error message
  docs/generated/eventlog.md
  pkg/sql/exec_log.go
  pkg/sql/telemetry_logging_test.go
  pkg/util/log/eventpb/json_encode_generated.go
  pkg/util/log/eventpb/sql_audit_events.proto
Labels: backport-21.2.x, backport-22.1.x

#85342 streamingccl: skip TestSinklessReplicationClient on 21.2
  pkg/ccl/streamingccl/streamclient/BUILD.bazel
  pkg/ccl/streamingccl/streamclient/cockroach_sinkless_replication_client_test.go
Labels: backport-21.2.x

#84553 streamingccl: support DeleteRange in tenant stream replication
  pkg/BUILD.bazel
  pkg/ccl/changefeedccl/kvfeed/kv_feed_test.go
  pkg/ccl/changefeedccl/kvfeed/physical_kv_feed.go
  pkg/ccl/streamingccl/BUILD.bazel
  pkg/ccl/streamingccl/event.go
  pkg/ccl/streamingccl/streamclient/client_test.go
  pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go
  pkg/ccl/streamingccl/streamingest/BUILD.bazel
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go
  pkg/ccl/streamingccl/streamingest/stream_replication_e2e_test.go
  pkg/ccl/streamingccl/streamingtest/replication_helpers.go
  pkg/ccl/streamingccl/streampb/stream.proto
  pkg/ccl/streamingccl/streamproducer/BUILD.bazel
  pkg/ccl/streamingccl/streamproducer/event_stream.go
  pkg/ccl/streamingccl/streamproducer/replication_stream_test.go
  pkg/ccl/streamingccl/utils.go
  pkg/ccl/streamingccl/utils_test.go
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvclient/kvcoord/rangefeed_message.go
  pkg/kv/kvclient/rangefeed/BUILD.bazel
  pkg/kv/kvclient/rangefeed/config.go
  pkg/kv/kvclient/rangefeed/db_adapter.go
  pkg/kv/kvclient/rangefeed/mocks_generated_test.go
  pkg/kv/kvclient/rangefeed/rangefeed.go
  pkg/kv/kvclient/rangefeed/rangefeed_external_test.go
  pkg/kv/kvclient/rangefeed/rangefeed_mock_test.go
  pkg/kv/kvnemesis/watcher.go
  pkg/kv/kvserver/client_rangefeed_test.go
  pkg/kv/kvserver/replica_rangefeed_test.go
Labels: A-tenant-streaming

#85565 kvserver: don't check ConnHealth when releasing proposal quota
  pkg/kv/kvserver/replica_proposal_quota.go
Labels: backport-21.2.x, backport-22.1.x

#85472 kvserver: add cluster setting for TxnCleanupThreshold
  pkg/cli/debug.go
  pkg/kv/kvserver/abortspan/BUILD.bazel
  pkg/kv/kvserver/abortspan/abortspan.go
  pkg/kv/kvserver/batcheval/cmd_end_transaction.go
  pkg/kv/kvserver/client_split_test.go
  pkg/kv/kvserver/gc/BUILD.bazel
  pkg/kv/kvserver/gc/gc.go
  pkg/kv/kvserver/gc/gc_old_test.go
  pkg/kv/kvserver/gc/gc_random_test.go
  pkg/kv/kvserver/gc/gc_test.go
  pkg/kv/kvserver/kvserverbase/base.go
  pkg/kv/kvserver/mvcc_gc_queue.go
  pkg/kv/kvserver/mvcc_gc_queue_test.go
Labels: backport-21.2.x, backport-22.1.x

#85996 sql: don't panic on auth check with unopen txn
  pkg/sql/authorization.go
Labels: backport-22.1.x

#85983 kv: permit different max clock offsets on different nodes in same cluster
  pkg/rpc/BUILD.bazel
  pkg/rpc/context.go
  pkg/rpc/context_test.go
  pkg/rpc/heartbeat.go
  pkg/rpc/heartbeat.proto
  pkg/rpc/heartbeat_test.go
Labels: docs-todo

#85493 cloud/amazon: add toggle for s3 storage to list prefix with additiona…
  pkg/cloud/amazon/BUILD.bazel
  pkg/cloud/amazon/s3_storage.go
Labels: backport-22.1.x

#85929 flowinfra: hydrate types for the inbound streams
  pkg/sql/flowinfra/BUILD.bazel
  pkg/sql/flowinfra/inbound.go
  pkg/sql/flowinfra/outbox_test.go
  pkg/sql/flowinfra/stream_data_test.go
  pkg/sql/flowinfra/stream_decoder.go
Labels: backport-22.1.x

#86087 release-22.1: build: publish cockroach-sql as an archive
  pkg/cmd/publish-provisional-artifacts/main.go
  pkg/cmd/publish-provisional-artifacts/main_test.go
  pkg/release/release.go
Labels: C-enhancement, A-release, T-release

#86052 backupccl: add mixed version infra to data driven test
  pkg/ccl/backupccl/datadriven_test.go
  pkg/ccl/backupccl/testdata/backup-restore/restore-schema-only-mixed-version
Labels: T-bulkio

#86339 multiregionccl: improve and deflake TestMultiRegionDataDriven
  pkg/ccl/multiregionccl/datadriven_test.go
Labels: backport-22.1.x

#86343 sql: allow controlling new tenants’ RANGE DEFAULT
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/spanconfigccl/spanconfigreconcilerccl/testdata/multitenant/range_tenants
  pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go
  pkg/sql/gcjob_test/gc_job_test.go
  pkg/sql/tenant.go
  pkg/sql/zone_config.go
Labels: backport-22.1.x

#85867 streamingccl: fix producer stream to properly propagate error
  pkg/ccl/streamingccl/streamclient/partitioned_stream_client_test.go
  pkg/ccl/streamingccl/streamingtest/BUILD.bazel
  pkg/ccl/streamingccl/streamingtest/replication_helpers.go
  pkg/ccl/streamingccl/streamproducer/event_stream.go
  pkg/ccl/streamingccl/streamproducer/replication_stream_test.go
Labels: A-tenant-streaming

#86606 opt: cache not-null columns in the metadata
  pkg/sql/opt/bench/bench_test.go
  pkg/sql/opt/memo/logical_props_builder.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/metadata.go
  pkg/sql/opt/table_meta.go
Labels: backport-21.2.x, backport-22.1.x

#86941 backupccl: missing txn in restore planning
  pkg/ccl/backupccl/restore_planning.go
Labels: backport-22.1.x

#86929 sql: also handle ESCAPE characters properly in COPY machine
  pkg/sql/copy.go
  pkg/sql/pgwire/testdata/pgtest/copy
Labels: backport-21.2.x, backport-22.1.x

#86841 workload/ycsb: give each worker a separate sql.Conn
  pkg/workload/ycsb/ycsb.go
Labels: backport-21.2.x, backport-22.1.x

#84620 admin: tenant support jobs endpoints
  pkg/BUILD.bazel
  pkg/ccl/serverccl/BUILD.bazel
  pkg/ccl/serverccl/adminccl/BUILD.bazel
  pkg/ccl/serverccl/adminccl/main_test.go
  pkg/ccl/serverccl/adminccl/tenant_admin_test.go
  pkg/ccl/serverccl/statusccl/tenant_status_test.go
  pkg/ccl/serverccl/tenant_test_utils.go
  pkg/server/admin.go
  pkg/server/tenant_admin.go
  pkg/sql/distsql_running_test.go
Labels: backport-22.1.x

#83688 kvcoord: heartbeat immediately to avoid being considered expired
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater_test.go
Labels: release-blocker, branch-release-22.2

#86820 kvcoord: restart stuck RangeFeeds
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_canceler.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_canceler_test.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go
  pkg/ts/catalog/chart_catalog.go
Labels: backport-21.2.x, backport-22.1.0
