Repository cockroachdb/cockroach, pull requests merged in 2022-07, with the labels that each got.

#83544 sql: add bulkio.column_backfill.update_chunk_size_threshold_bytes
  pkg/sql/backfill.go
  pkg/sql/backfill/backfill.go
  pkg/sql/distsql_plan_backfill.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/rowexec/backfiller.go
  pkg/sql/rowexec/columnbackfiller.go
Labels: backport-21.2.x, backport-22.1.x

#83467 release-22.1: opt: index accelerate `<tuple> = ANY(ARRAY[<tuple>, ...])`
  pkg/sql/opt/memo/testdata/logprops/constraints
  pkg/sql/opt/norm/scalar_funcs.go
  pkg/sql/opt/norm/testdata/rules/scalar
  pkg/sql/opt/xform/testdata/rules/select
Labels: do-not-merge

#82151 kv: add debug information to track down #77663
  pkg/kv/kvserver/concurrency/concurrency_manager.go
Labels: backport-21.2.x, backport-22.1.x

#83866 bazel: in `check.sh`, restrict `grep` to `pkg`
  build/bazelutil/check.sh
Labels: backport-22.1.x

#83729 storage: add nextKeyIgnoringTime() to MVCCIncrementalIterator
  pkg/storage/mvcc_history_test.go
  pkg/storage/mvcc_incremental_iterator.go
  pkg/storage/mvcc_incremental_iterator_test.go
  pkg/storage/testdata/mvcc_histories/range_key_iter_incremental
Labels: T-bulkio

#83112 streamingccl: support ingestion job to pause on error
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/ccl/streamingccl/streamingest/BUILD.bazel
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_test.go
  pkg/ccl/streamingccl/streamingest/stream_replication_e2e_test.go
  pkg/ccl/streamingccl/streamproducer/producer_job_test.go
  pkg/ccl/streamingccl/streamproducer/stream_lifetime.go
  pkg/jobs/jobspb/jobs.proto
  pkg/sql/exec_util.go
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/backup_restore
  pkg/sql/sem/tree/stream_ingestion.go
Labels: A-tenant-streaming

#84177 pgwire: Parse, Describe, and Bind should fail in an aborted txn
  pkg/sql/conn_executor_prepare.go
  pkg/sql/pgwire/testdata/pgtest/aborted_txn
Labels: backport-22.1.x

#82440 admission,storage: introduce flush tokens to constrain write admission
  pkg/kv/kvserver/metrics.go
  pkg/server/node.go
  pkg/storage/engine.go
  pkg/storage/pebble.go
  pkg/ts/catalog/chart_catalog.go
  pkg/util/admission/admissionpb/io_threshold.go
  pkg/util/admission/granter.go
  pkg/util/admission/granter_test.go
  pkg/util/admission/testdata/format_adjust_tokens_stats.txt
  pkg/util/admission/testdata/granter
  pkg/util/admission/testdata/io_load_listener
Labels: A-admission-control

#84205 server: fix conversion error on jobs
  pkg/server/admin.go
  pkg/server/admin_test.go
Labels: backport-21.2.x, backport-22.1.x

#83335 sql/pgwire: fix a leak of accounted for memory
  pkg/sql/pgwire/conn_test.go
  pkg/sql/pgwire/server.go
Labels: backport-21.2.x, backport-22.1.x

#84441 ppc64le - fix geoindex/TestS2GeometryIndexBasic failure
  pkg/geo/geo.go
Labels: O-community, X-blathers-triaged

#84606 release-21.2: bazel: add empty lintonbuild / nolintonbuild configs
  .bazelrc
Labels: A-build-system

#84613 DatumToHLC truncates timestamp
  pkg/sql/logictest/testdata/logic_test/as_of
  pkg/sql/sem/asof/as_of.go
  pkg/util/timeutil/pgdate/field_extract.go
  pkg/util/timeutil/pgdate/parsing.go
Labels: backport-21.2.x, backport-22.1.x

#84650 sql: fix multiregion sqlsmith failure
  pkg/internal/sqlsmith/alter.go
Labels: backport-22.1.x

#84686 Adjust per_changefeed_limit to 128MiB
  pkg/ccl/changefeedccl/changefeedbase/settings.go
Labels: backport-22.1.x

#84774 sqlproxyccl: add connection latency metrics
  pkg/ccl/sqlproxyccl/BUILD.bazel
  pkg/ccl/sqlproxyccl/connector.go
  pkg/ccl/sqlproxyccl/connector_test.go
  pkg/ccl/sqlproxyccl/metrics.go
  pkg/ccl/sqlproxyccl/proxy_handler.go
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
Labels: backport-22.1.x

#84495 backupccl: move conflicting system table descriptors to higher IDs
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/datadriven_test.go
  pkg/ccl/backupccl/restore_old_versions_test.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/backupccl/system_schema.go
  pkg/ccl/backupccl/testdata/backup-restore/descriptor-conflicts
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/BACKUP-CHECKPOINT-779898255398535169-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/BACKUP-CHECKPOINT-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/BACKUP-STATISTICS
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/BACKUP_MANIFEST
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/BACKUP_MANIFEST-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/data/779898260043694084.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/data/779898260043792387.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/data/779898260043825153.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/data/779898260043890689.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/data/779898260044513282.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/data/779898260045299713.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/data/779898260664254465.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.1.19/data/779898260732018689.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.2.13/BACKUP-CHECKPOINT-780216800973717505
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.2.13/BACKUP-CHECKPOINT-780216800973717505-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.2.13/BACKUP-CHECKPOINT-780216804883595265-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.2.13/BACKUP-CHECKPOINT-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.2.13/BACKUP-STATISTICS
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.2.13/BACKUP_MANIFEST
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.2.13/BACKUP_MANIFEST-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.2.13/data/780216812180635650.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.2.13/data/780216812182700033.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.2.13/data/780216812748275713.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v21.2.13/data/780216813191069697.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/BACKUP-LOCK-780220986219692033
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/BACKUP-STATISTICS
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/BACKUP_MANIFEST
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/BACKUP_MANIFEST-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/data/780220991158943746.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/data/780220991161040897.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/data/780220991337857025.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/fileinfo.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/metadata.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/progress/BACKUP-CHECKPOINT-13cdcfcdcdd2cfc8d2cec7dfcdcfc5cfc6c5cecfd1cac9cecbcccddfd4cfcfcfcfdfaaabbcfffe
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/progress/BACKUP-CHECKPOINT-13cdcfcdcdd2cfc8d2cec7dfcdcfc5cfc6c5cecfd1cac9cecbcccddfd4cfcfcfcfdfaaabbcfffe-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/progress/BACKUP-CHECKPOINT-13cdcfcdcdd2cfc8d2cec7dfcdcfc5cfc6c5cecfd1cdccc7cbc6c9dfd4cfcfcfcfdfaaabbcfffe
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster/v22.1.3/progress/BACKUP-CHECKPOINT-13cdcfcdcdd2cfc8d2cec7dfcdcfc5cfc6c5cecfd1cdccc7cbc6c9dfd4cfcfcfcfdfaaabbcfffe-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/create_cluster.sql
  pkg/sql/catalog/catpb/privilege.go
  pkg/sql/catalog/catprivilege/fix.go
  pkg/sql/catalog/catprivilege/system.go
  pkg/sql/catalog/catprivilege/validate.go
  pkg/sql/catalog/tabledesc/validate_test.go
  pkg/upgrade/upgrades/descriptor_utils.go
Labels: backport-22.1.x

#84615 release-22.1: colexec: fixed nullableArgs projection operators
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/colexec/colexecproj/proj_const_left_ops.eg.go
  pkg/sql/colexec/colexecproj/proj_const_ops_tmpl.go
  pkg/sql/colexec/colexecproj/proj_const_right_ops.eg.go
  pkg/sql/colexec/colexecproj/proj_like_ops.eg.go
  pkg/sql/colexec/colexecproj/proj_non_const_ops.eg.go
  pkg/sql/colexec/colexecproj/proj_non_const_ops_tmpl.go
  pkg/sql/colexec/colexecproj/projection_ops_test.go
  pkg/sql/logictest/testdata/logic_test/array
Labels: backport-22.1.x

#85140 kvserver: ignore leaseholder replica type in DistSender
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvclient/kvcoord/transport.go
  pkg/kv/kvclient/kvcoord/transport_test.go
  pkg/roachpb/metadata.go
Labels: backport-22.1.x

#83310 streamingccl: support canceling an ingestion job
  docs/generated/sql/functions.md
  pkg/ccl/streamingccl/streamclient/client.go
  pkg/ccl/streamingccl/streamclient/client_test.go
  pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go
  pkg/ccl/streamingccl/streamclient/partitioned_stream_client_test.go
  pkg/ccl/streamingccl/streamclient/random_stream_client.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go
  pkg/ccl/streamingccl/streamingest/stream_replication_e2e_test.go
  pkg/ccl/streamingccl/streamproducer/BUILD.bazel
  pkg/ccl/streamingccl/streamproducer/producer_job.go
  pkg/ccl/streamingccl/streamproducer/producer_job_test.go
  pkg/ccl/streamingccl/streamproducer/replication_manager.go
  pkg/ccl/streamingccl/streamproducer/replication_stream_test.go
  pkg/ccl/streamingccl/streamproducer/stream_lifetime.go
  pkg/jobs/jobspb/jobs.proto
  pkg/sql/sem/builtins/replication_builtins.go
  pkg/streaming/api.go
Labels: A-tenant-streaming
