Repository cockroachdb/cockroach, pull requests merged in 2022-02, with the labels that each got.

#75793 kvserver: use `ClearRawRange` to truncate very large Raft logs
  pkg/kv/kvserver/replica_raft.go
  pkg/kv/kvserver/replica_raft_truncation_test.go
  pkg/kv/kvserver/testdata/truncated_state/truncated_state
  pkg/roachpb/data.go
  pkg/roachpb/data_test.go
Labels: backport-21.1.x, backport-21.2.x

#76076 roachprod: Make it possible to specify file descriptor limit.
  pkg/cmd/roachprod/flags.go
  pkg/roachprod/config/config.go
  pkg/roachprod/install/cockroach.go
  pkg/roachprod/install/scripts/start.sh
  pkg/roachprod/install/testdata/start/start.txt
  pkg/roachprod/roachprod.go
Labels: O-cloudreport

#76148 migrations: remove unused testing knobs
  pkg/migration/BUILD.bazel
  pkg/migration/migrations/schema_changes.go
  pkg/migration/testing_knobs.go
Labels: T-bulkio

#76294 server: make the Drain interfaces available to SQL-only servers
  pkg/cli/mt_start_sql.go
  pkg/cli/start.go
  pkg/server/drain.go
  pkg/server/server.go
  pkg/server/server_sql.go
  pkg/server/tenant.go
  pkg/server/tenant_admin.go
  pkg/server/testserver.go
  pkg/sql/pgwire/pgwire_test.go
  pkg/testutils/serverutils/test_tenant_shim.go
Labels: T-server-and-security

#76402 importccl: move export parquet tests to new file
  pkg/ccl/importccl/BUILD.bazel
  pkg/ccl/importccl/exportcsv_test.go
  pkg/ccl/importccl/exportparquet_test.go
Labels: T-bulkio

#75969 backupccl: breakup the txn that inserts stats during cluster restore
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/restore_job.go
Labels: T-bulkio

#71882 admission: epoch based LIFO to prevent throughput collapse
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/util/admission/BUILD.bazel
  pkg/util/admission/granter.go
  pkg/util/admission/granter_test.go
  pkg/util/admission/testdata/priority_states
  pkg/util/admission/testdata/work_queue
  pkg/util/admission/work_queue.go
  pkg/util/admission/work_queue_test.go
Labels: A-admission-control

#76825 rangefeed: fix panic due to rangefeed stopper race
  pkg/kv/kvserver/rangefeed/processor.go
  pkg/kv/kvserver/rangefeed/processor_test.go
  pkg/kv/kvserver/replica_rangefeed.go
Labels: backport-21.1.x, backport-21.2.x

#77016 sql: dropping user with default privilege's error message is more clear
  pkg/sql/drop_role.go
  pkg/sql/logictest/testdata/logic_test/drop_role_with_default_privileges
  pkg/sql/logictest/testdata/logic_test/owner
Labels: backport-21.2.x
