Repository cockroachdb/cockroach, pull requests merged in 2022-05, with the labels that each got.

#80876 sql/catalog/descs,sql: tweak WaitForOneVersion backoff
  pkg/sql/catalog/descs/txn.go
  pkg/sql/schema_changer.go
Labels: backport-22.1.x

#80651 sql: change materialized view not to be created with fixed timestamp.
  pkg/sql/create_view.go
  pkg/sql/logictest/testdata/logic_test/materialized_view
Labels: backport-21.2.x, backport-22.1.x

#78110 stats: table setting to turn auto stats collection on/off
  pkg/sql/alter_table.go
  pkg/sql/catalog/catpb/BUILD.bazel
  pkg/sql/catalog/catpb/catalog.go
  pkg/sql/catalog/catpb/catalog.proto
  pkg/sql/catalog/descriptor.go
  pkg/sql/catalog/tabledesc/structured.go
  pkg/sql/catalog/tabledesc/validate.go
  pkg/sql/catalog/tabledesc/validate_test.go
  pkg/sql/create_table.go
  pkg/sql/create_test.go
  pkg/sql/distsql_plan_stats.go
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/logictest/testdata/logic_test/create_table
  pkg/sql/paramparse/BUILD.bazel
  pkg/sql/paramparse/paramobserver.go
  pkg/sql/set_cluster_setting.go
  pkg/sql/stats/BUILD.bazel
  pkg/sql/stats/automatic_stats.go
  pkg/sql/stats/automatic_stats_test.go
Labels: backport-22.1.x

#80923 opt: disable index recommendations for system tables
  pkg/sql/opt/cat/table.go
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/indexrec/index_candidate_set.go
  pkg/sql/opt/indexrec/testdata/index-candidates-recommendations
  pkg/sql/opt/testutils/testcat/BUILD.bazel
  pkg/sql/opt/testutils/testcat/create_table.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/opt/testutils/testcat/vtable.go
  pkg/sql/opt_catalog.go
  pkg/sql/sqlstats/persistedsqlstats/testdata/virtual_view_no_full_scans
Labels: backport-22.1.x

#81010 sql: optimize the common case where no cursor exists
  pkg/sql/conn_executor_prepare.go
  pkg/sql/sql_cursor.go
Labels: backport-22.1.x

#79176 sql: add sql.txn.contended.count metric
  pkg/server/status_test.go
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_util.go
  pkg/sql/executor_statement_metrics.go
  pkg/ts/catalog/chart_catalog.go
Labels: backport-22.1.x

#81054 roachtest: temporarily skip encryption test
  pkg/cmd/roachtest/tests/encryption.go
Labels: backport-22.1.x, backport-22.1.0

#81244 acceptance: skip TestComposeGSSPython
  pkg/acceptance/compose_test.go
Labels: backport-21.1.x, backport-21.2.x, backport-22.1.x

#81236 kvserver: deflake `TestInitRaftGroupOnRequest`
  pkg/kv/kvserver/client_raft_test.go
Labels: backport-22.1.x

#81222 cloud/gcp: include object path in missing object error
  pkg/cloud/gcp/gcs_storage.go
Labels: backport-22.1.x

#80241 sql: improve crdb_internal.lost_descriptors_with_data implementation
  pkg/sql/crdb_internal.go
Labels: backport-22.1.x

#79680 sql: deflake TestCancelMultipleQueued
  pkg/sql/schema_changer_test.go
Labels: backport-22.1.x

#79691 sql: disallow partial index creation referencing new column in predicate
  pkg/sql/catalog/descriptor.go
  pkg/sql/catalog/schemaexpr/partial_index.go
  pkg/sql/catalog/schemaexpr/testutils_test.go
  pkg/sql/logictest/testdata/logic_test/partial_index
  pkg/sql/logictest/testdata/logic_test/virtual_columns
Labels: backport-21.2.x, backport-22.1.x

#81420 parser: disallow 'SET tracing' in some contexts
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/alter_role.go
  pkg/sql/lexbase/predicates.go
  pkg/sql/logictest/testdata/logic_test/alter_role_set
  pkg/sql/logictest/testdata/logic_test/set
  pkg/sql/logictest/testdata/logic_test/set_local
  pkg/sql/parser/lexer.go
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/alter_user
  pkg/sql/parser/testdata/set
Labels: backport-21.2.x, backport-22.1.x

#81491 colflow: release disk resources in hash router in all cases
  pkg/sql/colflow/routers.go
Labels: backport-21.2.x, backport-22.1.x

#81103 roachtest: update TeamCity links to the new UI.
  pkg/cmd/internal/issues/issues.go
  pkg/cmd/internal/issues/issues_test.go
  pkg/cmd/internal/issues/testdata/post/failure-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-with-url-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-with-url-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-with-url-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-with-url-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/fatal-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/fatal-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/fatal-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/fatal-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/panic-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/panic-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/panic-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/panic-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/rsg-crash-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/rsg-crash-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/rsg-crash-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/rsg-crash-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/with-artifacts-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/with-artifacts-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/with-artifacts-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/with-artifacts-related-issue.txt
Labels: first-pr

#81266 cast: disallow int to 0-length bit or varbit casts
  pkg/sql/logictest/testdata/logic_test/cross_join
  pkg/sql/logictest/testdata/logic_test/srfs
  pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index
  pkg/sql/sem/cast/cast.go
  pkg/sql/sem/cast/cast_map.go
  pkg/sql/sem/eval/cast_test/testdata/explicit_casts_skip.csv
Labels: O-community, X-blathers-untriaged

#81564 sql: correct error code for CopyFail message
  pkg/sql/copy.go
  pkg/sql/pgwire/testdata/pgtest/copy
  pkg/testutils/pgtest/datadriven.go
Labels: backport-21.2.x, backport-22.1.x

#81336 authors: add wenyihu6 to authors
  AUTHORS
Labels: first-pr

#81667 awsdms: properly retry initial migration
  pkg/cmd/roachtest/tests/awsdms.go
Labels: backport-22.1.x

#81681 colexecwindow: fix panic when lead or lag arguments are different types
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/colexec/colexecwindow/window_functions_util.go
  pkg/sql/logictest/testdata/logic_test/window
Labels: O-community, backport-21.2.x, backport-22.1.x

#81796 sql: don't use the streamer for queries with mutations
  pkg/sql/distsql_running.go
Labels: backport-22.1.x

#81743 backupccl: avoid quadradic behaviour in spansForAllTableIndexes
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/backup_planning_test.go
Labels: backport-21.2.x, backport-22.1.x

#81136 kvserver: add timeout for lease acquisitions
  pkg/kv/kvserver/client_lease_test.go
  pkg/kv/kvserver/replica_range_lease.go
Labels: backport-21.2.x, backport-22.1.x

#81762 democluster: fix `cockroach demo movr --geo-partitioned-replicas --multi-region`
  pkg/cli/democluster/BUILD.bazel
  pkg/cli/democluster/demo_cluster.go
Labels: T-sql-experience

#81921 ccl/sqlproxyccl: ignore watch events with UNKNOWN pod states
  pkg/ccl/sqlproxyccl/tenant/directory.proto
  pkg/ccl/sqlproxyccl/tenant/directory_cache.go
  pkg/ccl/sqlproxyccl/tenant/entry.go
  pkg/ccl/sqlproxyccl/tenantdirsvr/test_directory_svr.go
Labels: backport-22.1.x

#81811 backupccl: use correct option name in error message
  pkg/ccl/backupccl/backup_destination.go
  pkg/ccl/backupccl/backup_test.go
Labels: backport-22.1.x

#81894 ppc64le - fix test failure of TestSegmentize/GEOMETRYCOLLECTION_
  pkg/geo/geomfn/segmentize_test.go
Labels: O-community, X-blathers-untriaged

#81986 server/debug: fix lsm-viz endpoint
  pkg/server/debug/BUILD.bazel
  pkg/server/debug/server.go
Labels: backport-21.2.x, backport-22.1.x

#82054 opt: fix bug with incorrect results produced by paired left lookup join
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
  pkg/sql/opt/xform/join_funcs.go
  pkg/sql/opt/xform/testdata/external/liquibase
  pkg/sql/opt/xform/testdata/external/navicat
  pkg/sql/opt/xform/testdata/rules/join
Labels: backport-22.1.x

#82026 planner: fix print valid sql in `show create view`
  pkg/sql/catalog/descriptor.go
  pkg/sql/logictest/testdata/logic_test/sequences_regclass
  pkg/sql/logictest/testdata/logic_test/views
  pkg/sql/show_create_clauses.go
Labels: O-community

#82087 sql: materialized view creation rollback leaves behind references
  pkg/sql/schema_changer.go
  pkg/sql/schema_changer_test.go
Labels: backport-21.1.x, backport-21.2.x, backport-22.1.x

#82090 sql/gcjob: mark the job idle when waiting for work
  pkg/ccl/testccl/sqlccl/BUILD.bazel
  pkg/ccl/testccl/sqlccl/gc_job_test.go
  pkg/sql/gcjob/BUILD.bazel
  pkg/sql/gcjob/gc_job.go
  pkg/sql/gcjob/gc_job_test.go
Labels: backport-22.1.x

#81693 sql: enforce NOT NULL when adding a virtual computed column
  pkg/sql/add_column.go
  pkg/sql/alter_table.go
  pkg/sql/logictest/testdata/logic_test/virtual_columns
Labels: backport-21.2.x, backport-22.1.x
