Repository cockroachdb/cockroach, pull requests merged in 2022-11, with the labels that each got.

#90116 sql: add option to use lookup join for db-scope virtual tables
  pkg/bench/rttanalysis/testdata/benchmark_expectations
  pkg/sql/catalog/catalogkeys/keys.go
  pkg/sql/catalog/descriptor.go
  pkg/sql/catalog/descs/collection.go
  pkg/sql/catalog/descs/collection_test.go
  pkg/sql/catalog/descs/descriptor.go
  pkg/sql/catalog/internal/catkv/BUILD.bazel
  pkg/sql/catalog/internal/catkv/catalog_reader.go
  pkg/sql/catalog/internal/catkv/stored_catalog.go
  pkg/sql/catalog/nstree/catalog.go
  pkg/sql/catalog/schemaexpr/partial_index.go
  pkg/sql/crdb_internal.go
  pkg/sql/delegate/show_tables.go
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/create_statements
  pkg/sql/logictest/testdata/logic_test/reassign_owned_by
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/exec/execbuilder/testdata/virtual
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt_catalog.go
  pkg/sql/pg_catalog.go
  pkg/sql/resolver.go
  pkg/sql/scheduledlogging/captured_index_usage_stats.go
  pkg/sql/scheduledlogging/captured_index_usage_stats_test.go
  pkg/sql/schema_changer.go
  pkg/sql/schema_resolver.go
  pkg/sql/sem/tree/name_resolution.go
  pkg/sql/virtual_schema.go
Labels: backport-22.2.x

#90887 sql: add nil-check gate for stmt passed to InternalExecutor.checkIfStmtIsAllowed
  pkg/sql/internal.go
Labels: backport-22.2.x, backport-22.2.0

#90621 backupccl: update backupAndRestore test helper
  pkg/ccl/backupccl/backup_test.go
Labels: T-disaster-recovery

#91101 release: RedHat Connect to use quay.io
  build/release/teamcity-publish-redhat-release.sh
Labels: C-bug, A-release, backport-21.2.x, T-release, backport-22.1.x, backport-22.2.x, backport-22.2.0

#91097 jobs: do not include nil error into a log message when stepping
  pkg/jobs/registry.go
Labels: backport-22.2.x

#88342 backupccl: reduce GC TTL on table during cluster restore rollback
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/testdata/backup-restore/restore-on-fail-or-cancel-fast-drop
  pkg/sql/gcjob/gc_job.go
  pkg/sql/gcjob/index_garbage_collection.go
  pkg/sql/gcjob/table_garbage_collection.go
Labels: backport-22.2.x

#90858 rowcontainer: fix an edge case when spilling to disk
  pkg/sql/rowcontainer/hash_row_container.go
  pkg/sql/rowcontainer/row_container.go
Labels: backport-22.2.x

#90924 sql: fix implicit record types for virtual tables
  pkg/sql/catalog/typedesc/table_implicit_record_type.go
  pkg/sql/catalog/typedesc/type_desc.go
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/record
  pkg/sql/pg_catalog.go
  pkg/sql/schema_resolver.go
  pkg/sql/virtual_schema.go
Labels: backport-22.1.x, backport-22.2.x

#91179 kvserver: add metric for raft leaders that hold invalid leases
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/store.go
  pkg/ts/catalog/chart_catalog.go
Labels: O-community

#91083 workflow: Added a github workflow to publish Cluster UI
  .github/workflows/cluster-ui-release-next.yml
  .github/workflows/cluster-ui-release.yml
Labels: A-ci, T-crux

#91173 spanconfigsqltranslator: translate spanconfigs for offline dbs
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/BUILD.bazel
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/misc
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/protectedts
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/tenant/misc
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/tenant/protectedts
  pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go
  pkg/spanconfig/spanconfigtestutils/spanconfigtestcluster/BUILD.bazel
  pkg/spanconfig/spanconfigtestutils/spanconfigtestcluster/tenant_state.go
Labels: backport-22.1.x, backport-22.2.x

#91009 storage: reuse byte buffer for `PointSynthesizingIter.UnsafeRawMVCCKey`
  pkg/storage/bench_pebble_test.go
  pkg/storage/bench_test.go
  pkg/storage/point_synthesizing_iter.go
Labels: backport-22.2.x

#91356 cli: support MVCC range keys in `debug range-keys` batches
  pkg/kv/kvserver/debug_print.go
  pkg/kv/kvserver/debug_print_test.go
Labels: backport-22.2.x

#91130 server: fixes nodes list on databases page
  pkg/ccl/multiregionccl/BUILD.bazel
  pkg/ccl/multiregionccl/multiregionccltestutils/testutils.go
  pkg/ccl/multiregionccl/region_test.go
  pkg/server/admin.go
Labels: backport-22.1.x, backport-22.2.x

#91186 sql: let `extendedEvalContext.QueueJob()` use txn from planner
  pkg/jobs/jobs_test.go
  pkg/sql/drop_schema.go
  pkg/sql/planner.go
  pkg/sql/table.go
Labels: backport-22.2.x

#91421 acceptance: skip broken test
  pkg/acceptance/compose_test.go
Labels: backport-22.1.x, backport-22.2.x, backport-22.2.0

#91317 ui: add loading the explain plan
  pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeStatementUtils.ts
  pkg/ui/workspaces/cluster-ui/src/api/decodePlanGistApi.ts
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/selectors/activeExecutionsCommon.selectors.ts
  pkg/ui/workspaces/cluster-ui/src/statementDetails/activeStatementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
Labels: backport-22.2.x

#90218 geo: fix panic when calling distance builtin with NaN coordinate
  pkg/geo/bbox.go
  pkg/geo/errors.go
  pkg/geo/geo.go
  pkg/geo/geogfn/distance.go
  pkg/geo/geogfn/topology_operations.go
  pkg/sql/logictest/testdata/logic_test/geospatial
Labels: backport-21.2.x, backport-22.1.x, backport-22.2.x

#91120 release: update OS packages before publishing to Red Hat Connect
  build/deploy-redhat/Dockerfile.in
Labels: C-enhancement, A-release, backport-21.2.x, T-release, backport-22.2.x, backport-22.2.0

#91542 cluster-ui: fix index usage stats reset for CC
  pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts
Labels: backport-22.1.x, backport-22.2.x

#91457 sql: catch panics in makeQueryIndexRecommendation
  pkg/sql/plan_opt.go
Labels: backport-22.1.x, backport-22.2.x

#91781 roachtest: always collect stats when restoring TPCH dataset
  pkg/cmd/roachtest/tests/multitenant_tpch.go
  pkg/cmd/roachtest/tests/tpc_utils.go
  pkg/cmd/roachtest/tests/tpchvec.go
Labels: backport-22.2.x

#91783 kvstreamer: fix recently introduced imprecise budget release
  pkg/kv/kvclient/kvstreamer/streamer.go
Labels: backport-22.2.x

#91824 storage: make `storage.mvcc.range_tombstones.enabled` tenant-readable
  pkg/storage/mvcc.go
Labels: backport-22.2.x

#91911 backupccl: fix bug in resolving encrypted backup manifests
  pkg/ccl/backupccl/backup_job.go
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/backupdest/backup_destination.go
  pkg/ccl/backupccl/backupencryption/encryption.go
  pkg/ccl/backupccl/backupinfo/manifest_handling.go
  pkg/ccl/backupccl/testdata/backup-restore/encrypted-backups
  pkg/jobs/jobspb/jobs.proto
Labels: backport-22.2.x, backport-22.2.0

#91756 upgrades: fix idempotence issue in system table role id migrations
  pkg/upgrade/upgrades/role_options_table_migration.go
  pkg/upgrade/upgrades/system_users_role_id_migration.go
Labels: backport-22.2.x

#86106 sql: make round builtin avoid negative zeros
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/sem/builtins/math_builtins.go
Labels: O-community

#91425 opt: don't drop LeftJoin filter during join ordering
  pkg/sql/opt/testutils/opttester/reorder_joins.go
  pkg/sql/opt/xform/join_order_builder.go
  pkg/sql/opt/xform/testdata/rules/join_order
Labels: backport-22.1.x, backport-22.2.x, backport-22.2.0

#90789 server: use a common logic for system log gc
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/server/BUILD.bazel
  pkg/server/purge_auth_session.go
  pkg/server/purge_auth_session_test.go
  pkg/server/server.go
  pkg/server/server_systemlog_gc.go
  pkg/server/server_systemlog_gc_test.go
  pkg/server/tenant.go
  pkg/server/testserver.go
  pkg/settings/registry.go
Labels: backport-22.1.x, backport-22.2.x

#92015 roachprod: use GCS instead of S3 to stage binaries
  pkg/roachprod/install/BUILD.bazel
  pkg/roachprod/install/staging.go
  pkg/roachprod/install/staging_test.go
Labels: C-enhancement, A-testing, T-testeng

#92075 sql: prevent error with ALTER DEFAULT PRIV on system db
  pkg/sql/alter_default_privileges.go
  pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_table
Labels: backport-22.1.x, backport-22.2.x

#92145 colexec: skip a couple slow tests under stress
  pkg/sql/colexec/mergejoiner_test.go
  pkg/sql/colexec/sorttopk_test.go
Labels: backport-22.2.x

#92233 envutil: add GOMEMLIMIT to safeVarRegistry
  pkg/util/envutil/env.go
Labels: backport-22.2.x

#91720 ttl: prevent schema changes on crdb_internal_expiration
  pkg/sql/alter_table.go
  pkg/sql/logictest/testdata/logic_test/row_level_ttl
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go
Labels: backport-22.1.x, backport-22.2.x

#92269 bazel: Add s390x support for libkrb5 cross-compilation
  build/toolchains/BUILD.bazel
  c-deps/BUILD.bazel
Labels: O-community, X-blathers-triaged

#91878 logictest: make a couple of cluster_locks queries more specific
  pkg/sql/logictest/testdata/logic_test/cluster_locks
Labels: backport-22.2.x

#92300 sql: fix bug with multi-statement implicit txn schema changes and Bind
  pkg/sql/conn_executor_prepare.go
  pkg/sql/pgwire/testdata/pgtest/schema_changes_implicit_txn_with_bind
Labels: backport-22.1.x, backport-22.2.x

#92299 c2c: create c2cSetup roachtest helper
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: T-disaster-recovery

#91978 cloud: add azure-blob as scheme
  pkg/cloud/azure/azure_connection.go
  pkg/cloud/azure/azure_storage.go
  pkg/cloud/azure/azure_storage_test.go
  pkg/cloud/userfile/BUILD.bazel
  pkg/cloud/userfile/file_table_storage_test.go
  pkg/cloud/userfile/filetable/filetabletest/BUILD.bazel
  pkg/cloud/userfile/filetable/filetabletest/file_table_read_writer_test.go
Labels: backport-22.2.x

#92346 backupccl: extend backupccl test timeout to 2 hours
  pkg/ccl/backupccl/BUILD.bazel
  pkg/cmd/generate-bazel-extra/main.go
  pkg/cmd/generate-bazel-extra/main_test.go
Labels: T-disaster-recovery, backport-22.2.x

#92405 actions: use GitHub PAT with project write permissions
  .github/workflows/add-mt-issues-to-project.yml
Labels: C-bug, T-dev-inf, A-ci

#92388 release-22.2: backupccl: extend backupccl test timeout to 2 hours
  pkg/ccl/backupccl/BUILD.bazel
  pkg/cmd/generate-bazel-extra/main.go
  pkg/cmd/generate-bazel-extra/main_test.go
Labels: T-disaster-recovery

#92408 sql: fix implicit txn flag in console
  pkg/sql/conn_executor_exec.go
  pkg/sql/logictest/testdata/logic_test/statement_statistics
Labels: backport-22.1.x, backport-22.2.x

#92396 util: improve allocation of combine functions
  pkg/util/slices.go
  pkg/util/slices_test.go
Labels: backport-22.1.x, backport-22.2.x

#91744 server: use a shared HTTP listener for all in-memory tenant servers
  pkg/base/config.go
  pkg/base/test_server_args.go
  pkg/ccl/serverccl/BUILD.bazel
  pkg/ccl/serverccl/server_controller_test.go
  pkg/cli/cliflags/flags.go
  pkg/cli/context.go
  pkg/cli/demo.go
  pkg/cli/democluster/context.go
  pkg/cli/democluster/demo_cluster.go
  pkg/cli/flags.go
  pkg/cli/start.go
  pkg/server/BUILD.bazel
  pkg/server/config.go
  pkg/server/debug/server.go
  pkg/server/server.go
  pkg/server/server_controller.go
  pkg/server/server_controller_test.go
  pkg/server/server_http.go
  pkg/server/server_sql.go
  pkg/server/tenant.go
  pkg/server/testserver.go
  pkg/util/netutil/net.go
  pkg/util/strings.go
Labels: A-multitenancy

#92501 ccl/sqlproxyccl: fix TestConnectionMigration test flake
  pkg/ccl/sqlproxyccl/conn_migration.go
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
Labels: backport-22.1.x, backport-22.2.x

#92102 opt: prevent null-rejection cycle with RightJoin
  pkg/sql/opt/norm/reject_nulls_funcs.go
Labels: backport-22.1.x, backport-22.2.x

#91511 release-22.1: backupccl: add 10TB TPCE restore nightly roachtest
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#92565 release-22.1: backupccl: restore2TB/nodes=10/with-pause
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#92118 kvserver: lower score threshold for mvcc GC eligibility
  pkg/kv/kvserver/mvcc_gc_queue.go
  pkg/kv/kvserver/mvcc_gc_queue_test.go
Labels: backport-22.1.x, backport-22.2.x

#92574 pgwire: unexport ServerMetrics, rename to tenantSpecificMetrics
  pkg/sql/pgwire/conn.go
  pkg/sql/pgwire/conn_test.go
  pkg/sql/pgwire/server.go
Labels: A-multitenancy

#92288 roachtest: Update liquibase blocklist
  pkg/cmd/roachtest/tests/liquibase.go
  pkg/cmd/roachtest/tests/liquibase_blocklist.go
Labels: backport-22.1.x, backport-22.2.x

#92625 ui: update sql error tooltip
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx
Labels: backport-22.1.x, backport-22.2.x

#92668 ui: fixes metrics page contention labels
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overview.tsx
Labels: backport-22.2.x

#92573 ui: fix sort setting on stmt/txn insights details
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/insightDetailsTables.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetailsOverviewTab.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx
Labels: backport-22.2.x

#92406 ccl/jwtauthccl: allow tenants to set jwt auth settings
  pkg/ccl/jwtauthccl/settings.go
Labels: backport-22.2.x

#92740 release 22-1: backupccl: fix restoreTPCE10TB test infra flake
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#92765 ui: ux improvements
  pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.module.scss
  pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx
  pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.module.scss
  pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
Labels: backport-22.2.x
