Repository cockroachdb/cockroach, pull requests merged in 2022-06, with the labels that each got.

#81996 sql: fix the propagation of some scan stats in some cases
  pkg/sql/colfetcher/colbatch_scan.go
  pkg/sql/colfetcher/index_join.go
  pkg/sql/execinfra/processorsbase.go
  pkg/sql/execstats/stats.go
  pkg/sql/explain_test.go
  pkg/sql/rowexec/inverted_joiner.go
  pkg/sql/rowexec/joinreader.go
  pkg/sql/rowexec/tablereader.go
  pkg/sql/rowexec/zigzagjoiner.go
Labels: backport-21.2.x, backport-22.1.x

#82187 clisqlshell: fix a bug where `\copy` would fail
  pkg/cli/clisqlshell/sql.go
  pkg/cli/interactive_tests/test_copy.tcl
Labels: backport-22.1.x

#82320 ccl/sqlproxyccl: fix panic on nil conn when failing to dial SQL backend
  pkg/ccl/sqlproxyccl/BUILD.bazel
  pkg/ccl/sqlproxyccl/backend_dialer.go
  pkg/ccl/sqlproxyccl/backend_dialer_test.go
Labels: backport-22.1.x

#82456 ppc64le - fix geoindex test failures TestS2GeographyIndexBasic and TestS2GeometryIndexBasic
  pkg/geo/geoindex/testdata/s2_geography
  pkg/geo/geoindex/testdata/s2_geometry
  pkg/geo/geoindex/utils_test.go
Labels: O-community, X-blathers-triaged

#82304 [CRDB-15892] SQL: NULL geography concatenation is inconsistent with Postgres
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
  pkg/sql/sem/tree/parse_array.go
  pkg/sql/sem/tree/pgwire_encode.go
  pkg/sql/types/types.go
  pkg/sql/types/types_test.go
Labels: O-community

#82517 release-22.1: roachtest: extract version map into separate file
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/fixtures.go
  pkg/cmd/roachtest/tests/predecessor_version.go
  pkg/cmd/roachtest/tests/predecessor_version.json
  pkg/cmd/roachtest/tests/registry.go
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: C-enhancement, A-release, T-release

#82518 release-21.2: roachtest: extract version map into separate file
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/predecessor_version.go
  pkg/cmd/roachtest/tests/predecessor_version.json
Labels: C-enhancement, A-release, T-release

#80993 server: react to decommissioning nodes by proactively enqueuing their replicas
  pkg/ccl/backupccl/utils_test.go
  pkg/ccl/multiregionccl/datadriven_test.go
  pkg/kv/kvserver/client_lease_test.go
  pkg/kv/kvserver/client_migration_test.go
  pkg/kv/kvserver/client_protectedts_test.go
  pkg/kv/kvserver/liveness/liveness.go
  pkg/kv/kvserver/replica_learner_test.go
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/kv/kvserver/scanner.go
  pkg/kv/kvserver/scanner_test.go
  pkg/kv/kvserver/store.go
  pkg/kv/kvserver/store_test.go
  pkg/kv/kvserver/stores_base.go
  pkg/kv/kvserver/testing_knobs.go
  pkg/roachpb/metadata_replicas.go
  pkg/server/admin.go
  pkg/server/admin_test.go
  pkg/server/decommission.go
  pkg/server/server.go
  pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber_client_test.go
  pkg/sql/importer/import_into_test.go
Labels: backport-22.1.x

#82523 builtins: implement to_timestamp for Unix epoch
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/timestamp
  pkg/sql/sem/builtins/builtins.go
Labels: O-community

#82641 sql: check for nils when adding placeholder types
  pkg/sql/conn_executor_prepare.go
  pkg/sql/pgwire/testdata/pgtest/as_of_system_time
Labels: backport-22.1.x

#82642 execbuilder: fix a rare flake
  pkg/sql/opt/exec/execbuilder/testdata/vectorize_local
Labels: backport-22.1.x

#82504 sql: soften AOST check to be a pgerror
  pkg/ccl/logictestccl/testdata/logic_test/as_of
  pkg/sql/conn_executor_exec.go
  pkg/sql/pgwire/testdata/pgtest/as_of_system_time
Labels: backport-22.1.x

#82666 sqlsmith: skip three builtins
  pkg/internal/sqlsmith/schema.go
Labels: backport-21.2.x, backport-22.1.x

#82390 ttljob: make TTL work for multi-tenant
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/settings/registry.go
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/main_test.go
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_test.go
Labels: backport-22.1.x

#82089 asim,kvserver: simulate rq rebalancing
  docs/RFCS/20150820_store_pool.md
  pkg/BUILD.bazel
  pkg/kv/kvserver/allocator/storepool/store_pool.go
  pkg/kv/kvserver/asim/BUILD.bazel
  pkg/kv/kvserver/asim/asim.go
  pkg/kv/kvserver/asim/asim_test.go
  pkg/kv/kvserver/asim/helpers.go
  pkg/kv/kvserver/asim/pacer.go
  pkg/kv/kvserver/asim/pacer_test.go
  pkg/kv/kvserver/asim/replicate_queue.go
  pkg/kv/kvserver/asim/replicate_queue_test.go
  pkg/kv/kvserver/asim/state/BUILD.bazel
  pkg/kv/kvserver/asim/state/change.go
  pkg/kv/kvserver/asim/state/change_test.go
  pkg/kv/kvserver/asim/state/config_loader.go
  pkg/kv/kvserver/asim/state/config_loader_test.go
  pkg/kv/kvserver/asim/state/exchange.go
  pkg/kv/kvserver/asim/state/exchange_test.go
  pkg/kv/kvserver/asim/state/helpers.go
  pkg/kv/kvserver/asim/state/impl.go
  pkg/kv/kvserver/asim/state/load.go
  pkg/kv/kvserver/asim/state/state.go
  pkg/kv/kvserver/asim/state/state_test.go
  pkg/kv/kvserver/asim/workload/BUILD.bazel
  pkg/kv/kvserver/asim/workload/workload.go
  pkg/kv/kvserver/asim/workload/workload_test.go
Labels: A-kv-simulation

#82819 release-22.1: Upgrade Go to version 1.17.11
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/bootstrap/bootstrap-debian.sh
  build/builder.sh
  build/builder/Dockerfile
  build/packer/teamcity-agent.sh
  pkg/cmd/roachtest/tests/go_helpers.go
Labels: C-enhancement, A-build-system, T-dev-inf

#82838 changefeedccl: reduce frequency logging when frontier is behind
  pkg/ccl/changefeedccl/changefeed_processors.go
Labels: O-community

#82889 authors: add Miral Gadani to authors
  AUTHORS
Labels: O-community, X-blathers-untriaged

#83162 backupccl: replace bulk-prs with bulk-io in CODEOWNERS
  .github/CODEOWNERS
Labels: T-bulkio, backport-21.1.x, backport-21.2.x, backport-22.1.x

#83103 ui: add period label to SQL Activity pages
  pkg/ui/workspaces/cluster-ui/src/pageConfig/pageConfig.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.tsx
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScale.module.scss
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/utils.ts
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx
Labels: backport-22.1.x

#83530 changefeedccl: do not error out on checkpoint during pause-requested
  pkg/ccl/changefeedccl/changefeed_processors.go
Labels: backport-22.1.x

#83622 build: remove crdb-protobuf-client node_modules with ui-maintainer-clean
  Makefile
Labels: backport-21.1.x, backport-21.2.x
