Repository cockroachdb/cockroach, pull requests merged in 2022-03, with the labels that each got.

#74174 logictest: randomly backup/restore in logic tests
  pkg/sql/logictest/BUILD.bazel
  pkg/sql/logictest/logic.go
Labels: T-bulkio

#77255 sql: fix crdb_internal.default_privileges
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges
Labels: backport-21.2.x

#77433 kvserver: limit concurrent consistency checks
  pkg/kv/kvserver/consistency_queue.go
  pkg/kv/kvserver/replica_consistency.go
  pkg/kv/kvserver/store.go
  pkg/sql/logictest/testdata/logic_test/builtin_function_notenant
Labels: backport-21.1.x, backport-21.2.x

#77316 cdc: filter schema changes that only backfill hidden columns
  pkg/ccl/changefeedccl/schemafeed/table_event_filter.go
  pkg/ccl/changefeedccl/schemafeed/table_event_filter_test.go
Labels: backport-21.2.x

#77797 changefeed: fix schema backfill after initial scan checkpoint
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
Labels: backport-21.2.x

#77804 build: disable release justification
  githooks/commit-msg
  githooks/prepare-commit-msg
Labels: backport-22.1.x

#77506 backupccl: warn core users that schedule backups without FULL BACKUP ALWAYS clause
  pkg/ccl/backupccl/create_scheduled_backup.go
Labels: A-bulkio, T-bulkio

#77640 changefeedccl: allow changefeeds specifying individual column families
  docs/generated/sql/bnf/create_changefeed_stmt.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/ccl/changefeedccl/alter_changefeed_stmt.go
  pkg/ccl/changefeedccl/alter_changefeed_test.go
  pkg/ccl/changefeedccl/changefeed_dist.go
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/validate.go
  pkg/ccl/changefeedccl/encoder.go
  pkg/ccl/changefeedccl/rowfetcher_cache.go
  pkg/ccl/changefeedccl/schemafeed/schema_feed.go
  pkg/cmd/docgen/diagrams.go
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/alter_changefeed
  pkg/sql/parser/testdata/changefeed
  pkg/sql/sem/tree/alter_changefeed.go
  pkg/sql/sem/tree/changefeed.go
Labels: backport-22.1.x

#77966 kv: Fix bug introduced in #77725
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
Labels: backport-22.1.x

#78031 kv: Increment catchup scan metric.
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
Labels: backport-22.1.x

#77837 sql: grouping metadata for stmt details
  docs/generated/http/full.md
  docs/generated/sql/functions.md
  pkg/roachpb/app_stats.proto
  pkg/server/combined_statement_stats.go
  pkg/server/serverpb/status.proto
  pkg/server/status_test.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_decoding.go
  pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding.go
  pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go
  pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.spec.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts
  pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.sagas.spec.ts
  pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx
  pkg/ui/workspaces/db-console/src/views/statements/statements.spec.tsx
Labels: backport-22.1.x

#78032 backupccl: allow user to run SHOW BACKUP on an encrypted incremental backup
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/manifest_handling.go
  pkg/ccl/backupccl/show.go
Labels: A-bulkio, T-bulkio, backport-21.2.x, backport-22.1.x

#77993 sql: error on new cursor with same name as portal
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_prepare.go
  pkg/sql/faketreeeval/evalctx.go
  pkg/sql/pgwire/testdata/pgtest/portals
  pkg/sql/sem/tree/eval.go
  pkg/sql/sem/tree/stmt.go
  pkg/sql/sql_cursor.go
Labels: backport-22.1.x

#77867 roachtest: update node death expectations in disk-full test
  pkg/cmd/roachtest/tests/disk_full.go
Labels: backport-21.2.x, backport-22.1.x

#77839 ccl: remove a stray comment
  pkg/ccl/ccl_init.go
Labels: T-dev-inf, T-server-and-security

#77798 kv/bulk: account for allocated kvBuf capacity in mem limiting
  pkg/kv/bulk/BUILD.bazel
  pkg/kv/bulk/buffering_adder.go
  pkg/kv/bulk/kv_buf.go
  pkg/kv/bulk/kv_buf_test.go
  pkg/kv/bulk/sst_batcher_test.go
  pkg/kv/kvserver/kvserverbase/bulk_adder.go
  pkg/settings/registry.go
  pkg/sql/importer/import_processor.go
  pkg/sql/rowexec/indexbackfiller.go
  pkg/util/mon/bytes_usage.go
Labels: backport-22.1.x

#78176 server: proper error handling in sessions API
  pkg/server/status.go
Labels: backport-22.1.x

#78148 rangefeedcache: use unbounded buffers during initial scans
  pkg/kv/kvclient/rangefeed/rangefeedbuffer/buffer.go
  pkg/kv/kvclient/rangefeed/rangefeedbuffer/buffer_test.go
  pkg/kv/kvclient/rangefeed/rangefeedcache/watcher.go
Labels: backport-22.1.x

#76146 kvserver: slow_replication_threshold := 1m
  docs/generated/settings/settings.html
  pkg/kv/kvserver/replica_circuit_breaker.go
Labels: O-community, X-blathers-triaged, backport-22.1.x

#78163 ttljob: fix range decoding bug
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_query_builder.go
  pkg/sql/ttl/ttljob/ttljob_query_builder_test.go
  pkg/sql/ttl/ttljob/ttljob_test.go
Labels: backport-22.1.x

#78199 changefeedccl: support end time option for changefeeds
  pkg/ccl/changefeedccl/alter_changefeed_test.go
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/options.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed_test.go
  pkg/ccl/changefeedccl/testfeed_test.go
  pkg/jobs/jobspb/jobs.proto
Labels: backport-22.1.x

#77726 spanconfig,kvserver: teach the GC job to respect tenant PTS records
  pkg/ccl/testccl/sqlccl/BUILD.bazel
  pkg/ccl/testccl/sqlccl/tenant_gc_test.go
  pkg/kv/kvserver/BUILD.bazel
  pkg/kv/kvserver/client_protectedts_test.go
  pkg/kv/kvserver/client_replica_test.go
  pkg/kv/kvserver/protectedts/ptutil/BUILD.bazel
  pkg/kv/kvserver/protectedts/ptutil/testutils.go
  pkg/spanconfig/protectedts_state_reader.go
  pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go
  pkg/spanconfig/spanconfigreconciler/reconciler.go
  pkg/sql/gcjob/BUILD.bazel
  pkg/sql/gcjob/gc_job.go
  pkg/sql/gcjob/refresh_statuses.go
  pkg/sql/gcjob/tenant_garbage_collection_test.go
  pkg/sql/gcjob_test/gc_job_test.go
Labels: backport-22.1.x

#78387 release: generate sentry panic
  pkg/cmd/release/BUILD.bazel
  pkg/cmd/release/pick_sha.go
  pkg/cmd/release/sentry.go
Labels: C-enhancement, A-release, T-release

#77834 sql: track index merging completion in mvcc-compatible backfiller
  pkg/sql/backfill.go
  pkg/sql/backfill_test.go
  pkg/sql/mvcc_backfiller.go
  pkg/sql/mvcc_backfiller_test.go
  pkg/sql/schema_changer_helpers_test.go
Labels: backport-22.1.x

#78317 sql: Simplify expected message requirement in TestAnonymizeStatementsForReporting
  pkg/sql/conn_executor_test.go
Labels: O-community, X-blathers-triaged

#78282 sql: fix get-login-dependencies with aborted txn
  pkg/sql/sessioninit/BUILD.bazel
  pkg/sql/sessioninit/cache.go
  pkg/sql/sessioninit/cache_test.go
  pkg/sql/user.go
Labels: backport-22.1.x

#78367 sql: support alter database alter super region
  docs/generated/sql/bnf/BUILD.bazel
  docs/generated/sql/bnf/alter_database_alter_super_region.bnf
  docs/generated/sql/bnf/alter_database_stmt.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/ccl/logictestccl/testdata/logic_test/super_regions
  pkg/gen/docs.bzl
  pkg/sql/alter_database.go
  pkg/sql/catalog/multiregion/region_config_test.go
  pkg/sql/opaque.go
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/alter_database_super_regions
  pkg/sql/sem/tree/alter_database.go
  pkg/sql/sem/tree/stmt.go
  pkg/sql/walk.go
Labels: backport-22.1.x

#78278 kvserver: measure the number of bytes sent/received via snapshots
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/raft_transport.go
  pkg/kv/kvserver/replica_command.go
  pkg/kv/kvserver/store_snapshot.go
  pkg/kv/kvserver/store_test.go
  pkg/ts/catalog/chart_catalog.go
Labels: backport-21.1.x, backport-21.2.x, backport-22.1.x

#78396 ccl/sqlproxyccl: add basic Balancer component for load balancing
  pkg/BUILD.bazel
  pkg/ccl/sqlproxyccl/BUILD.bazel
  pkg/ccl/sqlproxyccl/balancer/BUILD.bazel
  pkg/ccl/sqlproxyccl/balancer/balancer.go
  pkg/ccl/sqlproxyccl/balancer/balancer_test.go
  pkg/ccl/sqlproxyccl/balancer/pod.go
  pkg/ccl/sqlproxyccl/balancer/pod_test.go
  pkg/ccl/sqlproxyccl/connector.go
  pkg/ccl/sqlproxyccl/connector_test.go
  pkg/ccl/sqlproxyccl/proxy_handler.go
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
  pkg/ccl/sqlproxyccl/tenant/BUILD.bazel
  pkg/ccl/sqlproxyccl/tenant/directory_cache.go
  pkg/ccl/sqlproxyccl/tenant/directory_cache_test.go
  pkg/ccl/sqlproxyccl/tenant/entry.go
  pkg/ccl/sqlproxyccl/tenant/pod_test.go
Labels: backport-22.1.x

#78334 clusterversion: introduce a new cluster version for the new `StoreRebalancer`
  pkg/clusterversion/cockroach_versions.go
  pkg/clusterversion/key_string.go
Labels: backport-22.1.x

#78022 sql/schemachanger: set non-cancelable property on jobs correctly
  pkg/ccl/schemachangerccl/testdata/end_to_end/drop_multiregion
  pkg/sql/schemachanger/scbackup/job.go
  pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go
  pkg/sql/schemachanger/scexec/exec_mutation.go
  pkg/sql/schemachanger/scexec/scmutationexec/dependencies.go
  pkg/sql/schemachanger/scexec/scmutationexec/schema_change_job.go
  pkg/sql/schemachanger/scop/mutation.go
  pkg/sql/schemachanger/scpb/scpb.proto
  pkg/sql/schemachanger/scpb/state.go
  pkg/sql/schemachanger/scplan/internal/scstage/build.go
  pkg/sql/schemachanger/scplan/testdata/alter_table
  pkg/sql/schemachanger/scplan/testdata/create_index
  pkg/sql/schemachanger/scplan/testdata/drop_database
  pkg/sql/schemachanger/scplan/testdata/drop_schema
  pkg/sql/schemachanger/scplan/testdata/drop_sequence
  pkg/sql/schemachanger/scplan/testdata/drop_table
  pkg/sql/schemachanger/scplan/testdata/drop_type
  pkg/sql/schemachanger/scplan/testdata/drop_view
  pkg/sql/schemachanger/scrun/BUILD.bazel
  pkg/sql/schemachanger/scrun/scrun.go
  pkg/sql/schemachanger/testdata/alter_table_add_column
  pkg/sql/schemachanger/testdata/drop
  pkg/sql/schemachanger/testdata/index
Labels: backport-22.1.x

#78352 util/mon: mark monitor name and stack trace as safe from redacting
  pkg/base/config.go
  pkg/sql/buffer.go
  pkg/sql/buffer_util.go
  pkg/sql/colcontainer/diskqueue_test.go
  pkg/sql/colexec/colbuilder/BUILD.bazel
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/colexec/colexecargs/BUILD.bazel
  pkg/sql/colexec/colexecargs/monitor_registry.go
  pkg/sql/colexec/disk_spiller.go
  pkg/sql/colflow/BUILD.bazel
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/execinfra/processorsbase.go
  pkg/sql/planner.go
  pkg/sql/rowexec/BUILD.bazel
  pkg/sql/rowexec/sorter.go
  pkg/sql/rowflow/BUILD.bazel
  pkg/sql/rowflow/routers.go
  pkg/util/BUILD.bazel
  pkg/util/mon/bytes_usage.go
  pkg/util/smalltrace.go
  pkg/util/smalltrace_test.go
Labels: backport-21.2.x, backport-22.1.x

#78541 batcheval: reject addsstable if store capacity remaining too low
  pkg/kv/kvserver/batcheval/cmd_add_sstable.go
  pkg/kv/kvserver/batcheval/eval_context.go
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_eval_context_span.go
  pkg/roachpb/errors.go
  pkg/roachpb/errors.proto
Labels: backport-21.2.x, backport-22.1.x

#78543 jobs: show pause reason in SHOW JOBS + UI
  pkg/jobs/errors.go
  pkg/jobs/registry.go
  pkg/sql/crdb_internal.go
  pkg/ui/workspaces/db-console/src/views/jobs/jobStatusOptions.ts
Labels: backport-22.1.x

#78467 jobs, sql: Avoid jobs/scheduled jobs lock up.
  pkg/jobs/job_scheduler.go
  pkg/jobs/job_scheduler_test.go
  pkg/jobs/schedule_metrics.go
  pkg/sql/compact_sql_stats.go
  pkg/sql/sqlstats/persistedsqlstats/BUILD.bazel
  pkg/sql/sqlstats/persistedsqlstats/compaction_scheduling.go
  pkg/sql/sqlstats/persistedsqlstats/compaction_test.go
Labels: backport-21.2.x, backport-22.1.x

#78489 backupccl: set shorter closed_timestamp settings in datadriven tests
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/backup_test.go
Labels: backport-22.1.x

#78520 sql: fix handling of INT2VECTOR and OIDVECTOR in some cases
  pkg/sql/logictest/testdata/logic_test/array
  pkg/sql/rowenc/keyside/array.go
  pkg/sql/rowenc/valueside/array.go
  pkg/sql/rowenc/valueside/array_test.go
  pkg/sql/rowenc/valueside/decode.go
  pkg/sql/rowenc/valueside/legacy.go
  pkg/sql/sem/tree/cast.go
  pkg/sql/sem/tree/datum.go
Labels: backport-21.2.x, backport-22.1.x

#78460 ui: serve ETag header and respect If-None-Match req. header for assets
  pkg/BUILD.bazel
  pkg/server/server_test.go
  pkg/ui/BUILD.bazel
  pkg/ui/buildutil/BUILD.bazel
  pkg/ui/buildutil/hash_files.go
  pkg/ui/buildutil/hash_files_test.go
  pkg/ui/distccl/BUILD.bazel
  pkg/ui/distccl/distccl.go
  pkg/ui/distccl/distccl_no_bazel.go
  pkg/ui/distoss/BUILD.bazel
  pkg/ui/distoss/distoss.go
  pkg/ui/distoss/distoss_no_bazel.go
  pkg/ui/ui.go
  pkg/util/httputil/BUILD.bazel
  pkg/util/httputil/etag_handler_test.go
  pkg/util/httputil/handlers.go
Labels: backport-21.2.x, backport-22.1.x

#76466 spanconfig: verify migration for rangefeed enablement
  pkg/migration/migrations/BUILD.bazel
  pkg/migration/migrations/migrate_span_configs_test.go
  pkg/spanconfig/spanconfigjob/BUILD.bazel
  pkg/spanconfig/spanconfigjob/job.go
Labels: backport-22.1.x

#78964 sql: bump --max-sql-memory in a couple of tests
  pkg/sql/builtin_mem_usage_test.go
Labels: backport-22.1.x

#78703 colexecop: reset the internal batch in a test operator
  pkg/col/coldata/bytes.go
  pkg/sql/colexecop/testutils.go
Labels: backport-22.1.x

#79009 catalog: protobuf and cluster versioning for autostats table settings
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/clusterversion/cockroach_versions.go
  pkg/clusterversion/key_string.go
  pkg/sql/catalog/catpb/catalog.proto
  pkg/sql/catalog/descpb/structured.proto
  pkg/sql/catalog/tabledesc/validate_test.go
Labels: backport-22.1.x

#78472 sql: allow zone configuration cleanup in tenants
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/BUILD.bazel
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/tenant/indexes
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/tenant/protectedts
  pkg/sql/set_zone_config.go
Labels: backport-22.1.x

#77240 jobs: fix startable job num-runs overcount
  pkg/jobs/jobs.go
Labels: backport-21.2.x, backport-22.1.x

#79102 pgwire: avoid internal error for tuple in prepared statement
  pkg/sql/pgwire/pgwirebase/encoding.go
  pkg/sql/pgwire/testdata/pgtest/tuple
Labels: backport-22.1.x

#78705 sql,migration: ensure cluster version never regresses
  pkg/ccl/kvccl/kvtenantccl/BUILD.bazel
  pkg/ccl/kvccl/kvtenantccl/tenant_upgrade_test.go
  pkg/server/version_cluster_test.go
  pkg/sql/set_cluster_setting.go
Labels: backport-21.2.x, backport-22.1.x
