Repository cockroachdb/cockroach, pull requests merged in 2022-09, with the labels that each got.

#87242 colexec: memory accounting at row granularity in columnarizer
  Makefile
  pkg/gen/execgen.bzl
  pkg/sql/colexec/BUILD.bazel
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/colexec/columnarizer.go
  pkg/sql/colexec/columnarizer_test.go
  pkg/sql/colexec/execgen/cmd/execgen/BUILD.bazel
  pkg/sql/colexec/execgen/cmd/execgen/datum_to_vec_gen.go
  pkg/sql/colexec/execgen/cmd/execgen/rowtovec_gen.go
  pkg/sql/colexec/materializer_test.go
  pkg/sql/colexec/proj_utils_test.go
  pkg/sql/colexec/rowstovec.eg.go
  pkg/sql/colexec/rowstovec_test.go
  pkg/sql/colexec/rowstovec_tmpl.go
  pkg/sql/colexec/rowtovec.eg.go
  pkg/sql/colexec/rowtovec_test.go
  pkg/sql/colexec/rowtovec_tmpl.go
  pkg/sql/colexec/types_integration_test.go
  pkg/sql/colexec/values.go
  pkg/sql/colexec/values_test.go
  pkg/sql/colflow/vectorized_panic_propagation_test.go
  pkg/sql/colmem/allocator.go
  pkg/sql/distsql/columnar_utils_test.go
Labels: backport-22.1.x

#84727 kvserver/reports: replication_constraint_stats use voter constraints
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvserver/reports/constraint_stats_report.go
  pkg/kv/kvserver/reports/constraint_stats_report_test.go
  pkg/kv/kvserver/reports/critical_localities_report.go
  pkg/kv/kvserver/reports/critical_localities_report_test.go
  pkg/kv/kvserver/reports/reporter.go
  pkg/roachpb/metadata_replicas.go
Labels: backport-21.2.x, backport-22.1.x

#87336 cloud/amazon: add setting for buffered put-object uploads
  pkg/cloud/amazon/s3_storage.go
Labels: backport-21.2.x, backport-22.1.0

#87222 backupccl: prevent SHOW BACKUP with check_files failure when missing metadata
  pkg/ccl/backupccl/show.go
  pkg/ccl/backupccl/show_test.go
Labels: A-bulkio, T-bulkio

#86622 xform: ignore derived hash bucket lookup join cols for selectivity estimate
  pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index_query_plan
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_hash_sharded_index_query_plan
  pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index
  pkg/sql/opt/lookupjoin/constraint_builder.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/ops/relational.opt
  pkg/sql/opt/xform/join_funcs.go
  pkg/sql/opt/xform/testdata/rules/join
  pkg/sql/opt/xform/testdata/rules/join_order
Labels: backport-22.1.x

#87398 rowexec,colfetcher: introduce cluster settings for batch sizes
  pkg/sql/BUILD.bazel
  pkg/sql/colfetcher/BUILD.bazel
  pkg/sql/colfetcher/index_join.go
  pkg/sql/exec_util.go
  pkg/sql/execinfra/readerbase.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/rowexec/joinreader_strategies.go
  pkg/sql/sessiondatapb/session_data.proto
  pkg/sql/vars.go
Labels: backport-22.1.x

#87534 tree: fix population of function properties
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/sql/logictest/testdata/logic_test/distsql_builtin
  pkg/sql/logictest/tests/5node-disk/BUILD.bazel
  pkg/sql/logictest/tests/5node-disk/generated_test.go
  pkg/sql/logictest/tests/5node/generated_test.go
  pkg/sql/sem/tree/function_definition.go
Labels: backport-22.2.x

#87531 ui: hide non-tenant columns on the txn details page
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx
Labels: backport-22.1.x, backport-22.2.x

#87563 colmem: fix some issues with the memory limiting
  pkg/sql/colexec/colexecdisk/external_sort.go
  pkg/sql/colmem/allocator.go
  pkg/sql/colmem/allocator_test.go
Labels: backport-22.1.x, backport-22.2.x

#87567 sql: fix `is_generated` in `information_schema.column` table
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/workload/schemachange/operation_generator.go
Labels: backport-21.2.x, backport-22.1.x, backport-22.2.x

#87662 colbuilder: fix aggregation with no aggregate funcs
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/colexec/colexecbase/distinct.go
  pkg/sql/colexec/ordered_aggregator.go
  pkg/sql/logictest/testdata/logic_test/vectorize_agg
Labels: backport-22.1.x, backport-22.2.x

#86451 roachtest: add native libraries to test specification and verify
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster/cluster_interface.go
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/tests/activerecord.go
  pkg/cmd/roachtest/tests/costfuzz.go
  pkg/cmd/roachtest/tests/hibernate.go
  pkg/cmd/roachtest/tests/knex.go
  pkg/cmd/roachtest/tests/query_comparison_util.go
  pkg/cmd/roachtest/tests/ruby_pg.go
  pkg/cmd/roachtest/tests/schemachange_random_load.go
  pkg/cmd/roachtest/tests/sequelize.go
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/cmd/roachtest/tests/tlp.go
Labels: first-pr

#87650 docgen: fix missing backup diagram
  docs/generated/sql/bnf/backup.bnf
  pkg/cmd/docgen/diagrams.go
Labels: backport-22.2.x

#87562 opt: add scan constant columns to ordering if they are in the output
  pkg/sql/opt/ordering/scan.go
  pkg/sql/opt/xform/testdata/physprops/ordering
Labels: backport-22.1.x, backport-22.2.x

#87762 ui: add copy feature on idx recommendation
  pkg/ui/workspaces/cluster-ui/src/insights/indexActionBtn.module.scss
  pkg/ui/workspaces/cluster-ui/src/insights/indexActionBtn.tsx
  pkg/ui/workspaces/cluster-ui/src/text/text.module.scss
Labels: backport-22.2.x

#87793 ui: fix crash when there is no text
  pkg/ui/workspaces/cluster-ui/src/util/format.ts
Labels: backport-22.2.x

#87761 ui: change the unkown insight to the proper slow execution
  pkg/ui/workspaces/cluster-ui/src/insights/types.ts
  pkg/ui/workspaces/cluster-ui/src/insights/utils.ts
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx
  pkg/ui/workspaces/cluster-ui/src/util/docs.ts
Labels: backport-22.2.x

#87766 ui: remove link to stmt details when already on the page
  pkg/ui/workspaces/cluster-ui/src/insights/types.ts
  pkg/ui/workspaces/cluster-ui/src/insights/utils.ts
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/planDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/util/docs.ts
Labels: backport-22.2.x

#87632 ui: fix database index and grants table sort and url
  pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx
  pkg/ui/workspaces/cluster-ui/src/util/constants.ts
Labels: backport-22.1.x, backport-22.2.x

#87472 util,changefeedccl: streaminger csv writes
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/cdcevent/event.go
  pkg/ccl/changefeedccl/csv_test.go
  pkg/ccl/changefeedccl/encoder_csv.go
  pkg/util/encoding/csv/writer.go
  pkg/util/encoding/csv/writer_test.go
Labels: backport-22.1.x, backport-22.2.x

#87490 changefeedccl: add CHANGEFEED privilege
  pkg/ccl/changefeedccl/cdctest/testfeed.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/ccl/changefeedccl/testfeed_test.go
  pkg/ccl/logictestccl/testdata/logic_test/changefeed
  pkg/sql/catalog/catpb/privilege_test.go
  pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_sequence
  pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_table
  pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges
  pkg/sql/logictest/testdata/logic_test/grant_on_all_tables_in_schema
  pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option
  pkg/sql/logictest/testdata/logic_test/grant_sequence
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/show_default_privileges
  pkg/sql/privilege/kind_string.go
  pkg/sql/privilege/privilege.go
Labels: backport-22.2.x

#87825 awsdms: fix identifiers to be tagged by build version
  pkg/cmd/roachtest/tests/awsdms.go
Labels: backport-22.2.x

#87845 sql/gcjob: adopt setting to enable or disable use of delete range
  pkg/sql/gcjob/BUILD.bazel
  pkg/sql/gcjob/gc_job.go
  pkg/sql/gcjob/gcjobnotifier/BUILD.bazel
  pkg/sql/gcjob/gcjobnotifier/notifier.go
  pkg/sql/gcjob_test/BUILD.bazel
  pkg/sql/gcjob_test/gc_job_test.go
  pkg/sql/importer/BUILD.bazel
  pkg/sql/importer/import_stmt_test.go
  pkg/upgrade/upgrades/BUILD.bazel
  pkg/upgrade/upgrades/wait_for_del_range_in_gc_job.go
  pkg/upgrade/upgrades/wait_for_del_range_in_gc_job_test.go
Labels: backport-22.2.x

#87816 scgraph: make searching dep edges more efficient
  pkg/sql/schemachanger/scplan/internal/scgraph/BUILD.bazel
  pkg/sql/schemachanger/scplan/internal/scgraph/dep_edge_alloc.go
  pkg/sql/schemachanger/scplan/internal/scgraph/dep_edge_tree.go
  pkg/sql/schemachanger/scplan/internal/scgraph/dep_edge_tree_test.go
  pkg/sql/schemachanger/scplan/internal/scgraph/graph.go
  pkg/sql/schemachanger/scplan/internal/scgraph/iteration.go
Labels: backport-22.2.x

#87914 kvserver/reports: cancel context on stopper quiescence
  pkg/kv/kvserver/reports/reporter.go
Labels: backport-21.2.x, backport-22.1.x, backport-22.2.x

#87206 sql: minor fixes for opclasses in trigram indexes
  pkg/sql/catalog/catformat/index.go
  pkg/sql/create_index.go
  pkg/sql/create_table.go
  pkg/sql/logictest/testdata/logic_test/create_index
  pkg/sql/logictest/testdata/logic_test/trigram_indexes
Labels: backport-22.2.x

#87134 storage: assert iterator invariants
  pkg/storage/engine.go
  pkg/storage/intent_interleaving_iter.go
  pkg/storage/mvcc_incremental_iterator.go
  pkg/storage/pebble_iterator.go
  pkg/storage/point_synthesizing_iter.go
  pkg/storage/read_as_of_iterator.go
  pkg/storage/testdata/intent_interleaving_iter/basic
  pkg/storage/testdata/intent_interleaving_iter/error_race
  pkg/storage/testdata/intent_interleaving_iter/error_race_off
Labels: backport-22.2.x

#87467 changefeedccl: default to bare envelope for cdc expressions
  pkg/ccl/changefeedccl/avro.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/options.go
  pkg/ccl/changefeedccl/encoder_avro.go
  pkg/ccl/changefeedccl/encoder_json.go
  pkg/ccl/changefeedccl/sink_cloudstorage.go
  pkg/ccl/changefeedccl/sink_pubsub.go
  pkg/ccl/changefeedccl/sink_webhook.go
  pkg/ccl/changefeedccl/testfeed_test.go
Labels: backport-22.2.x

#87954 storage: remove `Reader.MVCCGet` and `MVCCGetProto`
  pkg/ccl/storageccl/engineccl/BUILD.bazel
  pkg/ccl/storageccl/engineccl/encrypted_fs_test.go
  pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go
  pkg/kv/kvserver/batch_spanset_test.go
  pkg/kv/kvserver/spanset/batch.go
  pkg/storage/batch_test.go
  pkg/storage/engine.go
  pkg/storage/engine_test.go
  pkg/storage/intent_reader_writer.go
  pkg/storage/mvcc_history_test.go
  pkg/storage/mvcc_test.go
  pkg/storage/pebble.go
  pkg/storage/pebble_batch.go
  pkg/storage/pebble_test.go
  pkg/testutils/storageutils/BUILD.bazel
  pkg/testutils/storageutils/mvcc.go
Labels: backport-22.2.x

#87991 backupccl: move backup proto package back to `backupccl`
  pkg/ccl/backupccl/backuppb/backup.proto
  pkg/ccl/backupccl/testdata/backup-restore/show-schedules-old
  pkg/ccl/backupccl/testdata/show_schedules_old/system_scheduled_jobs_22_1/rows/export171505a0801d4b400000000000000001-n796824123102855169.0.csv
Labels: backport-22.2.x

#87891 ci: fix invocation of `bazci` in `publish-sql-grammar-diagrams`
  build/teamcity/cockroach/publish-sql-grammar-diagrams-impl.sh
Labels: backport-22.2.x

#87861 backupccl: prevent restore schema_only from inserting stats
  pkg/ccl/backupccl/datadriven_test.go
  pkg/ccl/backupccl/restore_data_processor.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/testdata/backup-restore/restore-schema-only
  pkg/ccl/backupccl/testdata/backup-restore/restore-validation-only
  pkg/sql/exec_util.go
Labels: A-disaster-recovery, T-disaster-recovery, backport-22.2.x

#88054 release: fix roachtest release qualification script
  build/teamcity/internal/release/process/roachtest-release-qualification.sh
Labels: backport-22.2.x

#88022 storage: clean up multi-engine remnants
  pkg/kv/kvserver/spanset/batch.go
  pkg/storage/batch_test.go
  pkg/storage/engine.go
  pkg/storage/engine_test.go
  pkg/storage/intent_interleaving_iter.go
  pkg/storage/mvcc.go
  pkg/storage/mvcc_history_metamorphic_iterator_test.go
  pkg/storage/mvcc_incremental_iterator_test.go
  pkg/storage/mvcc_logical_ops_test.go
  pkg/storage/mvcc_stats_test.go
  pkg/storage/mvcc_test.go
  pkg/storage/pebble_iterator.go
  pkg/storage/point_synthesizing_iter.go
  pkg/storage/sst_test.go
Labels: backport-22.2.x

#86711 kvserver: update write bytes replica accounting
  pkg/kv/kvserver/replica_rankings_test.go
  pkg/kv/kvserver/replica_send.go
Labels: backport-22.2.x

#87863 export: unskip TestRandomParquetExports
  pkg/sql/importer/exportparquet_test.go
Labels: T-disaster-recovery, backport-22.1.x, backport-22.2.x

#88079 xform: fix wrong results from locality-optimized scan of inverted index
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/sql/opt/xform/scan_funcs.go
Labels: backport-22.1.x, backport-22.2.x

#87656 kvserver: add `admission.io.overload` metric
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/store.go
  pkg/ts/catalog/chart_catalog.go
  pkg/util/admission/admissionpb/io_threshold.go
Labels: backport-22.2.x

#87795 ui: add transaction exec id to blocking stmts table
  pkg/ui/workspaces/cluster-ui/src/activeExecutions/activeTransactionsTable/execContentionTable.tsx
Labels: backport-22.2.x

#88016 backupccl: remap IDs without conflicts
  pkg/ccl/backupccl/full_cluster_backup_restore_test.go
  pkg/ccl/backupccl/system_schema.go
Labels: backport-22.2.x

#88223 builtins: avoid panic for some uses of check_consistency
  pkg/sql/logictest/testdata/logic_test/builtin_function_notenant
  pkg/sql/sem/builtins/generator_builtins.go
Labels: backport-22.2.x

#88180 sql: populate information_schema.role_routine_grants with builtins
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/information_schema
Labels: backport-22.2.x

#88303 tenantrate: deflake testcloser
  pkg/kv/kvserver/tenantrate/BUILD.bazel
  pkg/kv/kvserver/tenantrate/limiter_test.go
Labels: backport-22.1.x, backport-22.2.x

#88288 kvserver: log retriable errors received during splits
  pkg/kv/kvserver/replica_command.go
Labels: backport-22.1.x, backport-22.2.x

#88268 kvserver: make consistency check symmetrical
  pkg/kv/kvserver/replica_consistency.go
Labels: backport-22.2.x

#87508 sql: add idx recs to sampled query telemetry
  docs/generated/eventlog.md
  pkg/sql/exec_log.go
  pkg/util/log/eventpb/json_encode_generated.go
  pkg/util/log/eventpb/telemetry.proto
Labels: backport-22.2.x

#88370 changefeedccl: add metric for size based flushes
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/changefeedccl/sink_cloudstorage.go
  pkg/ts/catalog/chart_catalog.go
Labels: backport-22.2.x

#88322 sql: fix telemetry panic for COPY
  pkg/sql/conn_executor.go
  pkg/sql/copy_in_test.go
  pkg/sql/exec_log.go
Labels: backport-22.2.x

#88304 sql: add eventlog for UDF relevant statements
  docs/generated/eventlog.md
  pkg/sql/alter_function.go
  pkg/sql/create_function.go
  pkg/sql/drop_function.go
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/util/log/eventpb/ddl_events.proto
  pkg/util/log/eventpb/eventlog_channels_generated.go
  pkg/util/log/eventpb/json_encode_generated.go
  pkg/util/log/eventpb/privilege_events.proto
Labels: backport-22.2.x

#88494 opt: fix error due to estimated row count must be non-zero
  pkg/sql/opt/constraint/span_test.go
  pkg/sql/opt/memo/testdata/stats/select
  pkg/sql/sem/tree/datum.go
Labels: backport-22.1.x, backport-22.2.x

#88530 colbuilder: avoid some allocations
  pkg/sql/colexec/colbuilder/execplan.go
Labels: backport-21.2.x, backport-22.1.x, backport-22.2.x

#88515 sql/opt: fix negative annotation caching for RegionConfig
  pkg/sql/opt/BUILD.bazel
  pkg/sql/opt/metadata_test.go
  pkg/sql/opt/table_meta.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
Labels: backport-22.2.x

#88461 ui: sql activity pages depend on node info
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetailsConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.stories.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageConnected.tsx
  pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx
  pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx
  pkg/ui/workspaces/db-console/src/views/transactions/transactionsPage.tsx
Labels: backport-22.1.x, backport-22.2.x

#88613 clusterversion: add stringer for EnableLeaseUpgrade
  pkg/clusterversion/key_string.go
Labels: backport-22.2.x

#87436 kv: update kvprober with quarantine pool
  pkg/kv/kvprober/BUILD.bazel
  pkg/kv/kvprober/helpers_test.go
  pkg/kv/kvprober/kvprober.go
  pkg/kv/kvprober/kvprober_test.go
  pkg/kv/kvprober/quarantine_pool.go
  pkg/kv/kvprober/quarantine_pool_test.go
  pkg/kv/kvprober/settings.go
  pkg/ts/catalog/chart_catalog.go
Labels: backport-22.1.x, backport-22.2.x

#88621 changefeedccl: use FmtExport in CSV feeds
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/encoder_csv.go
Labels: backport-22.2.x

#88441 opt: project required ordering for EXPLAIN to input columns
  pkg/sql/logictest/testdata/logic_test/explain
  pkg/sql/opt/ordering/statement.go
Labels: backport-22.1.x, backport-22.2.x

#88508 sql/stats: remove statistics forecasting time horizon
  pkg/sql/opt/exec/execbuilder/testdata/forecast1401
  pkg/sql/opt/exec/execbuilder/tests/local/generated_test.go
  pkg/sql/stats/forecast.go
Labels: backport-22.2.x

#88685 stats: fix missing auto stats on system tables on cluster startup
  pkg/sql/catalog/bootstrap/metadata.go
  pkg/sql/stats/BUILD.bazel
  pkg/sql/stats/automatic_stats.go
  pkg/sql/stats/automatic_stats_test.go
Labels: backport-22.2.x

#88573 storage: use metamorphic reader and writer in `TestMVCCHistories`
  pkg/storage/mvcc_history_test.go
Labels: backport-22.2.x

#88338 cliccl: remove the debug backup commands
  pkg/ccl/backupccl/targets.go
  pkg/ccl/cliccl/BUILD.bazel
  pkg/ccl/cliccl/debug_backup.go
  pkg/ccl/cliccl/debug_backup_test.go
Labels: backport-22.2.x

#88332 builtins: put check_consistency on DistsqlBlocklist
  pkg/sql/logictest/testdata/logic_test/builtin_function_notenant
  pkg/sql/planner.go
  pkg/sql/sem/builtins/generator_builtins.go
Labels: backport-22.2.x

#88462 sql/parser: fix ALTER PRIMARY KEY docs
  pkg/sql/parser/sql.y
Labels: backport-22.1.x, backport-22.2.x

#88598 sql: disallow UDFs with CTES and subqueries
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/opt/optbuilder/subquery.go
  pkg/sql/opt/optbuilder/with.go
Labels: backport-22.1.0, backport-22.2.x

#88843 release: use cockroach-sql in cockroach-sql archive
  pkg/cmd/publish-provisional-artifacts/main.go
Labels: C-bug, A-release, T-release

#88336 kvserver: mvcc gc queue - use gc full range hint
  pkg/kv/kvserver/batcheval/cmd_end_transaction.go
  pkg/kv/kvserver/batcheval/cmd_gc.go
  pkg/kv/kvserver/client_merge_test.go
  pkg/kv/kvserver/consistency_queue.go
  pkg/kv/kvserver/merge_queue.go
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/mvcc_gc_queue.go
  pkg/kv/kvserver/mvcc_gc_queue_test.go
  pkg/kv/kvserver/queue.go
  pkg/kv/kvserver/queue_concurrency_test.go
  pkg/kv/kvserver/queue_test.go
  pkg/kv/kvserver/raft_log_queue.go
  pkg/kv/kvserver/raft_snapshot_queue.go
  pkg/kv/kvserver/replica_gc_queue.go
  pkg/kv/kvserver/replicate_queue.go
  pkg/kv/kvserver/scanner.go
  pkg/kv/kvserver/split_queue.go
  pkg/kv/kvserver/testing_knobs.go
  pkg/kv/kvserver/ts_maintenance_queue.go
  pkg/roachpb/metadata.go
  pkg/storage/enginepb/mvcc.go
  pkg/ts/catalog/chart_catalog.go
Labels: backport-22.2.x

#87922 roachtest: add mixed version testing for the schema changer corpuses
  pkg/cli/declarative_corpus.go
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/mixed_version_decl_schemachange_compat.go
  pkg/cmd/roachtest/tests/registry.go
Labels: backport-22.2.x

#88828 server: fix panic when SendKVBatch is used with invalid req
  pkg/server/admin.go
Labels: backport-22.1.x, backport-22.2.x

#88963 sql: avoid using "rune" in COPY error message
  pkg/sql/copy.go
Labels: backport-22.2.x

#88874 opt: don't error when zero-cardinality group drops equivalency
  pkg/sql/opt/ordering/ordering.go
  pkg/sql/opt/xform/testdata/physprops/ordering
Labels: backport-21.2.x, backport-22.1.x, backport-22.2.x
