Repository cockroachdb/cockroach, pull requests merged in 2023-10, with the labels that each got.

#111538 colexecjoin: short-circuit cross join with empty right side if possible
  pkg/sql/colexec/colexecjoin/crossjoiner.go
  pkg/sql/logictest/testdata/logic_test/vectorize_local
  pkg/sql/logictest/tests/local/generated_test.go
Labels: backport-22.2.x, backport-23.1.x

#111552 release-23.1: kv: fix data race in `TestReplicaTxnIdempotency`
  pkg/kv/kvserver/replica_test.go
Labels: backport

#111553 release-22.2: kv: fix data race in `TestReplicaTxnIdempotency`
  pkg/kv/kvserver/replica_test.go
Labels: backport

#111574 c2c: skip TestStreamingRegionalConstraint
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
Labels: T-disaster-recovery

#111412 release-23.1: sql/copy: fix planning for vectorized COPY with nested renderNodes
  pkg/sql/copy/testdata/copy_from
  pkg/sql/distsql_physical_planner.go
  pkg/sql/values.go
Labels: backport

#111601 release-23.1: released CockroachDB version 23.1.11. Next version: 23.1.12
  pkg/build/version.txt
Labels: backport

#111580 release-23.1: configprofiles: avoid slices stomping each other
  pkg/configprofiles/profiles.go
  pkg/configprofiles/testdata/virtual-app-repl
Labels: backport

#111616 server: exit logging goroutine if work is done
  pkg/server/drain.go
Labels: backport-22.2.x, backport-23.1.x

#111394 release-22.2: roachtest: add --debug-always flag
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/test_test.go
Labels: backport

#111304 release-23.1: roachtest: refactor run/bench code
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/run.go
Labels: backport

#111744 release-23.1: cluster-ui: fix db page stories
  pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.stories.tsx
  pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.stories.tsx
  pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.stories.tsx
Labels: backport

#110600 release-23.1: roachprod: add GCE DNS Provider
  pkg/cmd/roachprod/main.go
  pkg/cmd/roachtest/cluster.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/cockroach.go
  pkg/roachprod/install/expander.go
  pkg/roachprod/install/services.go
  pkg/roachprod/install/services_test.go
  pkg/roachprod/multitenant.go
  pkg/roachprod/roachprod.go
  pkg/roachprod/vm/dns.go
  pkg/roachprod/vm/gce/BUILD.bazel
  pkg/roachprod/vm/gce/dns.go
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/local/dns.go
  pkg/roachprod/vm/local/dns_test.go
  pkg/roachprod/vm/local/local.go
Labels: backport

#111665 release-23.1: build: remove uses of `bindata`
  build/bazelutil/check.sh
  pkg/gen/BUILD.bazel
  pkg/gen/bindata.bzl
  pkg/gen/gen.bzl
  pkg/gen/genbzl/targets.go
  pkg/roachprod/vm/aws/BUILD.bazel
  pkg/roachprod/vm/aws/aws.go
  pkg/roachprod/vm/aws/config.go
  pkg/security/securitytest/BUILD.bazel
  pkg/security/securitytest/securitytest.go
Labels: backport

#111763 release-23.1: roachprod: retry dns lookup on network failures
  pkg/roachprod/vm/gce/dns.go
Labels: backport

#111743 release-23.1: build: build only the necessary arch for roachtests
  build/teamcity/cockroach/ci/tests/roachtest_stress_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_compile_bits.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_aws_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh
Labels: backport

#111652 release-23.1: ui: all xhr paths from db console are now relative
  pkg/ui/workspaces/cluster-ui/src/api/basePath.spec.ts
  pkg/ui/workspaces/cluster-ui/src/api/basePath.ts
  pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts
  pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/jobsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/livenessApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/nodesApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/sessionsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/sqlApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/sqlStatsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/statementsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/terminateQueryApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/userApi.ts
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPageConnected.spec.ts
  pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTableContent.tsx
  pkg/ui/workspaces/db-console/src/redux/analytics.ts
  pkg/ui/workspaces/db-console/src/util/dataFromServer.ts
  pkg/ui/workspaces/db-console/src/views/jwt/jwtAuthToken.tsx
Labels: backport

#111790 schemafeed: deflake TestTableHistoryIngestionTracking
  pkg/ccl/changefeedccl/schemafeed/schema_feed_test.go
Labels: backport-22.2.x, backport-23.1.x

#111578 backupccl: pause scheduled backup if resumed on different cluster
  pkg/ccl/backupccl/create_scheduled_backup_test.go
  pkg/ccl/backupccl/schedule_exec.go
  pkg/jobs/job_scheduler_test.go
Labels: T-disaster-recovery

#111785 release-23.1: server: reduce a flake under race
  pkg/server/settings_cache_test.go
Labels: backport

#111824 release-23.1: roachprod: enhance/clarify terminology
  pkg/cmd/roachprod/flags.go
  pkg/cmd/roachprod/main.go
  pkg/cmd/roachtest/cluster.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/cockroach.go
  pkg/roachprod/install/expander.go
  pkg/roachprod/install/services.go
  pkg/roachprod/install/services_test.go
  pkg/roachprod/multitenant.go
  pkg/roachprod/roachprod.go
Labels: backport

#111803 streamproducer: add verbose logging to span config event stream
  pkg/ccl/streamingccl/streamproducer/span_config_event_stream.go
Labels: T-disaster-recovery

#111792 release-23.1: schema: add insert/update/delete DML injection test
  pkg/sql/schemachanger/BUILD.bazel
  pkg/sql/schemachanger/dml_injection_test.go
  pkg/sql/schemachanger/main_test.go
  pkg/testutils/sqlutils/sql_runner.go
Labels: backport

#111841 roachtest: pass artifacts-literal flag to local fips roachtests
  build/teamcity/cockroach/ci/tests/local_roachtest_fips_impl.sh
Labels: C-bug, A-testing, T-testeng

#111804 streamingccl: verify backup schedule pauses after cutover
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/ccl/streamingccl/streamingest/alter_replication_job_test.go
  pkg/ccl/streamingccl/streamingest/datadriven_test.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/ccl/streamingccl/streamingest/testdata/backup_schedule_pauses_after_cutover
Labels: T-disaster-recovery

#111901 release-23.1: ui: do not show current time as a fall back for empty timestamps on Jobs pages
  pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsTable.tsx
  pkg/ui/workspaces/cluster-ui/src/jobs/util/duration.tsx
Labels: O-community, backport

#111871 release-23.1: kvcoord: add ambiguous commit tests
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/dist_sender_ambiguous_test.go
  pkg/kv/kvclient/kvcoord/replayed_commit_test.go
  pkg/kv/kvpb/batch.go
Labels: backport

#111911 pg_catalog: indoption was not encoded correctly
  pkg/sql/pg_catalog.go
  pkg/sql/pgwire/testdata/pgtest/int2vector
  pkg/sql/sem/tree/datum.go
Labels: backport-22.2.x, backport-23.1.x

#111951 release-23.1: go.mod: bump Pebble to 043c3795e649
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#111283 oidc: make redirect path after login configurable
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/oidcccl/BUILD.bazel
  pkg/ccl/oidcccl/authentication_oidc.go
  pkg/ccl/oidcccl/authentication_oidc_test.go
  pkg/server/server_controller_http.go
Labels: backport-22.2.x, backport-23.1.x

#111855 copy: fix slice out of bounds error in vectorized copy encoder
  pkg/sql/colenc/encode.go
  pkg/sql/copy/testdata/copy_from
Labels: backport-23.1.x

#111876 release-23.1: kv: enable replay protection for ambiguous writes on commits
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_ambiguous_test.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvpb/batch.go
  pkg/kv/kvpb/string_test.go
  pkg/kv/kvserver/batcheval/cmd_conditional_put.go
  pkg/kv/kvserver/batcheval/cmd_delete.go
  pkg/kv/kvserver/batcheval/cmd_delete_range.go
  pkg/kv/kvserver/batcheval/cmd_increment.go
  pkg/kv/kvserver/batcheval/cmd_init_put.go
  pkg/kv/kvserver/batcheval/cmd_put.go
  pkg/storage/mvcc.go
  pkg/storage/mvcc_history_test.go
  pkg/storage/testdata/mvcc_histories/ambiguous_writes
Labels: backport

#111775 release-23.1: deps: upgrade errors to 1.11.1
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cli/testdata/zip/partial1
  pkg/kv/kvpb/errors_test.go
  pkg/kv/kvserver/rditer/testdata/TestSelect/r1
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/opt/exec/execbuilder/testdata/explain_redact
  pkg/sql/pgwire/testdata/pgtest/tuple
  pkg/storage/testdata/mvcc_histories/conditional_put
  pkg/storage/testdata/mvcc_histories/conditional_put_write_too_old
  pkg/storage/testdata/mvcc_histories/export
  pkg/storage/testdata/mvcc_histories/export_fingerprint
  pkg/storage/testdata/mvcc_histories/export_fingerprint_no_timestamps
  pkg/storage/testdata/mvcc_histories/export_fingerprint_tenant
  pkg/storage/testdata/mvcc_histories/ignored_seq_nums_cput
  pkg/storage/testdata/mvcc_histories/range_tombstone_conflicts
  pkg/util/duration/parse_test.go
  pkg/util/rangedesc/testdata/scoped_iteration
  pkg/util/rangedesc/testdata/scoped_iteration_with_page_size
  pkg/util/rangedesc/testdata/scoped_iteration_with_splits
Labels: backport

#111568 sql: better inform the end-user about cluster virtualization
  pkg/ccl/logictestccl/tests/3node-tenant-multiregion/BUILD.bazel
  pkg/ccl/logictestccl/tests/3node-tenant-multiregion/generated_test.go
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/serverccl/settings_test.go
  pkg/cli/democluster/BUILD.bazel
  pkg/cli/democluster/demo_cluster.go
  pkg/cli/democluster/demo_cluster_test.go
  pkg/settings/registry.go
  pkg/sql/BUILD.bazel
  pkg/sql/descriptor.go
  pkg/sql/drop_tenant.go
  pkg/sql/logictest/testdata/logic_test/tenant
  pkg/sql/logictest/testdata/logic_test/tenant_from_tenant_hint
  pkg/sql/rename_tenant.go
  pkg/sql/restricted_system_interface.go
  pkg/sql/set_cluster_setting.go
  pkg/sql/show_fingerprints.go
  pkg/sql/show_tenant.go
  pkg/sql/tenant_accessors.go
  pkg/sql/tenant_capability.go
  pkg/sql/tenant_creation.go
  pkg/sql/tenant_deletion.go
  pkg/sql/tenant_gc.go
  pkg/sql/tenant_service.go
  pkg/sql/tenant_update.go
Labels: O-premortem

#111976 release-23.1: roachtest: require perf. tests to opt in via TestSpec.Benchmark
  pkg/cmd/roachtest/tests/admission_control_elastic_backup.go
  pkg/cmd/roachtest/tests/admission_control_elastic_cdc.go
  pkg/cmd/roachtest/tests/admission_control_index_overload.go
  pkg/cmd/roachtest/tests/admission_control_multi_store_overload.go
  pkg/cmd/roachtest/tests/admission_control_multitenant_fairness.go
  pkg/cmd/roachtest/tests/admission_control_snapshot_overload.go
  pkg/cmd/roachtest/tests/admission_control_tpcc_overload.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/multitenant_tpch.go
  pkg/cmd/roachtest/tests/pebble_write_throughput.go
  pkg/cmd/roachtest/tests/pebble_ycsb.go
  pkg/cmd/roachtest/tests/tpcdsvec.go
  pkg/cmd/roachtest/tests/tpchvec.go
Labels: backport

#111997 release-22.2: sql: fix flaky test TestSQLStatsCompactor
  pkg/sql/sqlstats/persistedsqlstats/compaction_test.go
Labels: backport

#112124 roachtest: mark npgsql type tests as passing
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
Labels: backport-23.2.x

#112144 release-23.1: roachtest: mark npgsql type tests as passing
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
Labels: backport

#111814 liveness: fix node count test to handle ambiguous errors
  pkg/kv/kvserver/liveness/client_test.go
Labels: backport-23.1.x

#111945 kvcoord: add "mixed version" test for `AmbiguousReplayProtection` flag
  pkg/kv/kvclient/kvcoord/dist_sender_ambiguous_test.go
Labels: backport-23.1.x

#112183 *: upgrade to Go 1.20.10
  WORKSPACE
  build/README.md
  build/bazelutil/distdir_files.bzl
  build/bootstrap/bootstrap-debian.sh
  build/packer/teamcity-agent.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
  pkg/cmd/roachtest/tests/go_helpers.go
Labels: backport-23.2.x

#112143 roachtest: fix reused cluster wipe failure handling
  pkg/cmd/roachtest/test_runner.go
Labels: backport-23.2.x

#112196 release-23.2: serverutils: TestURL query parameters with path
  pkg/ccl/serverccl/server_sql_test.go
  pkg/ccl/streamingccl/streamingest/replication_execution_details_test.go
  pkg/server/api_v2_ranges_test.go
  pkg/server/application_api/schema_inspection_test.go
  pkg/server/debug/debug_test.go
  pkg/server/testserver_http.go
  pkg/sql/jobs_profiler_execution_details_test.go
  pkg/testutils/serverutils/BUILD.bazel
  pkg/testutils/serverutils/test_server_shim.go
  pkg/testutils/serverutils/test_tenant_shim.go
  pkg/testutils/serverutils/test_url_test.go
Labels: backport

#112195 release-23.1: roachtest: upgrade roachtest ubuntu images to 22.04
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/spec/option.go
  pkg/cmd/roachtest/tests/activerecord.go
  pkg/cmd/roachtest/tests/asyncpg.go
  pkg/cmd/roachtest/tests/disk_stall.go
  pkg/cmd/roachtest/tests/ruby_pg.go
  pkg/cmd/roachtest/tests/sequelize.go
  pkg/cmd/roachtest/tests/sqlalchemy.go
  pkg/cmd/roachtest/tests/typeorm.go
  pkg/roachprod/install/install.go
  pkg/roachprod/vm/aws/config.json
  pkg/roachprod/vm/aws/support.go
  pkg/roachprod/vm/aws/terraform/aws-region/main.tf
  pkg/roachprod/vm/azure/azure.go
  pkg/roachprod/vm/azure/utils.go
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/gce/utils.go
  pkg/roachprod/vm/vm.go
Labels: backport

#112148 sql: add cluster version for udfs with mutations
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/clusterversion/cockroach_versions.go
  pkg/sql/logictest/testdata/logic_test/mixed_version_udf_mutations
  pkg/sql/logictest/testdata/logic_test/udf_delete
  pkg/sql/logictest/testdata/logic_test/udf_fk
  pkg/sql/logictest/testdata/logic_test/udf_insert
  pkg/sql/logictest/testdata/logic_test/udf_privileges
  pkg/sql/logictest/testdata/logic_test/udf_privileges_mutations
  pkg/sql/logictest/testdata/logic_test/udf_update
  pkg/sql/logictest/testdata/logic_test/udf_upsert
  pkg/sql/logictest/tests/cockroach-go-testserver-upgrade-to-master/BUILD.bazel
  pkg/sql/logictest/tests/cockroach-go-testserver-upgrade-to-master/generated_test.go
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-mixed-22.2-23.1/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/opt/optbuilder/builder.go
Labels: backport-23.2.x

#112193 roachtest: check cluster version after resetting cluster
  pkg/cmd/roachtest/tests/mixed_version_backup.go
Labels: backport-23.2.x

#112234 roachtest: use new context to fetch c2c debug zips
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: O-community, T-disaster-recovery

#112132 sctest: Skip `CREATE TEMP TABLE` and correctly handle `CREATE FUNCTION` with tagged quote
  pkg/sql/schemachanger/schemachanger_test.go
  pkg/sql/schemachanger/sctest/comparator.go
Labels: backport-23.2.x

#112240 release-22.2: backupccl: add logging to schedule PTS management
  pkg/ccl/backupccl/schedule_pts_chaining.go
Labels: backport

#112229 opt: fix bug in ReplaceMinWithLimit and ReplaceMaxWithLimit rules
  pkg/sql/opt/xform/groupby_funcs.go
  pkg/sql/opt/xform/rules/groupby.opt
  pkg/sql/opt/xform/testdata/rules/groupby
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#112238 release-23.2: scripts: update bump-pebble script
  scripts/bump-pebble.sh
Labels: backport

#112263 sql: use newly added aggregates for sql activity jobs
  pkg/sql/sql_activity_update_job.go
Labels: backport-23.2.x

#112135 release-22.2: sql: fix TestSQLStatsCompactor test flake
  pkg/sql/sqlstats/persistedsqlstats/compaction_test.go
Labels: backport

#112054 sql: fix statement tags for CREATE and DROP PROCEDURE
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/sql/logictest/testdata/logic_test/routine_schema_change
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/BUILD.bazel
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process_test.go
  pkg/sql/sem/tree/stmt.go
Labels: backport-23.2.x

#112317 release-22.2: kvserver: deflake test store capacity after split
  pkg/kv/kvserver/client_split_test.go
Labels: backport

#112299 release-22.2: opt: fix bug in ReplaceMinWithLimit and ReplaceMaxWithLimit rules
  pkg/sql/opt/xform/groupby_funcs.go
  pkg/sql/opt/xform/rules/groupby.opt
  pkg/sql/opt/xform/testdata/rules/groupby
Labels: backport

#112321 roachtest: maybe init tpcc with column families in backup-restore tests
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
Labels: T-disaster-recovery

#112037 kvserver,storage: logging and tracing of export requests
  pkg/kv/kvpb/api.proto
  pkg/kv/kvserver/batcheval/cmd_export.go
  pkg/kv/kvserver/batcheval/declare.go
  pkg/storage/intent_interleaving_iter.go
  pkg/storage/mvcc.go
  pkg/storage/mvcc_incremental_iterator.go
  pkg/storage/mvcc_test.go
  pkg/util/admission/elastic_cpu_work_handle.go
Labels: backport-23.1.x, backport-23.2.x

#112232 roachtest: automatically profile rebalance load roachtests
  pkg/cmd/roachtest/tests/rebalance_load.go
Labels: branch-release-23.2

#112149 logictest: unskip some mixed version tests
  pkg/sql/logictest/testdata/logic_test/mixed_version_bootstrap_tenant
  pkg/sql/logictest/testdata/logic_test/mixed_version_can_login
  pkg/sql/logictest/testdata/logic_test/mixed_version_new_system_privileges
  pkg/sql/logictest/testdata/logic_test/mixed_version_range_tombstones
  pkg/sql/logictest/tests/cockroach-go-testserver-upgrade-to-master/BUILD.bazel
  pkg/sql/logictest/tests/cockroach-go-testserver-upgrade-to-master/generated_test.go
Labels: backport-23.2.x

#112250 roachtest: fix deadlock in `getTestToRun`
  pkg/cmd/roachtest/work_pool.go
Labels: backport-23.2.x

#112115 kvserver,sql: speed up EventuallyFileOnlySnapshot acquisition in tests
  pkg/kv/kvserver/consistency_queue_test.go
  pkg/kv/kvserver/reset_quorum_test.go
  pkg/sql/logictest/BUILD.bazel
  pkg/sql/logictest/logic.go
  pkg/storage/pebble.go
Labels: backport-23.2.x

#112295 server: avoid missing service mode changes
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_manager_test.go
  pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/watcher.go
  pkg/server/server_controller_orchestration.go
  pkg/server/server_controller_test.go
Labels: backport-23.2.x

#112256 release-23.1: roachtest: backup-restore/mixed-version updates
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/option/connection_options.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper_test.go
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/registry.go
  pkg/roachpb/version.go
  pkg/roachpb/version_test.go
Labels: backport

#112404 release-23.2: demo: disable multitenancy by default
  pkg/cli/context.go
  pkg/cli/interactive_tests/test_demo.tcl
  pkg/cli/interactive_tests/test_demo_partitioning.tcl
Labels: backport

#112401 sql: handle nil value in DecodeAggregatedMetadataJSON func
  pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go
  pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go
Labels: O-community, backport-23.1.x, backport-23.2.x

#112472 release-23.2: logictest: fix backport skew
  pkg/sql/logictest/testdata/logic_test/udf
Labels: backport

#112457 release-23.2: Revert "Revert "kvstreamer: resolve a deadlock in an edge case""
  pkg/kv/kvclient/kvstreamer/results_buffer.go
  pkg/kv/kvclient/kvstreamer/streamer.go
Labels: backport

#112487 licenses: update CCT
  licenses/CCL.txt
Labels: backport-23.2.x

#112137 sql: make SHOW CREATE FUNCTION work with PLpgSQL
  pkg/sql/BUILD.bazel
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/show_create
Labels: backport-23.2.x

#112200 plpgsql: correctly handle parsing errors
  pkg/sql/parser/parse.go
  pkg/sql/plpgsql/parser/lexer.go
  pkg/sql/plpgsql/parser/plpgsql.y
  pkg/sql/plpgsql/parser/testdata/decl_header
  pkg/sql/plpgsql/parser/testdata/stmt_assign
  pkg/sql/plpgsql/parser/testdata/stmt_exec_sql
  pkg/sql/plpgsql/parser/testdata/stmt_fetch_move
  pkg/sql/plpgsql/parser/testdata/stmt_open
  pkg/sql/plpgsql/parser/testdata/stmt_return
Labels: backport-23.2.x

#112403 release-23.2: server: avoid missing service mode changes
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_manager_test.go
  pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/watcher.go
  pkg/server/server_controller_orchestration.go
  pkg/server/server_controller_test.go
Labels: backport

#112440 sctest: Fix bug where post-execution checks happens even in open txn
  pkg/sql/schemachanger/schemachanger_test.go
  pkg/sql/schemachanger/sctest/comparator.go
Labels: backport-23.2.x

#112507 roachtest: fix teamCityEscape to handle '\r' and unicode
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_impl_test.go
  pkg/cmd/roachtest/test_runner.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#112452 release-23.2: set devBranch to false and version.txt for beta.1
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/build/version.txt
  pkg/cli/testdata/declarative-rules/deprules
  pkg/cli/testdata/declarative-rules/invalid_version
  pkg/cli/testdata/declarative-rules/oprules
  pkg/clusterversion/cockroach_versions.go
  pkg/sql/catalog/bootstrap/bootstrap_test.go
  pkg/sql/catalog/bootstrap/testdata/testdata
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_system
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_tenant
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
Labels: do-not-merge, backport

#112228 cli: make debug zip and node status more likely to work by default
  pkg/cli/BUILD.bazel
  pkg/cli/auth.go
  pkg/cli/debug_job_trace.go
  pkg/cli/doctor.go
  pkg/cli/import.go
  pkg/cli/node.go
  pkg/cli/nodelocal.go
  pkg/cli/sql_client.go
  pkg/cli/sql_client_test.go
  pkg/cli/sql_shell_cmd.go
  pkg/cli/statement_diag.go
  pkg/cli/testdata/zip/testzip_shared_process_virtualization_with_default_tenant
  pkg/cli/userfile.go
  pkg/cli/zip.go
  pkg/cli/zip_tenant_test.go
  pkg/server/pgurl/pgurl.go
  pkg/server/pgurl/pgurl_test.go
Labels: backport-23.1.x, backport-23.2.x

#112562 release-23.1: backport changes to roachtest build scripts
  build/teamcity/cockroach/coverage/roachtest_nightly_gce.sh
  build/teamcity/cockroach/coverage/roachtest_nightly_gce_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_arch_util.sh
  build/teamcity/cockroach/nightlies/roachtest_compile_bits.sh
  build/teamcity/cockroach/nightlies/roachtest_compile_component.sh
Labels: backport

#112553 release-23.1: roachtest: tpcc: don't look at cloud during registration
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster/cluster_interface.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/tests/tpcc.go
Labels: backport

#112576 logictest: deflake new_schema_changer test
  pkg/sql/logictest/testdata/logic_test/new_schema_changer
Labels: backport-23.1.x, backport-23.2.x

#112422 schema: skip flaky TestAlterTableDMLInjection tests
  pkg/sql/schemachanger/dml_injection_test.go
Labels: backport-23.1.x, backport-23.2.x

#112622 release-23.1: roachtest: clean up artifacts zipping code
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/zip_util.go
  pkg/cmd/roachtest/zip_util_test.go
Labels: backport

#111863 release-23.1: ccl: add an option to perform a regionless RESTORE
  docs/generated/sql/bnf/restore_options.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_multiregion_rbr_test.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/backupccl/testdata/backup-restore/restore-regionless-alter-region
  pkg/ccl/backupccl/testdata/backup-restore/restore-regionless-on-regionless
  pkg/ccl/backupccl/testdata/backup-restore/restore-regionless-regional-by-row
  pkg/jobs/jobspb/jobs.proto
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/backup_restore
  pkg/sql/sem/tree/backup.go
Labels: backport, backport-23.1.12-rc

#112646 release-23.1: logictest: disable metamorphic testing for mixed version test
  pkg/sql/logictest/logic.go
Labels: backport

#112393 sql: remove redundant conditional paths
  pkg/sql/sem/tree/backup.go
Labels: O-community, X-blathers-untriaged

#112634 release-23.1: roachtest: mark ruby-pg and npgsql flaky tests
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
  pkg/cmd/roachtest/tests/ruby_pg_blocklist.go
Labels: backport

#112651 release-23.1: sqlstats: fix schema name for TestInsightsIntegrationForContention
  pkg/sql/sqlstats/insights/integration/insights_test.go
Labels: backport

#112640 release-23.1: roachtest: add support for collecting Go coverage
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/test/test_interface.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
  pkg/roachprod/install/scripts/start.sh
  pkg/roachprod/install/testdata/start/start.txt
Labels: backport

#111533 roachprod: support managing shared process virtual clusters
  pkg/cmd/roachprod/flags.go
  pkg/cmd/roachprod/main.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/cockroach.go
  pkg/roachprod/install/services.go
  pkg/roachprod/multitenant.go
  pkg/roachprod/roachprod.go
Labels: backport-23.1.x, backport-23.2.x

#112668 roachtest: bump previous version in multitenant-upgrade
  pkg/cmd/roachtest/tests/multitenant_upgrade.go
Labels: backport-23.2.x

#112691 sql/schemachanger: fix TableData element migration crash
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go
  pkg/sql/schemachanger/scpb/migration.go
  pkg/sql/schemachanger/scpb/state.go
  pkg/sql/schemachanger/scplan/testdata/alter_table_add_column
  pkg/sql/schemachanger/sctest/backup.go
  pkg/sql/schemachanger/sctest/framework.go
  pkg/sql/schemachanger/testdata/end_to_end/add_column_default_unique/add_column_default_unique.explain
  pkg/sql/schemachanger/testdata/end_to_end/add_column_default_unique/add_column_default_unique.side_effects
Labels: backport-23.2.x

#112563 sql: fix db/schema in information_schema.referential_constraints
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/fk
Labels: backport-23.1.x, backport-23.2.x

#112721 release-23.2: backupccl: retire bulkio.restore.remove_regions.enabled
  pkg/settings/registry.go
Labels: backport

#112710 roachtest: reenable Jepsen subcritical-skews test
  pkg/cmd/roachtest/tests/jepsen.go
Labels: backport-23.1.x, backport-23.2.x

#111653 sql: separate "internal key" and "display name" for system privileges
  pkg/ccl/backupccl/show.go
  pkg/gen/stringer.bzl
  pkg/jobs/jobsauth/authorization_test.go
  pkg/server/privchecker/privchecker.go
  pkg/server/user.go
  pkg/sql/alter_default_privileges.go
  pkg/sql/alter_table.go
  pkg/sql/authorization.go
  pkg/sql/catalog/catpb/default_privilege.go
  pkg/sql/catalog/catpb/privilege.go
  pkg/sql/catalog/catpb/privilege_test.go
  pkg/sql/catalog/catprivilege/default_privilege_test.go
  pkg/sql/catalog/dbdesc/database_test.go
  pkg/sql/crdb_internal.go
  pkg/sql/delegate/show_grants.go
  pkg/sql/grant_revoke.go
  pkg/sql/grant_revoke_system.go
  pkg/sql/grant_revoke_test.go
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/logictest/testdata/logic_test/grant_database
  pkg/sql/privilege/BUILD.bazel
  pkg/sql/privilege/kind.go
  pkg/sql/privilege/kind_string.go
  pkg/sql/privilege/privilege.go
  pkg/sql/privilege/privilege_test.go
  pkg/sql/repair.go
  pkg/sql/schemachanger/scbuild/builder_state.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/tree/alter_default_privileges.go
  pkg/sql/sem/tree/grant.go
  pkg/sql/sem/tree/revoke.go
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
Labels: backport-23.2.x

#112779 plpgql: implement special OTHERS exception-handling branch
  pkg/sql/logictest/testdata/logic_test/udf_plpgsql
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/optbuilder/plpgsql.go
  pkg/sql/opt/optbuilder/testdata/udf_plpgsql
  pkg/sql/routine.go
  pkg/sql/sem/tree/routine.go
Labels: backport-23.2.x

#112350 sql: fix sql activity cache for large cardinality
  docs/generated/sql/functions.md
  pkg/server/application_api/sql_stats_test.go
  pkg/server/combined_statement_stats.go
  pkg/sql/appstatspb/app_stats.go
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/array
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/opt/exec/execbuilder/testdata/observability
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sql_activity_update_job.go
  pkg/sql/sql_activity_update_job_test.go
Labels: backport-23.1.x, backport-23.2.x

#112735 streamingccl: reduce scan interval for testing
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
Labels: backport-23.2.x

#112773 release-23.1: roachprod: virtual cluster support work
  pkg/cmd/roachprod/flags.go
  pkg/cmd/roachprod/main.go
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/monitor.go
  pkg/cmd/roachtest/roachtestutil/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/utils.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/decommission_self.go
  pkg/cmd/roachtest/tests/decommissionbench.go
  pkg/cmd/roachtest/tests/disk_full.go
  pkg/cmd/roachtest/tests/disk_stall.go
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/import.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
  pkg/cmd/roachtest/tests/mixed_version_decl_schemachange_compat.go
  pkg/cmd/roachtest/tests/mixed_version_decommission.go
  pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go
  pkg/cmd/roachtest/tests/mixed_version_jobs.go
  pkg/cmd/roachtest/tests/mixed_version_schemachange.go
  pkg/cmd/roachtest/tests/multitenant_upgrade.go
  pkg/cmd/roachtest/tests/rebalance_load.go
  pkg/cmd/roachtest/tests/secondary_indexes.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go
  pkg/cmd/roachtest/tests/versionupgrade.go
  pkg/roachprod/install/BUILD.bazel
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/cockroach.go
  pkg/roachprod/install/cockroach_test.go
  pkg/roachprod/install/scripts/start.sh
  pkg/roachprod/install/services.go
  pkg/roachprod/install/session.go
  pkg/roachprod/install/start_template_test.go
  pkg/roachprod/install/testdata/start/start.txt
  pkg/roachprod/multitenant.go
  pkg/roachprod/roachprod.go
Labels: backport

#112795 release-23.1: opt: fix invalid st_union optimizations
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/opt/operator.go
Labels: backport

#112796 release-22.2: opt: fix invalid st_union optimizations
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/opt/operator.go
Labels: backport

#112827 c2c: deflake a few e2e tests
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/ccl/streamingccl/streamingest/alter_replication_job_test.go
  pkg/ccl/streamingccl/streamingest/datadriven_test.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
Labels: T-disaster-recovery, backport-23.2.x

#112873 clusterversion: remove redundant version gates introduced in 23.2
  pkg/clusterversion/cockroach_versions.go
  pkg/clusterversion/cockroach_versions_test.go
  pkg/sql/alter_index_visible.go
  pkg/sql/alter_table.go
  pkg/sql/catalog/tabledesc/validate.go
  pkg/sql/create_index.go
  pkg/sql/create_table.go
  pkg/sql/logictest/testdata/logic_test/mixed_version_procedure
  pkg/sql/logictest/testdata/logic_test/mixed_version_udf_mutations
  pkg/sql/opt/optbuilder/builder.go
  pkg/sql/opt/optbuilder/create_function.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
  pkg/upgrade/upgrades/upgrades.go
  pkg/workload/schemachange/operation_generator.go
Labels: backport-23.2.x

#112871 release-23.2: sql/schemachanger: fix TableData element migration crash
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go
  pkg/sql/schemachanger/scpb/migration.go
  pkg/sql/schemachanger/scpb/state.go
  pkg/sql/schemachanger/scplan/testdata/alter_table_add_column
  pkg/sql/schemachanger/sctest/backup.go
  pkg/sql/schemachanger/sctest/framework.go
  pkg/sql/schemachanger/testdata/end_to_end/add_column_default_unique/add_column_default_unique.explain
  pkg/sql/schemachanger/testdata/end_to_end/add_column_default_unique/add_column_default_unique.side_effects
Labels: backport

#112894 roachtest: use 3 nodes for splits/load test
  pkg/cmd/roachtest/tests/split.go
Labels: backport-23.1.x, backport-23.2.x

#112899 stats: harden stats collection code a bit
  pkg/sql/rowenc/encoded_datum.go
  pkg/sql/rowexec/sampler.go
  pkg/sql/stats/row_sampling.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#112904 roachtest: properly escape `'` in TeamCity service messages
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_impl_test.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#112586 storage: restore optimization for inline puts/deletes
  pkg/storage/mvcc.go
  pkg/storage/testdata/mvcc_histories/inline
  pkg/storage/testdata/mvcc_histories/replicated_locks
Labels: backport-23.2.x

#112860 release-23.2: sql: fix incorrectly stripping during fingerprinting
  pkg/sql/show_fingerprints.go
Labels: backport

#112965 release-22.2: acceptance: deflake test_demo_node_cmds
  pkg/cli/interactive_tests/test_demo_node_cmds.tcl
Labels: backport

#112905 release-23.2: opt: revert planning regression for queries with many indexes
  pkg/sql/opt/metadata.go
  pkg/sql/opt/table_meta.go
Labels: backport

#112906 release-23.1: sql: drop index can be incorrectly blocked for a TA
  pkg/sql/drop_index.go
  pkg/sql/logictest/testdata/logic_test/drop_index
Labels: backport

#112861 release-23.1: acceptance: skip TestDockerCLI/test_demo_multitenant
  pkg/cli/interactive_tests/test_demo_multitenant.tcl.disabled
Labels: backport

#113012 licenses: update licenses prior to 23.2 release
  licenses/BSD2-apache.arrow.go.arrow.txt
  licenses/BSD2-apache.arrow.go.v11.txt
  licenses/BSD2-rcrowley.go-metrics.txt
  licenses/BSD2-zeebo.xxh3.txt
  licenses/BSD3-apache.arrow.go.arrow.txt
  licenses/BSD3-apache.arrow.go.v11.txt
  licenses/BSD3-apache.thrift.lib.go.thrift.txt
  licenses/BSD3-blevesearch.snowballstem.txt
  licenses/BSD3-dave.dst.txt
  licenses/BSD3-klauspost.compress.txt
Labels: C-enhancement, A-release, T-release, backport-23.2.x

#112941 release-23.2: cli: raise timeout on TestUnavailableZip, refactor assertion logic
  pkg/cli/testdata/zip/unavailable
  pkg/cli/zip_test.go
Labels: backport

#112987 release-23.2: kvserver: disable allocator checks with `COCKROACH_DISABLE_LEADER_FOLLOWS_LEASEHOLDER`
  pkg/cmd/roachtest/tests/failover.go
  pkg/kv/kvserver/allocator/allocatorimpl/allocator.go
  pkg/kv/kvserver/store.go
Labels: backport

#112852 rangefeed: add `TestDBClientScan` debug logging
  pkg/kv/kvclient/rangefeed/db_adapter_external_test.go
Labels: backport-23.2.x

#112973 release-23.1: roachprod: automatically create admin user for secure clusters
  pkg/cmd/roachprod/flags.go
  pkg/cmd/roachprod/main.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/cockroach.go
  pkg/roachprod/multitenant.go
  pkg/roachprod/roachprod.go
Labels: backport

#112921 release-23.2: clusterversion: remove redundant version gates introduced in 23.2
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/clusterversion/cockroach_versions.go
  pkg/clusterversion/cockroach_versions_test.go
  pkg/sql/alter_index_visible.go
  pkg/sql/alter_table.go
  pkg/sql/catalog/tabledesc/validate.go
  pkg/sql/create_index.go
  pkg/sql/create_table.go
  pkg/sql/logictest/testdata/logic_test/mixed_version_procedure
  pkg/sql/logictest/testdata/logic_test/mixed_version_udf_mutations
  pkg/sql/opt/optbuilder/builder.go
  pkg/sql/opt/optbuilder/create_function.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
  pkg/upgrade/upgrades/upgrades.go
  pkg/workload/schemachange/operation_generator.go
Labels: backport

#113024 pkg/cli: update the delayed tenant id watcher to be more robust
  pkg/cli/cliflags/flags_mt.go
  pkg/cli/flags.go
  pkg/cli/flags_test.go
  pkg/cli/start.go
  pkg/server/config.go
  pkg/server/tenant.go
  pkg/server/tenant_delayed_id_set_test.go
Labels: backport-23.1.x, backport-23.2.x

#113084 release 23.2: c2c: deflake/remove some multinode tests
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
Labels: T-disaster-recovery, backport

#112919 server: skip decommission self under deadlock
  pkg/server/storage_api/decommission_test.go
Labels: backport-23.1.x, backport-23.2.x

#113019 sql: fix usage of streamer with multiple column families
  pkg/sql/colfetcher/index_join.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/rowexec/joinreader.go
  pkg/sql/sessiondatapb/session_data.proto
  pkg/sql/vars.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x, backport-23.1.12-rc

#113056 release-23.2: upgrade: Tune upgradeinterlockccl TTL for stress
  pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/local_test_util_test.go
  pkg/sql/sqlliveness/slstorage/slstorage.go
Labels: backport

#113070 sql/catalog: fix SHOW CREATE for columns with collated strings
  pkg/sql/logictest/testdata/logic_test/collatedstring
  pkg/sql/sem/tree/type_check.go
  pkg/sql/show_create_all_tables_builtin_test.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#113097 opt: add setting for provided ordering fix
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/optgen/exprgen/expr_gen.go
  pkg/sql/opt/ordering/BUILD.bazel
  pkg/sql/opt/ordering/ordering.go
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/optimizer.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-23.1.x, backport-23.2.x

#112356 roachtest: add backup-restore/small-ranges
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
Labels: T-disaster-recovery

#113130 streamingccl: skip TestTenantStreamingFailback under stressrace
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go
Labels: backport-23.2.x

#112720 release-23.1: sql: simplify and fix error handling from remote flows watcher
  pkg/sql/distsql_running.go
Labels: backport

#113068 release-23.1: kvstreamer: mark one setting as ApplicationLevel
  pkg/kv/kvclient/kvstreamer/avg_response_estimator.go
Labels: backport

#113139 release-23.1: server: skip decommission self under deadlock
  pkg/server/admin_test.go
Labels: backport

#113149 sql/logictest: skip unreliable mixed version tests
  pkg/sql/logictest/testdata/logic_test/mixed_version_procedure
  pkg/sql/logictest/testdata/logic_test/mixed_version_udf_execute_privileges
  pkg/sql/logictest/testdata/logic_test/mixed_version_udf_mutations
Labels: backport-23.2.x

#113077 release-23.1: scexec: remember to set `invertedIndexKinds` field for `AddIndexColumn` op
  pkg/sql/logictest/testdata/logic_test/trigram_indexes
  pkg/sql/schemachanger/scexec/scmutationexec/index.go
  pkg/sql/schemachanger/scplan/internal/opgen/opgen_index_column.go
  pkg/sql/schemachanger/scplan/testdata/create_index
Labels: backport

#113161 release-23.2: storage: check for replicated locks in CheckSSTConflicts
  pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go
  pkg/storage/sst.go
  pkg/storage/sst_test.go
Labels: backport

#112357 streamingccl: test that replicated backup fails post cutover
  pkg/ccl/streamingccl/streamingest/datadriven_test.go
  pkg/ccl/streamingccl/streamingest/testdata/jobs_post_cutover
Labels: T-disaster-recovery

#113076 release-23.2: sql: rename MANAGETENANT to MANAGEVIRTUALCLUSTER
  pkg/ccl/backupccl/show.go
  pkg/ccl/streamingccl/streamingest/stream_ingest_manager.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_manager_test.go
  pkg/gen/stringer.bzl
  pkg/jobs/jobsauth/authorization_test.go
  pkg/server/privchecker/privchecker.go
  pkg/server/user.go
  pkg/sql/alter_default_privileges.go
  pkg/sql/alter_table.go
  pkg/sql/authorization.go
  pkg/sql/catalog/catpb/default_privilege.go
  pkg/sql/catalog/catpb/privilege.go
  pkg/sql/catalog/catpb/privilege_test.go
  pkg/sql/catalog/catprivilege/default_privilege_test.go
  pkg/sql/catalog/dbdesc/database_test.go
  pkg/sql/crdb_internal.go
  pkg/sql/delegate/show_grants.go
  pkg/sql/grant_revoke.go
  pkg/sql/grant_revoke_system.go
  pkg/sql/grant_revoke_test.go
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/logictest/testdata/logic_test/grant_database
  pkg/sql/logictest/testdata/logic_test/show_tenant_fingerprints
  pkg/sql/logictest/testdata/logic_test/tenant
  pkg/sql/logictest/testdata/logic_test/tenant_builtins
  pkg/sql/privilege/BUILD.bazel
  pkg/sql/privilege/kind.go
  pkg/sql/privilege/kind_string.go
  pkg/sql/privilege/privilege.go
  pkg/sql/privilege/privilege_test.go
  pkg/sql/repair.go
  pkg/sql/schemachanger/scbuild/builder_state.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/builtins/replication_builtins.go
  pkg/sql/sem/tree/alter_default_privileges.go
  pkg/sql/sem/tree/grant.go
  pkg/sql/sem/tree/revoke.go
  pkg/sql/show_tenant.go
  pkg/sql/tenant_settings.go
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
Labels: backport

#113107 release-23.1.12-rc: sql: fix usage of streamer with multiple column families
  pkg/sql/colfetcher/index_join.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join_limit
  pkg/sql/rowexec/joinreader.go
  pkg/sql/sessiondatapb/session_data.proto
  pkg/sql/vars.go
Labels: backport

#113108 release-23.1: sql: fix usage of streamer with multiple column families
  pkg/sql/colfetcher/index_join.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join_limit
  pkg/sql/rowexec/joinreader.go
  pkg/sql/sessiondatapb/session_data.proto
  pkg/sql/vars.go
Labels: backport

#113109 release-22.2: sql: fix usage of streamer with multiple column families
  pkg/sql/colfetcher/index_join.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join_limit
  pkg/sql/rowexec/joinreader.go
  pkg/sql/sessiondatapb/session_data.proto
  pkg/sql/vars.go
Labels: backport

#113101 schemachanger: use bazel test sharding for comparator tests
  .github/CODEOWNERS
  build/teamcity/cockroach/nightlies/schema_changer_comparator_nightly_impl.sh
  pkg/BUILD.bazel
  pkg/cmd/generate-logictest-corpus/BUILD.bazel
  pkg/cmd/generate-logictest-corpus/main.go
  pkg/gen/schemachanger.bzl
  pkg/sql/logictest/BUILD.bazel
  pkg/sql/schemachanger/BUILD.bazel
  pkg/sql/schemachanger/comparator_generated_test.go
  pkg/sql/schemachanger/comparator_test.go
  pkg/sql/schemachanger/schemachanger_test.go
  pkg/sql/schemachanger/scpb/scpb.proto
  pkg/sql/schemachanger/sctest/sccomparatortestgen/BUILD.bazel
  pkg/sql/schemachanger/sctest/sccomparatortestgen/main.go
Labels: backport-23.2.x

#113141 allocator/plan: add `AllowVoterRemovalWhenNotLeader` testing knob
  pkg/kv/kvserver/allocator/allocatorimpl/allocator.go
  pkg/kv/kvserver/allocator/plan/replicate.go
  pkg/kv/kvserver/store.go
Labels: backport-23.1.x, backport-23.2.x

#113212 rangefeed: deflake `TestDBClientScan`
  pkg/kv/kvclient/rangefeed/db_adapter_external_test.go
Labels: backport-23.2.x

#113150 kvserver: do lazy map allocations in replicaFlowControl
  pkg/kv/kvserver/flow_control_replica.go
  pkg/kv/kvserver/flow_control_replica_integration.go
Labels: backport-23.2.x

#113153 release-23.1: kvserver: add metrics for raft (re-)proposals
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica_application_result.go
  pkg/kv/kvserver/replica_raft.go
  pkg/ts/catalog/chart_catalog.go
Labels: backport

#113167 admission: use ambient context in debug message
  pkg/util/admission/work_queue.go
Labels: backport-23.1.x, backport-23.2.x

#113173 kv: downgrade STAGING status in error during retry of failed parallel commit
  pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_committer_test.go
Labels: backport-23.2.x

#113224 c2c: only persist physical specs after initial plan
  pkg/ccl/streamingccl/streamingest/replication_execution_details.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_dist.go
  pkg/sql/exec_util.go
Labels: T-disaster-recovery, backport-23.2.x

#113114 roachtest: update hibernate test to use 6.3.1
  pkg/cmd/roachtest/tests/hibernate.go
  pkg/cmd/roachtest/tests/hibernate_blocklist.go
  pkg/cmd/roachtest/tests/java_helpers.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#113185 sql/stats: deflake TestStatsAreDeletedForDroppedTables
  pkg/sql/stats/delete_stats_test.go
Labels: backport-23.2.x

#113211 demo: wait for stopper to stop on shutdown
  pkg/acceptance/generated_cli_test.go
  pkg/cli/democluster/demo_cluster.go
  pkg/cli/interactive_tests/test_demo_multitenant.tcl
Labels: backport-23.1.x, backport-23.2.x

#113171 release-23.1: sql: PartitionSpan should only use healthy nodes in mixed-process mode
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/backup_tenant_test.go
  pkg/jobs/joberror/BUILD.bazel
  pkg/jobs/joberror/errors.go
  pkg/sql/distsql_physical_planner.go
Labels: backport

#113251 release-22.2: roachtest: update hibernate test to use 6.3.1
  pkg/cmd/roachtest/tests/hibernate.go
  pkg/cmd/roachtest/tests/hibernate_blocklist.go
  pkg/cmd/roachtest/tests/java_helpers.go
Labels: backport
