Repository cockroachdb/cockroach, pull requests merged in 2023-11, with the labels that each got.

#112613 jobs: handle retryable errors waiting for jobs
  pkg/jobs/BUILD.bazel
  pkg/jobs/registry_external_test.go
  pkg/jobs/wait.go
  pkg/sql/internal.go
Labels: backport-23.2.x

#113281 rangefeed: add `kv.rangefeed.push_txns.enabled`
  pkg/kv/kvserver/rangefeed/BUILD.bazel
  pkg/kv/kvserver/rangefeed/processor.go
  pkg/kv/kvserver/rangefeed/processor_test.go
  pkg/kv/kvserver/replica_rangefeed.go
  pkg/kv/kvserver/store.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#113311 roachtest: uninstall `snapd` for `dmsetup` disk stall tests
  pkg/cmd/roachtest/tests/disk_stall.go
Labels: backport-23.1.x, backport-23.2.x

#113320 roachprod: support config profiles
  pkg/roachprod/install/cockroach.go
Labels: backport-23.1.x, backport-23.2.x

#113004 release-22.2: sql: drop index can be incorrectly blocked for a TA
  pkg/sql/drop_index.go
  pkg/sql/logictest/testdata/logic_test/drop_index
  pkg/sql/pgwire/testdata/pgtest/notice
Labels: backport

#113599 sql: disable shared process tenant for TestTraceAnalyzer
  pkg/sql/execstats/traceanalyzer_test.go
Labels: skipped-test

#113510 release-23.2: storage: restore optimization for inline puts/deletes
  pkg/storage/mvcc.go
  pkg/storage/testdata/mvcc_histories/inline
  pkg/storage/testdata/mvcc_histories/replicated_locks
Labels: backport

#113585 bootstrap: don't automatically add `--config dev` for `bazel`
  build/bootstrap/bootstrap-debian.sh
Labels: backport-22.1.x, backport-22.2.x

#113597 release-23.1: roachtest: mark new npgsql tests as flaky
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
Labels: backport

#113546 roachtest: port import/mixed-versions to the new framework
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/import.go
  pkg/cmd/roachtest/tests/mixed_version_import.go
  pkg/cmd/roachtest/tests/registry.go
Labels: backport-23.2.x

#113111 kvcoord: fix error index in case of range split
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#113639 sql/schemachanger: prevent concurrent type desc changes
  pkg/sql/catalog/typedesc/type_desc.go
  pkg/sql/schemachanger/schemachanger_test.go
Labels: backport-23.2.x

#113615 schemachanger: skip TestCompareLegacyAndDeclarative under stressrace
  pkg/sql/schemachanger/schemachanger_test.go
Labels: backport-23.2.x

#111947 build: update roachtest scripts to use --suite instead of tags
  build/teamcity/cockroach/coverage/roachtest_nightly_gce_impl.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_write_throughput_impl.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_ycsb_impl.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_ycsb_race_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_aws_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh
  build/teamcity/internal/release/process/roachtest-release-qualification.sh
  build/teamcity/util/roachtest_util.sh
  pkg/cmd/roachtest/tests/fixtures.go
Labels: backport-23.2.x

#113681 roachtest: fix qps parse in kvrestart test
  pkg/cmd/roachtest/tests/kv.go
Labels: backport-23.1.x, backport-23.2.x

#113306 storage: correctly update the stats for rolled back deletes
  pkg/storage/mvcc.go
  pkg/storage/mvcc_stats_test.go
  pkg/storage/testdata/mvcc_histories/ignored_seq_nums_delete
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#113713 sql/schemachanger: apply admission control to merge phase of backfill
  pkg/sql/backfill/mvcc_index_merger.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#113710 ui: remove duplicates of metrics on tooltip
  pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx
Labels: backport-23.2.x

#113744 kvserver: deflake `TestReplicaCircuitBreaker_ExemptRequests`
  pkg/kv/kvserver/client_replica_circuit_breaker_test.go
  pkg/kv/kvserver/helpers_test.go
Labels: backport-23.1.x, backport-23.2.x

#108735 sql: don't bump external read timestamp for RC internal executor txns
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/kvclient/kvcoord/txn_test.go
  pkg/kv/mock_transactional_sender.go
  pkg/kv/sender.go
  pkg/kv/txn.go
  pkg/kv/txn_external_test.go
  pkg/sql/catalog/descs/txn_external_test.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/conn_executor_test.go
  pkg/sql/distsql_running.go
  pkg/sql/routine.go
  pkg/sql/tests/read_committed_test.go
Labels: backport-23.2.x

#113620 release-23.2: sqlstats: fix null columns for TestInsightsIntegrationForContention
  pkg/sql/sqlstats/insights/integration/insights_test.go
Labels: backport

#113742 logstore: pool MVCCStats to avoid hot path allocs
  pkg/kv/kvserver/logstore/logstore.go
Labels: backport-23.2.x

#113661 release-23.2: serverutils: probabilistic shared process virtual cluster
  pkg/base/BUILD.bazel
  pkg/base/test_server_args.go
  pkg/base/test_server_args_test.go
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/datadriven_test.go
  pkg/ccl/changefeedccl/sink_test.go
  pkg/ccl/importerccl/ccl_test.go
  pkg/ccl/serverccl/server_sql_test.go
  pkg/ccl/spanconfigccl/spanconfiglimiterccl/drop_table_test.go
  pkg/ccl/spanconfigccl/spanconfiglimiterccl/testdata/indexes
  pkg/ccl/spanconfigccl/spanconfiglimiterccl/testdata/limit
  pkg/ccl/spanconfigccl/spanconfiglimiterccl/testdata/partitioning
  pkg/ccl/spanconfigccl/spanconfiglimiterccl/testdata/tables
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
  pkg/ccl/testccl/authccl/BUILD.bazel
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/ccl/testccl/sqlccl/tenant_gc_test.go
  pkg/cli/gen.go
  pkg/cli/interactive_tests/test_demo_partitioning.tcl
  pkg/cli/zip_test.go
  pkg/server/application_api/metrics_test.go
  pkg/server/application_api/sessions_test.go
  pkg/server/application_api/sql_stats_test.go
  pkg/server/debug/debug_test.go
  pkg/server/storage_api/files_test.go
  pkg/server/testserver.go
  pkg/server/testserver_sqlconn.go
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/conn_executor_test.go
  pkg/sql/copy/copy_in_test.go
  pkg/sql/copy/copy_out_test.go
  pkg/sql/copy/copy_test.go
  pkg/sql/execstats/traceanalyzer_test.go
  pkg/sql/importer/exportcsv_test.go
  pkg/sql/importer/import_stmt_test.go
  pkg/sql/pgrepl/connect_test.go
  pkg/sql/pgrepl/extended_protocol_test.go
  pkg/sql/pgwire/auth_test.go
  pkg/sql/pgwire/conn_test.go
  pkg/sql/pgwire/pgtest_test.go
  pkg/sql/pgwire/pgwire_test.go
  pkg/sql/sessioninit/BUILD.bazel
  pkg/sql/sessioninit/cache_test.go
  pkg/sql/tests/allow_role_memberships_to_change_during_transaction_test.go
  pkg/sql/tests/autocommit_extended_protocol_test.go
  pkg/sql/tests/copy_file_upload_test.go
  pkg/sql/tests/drop_role_concurrent_session_test.go
  pkg/sql/tests/show_commit_timestamp_test.go
  pkg/testutils/serverutils/BUILD.bazel
  pkg/testutils/serverutils/api.go
  pkg/testutils/serverutils/options.go
  pkg/testutils/serverutils/test_server_shim.go
  pkg/util/tracing/tracer_external_test.go
Labels: backport

#113726 kvpb: add some more information to BatchRequest.SafeFormat
  pkg/kv/kvpb/batch.go
Labels: backport-23.2.x

#113635 release-23.1: roachtest: port import/mixed-versions to the new framework
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/import.go
  pkg/cmd/roachtest/tests/mixed_version_import.go
  pkg/cmd/roachtest/tests/registry.go
Labels: backport

#113758 release-23.1: roachtest: add backup-restore/small-ranges
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
Labels: T-disaster-recovery, backport

#113658 kvserver: fix reproposals test with pipelined writes
  pkg/kv/kvserver/replica_raft_test.go
Labels: backport-23.2.x

#113672 sql/tests: avoid dropping database in TestRandomSyntaxGeneration
  pkg/sql/tests/rsg_test.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#113646 kv: split LockConflictError, revive WriteIntentError over wire
  docs/generated/metrics/metrics.html
  pkg/ccl/backupccl/backup_processor.go
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvclient/kvcoord/priority_refresh_test.go
  pkg/kv/kvclient/kvcoord/testdata/savepoints
  pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go
  pkg/kv/kvclient/kvcoord/txn_test.go
  pkg/kv/kvpb/errordetailtype_string.go
  pkg/kv/kvpb/errors.go
  pkg/kv/kvpb/errors.proto
  pkg/kv/kvpb/errors_test.go
  pkg/kv/kvserver/concurrency/concurrency_control.go
  pkg/kv/kvserver/concurrency/lock_table_waiter.go
  pkg/kv/kvserver/concurrency/lock_table_waiter_test.go
  pkg/kv/kvserver/replica_closedts_test.go
  pkg/kv/txn_external_test.go
  pkg/roachpb/data.go
  pkg/sql/row/errors.go
Labels: backport-23.2.x

#113779 release-23.2: kvserver: prevent infinite lock discovery hazard on replayed writes
  pkg/kv/kvserver/batcheval/cmd_conditional_put.go
  pkg/kv/kvserver/batcheval/cmd_delete.go
  pkg/kv/kvserver/batcheval/cmd_delete_range.go
  pkg/kv/kvserver/batcheval/cmd_increment.go
  pkg/kv/kvserver/batcheval/cmd_init_put.go
  pkg/kv/kvserver/batcheval/cmd_put.go
  pkg/kv/kvserver/batcheval/result/BUILD.bazel
  pkg/kv/kvserver/batcheval/result/intent.go
  pkg/kv/kvserver/concurrency/lock_table.go
  pkg/kv/kvserver/replica_test.go
Labels: backport

#113777 sql/tests: use SFU with consistent lock ordering in Bank benchmark
  pkg/sql/tests/bank_test.go
Labels: backport-23.1.x, backport-23.2.x

#113712 sql/stats: don't use linear regression with NaN for stats forecasting
  pkg/sql/stats/BUILD.bazel
  pkg/sql/stats/forecast.go
  pkg/sql/stats/quantile.go
  pkg/sql/stats/quantile_test.go
  pkg/sql/stats/simple_linear_regression_test.go
  pkg/sql/stats/stats_cache.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#113652 sql: fix internal error from refcursor array comparisons
  docs/generated/sql/aggregates.md
  docs/generated/sql/functions.md
  docs/generated/sql/operators.md
  docs/generated/sql/window_functions.md
  pkg/ccl/changefeedccl/avro_test.go
  pkg/sql/colexec/colexecproj/projection_ops_test.go
  pkg/sql/logictest/testdata/logic_test/refcursor
  pkg/sql/opt/optbuilder/testdata/aggregate
  pkg/sql/opt/xform/testdata/rules/join_order
  pkg/sql/sem/builtins/aggregate_builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/tree/type_check.go
  pkg/sql/types/types.go
Labels: backport-23.2.x

#111986 sql: change type for RU estimates from integer to floating-point
  pkg/ccl/multitenantccl/tenantcostclient/query_ru_estimate_test.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/execstats/traceanalyzer.go
  pkg/sql/opt/exec/explain/output.go
  pkg/util/humanizeutil/count.go
Labels: O-community, X-blathers-triaged

#112920 sql: rename setting to sql.txn.read_committed_isolation.enabled
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_read_committed
  pkg/cmd/roachtest/tests/orm_helpers.go
  pkg/cmd/roachtest/tests/ycsb.go
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_test.go
  pkg/sql/logictest/testdata/logic_test/fk_read_committed
  pkg/sql/logictest/testdata/logic_test/hash_sharded_index_read_committed
  pkg/sql/logictest/testdata/logic_test/read_committed
  pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed
  pkg/sql/logictest/testdata/logic_test/txn
  pkg/sql/logictest/testdata/logic_test/unique_read_committed
  pkg/sql/opt/exec/execbuilder/testdata/explain_analyze
  pkg/sql/opt/exec/execbuilder/testdata/fk_read_committed
  pkg/sql/opt/exec/execbuilder/testdata/select_for_update_read_committed
  pkg/sql/opt/exec/execbuilder/testdata/unique_read_committed
  pkg/sql/pgwire/conn_test.go
  pkg/sql/tests/read_committed_test.go
Labels: backport-23.2.x

#113688 release-23.1: roachtest: harmonize GCE and AWS machine types + partial revert
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/spec/machine_type.go
  pkg/cmd/roachtest/tests/restore.go
  pkg/roachprod/cloud/cluster_cloud.go
  pkg/roachprod/vm/aws/aws.go
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/vm.go
  pkg/roachprod/vm/vm_test.go
Labels: backport

#113841 roachtest: remove 128 KiB bank payload load option from backup-restore/*
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
Labels: T-disaster-recovery, backport-23.1.x, backport-23.2.x

#113798 release-23.1: sql/stats: don't use linear regression with NaN for stats forecasting
  pkg/sql/stats/BUILD.bazel
  pkg/sql/stats/forecast.go
  pkg/sql/stats/quantile.go
  pkg/sql/stats/quantile_test.go
  pkg/sql/stats/simple_linear_regression_test.go
  pkg/sql/stats/stats_cache.go
Labels: backport

#113879 release-23.2: roachtest: add new passing npgsql test
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
Labels: backport-23.1.x, backport

#113666 server: wait for active configuration profiles during startup
  pkg/server/autoconfig/acprovider/provider.go
  pkg/server/autoconfig/auto_config_test.go
  pkg/server/server_sql.go
  pkg/server/testing_knobs.go
Labels: backport-23.2.x

#113784 release-23.1: roachtest: test AOST restore in backup-restore/* roachtests
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/mixed_version_backup.go
Labels: T-disaster-recovery, backport

#112800 release-23.1: acceptance: use single-node cluster and disable metamorphic constants
  pkg/acceptance/adapter_test.go
  pkg/acceptance/cluster/dockercluster.go
  pkg/acceptance/util_cluster.go
Labels: backport

#113872 build: fix colon in `roachtest_weekly_impl.sh`
  build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh
Labels: backport-23.2.x

#113752 release-23.2: roachtest: randomly run with runtime assertions by default
  build/teamcity/cockroach/nightlies/roachtest_compile_component.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_azure.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster/cluster_interface.go
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/test/test_interface.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/tests/allocator.go
  pkg/cmd/roachtest/tests/asyncpg.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/cdc.go
  pkg/cmd/roachtest/tests/copy.go
  pkg/cmd/roachtest/tests/import_cancellation.go
  pkg/cmd/roachtest/tests/kvbench.go
  pkg/cmd/roachtest/tests/multitenant_utils.go
  pkg/cmd/roachtest/tests/mvcc_gc.go
  pkg/cmd/roachtest/tests/pgjdbc.go
  pkg/cmd/roachtest/tests/schemachange.go
  pkg/cmd/roachtest/tests/split.go
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/cmd/roachtest/tests/tpce.go
  pkg/cmd/roachtest/tests/tpch_concurrency.go
  pkg/cmd/roachtest/tests/util.go
  pkg/roachprod/install/cockroach.go
Labels: backport

#113766 release-23.2: storage: correctly update the stats for rolled back deletes
  pkg/storage/mvcc.go
  pkg/storage/mvcc_stats_test.go
  pkg/storage/testdata/mvcc_histories/ignored_seq_nums_delete
Labels: backport

#113887 kv/kvnemesis: disable replicated lock validation
  pkg/kv/kvnemesis/testdata/TestValidate/weak_isolation_transaction_with_non-atomic_locking_replicated_get
  pkg/kv/kvnemesis/testdata/TestValidate/weak_isolation_transaction_with_non-atomic_locking_replicated_scan
  pkg/kv/kvnemesis/validator.go
Labels: backport-23.2.x

#113913 release: fix ubi9 openssl FIPS check
  build/release/teamcity-support.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh
  build/teamcity/internal/release/process/publish-cockroach-release.sh
Labels: C-bug, A-release, T-release, backport-23.2.x

#113909 release-23.2: build: update roachtest scripts to use --suite instead of tags
  build/teamcity/cockroach/coverage/roachtest_nightly_gce_impl.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_write_throughput_impl.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_ycsb_impl.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_ycsb_race_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_aws_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh
  build/teamcity/internal/release/process/roachtest-release-qualification.sh
  build/teamcity/util/roachtest_util.sh
  pkg/cmd/roachtest/tests/fixtures.go
Labels: backport

#113687 server: option to wait for default_target_cluster on connect
  pkg/multitenant/tenant_config.go
  pkg/server/BUILD.bazel
  pkg/server/admin.go
  pkg/server/server.go
  pkg/server/server_controller.go
  pkg/server/server_controller_accessors.go
  pkg/server/server_controller_http.go
  pkg/server/server_controller_orchestration.go
  pkg/server/server_controller_sql.go
  pkg/server/server_controller_test.go
Labels: backport-23.2.x

#113881 release-23.1.12-rc.FROZEN: sql/stats: don't use linear regression with NaN for stats forecasting
  pkg/sql/stats/BUILD.bazel
  pkg/sql/stats/forecast.go
  pkg/sql/stats/quantile.go
  pkg/sql/stats/quantile_test.go
  pkg/sql/stats/simple_linear_regression_test.go
  pkg/sql/stats/stats_cache.go
Labels: backport

#113564 release-23.1: rangefeed: add `kv.rangefeed.push_txns.enabled`
  pkg/kv/kvserver/rangefeed/BUILD.bazel
  pkg/kv/kvserver/rangefeed/processor.go
  pkg/kv/kvserver/rangefeed/processor_test.go
  pkg/kv/kvserver/replica_rangefeed.go
Labels: backport

#113696 roachtest: move schemachange/secondary-index-multi-version to new framework
  pkg/cmd/roachtest/tests/secondary_indexes.go
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: backport-23.2.x

#113987 kv: fix handling of non-txn'al locking requests in recomputeWaitQueues
  pkg/kv/kvserver/concurrency/lock_table.go
  pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks
Labels: backport-23.2.x

#113998 roachtest: revert recent changes to tpch_concurrency
  pkg/cmd/roachtest/tests/tpch_concurrency.go
Labels: backport-23.2.x

#113888 server: statement stats test ignores retry counts
  pkg/server/application_api/sql_stats_test.go
Labels: backport-23.2.x

#113826 multiregionccl,testutilsccl: deflake TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill
  pkg/ccl/testutilsccl/BUILD.bazel
  pkg/ccl/testutilsccl/alter_primary_key.go
Labels: backport-23.1.x, backport-23.2.x

#113714 ccl/backupccl: add BACKUP/RESTORE tests for procedures
  pkg/ccl/backupccl/testdata/backup-restore/procedures
Labels: backport-23.2.x

#113850 release-23.2: serverutils: log shared process mode for default test tenant
  pkg/testutils/serverutils/test_server_shim.go
Labels: backport

#114035 release-23.2: roachtest: move schemachange/secondary-index-multi-version to new framework
  pkg/cmd/roachtest/tests/secondary_indexes.go
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: backport

#114023 release-23.2: kv: fix handling of non-txn'al locking requests and recompute wait queues when locking requests drop out
  pkg/kv/kvserver/concurrency/lock_table.go
  pkg/kv/kvserver/concurrency/testdata/lock_table/shared_locks
Labels: backport

#113897 kv: add server-side metrics for {successful,failed} 1PC evaluation
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/replica_write.go
Labels: backport-23.2.x

#114037 release-23.2: multiregionccl,testutilsccl: deflake TestAlterTableLocalityRegionalByRowCorrectZoneConfigBeforeBackfill
  pkg/ccl/testutilsccl/BUILD.bazel
  pkg/ccl/testutilsccl/alter_primary_key.go
Labels: backport

#114057 release-23.2: storage: disable metamorphism of excises and EFOS
  docs/generated/settings/settings.html
  pkg/storage/pebble.go
Labels: backport

#113809 kvstreamer: add limit to how many eager batches are issued
  pkg/kv/kvclient/kvstreamer/BUILD.bazel
  pkg/kv/kvclient/kvstreamer/avg_response_estimator.go
  pkg/kv/kvclient/kvstreamer/avg_response_estimator_test.go
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/kv/kvclient/kvstreamer/streamer_accounting_test.go
  pkg/kv/kvclient/kvstreamer/streamer_test.go
  pkg/sql/colfetcher/index_join.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/row/kv_fetcher.go
  pkg/sql/rowexec/joinreader.go
  pkg/sql/sessiondatapb/session_data.proto
  pkg/sql/vars.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#113930 release-23.2: demo: Grant all capabilities to default tenant
  pkg/cli/democluster/BUILD.bazel
  pkg/cli/democluster/demo_cluster.go
  pkg/cli/democluster/demo_cluster_test.go
Labels: backport

#114070 release-23.2: streamingest: reset distSQL flow if a single node is lagging far behind
  pkg/ccl/streamingccl/settings.go
  pkg/ccl/streamingccl/streamingest/BUILD.bazel
  pkg/ccl/streamingccl/streamingest/node_lag_detector.go
  pkg/ccl/streamingccl/streamingest/node_lag_detector_test.go
  pkg/ccl/streamingccl/streamingest/replication_execution_details.go
  pkg/ccl/streamingccl/streamingest/replication_execution_details_test.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_dist.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/sql/exec_util.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
Labels: T-disaster-recovery, backport

#114067 roachtest: unskip c2c/BulkOps/full
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: T-disaster-recovery, backport-23.2.x

#113889 release-23.1: roachtest: move validate-after-version-upgrade to new framework
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/registry.go
  pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go
Labels: backport

#114162 github-pull-request-make: bump timeouts for `maybe-stress{,race}`
  pkg/cmd/github-pull-request-make/main.go
Labels: backport-23.2.x

#114113 kv: eliminate broken txn retry logic in replication reports
  pkg/kv/kvserver/reports/BUILD.bazel
  pkg/kv/kvserver/reports/constraint_stats_report.go
  pkg/kv/kvserver/reports/critical_localities_report.go
  pkg/kv/kvserver/reports/replication_stats_report.go
  pkg/kv/kvserver/reports/reporter.go
  pkg/kv/kvserver/reports/reporter_test.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#114148 Fix small typos
  pkg/ccl/backupccl/backup_test.go
  pkg/roachprod/multitenant.go
  pkg/sql/create_external_connection.go
  pkg/sql/walk.go
  pkg/util/hlc/timestamp.go
Labels: O-community

#114072 roachtest: trace query in restart/down-for-2m
  pkg/cmd/roachtest/tests/restart.go
Labels: branch-release-23.2

#113799 release-22.2: sql/stats: don't use linear regression with NaN for stats forecasting
  pkg/sql/stats/forecast.go
  pkg/sql/stats/quantile.go
  pkg/sql/stats/quantile_test.go
  pkg/sql/stats/stats_cache.go
Labels: backport

#113876 release-23.2: *: disable shared process test virtual cluster on some tests
  pkg/ccl/backupccl/backup_test.go
  pkg/server/application_api/stats_test.go
  pkg/sql/sqlstats/persistedsqlstats/datadriven_test.go
  pkg/sql/sqlstats/persistedsqlstats/flush_test.go
Labels: backport

#114049 release-23.2: serverutils: allow COCKROACH_TEST_TENANT to specify process mode
  pkg/testutils/serverutils/test_server_shim.go
Labels: backport

#114135 replicationutils: relax InitialScan timeout on race builds
  pkg/ccl/streamingccl/replicationtestutils/BUILD.bazel
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
Labels: T-disaster-recovery, backport-23.2.x

#114139 release-23.1: changefeedccl: Improve error handling
  pkg/ccl/changefeedccl/cdcevent/BUILD.bazel
  pkg/ccl/changefeedccl/cdcevent/event.go
Labels: backport

#114156 release-23.2: team: ignore TEAMS.yaml
  pkg/internal/team/.gitignore
Labels: backport-23.1.x, backport

#114150 release-23.2: spec: move machine type, zone, local ssd defaults out of the TestSpec and the registry
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/main_test.go
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/spec/option.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/test_registry_test.go
  pkg/cmd/roachtest/test_test.go
  pkg/cmd/roachtest/tests/disk_stall.go
  pkg/cmd/roachtest/tests/failover.go
  pkg/cmd/roachtest/tests/restore.go
  pkg/cmd/roachtest/tests/tpcc_test.go
Labels: backport

#114153 cli: deprecate the cockroach connect functionality
  pkg/cli/connect.go
  pkg/cli/connect_join.go
  pkg/cli/flags_test.go
Labels: release-blocker, branch-release-23.2, backport-23.2.x

#114123 kv: fix redaction in split logging
  pkg/kv/kvserver/merge_queue.go
  pkg/kv/kvserver/replica_command.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/split/objective.go
  pkg/kv/kvserver/split_delay_helper.go
  pkg/kv/kvserver/split_delay_helper_test.go
  pkg/kv/kvserver/split_queue.go
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
Labels: backport-23.2.x

#114111 release-23.2: backport distributed token bucket changes for provisioned tenants
  pkg/ccl/multitenantccl/tenantcostclient/BUILD.bazel
  pkg/ccl/multitenantccl/tenantcostclient/limiter.go
  pkg/ccl/multitenantccl/tenantcostclient/limiter_test.go
  pkg/ccl/multitenantccl/tenantcostclient/metrics.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side_test.go
  pkg/ccl/multitenantccl/tenantcostclient/test_utils.go
  pkg/ccl/multitenantccl/tenantcostclient/testdata/consumption
  pkg/ccl/multitenantccl/tenantcostclient/testdata/debt
  pkg/ccl/multitenantccl/tenantcostclient/testdata/external-io
  pkg/ccl/multitenantccl/tenantcostclient/testdata/fallback
  pkg/ccl/multitenantccl/tenantcostclient/testdata/fallback-throttled
  pkg/ccl/multitenantccl/tenantcostclient/testdata/large-request
  pkg/ccl/multitenantccl/tenantcostclient/testdata/low-ru
  pkg/ccl/multitenantccl/tenantcostclient/testdata/low-ru-race
  pkg/ccl/multitenantccl/tenantcostclient/testdata/low-throttling
  pkg/ccl/multitenantccl/tenantcostclient/testdata/no-ru
  pkg/ccl/multitenantccl/tenantcostclient/testdata/throttling
  pkg/ccl/multitenantccl/tenantcostclient/token_bucket.go
  pkg/ccl/multitenantccl/tenantcostclient/token_bucket_test.go
  pkg/ccl/multitenantccl/tenantcostserver/system_table.go
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/BUILD.bazel
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/tenant_token_bucket.go
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/tenant_token_bucket_test.go
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/testdata/fallback
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/testdata/reconfigure
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/testdata/request
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/testdata/update
  pkg/ccl/multitenantccl/tenantcostserver/testdata/cleanup
  pkg/ccl/multitenantccl/tenantcostserver/testdata/configure
  pkg/ccl/multitenantccl/tenantcostserver/testdata/instances
  pkg/ccl/multitenantccl/tenantcostserver/testdata/metrics
  pkg/ccl/multitenantccl/tenantcostserver/testdata/requests
  pkg/ccl/multitenantccl/tenantcostserver/testdata/seqnum
  pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go
  pkg/multitenant/tenant_usage.go
Labels: backport

#113939 kv: disable 1PC when weak isolation txns acquire replicated locks
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_committer_test.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/replica_write.go
Labels: backport-23.2.x

#114116 release-23.1: backport distributed token bucket changes for provisioned tenants
  pkg/ccl/multitenantccl/tenantcostclient/BUILD.bazel
  pkg/ccl/multitenantccl/tenantcostclient/limiter.go
  pkg/ccl/multitenantccl/tenantcostclient/limiter_test.go
  pkg/ccl/multitenantccl/tenantcostclient/metrics.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side_test.go
  pkg/ccl/multitenantccl/tenantcostclient/test_utils.go
  pkg/ccl/multitenantccl/tenantcostclient/testdata/consumption
  pkg/ccl/multitenantccl/tenantcostclient/testdata/debt
  pkg/ccl/multitenantccl/tenantcostclient/testdata/external-io
  pkg/ccl/multitenantccl/tenantcostclient/testdata/fallback
  pkg/ccl/multitenantccl/tenantcostclient/testdata/fallback-throttled
  pkg/ccl/multitenantccl/tenantcostclient/testdata/large-request
  pkg/ccl/multitenantccl/tenantcostclient/testdata/low-ru
  pkg/ccl/multitenantccl/tenantcostclient/testdata/low-ru-race
  pkg/ccl/multitenantccl/tenantcostclient/testdata/low-throttling
  pkg/ccl/multitenantccl/tenantcostclient/testdata/no-ru
  pkg/ccl/multitenantccl/tenantcostclient/testdata/throttling
  pkg/ccl/multitenantccl/tenantcostclient/token_bucket.go
  pkg/ccl/multitenantccl/tenantcostclient/token_bucket_test.go
  pkg/ccl/multitenantccl/tenantcostserver/system_table.go
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/BUILD.bazel
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/tenant_token_bucket.go
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/tenant_token_bucket_test.go
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/testdata/fallback
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/testdata/reconfigure
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/testdata/request
  pkg/ccl/multitenantccl/tenantcostserver/tenanttokenbucket/testdata/update
  pkg/ccl/multitenantccl/tenantcostserver/testdata/cleanup
  pkg/ccl/multitenantccl/tenantcostserver/testdata/configure
  pkg/ccl/multitenantccl/tenantcostserver/testdata/instances
  pkg/ccl/multitenantccl/tenantcostserver/testdata/metrics
  pkg/ccl/multitenantccl/tenantcostserver/testdata/requests
  pkg/ccl/multitenantccl/tenantcostserver/testdata/seqnum
  pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go
  pkg/multitenant/tenant_usage.go
Labels: backport

#114269 github-pull-request-make: pass timeout to stress directly
  pkg/cmd/github-pull-request-make/main.go
Labels: backport-23.2.x

#114263 execinfrapb: truncate ChangeAggregator spans in diagram
  pkg/sql/execinfrapb/flow_diagram.go
  pkg/sql/execinfrapb/flow_diagram_test.go
Labels: backport-23.1.x, backport-23.2.x

#113808 kvstreamer: remove redundant serialization / deserializion of results
  pkg/kv/kvclient/kvstreamer/results_buffer.go
  pkg/kv/kvclient/kvstreamer/streamer.go
Labels: backport-23.2.x

#114152 release-22.2: changefeedccl: Improve error handling
  pkg/ccl/changefeedccl/cdcevent/BUILD.bazel
  pkg/ccl/changefeedccl/cdcevent/event.go
Labels: backport

#114211 release-23.1: roachtest: clean up allocate cluster function
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/test_test.go
Labels: backport

#114193 roachprod: kill() creates log directory if it doesn't exist
  pkg/roachprod/install/cluster_synced.go
Labels: backport-23.1.x, backport-23.2.x

#114228 server: bump timeout in TestServerControllerWaitForDefaultCluster
  pkg/server/server_controller_test.go
  pkg/testutils/skip/skip.go
Labels: backport-23.2.x

#114258 release-23.2: go.mod: bump Pebble to b80b523e3215
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
Labels: backport

#114145 release-22.2: kvstreamer: add limit to how many eager batches are issued
  pkg/kv/kvclient/kvstreamer/BUILD.bazel
  pkg/kv/kvclient/kvstreamer/avg_response_estimator.go
  pkg/kv/kvclient/kvstreamer/avg_response_estimator_test.go
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/kv/kvclient/kvstreamer/streamer_test.go
  pkg/sql/colfetcher/index_join.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/row/BUILD.bazel
  pkg/sql/row/kv_fetcher.go
  pkg/sql/rowexec/joinreader.go
  pkg/sql/sessiondatapb/session_data.proto
  pkg/sql/vars.go
Labels: backport

#114378 roachtest: bump timeout for hibernate tests
  pkg/cmd/roachtest/tests/hibernate.go
Labels: backport-23.1.x, backport-23.2.x

#113722 server, cli: make debug zip tolerate corrupted log entries
  docs/generated/http/full.md
  pkg/cli/zip_per_node.go
  pkg/server/serverpb/status.proto
  pkg/server/status.go
  pkg/server/storage_api/logfiles_test.go
  pkg/util/log/format_crdb_v2.go
  pkg/util/log/format_crdb_v2_test.go
  pkg/util/log/format_json.go
  pkg/util/log/format_json_test.go
  pkg/util/log/log_decoder.go
  pkg/util/log/testdata/parse
  pkg/util/log/testdata/parse_json
Labels: O-community

#114326 roachtest: add online restore roachtest
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/online_restore.go
  pkg/cmd/roachtest/tests/registry.go
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#108543 concurrency: refactor LockStateInfo to display shared locks correctly with lock strength
  pkg/ccl/logictestccl/testdata/logic_test/cluster_locks_tenant
  pkg/kv/kvserver/concurrency/lock_table.go
  pkg/kv/kvserver/concurrency/testdata/lock_table/basic
  pkg/kv/kvserver/concurrency/testdata/lock_table/query
  pkg/roachpb/data.proto
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/cluster_locks
  pkg/sql/logictest/testdata/logic_test/select_for_share
Labels: O-community

#114385 release-23.1: kvstreamer: adjust recently added test
  pkg/kv/kvclient/kvstreamer/streamer_test.go
Labels: backport

#114351 release-23.2: admission: add tracing for admission work queue
  pkg/util/admission/BUILD.bazel
  pkg/util/admission/admissionpb/BUILD.bazel
  pkg/util/admission/admissionpb/admission_stats.proto
  pkg/util/admission/work_queue.go
Labels: backport

#114367 release-23.1: kvclient: stop reads on followers
  pkg/ccl/kvccl/kvfollowerreadsccl/BUILD.bazel
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvclient/kvcoord/replica_slice.go
  pkg/kv/kvclient/kvcoord/replica_slice_test.go
  pkg/server/server.go
  pkg/sql/physicalplan/replicaoracle/BUILD.bazel
  pkg/sql/physicalplan/replicaoracle/oracle.go
  pkg/sql/physicalplan/replicaoracle/oracle_test.go
  pkg/sql/physicalplan/span_resolver.go
Labels: backport

#114419 restore: add workload node to online restore roachtest
  pkg/cmd/roachtest/tests/online_restore.go
Labels: T-disaster-recovery

#113563 release-23.1: demo: wait for stopper to stop on shutdown
  pkg/cli/democluster/demo_cluster.go
  pkg/cli/interactive_tests/test_demo_multitenant.tcl
Labels: backport

#114479 release-23.1: sql: do not require system table privileges to use SHOW STATISTICS
  pkg/sql/explain_bundle_test.go
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/show_stats.go
Labels: backport

#114490 release: fix release qualification script
  build/teamcity/internal/release/process/roachtest-release-qualification.sh
Labels: C-bug, A-release, T-release, backport-23.2.x

#114489 release-23.2: multitenant: Extend retry for upgrade rpc
  pkg/upgrade/upgradecluster/tenant_cluster.go
Labels: backport

#113972 release-23.1: workloadccl: deflake TestImportFixture
  pkg/ccl/workloadccl/BUILD.bazel
  pkg/ccl/workloadccl/fixture_test.go
Labels: backport

#114435 release-23.1: clean up cluster reuse code in testRunner and fixes
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/work_pool.go
Labels: backport

#114054 release-22.2: importer: only check import *atomicity* in TestImportWorkerFailure
  pkg/sql/importer/import_stmt_test.go
Labels: backport

#114055 release-22.2.17-rc: importer: only check import *atomicity* in TestImportWorkerFailure
  pkg/sql/importer/import_stmt_test.go
Labels: backport

#114273 pkg/util/aggmetric: tick histogram windows in AggHistogram
  pkg/BUILD.bazel
  pkg/util/metric/BUILD.bazel
  pkg/util/metric/aggmetric/BUILD.bazel
  pkg/util/metric/aggmetric/agg_metric.go
  pkg/util/metric/aggmetric/agg_metric_test.go
  pkg/util/metric/aggmetric/histogram.go
  pkg/util/metric/hdrhistogram.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_test.go
  pkg/util/metric/tick/BUILD.bazel
  pkg/util/metric/tick/tick.go
  pkg/util/metric/tick_helper.go
Labels: backport-23.1.x, backport-23.2.x

#114432 release-23.2: roachtest: clean up command-line flags
  pkg/BUILD.bazel
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/roachtestflags/BUILD.bazel
  pkg/cmd/roachtest/roachtestflags/flags.go
  pkg/cmd/roachtest/roachtestflags/manager.go
  pkg/cmd/roachtest/roachtestflags/manager_test.go
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/slack.go
  pkg/cmd/roachtest/test_filter.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/test_test.go
Labels: backport

#114527 release-23.2: sql: use role membership cache to check for role existence
  pkg/bench/rttanalysis/testdata/benchmark_expectations
  pkg/ccl/streamingccl/streamproducer/replication_manager_test.go
  pkg/server/application_api/sql_stats_test.go
  pkg/sql/authorization.go
  pkg/sql/conn_executor.go
  pkg/sql/create_role.go
  pkg/sql/delegate/BUILD.bazel
  pkg/sql/delegate/show_grants.go
  pkg/sql/drop_role.go
  pkg/sql/internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/logictest/testdata/logic_test/drop_database
  pkg/sql/logictest/testdata/logic_test/drop_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/jobs
  pkg/sql/opt/cat/catalog.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/opt_catalog.go
  pkg/sql/planner.go
  pkg/sql/reassign_owned_by.go
  pkg/sql/sem/eval/context.go
  pkg/sql/sqlstats/sslocal/sql_stats_test.go
  pkg/sql/user.go
Labels: backport

#114452 sql: use 'background' QoS for COPY by default
  pkg/sql/copy_from.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-23.2.x

#114398 sql: introduce limit on number of retries in IntExec.Exec{Ex} methods
  pkg/sql/internal.go
  pkg/sql/internal_test.go
Labels: backport-23.2.x

#114538 ui: update `crl-email-subscription` styling
  pkg/ui/workspaces/db-console/src/views/dashboard/emailSubscription.styl
Labels: backport-23.1.x, backport-23.2.x

#114525 streamingccl: prevent node lag replanning starvation
  pkg/ccl/streamingccl/streamingest/node_lag_detector.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go
Labels: T-disaster-recovery, backport-23.2.x

#114529 release-23.1: ui: fix sql activity app filter on internal queries
  pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.spec.tsx
  pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.tsx
Labels: backport

#114488 release-23.2: sqlproxyccl: disable shared process test virtual cluster
  pkg/base/test_server_args.go
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
Labels: backport

#114485 release-23.2: server: populate `pgPreServer` on shared process `testTenant`
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/server/testserver.go
  pkg/sql/pgwire/auth_test.go
Labels: backport

#114286 mixedversion: refactor test context
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/context.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/context_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner_test.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_decl_schemachange_compat.go
  pkg/cmd/roachtest/tests/secondary_indexes.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: backport-23.1.x, backport-23.2.x

#114542 row: reduce the size of spans string
  pkg/roachpb/data.go
  pkg/roachpb/string_test.go
  pkg/sql/row/kv_batch_fetcher.go
  pkg/sql/row/kv_batch_streamer.go
Labels: backport-23.2.x

#114197 release-23.1: sql: only validate new regions when adding/dropping
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/mismatched_locality.go
  pkg/sql/alter_database.go
  pkg/sql/region_util.go
  pkg/sql/set_zone_config.go
  pkg/sql/set_zone_config_test.go
Labels: backport

#114618 roachtest: disable assertions and metamorphic constants
  pkg/cmd/roachtest/test_impl.go
Labels: backport-23.2.x

#114633 release-23.1: roachtest: use secure cluster and non-root user for kv workload
  pkg/cmd/roachtest/tests/kv.go
Labels: backport

#113894 release-23.1: roachtest: randomly run with runtime assertions by default
  build/teamcity/cockroach/nightlies/roachtest_compile_component.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster/cluster_interface.go
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/test/test_interface.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/tests/allocator.go
  pkg/cmd/roachtest/tests/asyncpg.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/copy.go
  pkg/cmd/roachtest/tests/import_cancellation.go
  pkg/cmd/roachtest/tests/kvbench.go
  pkg/cmd/roachtest/tests/multitenant_utils.go
  pkg/cmd/roachtest/tests/mvcc_gc.go
  pkg/cmd/roachtest/tests/pgjdbc.go
  pkg/cmd/roachtest/tests/schemachange.go
  pkg/cmd/roachtest/tests/split.go
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/cmd/roachtest/tests/tpce.go
  pkg/cmd/roachtest/tests/tpch_concurrency.go
  pkg/cmd/roachtest/tests/util.go
  pkg/roachprod/install/cockroach.go
Labels: backport

#114606 sql: use a session-bound internal executor for SQL cursors
  pkg/cmd/roachtest/tests/npgsql.go
  pkg/sql/logictest/testdata/logic_test/read_committed
  pkg/sql/sql_cursor.go
Labels: backport-23.1.x, backport-23.2.x

#114646 release-23.1: roachtest: disable assertions and metamorphic constants
  pkg/cmd/roachtest/test_impl.go
Labels: backport

#114651 release-23.1: roachtest: use dotnet v7 for npgsql test
  pkg/cmd/roachtest/tests/npgsql.go
Labels: backport

#114535 release-23.2: sql: use 'background' QoS for COPY by default
  pkg/sql/copy_from.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#114509 release-23.2: roachtest: remove cloud from registry and ClusterSpec
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/main_test.go
  pkg/cmd/roachtest/registry/registry_interface.go
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/spec/option.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/test_registry_test.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/test_test.go
  pkg/cmd/roachtest/tests/admission_control_database_drop.go
  pkg/cmd/roachtest/tests/admission_control_index_backfill.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/cdc.go
  pkg/cmd/roachtest/tests/prune_dangling_snapshots_and_disks.go
  pkg/cmd/roachtest/tests/tpcc_test.go
Labels: backport

#114617 sql: fix possible nil pointer in crdb_internal.cluster_locks
  pkg/security/certificate_manager_test.go
  pkg/security/securitytest/test_certs/README.md
  pkg/security/securitytest/test_certs/ca-client-tenant.crt
  pkg/security/securitytest/test_certs/ca-client-tenant.key
  pkg/security/securitytest/test_certs/ca.crt
  pkg/security/securitytest/test_certs/ca.key
  pkg/security/securitytest/test_certs/client-tenant.10.crt
  pkg/security/securitytest/test_certs/client-tenant.10.key
  pkg/security/securitytest/test_certs/client-tenant.11.crt
  pkg/security/securitytest/test_certs/client-tenant.11.key
  pkg/security/securitytest/test_certs/client-tenant.2.crt
  pkg/security/securitytest/test_certs/client-tenant.2.key
  pkg/security/securitytest/test_certs/client-tenant.20.crt
  pkg/security/securitytest/test_certs/client-tenant.20.key
  pkg/security/securitytest/test_certs/client.root.crt
  pkg/security/securitytest/test_certs/client.root.key
  pkg/security/securitytest/test_certs/client.testuser.crt
  pkg/security/securitytest/test_certs/client.testuser.key
  pkg/security/securitytest/test_certs/client.testuser2.crt
  pkg/security/securitytest/test_certs/client.testuser2.key
  pkg/security/securitytest/test_certs/client.testuser3.crt
  pkg/security/securitytest/test_certs/client.testuser3.key
  pkg/security/securitytest/test_certs/node.crt
  pkg/security/securitytest/test_certs/node.key
  pkg/security/securitytest/test_certs/regenerate.sh
  pkg/security/securitytest/test_certs/tenant-signing.10.crt
  pkg/security/securitytest/test_certs/tenant-signing.10.key
  pkg/security/securitytest/test_certs/tenant-signing.11.crt
  pkg/security/securitytest/test_certs/tenant-signing.11.key
  pkg/security/securitytest/test_certs/tenant-signing.2.crt
  pkg/security/securitytest/test_certs/tenant-signing.2.key
  pkg/security/securitytest/test_certs/tenant-signing.20.crt
  pkg/security/securitytest/test_certs/tenant-signing.20.key
  pkg/server/storage_api/certs_test.go
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/cluster_locks
Labels: backport-23.2.x

#114647 release-23.1: roachtest: port tpcc/mixed-headroom to the new framework + refactor test context
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/context.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/context_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner_test.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
  pkg/cmd/roachtest/tests/mixed_version_decl_schemachange_compat.go
  pkg/cmd/roachtest/tests/mixed_version_tenant_span_stats.go
  pkg/cmd/roachtest/tests/secondary_indexes.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: backport

#114652 sql: don't bump RC txn read timestamp before commit
  pkg/sql/conn_executor_exec.go
  pkg/sql/tests/BUILD.bazel
  pkg/sql/tests/read_committed_test.go
Labels: backport-23.2.x

#114623 opt: reduce planning time for queries with many joins
  pkg/sql/opt/bench/BUILD.bazel
  pkg/sql/opt/bench/bench_test.go
  pkg/sql/opt/bench/testdata/slow-schemas.sql
  pkg/sql/opt/colset.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/norm/testdata/rules/join
  pkg/sql/opt/props/col_stats_map.go
  pkg/sql/opt/props/func_dep.go
  pkg/sql/opt/testutils/testcat/BUILD.bazel
  pkg/sql/opt/testutils/testcat/test_catalog.go
Labels: backport-23.1.x, backport-23.2.x

#114486 release-23.2: roachtest: improvements to retry api
  pkg/cmd/roachprod-microbench/BUILD.bazel
  pkg/cmd/roachprod-microbench/cluster/BUILD.bazel
  pkg/cmd/roachprod-microbench/cluster/execute.go
  pkg/cmd/roachprod-microbench/util.go
  pkg/cmd/roachprod-stress/BUILD.bazel
  pkg/cmd/roachprod-stress/main.go
  pkg/cmd/roachprod/main.go
  pkg/cmd/roachtest/cluster.go
  pkg/roachprod/install/BUILD.bazel
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/cluster_synced_test.go
  pkg/roachprod/install/cockroach.go
  pkg/roachprod/install/download.go
  pkg/roachprod/install/install.go
  pkg/roachprod/install/run_options.go
  pkg/roachprod/install/staging.go
  pkg/roachprod/prometheus/prometheus.go
  pkg/roachprod/roachprod.go
Labels: backport

#114713 release-23.2: roachprod: garbage collect DNS records
  pkg/roachprod/cloud/BUILD.bazel
  pkg/roachprod/cloud/cluster_cloud.go
  pkg/roachprod/cloud/gc.go
  pkg/roachprod/roachprod.go
  pkg/roachprod/vm/dns.go
  pkg/roachprod/vm/gce/dns.go
  pkg/roachprod/vm/local/dns.go
  pkg/roachprod/vm/local/local.go
Labels: backport

#114736 streamingccl: deflake TestStreamingMismatchedMRDatabase
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
Labels: T-disaster-recovery, backport-23.2.x

#95332 ci: separate location for customized builds
  build/teamcity/internal/release/process/make-and-publish-build-artifacts.sh
  build/teamcity/internal/release/process/make-and-publish-build-tagging.sh
  scripts/tag-custom-build.sh
Labels: C-enhancement, T-dev-inf, A-ci, backport-23.1.x, backport-23.2.x

#114754 release-23.1: mixedversion: use datadriven framework when asserting on test plans
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/basic_test_mixed_version_hooks
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/concurrent_after_upgrade_finalized
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/concurrent_on_startup
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/multiple_upgrades
Labels: backport

#114720 release-23.2: roachprod: use gcloud CLI instead of net.LookupSRV
  pkg/roachprod/install/services.go
  pkg/roachprod/vm/dns.go
  pkg/roachprod/vm/gce/BUILD.bazel
  pkg/roachprod/vm/gce/dns.go
  pkg/roachprod/vm/local/dns.go
  pkg/roachprod/vm/local/dns_test.go
Labels: backport

#114779 sem/tree: add unredacted info to some assertions
  pkg/sql/sem/tree/constant.go
  pkg/sql/sem/tree/datum.go
  pkg/sql/sem/tree/eval.go
  pkg/sql/sem/tree/expr.go
  pkg/sql/sem/tree/parse_string.go
  pkg/sql/sem/tree/parse_tuple.go
  pkg/sql/sem/tree/type_check.go
  pkg/sql/types/types.go
Labels: backport-23.1.x, backport-23.2.x

#114750 release-23.2: opt: fix minor bug in optsteps[web] and exploretrace
  pkg/sql/opt/norm/testdata/rules/combo
  pkg/sql/opt/testutils/opttester/forcing_opt.go
Labels: backport

#114748 release-23.1: changefeedccl: Add jitter to aggregator flushes
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport

#114729 release-23.2: changefeedccl: Add jitter to aggregator flushes
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport

#114800 release-22.2: ci: separate location for customized builds
  build/teamcity/internal/release/process/make-and-publish-build-artifacts.sh
  build/teamcity/internal/release/process/make-and-publish-build-tagging.sh
  scripts/tag-custom-build.sh
Labels: backport

#114563 server: fix TestStatusLocalLogs flaky test
  pkg/server/storage_api/BUILD.bazel
  pkg/server/storage_api/logfiles_test.go
Labels: O-community

#114805 release-23.2: go.mod: bump Pebble to 584ae38642ac
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#114794 release-23.1: roachprod: garbage collect DNS records and use gcloud CLI
  pkg/roachprod/cloud/BUILD.bazel
  pkg/roachprod/cloud/cluster_cloud.go
  pkg/roachprod/cloud/gc.go
  pkg/roachprod/install/services.go
  pkg/roachprod/roachprod.go
  pkg/roachprod/vm/dns.go
  pkg/roachprod/vm/gce/BUILD.bazel
  pkg/roachprod/vm/gce/dns.go
  pkg/roachprod/vm/local/dns.go
  pkg/roachprod/vm/local/dns_test.go
  pkg/roachprod/vm/local/local.go
Labels: backport

#114759 server: fix error handling in status server GetFiles
  pkg/server/BUILD.bazel
  pkg/server/get_local_files_test.go
  pkg/server/status.go
  pkg/server/status_local_file_retrieval.go
Labels: backport-23.1.x, backport-23.2.x

#114607 roachtest: properly disable direct columnar scans
  pkg/cmd/roachtest/tests/backup.go
Labels: backport-23.2.x
