Repository cockroachdb/cockroach, pull requests merged in 2023-09, with the labels that each got.

#109845 sql: fix flaky TestInsightsIntegrationForContention
  pkg/sql/sqlstats/insights/integration/insights_test.go
Labels: backport-23.1.x

#109785 sql: fix performance when disabling sql.metrics.statement_details
  pkg/sql/instrumentation.go
  pkg/sql/sqlstats/persistedsqlstats/BUILD.bazel
  pkg/sql/sqlstats/persistedsqlstats/controller_test.go
Labels: backport-22.2.x, backport-23.1.x

#109812 release-23.1: roachtest: add option to always use latest predecessor in mixedversion
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
Labels: backport

#109693 testing: rewrite TestInitialPartitioning as SQLTranslator tests
  pkg/ccl/partitionccl/partition_test.go
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/all_indexes
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/all_indexes_shuffled
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/list_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/list_range_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_list_partitioning_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_list_partitioning_default_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_list_partitioning_default_default_subpartitioned
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_range_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_range_partitioning_descending
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_range_partitioning_maxvalue
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_range_partitioning_maxvalue_maxvalue
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_range_partitioning_sparse
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/scans
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/secondary_index_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/secondary_index_list_partitioning_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/secondary_index_null
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/secondary_index_unpartitioned
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_list_partitioning_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_range_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_range_partitioning_maxvalue
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_range_partitioning_sparse
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/some_indexes
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/unpartitioned
Labels: backport-23.1.x

#109864 release-23.1: roachtest: revert marking of passing tests for ruby-pg
  pkg/cmd/roachtest/tests/ruby_pg_blocklist.go
Labels: backport

#109904 release-23.1: roachtest: add npgsql tests to ignorelist; not blocklist
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
Labels: backport

#109058 roachtest: avoid flake in post-test assertions after decommission
  pkg/cmd/roachtest/tests/mixed_version_decommission.go
Labels: backport-23.1.x

#109894 release-23.1: testing: rewrite TestInitialPartitioning as SQLTranslator tests
  pkg/ccl/partitionccl/partition_test.go
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/all_indexes
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/all_indexes_shuffled
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/list_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/list_range_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_list_partitioning_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_list_partitioning_default_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_list_partitioning_default_default_subpartitioned
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_range_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_range_partitioning_descending
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_range_partitioning_maxvalue
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_range_partitioning_maxvalue_maxvalue
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/multi_col_range_partitioning_sparse
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/scans
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/secondary_index_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/secondary_index_list_partitioning_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/secondary_index_null
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/secondary_index_unpartitioned
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_list_partitioning_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_range_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_range_partitioning_maxvalue
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/single_col_range_partitioning_sparse
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/some_indexes
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/partition/unpartitioned
Labels: backport

#109908 release-23.1: roachprod: azure gc cleans up empty clusters
  pkg/roachprod/cloud/cluster_cloud.go
  pkg/roachprod/cloud/gc.go
  pkg/roachprod/roachprod.go
  pkg/roachprod/vm/azure/azure.go
  pkg/roachprod/vm/vm.go
Labels: backport

#109917 release-22.2: roachprod: azure gc cleans up empty clusters
  pkg/roachprod/cloud/cluster_cloud.go
  pkg/roachprod/cloud/gc.go
  pkg/roachprod/roachprod.go
  pkg/roachprod/vm/aws/aws.go
  pkg/roachprod/vm/azure/azure.go
  pkg/roachprod/vm/flagstub/flagstub.go
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/local/local.go
  pkg/roachprod/vm/vm.go
Labels: backport

#109750 backupccl: during restore, do not .Next() any keys in makeSimpleImportSpans
  pkg/ccl/backupccl/restore_span_covering.go
  pkg/ccl/backupccl/restore_span_covering_test.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.9-rc

#109943 roachtest: metamorphically run restore roachtests with simpleImportSpans
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#109685 release-22.2: kvserver: start raft after gossip
  pkg/kv/kvserver/store.go
Labels: backport

#109684 release-23.1: kvserver: start raft after gossip
  pkg/kv/kvserver/store.go
Labels: backport

#109922 release-23.1: storage: improve logging during range descriptor iteration
  pkg/kv/kvpb/api.go
  pkg/kv/kvserver/kvstorage/BUILD.bazel
  pkg/kv/kvserver/kvstorage/datadriven_test.go
  pkg/kv/kvserver/kvstorage/init.go
  pkg/kv/kvserver/kvstorage/testdata/init
Labels: backport

#109931 release-22.2: storage: improve logging during range descriptor iteration
  pkg/kv/kvserver/store.go
  pkg/roachpb/api.go
Labels: backport

#109893 release-23.1: roachprod: add multiple instance support
  pkg/cmd/roachprod/flags.go
  pkg/cmd/roachprod/main.go
  pkg/cmd/roachtest/cluster.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/cockroach.go
  pkg/roachprod/install/expander.go
  pkg/roachprod/install/services.go
  pkg/roachprod/install/services_test.go
  pkg/roachprod/multitenant.go
  pkg/roachprod/roachprod.go
Labels: backport

#109876 release-23.1: ui: de-emphasize the term "secondary tenant"
  pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx
Labels: backport

#109641 roachtest: show grafana link in logs
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/test_runner.go
  pkg/roachprod/vm/vm.go
  pkg/roachprod/vm/vm_test.go
Labels: backport-23.1.x

#110034 roachprod: report runs to DMS
  pkg/cmd/roachprod/docker/entrypoint.sh
Labels: C-bug, A-roachprod, T-testeng

#109941 release-22.2: backupccl: during restore, do not .Next() any keys in makeSimpleImportSpans
  pkg/ccl/backupccl/restore_span_covering.go
  pkg/ccl/backupccl/restore_span_covering_test.go
Labels: backport

#109930 streamProducer: log context errors during spanConfigEventStream.handleUpdate()
  pkg/ccl/streamingccl/streamproducer/span_config_event_stream.go
Labels: T-disaster-recovery

#109840 release-23.1: sql: avoid reusing txn ID when logging BEGIN
  pkg/sql/audit_logging.go
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
Labels: backport

#110044 release-23.1: roachtest: fix calls to schemachange workload in acceptance/version-upgrade
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: backport

#110046 release-23.1.10-rc: roachtest: fix calls to schemachange workload in acceptance/version-upgrade
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: backport

#108797 concurrency: only count active waiter in totalAndMaxWaitDuration metric calculation
  pkg/kv/kvserver/concurrency/lock_table.go
  pkg/kv/kvserver/concurrency/testdata/lock_table/basic
Labels: O-community

#110065 roachtest: fix dependencies in typeorm tests
  pkg/cmd/roachtest/tests/typeorm.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.10-rc

#110052 release-23.1: ccl/multiregionccl: disable transfers in multiregion test
  pkg/ccl/multiregionccl/datadriven_test.go
Labels: backport

#110053 release-22.2: ccl/multiregionccl: disable transfers in multiregion test
  pkg/ccl/multiregionccl/datadriven_test.go
Labels: backport

#109835 changefeedccl: add changefeed.lagging_ranges metric
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/options.go
  pkg/ccl/changefeedccl/changefeedbase/settings.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/kvfeed/physical_kv_feed.go
  pkg/ccl/changefeedccl/kvfeed/testing_knobs.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_test.go
Labels: backport-22.2.x, backport-23.1.x

#110108 release-22.2: TEAMS: use workflow for SQL Queries issue triage
  TEAMS.yaml
Labels: backport

#110116 indexrec: fix internal error with inverted indexes
  pkg/sql/opt/indexrec/hypothetical_index.go
  pkg/sql/opt/indexrec/testdata/index
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.10-rc

#110106 release-23.1: TEAMS: add T-sql-queries label
  TEAMS.yaml
Labels: backport

#110083 sql: return pgerror for duplicate regions in super region
  pkg/ccl/logictestccl/testdata/logic_test/secondary_region
  pkg/sql/alter_database.go
Labels: backport-23.1.x

#110030 release-23.1: roachtest: show grafana link in logs
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/test_runner.go
  pkg/roachprod/vm/vm.go
  pkg/roachprod/vm/vm_test.go
Labels: backport

#110128 release-22.2: indexrec: fix internal error with inverted indexes
  pkg/sql/opt/indexrec/hypothetical_index.go
  pkg/sql/opt/indexrec/testdata/index
Labels: backport

#110105 release-23.1.10-rc: TEAMS: add T-sql-queries label
  TEAMS.yaml
Labels: backport

#110134 kvserver: fix replica State update
  pkg/kv/kvserver/batcheval/cmd_gc.go
Labels: backport-23.1.x

#110033 roachtest: backup source and destination tenants on c2c fingerprint mismatch
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/multitenant_utils.go
Labels: T-disaster-recovery

#109467 release-22.2: builtins: fix memory accounting of `st_collect` and `st_makeline` aggregates
  pkg/geo/geo.go
  pkg/sql/sem/builtins/aggregate_builtins.go
Labels: backport

#109725 release-23.1: backport support for cross-region network pricing
  pkg/ccl/multitenantccl/tenantcostclient/BUILD.bazel
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side_test.go
  pkg/ccl/multitenantccl/tenantcostclient/testdata/consumption
  pkg/ccl/multitenantccl/tenantcostserver/metrics.go
  pkg/ccl/multitenantccl/tenantcostserver/server_test.go
  pkg/ccl/multitenantccl/tenantcostserver/testdata/metrics
  pkg/ccl/multitenantccl/tenantcostserver/token_bucket.go
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvpb/api.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvpb/api_test.go
  pkg/multitenant/tenantcostmodel/model.go
  pkg/multitenant/tenantcostmodel/settings.go
  pkg/multitenant/tenantcostmodel/settings_test.go
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/ts/catalog/chart_catalog.go
Labels: backport

#110172 roachtest: skip backups in old releases in backup-restore/mixed-version
  pkg/cmd/roachtest/tests/mixed_version_backup.go
Labels: backport-23.1.x, backport-23.1.10-rc

#110120 testing: add table id placeholder in multi-node SQLTranslator tests
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/all_indexes
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/all_indexes_shuffled
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/list_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/list_range_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_list_partitioning_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_list_partitioning_default_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_list_partitioning_default_default_subpartitioned
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_range_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_range_partitioning_descending
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_range_partitioning_maxvalue
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_range_partitioning_maxvalue_maxvalue
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_range_partitioning_sparse
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/scans
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/secondary_index_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/secondary_index_list_partitioning_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/secondary_index_null
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/secondary_index_unpartitioned
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_list_partitioning_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_range_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_range_partitioning_maxvalue
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_range_partitioning_sparse
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/some_indexes
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned
Labels: backport-23.1.x, backport-23.1.10-rc

#110144 sql: fix column in pg_catalog.pg_depend
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.10-rc

#110200 release-23.1: testing: add table id placeholder in multi-node SQLTranslator tests
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/all_indexes
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/all_indexes_shuffled
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/list_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/list_range_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_list_partitioning_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_list_partitioning_default_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_list_partitioning_default_default_subpartitioned
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_range_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_range_partitioning_descending
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_range_partitioning_maxvalue
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_range_partitioning_maxvalue_maxvalue
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/multi_col_range_partitioning_sparse
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/scans
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/secondary_index_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/secondary_index_list_partitioning_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/secondary_index_null
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/secondary_index_unpartitioned
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_list_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_list_partitioning_default
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_range_partitioning
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_range_partitioning_maxvalue
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/single_col_range_partitioning_sparse
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/some_indexes
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/testdata/3node/partition/unpartitioned
Labels: backport

#109849 release-23.1: kv: prioritize errors in UpdateStateOnRemoteRetryableErr
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/txn_external_test.go
Labels: backport

#109850 release-22.2: kv: prioritize errors in UpdateStateOnRemoteRetryableErr
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/txn_external_test.go
Labels: backport

#110211 release-22.2: sql: fix column in pg_catalog.pg_depend
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: backport

#110206 release-23.1.10-rc: sql: fix column in pg_catalog.pg_depend
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: backport

#110207 release-23.1: sql: fix column in pg_catalog.pg_depend
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: backport

#110224 scheduledlogging: fix `TestCaptureIndexUsageStats`
  pkg/sql/scheduledlogging/BUILD.bazel
  pkg/sql/scheduledlogging/captured_index_usage_stats.go
  pkg/sql/scheduledlogging/captured_index_usage_stats_test.go
Labels: backport-23.1.x

#110232 release-22.2: sqlstats: unskip tests hitting combinedstmts and stmts endpoints
  pkg/server/combined_statement_stats.go
  pkg/server/status_test.go
  pkg/testutils/serverutils/test_server_shim.go
Labels: backport

#110231 release-23.1: sqlstats: unskip tests hitting combinedstmts and stmts endpoints
  pkg/server/combined_statement_stats.go
  pkg/server/status_test.go
  pkg/testutils/serverutils/test_server_shim.go
Labels: backport

#110258 release-22.2: debug: option to omit goroutine stacks by default from debug zip
  pkg/cli/cliflags/flags.go
  pkg/cli/context.go
  pkg/cli/flags.go
  pkg/cli/testdata/zip/testzip_exclude_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_goroutine_stacks
  pkg/cli/zip.go
  pkg/cli/zip_per_node.go
  pkg/cli/zip_test.go
Labels: backport

#110256 release-23.1: cluster-ui: break circular import of `rootActions`
  pkg/ui/workspaces/cluster-ui/src/store/index.ts
  pkg/ui/workspaces/cluster-ui/src/store/liveness/liveness.sagas.ts
  pkg/ui/workspaces/cluster-ui/src/store/nodes/nodes.sagas.ts
  pkg/ui/workspaces/cluster-ui/src/store/reducers.spec.ts
  pkg/ui/workspaces/cluster-ui/src/store/reducers.ts
  pkg/ui/workspaces/cluster-ui/src/store/rootActions.ts
  pkg/ui/workspaces/cluster-ui/src/store/statementDiagnostics/statementDiagnostics.sagas.ts
  pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts
Labels: backport

#110273 release-23.1.10-rc: kv: prioritize errors in UpdateStateOnRemoteRetryableErr
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/txn_external_test.go
Labels: backport

#110168 release-23.1: roachprod: update start-tenant command
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/cockroach.go
  pkg/roachprod/install/expander.go
  pkg/roachprod/multitenant.go
Labels: backport

#110162 release-22.2: build: add cdeps to random syntax tests
  build/teamcity/cockroach/nightlies/random_syntax_tests_impl.sh
Labels: backport

#110161 release-23.1: build: add cdeps to random syntax tests
  build/teamcity/cockroach/nightlies/random_syntax_tests_impl.sh
Labels: backport

#109824 server: add goroutinedumper file to TestStatusGetFiles
  pkg/server/storage_api/files_test.go
Labels: backport-23.1.x

#110277 release-23.1: scheduledlogging: fix `TestCaptureIndexUsageStats`
  pkg/sql/scheduledlogging/BUILD.bazel
  pkg/sql/scheduledlogging/captured_index_usage_stats.go
  pkg/sql/scheduledlogging/captured_index_usage_stats_test.go
Labels: backport

#110266 release-23.1: debug: option to omit goroutine stacks by default from debug zip
  pkg/cli/cliflags/flags.go
  pkg/cli/context.go
  pkg/cli/flags.go
  pkg/cli/testdata/zip/testzip_exclude_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_goroutine_stacks
  pkg/cli/zip.go
  pkg/cli/zip_per_node.go
  pkg/cli/zip_test.go
Labels: backport

#110338 release-23.1: sql: implement datetime builtins
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/datetime
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/util/timeutil/pgdate/pgdate.go
Labels: backport

#110195 kvserver: fix delegated snap gen change error
  pkg/kv/kvserver/replica_command.go
Labels: backport-23.1.x

#110342 release-23.1: cluster-ui: handle partial response errors on the databases page
  pkg/sql/planner.go
  pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/databasesApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/sqlApi.ts
  pkg/ui/workspaces/cluster-ui/src/databases/combiners.ts
  pkg/ui/workspaces/cluster-ui/src/databases/util.tsx
  pkg/ui/workspaces/cluster-ui/src/databasesPage/databaseTableCells.tsx
  pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.module.scss
  pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.tsx
  pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPageConnected.ts
  pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.spec.ts
  pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts
Labels: backport

#110359 release-23.1: sql: add CREATEROLE, CREATELOGIN, CREATEDB, and CONTROLJOB system privileges
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/restore_planning.go
  pkg/jobs/jobsauth/BUILD.bazel
  pkg/jobs/jobsauth/authorization.go
  pkg/jobs/jobsauth/authorization_test.go
  pkg/sql/alter_database.go
  pkg/sql/alter_role.go
  pkg/sql/alter_table.go
  pkg/sql/authorization.go
  pkg/sql/crdb_internal.go
  pkg/sql/create_database.go
  pkg/sql/create_role.go
  pkg/sql/drop_role.go
  pkg/sql/grant_role.go
  pkg/sql/logictest/testdata/logic_test/jobs
  pkg/sql/logictest/testdata/logic_test/role
  pkg/sql/privilege/BUILD.bazel
  pkg/sql/privilege/kind_string.go
  pkg/sql/privilege/privilege.go
  pkg/sql/privilege/privilege_test.go
  pkg/sql/rename_database.go
  pkg/sql/revoke_role.go
  pkg/sql/set_cluster_setting.go
Labels: backport

#110148 sql/randgen: make insert values deterministic with a seed
  pkg/sql/randgen/schema.go
Labels: backport-22.2.x, backport-23.1.x

#110339 release: post-publishing fixes
  pkg/cmd/release/update_orchestration.go
  pkg/cmd/release/update_versions.go
Labels: C-bug, A-release, T-release

#109103 roachprod: use correct ($os-$arch) suffix for staging arm64 workload …
  pkg/roachprod/install/staging.go
  pkg/roachprod/install/staging_test.go
Labels: backport-22.2.x, backport-23.1.x

#110147 release-23.1: sql/sem/tree: eliminate types.T allocations in collated string comparison
  pkg/sql/sem/tree/datum.go
Labels: backport

#110369 release-23.1: cluster-ui: handle partial response errors on the database details page
  pkg/ui/workspaces/cluster-ui/src/api/sqlApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts
  pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsConnected.ts
  pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.stories.tsx
  pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/tableCells.tsx
  pkg/ui/workspaces/cluster-ui/src/databases/combiners.ts
  pkg/ui/workspaces/db-console/src/views/databases/databaseDetailsPage/redux.spec.ts
  pkg/ui/workspaces/db-console/src/views/databases/databaseDetailsPage/redux.ts
Labels: backport

#110296 release-23.1: sql: fix decimal evaluation edge cases
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/sql/colexec/colexecagg/hash_avg_agg.eg.go
  pkg/sql/colexec/colexecagg/hash_sum_agg.eg.go
  pkg/sql/colexec/colexecagg/ordered_avg_agg.eg.go
  pkg/sql/colexec/colexecagg/ordered_sum_agg.eg.go
  pkg/sql/colexec/colexecagg/window_avg_agg.eg.go
  pkg/sql/colexec/colexecagg/window_sum_agg.eg.go
  pkg/sql/colexec/colexecproj/proj_non_const_ops.eg.go
  pkg/sql/colexec/colexecprojconst/proj_const_left_ops.eg.go
  pkg/sql/colexec/colexecprojconst/proj_const_right_ops.eg.go
  pkg/sql/colexec/colexecwindow/range_offset_handler.eg.go
  pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go
  pkg/sql/logictest/testdata/logic_test/decimal
  pkg/sql/sem/eval/binary_op.go
  pkg/sql/sem/tree/datum.go
Labels: backport

#110392 release-23.1: roachtest: update github issue grafana link
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/testdata/help_command.txt
  pkg/cmd/roachtest/testdata/help_command_createpost_1.txt
  pkg/cmd/roachtest/testdata/help_command_createpost_5.txt
Labels: backport

#110298 release-22.2: sql: fix decimal evaluation edge cases
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/sql/colexec/colexecagg/hash_avg_agg.eg.go
  pkg/sql/colexec/colexecagg/hash_sum_agg.eg.go
  pkg/sql/colexec/colexecagg/ordered_avg_agg.eg.go
  pkg/sql/colexec/colexecagg/ordered_sum_agg.eg.go
  pkg/sql/colexec/colexecagg/window_avg_agg.eg.go
  pkg/sql/colexec/colexecagg/window_sum_agg.eg.go
  pkg/sql/colexec/colexecproj/proj_non_const_ops.eg.go
  pkg/sql/colexec/colexecprojconst/proj_const_left_ops.eg.go
  pkg/sql/colexec/colexecprojconst/proj_const_right_ops.eg.go
  pkg/sql/colexec/colexecwindow/range_offset_handler.eg.go
  pkg/sql/colexec/execgen/cmd/execgen/overloads_bin.go
  pkg/sql/logictest/testdata/logic_test/decimal
  pkg/sql/sem/eval/binary_op.go
  pkg/sql/sem/tree/datum.go
Labels: backport

#110337 release-23.1: sql,keys: disregard checks in *ZoneConfig*Batch
  pkg/keys/constants.go
  pkg/sql/catalog/descs/collection.go
  pkg/sql/logictest/testdata/logic_test/zone_config
  pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant
Labels: backport

#110474 release-23.1: go.mod: bump Pebble to 46873a6a7a06
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#110444 release-22.2: ui: all xhr paths from db console are now relative
  pkg/ui/workspaces/cluster-ui/src/api/basePath.spec.ts
  pkg/ui/workspaces/cluster-ui/src/api/basePath.ts
  pkg/ui/workspaces/cluster-ui/src/api/fetchData.ts
  pkg/ui/workspaces/cluster-ui/src/api/indexDetailsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/jobsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/livenessApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/nodesApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/sessionsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/sqlApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/sqlStatsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/statementsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/terminateQueryApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/userApi.ts
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPageConnected.spec.ts
  pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTableContent.tsx
  pkg/ui/workspaces/db-console/src/redux/analytics.ts
  pkg/ui/workspaces/db-console/src/util/dataFromServer.ts
Labels: backport

#110401 release-22.2: tree: fix formatting of CreateChangefeed with predicate
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/sql/parser/testdata/changefeed
  pkg/sql/sem/tree/changefeed.go
Labels: backport

#110500 release-23.1: upgrade: remove buggy TTL repair
  pkg/sql/catalog/tabledesc/table_desc_builder.go
  pkg/sql/catalog/tabledesc/table_desc_test.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/mixed_version_upgrade_repair_descriptors
  pkg/sql/logictest/tests/cockroach-go-testserver-upgrade-to-master/BUILD.bazel
  pkg/sql/logictest/tests/cockroach-go-testserver-upgrade-to-master/generated_test.go
  pkg/upgrade/upgrades/first_upgrade.go
  pkg/upgrade/upgrades/first_upgrade_test.go
Labels: backport, staging-v23.1.10

#110470 release-22.2: sql/tests: deflake TestRandomSyntaxSchemaChangeColumn
  pkg/sql/schemachanger/rel/schema_attribute.go
  pkg/sql/tests/rsg_test.go
Labels: backport

#110570 release-23.1: logictest: deflake zone_config_system_tenant
  pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant
Labels: backport

#110513 release-22.2: sql: use redactable type name in a few errors
  pkg/sql/opt/invertedidx/trigram.go
  pkg/sql/rowenc/index_encoding.go
Labels: backport

#110216 sql/schemachanger: create partial index with inserts can fail
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go
  pkg/sql/schemachanger/scpb/elements.proto
  pkg/sql/schemachanger/scpb/uml/table.puml
  pkg/sql/schemachanger/scplan/internal/opgen/opgen_temporary_index.go
  pkg/sql/schemachanger/testdata/end_to_end/create_index/create_index.definition
  pkg/sql/schemachanger/testdata/end_to_end/create_index/create_index.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_index/create_index.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_index_create_schema_separate_statements/create_index_create_schema_separate_statements.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_index_create_schema_separate_statements/create_index_create_schema_separate_statements__statement_1_of_2.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_index_create_schema_separate_statements/create_index_create_schema_separate_statements__statement_2_of_2.explain
Labels: backport-23.1.x

#110571 release-23.1.11-rc: logictest: deflake zone_config_system_tenant
  pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant
Labels: backport

#110406 roachtest: fix NPE in test_runner
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/test_runner.go
Labels: backport-22.2.x, backport-23.1.x

#110611 release-23.1: backupccl: add EXECUTION LOCALITY option to RESTORE
  docs/generated/sql/bnf/restore_options.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/ccl/backupccl/backup_job.go
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/backupccl/restore_processor_planning.go
  pkg/jobs/jobspb/jobs.proto
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/backup_restore
  pkg/sql/sem/tree/backup.go
  pkg/sql/sem/tree/walk.go
Labels: backport

#110672 sqlstats: fix TestInsightsIntegrationForContention
  pkg/sql/sqlstats/insights/integration/insights_test.go
Labels: backport-23.1.x

#110639 sql: fix TestCaptureIndexUsageStats
  pkg/sql/scheduledlogging/captured_index_usage_stats_test.go
Labels: backport-23.1.x

#110574 release-23.1: tests: support float approximation in roachtest query comparison utils
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/costfuzz.go
  pkg/cmd/roachtest/tests/query_comparison_util.go
  pkg/cmd/roachtest/tests/query_comparison_util_test.go
  pkg/cmd/roachtest/tests/tlp.go
  pkg/cmd/roachtest/tests/unoptimized_query_oracle.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/main_test.go
  pkg/testutils/floatcmp/BUILD.bazel
  pkg/testutils/floatcmp/floatcmp.go
  pkg/testutils/floatcmp/floatcmp_test.go
Labels: backport

#110703 release-22.2: tree: fix formatting of SHOW BACKUP WITH OPTIONS
  pkg/sql/parser/testdata/backup_restore
  pkg/sql/sem/tree/show.go
Labels: backport

#110700 release-23.1: tree: fix formatting of SHOW BACKUP WITH OPTIONS
  docs/generated/sql/bnf/show_backup.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/backup_restore
  pkg/sql/parser/testdata/show
  pkg/sql/sem/tree/show.go
Labels: backport

#110130 sql: update UDF references in `ALTER TABLE`
  pkg/sql/alter_table.go
  pkg/sql/logictest/testdata/logic_test/udf_in_constraints
Labels: backport-23.1.x

#110716 release-22.2: roachtest: remove old executables before installing ruby
  pkg/cmd/roachtest/tests/ruby_pg.go
Labels: backport

#110588 release-23.1: sql: fix system database survival on create or drop database
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_survial_goal
  pkg/sql/alter_database.go
  pkg/sql/descriptor.go
  pkg/sql/drop_database.go
  pkg/sql/schemachanger/scbuild/builder_test.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/BUILD.bazel
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_database.go
  pkg/sql/schemachanger/scdeps/sctestdeps/BUILD.bazel
  pkg/sql/schemachanger/scdeps/sctestdeps/config.go
  pkg/sql/schemachanger/sctest/end_to_end.go
Labels: backport

#110507 release-23.1: cli: fix debug pebble commands on encrypted stores
  pkg/ccl/cliccl/debug.go
  pkg/cli/BUILD.bazel
  pkg/cli/absolute_fs.go
  pkg/cli/auto_decrypt_fs.go
  pkg/cli/auto_decrypt_fs_test.go
  pkg/cli/debug.go
  pkg/cli/interactive_tests/test_encryption.tcl
  pkg/cli/swappable_fs.go
Labels: backport

#110509 release-22.2: cli: fix debug pebble commands on encrypted stores
  pkg/ccl/cliccl/debug.go
  pkg/cli/BUILD.bazel
  pkg/cli/absolute_fs.go
  pkg/cli/auto_decrypt_fs.go
  pkg/cli/auto_decrypt_fs_test.go
  pkg/cli/debug.go
  pkg/cli/interactive_tests/test_encryption.tcl
  pkg/cli/swappable_fs.go
Labels: backport

#110577 release-22.2: tests: support float approximation in roachtest query comparison utils
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/costfuzz.go
  pkg/cmd/roachtest/tests/query_comparison_util.go
  pkg/cmd/roachtest/tests/query_comparison_util_test.go
  pkg/cmd/roachtest/tests/tlp.go
  pkg/cmd/roachtest/tests/unoptimized_query_oracle.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/main_test.go
  pkg/testutils/floatcmp/BUILD.bazel
  pkg/testutils/floatcmp/floatcmp.go
  pkg/testutils/floatcmp/floatcmp_test.go
Labels: backport

#110741 release-23.1: cluster-ui: skip undefined regions on database pages
  pkg/ui/workspaces/cluster-ui/src/databases/util.spec.ts
  pkg/ui/workspaces/cluster-ui/src/databases/util.tsx
  pkg/ui/workspaces/db-console/src/views/databases/databaseDetailsPage/redux.spec.ts
  pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.spec.ts
Labels: backport

#110680 release-23.1: cluster-ui: handle partial response errors on the database table page
  pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx
  pkg/ui/workspaces/cluster-ui/src/databaseTablePage/helperComponents.tsx
  pkg/ui/workspaces/cluster-ui/src/databases/combiners.ts
  pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.spec.ts
Labels: backport

#110662 release-23.1: cli: add limit statment_statistics to debug zip
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/partial1_excluded
  pkg/cli/testdata/zip/partial2
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/testzip_concurrent
  pkg/cli/testdata/zip/testzip_exclude_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_range_info
  pkg/cli/testdata/zip/testzip_shared_process_tenant
  pkg/cli/testdata/zip/testzip_tenant_separate_process
  pkg/cli/zip_table_registry.go
Labels: backport

#110745 keys: Don't panic when error can be returned
  pkg/keys/BUILD.bazel
  pkg/keys/printer_test.go
  pkg/keys/sql.go
  pkg/keys/testdata/fuzz/FuzzPrettyPrint/0993bb3a50de2d9726809ce574e86227a94a7f0c0874449f034c656060f1068e
  pkg/keys/testdata/fuzz/FuzzPrettyPrint/36d185f8df737d16ff68de3e516c6633ec320265dcb6ee83b31f3356947e7bab
  pkg/keys/testdata/fuzz/FuzzPrettyPrint/cd38de85c2cd0a417779f94ac2847e35817509ac8d04daaed05a6fbe9edc11f9
  pkg/keys/testdata/fuzz/FuzzPrettyPrint/dd1de6f67c6c53768df6ccdedb6df4a804f4cf63eba4679d0db073b85d71ca5a
Labels: backport-23.1.x

#110718 release-22.2: export: add memory monitoring for EXPORT INTO PARQUET
  pkg/sql/execinfra/server_config.go
  pkg/sql/importer/BUILD.bazel
  pkg/sql/importer/export_base.go
  pkg/sql/importer/exportparquet.go
  pkg/sql/importer/exportparquet_test.go
Labels: backport

#110717 release-23.1: export: add memory monitoring for EXPORT INTO PARQUET
  pkg/sql/execinfra/server_config.go
  pkg/sql/importer/BUILD.bazel
  pkg/sql/importer/export_base.go
  pkg/sql/importer/exportparquet.go
  pkg/sql/importer/exportparquet_test.go
Labels: backport

#110746 release-23.1: ttl: do not remove all table TTL settings on RESET (ttl_expire_after)
  pkg/sql/alter_table.go
  pkg/sql/logictest/testdata/logic_test/row_level_ttl
  pkg/sql/schema_changer.go
  pkg/sql/show_create_external_connection.go
  pkg/sql/show_create_schedule.go
Labels: backport

#110721 release-22.2: upgrade: include schema in search_path upgrading sequences
  pkg/upgrade/tenant_upgrade.go
  pkg/upgrade/upgradejob/BUILD.bazel
  pkg/upgrade/upgradejob/upgrade_job.go
  pkg/upgrade/upgrades/upgrade_sequence_to_be_referenced_by_ID.go
  pkg/upgrade/upgrades/upgrade_sequence_to_be_referenced_by_ID_external_test.go
Labels: backport

#110750 release-22.2: ttl: do not remove all table TTL settings on RESET (ttl_expire_after)
  pkg/sql/alter_table.go
  pkg/sql/logictest/testdata/logic_test/row_level_ttl
  pkg/sql/schema_changer.go
  pkg/sql/show_create_external_connection.go
  pkg/sql/show_create_schedule.go
Labels: backport

#110773 changefeedccl: Fix potential shutdown NPE
  pkg/ccl/changefeedccl/changefeed_processors.go
Labels: backport-22.2.x, backport-23.1.x

#110775 sql: remove accidental copy of inFlightTraceCollector
  pkg/sql/instrumentation.go
Labels: backport-22.2.x, backport-23.1.x

#110636 release-22.2: changefeedccl: Fix setting propagation flake
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/testutils/fuzz/BUILD.bazel
  pkg/testutils/sqlutils/BUILD.bazel
  pkg/testutils/sqlutils/sql_runner.go
Labels: backport

#110635 release-23.1: changefeedccl: Fix setting propagation flake
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/testutils/fuzz/BUILD.bazel
  pkg/testutils/sqlutils/BUILD.bazel
  pkg/testutils/sqlutils/sql_runner.go
Labels: backport

#110836 release-23.1: storageparam: do not allow subqueries in storage param clause
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/storageparam/storage_param.go
Labels: backport

#110819 release-22.2: roachtest: roachprod: add test name and run id vm labels for metrics
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/test_runner.go
  pkg/roachprod/roachprod.go
  pkg/roachprod/vm/aws/aws.go
  pkg/roachprod/vm/azure/azure.go
  pkg/roachprod/vm/flagstub/flagstub.go
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/local/local.go
  pkg/roachprod/vm/vm.go
Labels: backport

#110584 release-23.1: sql/schemachanger: create partial index with inserts can fail
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go
  pkg/sql/schemachanger/scpb/elements.proto
  pkg/sql/schemachanger/scpb/uml/table.puml
  pkg/sql/schemachanger/scplan/internal/opgen/opgen_temporary_index.go
  pkg/sql/schemachanger/testdata/end_to_end/create_index
  pkg/sql/schemachanger/testdata/explain/create_index
  pkg/sql/schemachanger/testdata/explain_verbose/create_index
Labels: backport

#110904 changefeedccl: deflake TestChangefeedSchemaChangeBackfillCheckpoint
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport-22.2.x

#110806 kvserver: fix Replica.tenantLimiter race
  pkg/kv/kvserver/replica_rate_limit.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/store_test.go
  pkg/kv/kvserver/tenantrate/settings.go
Labels: backport-22.2.x, backport-23.1.x

#110944 release-22.2: sql: add libgeos runfile dependency for RSG tests
  build/teamcity/cockroach/nightlies/random_syntax_tests_impl.sh
  pkg/sql/tests/BUILD.bazel
Labels: backport

#110946 release-23.1: sql: add libgeos runfile dependency for RSG tests
  build/teamcity/cockroach/nightlies/random_syntax_tests_impl.sh
  pkg/sql/tests/BUILD.bazel
Labels: backport

#110972 release-22.2: kv: wait on latches on each key in reverse acquisition order
  pkg/kv/kvserver/spanlatch/manager.go
Labels: backport

#110994 release-23.1: roachtest: tolerate errors in clearrange workload
  pkg/cmd/roachtest/tests/clearrange.go
Labels: backport

#110858 kvserver: unskip TestMergeQueueWithSlowNonVoterSnaps
  pkg/kv/kvserver/client_merge_test.go
Labels: backport-23.1.x

#110621 sql: sequences created for identity columns have incorrect types
  pkg/sql/logictest/testdata/logic_test/create_table
  pkg/sql/serial.go
Labels: backport-23.1.x

#110991 release-22.2: de-flake debug zip tests
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/testzip_exclude_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_range_info
  pkg/cli/testdata/zip/testzip_tenant
  pkg/cli/zip_test.go
Labels: backport

#110084 privilege: add REPAIRCLUSTERMETADATA system prvilege and remove admin checks
  pkg/ccl/backupccl/alter_backup_schedule.go
  pkg/ccl/backupccl/create_scheduled_backup.go
  pkg/ccl/backupccl/testdata/backup-restore/alter-schedule/schedule-options
  pkg/ccl/logictestccl/testdata/logic_test/crdb_internal
  pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant
  pkg/ccl/logictestccl/testdata/logic_test/tenant_usage
  pkg/ccl/logictestccl/testdata/logic_test/zone
  pkg/server/privchecker/api.go
  pkg/sql/alter_default_privileges.go
  pkg/sql/alter_role.go
  pkg/sql/authorization.go
  pkg/sql/copy_file_upload.go
  pkg/sql/crdb_internal.go
  pkg/sql/delegate/show_all_cluster_settings.go
  pkg/sql/gossip.go
  pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_all_roles
  pkg/sql/logictest/testdata/logic_test/alter_role_set
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/role
  pkg/sql/logictest/testdata/logic_test/tenant_builtins
  pkg/sql/opt/cat/catalog.go
  pkg/sql/opt/optbuilder/BUILD.bazel
  pkg/sql/opt/optbuilder/alter_range.go
  pkg/sql/opt/testutils/testcat/BUILD.bazel
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/opt_catalog.go
  pkg/sql/privilege/kind_string.go
  pkg/sql/privilege/privilege.go
  pkg/sql/repair.go
  pkg/sql/scrub.go
  pkg/sql/sem/builtins/BUILD.bazel
  pkg/sql/sem/builtins/generator_builtins.go
  pkg/sql/sem/builtins/generator_probe_ranges.go
  pkg/sql/set_zone_config.go
  pkg/sql/tenant_accessors.go
  pkg/sql/tenant_gc.go
  pkg/sql/tenant_settings.go
  pkg/sql/tenant_update.go
  pkg/sql/tests/copy_file_upload_test.go
Labels: backport-23.1.x

#111058 release-23.1: privilege: add REPAIRCLUSTERMETADATA system prvilege and remove admin checks
  pkg/ccl/backupccl/alter_backup_schedule.go
  pkg/ccl/backupccl/create_scheduled_backup.go
  pkg/ccl/backupccl/testdata/backup-restore/alter-schedule/schedule-options
  pkg/ccl/logictestccl/testdata/logic_test/crdb_internal
  pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant
  pkg/ccl/logictestccl/testdata/logic_test/tenant_usage
  pkg/ccl/logictestccl/testdata/logic_test/zone
  pkg/sql/alter_default_privileges.go
  pkg/sql/alter_role.go
  pkg/sql/authorization.go
  pkg/sql/copy_file_upload.go
  pkg/sql/crdb_internal.go
  pkg/sql/delegate/show_all_cluster_settings.go
  pkg/sql/gossip.go
  pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_all_roles
  pkg/sql/logictest/testdata/logic_test/alter_role_set
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/role
  pkg/sql/logictest/testdata/logic_test/tenant_builtins
  pkg/sql/opt/cat/catalog.go
  pkg/sql/opt/optbuilder/BUILD.bazel
  pkg/sql/opt/optbuilder/alter_range.go
  pkg/sql/opt/testutils/testcat/BUILD.bazel
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/opt_catalog.go
  pkg/sql/privilege/kind_string.go
  pkg/sql/privilege/privilege.go
  pkg/sql/repair.go
  pkg/sql/scrub.go
  pkg/sql/sem/builtins/BUILD.bazel
  pkg/sql/sem/builtins/generator_builtins.go
  pkg/sql/sem/builtins/generator_probe_ranges.go
  pkg/sql/set_zone_config.go
  pkg/sql/tenant_accessors.go
  pkg/sql/tenant_gc.go
  pkg/sql/tenant_settings.go
  pkg/sql/tenant_update.go
  pkg/sql/tests/copy_file_upload_test.go
Labels: backport

#110605 logictest: don't download `cockroach` from the internet in test
  WORKSPACE
  build/toolchains/BUILD.bazel
  pkg/ccl/logictestccl/tests/3node-tenant-multiregion/BUILD.bazel
  pkg/ccl/logictestccl/tests/3node-tenant/BUILD.bazel
  pkg/ccl/logictestccl/tests/5node/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist-disk/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-mixed-22.2-23.1/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/local/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-15node-5region-3azs/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-3node-3superlongregions/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/BUILD.bazel
  pkg/ccl/sqlitelogictestccl/tests/3node-tenant/BUILD.bazel
  pkg/cmd/generate-logictest/templates.go
  pkg/cmd/release/main.go
  pkg/cmd/release/update_releases.go
  pkg/sql/logictest/BUILD.bazel
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/tests/5node-disk/BUILD.bazel
  pkg/sql/logictest/tests/5node/BUILD.bazel
  pkg/sql/logictest/tests/cockroach-go-testserver-upgrade-to-master/BUILD.bazel
  pkg/sql/logictest/tests/fakedist-disk/BUILD.bazel
  pkg/sql/logictest/tests/fakedist-vec-off/BUILD.bazel
  pkg/sql/logictest/tests/fakedist/BUILD.bazel
  pkg/sql/logictest/tests/local-legacy-schema-changer/BUILD.bazel
  pkg/sql/logictest/tests/local-mixed-22.2-23.1/BUILD.bazel
  pkg/sql/logictest/tests/local-vec-off/BUILD.bazel
  pkg/sql/logictest/tests/local/BUILD.bazel
  pkg/sql/logictest/tests/multiregion-9node-3region-3azs/BUILD.bazel
  pkg/sql/logictest/tests/multiregion-invalid-locality/BUILD.bazel
  pkg/sql/opt/exec/execbuilder/tests/5node/BUILD.bazel
  pkg/sql/opt/exec/execbuilder/tests/fakedist-disk/BUILD.bazel
  pkg/sql/opt/exec/execbuilder/tests/fakedist-vec-off/BUILD.bazel
  pkg/sql/opt/exec/execbuilder/tests/fakedist/BUILD.bazel
  pkg/sql/opt/exec/execbuilder/tests/local-legacy-schema-changer/BUILD.bazel
  pkg/sql/opt/exec/execbuilder/tests/local-mixed-22.2-23.1/BUILD.bazel
  pkg/sql/opt/exec/execbuilder/tests/local-vec-off/BUILD.bazel
  pkg/sql/opt/exec/execbuilder/tests/local/BUILD.bazel
  pkg/sql/sqlitelogictest/tests/fakedist-disk/BUILD.bazel
  pkg/sql/sqlitelogictest/tests/fakedist-vec-off/BUILD.bazel
  pkg/sql/sqlitelogictest/tests/fakedist/BUILD.bazel
  pkg/sql/sqlitelogictest/tests/local-legacy-schema-changer/BUILD.bazel
  pkg/sql/sqlitelogictest/tests/local-mixed-22.2-23.1/BUILD.bazel
  pkg/sql/sqlitelogictest/tests/local-vec-off/BUILD.bazel
  pkg/sql/sqlitelogictest/tests/local/BUILD.bazel
Labels: backport-23.1.x

#111061 roachtest: show informational message when grafana is not available
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/testdata/help_command_non_gce.txt
Labels: backport-23.1.x

#111082 teamcity-trigger: reduce streamingest paralleism
  pkg/cmd/teamcity-trigger/main.go
Labels: T-disaster-recovery

#111072 release-22.2: storageparam: do not allow subqueries in storage param clause
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/storageparam/storage_param.go
Labels: backport

#111019 sql/pg_catalog: add dropped columns into pg_attribute
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/privilege_builtins
  pkg/sql/logictest/testdata/logic_test/srfs
  pkg/sql/pg_catalog.go
Labels: backport-23.1.x

#110956 sql: return expected user-facing error for invalid unnest arguments
  pkg/sql/logictest/testdata/logic_test/srfs
  pkg/sql/sem/builtins/generator_builtins.go
Labels: backport-22.2.x, backport-23.1.x

#111086 release-23.1: roachtest: codify longer ttl external storage buckets
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/backup.go
  pkg/testutils/lint/lint_test.go
Labels: backport

#111108 sql/tests: avoid contention in RSG test
  pkg/sql/tests/rsg_test.go
Labels: backport-22.2.x, backport-23.1.x

#111141 release-23.1: go.mod: bump Pebble to cfe17167bac5
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#111191 loqrecovery: bypass circuit breakers in fan-out ops
  pkg/kv/kvserver/loqrecovery/server.go
Labels: backport-23.1.x

#111176 release-22.2: roachtest: allow running skipped tests
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/registry/filter.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/test_test.go
Labels: backport

#111254 release-23.1: kv: deflake TestLeaseExpirationBasedDrainTransferWithExtension
  pkg/kv/kvserver/client_replica_test.go
Labels: backport

#111137 release-23.1: roachtest: expand tag functionality to allow filtering by conjunctive…
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  build/teamcity/util/roachtest_util.sh
  pkg/cmd/roachtest/README.md
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/registry/filter.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/test_test.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/activerecord.go
  pkg/cmd/roachtest/tests/admission_control_elastic_backup.go
  pkg/cmd/roachtest/tests/admission_control_elastic_cdc.go
  pkg/cmd/roachtest/tests/admission_control_index_overload.go
  pkg/cmd/roachtest/tests/admission_control_multi_store_overload.go
  pkg/cmd/roachtest/tests/admission_control_snapshot_overload.go
  pkg/cmd/roachtest/tests/admission_control_tpcc_overload.go
  pkg/cmd/roachtest/tests/asyncpg.go
  pkg/cmd/roachtest/tests/awsdms.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/cdc.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/django.go
  pkg/cmd/roachtest/tests/failover.go
  pkg/cmd/roachtest/tests/fixtures.go
  pkg/cmd/roachtest/tests/gopg.go
  pkg/cmd/roachtest/tests/gorm.go
  pkg/cmd/roachtest/tests/hibernate.go
  pkg/cmd/roachtest/tests/jasyncsql.go
  pkg/cmd/roachtest/tests/knex.go
  pkg/cmd/roachtest/tests/kv.go
  pkg/cmd/roachtest/tests/kvbench.go
  pkg/cmd/roachtest/tests/libpq.go
  pkg/cmd/roachtest/tests/liquibase.go
  pkg/cmd/roachtest/tests/loss_of_quorum_recovery.go
  pkg/cmd/roachtest/tests/nodejs_postgres.go
  pkg/cmd/roachtest/tests/npgsql.go
  pkg/cmd/roachtest/tests/pebble_write_throughput.go
  pkg/cmd/roachtest/tests/pebble_ycsb.go
  pkg/cmd/roachtest/tests/pgjdbc.go
  pkg/cmd/roachtest/tests/pgx.go
  pkg/cmd/roachtest/tests/pop.go
  pkg/cmd/roachtest/tests/psycopg.go
  pkg/cmd/roachtest/tests/restore.go
  pkg/cmd/roachtest/tests/roachtest.go
  pkg/cmd/roachtest/tests/ruby_pg.go
  pkg/cmd/roachtest/tests/rust_postgres.go
  pkg/cmd/roachtest/tests/schemachange_random_load.go
  pkg/cmd/roachtest/tests/sequelize.go
  pkg/cmd/roachtest/tests/smoketest_secure.go
  pkg/cmd/roachtest/tests/sqlalchemy.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/tpce.go
  pkg/cmd/roachtest/tests/typeorm.go
  pkg/cmd/roachtest/tests/ycsb.go
Labels: backport

#111273 github-pull-request-make: stress up to 5 tests per package
  pkg/cmd/github-pull-request-make/main.go
  pkg/cmd/github-pull-request-make/main_test.go
  pkg/cmd/github-pull-request-make/testdata/five_tests.diff
Labels: T-dev-inf

#111281 release-23.1: roachtest: fix acceptance tests owner tags
  pkg/cmd/roachtest/tests/acceptance.go
Labels: backport

#111311 release: don not update releases.yaml files on forked repos
  .github/workflows/update_releases.yaml
Labels: C-enhancement, A-release, T-release

#111233 release-22.2: roachtest: expand tag functionality to allow filtering by conjunctive…
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  build/teamcity/util/roachtest_util.sh
  pkg/cmd/roachtest/README.md
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/registry/filter.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/test_test.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/activerecord.go
  pkg/cmd/roachtest/tests/asyncpg.go
  pkg/cmd/roachtest/tests/awsdms.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/cdc.go
  pkg/cmd/roachtest/tests/django.go
  pkg/cmd/roachtest/tests/fixtures.go
  pkg/cmd/roachtest/tests/gopg.go
  pkg/cmd/roachtest/tests/gorm.go
  pkg/cmd/roachtest/tests/hibernate.go
  pkg/cmd/roachtest/tests/jasyncsql.go
  pkg/cmd/roachtest/tests/knex.go
  pkg/cmd/roachtest/tests/kv.go
  pkg/cmd/roachtest/tests/kvbench.go
  pkg/cmd/roachtest/tests/libpq.go
  pkg/cmd/roachtest/tests/liquibase.go
  pkg/cmd/roachtest/tests/loss_of_quorum_recovery.go
  pkg/cmd/roachtest/tests/nodejs_postgres.go
  pkg/cmd/roachtest/tests/pebble_write_throughput.go
  pkg/cmd/roachtest/tests/pebble_ycsb.go
  pkg/cmd/roachtest/tests/pgjdbc.go
  pkg/cmd/roachtest/tests/pgx.go
  pkg/cmd/roachtest/tests/pop.go
  pkg/cmd/roachtest/tests/psycopg.go
  pkg/cmd/roachtest/tests/restore.go
  pkg/cmd/roachtest/tests/roachtest.go
  pkg/cmd/roachtest/tests/ruby_pg.go
  pkg/cmd/roachtest/tests/rust_postgres.go
  pkg/cmd/roachtest/tests/schemachange_random_load.go
  pkg/cmd/roachtest/tests/sequelize.go
  pkg/cmd/roachtest/tests/smoketest_secure.go
  pkg/cmd/roachtest/tests/sqlalchemy.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/tpce.go
  pkg/cmd/roachtest/tests/typeorm.go
  pkg/cmd/roachtest/tests/ycsb.go
Labels: backport

#111341 release-22.2: batcheval: delete flaky integration test
  pkg/kv/kvserver/batcheval/cmd_lease_test.go
Labels: backport

#111286 release-22.2: cloud/azure: Fix azure schemes
  pkg/ccl/cloudccl/externalconn/datadriven_test.go
  pkg/ccl/cloudccl/externalconn/testdata/create_drop_external_connection
  pkg/cloud/azure/azure_connection.go
  pkg/cloud/azure/azure_storage.go
Labels: backport

#111344 release-23.1: ttl: default to cluster setting select batch size in ttl job description
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/ttl/ttlbase/BUILD.bazel
  pkg/sql/ttl/ttlbase/ttl_helpers.go
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
  pkg/sql/ttl/ttljob/ttljob_test.go
  pkg/sql/ttl/ttlschedule/BUILD.bazel
  pkg/sql/ttl/ttlschedule/ttlschedule.go
Labels: backport

#111370 release-22.2: roachtest: fix acceptance tests owner tags
  pkg/cmd/roachtest/tests/acceptance.go
Labels: backport

#111272 kvserver: add metrics for raft (re-)proposals
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica_application_result.go
  pkg/kv/kvserver/replica_raft.go
Labels: backport-22.2.x, backport-23.1.x

#111287 release-23.1: rpc: permit gRPC stream window sizes up to 64 MB
  pkg/rpc/context.go
Labels: backport

#111288 release-22.2: rpc: permit gRPC stream window sizes up to 64 MB
  pkg/rpc/context.go
Labels: backport

#111395 release-22.2: roachtest: introduce `grafana-dump`, `--skip-init`
  pkg/cmd/roachprod/flags.go
  pkg/cmd/roachprod/main.go
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/test/test_interface.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
  pkg/roachprod/prometheus/prometheus.go
  pkg/roachprod/roachprod.go
Labels: backport

#110983 release-23.1: sql: limit statistics discard log message
  pkg/sql/sqlstats/persistedsqlstats/flush_test.go
  pkg/sql/sqlstats/sslocal/sql_stats.go
  pkg/sql/sqlstats/sslocal/sslocal_provider.go
  pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go
  pkg/sql/sqlstats/ssmemstorage/BUILD.bazel
  pkg/sql/sqlstats/ssmemstorage/ss_mem_counter.go
  pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go
  pkg/sql/sqlstats/ssprovider.go
Labels: backport
