Repository cockroachdb/cockroach, pull requests merged in 2023-08, with the labels that each got.

#107737 kv: don't log stack trace on async rollback of committed txn
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
Labels: backport-22.2.x, backport-23.1.x

#107923 changefeedccl: Correctly handle dropped UDTs
  pkg/ccl/changefeedccl/schemafeed/schema_feed.go
  pkg/ccl/changefeedccl/schemafeed/schema_feed_test.go
Labels: backport-22.1.x, backport-22.2.x, backport-23.1.x

#107567 sql: fix CREATE AS [SHOW CREATE FUNCTION] job failure
  pkg/BUILD.bazel
  pkg/jobs/jobspb/jobs.proto
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/create_as_test.go
  pkg/sql/delegate/show_function.go
  pkg/sql/drop_function.go
  pkg/sql/drop_schema.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/logictest/testdata/logic_test/set
  pkg/sql/logictest/testdata/logic_test/vectorize
  pkg/sql/protoreflect/utils.go
  pkg/sql/schema.go
  pkg/sql/schema_changer.go
  pkg/sql/sessiondatapb/BUILD.bazel
  pkg/sql/sessiondatapb/session_data.go
  pkg/sql/sessiondatapb/session_data.proto
  pkg/sql/sessiondatapb/session_data_test.go
  pkg/sql/table.go
  pkg/sql/vars.go
Labels: backport-22.2.x, backport-23.1.x

#107893 cluster-ui: fix replicas and regions query for the database details API
  pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts
Labels: backport-23.1.x

#108032 sql: Make tochar.FormatCache thread safe
  pkg/util/tochar/cache.go
  pkg/util/tochar/cache_test.go
Labels: backport-22.2.x, backport-23.1.x

#108056 sql: delete TestSchemaChangeReverseMutations
  pkg/sql/schema_changer_test.go
Labels: backport-22.2.x, backport-23.1.x

#108017 sql: fix TestSQLStatsRegions flaky test
  pkg/ccl/testccl/sqlstatsccl/BUILD.bazel
  pkg/ccl/testccl/sqlstatsccl/sql_stats_test.go
Labels: O-community, backport-23.1.x

#108060 release-23.1: sql: fix TestSQLStatsCompactor flaky test
  pkg/sql/sqlstats/persistedsqlstats/compaction_test.go
Labels: O-community

#107953 sql: add show default privileges for grantee
  docs/generated/sql/bnf/show_default_privileges_stmt.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/delegate/show_default_privileges.go
  pkg/sql/logictest/testdata/logic_test/show_default_privileges
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/show_default_privileges
  pkg/sql/sem/tree/show.go
Labels: backport-22.2.x, backport-23.1.x

#108069 sql/sem/builtins: deflake TestSerialNormalizationWithUniqueUnorderedID
  pkg/sql/sem/builtins/BUILD.bazel
  pkg/sql/sem/builtins/builtins_test.go
Labels: backport-23.1.x

#108165 sql: fix insight integration test for contention
  pkg/sql/sqlstats/insights/integration/insights_test.go
Labels: O-community, backport-23.1.x

#108208 rowexec: fix remote lookups when streamer is used
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/sql/rowexec/joinreader.go
Labels: backport-22.2.x, backport-23.1.x

#107918 importer: fix collated string imports for MySQL/DELIMITED DATA
  pkg/sql/importer/import_stmt_test.go
  pkg/sql/importer/read_import_mysql.go
  pkg/sql/importer/read_import_mysql_test.go
  pkg/sql/importer/read_import_mysqlout.go
  pkg/sql/rowenc/roundtrip_format.go
Labels: backport-22.2.x, backport-23.1.x

#108054 kvserver: always log store rebalancer transfers and relocates
  pkg/kv/kvserver/store_rebalancer.go
Labels: backport-23.1.x

#108199 sql: fix overload type checking of nested case expressions
  pkg/sql/sem/tree/overload.go
  pkg/sql/sem/tree/type_check_test.go
Labels: backport-23.1.x

#108347 catalog: add more detail to DescriptorNotFoundErrors
  pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row
  pkg/cli/testdata/doctor/test_examine_zipdir
  pkg/cli/testdata/doctor/test_examine_zipdir_verbose
  pkg/sql/catalog/descs/descriptor.go
  pkg/sql/catalog/descs/hydrate.go
  pkg/sql/catalog/errors.go
  pkg/sql/catalog/internal/catkv/catalog_query.go
  pkg/sql/catalog/internal/validate/validate.go
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/nstree/catalog.go
  pkg/sql/crdb_internal_test.go
  pkg/sql/doctor/doctor_test.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
Labels: backport-22.2.x, backport-23.1.x

#107548 roachtest/mixedversion: monitor nodes in every test
  pkg/cmd/roachprod/main.go
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/monitor.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/README.md
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner_test.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/session.go
Labels: backport-23.1.x

#108283 release-22.2: sql: add show default privileges for grantee
  docs/generated/sql/bnf/show_default_privileges_stmt.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/delegate/show_default_privileges.go
  pkg/sql/logictest/testdata/logic_test/show_default_privileges
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/show_default_privileges
  pkg/sql/sem/tree/show.go
Labels: T-sql-foundations

#108401 server: avoid a race in the server controller
  pkg/server/server_controller_channel_orchestrator.go
Labels: backport-23.1.x

#108227 kv: deflake `TestAdminDecommissionedOperations` by setting `server.shutdown.query_wait`
  pkg/server/storage_api/decommission_test.go
Labels: backport-22.2.x, backport-23.1.x

#108324 release-22.2: sql: fix formatting of export
  pkg/sql/parser/testdata/import_export
  pkg/sql/sem/tree/export.go
Labels: T-sql-foundations

#108133 sql: release save point did not retry for two version invariant errors
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/conn_executor_savepoints.go
Labels: backport-23.1.x

#106590 sql: fix VIEWACTIVITY privilege for ListSessions
  pkg/server/application_api/BUILD.bazel
  pkg/server/application_api/sessions_test.go
  pkg/server/privchecker/api.go
  pkg/server/privchecker/privchecker.go
  pkg/server/status.go
Labels: backport-23.1.x

#108395 telemetry: log all querys used by internal-console
  pkg/server/combined_statement_stats.go
  pkg/sql/exec_log.go
  pkg/sql/telemetry_logging.go
  pkg/sql/telemetry_logging_test.go
  pkg/ui/workspaces/cluster-ui/src/api/sqlApi.ts
Labels: backport-23.1.x

#108460 ui: fix crash when adminUI is not yet initialized
  pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsConnected.ts
  pkg/ui/workspaces/cluster-ui/src/store/statementDiagnostics/statementDiagnostics.selectors.ts
Labels: backport-23.1.x

#108484 roachtest: better failure message for c2c roachtests
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: backport-23.1.x

#108186 parser: add SHOW BACKUP...NOWAIT hidden alias for SKIP SIZE
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/show
Labels: backport-23.1.x

#108514 awsdms: use custom status checker
  pkg/cmd/roachtest/tests/awsdms.go
Labels: backport-22.2.x, backport-23.1.x

#108285 release-23.1: sql: add show default privileges for grantee
  docs/generated/sql/bnf/show_default_privileges_stmt.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/delegate/show_default_privileges.go
  pkg/sql/logictest/testdata/logic_test/show_default_privileges
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/show_default_privileges
  pkg/sql/sem/tree/show.go
Labels: T-sql-foundations

#107991 streamproducer: retry loading a job in the c2c stream producer
  pkg/ccl/streamingccl/replicationutils/utils.go
  pkg/ccl/streamingccl/streamingest/BUILD.bazel
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go
  pkg/ccl/streamingccl/streamproducer/producer_job.go
  pkg/jobs/jobs.go
  pkg/jobs/jobs_test.go
  pkg/sql/exec_util.go
Labels: backport-23.1.x

#108595 ui: fix occurrence of x.toNumber is not a function
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionsTable.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts
Labels: backport-23.1.x

#108566 cli/demo: various fixes
  pkg/acceptance/generated_cli_test.go
  pkg/cli/clisqlshell/sql.go
  pkg/cli/democluster/api/api.go
  pkg/cli/democluster/demo_cluster.go
  pkg/cli/interactive_tests/test_demo_multitenant.tcl
  pkg/cli/interactive_tests/test_demo_node_cmds.tcl
Labels: backport-23.1.x

#108679 kvclient/kvcoord: respect rangefeed closedts interval in stuck watcher
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvserver/kvserverbase/base.go
  pkg/kv/kvserver/replica_rangefeed.go
Labels: backport-23.1.x

#108634 sql: fix TestSQLStatsRegions test
  pkg/ccl/testccl/sqlstatsccl/BUILD.bazel
  pkg/ccl/testccl/sqlstatsccl/sql_stats_test.go
Labels: O-community, backport-23.1.x, backport-23.1.9-rc

#108594 roachtest: allow callers to listen for node events in monitor
  pkg/cmd/roachtest/cluster/monitor_interface.go
  pkg/cmd/roachtest/monitor.go
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
  pkg/cmd/roachtest/tests/sstable_corruption.go
Labels: backport-23.1.x

#108709 release-23.1: sql: fix TestSQLStatsRegions test
  pkg/ccl/testccl/sqlstatsccl/BUILD.bazel
  pkg/ccl/testccl/sqlstatsccl/sql_stats_test.go
Labels: O-community

#108713 release-23.1.9-rc: sql: fix TestSQLStatsRegions test
  pkg/ccl/testccl/sqlstatsccl/BUILD.bazel
  pkg/ccl/testccl/sqlstatsccl/sql_stats_test.go
Labels: O-community

#108703 kvserver: deflake TestReplicateQueueLeasePreferencePurgatoryError
  pkg/kv/kvserver/replicate_queue_test.go
Labels: backport-23.1.x, backport-23.1.9-rc

#108456 server: make the span stats fan-out more fault tolerant
  pkg/roachpb/span_stats.go
  pkg/roachpb/span_stats.proto
  pkg/server/admin.go
  pkg/server/api_v2_ranges.go
  pkg/server/index_usage_stats.go
  pkg/server/key_visualizer_server.go
  pkg/server/server.go
  pkg/server/span_stats_server.go
  pkg/server/span_stats_test.go
  pkg/server/sql_stats.go
  pkg/server/statements.go
  pkg/server/status.go
  pkg/server/testing_knobs.go
Labels: backport-23.1.x

#108486 server: allow users with VIEWACTIVITY to get console settings
  pkg/server/BUILD.bazel
  pkg/server/admin.go
  pkg/server/application_api/BUILD.bazel
  pkg/server/application_api/config_test.go
  pkg/settings/registry.go
Labels: backport-23.1.x, backport-23.1.9-rc

#108777 metricspoller: avoid forever-growing context chain
  pkg/jobs/metricspoller/poller.go
Labels: backport-23.1.x

#107954 schema: allow transaction retry in schema changer backfill
  pkg/ccl/backupccl/BUILD.bazel
  pkg/ccl/backupccl/datadriven_test.go
  pkg/kv/db.go
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/testing_knobs.go
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/mock_transactional_sender.go
  pkg/kv/sender.go
  pkg/kv/txn.go
  pkg/sql/BUILD.bazel
  pkg/sql/create_as_test.go
  pkg/sql/internal.go
  pkg/sql/schema_changer.go
  pkg/testutils/kvclientutils/BUILD.bazel
  pkg/testutils/kvclientutils/txn_restart.go
Labels: backport-23.1.x

#108743 backupccl: dont validate introduced tenant spans
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/targets.go
Labels: T-disaster-recovery

#108811 sqlsmith: disable NAME type in postgres mode
  pkg/internal/sqlsmith/type.go
Labels: backport-22.2.x, backport-23.1.x

#108835 persistedsqlstats: add cluster setting to enable flush on row limit r…
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go
  pkg/sql/sqlstats/persistedsqlstats/flush.go
  pkg/sql/sqlstats/persistedsqlstats/flush_test.go
Labels: backport-23.1.x

#108897 cli: use reusable listeners in TestStageVersionCheck
  pkg/cli/debug_recover_loss_of_quorum_test.go
Labels: backport-23.1.x

#108818 sql: fix pg_statistic_ext behavior for dropped tables
  pkg/sql/create_stats_test.go
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: backport-23.1.x

#108851 release: automatically update pkg/testutils/release/cockroach_releases.yaml
  .github/workflows/update_releases.yaml
Labels: C-enhancement, A-release, T-release

#108927 release-22.2: jobs: pass explicit transaction to lookup-num-running query
  pkg/jobs/job_scheduler.go
Labels: T-jobs

#108939 roachtest: ignore upstream flakes in activerecord and sequelize
  pkg/cmd/roachtest/tests/activerecord.go
  pkg/cmd/roachtest/tests/sequelize.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.9-rc

#108873 requestbatcher: change MaxTimeout to apply to each BatchRequest
  pkg/internal/client/requestbatcher/batcher.go
  pkg/internal/client/requestbatcher/batcher_test.go
Labels: backport-23.1.x

#108947 sql: fix sql compaction job full scan
  pkg/sql/opt/exec/execbuilder/testdata/sql_activity_stats_compaction
  pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go
Labels: backport-23.1.x, backport-23.1.9-rc

#108987 release-23.1: sql: fix sql compaction job full scan
  pkg/sql/opt/exec/execbuilder/testdata/sql_activity_stats_compaction
  pkg/sql/sqlstats/persistedsqlstats/compaction_exec.go
Labels: blathers-backport

#108930 roachtest: add ability to set env vars during chaos testing
  pkg/cmd/roachtest/tests/cdc.go
  pkg/cmd/roachtest/tests/chaos.go
Labels: backport-23.1.x, backport-23.1.9-rc

#108993 logictest: remove unnecessary usage of a sequence
  pkg/sql/logictest/testdata/logic_test/alter_table
Labels: backport-23.1.x

#108994 roachprod: do not send monitor error when context is canceled
  pkg/roachprod/install/cluster_synced.go
Labels: backport-23.1.x

#108951 cloud/azure: allow all tests in TestAzure to be run in parallel
  pkg/cloud/azure/azure_storage_test.go
Labels: backport-23.1.x, backport-23.1.9-rc

#109025 multiregionccl: unskip TestRegionAddDropWithConcurrentBackupOps
  pkg/ccl/multiregionccl/region_test.go
Labels: backport-23.1.x

#109030 kv: don't log trace of cancelled requests if not Export
  pkg/server/node.go
Labels: backport-23.1.9-rc

#108952 physicalplan: do not simply project out render expressions
  pkg/sql/logictest/testdata/logic_test/distsql_agg
  pkg/sql/opt/exec/execbuilder/testdata/distsql_agg
  pkg/sql/physicalplan/BUILD.bazel
  pkg/sql/physicalplan/physical_plan.go
  pkg/sql/physicalplan/physical_plan_test.go
Labels: backport-22.2.x, backport-23.1.x

#108356 c2c: add new streaming client and value generator for span config replication
  pkg/ccl/streamingccl/event.go
  pkg/ccl/streamingccl/replicationtestutils/BUILD.bazel
  pkg/ccl/streamingccl/replicationtestutils/replication_helpers.go
  pkg/ccl/streamingccl/replicationtestutils/span_config_helpers.go
  pkg/ccl/streamingccl/streamclient/BUILD.bazel
  pkg/ccl/streamingccl/streamclient/client.go
  pkg/ccl/streamingccl/streamclient/client_helpers.go
  pkg/ccl/streamingccl/streamclient/client_test.go
  pkg/ccl/streamingccl/streamclient/partitioned_stream_client.go
  pkg/ccl/streamingccl/streamclient/partitioned_stream_client_test.go
  pkg/ccl/streamingccl/streamclient/random_stream_client.go
  pkg/ccl/streamingccl/streamclient/span_config_stream_client.go
  pkg/ccl/streamingccl/streamclient/span_config_stream_client_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go
  pkg/ccl/streamingccl/streamproducer/BUILD.bazel
  pkg/ccl/streamingccl/streamproducer/event_stream.go
  pkg/ccl/streamingccl/streamproducer/replication_manager.go
  pkg/ccl/streamingccl/streamproducer/replication_stream_test.go
  pkg/ccl/streamingccl/streamproducer/span_config_event_stream.go
  pkg/ccl/streamingccl/streamproducer/stream_event_batcher.go
  pkg/ccl/streamingccl/streamproducer/stream_event_batcher_test.go
  pkg/ccl/streamingccl/streamproducer/stream_lifetime.go
  pkg/repstream/streampb/stream.proto
  pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go
  pkg/spanconfig/spanconfigkvsubscriber/spanconfigdecoder.go
  pkg/sql/exec_util.go
  pkg/sql/sem/builtins/replication_builtins.go
  pkg/sql/sem/eval/context.go
Labels: T-disaster-recovery

#109044 sqlstats: ignore EXPLAIN stmts on insights
  pkg/sql/sqlstats/insights/detector.go
  pkg/sql/sqlstats/insights/registry_test.go
Labels: backport-23.1.x

#109076 pgwire: avoid mentioning "tenants" in pre-serve metric descriptions
  pkg/sql/pgwire/pre_serve.go
  pkg/sql/pgwire/server.go
Labels: backport-23.1.x

#109139 roachtest: use X-infra-flake for GH issues created due to infra flakes
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.9-rc

#109111 upgrades: avoid possible self-contention in tenant upgrade
  pkg/sql/exec_util.go
  pkg/sql/set_cluster_setting.go
  pkg/upgrade/system_upgrade.go
  pkg/upgrade/upgradecluster/cluster.go
  pkg/upgrade/upgradecluster/tenant_cluster.go
  pkg/upgrade/upgrademanager/manager.go
Labels: backport-23.1.x

#109171 roachtest: remove healthchecker from DR tests
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#108354 sqlstats: fix fullScan determination and add test coverage
  pkg/server/application_api/sql_stats_test.go
  pkg/server/combined_statement_stats.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.9-rc

#109173 bazci/githubpost: allow C-Test-Failure to be disabled by CI config
  pkg/cmd/bazci/githubpost/githubpost.go
  pkg/cmd/bazci/githubpost/githubpost_test.go
Labels: backport-23.1.x

#109221 roachtest: provision 250 MB/s for restore tests on AWS
  pkg/cmd/roachtest/tests/restore.go
Labels: backport-23.1.x

#109249 sql/tests: use smaller lease timeout for random schema change tests
  pkg/sql/tests/rsg_test.go
Labels: backport-23.1.x

#109235 release-23.1: roachtest: remove healthchecker from DR tests
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#109227 roachtest: clean up node shutdown infra and deflake c2c/shutdown
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/import.go
  pkg/cmd/roachtest/tests/jobs.go
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#109300 builtins: fix memory accounting of `st_collect` and `st_makeline` aggregates
  pkg/geo/geo.go
  pkg/sql/sem/builtins/aggregate_builtins.go
Labels: backport-23.1.x

#108954 invertedidx: derive geog/geom filters which enable inverted index scan
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/opt/invertedidx/geo.go
  pkg/sql/opt/norm/comp_funcs.go
  pkg/sql/opt/norm/rules/comp.opt
  pkg/sql/opt/norm/testdata/rules/comp
  pkg/sql/opt/xform/testdata/coster/spatial-filters
  pkg/sql/opt/xform/testdata/rules/select
Labels: backport-23.1.x, backport-23.1.9-rc

#109412 roachtest: close the disk usage logger in restore perf tests
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#109330 release-22.2: roachtest: remove healthchecker from DR tests
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#109362 release-23.1: roachtest: clean up node shutdown infra and deflake c2c/shutdown
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/import.go
  pkg/cmd/roachtest/tests/jobs.go
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#109419 errorutil: de-emphasize "multi-tenancy" in the main compat error message
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/nemeses_test.go
  pkg/ccl/changefeedccl/validations_test.go
  pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant
  pkg/ccl/logictestccl/testdata/logic_test/tenant_unsupported
  pkg/ccl/logictestccl/testdata/logic_test/zone_config_secondary_tenants_disallowed
  pkg/ccl/workloadccl/fixture.go
  pkg/cli/interactive_tests/test_demo_partitioning.tcl
  pkg/cli/testdata/zip/testzip_external_process_virtualization
  pkg/cli/testdata/zip/testzip_shared_process_virtualization
  pkg/inspectz/unsupported.go
  pkg/kv/kvserver/kvserverbase/stores.go
  pkg/server/server_sql.go
  pkg/sql/logictest/testdata/logic_test/kv_builtin_functions_tenant
  pkg/sql/set_zone_config.go
  pkg/util/errorutil/tenant.go
  pkg/util/errorutil/tenant_deprecated_wrapper.go
  pkg/workload/workloadsql/workloadsql.go
Labels: backport-23.1.x

#108754 sql: add in-flight trace to the stmt bundle
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
  pkg/sql/instrumentation.go
Labels: backport-22.2.x, backport-23.1.x

#109463 build/roachtest: do not exit with code 11 on cluster creation failure
  build/teamcity-roachtest-invoke.sh
  pkg/cmd/roachtest/main.go
Labels: backport-23.1.x

#109484 release-23.1: sql/tests: fix test size of random syntax generation
  pkg/sql/tests/BUILD.bazel
Labels: backport

#109466 release-23.1: ui: use cluster setting from redux on schema insights
  pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/schemaInsightsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts
  pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.stories.tsx
  pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.stories.tsx
  pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPage.stories.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/schemaInsights/schemaInsights.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/insights/schemaInsights/schemaInsightsPageConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/schemaInsights/schemaInsightsView.tsx
  pkg/ui/workspaces/cluster-ui/src/store/clusterSettings/clusterSettings.selectors.ts
  pkg/ui/workspaces/cluster-ui/src/store/databaseDetails/databaseDetails.saga.spec.ts
  pkg/ui/workspaces/cluster-ui/src/store/databaseTableDetails/tableDetails.saga.spec.ts
  pkg/ui/workspaces/cluster-ui/src/store/schemaInsights/schemaInsights.reducer.ts
  pkg/ui/workspaces/cluster-ui/src/store/schemaInsights/schemaInsights.sagas.ts
  pkg/ui/workspaces/cluster-ui/src/util/constants.ts
  pkg/ui/workspaces/db-console/src/redux/apiReducers.spec.ts
  pkg/ui/workspaces/db-console/src/redux/clusterSettings/clusterSettings.selectors.ts
  pkg/ui/workspaces/db-console/src/util/api.spec.ts
  pkg/ui/workspaces/db-console/src/util/constants.ts
  pkg/ui/workspaces/db-console/src/views/databases/databaseDetailsPage/redux.spec.ts
  pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.spec.ts
  pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.spec.ts
  pkg/ui/workspaces/db-console/src/views/insights/schemaInsightsPage.tsx
Labels: backport

#109468 release-23.1: ui: show warning when data is not old enough
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.tsx
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScale.module.scss
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleLabel.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.stories.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPageConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/util/convert.ts
  pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx
  pkg/ui/workspaces/db-console/src/views/transactions/transactionsPage.tsx
Labels: backport

#108625 backupccl: dont validate introduced tenant spans
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/targets.go
Labels: T-disaster-recovery

#109488 release-22.2: sql: add in-flight trace to the stmt bundle
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
  pkg/sql/instrumentation.go
Labels: backport

#109487 release-23.1: sql: add in-flight trace to the stmt bundle
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
  pkg/sql/instrumentation.go
Labels: backport

#109388 sql: skip TestRelocateNonVoters under race
  pkg/sql/multitenant_admin_function_test.go
Labels: backport-23.1.x

#109508 insights/integration: deflake TestInsightsIntegrationForContention
  pkg/sql/sqlstats/insights/integration/insights_test.go
Labels: backport-23.1.x

#109541 builtins: avoid overflow in sum square difference calculation
  pkg/sql/logictest/testdata/logic_test/distsql_agg
  pkg/sql/sem/builtins/aggregate_builtins.go
Labels: backport-23.1.x

#109585 cloudtestutils: make antagonistic read file name unique
  pkg/cloud/cloudtestutils/cloud_test_helpers.go
Labels: backport-23.1.x

#109509 opt: fix ordinal column reference internal error
  pkg/sql/opt/optbuilder/testdata/table_ref
  pkg/sql/opt/optbuilder/util.go
Labels: backport-22.2.x, backport-23.1.x

#109592 sql: fix SQL Activity table execution_total_cluster_seconds
  pkg/server/combined_statement_stats.go
  pkg/sql/BUILD.bazel
  pkg/sql/sql_activity_update_job.go
  pkg/sql/sql_activity_update_job_test.go
Labels: backport-23.1.x

#109308 kvstreamer: add more tracing
  pkg/kv/kvclient/kvstreamer/BUILD.bazel
  pkg/kv/kvclient/kvstreamer/requests_provider.go
  pkg/kv/kvclient/kvstreamer/results_buffer.go
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/kv/kvpb/api.go
  pkg/kv/kvpb/batch.go
Labels: backport-22.2.x, backport-23.1.x

#109513 import: fix incomplete successful imports during node failure
  pkg/sql/importer/read_import_base.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.9-rc

#109598 release-22.2: sql: fix formatting of import, backup and create tenant
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/show_changefeed_jobs_test.go
  pkg/sql/importer/import_csv_mark_redaction_test.go
  pkg/sql/importer/import_stmt_test.go
  pkg/sql/parser/testdata/changefeed
  pkg/sql/parser/testdata/show
  pkg/sql/sem/tree/changefeed.go
  pkg/sql/sem/tree/show.go
Labels: backport

#109677 release-22.2: ccl/sqlproxyccl: deflake TestDenylistUpdate
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
Labels: backport

#109653 release-23.1: kvstreamer: add more tracing
  pkg/kv/kvclient/kvstreamer/BUILD.bazel
  pkg/kv/kvclient/kvstreamer/requests_provider.go
  pkg/kv/kvclient/kvstreamer/results_buffer.go
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/kv/kvpb/api.go
  pkg/kv/kvpb/batch.go
Labels: backport

#109654 release-22.2: kvstreamer: add more tracing
  pkg/kv/kvclient/kvstreamer/BUILD.bazel
  pkg/kv/kvclient/kvstreamer/requests_provider.go
  pkg/kv/kvclient/kvstreamer/results_buffer.go
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/roachpb/api.go
  pkg/roachpb/batch.go
Labels: backport

#109695 release-22.2: sql/tests: deflake TestCancelQueriesRace
  pkg/sql/show_test.go
  pkg/util/leaktest/leaktest.go
Labels: backport

#109692 release-23.1: tree: handle format of START/BEGIN inside of functions
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/begin_commit
  pkg/sql/sem/tree/txn.go
Labels: backport

#109701 roachtest: update ruby-pg and activerecord tests
  pkg/cmd/roachtest/tests/activerecord_blocklist.go
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
  pkg/cmd/roachtest/tests/ruby_pg_blocklist.go
Labels: backport-23.1.x, backport-23.1.9-rc

#109696 sql: optimize persistedsqlstats flush size check
  pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go
  pkg/sql/sqlstats/persistedsqlstats/flush.go
  pkg/sql/sqlstats/persistedsqlstats/flush_test.go
  pkg/sql/sqlstats/persistedsqlstats/provider.go
Labels: backport-22.2.x, backport-23.1.x

#109708 release-23.1: go.mod: bump Pebble to b1263239fd6e
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#109715 rpc: increase gRPC server keepalive interval to 2x PingInterval
  pkg/base/config.go
  pkg/rpc/keepalive.go
Labels: backport-23.1.x, backport-23.1.9-rc

#109721 release-23.1: logictest: deflake zone_config_system_tenant
  pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant
Labels: backport

#109731 sql: difference built-in as wrong return value type
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/fuzzystrmatch
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
Labels: backport-22.2.x, backport-23.1.x

#108878 sql: fix sequence reporting of smallint type
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/information_schema
Labels: O-community, backport-23.1.x

#109713 backupccl: avoid creating spans that start or end on a .Next() key
  pkg/ccl/backupccl/restore_span_covering.go
  pkg/ccl/backupccl/restore_span_covering_test.go
Labels: backport-23.1.x, backport-23.1.9-rc

#109748 roachpb: don't un-abort txn proto after restart
  pkg/roachpb/data.go
  pkg/roachpb/data_test.go
Labels: backport-22.2.x, backport-23.1.x

#109510 kv: prioritize errors in UpdateStateOnRemoteRetryableErr
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/txn_external_test.go
Labels: backport-22.2.x, backport-23.1.x

#109784 loqrecovery: fix TestRetrieveRangeStatus to wait 5x replication
  pkg/kv/kvserver/loqrecovery/server_integration_test.go
Labels: backport-23.1.x

#109605 ui: show source table on error message
  pkg/ui/workspaces/cluster-ui/src/sqlActivity/errorComponent.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx
Labels: backport-23.1.x

#109805 release-23.1: metrics: refactor histogram bucket generation and testing
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/sqlproxyccl/connector_test.go
  pkg/ccl/sqlproxyccl/metrics.go
  pkg/ccl/streamingccl/streamingest/metrics.go
  pkg/kv/bulk/bulk_metrics.go
  pkg/kv/kvclient/kvcoord/txn_metrics.go
  pkg/kv/kvprober/kvprober.go
  pkg/kv/kvserver/kvflowcontrol/kvflowcontroller/kvflowcontroller_metrics.go
  pkg/kv/kvserver/kvflowcontrol/kvflowhandle/kvflowhandle_metrics.go
  pkg/kv/kvserver/liveness/liveness.go
  pkg/kv/kvserver/logstore/logstore_bench_test.go
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/txnwait/metrics.go
  pkg/rpc/clock_offset.go
  pkg/server/node.go
  pkg/sql/conn_executor.go
  pkg/sql/execinfra/metrics.go
  pkg/sql/mem_metrics.go
  pkg/sql/pgwire/pre_serve.go
  pkg/sql/pgwire/server.go
  pkg/sql/ttl/ttljob/ttljob_metrics.go
  pkg/util/admission/elastic_cpu_granter.go
  pkg/util/admission/work_queue.go
  pkg/util/metric/BUILD.bazel
  pkg/util/metric/aggmetric/agg_metric_test.go
  pkg/util/metric/histogram_buckets.go
  pkg/util/metric/histogram_buckets_test.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_test.go
  pkg/util/metric/registry_test.go
  pkg/util/metric/testdata/BatchProcessLatencyBuckets
  pkg/util/metric/testdata/Count1KBuckets
  pkg/util/metric/testdata/DataSize16MBBuckets
  pkg/util/metric/testdata/IOLatencyBuckets
  pkg/util/metric/testdata/LongRunning60mLatencyBuckets
  pkg/util/metric/testdata/MemoryUsage64MBBuckets
  pkg/util/metric/testdata/Percent100Buckets
  pkg/util/metric/testdata/ReplicaBatchRequestCountBuckets
  pkg/util/metric/testdata/ReplicaCPUTimeBuckets
Labels: backport

#109827 release-22.1: spanconfig: skip protected timestamps on non-table data
  pkg/keys/spans.go
  pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go
  pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber_test.go
Labels: backport

#109828 release-22.2: spanconfig: skip protected timestamps on non-table data
  pkg/keys/spans.go
  pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go
  pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber_test.go
Labels: backport

#109829 release-23.1: spanconfig: skip protected timestamps on non-table data
  pkg/keys/spans.go
  pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber.go
  pkg/spanconfig/spanconfigkvsubscriber/kvsubscriber_test.go
Labels: backport

#109815 release-23.1: kv: deflake TestTxnCoordSenderRetries
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
Labels: backport

#109816 release-22.2: kv: deflake TestTxnCoordSenderRetries
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
Labels: backport

#109846 Revert "sql: optimize persistedsqlstats flush size check"
  pkg/sql/sqlstats/persistedsqlstats/cluster_settings.go
  pkg/sql/sqlstats/persistedsqlstats/flush.go
  pkg/sql/sqlstats/persistedsqlstats/flush_test.go
  pkg/sql/sqlstats/persistedsqlstats/provider.go
Labels: backport-23.1.x
