Repository cockroachdb/cockroach, pull requests merged in 2023-04, with the labels that each got.

#100334 ttl: change delete priority to TTLLowPri
  pkg/sql/ttl/ttljob/ttljob_processor.go
Labels: backport-23.1.x

#100328 roachtest: update expected ruby-pg failures
  pkg/cmd/roachtest/tests/ruby_pg_blocklist.go
Labels: backport-23.1.x

#99726 storage: aggregate iterator stats
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/spanset/BUILD.bazel
  pkg/kv/kvserver/spanset/batch.go
  pkg/storage/bench_pebble_test.go
  pkg/storage/engine.go
  pkg/storage/intent_interleaving_iter.go
  pkg/storage/mvcc.go
  pkg/storage/pebble.go
  pkg/storage/pebble_batch.go
  pkg/storage/pebble_iterator.go
  pkg/storage/pebble_iterator_test.go
  pkg/ts/catalog/chart_catalog.go
Labels: backport-23.1.x

#100523 upgrades: ensure that create job_info synchronizes with jobs
  pkg/upgrade/upgrades/system_job_info.go
  pkg/upgrade/upgrades/system_job_info_test.go
Labels: backport-23.1.x

#99133 roachprod: enforce consistent logging
  pkg/cmd/roachprod/BUILD.bazel
  pkg/cmd/roachprod/flags.go
  pkg/cmd/roachprod/main.go
  pkg/roachprod/BUILD.bazel
  pkg/roachprod/cloud/BUILD.bazel
  pkg/roachprod/cloud/cluster_cloud.go
  pkg/roachprod/cloud/gc.go
  pkg/roachprod/cloud/gc_aws_keypairs.go
  pkg/roachprod/clusters_cache.go
  pkg/roachprod/config/BUILD.bazel
  pkg/roachprod/config/config.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/roachprod.go
  pkg/roachprod/vm/aws/BUILD.bazel
  pkg/roachprod/vm/aws/aws.go
  pkg/roachprod/vm/aws/keys.go
  pkg/roachprod/vm/aws/support.go
  pkg/roachprod/vm/azure/BUILD.bazel
  pkg/roachprod/vm/azure/azure.go
  pkg/roachprod/vm/flagstub/flagstub.go
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/gce/utils.go
  pkg/roachprod/vm/local/local.go
  pkg/roachprod/vm/vm.go
Labels: backport-22.2.x, backport-23.1.x

#100479 sql: add table storage params to set histogram samples and buckets count
  pkg/sql/catalog/descpb/structured.proto
  pkg/sql/catalog/descriptor.go
  pkg/sql/catalog/tabledesc/structured.go
  pkg/sql/catalog/tabledesc/validate_test.go
  pkg/sql/create_stats.go
  pkg/sql/distsql_plan_stats.go
  pkg/sql/importer/import_job.go
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/stats/histogram.go
  pkg/sql/storageparam/tablestorageparam/table_storage_param.go
Labels: backport-23.1.x

#100536 kvtenantccl: unskip TestTenantUpgradeInterlock (and move it to its own package)
  pkg/BUILD.bazel
  pkg/ccl/kvccl/kvtenantccl/BUILD.bazel
  pkg/ccl/kvccl/kvtenantccl/upgradeccl/BUILD.bazel
  pkg/ccl/kvccl/kvtenantccl/upgradeccl/main_test.go
  pkg/ccl/kvccl/kvtenantccl/upgradeccl/tenant_upgrade_test.go
  pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/BUILD.bazel
  pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/main_test.go
  pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/tenant_upgrade_test.go
Labels: backport-23.1.x

#100541 logictest: disable circuit breakers in TestParallel
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/sql/logictest/parallel_test.go
Labels: backport-23.1.x

#100401 raftlog: correctly decode empty commands
  pkg/kv/kvserver/kvserverbase/forced_error.go
  pkg/kv/kvserver/raftlog/entry.go
  pkg/kv/kvserver/raftlog/entry_test.go
Labels: backport-23.1.x

#100430 kvserver: eagerly extend expiration leases in Raft scheduler
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_lease_renewal_test.go
  pkg/kv/kvserver/replica_proposal.go
  pkg/kv/kvserver/replica_raft.go
  pkg/kv/kvserver/replica_raft_quiesce.go
  pkg/kv/kvserver/replica_range_lease.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/replicate_queue.go
  pkg/kv/kvserver/store.go
  pkg/kv/kvserver/testing_knobs.go
Labels: backport-23.1.x

#100644 upgrades: deflake TestMigrationWithFailures
  pkg/upgrade/upgrades/schema_changes_external_test.go
Labels: backport-23.1.x

#100665 awsdms: key off TC_BUILD_ID for uniqueness
  pkg/cmd/roachtest/tests/awsdms.go
Labels: backport-23.1.x

#100326 storage: set range tombstone cluster setting default to false
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/sql/logictest/testdata/logic_test/mixed_version_range_tombstones
  pkg/sql/logictest/tests/cockroach-go-testserver-upgrade-to-master/BUILD.bazel
  pkg/sql/logictest/tests/cockroach-go-testserver-upgrade-to-master/generated_test.go
  pkg/sql/schemachanger/sctest/cumulative.go
  pkg/storage/mvcc.go
Labels: backport-23.1.x

#100014 backupccl: update system table RESTORE logic to check for NOT NULL cols
  pkg/ccl/backupccl/system_schema.go
Labels: backport-23.1.x

#100752 roachprod: fix creation of AWS clusters with custom labels
  pkg/roachprod/vm/aws/aws.go
Labels: backport-22.2.x, backport-23.1.x

#99833 changefeedccl: reduce duplicate schema registrations
  pkg/ccl/changefeedccl/cdctest/schema_registry.go
  pkg/ccl/changefeedccl/schema_registry.go
  pkg/ccl/changefeedccl/schema_registry_test.go
Labels: backport-22.2.x

#100756 sql/stats: fix flakes due to automatic stats on system tables
  pkg/sql/importer/import_stmt_test.go
  pkg/sql/stats/automatic_stats.go
  pkg/sql/stats/automatic_stats_test.go
Labels: backport-23.1.x

#100869 server: properly config disk spill storage for shared-process tenant servers
  pkg/ccl/serverccl/server_controller_test.go
  pkg/server/server_controller_new_server.go
  pkg/server/testserver.go
  pkg/sql/colflow/draining_test.go
  pkg/sql/colmem/allocator.go
  pkg/util/mon/bytes_usage.go
  pkg/util/mon/bytes_usage_test.go
Labels: backport-23.1.x

#100895 upgrades: fix race condition in TestWaitForDelRangeInGCJob
  pkg/upgrade/upgrades/wait_for_del_range_in_gc_job_test.go
Labels: backport-23.1.x

#100873 upgrademanager: audit tests that use MakeTestingClusterSettingsWithVersions
  pkg/upgrade/upgrademanager/manager_external_test.go
Labels: backport-23.1.x

#98116 kv: consider ErrReplicaNotFound and ErrReplicaCannotHoldLease to be retryable
  pkg/kv/kvnemesis/validator.go
  pkg/kv/kvserver/batcheval/cmd_lease_test.go
  pkg/kv/kvserver/client_lease_test.go
  pkg/kv/kvserver/client_replica_test.go
  pkg/kv/kvserver/markers.go
  pkg/kv/kvserver/replica_learner_test.go
  pkg/kv/kvserver/replica_raft.go
  pkg/kv/kvserver/replica_range_lease.go
  pkg/roachpb/metadata_replicas.go
Labels: backport-22.2.x, backport-23.1.x

#100837 roachtest: fix assertion in drain test
  pkg/cmd/roachtest/tests/drain.go
Labels: backport-22.1.x, backport-22.2.x, backport-23.1.x

#100964 sql: add issue number for unimplemented udf default params
  pkg/sql/create_function.go
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go
Labels: backport-23.1.x

#100920 cli/sql: announce the target tenant in the output
  pkg/cli/clisqlclient/conn.go
  pkg/cli/clisqlshell/sql.go
  pkg/cli/democluster/demo_cluster.go
  pkg/cli/interactive_tests/test_client_side_checking.tcl
  pkg/cli/interactive_tests/test_demo_cli_integration.tcl.disabled
  pkg/cli/interactive_tests/test_demo_multitenant.tcl.disabled
  pkg/cli/interactive_tests/test_sql_version_reporting.tcl
Labels: backport-23.1.x

#100922 server: increase timeout for TestClusterVersionUpgrade
  pkg/server/version_cluster_test.go
Labels: backport-23.1.x

#101218 release-23.1: streamingccl: deflake TestRandomClientGeneration
  pkg/ccl/streamingccl/streamclient/random_stream_client.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go
Labels: T-disaster-recovery, backport-23.1.0

#100954 schemachanger: Memory monitoring builder and explain
  pkg/sql/catalog/descriptor.go
  pkg/sql/conn_executor.go
  pkg/sql/explain_ddl.go
  pkg/sql/internal.go
  pkg/sql/schema_change_plan_node.go
  pkg/sql/schema_changer_state.go
  pkg/sql/schemachanger/scbuild/BUILD.bazel
  pkg/sql/schemachanger/scbuild/build.go
  pkg/sql/schemachanger/scbuild/builder_state.go
  pkg/sql/schemachanger/scbuild/builder_test.go
  pkg/sql/schemachanger/scdeps/sctestutils/BUILD.bazel
  pkg/sql/schemachanger/scdeps/sctestutils/sctestutils.go
  pkg/sql/schemachanger/scexec/executor_external_test.go
  pkg/sql/schemachanger/scpb/state.go
  pkg/sql/schemachanger/scplan/BUILD.bazel
  pkg/sql/schemachanger/scplan/plan.go
  pkg/sql/schemachanger/scplan/plan_explain.go
  pkg/sql/schemachanger/scplan/plan_test.go
  pkg/sql/schemachanger/sctest/end_to_end.go
Labels: backport-23.1.x, backport-23.1.0

#101267 sql: job SessionData OptimizerFKCascadesLimit not defaulting to optDrivenFKCascadesClusterLimit
  pkg/sql/schema_changer.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.0

#101258 ui: encode time window in url for metrics charts
  pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx
  pkg/ui/workspaces/db-console/src/views/cluster/containers/timeScaleDropdownWithSearchParams/index.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx
Labels: backport-22.2.x, backport-23.1.x

#98203 kvtenant: move kv tenant connector out of ccl
  pkg/BUILD.bazel
  pkg/ccl/BUILD.bazel
  pkg/ccl/ccl_init.go
  pkg/ccl/kvccl/kvtenantccl/BUILD.bazel
  pkg/ccl/kvccl/kvtenantccl/connector.go
  pkg/ccl/kvccl/kvtenantccl/connector_factory.go
  pkg/ccl/kvccl/kvtenantccl/test_utils.go
  pkg/ccl/serverccl/diagnosticsccl/main_test.go
  pkg/ccl/serverccl/diagnosticsccl/reporter_test.go
  pkg/ccl/sqlproxyccl/BUILD.bazel
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
  pkg/ccl/sqlproxyccl/tenant/BUILD.bazel
  pkg/ccl/sqlproxyccl/tenant/directory_cache_test.go
  pkg/ccl/testccl/sqlccl/BUILD.bazel
  pkg/ccl/testccl/sqlccl/run_control_test.go
  pkg/cli/BUILD.bazel
  pkg/cli/main_test.go
  pkg/cli/zip_tenant_test.go
  pkg/kv/kvclient/kvtenant/BUILD.bazel
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/kv/kvclient/kvtenant/connector_factory.go
  pkg/kv/kvclient/kvtenant/connector_test.go
  pkg/kv/kvclient/kvtenant/main_test.go
  pkg/kv/kvclient/kvtenant/rangedesc_iter.go
  pkg/kv/kvclient/kvtenant/setting_overrides.go
  pkg/kv/kvclient/kvtenant/setting_overrides_test.go
  pkg/kv/kvclient/kvtenant/tenant_kv_test.go
  pkg/kv/kvclient/kvtenant/tenant_range_lookup_test.go
  pkg/kv/kvclient/kvtenant/tenant_scan_range_descriptors_test.go
  pkg/kv/kvclient/kvtenant/tenant_trace_test.go
  pkg/kv/kvclient/kvtenant/test_utils.go
  pkg/kv/kvclient/rangefeed/rangefeedcache/BUILD.bazel
  pkg/kv/kvclient/rangefeed/rangefeedcache/main_test.go
  pkg/kv/kvclient/rangefeed/rangefeedcache/watcher_test.go
  pkg/server/BUILD.bazel
  pkg/server/config.go
  pkg/server/drain_test.go
  pkg/server/main_test.go
  pkg/server/server_controller_new_server.go
  pkg/server/tenant.go
  pkg/sql/BUILD.bazel
  pkg/sql/main_test.go
  pkg/sql/sqlinstance/instancestorage/BUILD.bazel
  pkg/sql/sqlinstance/instancestorage/instancecache_test.go
  pkg/sql/sqlinstance/instancestorage/main_test.go
  pkg/sql/telemetry_test.go
  pkg/ts/BUILD.bazel
  pkg/ts/main_test.go
  pkg/ts/server_test.go
Labels: A-multitenancy, backport-23.1.x

#101323 upgrades: avoid using a permanent migration to create a new table
  pkg/cli/testdata/doctor/test_examine_cluster
  pkg/upgrade/system_upgrade.go
  pkg/upgrade/tenant_upgrade.go
  pkg/upgrade/upgrades/upgrades.go
Labels: backport-23.1.x, backport-23.1.0

#101338 build: bump release version
  pkg/build/version.txt
Labels: C-enhancement, A-release, T-release

#101187 changefeedccl: Cleanup row handling with CDC Queries
  pkg/ccl/changefeedccl/cdceval/cdc_prev.go
  pkg/ccl/changefeedccl/cdceval/expr_eval.go
  pkg/ccl/changefeedccl/cdceval/expr_eval_test.go
  pkg/ccl/changefeedccl/cdceval/functions_test.go
  pkg/ccl/changefeedccl/cdceval/plan_test.go
  pkg/ccl/changefeedccl/cdcevent/event.go
  pkg/ccl/changefeedccl/cdcevent/version_cache.go
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/encoder.go
  pkg/ccl/changefeedccl/encoder_json.go
  pkg/ccl/changefeedccl/encoder_test.go
  pkg/ccl/changefeedccl/event_processing.go
  pkg/ccl/changefeedccl/sink_cloudstorage_test.go
  pkg/ccl/changefeedccl/sink_webhook_test.go
  pkg/ccl/changefeedccl/testfeed_test.go
Labels: backport-23.1.x, backport-23.1.0

#100649 kvcoord: Rework error propagation in mux rangefeed
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvserver/client_replica_circuit_breaker_test.go
  pkg/kv/kvserver/rangefeed/registry.go
  pkg/kv/kvserver/replica_rangefeed.go
  pkg/server/node.go
Labels: backport-23.1.x, backport-23.1.0

#101398 release: fix secret reference for GAR
  build/teamcity/internal/release/process/build-cockroach-release.sh
Labels: C-bug, A-release, T-release, backport-23.1.x, backport-23.1.0

#101352 sql: fix udfs with $$ in body
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/schemachanger/scbuild/ast_annotator.go
  pkg/sql/sem/tree/format.go
  pkg/sql/sem/tree/pretty.go
  pkg/sql/sem/tree/udf.go
Labels: backport-23.1.x, backport-23.1.0

#101454 sql/sessiondata: fixes for parsing of search_path
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/schema
  pkg/sql/pgwire/conn_test.go
  pkg/sql/sessiondata/BUILD.bazel
  pkg/sql/sessiondata/parse_search_path.go
  pkg/sql/sessiondata/search_path.go
  pkg/sql/sessiondata/search_path_test.go
  pkg/sql/tests/BUILD.bazel
  pkg/sql/tests/search_path_test.go
  pkg/sql/vars.go
  pkg/util/randutil/rand.go
Labels: backport-23.1.x, backport-23.1.0

#101442 pkg/roachtest: increase multi-region restore timeout
  pkg/cmd/roachtest/tests/restore.go
Labels: backport-23.1.x

#101437 base: reduce `RaftMaxInflightBytes` to 32 MB
  pkg/base/config.go
  pkg/base/config_test.go
  pkg/base/testdata/raft_config
Labels: backport-23.1.x, backport-23.1.0

#101447 c2c: randomize node shutdown timing in roachtests
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: T-disaster-recovery

#100785 kvserver: skip replicate queue tests under metamorphic builds
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/testutils/skip/skip.go
Labels: backport-23.1.x

#101567 roachtest: update npgsql and pgjdbc blocklists
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
  pkg/cmd/roachtest/tests/pgjdbc_blocklist.go
Labels: backport-23.1.x, backport-23.1.0

#101571 pgwire: fix decoding array placeholder arguments
  pkg/sql/pgwire/pgwirebase/BUILD.bazel
  pkg/sql/pgwire/pgwirebase/encoding.go
  pkg/sql/pgwire/testdata/pgtest/array
  pkg/sql/pgwire/testdata/pgtest/json_array
  pkg/sql/pgwire/types_test.go
Labels: backport-22.2.x, backport-23.1.x

#101109 kvserver: re-enable `kv.expiration_leases_only.enabled` test metamorphism
  pkg/kv/kvserver/client_raft_test.go
  pkg/kv/kvserver/replica_lease_renewal_test.go
  pkg/kv/kvserver/replica_range_lease.go
  pkg/kv/kvserver/replica_test.go
Labels: backport-23.1.x

#93787 liveness: clarify `IncrementEpoch` race error and log as INFO
  pkg/kv/kvserver/liveness/liveness.go
  pkg/kv/kvserver/replica_range_lease.go
Labels: backport-22.2.x, backport-23.1.x

#100466 kvserver: fix `TestNodeLivenessRetryAmbiguousResultOnCreateError` data race
  pkg/kv/kvserver/node_liveness_test.go
Labels: backport-22.1.x, backport-22.2.x, backport-23.1.x

#101177 pgwire: update description of server.max_connections_per_gateway
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/pgwire/server.go
Labels: backport-22.1.x, backport-22.2.x, backport-23.1.x

#100881 opt: hoist uncorrelated equality subqueries
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/subquery
  pkg/sql/opt/exec/execbuilder/testdata/tpch_vec
  pkg/sql/opt/exec/execbuilder/testdata/udf
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/testdata/stats_quality/tpch/q15
  pkg/sql/opt/norm/decorrelate_funcs.go
  pkg/sql/opt/norm/testdata/rules/decorrelate
  pkg/sql/opt/norm/testdata/rules/inline
  pkg/sql/opt/norm/testdata/rules/join
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/testdata/external/tpch
  pkg/sql/opt/xform/testdata/external/tpch-no-stats
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.0

#101687 rowcontainer: fix flaky test
  pkg/sql/rowcontainer/BUILD.bazel
  pkg/sql/rowcontainer/disk_row_container_test.go
  pkg/sql/rowcontainer/row_container_test.go
Labels: backport-23.1.x

#101581 sql: do not propagate incorrect misplanned ranges metadata
  pkg/sql/colfetcher/colbatch_scan.go
  pkg/sql/distsql_physical_planner.go
  pkg/sql/execinfra/readerbase.go
  pkg/sql/execinfrapb/processors_sql.proto
  pkg/sql/logictest/testdata/logic_test/distsql_numtables
  pkg/sql/rowexec/tablereader.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.0

#101499 kvserver: fix rebalancing.(write|read)bytes desc
  pkg/kv/kvserver/metrics.go
Labels: backport-23.1.x, backport-23.1.0

#101574 ui: improvements on sort warning
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.tsx
Labels: backport-23.1.x, backport-23.1.0

#101682 restore: skip_localities_check no longer works
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/backupccl/testdata/backup-restore/multiregion
  pkg/jobs/jobspb/jobs.proto
  pkg/sql/alter_database.go
  pkg/sql/database_region_change_finalizer.go
  pkg/sql/region_util.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.0

#101787 sqlproxy: fix per-connection memory leaks
  pkg/ccl/sqlproxyccl/tenant/directory_cache.go
Labels: backport-23.1.x, backport-23.1.0

#101749 release-23.1: update c2c roachtests
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/jobs.go
  pkg/cmd/roachtest/tests/registry.go
Labels: T-disaster-recovery

#101800 copy: fix copy partial index handling
  pkg/sql/copy/copy_test.go
  pkg/sql/copy/testdata/copy_from
  pkg/sql/row/putter.go
Labels: backport-23.1.x, backport-23.1.0

#101477 sql: fix internal executor when it encounters a retry error
  pkg/ccl/changefeedccl/changefeed_dist.go
  pkg/sql/conn_executor_internal_test.go
  pkg/sql/conn_io.go
  pkg/sql/distsql_running.go
  pkg/sql/internal.go
  pkg/sql/internal_test.go
  pkg/sql/pgwire/command_result.go
  pkg/sql/recursive_cte.go
  pkg/sql/routine.go
  pkg/sql/sessiondata/internal.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
Labels: backport-23.1.x, backport-23.1.0

#101851 opt: fixed issue with incorrectly building data sources with an alias
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/testdata/subquery
Labels: backport-22.2.x, backport-23.1.x

#101828 sql: fix transaction_contention_events for RangeDescriptor
  pkg/sql/BUILD.bazel
  pkg/sql/crdb_internal.go
  pkg/sql/crdb_internal_test.go
Labels: backport-23.1.x, backport-23.1.0

#101865 kv: return on quiesce in rangeFeedSlowClosedTimestampNudge task
  pkg/kv/kvserver/replica_rangefeed.go
Labels: backport-23.1.x, backport-23.1.0

#99108 server: deflake test hot ranges response
  pkg/kv/kvserver/allocator/range_usage_info.go
  pkg/kv/kvserver/replicate_queue.go
  pkg/kv/kvserver/store.go
  pkg/server/status_test.go
Labels: O-community, X-blathers-triaged

#101833 skip c2c/BulkOps roachtest
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: T-disaster-recovery

#101949 metric: fix race in manual histogram
  pkg/util/metric/metric.go
Labels: backport-23.1.x, backport-23.1.0

#101997 release-23.1.0: build,release: provide way to inject build tag override, use in MAPB
  build/bazelutil/stamp.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts.sh
  pkg/build/BUILD.bazel
  pkg/build/info.go
  pkg/cmd/publish-provisional-artifacts/main.go
  pkg/cmd/publish-provisional-artifacts/main_test.go
  pkg/release/build.go
Labels: C-enhancement, T-dev-inf, A-ci

#101998 release-23.1: build,release: provide way to inject build tag override, use in MAPB
  build/bazelutil/stamp.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts.sh
  pkg/build/BUILD.bazel
  pkg/build/info.go
  pkg/cmd/publish-provisional-artifacts/main.go
  pkg/cmd/publish-provisional-artifacts/main_test.go
  pkg/release/build.go
Labels: C-enhancement, T-dev-inf, A-ci

#101975 tree: fix type checking of IN subquery expressions
  pkg/sql/logictest/testdata/logic_test/select
  pkg/sql/logictest/testdata/logic_test/subquery
  pkg/sql/opt/exec/execbuilder/testdata/subquery
  pkg/sql/opt/optbuilder/subquery.go
  pkg/sql/opt/optbuilder/testdata/subquery
  pkg/sql/sem/tree/type_check.go
Labels: backport-23.1.x

#102038 roachtest: some more logging for costfuzz and unoptimized query oracle
  pkg/cmd/roachtest/tests/query_comparison_util.go
Labels: backport-23.1.x

#101971 colexec: fix hash table memory accounting for hash aggregator
  pkg/sql/colexec/colexechash/hashtable.go
  pkg/sql/colexec/colexecjoin/hashjoiner.go
  pkg/sql/colexec/hash_aggregator.go
  pkg/sql/colexec/unordered_distinct.go
Labels: backport-23.1.x

#98162 sql: fix record-returning udfs when used as data source
  pkg/sql/logictest/testdata/logic_test/enums
  pkg/sql/logictest/testdata/logic_test/udf_record
  pkg/sql/logictest/testdata/logic_test/udf_setof
  pkg/sql/opt/exec/execbuilder/scalar.go
  pkg/sql/opt/norm/inline_funcs.go
  pkg/sql/opt/norm/testdata/rules/inline
  pkg/sql/opt/norm/testdata/rules/udf
  pkg/sql/opt/ops/scalar.opt
  pkg/sql/opt/optbuilder/builder.go
  pkg/sql/opt/optbuilder/scalar.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/srfs.go
  pkg/sql/opt/optbuilder/testdata/udf
  pkg/sql/opt/optbuilder/util.go
  pkg/sql/routine.go
  pkg/sql/rowexec/project_set.go
  pkg/sql/sem/builtins/generator_builtins.go
  pkg/sql/sem/eval/generators.go
  pkg/sql/sem/tree/expr.go
  pkg/sql/sem/tree/routine.go
  pkg/sql/sem/tree/type_check.go
Labels: backport-23.1.x, backport-23.1.0

#102042 changefeedccl: make batch_reduction_retry_enabled setting public
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/changefeedccl/changefeedbase/settings.go
Labels: backport-22.2.x, backport-23.1.x

#102103 xform: ensure a DistributeOp is built for uniq checks with enforce_home_region
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/physical_props.go
  pkg/sql/opt/xform/testdata/rules/scan
Labels: backport-23.1.x

#99841 changefeed: cancel jobs replicated from another cluster
  pkg/ccl/changefeedccl/changefeed_stmt.go
Labels: backport-23.1.x

#102165 crdb_internal: finer-grained priv for viewing {cluster,node}_transactions
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
Labels: backport-22.2.x, backport-23.1.x

#102139 kvserver: validate returned load split keys
  pkg/kv/kvserver/replica_split_load.go
  pkg/kv/kvserver/replica_split_load_test.go
  pkg/kv/kvserver/split_queue.go
Labels: backport-23.1.x

#102179 backupccl: pretend manifest files spans actually end at EndKey.Next on restore
  pkg/ccl/backupccl/generative_split_and_scatter_processor_test.go
  pkg/ccl/backupccl/restore_span_covering.go
  pkg/ccl/backupccl/restore_span_covering_test.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.0

#102094 kvcoord: Fix error handling and retries in mux rangefeed client
  pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed_mock_test.go
  pkg/kv/kvserver/client_raft_test.go
Labels: backport-23.1.x, backport-23.1.0

#102192 sqlstats: only include local region in statement_statistics
  pkg/ccl/multiregionccl/testdata/secondary_region
  pkg/sql/executor_statement_metrics.go
Labels: backport-23.1.x, backport-23.1.0

#101340 ui: remove some functions generated by protobufjs
  pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsPage.fixture.tsx
  pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsPage.spec.tsx
  pkg/ui/workspaces/cluster-ui/src/recentExecutions/recentStatementUtils.spec.ts
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/store/indexStats/indexStats.sagas.spec.ts
  pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.sagas.spec.ts
  pkg/ui/workspaces/cluster-ui/src/tracez/snapshot/snapshotPage.spec.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.fixture.ts
  pkg/ui/workspaces/db-console/src/js/defs.bzl
  pkg/ui/workspaces/db-console/src/redux/locations.spec.ts
  pkg/ui/workspaces/db-console/src/util/api.spec.ts
  pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/linegraph.spec.tsx
  pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx
  pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/hotranges/index.tsx
  pkg/ui/workspaces/db-console/src/views/statements/statements.spec.tsx
Labels: backport-22.1.x, backport-22.2.x, backport-23.1.x

#102279 sql: set system db survival as max survival goal
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_survial_goal
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/generated_test.go
  pkg/sql/alter_database.go
  pkg/sql/descriptor.go
Labels: backport-23.1.x

#102336 opt: fix internal error when planning correlated ANY subqueries
  pkg/sql/opt/exec/execbuilder/scalar.go
  pkg/sql/opt/exec/execbuilder/testdata/subquery
Labels: backport-23.1.x

#102346 sql: add bounds checking to resolved function definition functions
  pkg/sql/sem/tree/function_definition.go
Labels: backport-22.2.x, backport-23.1.x

#102370 pkg/util/tracing: don't tag child spans when trimming spans recursively
  pkg/util/tracing/crdbspan.go
  pkg/util/tracing/span_test.go
Labels: backport-23.1.x, backport-23.1.0

#100434 kvserver: grow goroutine stack for `requestLease`
  pkg/kv/kvserver/BUILD.bazel
  pkg/kv/kvserver/replica_range_lease.go
Labels: backport-23.1.x

#102291 split: add additional lb split tests and fix decider weight
  pkg/cmd/roachtest/tests/split.go
  pkg/kv/kvserver/split/BUILD.bazel
  pkg/kv/kvserver/split/decider.go
  pkg/kv/kvserver/split/load_based_splitter_test.go
  pkg/kv/kvserver/split/testdata/cpu_decider_cartesian
  pkg/kv/kvserver/split/testdata/unweighted_finder
  pkg/kv/kvserver/split/testdata/weighted_finder
  pkg/kv/kvserver/split/weighted_finder.go
  pkg/kv/kvserver/split/weighted_finder_test.go
Labels: backport-23.1.x

#102483 sql: use bytes-based limiting in UPSERT
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/sql/logictest/testdata/logic_test/upsert_non_metamorphic
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-mixed-22.2-23.1/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/upsert.go
Labels: backport-22.2.x, backport-23.1.x

#102187 sql/tests: deflake TestErrorDuringExtendedProtocolCommit (again)
  pkg/sql/tests/autocommit_extended_protocol_test.go
Labels: backport-22.2.x, backport-23.1.x

#102413 backupccl: don't restore sql_instances, sqlliveness or lease rows
  pkg/ccl/backupccl/key_rewriter.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go
  pkg/storage/fingerprint_writer.go
Labels: backport-22.1.x, backport-23.1.x

#102508 ccl/sqlproxyccl: export balancer metrics
  pkg/ccl/sqlproxyccl/balancer/balancer.go
  pkg/ccl/sqlproxyccl/balancer/balancer_test.go
  pkg/ccl/sqlproxyccl/balancer/metrics.go
  pkg/ccl/sqlproxyccl/server_test.go
Labels: backport-23.1.x, backport-23.1.0

#102405 opt: check privileges after data sources in memo staleness check
  pkg/sql/logictest/testdata/logic_test/schema
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/metadata.go
Labels: backport-22.1.x, backport-22.2.x, backport-23.1.x, backport-23.1.0

#102623 changefeedccl: Terminate retries when loosing claim
  pkg/ccl/changefeedccl/changefeed_stmt.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.1.0

#102594 sql/stats: collect automatic table statistics on the system.jobs table
  pkg/jobs/utils.go
  pkg/sql/stats/automatic_stats.go
  pkg/sql/stats/automatic_stats_test.go
Labels: backport-23.1.x

#102593 c2c: skip and deflake a few unit tests
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/ccl/streamingccl/streamproducer/replication_stream_test.go
  pkg/util/leaktest/leaktest.go
Labels: T-disaster-recovery

#102492 roachtest: remove the FUSE-variants of the disk-stall roachtest
  pkg/cmd/roachtest/tests/disk_stall.go
Labels: backport-22.2.x, backport-23.1.x

#100433 batcheval: don't declare latches for `RequestLease`
  pkg/kv/kvserver/batcheval/cmd_lease_request.go
  pkg/kv/kvserver/batcheval/declare_test.go
Labels: backport-23.1.x

#102421 sql: allow COPY ... TO in a prepared statement
  pkg/acceptance/testdata/node/base-test.js
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_prepare.go
  pkg/sql/opaque.go
  pkg/sql/pgwire/testdata/pgtest/copy
  pkg/sql/plan_opt.go
  pkg/sql/sem/tree/walk.go
Labels: backport-23.1.x

#100435 kvserver: avoid unnecessary tracing span in `requestLeaseAsync()`
  pkg/kv/kvserver/replica_range_lease.go
Labels: backport-23.1.x
