Repository cockroachdb/cockroach, pull requests merged in 2023-12, with the labels that each got.

#112971 geo/geomfn: implement ST_TileEnvelope({int4,int4,int4,geometry})
  docs/generated/sql/functions.md
  pkg/geo/geomfn/BUILD.bazel
  pkg/geo/geomfn/tile_envelope.go
  pkg/geo/geomfn/tile_envelope_test.go
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community

#115383 sql: add logging to GetAllInstancesByLocality
  pkg/sql/distsql_physical_planner.go
Labels: backport-23.1.x, backport-23.2.x

#115156 plpgsql: correctly assign to single record-type variable
  pkg/sql/logictest/testdata/logic_test/procedure_plpgsql
  pkg/sql/opt/optbuilder/plpgsql.go
Labels: backport-23.2.x

#115246 base: include Spec in TempStorageConfig's created in tests
  pkg/base/config.go
  pkg/base/test_server_args.go
  pkg/server/server_controller_new_server.go
  pkg/server/testserver.go
  pkg/sql/colflow/draining_test.go
Labels: backport-23.2.x

#115408 server: remove /debug/tickle
  pkg/server/debug/server.go
  pkg/server/server.go
  pkg/server/tenant.go
Labels: backport-23.2.x

#108688 concurrency: remove LocksWithReservation counter
  pkg/kv/kvserver/concurrency/metrics.go
  pkg/kv/kvserver/concurrency/testdata/lock_table/basic
  pkg/kv/kvserver/concurrency/testdata/lock_table/update
Labels: O-community

#115395 ci: explicitly set author for predecessor update action
  .github/workflows/update_releases.yaml
Labels: C-bug, A-release, T-release

#115350 release-23.1: roachprod: fix dns create records
  pkg/roachprod/vm/gce/dns.go
Labels: backport

#115061 roachtest: add `UploadCockroach` and `UploadWorkload` APIs
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/tests/admission_control_database_drop.go
  pkg/cmd/roachtest/tests/admission_control_index_backfill.go
  pkg/cmd/roachtest/tests/backup_fixtures.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/decommission_self.go
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_decl_schemachange_compat.go
  pkg/cmd/roachtest/tests/mixed_version_decommission.go
  pkg/cmd/roachtest/tests/multitenant_upgrade.go
  pkg/cmd/roachtest/tests/rebalance_load.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: backport-23.1.x, backport-23.2.x

#114362 release-23.1: released CockroachDB version 23.1.12. Next version: 23.1.13
  pkg/build/version.txt
Labels: backport

#115286 roachtest: no longer show other errors if a test times out
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
Labels: backport-23.1.x, backport-23.2.x

#115263 kv: don't modify `kv.closed_timestamp.propagation_slack` in unit tests
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go
Labels: backport-23.1.x, backport-23.2.x

#115473 storage: disable multi-level compactions
  pkg/storage/pebble.go
Labels: backport-23.2.x

#115044 ui: keep timewindow with fixed range after Now button click
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScaleDropdown.tsx
Labels: O-community, backport-23.1.x, backport-23.2.x

#115482 sql/schemachanger: create index should fallback for materialized views
  pkg/sql/logictest/testdata/logic_test/create_index
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
Labels: backport-23.1.x, backport-23.2.x

#115476 ci: add release justification to predecessor updates
  .github/workflows/update_releases.yaml
Labels: C-enhancement, A-release, T-release

#115507 roachtest: enable more TPCC benchmarks in roachperf
  pkg/cmd/roachtest/tests/tpcc.go
Labels: branch-release-23.1, branch-release-23.2

#115469 streamingccl: add creating splits job status
  pkg/ccl/streamingccl/streamingest/stream_ingestion_dist.go
  pkg/jobs/jobspb/wrap.go
Labels: backport-23.2.x

#115459 streamingccl: double the frequency we check for lagging nodes
  pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go
Labels: T-disaster-recovery

#115569 kvstreamer: fix cross-range ScanRequests with SingleRowLookup hint
  pkg/kv/kvclient/kvstreamer/requests_provider.go
  pkg/kv/kvclient/kvstreamer/results_buffer.go
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/kv/kvclient/kvstreamer/streamer_accounting_test.go
  pkg/sql/logictest/testdata/logic_test/lookup_join
Labels: backport-23.1.x, backport-23.2.x

#115572 explain: add missing space between equality column names
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_foreign_key_lookup_join
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_query_behavior
  pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/sql/opt/exec/execbuilder/testdata/expression_index
  pkg/sql/opt/exec/execbuilder/testdata/fk
  pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index
  pkg/sql/opt/exec/execbuilder/testdata/inverted_join_geospatial
  pkg/sql/opt/exec/execbuilder/testdata/inverted_join_geospatial_dist
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join_spans
  pkg/sql/opt/exec/execbuilder/testdata/observability
  pkg/sql/opt/exec/execbuilder/testdata/unique
  pkg/sql/opt/exec/execbuilder/testdata/upsert
  pkg/sql/opt/exec/explain/emit.go
  pkg/sql/opt/exec/explain/testdata/gists
Labels: backport-23.2.x

#114961 concurrency: add tests for replicated shared and exclusive locks
  pkg/kv/kvserver/concurrency/concurrency_manager_test.go
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/replicated
Labels: backport-23.2.x

#115241 server: deflake TestHealthCheck
  pkg/server/server_test.go
Labels: backport-23.2.x

#115550 release-23.1: roachtest: enable more TPCC benchmarks in roachperf
  pkg/cmd/roachtest/tests/tpcc.go
Labels: backport

#115555 release-23.2: roachtest: enable more TPCC benchmarks in roachperf
  pkg/cmd/roachtest/tests/tpcc.go
Labels: backport

#115603 release-23.1: Revert "s3: disable content pre-upload checksums"
  pkg/cloud/amazon/s3_storage.go
Labels: backport

#115389 release-23.1: roachtest: stop using ClusterSpec.Cloud in test code
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/spec/machine_type.go
  pkg/cmd/roachtest/spec/option.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/test_registry_test.go
  pkg/cmd/roachtest/tests/awsdms.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/connection_latency.go
  pkg/cmd/roachtest/tests/copy.go
  pkg/cmd/roachtest/tests/decommissionbench.go
  pkg/cmd/roachtest/tests/disk_stall.go
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/import.go
  pkg/cmd/roachtest/tests/import_cancellation.go
  pkg/cmd/roachtest/tests/indexes.go
  pkg/cmd/roachtest/tests/kv.go
  pkg/cmd/roachtest/tests/ledger.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_cdc.go
  pkg/cmd/roachtest/tests/mixed_version_decl_schemachange_compat.go
  pkg/cmd/roachtest/tests/rebalance_load.go
  pkg/cmd/roachtest/tests/restore.go
  pkg/cmd/roachtest/tests/roachmart.go
  pkg/cmd/roachtest/tests/schemachange.go
  pkg/cmd/roachtest/tests/schemachange_random_load.go
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/cmd/roachtest/tests/tpc_utils.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/tpcdsvec.go
  pkg/cmd/roachtest/tests/ycsb.go
Labels: backport

#115390 release-23.1: roachtest: add --suite and --owner flags, improve test filtering
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/main_test.go
  pkg/cmd/roachtest/registry/BUILD.bazel
  pkg/cmd/roachtest/registry/filter.go
  pkg/cmd/roachtest/registry/filter_test.go
  pkg/cmd/roachtest/registry/owners.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/registry/testdata/filter/describe
  pkg/cmd/roachtest/registry/testdata/filter/errors
  pkg/cmd/roachtest/registry/testdata/filter/filter
  pkg/cmd/roachtest/registry/testdata/filter/matches
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/test_filter.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/test_registry_test.go
  pkg/cmd/roachtest/test_test.go
Labels: backport

#115594 release-23.2: plpgsql: coerce types for PLpgSQL expressions
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/sql/logictest/testdata/logic_test/plpgsql_record
  pkg/sql/logictest/testdata/logic_test/procedure_plpgsql
  pkg/sql/logictest/testdata/logic_test/udf_plpgsql
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/opt/optbuilder/plpgsql.go
  pkg/sql/opt/optbuilder/routine.go
  pkg/sql/opt/optbuilder/testdata/procedure_plpgsql
  pkg/sql/opt/optbuilder/testdata/udf_plpgsql
  pkg/sql/schemachanger/comparator_generated_test.go
  pkg/sql/sem/plpgsqltree/BUILD.bazel
  pkg/sql/sem/plpgsqltree/visitor.go
Labels: backport

#115644 release-23.2: go.mod: bump Pebble to 52e1a820246d
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#114401 execbuilder: elide redundant locking lookup join in some simple cases
  pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/testdata/select_for_update
  pkg/sql/opt/exec/execbuilder/testdata/select_for_update_read_committed
  pkg/sql/opt/testutils/opttester/BUILD.bazel
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/testdata/external/tpcc-read-committed
Labels: backport-23.2.x

#115685 builtins: skip TestSerialNormalizationWithUniqueUnorderedID under deadlock
  pkg/sql/sem/builtins/builtins_test.go
Labels: backport-23.2.x

#114840 server: delay job scheduler startup
  pkg/server/external_storage_builder.go
  pkg/server/server.go
  pkg/server/server_sql.go
  pkg/server/server_test.go
  pkg/server/tenant.go
Labels: backport-23.1.x, backport-23.2.x

#115581 release-23.1: kvstreamer: fix cross-range ScanRequests with SingleRowLookup hint
  pkg/kv/kvclient/kvstreamer/requests_provider.go
  pkg/kv/kvclient/kvstreamer/results_buffer.go
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/kv/kvclient/kvstreamer/streamer_test.go
  pkg/sql/logictest/testdata/logic_test/lookup_join
Labels: backport

#115596 release-23.1: sql/schemachanger: create index should fallback for materialized views
  pkg/sql/logictest/testdata/logic_test/create_index
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
Labels: backport

#115704 build: update go to 1.21.5
  .bazelrc
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/bootstrap/bootstrap-debian.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
Labels: C-enhancement, A-build-system, T-dev-inf

#115718 release-23.1: roachtest: allocate new cluster when c.Extend fails
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/test_runner.go
Labels: backport

#115724 release-23.1: generate-logictest: fix order of lines in generated BUILD.bazel
  pkg/cmd/generate-logictest/templates.go
Labels: backport

#115273 builtins: support bit_count for bytea and varbit
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/eval/testdata/eval/builtins
Labels: O-community

#115285 server: load stores in parallel during node startup
  pkg/server/node.go
  pkg/server/node_test.go
Labels: O-community, X-blathers-triaged

#115683 release-23.1: roachprod: update tenant certs distribution
  pkg/roachprod/install/cluster_synced.go
Labels: backport

#115735 workload/schemachange: `Release` connection only when acquired
  pkg/workload/schemachange/schemachange.go
Labels: backport-23.2.x

#115762 release-23.2: roachprod: add jaeger-[start|stop|url] command
  pkg/cmd/roachprod/flags.go
  pkg/cmd/roachprod/main.go
  pkg/roachprod/install/install.go
  pkg/roachprod/roachprod.go
Labels: backport

#115388 release-23.2: sql: prevent gateway from always being picked as the default
  pkg/sql/distsql_physical_planner.go
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/exec_util.go
  pkg/sql/execinfra/server_config.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/sessiondatapb/session_data.proto
  pkg/sql/vars.go
Labels: backport

#115768 release-23.2: workload/schemachange: `Release` connection only when acquired
  pkg/workload/schemachange/schemachange.go
Labels: backport

#115798 release-23.1: roachtest: lower default timeout
  pkg/cmd/roachtest/tests/activerecord.go
  pkg/cmd/roachtest/tests/multitenant_upgrade.go
  pkg/cmd/roachtest/tests/ruby_pg.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/version.go
Labels: backport

#115803 changefeedccl: make lagging ranges settings public
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/changefeedccl/changefeedbase/settings.go
Labels: backport-22.2.x

#115826 plpgsql: add optimization barriers for volatile expressions
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/memo/logical_props_builder.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/ops/relational.opt
  pkg/sql/opt/optbuilder/plpgsql.go
  pkg/sql/opt/optbuilder/testdata/procedure_plpgsql
  pkg/sql/opt/optbuilder/testdata/udf_plpgsql
Labels: backport-23.2.x, backport-23.2.0-rc

#115817 sql: omit virtual tables from stmt bundles
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/metadata.go
Labels: backport-23.1.x, backport-23.2.x, backport-23.2.0-rc

#115753 jobs: avoid crdb_internal.system_jobs in test utils
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/testfeed_test.go
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/ccl/streamingccl/replicationutils/BUILD.bazel
  pkg/ccl/streamingccl/replicationutils/utils.go
  pkg/ccl/streamingccl/streamingest/replication_execution_details_test.go
  pkg/testutils/jobutils/jobs_verification.go
Labels: backport-23.2.x

#115760 kvserver: log progress during store initialization
  pkg/kv/kvserver/kvstorage/init.go
  pkg/kv/kvserver/store.go
  pkg/server/node.go
Labels: backport-23.1.x, backport-23.2.x

#115781 release-23.1: roachtest: WipeForReuse clears DNS entries
  pkg/cmd/roachprod/main.go
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster/cluster_interface.go
  pkg/roachprod/roachprod.go
Labels: backport

#115797 kvtenant: server shutdown deadlock from TenantSettingsSubscription race
  pkg/kv/kvclient/kvtenant/setting_overrides.go
Labels: T-multitenant, backport-23.2.x, backport-23.2.0-rc

#115740 release-23.2: go.mod: bump Pebble to 50519c512bcc
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport-23.2.0-rc

#115795 optbuilder: disallow locking tables on null-extended side of outer join
  pkg/sql/opt/optbuilder/join.go
  pkg/sql/opt/optbuilder/locking.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/testdata/select_for_update
Labels: backport-23.2.x, backport-23.2.0-rc

#115791 release-22.2: build: backport Go fix to 1.19
  .bazelrc
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/teamcity/internal/release/build-and-publish-patched-go/6446af9.diff
  build/teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
Labels: C-enhancement, A-build-system, T-dev-inf, backport

#115787 release-23.1: build: backport Go fix to 1.19
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/teamcity/internal/release/build-and-publish-patched-go/6446af9.diff
  build/teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
Labels: C-enhancement, A-build-system, T-dev-inf

#115849 release-23.2.0-rc: release-23.2: enginepb: add OmitInRangefeeds field to MVCCValueHeader
  pkg/storage/enginepb/mvcc3.proto
  pkg/storage/enginepb/mvcc3_test.go
  pkg/storage/enginepb/mvcc3_valueheader.go
Labels: backport

#115802 release-23.2.0-rc: ttljob: introduce sql.ttl.default_select_rate_limit cluster setting, ttl_select_rate_limit storage param
  docs/RFCS/20220120_row_level_ttl.md
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/catalog/catpb/catalog.proto
  pkg/sql/catalog/tabledesc/structured.go
  pkg/sql/catalog/tabledesc/ttl.go
  pkg/sql/execinfrapb/processors_ttl.proto
  pkg/sql/logictest/testdata/logic_test/row_level_ttl
  pkg/sql/storageparam/tablestorageparam/table_storage_param.go
  pkg/sql/ttl/ttlbase/ttl_helpers.go
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
  pkg/sql/ttl/ttljob/ttljob_query_builder.go
  pkg/sql/ttl/ttljob/ttljob_query_builder_test.go
  pkg/sql/ttl/ttljob/ttljob_test.go
Labels: backport

#115778 release-23.2.0-rc: kv,admission: only log empty admission warning for non-release builds
  pkg/kv/kvserver/intentresolver/BUILD.bazel
  pkg/kv/kvserver/intentresolver/intent_resolver.go
Labels: backport

#115896 release-23.2: advance version.txt to v23.2.1
  pkg/build/version.txt
Labels: backport

#115848 sql: allow dropping routines with UDT-typed parameters
  pkg/sql/logictest/testdata/logic_test/drop_function
  pkg/sql/logictest/testdata/logic_test/drop_procedure
  pkg/sql/sem/tree/overload.go
Labels: backport-23.1.x, backport-23.2.x, backport-23.2.0-rc

#115468 sql: make CALL statements explainable
  docs/generated/sql/bnf/explainable_stmt.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/ccl/logictestccl/testdata/logic_test/explain_call_plpgsql
  pkg/ccl/logictestccl/tests/local/BUILD.bazel
  pkg/ccl/logictestccl/tests/local/generated_test.go
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
  pkg/sql/logictest/testdata/logic_test/prepare
  pkg/sql/opt/exec/execbuilder/testdata/call
  pkg/sql/opt/exec/execbuilder/tests/local/generated_test.go
  pkg/sql/opt/exec/explain/emit.go
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/optbuilder/plpgsql.go
  pkg/sql/opt/optbuilder/routine.go
  pkg/sql/opt/optbuilder/testdata/procedure
  pkg/sql/opt/optbuilder/testdata/procedure_plpgsql
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/explain
  pkg/sql/sem/tree/overload.go
Labels: backport-23.2.x, backport-23.2.0-rc

#115782 release-23.2: admission: include more work queue info in tracing and errors
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
  pkg/util/admission/admission.go
  pkg/util/admission/admissionpb/admission_stats.proto
  pkg/util/admission/grant_coordinator.go
  pkg/util/admission/work_queue.go
Labels: backport

#115784 release-23.2.0-rc: admission: include more work queue info in tracing and errors
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
  pkg/util/admission/admission.go
  pkg/util/admission/admissionpb/admission_stats.proto
  pkg/util/admission/grant_coordinator.go
  pkg/util/admission/work_queue.go
Labels: backport

#116004 logictest: add regression test for UDFs with composite types
  pkg/sql/logictest/testdata/logic_test/udf
Labels: backport-23.1.x, backport-23.2.x

#115766 release-23.2: kv: extend the KV API to allow setting the OmitInRangefeeds txn attribute
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go
  pkg/kv/admission_test.go
  pkg/kv/client_test.go
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go
  pkg/kv/kvpb/batch_test.go
  pkg/kv/kvpb/data.go
  pkg/kv/kvpb/data_test.go
  pkg/kv/kvpb/errors_test.go
  pkg/kv/kvpb/string_test.go
  pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go
  pkg/kv/kvserver/batcheval/cmd_delete_range_test.go
  pkg/kv/kvserver/batcheval/cmd_end_transaction_test.go
  pkg/kv/kvserver/batcheval/cmd_query_intent_test.go
  pkg/kv/kvserver/batcheval/cmd_query_resolved_timestamp_test.go
  pkg/kv/kvserver/batcheval/cmd_recover_txn_test.go
  pkg/kv/kvserver/batcheval/cmd_resolve_intent_test.go
  pkg/kv/kvserver/batcheval/cmd_revert_range_test.go
  pkg/kv/kvserver/batcheval/intent_test.go
  pkg/kv/kvserver/batcheval/transaction_test.go
  pkg/kv/kvserver/client_merge_test.go
  pkg/kv/kvserver/client_metrics_test.go
  pkg/kv/kvserver/client_raft_test.go
  pkg/kv/kvserver/client_replica_test.go
  pkg/kv/kvserver/client_split_test.go
  pkg/kv/kvserver/closed_timestamp_test.go
  pkg/kv/kvserver/concurrency/lock_table_waiter_test.go
  pkg/kv/kvserver/gc/gc_test.go
  pkg/kv/kvserver/intent_resolver_integration_test.go
  pkg/kv/kvserver/intentresolver/intent_resolver_test.go
  pkg/kv/kvserver/rangefeed/catchup_scan_test.go
  pkg/kv/kvserver/replica_closedts_internal_test.go
  pkg/kv/kvserver/replica_closedts_test.go
  pkg/kv/kvserver/replica_evaluate_test.go
  pkg/kv/kvserver/replica_follower_read_test.go
  pkg/kv/kvserver/replica_learner_test.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/store_test.go
  pkg/kv/kvserver/txnrecovery/manager_test.go
  pkg/kv/kvserver/txnwait/queue_test.go
  pkg/kv/mock_transactional_sender.go
  pkg/kv/sender.go
  pkg/kv/txn.go
  pkg/roachpb/data.go
  pkg/roachpb/data_test.go
  pkg/sql/flowinfra/cluster_test.go
  pkg/sql/sem/eval/timeconv_test.go
  pkg/storage/engine_test.go
  pkg/storage/mvcc_stats_test.go
  pkg/storage/mvcc_test.go
  pkg/storage/pebble_test.go
Labels: backport

#116021 release-23.1: build: update roachtest scripts to use --suite instead of tags
  build/teamcity/cockroach/coverage/roachtest_nightly_gce_impl.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_write_throughput_impl.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_ycsb_impl.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_ycsb_race_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_aws_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh
  build/teamcity/internal/release/process/roachtest-release-qualification.sh
  build/teamcity/util/roachtest_util.sh
  pkg/cmd/roachtest/tests/fixtures.go
Labels: backport

#116124 release-23.1: released CockroachDB version 23.1.13. Next version: 23.1.14
  pkg/build/version.txt
Labels: backport

#115339 release-23.2: build: upgrade to golang v1.21.5
  .bazelrc
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/bootstrap/bootstrap-debian.sh
  build/nodejs.bzl
  build/patches/aspect_bazel_lib.patch
  build/teamcity/internal/release/build-and-publish-patched-go/diff.patch
  build/teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
  build/toolchains/BUILD.bazel
  go.mod
  go.sum
  pkg/acceptance/compose/gss/psql/Dockerfile
  pkg/cmd/dev/doctor.go
  pkg/cmd/roachprod/docker/Dockerfile
  pkg/cmd/roachtest/tests/go_helpers.go
  pkg/col/coldata/batch_test.go
  pkg/col/coldata/bytes.go
  pkg/col/colserde/arrowbatchconverter.go
  pkg/security/certs_rotation_test.go
  pkg/security/certs_test.go
  pkg/sql/colexec/colexecwindow/min_max_queue.go
  pkg/sql/crdb_internal_test.go
  pkg/util/ctxutil/BUILD.bazel
  pkg/util/ctxutil/canceler_1_19.go
  pkg/util/ctxutil/canceler_1_20.go
  pkg/util/ctxutil/canceler_1_21.go
  pkg/util/ctxutil/canceler_1_21_bazel.go
  pkg/util/ctxutil/context.go
  pkg/util/ctxutil/context_test.go
  pkg/util/ctxutil/link_pre_1_21.go
  pkg/util/ctxutil/link_shared.go
  pkg/util/grunning/BUILD.bazel
  pkg/util/grunning/disabled.go
  pkg/util/grunning/disabled_test.go
  pkg/util/grunning/enabled.go
  pkg/util/grunning/enabled_test.go
  pkg/util/grunning/grunning.go
  pkg/util/json/json.go
  pkg/util/json/parser.go
  pkg/util/log/clog_test.go
  pkg/util/log/logcrash/crash_reporting_test.go
  pkg/util/parquet/write_functions.go
Labels: backport

#116098 release-23.2.0-rc: build: upgrade to golang v1.21.5
  .bazelrc
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/bootstrap/bootstrap-debian.sh
  build/nodejs.bzl
  build/patches/aspect_bazel_lib.patch
  build/teamcity/internal/release/build-and-publish-patched-go/diff.patch
  build/teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
  build/toolchains/BUILD.bazel
  go.mod
  go.sum
  pkg/acceptance/compose/gss/psql/Dockerfile
  pkg/cmd/dev/doctor.go
  pkg/cmd/roachprod/docker/Dockerfile
  pkg/cmd/roachtest/tests/go_helpers.go
  pkg/col/coldata/batch_test.go
  pkg/col/coldata/bytes.go
  pkg/col/colserde/arrowbatchconverter.go
  pkg/security/certs_rotation_test.go
  pkg/security/certs_test.go
  pkg/sql/colexec/colexecwindow/min_max_queue.go
  pkg/sql/crdb_internal_test.go
  pkg/util/ctxutil/BUILD.bazel
  pkg/util/ctxutil/canceler_1_19.go
  pkg/util/ctxutil/canceler_1_20.go
  pkg/util/ctxutil/canceler_1_21.go
  pkg/util/ctxutil/canceler_1_21_bazel.go
  pkg/util/ctxutil/context.go
  pkg/util/ctxutil/context_test.go
  pkg/util/ctxutil/link_pre_1_21.go
  pkg/util/ctxutil/link_shared.go
  pkg/util/grunning/BUILD.bazel
  pkg/util/grunning/disabled.go
  pkg/util/grunning/disabled_test.go
  pkg/util/grunning/enabled.go
  pkg/util/grunning/enabled_test.go
  pkg/util/grunning/grunning.go
  pkg/util/json/json.go
  pkg/util/json/parser.go
  pkg/util/log/clog_test.go
  pkg/util/log/logcrash/crash_reporting_test.go
  pkg/util/parquet/write_functions.go
Labels: backport

#115202 release-23.2: fipsccl: Add interfaces to expose FIPS-readiness status
  .github/CODEOWNERS
  WORKSPACE
  pkg/BUILD.bazel
  pkg/ccl/BUILD.bazel
  pkg/ccl/ccl_init.go
  pkg/ccl/cliccl/BUILD.bazel
  pkg/ccl/cliccl/debug.go
  pkg/ccl/cliccl/flags.go
  pkg/ccl/logictestccl/testdata/logic_test/fips_ready
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-disk/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist-disk/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist/generated_test.go
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/generated_test.go
  pkg/ccl/logictestccl/tests/local-mixed-23.1/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-mixed-23.1/generated_test.go
  pkg/ccl/logictestccl/tests/local-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/local/BUILD.bazel
  pkg/ccl/logictestccl/tests/local/generated_test.go
  pkg/ccl/securityccl/fipsccl/BUILD.bazel
  pkg/ccl/securityccl/fipsccl/build_boring.go
  pkg/ccl/securityccl/fipsccl/build_noboring.go
  pkg/ccl/securityccl/fipsccl/fips_linux.go
  pkg/ccl/securityccl/fipsccl/fips_nolinux.go
  pkg/ccl/securityccl/fipsccl/sql.go
  pkg/cli/cli.go
  pkg/sql/sem/builtins/fixed_oids.go
Labels: backport, backport-23.2.0-rc

#116060 release-23.1: spec: move machine type, zone, local ssd defaults out of the TestSpec and the registry
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/main_test.go
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/spec/option.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/test_registry_test.go
  pkg/cmd/roachtest/test_test.go
  pkg/cmd/roachtest/tests/disk_stall.go
  pkg/cmd/roachtest/tests/failover.go
  pkg/cmd/roachtest/tests/restore.go
  pkg/cmd/roachtest/tests/tpcc_test.go
Labels: backport

#116069 release: use explicit branch name for `git cat-file`
  pkg/cmd/release/git.go
  pkg/cmd/release/update_versions.go
Labels: C-bug, A-release, T-release

#116086 release-23.1: kv: don't modify `kv.closed_timestamp.propagation_slack` in unit tests
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go
Labels: backport

#116344 release-23.2: server: fix TestStatusLocalLogs flaky test
  pkg/server/storage_api/BUILD.bazel
  pkg/server/storage_api/logfiles_test.go
Labels: O-community, backport

#116392 release-23.2.0-rc: ccl: dev gen bazel to update BUILD.bazel
  pkg/ccl/logictestccl/tests/local/BUILD.bazel
Labels: backport

#116371 testserver: set defaults on shared-process tenant before starting it
  pkg/server/testserver.go
Labels: backport-23.2.x, backport-23.2.0-rc

#116092 sql: disable write pipelining for implicit txns used by COPY
  pkg/sql/conn_executor.go
  pkg/sql/copy_from.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-23.2.x, backport-23.2.0-rc

#116406 release-23.1: sql: support multiple databases with EXPLAIN ANALYZE (DEBUG)
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
  pkg/sql/opt/exec/execbuilder/testdata/explain_env
Labels: backport

#116289 release-23.2: roachtest: segregate issues for coverage and metamorphic builds and related changes
  pkg/cmd/bazci/githubpost/githubpost.go
  pkg/cmd/bazci/githubpost/githubpost_test.go
  pkg/cmd/internal/issues/formatter_unit.go
  pkg/cmd/internal/issues/issues.go
  pkg/cmd/internal/issues/issues_test.go
  pkg/cmd/internal/issues/render.go
  pkg/cmd/internal/issues/testdata/issues
  pkg/cmd/internal/issues/testdata/post/failure-engflow-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-engflow-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-with-url-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-with-url-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-with-url-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-with-url-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/fatal-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/fatal-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/fatal-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/fatal-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/infrastructure-flake-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/infrastructure-flake-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/infrastructure-flake-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/infrastructure-flake-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/panic-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/panic-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/panic-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/panic-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/rsg-crash-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/rsg-crash-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/rsg-crash-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/rsg-crash-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/with-artifacts-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/with-artifacts-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/with-artifacts-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/with-artifacts-related-issue.txt
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/testdata/help_command_createpost_8.txt
  pkg/cmd/roachtest/testdata/help_command_createpost_9.txt
Labels: backport

#116411 ui: update label "CPU" to "SQL CPU"
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetailsOverviewTab.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx
  pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.tsx
Labels: backport-23.1.x, backport-23.2.x, backport-23.2.0-rc

#116005 status: add network packet dropped and error metrics
  docs/generated/metrics/metrics.html
  pkg/server/status/runtime.go
  pkg/server/status/runtime_test.go
  pkg/ui/workspaces/cluster-ui/src/store/nodes/nodes.fixtures.ts
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx
Labels: O-community, A-webui, X-blathers-triaged

#116312 sql: attempt to unsplit ranges in GC job for secondary tenants
  pkg/sql/gcjob/BUILD.bazel
  pkg/sql/gcjob/gc_job.go
  pkg/sql/gcjob/gc_job_test.go
Labels: backport-23.2.x, backport-23.2.0-rc

#116424 release-23.2.0-rc: sql: add rewrite logic tests for udfs
  pkg/ccl/logictestccl/testdata/logic_test/udf_rewrite
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-disk/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist-disk/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist/generated_test.go
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/generated_test.go
  pkg/ccl/logictestccl/tests/local-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/local/BUILD.bazel
  pkg/ccl/logictestccl/tests/local/generated_test.go
  pkg/sql/create_function.go
  pkg/sql/logictest/testdata/logic_test/udf_rewrite
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/schemachanger/comparator_generated_test.go
  pkg/sql/schemachanger/scbuild/builder_state.go
Labels: backport

#116422 release-23.1: storage: improve mvcc benchmarks under -short
  pkg/storage/bench_pebble_test.go
  pkg/storage/bench_test.go
  pkg/storage/mvcc_key_test.go
  pkg/storage/mvcc_value_test.go
Labels: backport

#116437 roachtestutil: don't reference context after cancellation
  pkg/cmd/roachtest/roachtestutil/validation_check.go
Labels: backport-23.2.x

#116456 release-23.2: go.mod: bump Pebble to 93aaf52c3bec
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport-23.2.0-rc

#116423 release-23.2: sql: add rewrite logic tests for udfs
  pkg/ccl/logictestccl/testdata/logic_test/udf_rewrite
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-disk/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist-disk/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist/generated_test.go
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/generated_test.go
  pkg/ccl/logictestccl/tests/local-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/local/BUILD.bazel
  pkg/ccl/logictestccl/tests/local/generated_test.go
  pkg/sql/create_function.go
  pkg/sql/logictest/testdata/logic_test/udf_rewrite
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/schemachanger/comparator_generated_test.go
  pkg/sql/schemachanger/scbuild/builder_state.go
Labels: backport

#116448 release-23.1: ui: update label "CPU" to "SQL CPU"
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetailsOverviewTab.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx
  pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.tsx
Labels: backport

#116449 release-23.2: ui: update label "CPU" to "SQL CPU"
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetailsOverviewTab.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx
  pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.tsx
Labels: backport

#116450 release-23.2.0-rc: ui: update label "CPU" to "SQL CPU"
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetailsOverviewTab.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetailsOverviewTab.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/util/insightsColumns.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx
  pkg/ui/workspaces/cluster-ui/src/util/sqlActivityConstants.tsx
Labels: backport

#115562 streamingccl: parallelize initial splits
  pkg/ccl/streamingccl/streamingest/stream_ingestion_dist.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_dist_test.go
Labels: T-disaster-recovery, backport-23.2.x

#116489 backupccl: skip TestBackupWorkerFailure
  pkg/ccl/backupccl/backup_test.go
Labels: T-disaster-recovery, backport-23.2.x, backport-23.2.0-rc

#116419 release-23.2: sql: support sequence and udt name rewriting in plpgsql
  pkg/ccl/logictestccl/testdata/logic_test/udf_rewrite
  pkg/sql/BUILD.bazel
  pkg/sql/crdb_internal.go
  pkg/sql/create_function.go
  pkg/sql/create_view.go
  pkg/sql/opt/optbuilder/plpgsql.go
  pkg/sql/plpgsql/parser/testdata/stmt_case
  pkg/sql/sem/plpgsqltree/BUILD.bazel
  pkg/sql/sem/plpgsqltree/exception.go
  pkg/sql/sem/plpgsqltree/statements.go
  pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go
  pkg/sql/sem/plpgsqltree/visitor.go
  pkg/sql/show_create_clauses.go
Labels: backport

#116390 release-23.2: roachtest: deflake restore node shutdown tests
  pkg/cmd/roachtest/tests/restore.go
Labels: backport

#116389 changefeedccl: Flush prior to emitting trailing metadata
  pkg/ccl/changefeedccl/changefeed_processors.go
Labels: backport-23.2.x, backport-23.2.0-rc

#116496 ui: remove "undefined" from events description
  pkg/ui/workspaces/db-console/src/util/events.ts
Labels: backport-23.1.x, backport-23.2.x, backport-23.2.0-rc

#116316 backupccl: fix codec selection during restore
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/backupinfo/BUILD.bazel
  pkg/ccl/backupccl/backupinfo/manifest_handling.go
  pkg/ccl/backupccl/backupinfo/manifest_handling_test.go
  pkg/ccl/backupccl/restore_job.go
Labels: backport-23.1.x, backport-23.2.x

#116442 kvnemesis: properly encode range keys
  pkg/kv/kvnemesis/engine.go
  pkg/kv/kvnemesis/validator.go
Labels: backport-23.1.x, backport-23.2.x

#116065 kvserver: filter rangefeed events based on OmitInRangefeeds flag
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed_test.go
  pkg/ccl/changefeedccl/kvfeed/physical_kv_feed.go
  pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvserver/batcheval/cmd_conditional_put.go
  pkg/kv/kvserver/batcheval/cmd_delete.go
  pkg/kv/kvserver/batcheval/cmd_delete_range.go
  pkg/kv/kvserver/batcheval/cmd_increment.go
  pkg/kv/kvserver/batcheval/cmd_init_put.go
  pkg/kv/kvserver/batcheval/cmd_put.go
  pkg/kv/kvserver/batcheval/declare.go
  pkg/kv/kvserver/client_test.go
  pkg/kv/kvserver/rangefeed/bench_test.go
  pkg/kv/kvserver/rangefeed/catchup_scan.go
  pkg/kv/kvserver/rangefeed/catchup_scan_bench_test.go
  pkg/kv/kvserver/rangefeed/catchup_scan_test.go
  pkg/kv/kvserver/rangefeed/processor.go
  pkg/kv/kvserver/rangefeed/processor_test.go
  pkg/kv/kvserver/rangefeed/registry.go
  pkg/kv/kvserver/rangefeed/registry_test.go
  pkg/kv/kvserver/rangefeed/scheduled_processor.go
  pkg/kv/kvserver/rangefeed/task_test.go
  pkg/kv/kvserver/replica_evaluate.go
  pkg/kv/kvserver/replica_evaluate_test.go
  pkg/kv/kvserver/replica_gossip.go
  pkg/kv/kvserver/replica_rangefeed.go
  pkg/kv/kvserver/replica_rangefeed_test.go
  pkg/kv/kvserver/replica_read.go
  pkg/kv/kvserver/replica_write.go
  pkg/storage/enginepb/mvcc3.proto
  pkg/storage/mvcc.go
  pkg/storage/mvcc_test.go
Labels: backport-23.2.x

#116466 release-23.1: roachtest: report failures to extend cluster as infra flakes
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/test_runner.go
Labels: backport

#116446 kv: disable use of shared locks in conjunction with skip locked
  pkg/kv/kvnemesis/BUILD.bazel
  pkg/kv/kvnemesis/applier.go
  pkg/kv/kvnemesis/testdata/TestApplier/get-for-share-skip-locked
  pkg/kv/kvnemesis/testdata/TestApplier/get-for-share-skip-locked-guaranteed-durability
  pkg/kv/kvnemesis/testdata/TestApplier/rscan-for-share-skip-locked
  pkg/kv/kvnemesis/testdata/TestApplier/rscan-for-share-skip-locked-guaranteed-durability
  pkg/kv/kvnemesis/testdata/TestApplier/scan-for-share-skip-locked
  pkg/kv/kvnemesis/testdata/TestApplier/scan-for-share-skip-locked-guaranteed-durability
  pkg/kv/kvnemesis/validator.go
  pkg/kv/kvserver/batcheval/cmd_get.go
  pkg/kv/kvserver/batcheval/cmd_reverse_scan.go
  pkg/kv/kvserver/batcheval/cmd_scan.go
  pkg/sql/logictest/testdata/logic_test/select_for_share
Labels: backport-23.2.x, backport-23.2.0-rc

#116420 release-23.2.0-rc: sql: support sequence and udt name rewriting in plpgsql
  pkg/ccl/logictestccl/testdata/logic_test/udf_rewrite
  pkg/sql/BUILD.bazel
  pkg/sql/crdb_internal.go
  pkg/sql/create_function.go
  pkg/sql/create_view.go
  pkg/sql/opt/optbuilder/plpgsql.go
  pkg/sql/plpgsql/parser/testdata/stmt_case
  pkg/sql/sem/plpgsqltree/BUILD.bazel
  pkg/sql/sem/plpgsqltree/exception.go
  pkg/sql/sem/plpgsqltree/statements.go
  pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go
  pkg/sql/sem/plpgsqltree/visitor.go
  pkg/sql/show_create_clauses.go
Labels: backport

#116499 release-23.2.0-rc: released CockroachDB version 23.2.0-beta.3. Next version: 23.2.0-rc.1
  pkg/build/version.txt
Labels: backport

#116462 release-23.2: scripts/bump-pebble.sh: use current branch, don't use pebble repo
  scripts/bump-pebble.sh
Labels: backport

#116361 release-23.1: importer: support arrays of UDT in some cases
  pkg/cli/statement_bundle.go
  pkg/sql/importer/BUILD.bazel
  pkg/sql/importer/import_into_test.go
  pkg/sql/importer/import_type_resolver.go
  pkg/sql/importer/read_import_avro.go
  pkg/sql/importer/read_import_base.go
  pkg/sql/importer/read_import_csv.go
  pkg/sql/importer/read_import_mysql.go
  pkg/sql/importer/read_import_mysql_test.go
  pkg/sql/importer/read_import_pgcopy.go
  pkg/sql/importer/read_import_pgdump.go
  pkg/sql/importer/read_import_workload.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/row/row_converter.go
  pkg/sql/rowenc/roundtrip_format.go
  pkg/sql/rowenc/roundtrip_format_test.go
  pkg/sql/stats/json.go
Labels: backport

#116359 release-23.2: importer: support arrays of UDT in some cases
  pkg/cli/statement_bundle.go
  pkg/sql/importer/BUILD.bazel
  pkg/sql/importer/import_into_test.go
  pkg/sql/importer/import_type_resolver.go
  pkg/sql/importer/read_import_avro.go
  pkg/sql/importer/read_import_base.go
  pkg/sql/importer/read_import_csv.go
  pkg/sql/importer/read_import_mysql.go
  pkg/sql/importer/read_import_mysql_test.go
  pkg/sql/importer/read_import_pgcopy.go
  pkg/sql/importer/read_import_pgdump.go
  pkg/sql/importer/read_import_workload.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/row/row_converter.go
  pkg/sql/rowenc/roundtrip_format.go
  pkg/sql/rowenc/roundtrip_format_test.go
  pkg/sql/stats/json.go
Labels: backport

#116360 release-23.2.0-rc: importer: support arrays of UDT in some cases
  pkg/cli/statement_bundle.go
  pkg/sql/importer/BUILD.bazel
  pkg/sql/importer/import_into_test.go
  pkg/sql/importer/import_type_resolver.go
  pkg/sql/importer/read_import_avro.go
  pkg/sql/importer/read_import_base.go
  pkg/sql/importer/read_import_csv.go
  pkg/sql/importer/read_import_mysql.go
  pkg/sql/importer/read_import_mysql_test.go
  pkg/sql/importer/read_import_pgcopy.go
  pkg/sql/importer/read_import_pgdump.go
  pkg/sql/importer/read_import_workload.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/row/row_converter.go
  pkg/sql/rowenc/roundtrip_format.go
  pkg/sql/rowenc/roundtrip_format_test.go
  pkg/sql/stats/json.go
Labels: backport

#112347 release-23.2: mint 23.2 version
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant
  pkg/cli/declarative_print_rules_test.go
  pkg/clusterversion/cockroach_versions.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/mixed_version_can_login
  pkg/sql/logictest/testdata/logic_test/mixed_version_role_members_user_ids
  pkg/sql/logictest/testdata/logic_test/mixed_version_udf_execute_privileges
Labels: backport, backport-23.2.0-rc

#116608 sqlsmith: don't use crdb_internal.reset_sql_stats builtin
  pkg/internal/sqlsmith/schema.go
Labels: backport-23.1.x, backport-23.2.x, backport-23.2.0-rc

#116624 sql: skip TestRaceWithIndexBackfillMerge under duress
  pkg/sql/mvcc_backfiller_test.go
  pkg/testutils/skip/skip.go
Labels: backport-23.1.x, backport-23.2.x, backport-23.2.0-rc

#116498 changefeedccl: Partially support CDC query in ALTER CHANGEFEED
  pkg/ccl/changefeedccl/alter_changefeed_stmt.go
  pkg/ccl/changefeedccl/alter_changefeed_test.go
Labels: backport-23.1.x, backport-23.2.x

#114707 lexbase: fix double-escaping in json + sql display format
  pkg/cli/clisqlexec/format_sql.go
  pkg/sql/lexbase/encode.go
  pkg/sql/lexbase/encode_test.go
Labels: O-community, X-blathers-triaged

#116547 sql: delete zone configuration in secondary tenant
  pkg/sql/drop_test.go
  pkg/sql/schema_changer.go
  pkg/sql/server_params_test.go
  pkg/sql/tests/data.go
Labels: backport-23.2.x

#116593 raftlog: close storage engine in test
  pkg/kv/kvserver/raftlog/iter_test.go
Labels: backport-23.1.x, backport-23.2.x

#116647 backup: fix BackingFileSize
  pkg/ccl/backupccl/backup_processor.go
  pkg/ccl/backupccl/file_sst_sink.go
Labels: backport-23.2.x

#116588 catalog: skip TestRangefeedUpdatesHandledProperlyInTheFaceOfRaces under duress
  pkg/sql/catalog/lease/lease_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-23.2.0-rc

#116570 json,tree,geopb: remove dependency from kvpb on geo
  docs/generated/http/BUILD.bazel
  pkg/cmd/geoviz/BUILD.bazel
  pkg/cmd/geoviz/geoviz.go
  pkg/gen/protobuf.bzl
  pkg/geo/geoindex/BUILD.bazel
  pkg/geo/geoindex/geoindex.go
  pkg/geo/geoindex/s2_geography_index.go
  pkg/geo/geoindex/s2_geography_index_test.go
  pkg/geo/geoindex/s2_geometry_index.go
  pkg/geo/geoindex/s2_geometry_index_test.go
  pkg/geo/geoindex/utils_test.go
  pkg/geo/geopb/BUILD.bazel
  pkg/geo/geopb/config.go
  pkg/geo/geopb/config.proto
  pkg/kv/kvpb/BUILD.bazel
  pkg/sql/catalog/BUILD.bazel
  pkg/sql/catalog/catformat/BUILD.bazel
  pkg/sql/catalog/catformat/index.go
  pkg/sql/catalog/descpb/BUILD.bazel
  pkg/sql/catalog/descpb/structured.proto
  pkg/sql/catalog/fetchpb/BUILD.bazel
  pkg/sql/catalog/fetchpb/index_fetch.proto
  pkg/sql/catalog/table_elements.go
  pkg/sql/catalog/tabledesc/BUILD.bazel
  pkg/sql/catalog/tabledesc/index.go
  pkg/sql/catalog/tabledesc/index_test.go
  pkg/sql/evalcatalog/BUILD.bazel
  pkg/sql/evalcatalog/geo_inverted_index_entries.go
  pkg/sql/opt/cat/BUILD.bazel
  pkg/sql/opt/cat/index.go
  pkg/sql/opt/exec/explain/BUILD.bazel
  pkg/sql/opt/exec/explain/plan_gist_factory.go
  pkg/sql/opt/indexrec/BUILD.bazel
  pkg/sql/opt/indexrec/hypothetical_index.go
  pkg/sql/opt/invertedidx/geo.go
  pkg/sql/opt/invertedidx/inverted_index_expr.go
  pkg/sql/opt/testutils/testcat/BUILD.bazel
  pkg/sql/opt/testutils/testcat/create_table.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/opt_catalog.go
  pkg/sql/protoreflect/BUILD.bazel
  pkg/sql/protoreflect/utils_test.go
  pkg/sql/rowenc/index_encoding.go
  pkg/sql/schemachanger/scdecomp/BUILD.bazel
  pkg/sql/schemachanger/scdecomp/decomp.go
  pkg/sql/schemachanger/scpb/BUILD.bazel
  pkg/sql/schemachanger/scpb/elements.proto
  pkg/sql/sem/builtins/geo_builtins.go
  pkg/sql/sem/tree/datum.go
  pkg/sql/storageparam/indexstorageparam/BUILD.bazel
  pkg/sql/storageparam/indexstorageparam/index_storage_param.go
  pkg/util/json/BUILD.bazel
  pkg/util/json/json.go
Labels: O-community

#116650 sql,plpgsql: correctly handle formatting for PL/pgSQL routine redaction and rewrites
  .github/workflows/experimental-github-actions-testing.yml
  pkg/ccl/backupccl/testdata/backup-restore/plpgsql_procedures
  pkg/ccl/backupccl/testdata/backup-restore/plpgsql_user_defined_functions
  pkg/cmd/roachtest/tests/online_restore.go
  pkg/sql/catalog/redact/BUILD.bazel
  pkg/sql/catalog/redact/redact.go
  pkg/sql/catalog/redact/redact_test.go
  pkg/sql/catalog/rewrite/BUILD.bazel
  pkg/sql/catalog/rewrite/rewrite.go
  pkg/sql/parser/parse_test.go
  pkg/sql/parser/statements/statement.go
  pkg/sql/plpgsql/parser/BUILD.bazel
  pkg/sql/plpgsql/parser/lexer.go
  pkg/sql/plpgsql/parser/parser_test.go
  pkg/sql/plpgsql/parser/plpgsql.y
  pkg/sql/plpgsql/parser/testdata/combo
  pkg/sql/plpgsql/parser/testdata/decl_header
  pkg/sql/plpgsql/parser/testdata/exception_sect
  pkg/sql/plpgsql/parser/testdata/stmt_assert
  pkg/sql/plpgsql/parser/testdata/stmt_assign
  pkg/sql/plpgsql/parser/testdata/stmt_block
  pkg/sql/plpgsql/parser/testdata/stmt_call
  pkg/sql/plpgsql/parser/testdata/stmt_case
  pkg/sql/plpgsql/parser/testdata/stmt_close
  pkg/sql/plpgsql/parser/testdata/stmt_commit_rollback
  pkg/sql/plpgsql/parser/testdata/stmt_dynexec
  pkg/sql/plpgsql/parser/testdata/stmt_exec_sql
  pkg/sql/plpgsql/parser/testdata/stmt_exit
  pkg/sql/plpgsql/parser/testdata/stmt_fetch_move
  pkg/sql/plpgsql/parser/testdata/stmt_for
  pkg/sql/plpgsql/parser/testdata/stmt_foreach_a
  pkg/sql/plpgsql/parser/testdata/stmt_getdiag
  pkg/sql/plpgsql/parser/testdata/stmt_if
  pkg/sql/plpgsql/parser/testdata/stmt_loop
  pkg/sql/plpgsql/parser/testdata/stmt_open
  pkg/sql/plpgsql/parser/testdata/stmt_perform
  pkg/sql/plpgsql/parser/testdata/stmt_raise
  pkg/sql/plpgsql/parser/testdata/stmt_return
  pkg/sql/plpgsql/parser/testdata/stmt_while
  pkg/sql/sem/plpgsqltree/exception.go
  pkg/sql/sem/plpgsqltree/statements.go
  pkg/sql/sem/plpgsqltree/utils/plpg_visitor.go
  pkg/testutils/sqlutils/BUILD.bazel
  pkg/testutils/sqlutils/parse.go
  pkg/testutils/sqlutils/pretty.go
Labels: backport-23.2.x, backport-23.2.0-rc

#116554 release-23.2: kvserver: filter rangefeed events based on OmitInRangefeeds flag
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed_test.go
  pkg/ccl/changefeedccl/kvfeed/physical_kv_feed.go
  pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvserver/batcheval/cmd_conditional_put.go
  pkg/kv/kvserver/batcheval/cmd_delete.go
  pkg/kv/kvserver/batcheval/cmd_delete_range.go
  pkg/kv/kvserver/batcheval/cmd_increment.go
  pkg/kv/kvserver/batcheval/cmd_init_put.go
  pkg/kv/kvserver/batcheval/cmd_put.go
  pkg/kv/kvserver/batcheval/declare.go
  pkg/kv/kvserver/client_test.go
  pkg/kv/kvserver/rangefeed/bench_test.go
  pkg/kv/kvserver/rangefeed/catchup_scan.go
  pkg/kv/kvserver/rangefeed/catchup_scan_bench_test.go
  pkg/kv/kvserver/rangefeed/catchup_scan_test.go
  pkg/kv/kvserver/rangefeed/processor.go
  pkg/kv/kvserver/rangefeed/processor_test.go
  pkg/kv/kvserver/rangefeed/registry.go
  pkg/kv/kvserver/rangefeed/registry_test.go
  pkg/kv/kvserver/rangefeed/scheduled_processor.go
  pkg/kv/kvserver/rangefeed/task_test.go
  pkg/kv/kvserver/replica_evaluate.go
  pkg/kv/kvserver/replica_evaluate_test.go
  pkg/kv/kvserver/replica_gossip.go
  pkg/kv/kvserver/replica_rangefeed.go
  pkg/kv/kvserver/replica_rangefeed_test.go
  pkg/kv/kvserver/replica_read.go
  pkg/kv/kvserver/replica_write.go
  pkg/storage/enginepb/mvcc3.proto
  pkg/storage/mvcc.go
  pkg/storage/mvcc_test.go
Labels: backport

#116557 release-23.2.0-rc: sql: attempt to unsplit ranges in GC job for secondary tenants
  pkg/sql/gcjob/BUILD.bazel
  pkg/sql/gcjob/gc_job.go
  pkg/sql/gcjob/gc_job_test.go
Labels: backport

#116558 release-23.1: sql: add `StmtPosInTxn` to CommonSQLExecDetails
  docs/generated/eventlog.md
  pkg/cli/interactive_tests/test_exec_log.tcl
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_log.go
  pkg/sql/telemetry_logging_test.go
  pkg/util/log/eventpb/json_encode_generated.go
  pkg/util/log/eventpb/sql_audit_events.proto
Labels: backport

#116612 release-23.2: roachtest: replace gs://cockroach-fixtures with gs://cockroach-fixtures-us-east1
  pkg/ccl/workloadccl/cliccl/fixtures.go
  pkg/cli/interactive_tests/test_workload.tcl
  pkg/cloud/gcp/gcs_storage_test.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/cdc.go
  pkg/cmd/roachtest/tests/copy.go
  pkg/cmd/roachtest/tests/copyfrom.go
  pkg/cmd/roachtest/tests/import.go
  pkg/cmd/roachtest/tests/import_cancellation.go
  pkg/cmd/roachtest/tests/restore.go
  pkg/cmd/roachtest/tests/schemachange.go
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/cmd/roachtest/tests/tpc_utils.go
  pkg/cmd/roachtest/tests/tpcdsvec.go
  pkg/roachprod/install/download.go
  pkg/roachprod/prometheus/prometheus.go
  pkg/workload/querybench/2.1-sql-20
  pkg/workload/tpcds/import.sql
  pkg/workload/tpch/import-sf1.sql
  pkg/workload/tpch/import-sf10.sql
  pkg/workload/tpch/tpch.go
Labels: T-testeng, backport

#116674 release-23.1: sql,opt: don't validate AOST during session migration
  pkg/sql/conn_executor_prepare.go
  pkg/sql/opt/optbuilder/builder.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/plan.go
  pkg/sql/plan_opt.go
  pkg/sql/testdata/session_migration/prepared_statements
Labels: backport

#116728 release-23.2: Improve shutdown checkpoint logic
  pkg/ccl/changefeedccl/changefeed_processors.go
Labels: backport

#116729 release-23.2.0-rc: Improve changefeed shutdown checkpoint logic
  pkg/ccl/changefeedccl/changefeed_processors.go
Labels: backport

#116779 release-23.2.0-rc: ui: clean up tenant dashboards
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overview.tsx
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/storage.tsx
Labels: backport

#116775 streamingccl: skip a few multi node tests under duress
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
Labels: T-disaster-recovery

#114747 release-23.1: pkg/util/aggmetric: tick histogram windows in AggHistogram
  pkg/BUILD.bazel
  pkg/util/metric/BUILD.bazel
  pkg/util/metric/aggmetric/BUILD.bazel
  pkg/util/metric/aggmetric/agg_metric.go
  pkg/util/metric/aggmetric/agg_metric_test.go
  pkg/util/metric/aggmetric/histogram.go
  pkg/util/metric/hdrhistogram.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_test.go
  pkg/util/metric/tick/BUILD.bazel
  pkg/util/metric/tick/tick.go
  pkg/util/metric/tick_helper.go
Labels: backport

#116613 release-23.2: roachtest: use backup cloud to set CompatibleClouds
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/backup_fixtures.go
  pkg/cmd/roachtest/tests/disagg_rebalance.go
  pkg/cmd/roachtest/tests/restore.go
Labels: backport

#116720 release-23.1: sql: make txnCounter for BEGIN logs more understandable
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/telemetry_logging_test.go
Labels: backport

#116704 release-23.2: sql: make txnCounter for BEGIN logs more understandable
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/telemetry_logging_test.go
Labels: backport

#116718 release-23.2: sql: add disable_changefeed_replication session variable
  pkg/ccl/logictestccl/testdata/logic_test/changefeed
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#116719 release-23.2: sql: add sql.ttl.changefeed_replication.disabled cluster setting
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/execinfrapb/processors_ttl.proto
  pkg/sql/ttl/ttlbase/ttl_helpers.go
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
Labels: backport

#116777 release-23.2.0-rc: kv: disable use of {shared,replicated} locks in conjunction with skip locked
  pkg/kv/kvnemesis/BUILD.bazel
  pkg/kv/kvnemesis/applier.go
  pkg/kv/kvnemesis/testdata/TestApplier/get-for-share-skip-locked
  pkg/kv/kvnemesis/testdata/TestApplier/get-for-share-skip-locked-guaranteed-durability
  pkg/kv/kvnemesis/testdata/TestApplier/rscan-for-share-skip-locked
  pkg/kv/kvnemesis/testdata/TestApplier/rscan-for-share-skip-locked-guaranteed-durability
  pkg/kv/kvnemesis/testdata/TestApplier/scan-for-share-skip-locked
  pkg/kv/kvnemesis/testdata/TestApplier/scan-for-share-skip-locked-guaranteed-durability
  pkg/kv/kvnemesis/validator.go
  pkg/kv/kvserver/batcheval/cmd_get.go
  pkg/kv/kvserver/batcheval/cmd_reverse_scan.go
  pkg/kv/kvserver/batcheval/cmd_scan.go
  pkg/sql/logictest/testdata/logic_test/select_for_share
  pkg/sql/logictest/testdata/logic_test/select_for_update
  pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed
Labels: backport

#116776 release-23.2: kv: disable use of {shared,replicated} locks in conjunction with skip locked
  pkg/kv/kvnemesis/BUILD.bazel
  pkg/kv/kvnemesis/applier.go
  pkg/kv/kvnemesis/testdata/TestApplier/get-for-share-skip-locked
  pkg/kv/kvnemesis/testdata/TestApplier/get-for-share-skip-locked-guaranteed-durability
  pkg/kv/kvnemesis/testdata/TestApplier/rscan-for-share-skip-locked
  pkg/kv/kvnemesis/testdata/TestApplier/rscan-for-share-skip-locked-guaranteed-durability
  pkg/kv/kvnemesis/testdata/TestApplier/scan-for-share-skip-locked
  pkg/kv/kvnemesis/testdata/TestApplier/scan-for-share-skip-locked-guaranteed-durability
  pkg/kv/kvnemesis/validator.go
  pkg/kv/kvserver/batcheval/cmd_get.go
  pkg/kv/kvserver/batcheval/cmd_reverse_scan.go
  pkg/kv/kvserver/batcheval/cmd_scan.go
  pkg/sql/logictest/testdata/logic_test/select_for_share
  pkg/sql/logictest/testdata/logic_test/select_for_update
  pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed
Labels: backport

#116170 opt: lock all column families for new SELECT FOR UPDATE
  pkg/sql/distsql_physical_planner.go
  pkg/sql/logictest/testdata/logic_test/select_for_update_read_committed
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/testdata/select_for_update
  pkg/sql/opt/ops/mutation.opt
  pkg/sql/opt/optbuilder/locking.go
  pkg/sql/opt/optbuilder/testdata/select_for_update
  pkg/sql/opt_exec_factory.go
  pkg/sql/rowenc/index_encoding.go
  pkg/sql/span/BUILD.bazel
  pkg/sql/span/span_splitter.go
  pkg/sql/span/span_splitter_test.go
Labels: backport-23.2.x, backport-23.1.12-rc.FROZEN, backport-23.2.0-rc

#116656 backupccl: replace UDT IDs within routine bodies and views
  pkg/ccl/backupccl/testdata/backup-restore/plpgsql_procedures
  pkg/ccl/backupccl/testdata/backup-restore/plpgsql_user_defined_functions
  pkg/ccl/backupccl/testdata/backup-restore/procedures
  pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions
  pkg/ccl/backupccl/testdata/backup-restore/views
  pkg/sql/catalog/rewrite/rewrite.go
Labels: backport-23.1.x, backport-23.2.x

#116663 util/interval/generic: stop lying about live memory
  pkg/kv/kvserver/concurrency/keylocks_interval_btree.go
  pkg/kv/kvserver/concurrency/keylocks_interval_btree_test.go
  pkg/kv/kvserver/spanlatch/latch_interval_btree.go
  pkg/kv/kvserver/spanlatch/latch_interval_btree_test.go
  pkg/spanconfig/spanconfigstore/entry_interval_btree.go
  pkg/spanconfig/spanconfigstore/entry_interval_btree_test.go
  pkg/util/interval/generic/example_interval_btree.go
  pkg/util/interval/generic/example_interval_btree_test.go
  pkg/util/interval/generic/internal/interval_btree_tmpl.go
  pkg/util/interval/generic/internal/interval_btree_tmpl_test.go
Labels: O-community

#116871 release-23.2.0-rc: tick AggHistograms, reduce allocations when recording histograms
  pkg/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/sqlproxyccl/connector_test.go
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
  pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go
  pkg/kv/kvserver/scheduler_test.go
  pkg/server/status/recorder.go
  pkg/server/status/recorder_test.go
  pkg/sql/sqlstats/persistedsqlstats/bench_test.go
  pkg/util/asciitsdb/BUILD.bazel
  pkg/util/asciitsdb/asciitsdb.go
  pkg/util/metric/BUILD.bazel
  pkg/util/metric/aggmetric/BUILD.bazel
  pkg/util/metric/aggmetric/agg_metric.go
  pkg/util/metric/aggmetric/agg_metric_test.go
  pkg/util/metric/aggmetric/histogram.go
  pkg/util/metric/hdrhistogram.go
  pkg/util/metric/histogram_snapshot.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_test.go
  pkg/util/metric/tick/BUILD.bazel
  pkg/util/metric/tick/tick.go
  pkg/util/metric/tick_helper.go
  pkg/util/schedulerlatency/histogram.go
  pkg/util/schedulerlatency/histogram_test.go
  pkg/util/schedulerlatency/scheduler_latency_test.go
Labels: backport

#116786 release-23.2: logictest: fix rare flake
  pkg/ccl/logictestccl/testdata/logic_test/crdb_internal
Labels: backport

#116787 release-23.2.0-rc: logictest: fix rare flake
  pkg/ccl/logictestccl/testdata/logic_test/crdb_internal
Labels: backport

#116645 testutils: Fix `ExpectErrWithTimeout` function to correctly fail the test on mismatched error message
  pkg/testutils/sqlutils/sql_runner.go
Labels: O-community, backport-23.2.x, backport-23.2.0-rc

#115730 release: 23.2: backupccl: add backup checkpointing test
  pkg/ccl/backupccl/backup_job.go
  pkg/ccl/backupccl/backup_test.go
Labels: T-disaster-recovery

#116686 release-23.2: catalog: skip TestRangefeedUpdatesHandledProperlyInTheFaceOfRaces under duress
  pkg/sql/catalog/lease/lease_test.go
Labels: backport

#116687 release-23.2.0-rc: catalog: skip TestRangefeedUpdatesHandledProperlyInTheFaceOfRaces under duress
  pkg/sql/catalog/lease/lease_test.go
Labels: backport

#116897 release-23.2.0-rc: storage: disable crashing for single delete callbacks
  docs/generated/settings/settings.html
  pkg/kv/kvserver/metrics.go
  pkg/storage/engine.go
  pkg/storage/metamorphic/BUILD.bazel
  pkg/storage/metamorphic/generator.go
  pkg/storage/pebble.go
Labels: backport

#116889 storage: disable crashing for single delete callbacks
  docs/generated/settings/settings.html
  pkg/kv/kvserver/metrics.go
  pkg/storage/engine.go
  pkg/storage/metamorphic/BUILD.bazel
  pkg/storage/metamorphic/generator.go
  pkg/storage/pebble.go
Labels: release-blocker, GA-blocker, branch-release-23.2, backport-23.2.x, backport-23.2.0-rc, blocks-23.2.0-rc.1

#116548 backupccl: reset job level retry counter if progress has advanced
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_progress_test.go
  pkg/jobs/jobspb/jobs.go
  pkg/sql/exec_util.go
Labels: T-disaster-recovery
