Repository cockroachdb/cockroach, pull requests merged in 2023-07, with the labels that each got.

#105914 ui: add cluster setting to skip activity tables
  pkg/server/cluster_settings.go
  pkg/server/combined_statement_stats.go
  pkg/sql/sql_activity_update_job_test.go
Labels: backport-23.1.x

#105924 allocator: expose LeaseRebalanceThreshold as a cluster setting
  docs/generated/settings/settings.html
  pkg/kv/kvserver/allocator/allocatorimpl/allocator.go
  pkg/kv/kvserver/replicate_queue_test.go
Labels: backport-22.1.x, backport-23.1.x

#105945 lease: unskip TestDescriptorRefreshOnRetry
  pkg/sql/catalog/lease/lease_test.go
Labels: backport-23.1.x

#105897 kvserver: deflake TestClosedTimestampCantServeWithConflictingIntent
  pkg/kv/kvserver/closed_timestamp_test.go
Labels: backport-23.1.x

#105896 kvserver: don't put a timeout on circuit breaker probes
  pkg/kv/kvserver/replica_circuit_breaker.go
Labels: backport-22.2.x, backport-23.1.x

#105969 roachtest: load AWS fixtures from us-east-2 to avoid egress
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/copy.go
  pkg/cmd/roachtest/tests/import.go
  pkg/cmd/roachtest/tests/import_cancellation.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_decl_schemachange_compat.go
  pkg/cmd/roachtest/tests/restore.go
  pkg/cmd/roachtest/tests/schemachange.go
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/cmd/roachtest/tests/tpc_utils.go
  pkg/cmd/roachtest/tests/tpcdsvec.go
  pkg/roachprod/vm/aws/aws.go
Labels: backport-22.2.x, backport-23.1.x

#106083 TEAMS.yaml: change triage column id for migrations
  TEAMS.yaml
Labels: backport-22.2.x, backport-23.1.x

#106111 roachtest: fix sysbench segfault detection one more time
  pkg/cmd/roachtest/tests/sysbench.go
Labels: backport-23.1.x

#105841 sqlstats, builtins: add builtin to reset activity tables
  docs/generated/sql/functions.md
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/eval/deps.go
  pkg/sql/sqlstats/persistedsqlstats/controller.go
  pkg/sql/sqlstats/persistedsqlstats/controller_test.go
Labels: backport-23.1.x

#106098 roachtest: restart-one-node to use explicit addrs
  pkg/cmd/roachtest/tests/gossip.go
Labels: backport-22.2.x, backport-23.1.x

#102635 server, tenant: gate process debugging behind capability
  pkg/ccl/logictestccl/testdata/logic_test/tenant_capability
  pkg/ccl/oidcccl/authentication_oidc_test.go
  pkg/ccl/serverccl/server_controller_test.go
  pkg/ccl/serverccl/server_sql_test.go
  pkg/ccl/serverccl/statusccl/tenant_grpc_test.go
  pkg/ccl/serverccl/tenant_test_utils.go
  pkg/ccl/serverccl/tenant_vars_test.go
  pkg/cli/democluster/demo_cluster.go
  pkg/configprofiles/testdata/multitenant-app
  pkg/configprofiles/testdata/multitenant-app-repl
  pkg/configprofiles/testdata/multitenant-noapp
  pkg/configprofiles/testdata/multitenant-noapp-repl
  pkg/kv/kvserver/client_tenant_test.go
  pkg/kv/kvserver/tenantrate/limiter_test.go
  pkg/multitenant/tenantcapabilities/capabilities.go
  pkg/multitenant/tenantcapabilities/id_string.go
  pkg/multitenant/tenantcapabilities/interfaces.go
  pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/allow_everything.go
  pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/allow_nothing.go
  pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go
  pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/testdata/authorizer_enabled
  pkg/multitenant/tenantcapabilities/tenantcapabilitiespb/capabilities.proto
  pkg/multitenant/tenantcapabilities/values.go
  pkg/rpc/auth_test.go
  pkg/security/certs_rotation_test.go
  pkg/security/certs_test.go
  pkg/server/admin_cluster_test.go
  pkg/server/admin_test.go
  pkg/server/api_v2_ranges_test.go
  pkg/server/api_v2_sql_schema_test.go
  pkg/server/api_v2_sql_test.go
  pkg/server/api_v2_test.go
  pkg/server/authentication_test.go
  pkg/server/config.go
  pkg/server/debug/BUILD.bazel
  pkg/server/debug/server.go
  pkg/server/node_http_router_test.go
  pkg/server/server.go
  pkg/server/server_controller_new_server.go
  pkg/server/server_http_test.go
  pkg/server/server_test.go
  pkg/server/status_test.go
  pkg/server/tenant.go
  pkg/server/testserver.go
  pkg/server/testserver_http.go
  pkg/testutils/serverutils/test_server_shim.go
  pkg/testutils/serverutils/test_tenant_shim.go
  pkg/testutils/testcluster/testcluster_test.go
Labels: A-multitenancy, backport-23.1.x

#106149 c2c: skip TestTenantStreamingUnavailableStreamAddress
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
Labels: T-disaster-recovery, backport-23.1.x

#105832 upgrades: try to repair catalog corruptions during upgrade
  docs/generated/sql/functions.md
  pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant
  pkg/cli/zip_test.go
  pkg/sql/catalog/desctestutils/descriptor_test_utils.go
  pkg/sql/catalog/post_deserialization_changes.go
  pkg/sql/catalog/redact/redact_test.go
  pkg/sql/catalog/tabledesc/structured_test.go
  pkg/sql/catalog/tabledesc/table_desc_builder.go
  pkg/sql/catalog/tabledesc/table_desc_test.go
  pkg/sql/crdb_internal.go
  pkg/sql/crdb_internal_test.go
  pkg/sql/doctor/doctor_test.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_builtins
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/schema_repair
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/xform/testdata/external/activerecord
  pkg/sql/opt/xform/testdata/external/liquibase
  pkg/sql/opt/xform/testdata/external/navicat
  pkg/sql/opt/xform/testdata/external/pgjdbc
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/catconstants/constants.go
  pkg/upgrade/upgrades/first_upgrade.go
  pkg/upgrade/upgrades/first_upgrade_test.go
Labels: backport-23.1.x

#106081 cmd/internal/issues: fix missing reproduction command in GH issue rep…
  pkg/cmd/internal/issues/formatter_unit.go
Labels: backport-22.2.x, backport-23.1.x

#106074 cloud,backupccl: path does not contain a completed latest backup (emp…
  pkg/ccl/backupccl/backupdest/backup_destination.go
Labels: backport-22.2.x, backport-23.1.x

#106115 backupccl: enable restore-grants test on tenant
  pkg/ccl/backupccl/testdata/backup-restore/restore-grants
Labels: backport-23.1.x

#106116 configprofiles: emphasize "cluster virtualization"
  pkg/configprofiles/profiles.go
  pkg/configprofiles/setter.go
  pkg/configprofiles/testdata/replication-source
  pkg/configprofiles/testdata/replication-target
  pkg/configprofiles/testdata/virtual-app
  pkg/configprofiles/testdata/virtual-app-repl
  pkg/configprofiles/testdata/virtual-noapp
  pkg/configprofiles/testdata/virtual-noapp-repl
Labels: A-multitenancy, backport-23.1.x

#105885 rpc: improve test coverage of initial heartbeat failures
  pkg/rpc/context_test.go
  pkg/util/grpcutil/BUILD.bazel
  pkg/util/grpcutil/grpc_util.go
  pkg/util/grpcutil/grpc_util_test.go
Labels: backport-22.2.x, backport-23.1.x

#106121 sql: session var `disable_drop_virtual_cluster`
  pkg/configprofiles/profiles.go
  pkg/configprofiles/testdata/virtual-app
  pkg/configprofiles/testdata/virtual-app-repl
  pkg/configprofiles/testdata/virtual-noapp
  pkg/configprofiles/testdata/virtual-noapp-repl
  pkg/settings/registry.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/tenant
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/tenant_deletion.go
  pkg/sql/vars.go
Labels: A-multitenancy, backport-23.1.x

#106323 ui: fix crash on key visualizer
  pkg/ui/workspaces/db-console/src/views/keyVisualizer/index.tsx
  pkg/ui/workspaces/db-console/src/views/keyVisualizer/keyVisualizer.tsx
Labels: backport-23.1.x

#106298 cli/zip: Use "cluster" to identify the logical cluster instead of "tenant"
  pkg/cli/testdata/zip/testzip_shared_process_virtualization
  pkg/cli/zip.go
Labels: A-multitenancy, backport-23.1.x

#106265 c2c: unskip some tests under stress race
  pkg/ccl/streamingccl/streamingest/BUILD.bazel
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go
Labels: T-disaster-recovery

#106359 changefeedccl: Fix cluster ID check logic
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport-23.1.x

#106396 server: de-flake a decommission test race condition
  pkg/server/decommission.go
  pkg/sql/event_log.go
Labels: backport-23.1.x

#103142 c2c: introduce automatic distsql replanning
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/ccl/streamingccl/streamingest/BUILD.bazel
  pkg/ccl/streamingccl/streamingest/metrics.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_dist.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_dist_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/sql/distsql_plan_bulk.go
  pkg/sql/exec_util.go
Labels: T-disaster-recovery

#106180 sql: enable TestDropDatabaseDeleteData
  pkg/sql/drop_test.go
Labels: backport-23.1.x

#106436 sql: increase test timeout
  pkg/sql/sql_activity_update_job_test.go
Labels: backport-23.1.x

#106424 logictest: deflake udf tracing test
  pkg/sql/logictest/testdata/logic_test/udf
Labels: backport-22.2.x, backport-23.1.x

#106416 roachtest: fix multitenant-upgrade
  pkg/ccl/logictestccl/testdata/logic_test/tenant_settings
  pkg/cmd/roachtest/tests/multitenant_upgrade.go
  pkg/server/node.go
  pkg/settings/version.go
  pkg/sql/logictest/testdata/logic_test/tenant
  pkg/sql/set_cluster_setting.go
  pkg/upgrade/upgrades/permanent_upgrades.go
Labels: A-multitenancy, backport-23.1.x

#106037 sql,server,upgrades: simpler sending of version to tenant servers
  pkg/ccl/logictestccl/testdata/logic_test/tenant_settings
  pkg/server/node.go
  pkg/settings/version.go
  pkg/sql/logictest/testdata/logic_test/tenant
  pkg/sql/set_cluster_setting.go
  pkg/upgrade/upgrades/permanent_upgrades.go
Labels: A-multitenancy

#106270 sql: enable gc tests
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/drop_test.go
  pkg/sql/tests/data.go
Labels: backport-23.1.x

#106463 interactive_tests: preserve demo logs in tests
  pkg/acceptance/generated_cli_test.go
  pkg/cli/interactive_tests/test_demo.tcl
  pkg/cli/interactive_tests/test_demo_changefeeds.tcl
  pkg/cli/interactive_tests/test_demo_cli_integration.tcl
  pkg/cli/interactive_tests/test_demo_global.tcl
  pkg/cli/interactive_tests/test_demo_global_insecure.tcl
  pkg/cli/interactive_tests/test_demo_locality_error.tcl
  pkg/cli/interactive_tests/test_demo_memory_warning.tcl
  pkg/cli/interactive_tests/test_demo_multitenant.tcl.disabled
  pkg/cli/interactive_tests/test_demo_networking.tcl
  pkg/cli/interactive_tests/test_demo_node_cmds.tcl
  pkg/cli/interactive_tests/test_demo_partitioning.tcl.disabled
  pkg/cli/interactive_tests/test_demo_telemetry.tcl
  pkg/cli/interactive_tests/test_demo_workload.tcl
  pkg/cli/interactive_tests/test_dump_sig.tcl
  pkg/cli/interactive_tests/test_interrupt.tcl
  pkg/cli/interactive_tests/test_local_cmds.tcl
  pkg/cli/interactive_tests/test_log_flags.tcl
  pkg/cli/interactive_tests/test_notice.tcl
  pkg/cli/interactive_tests/test_timing.tcl
Labels: backport-23.1.x

#106509 upgrades: fix transaction retry bug in auto config job migration
  pkg/upgrade/upgrades/create_auto_config_runner_job.go
Labels: backport-23.1.x

#106562 sql: fix rare flake in a stmt bundle test
  pkg/sql/instrumentation.go
Labels: backport-23.1.x

#106535 sqlstats: deflake TestSQLStatsIdleLatencies
  pkg/sql/sqlstats/sslocal/BUILD.bazel
  pkg/sql/sqlstats/sslocal/sql_stats_test.go
Labels: backport-23.1.x

#106275 roachtest: support `versions-binary-override` in `mixedversion`
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: backport-23.1.x

#106544 build: don't use `goimports` for `goyacc`
  pkg/sql/lexbase/sql-gen.sh
  pkg/sql/parser/BUILD.bazel
  pkg/sql/parser/sql.y
  pkg/sql/pgrepl/pgreplparser/BUILD.bazel
  pkg/sql/pgrepl/pgreplparser/pgrepl.y
  pkg/sql/plpgsql/parser/BUILD.bazel
  pkg/sql/plpgsql/parser/plpgsql.y
  pkg/testutils/lint/lint_test.go
Labels: backport-23.1.x

#106495 sql: deflake TestParallel
  pkg/sql/logictest/parallel_test.go
  pkg/sql/logictest/testdata/parallel_test/create_stats/test.yaml
Labels: backport-23.1.x

#106631 statusccl: unskip testTenantRanges pagination
  pkg/ccl/serverccl/statusccl/tenant_status_test.go
Labels: backport-23.1.x

#106566 cli/interactive_tests: re-enable sql_mem_monitor test
  pkg/acceptance/generated_cli_test.go
  pkg/cli/interactive_tests/test_sql_mem_monitor.tcl
Labels: backport-23.1.x

#105647 cloud/azure: add file credentials to implicit auth path for storage and KMS
  pkg/cloud/azure/BUILD.bazel
  pkg/cloud/azure/azure_file_credential.go
  pkg/cloud/azure/azure_file_credentials_test.go
  pkg/cloud/azure/azure_kms.go
  pkg/cloud/azure/azure_kms_test.go
  pkg/cloud/azure/azure_storage.go
  pkg/cloud/azure/azure_storage_test.go
  pkg/cloud/external_storage.go
  pkg/cloud/kms_test_utils.go
  pkg/cloud/options.go
Labels: backport-23.1.x

#106639 stmtdiagnostics: de-flake TestDiagnosticsRequest for good
  pkg/sql/stmtdiagnostics/statement_diagnostics.go
  pkg/sql/stmtdiagnostics/statement_diagnostics_test.go
Labels: backport-23.1.x

#106609 cli,server: log the initiation of shutdown more clearly
  pkg/cli/start.go
  pkg/server/stop_trigger.go
  pkg/server/testserver.go
Labels: backport-23.1.x

#106502 batcheval: delete flaky integration test
  pkg/kv/kvserver/batcheval/cmd_lease_test.go
Labels: backport-23.1.x

#89170 serverutils: fix and simplify the tenant server configuration
  pkg/cli/flags.go
  pkg/testutils/serverutils/BUILD.bazel
  pkg/testutils/serverutils/test_server_shim.go
  pkg/util/constants.go
Labels: A-multitenancy

#106676 jobs: unskip TestRetriesWithExponentialBackoff subcases
  pkg/jobs/registry_test.go
Labels: backport-23.1.x

#106332 roachtest: add README to `mixedversion` package
  pkg/cmd/roachtest/roachtestutil/mixedversion/README.md
Labels: backport-23.1.x

#106679 democluster: fix a flake in TestTransientClusterMultitenant
  pkg/cli/democluster/demo_cluster_test.go
Labels: A-multitenancy, backport-22.2.x, backport-23.1.x

#106624 server: assert `ApproximateDiskBytes` from db details is non-zero
  pkg/server/admin_cluster_test.go
Labels: backport-22.2.x, backport-23.1.x

#106503 userfile: fix transaction retry upload bug
  pkg/cloud/userfile/filetable/file_table_read_writer.go
Labels: backport-22.1.x, backport-22.2.x, backport-23.1.x

#106510 backupccl: fix txn retry bug during planning
  pkg/ccl/backupccl/backup_job.go
Labels: backport-22.2.x, backport-23.1.x

#106561 c2c: deflake and refactor TestTenantReplicationProtectedTimestampManagement
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
Labels: T-disaster-recovery, backport-23.1.x

#106702 sql: stablize TestTxnObeysTableModificationTime
  pkg/sql/catalog/lease/lease_test.go
Labels: backport-23.1.x

#106587 sql: fix StatementStatistics.Nodes list
  pkg/ccl/testccl/sqlstatsccl/BUILD.bazel
  pkg/ccl/testccl/sqlstatsccl/sql_stats_test.go
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_log.go
  pkg/sql/execinfra/flow_context.go
  pkg/sql/execinfrapb/component_stats.go
  pkg/sql/execinfrapb/component_stats.proto
  pkg/sql/execstats/BUILD.bazel
  pkg/sql/execstats/traceanalyzer.go
  pkg/sql/execstats/traceanalyzer_test.go
  pkg/sql/executor_statement_metrics.go
  pkg/sql/flowinfra/flow.go
  pkg/sql/flowinfra/outbox.go
  pkg/sql/instrumentation.go
  pkg/sql/opt/exec/execbuilder/testdata/distsql_misc
  pkg/sql/sqlstats/ssmemstorage/ss_mem_writer.go
  pkg/sql/sqlstats/ssprovider.go
Labels: backport-23.1.x

#106721 spanstatsconsumer: avoid unnecessary panics in GetSamples
  pkg/keyvisualizer/spanstatsconsumer/span_stats_consumer.go
Labels: backport-23.1.x

#106699 release-22.2: democluster: fix a flake in TestTransientClusterMultitenant
  pkg/cli/democluster/demo_cluster_test.go
Labels: A-multitenancy

#106181 sql: TestValidationWithProtectedTS is skipped
  pkg/sql/backfill_protected_timestamp_test.go
  pkg/sql/index_backfiller.go
  pkg/sql/mvcc_backfiller.go
  pkg/sql/schemachanger/scdeps/sctestdeps/backfill.go
  pkg/sql/schemachanger/scexec/dependencies.go
  pkg/sql/schemachanger/scexec/exec_backfill.go
  pkg/sql/schemachanger/scexec/exec_backfill_test.go
  pkg/sql/schemachanger/scexec/executor_external_test.go
  pkg/sql/schemachanger/scexec/mocks_generated_test.go
Labels: backport-23.1.x

#106701 upgrades: fix transaction retry error
  pkg/upgrade/upgrades/delete_descriptors_of_dropped_functions.go
Labels: backport-23.1.x

#106145 kvserver: deflake all tests that restart test cluster servers
  pkg/BUILD.bazel
  pkg/base/BUILD.bazel
  pkg/base/test_server_args.go
  pkg/cli/BUILD.bazel
  pkg/cli/debug_recover_loss_of_quorum_test.go
  pkg/kv/kvserver/BUILD.bazel
  pkg/kv/kvserver/client_raft_test.go
  pkg/kv/kvserver/client_replica_test.go
  pkg/kv/kvserver/client_store_test.go
  pkg/kv/kvserver/loqrecovery/BUILD.bazel
  pkg/kv/kvserver/loqrecovery/server_integration_test.go
  pkg/kv/kvserver/node_liveness_test.go
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/server/BUILD.bazel
  pkg/server/server_startup_test.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/listenerutil/BUILD.bazel
  pkg/testutils/listenerutil/listener.go
  pkg/testutils/listenerutil/listener_test.go
  pkg/testutils/testcluster/BUILD.bazel
  pkg/testutils/testcluster/testcluster.go
  pkg/testutils/testcluster/testcluster_test.go
  pkg/util/startup/BUILD.bazel
  pkg/util/startup/startup_test.go
Labels: backport-23.1.x

#106711 release-23.1: unskip and deflake some c2c tests
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/ccl/streamingccl/streamingest/BUILD.bazel
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go
Labels: T-disaster-recovery

#106574 kvserver: avoid leaked replica mutex during delegated snapshot
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_app_batch.go
  pkg/kv/kvserver/replica_command.go
  pkg/kv/kvserver/replica_proposal_buf.go
  pkg/kv/kvserver/replica_raftstorage.go
  pkg/kv/kvserver/stores_base.go
Labels: backport-22.2.x, backport-23.1.x

#106717 opt: fix top-k ordering enforcement
  pkg/sql/logictest/testdata/logic_test/order_by
  pkg/sql/opt/ordering/topk.go
  pkg/sql/opt/xform/testdata/physprops/ordering
Labels: backport-22.2.x, backport-23.1.x

#106753 sql: add SQLInstanceIDs to telemetry SampledQuery event
  docs/generated/eventlog.md
  pkg/sql/exec_log.go
  pkg/sql/telemetry_logging_test.go
  pkg/util/log/eventpb/eventpbgen/gen.go
  pkg/util/log/eventpb/json_encode_generated.go
  pkg/util/log/eventpb/telemetry.proto
Labels: backport-23.1.x

#106033 codelabs: add details about fixed OIDs to SQL function codelab
  docs/codelabs/00-sql-function.md
Labels: O-community, X-blathers-untriaged

#106641 CODEOWNERS: move upgrade pkg to release-eng team
  .github/CODEOWNERS
  TEAMS.yaml
Labels: backport-23.1.x

#106826 release-23.1: c2c: use shared process tenants in c2c unit tests
  pkg/ccl/streamingccl/replicationtestutils/BUILD.bazel
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/ccl/streamingccl/streamingest/alter_replication_job_test.go
  pkg/ccl/streamingccl/streamingest/datadriven_test.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/ccl/streamingccl/streamingest/testdata/simple
Labels: T-disaster-recovery

#105931 colexec: don't infinite loop cross-join with zero-column left input
  pkg/sql/colexec/colexecjoin/crossjoiner.eg.go
  pkg/sql/colexec/colexecjoin/crossjoiner_tmpl.go
  pkg/sql/logictest/testdata/logic_test/cross_join
Labels: backport-22.2.x, backport-23.1.x

#106444 c2c: refactor eventStream to track batch in seperate streamEventBatcher
  pkg/ccl/streamingccl/replicationtestutils/BUILD.bazel
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/ccl/streamingccl/replicationutils/utils.go
  pkg/ccl/streamingccl/streamingest/replication_random_client_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go
  pkg/ccl/streamingccl/streamproducer/BUILD.bazel
  pkg/ccl/streamingccl/streamproducer/event_stream.go
  pkg/ccl/streamingccl/streamproducer/stream_event_batcher.go
  pkg/ccl/streamingccl/streamproducer/stream_event_batcher_test.go
Labels: T-disaster-recovery

#106853 c2c: run TestStreamingAutoReplan on a single multitenant cluster
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
Labels: T-disaster-recovery, backport-23.1.x

#106553 sql: fix labelled tuple type checking
  pkg/sql/logictest/testdata/logic_test/tuple
  pkg/sql/sem/tree/type_check.go
Labels: backport-23.1.x

#106712 ui: add timescale label to statement diagnostics
  pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.spec.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
Labels: backport-22.2.x, backport-23.1.x

#106754 ui: increase polling of stmnt diagnostics if not completed
  pkg/ui/workspaces/cluster-ui/src/store/statementDiagnostics/statementDiagnostics.sagas.ts
  pkg/ui/workspaces/db-console/src/redux/apiReducers.ts
  pkg/ui/workspaces/db-console/src/redux/statements/statementsSagas.spec.ts
  pkg/ui/workspaces/db-console/src/redux/statements/statementsSagas.ts
Labels: O-community

#107229 sql: fix SHOW GRANTS when schema is offline
  pkg/ccl/backupccl/testdata/backup-restore/restore-grants
  pkg/sql/information_schema.go
Labels: backport-23.1.x

#106893 failover: re-enable disk stall detector in `diskStallFailer.Ready`
  pkg/cmd/roachtest/tests/failover.go
Labels: backport-23.1.x

#107213 ui: fix Sort dropdown on Latency page in db-console
  pkg/ui/workspaces/db-console/src/app.spec.tsx
  pkg/ui/workspaces/db-console/src/app.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/network/sort/index.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/network/sort/sort.spec.tsx
Labels: O-community, backport-22.2.x

#107334 backupccl: possibly deflake TestBackupRestoreAppend
  pkg/ccl/backupccl/backup_test.go
Labels: backport-23.1.x

#106808 ttljob: fix minor book-keeping bug during txn retry
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/ttljob_processor.go
  pkg/sql/ttl/ttljob/ttljob_test.go
Labels: backport-23.1.x

#107324 colbuilder: clean up type schema handling
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/colexec/colbuilder/execplan_test.go
  pkg/testutils/lint/lint_test.go
Labels: backport-22.2.x, backport-23.1.x

#107282 sql: do not audit internal executors
  pkg/sql/audit_logging.go
  pkg/sql/exec_log.go
Labels: backport-23.1.x

#106414 server: properly check existence of tenant record
  pkg/BUILD.bazel
  pkg/base/test_server_args.go
  pkg/ccl/serverccl/BUILD.bazel
  pkg/ccl/serverccl/server_sql_test.go
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/kv/kvclient/kvtenant/connector_factory.go
  pkg/kv/kvclient/kvtenant/setting_overrides.go
  pkg/kv/kvpb/BUILD.bazel
  pkg/kv/kvpb/api.proto
  pkg/kv/kvpb/errors.go
  pkg/multitenant/mtinfo/BUILD.bazel
  pkg/multitenant/mtinfo/info.go
  pkg/multitenant/mtinfopb/info.go
  pkg/multitenant/tenantcapabilities/BUILD.bazel
  pkg/multitenant/tenantcapabilities/interfaces.go
  pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/BUILD.bazel
  pkg/multitenant/tenantcapabilities/tenantcapabilitiestestutils/testutils.go
  pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/BUILD.bazel
  pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/decoder.go
  pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/decoder_test.go
  pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/testdata/basic
  pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/testdata/initial_scan
  pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/testdata/rangefeed_errors
  pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/testdata/wait_info
  pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/watcher.go
  pkg/multitenant/tenantcapabilities/tenantcapabilitieswatcher/watcher_test.go
  pkg/server/node.go
  pkg/server/server.go
  pkg/server/settingswatcher/BUILD.bazel
  pkg/server/settingswatcher/settings_watcher.go
  pkg/server/tenant.go
  pkg/server/tenantsettingswatcher/overrides_store.go
  pkg/server/tenantsettingswatcher/watcher.go
  pkg/server/testing_knobs.go
  pkg/server/testserver.go
  pkg/sql/BUILD.bazel
  pkg/sql/tenant_accessors.go
  pkg/testutils/lint/lint_test.go
  pkg/testutils/serverutils/test_server_shim.go
Labels: A-multitenancy

#107059 release-23.1: DEPS: bump across etcd-io/raft#81 and disable conf change validation
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/kv/kvserver/client_raft_test.go
  pkg/kv/kvserver/store.go
Labels: db-cy-23

#107459 sql: fix potential mutex leak in conn_executor
  pkg/sql/conn_executor.go
Labels: backport-22.2.x, backport-23.1.x

#107536 roachprod: Azure FindActiveAccount username fix
  pkg/roachprod/vm/azure/azure.go
Labels: backport-23.1.x

#107506 kvserver,allocator: minor log message improvements
  pkg/kv/kvserver/allocator/allocatorimpl/allocator.go
  pkg/kv/kvserver/replicate_queue.go
Labels: backport-22.2.x, backport-23.1.x

#107176 release-22.2: ui: fix Filter dropdown menu on Latency page
  pkg/ui/workspaces/db-console/src/views/reports/containers/network/filter/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/dropdown/index.tsx
Labels: O-community

#107596 kvcoord: disable fatal assertion on transaction commit sanity check
  pkg/kv/kvclient/kvcoord/replayed_commit_test.go
  pkg/kv/kvclient/kvcoord/testing_knobs.go
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
Labels: backport-23.1.x

#107359 roachtest: mixed version decommission pass pgport
  pkg/cmd/roachtest/tests/mixed_version_decommission.go
Labels: backport-23.1.x

#107504 sql: Add observability when schema change jobs are blocked by concurrent ones
  pkg/sql/catalog/dbdesc/database_desc.go
  pkg/sql/catalog/descriptor.go
  pkg/sql/catalog/funcdesc/func_desc.go
  pkg/sql/catalog/schemadesc/schema_desc.go
  pkg/sql/catalog/schemadesc/synthetic_schema_desc.go
  pkg/sql/catalog/tabledesc/table_desc.go
  pkg/sql/catalog/typedesc/table_implicit_record_type.go
  pkg/sql/catalog/typedesc/type_desc.go
  pkg/sql/schema_change_plan_node.go
  pkg/sql/schema_changer.go
  pkg/sql/schema_changer_helpers_test.go
  pkg/sql/schema_changer_test.go
Labels: backport-22.2.x, backport-23.1.x

#107613 kvserver: avoid moving parts in closedts tests
  pkg/kv/kvserver/client_rangefeed_test.go
  pkg/kv/kvserver/closed_timestamp_test.go
  pkg/kv/kvserver/replica_rangefeed_test.go
Labels: db-cy-23

#107645 teamcity-trigger: limit the number of triggers per unit time
  pkg/cmd/teamcity-trigger/main.go
Labels: backport-22.2.x, backport-23.1.x

#107529 roachtest: make upgrade timeouts configurable
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: backport-23.1.x

#107677 ui,build: write typescript declarations to multiple directories in watch mode
  pkg/ui/pnpm-lock.yaml
  pkg/ui/workspaces/cluster-ui/BUILD.bazel
  pkg/ui/workspaces/cluster-ui/build/typescript/watchWithMultipleDests.js
  pkg/ui/workspaces/cluster-ui/build/util/index.js
  pkg/ui/workspaces/cluster-ui/build/webpack/copyEmittedFilesPlugin.js
  pkg/ui/workspaces/cluster-ui/package.json
Labels: backport-23.1.x

#107295 release-22.2: ui: fix Sort dropdown on Latency page in db-console
  pkg/ui/workspaces/db-console/src/app.spec.tsx
  pkg/ui/workspaces/db-console/src/app.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/network/sort/index.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/network/sort/sort.spec.tsx
Labels: O-community

#107832 ui: fix check for config
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts
  pkg/ui/workspaces/cluster-ui/src/store/sessions/sessions.selectors.ts
  pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.selector.ts
Labels: backport-22.2.x

#106314 c2c: prioritize matching src-node pairs with shared localities
  pkg/ccl/streamingccl/streamingest/stream_ingestion_dist.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_dist_test.go
  pkg/sql/distsql_physical_planner.go
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/sqlinstance/sqlinstance.go
Labels: T-disaster-recovery
