Repository cockroachdb/cockroach, pull requests merged in 2023-06, with the labels that each got.

#104153 status: account for gomaxprocs in cpu utilization
  pkg/server/status/runtime.go
Labels: backport-22.2.x, backport-23.1.x

#104187 backupccl: always track opened writer
  pkg/ccl/backupccl/file_sst_sink.go
Labels: backport-22.2.x

#103180 sql: more redactable details about traces in logs
  pkg/base/node_id.go
  pkg/sql/catalog/lease/descriptor_state.go
  pkg/sql/catalog/lease/descriptor_version_state.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_util.go
  pkg/sql/execinfrapb/BUILD.bazel
  pkg/sql/execinfrapb/component_stats.go
  pkg/sql/execinfrapb/component_stats.proto
  pkg/sql/trace_test.go
  pkg/sql/txn_state.go
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
  pkg/util/tracing/span.go
  pkg/util/tracing/tracingpb/recording.go
Labels: backport-22.2.x, backport-23.1.x

#104133 cli: default --include-range-info to true, but create a single file
  pkg/cli/context.go
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/partial1_excluded
  pkg/cli/testdata/zip/partial2
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/testzip_concurrent
  pkg/cli/testdata/zip/testzip_include_range_info
  pkg/cli/testdata/zip/testzip_shared_process_tenant
  pkg/cli/testdata/zip/testzip_tenant_separate_process
  pkg/cli/testdata/zip/unavailable
  pkg/cli/zip_cluster_wide.go
  pkg/cli/zip_helpers.go
  pkg/cli/zip_per_node.go
Labels: backport-23.1.x

#104128 startup: retry pgerror.Code == RangeUnavailable
  pkg/util/startup/BUILD.bazel
  pkg/util/startup/retry.go
Labels: backport-22.2.x, backport-23.1.x

#104226 release-23.1: c2c: reset ingestion job retry counter if retained timestamp advanced
  pkg/ccl/streamingccl/replicationtestutils/BUILD.bazel
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/ccl/streamingccl/replicationutils/BUILD.bazel
  pkg/ccl/streamingccl/replicationutils/utils.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go
  pkg/sql/exec_util.go
Labels: T-disaster-recovery

#104270 server, ui: don't recommend drop index to unique indexes
  docs/generated/http/full.md
  pkg/server/index_usage_stats.go
  pkg/server/serverpb/status.proto
  pkg/sql/idxusage/index_usage_stats_rec.go
  pkg/sql/idxusage/index_usage_stats_rec_test.go
  pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/schemaInsightsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts
Labels: backport-23.1.x

#104277 sql: avoid using shadowed index var to get sequence id
  pkg/sql/catalog/seqexpr/sequence.go
  pkg/sql/logictest/testdata/logic_test/udf
Labels: backport-22.2.x, backport-23.1.x

#104245 backupccl: handle pre-23.1 tenant metadata in backup manifests
  pkg/BUILD.bazel
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/backupinfo/manifest_handling.go
  pkg/ccl/backupccl/backuppb/BUILD.bazel
  pkg/ccl/backupccl/backuppb/backup.go
  pkg/ccl/backupccl/backuppb/backup.proto
  pkg/ccl/backupccl/backuppb/backup_test.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_old_versions_test.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/backupccl/show.go
  pkg/ccl/backupccl/targets.go
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster-with-tenants/v22.2.10/2023/06/02-075329.52/BACKUP-LOCK-870390200839241729
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster-with-tenants/v22.2.10/2023/06/02-075329.52/BACKUP-STATISTICS
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster-with-tenants/v22.2.10/2023/06/02-075329.52/BACKUP_MANIFEST
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster-with-tenants/v22.2.10/2023/06/02-075329.52/BACKUP_MANIFEST-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster-with-tenants/v22.2.10/2023/06/02-075329.52/data/870390202346864641.sst
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster-with-tenants/v22.2.10/2023/06/02-075329.52/progress/BACKUP-CHECKPOINT-13cdcfcdccd2cfc9d2cfcddfcfc8c5caccc5cccfd1cfcecac9c6c7dfd4cfcfcfcfdfaaabbcdf92c2d4c9cfd1c7caccc8c9cbcec6c8fffe
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster-with-tenants/v22.2.10/2023/06/02-075329.52/progress/BACKUP-CHECKPOINT-13cdcfcdccd2cfc9d2cfcddfcfc8c5caccc5cccfd1cfcecac9c6c7dfd4cfcfcfcfdfaaabbcdf92c2d4c9cfd1c7caccc8c9cbcec6c8fffe-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster-with-tenants/v22.2.10/2023/06/02-075329.52/progress/BACKUP-CHECKPOINT-13cdcfcdccd2cfc9d2cfcddfcfc8c5caccc5cdc6d1c8c6c6cec6c8dfd4cfcfcfcfdfaaabbcdf92c2d4c9cfd1c9ccc8cdc9cccecccffffe
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster-with-tenants/v22.2.10/2023/06/02-075329.52/progress/BACKUP-CHECKPOINT-13cdcfcdccd2cfc9d2cfcddfcfc8c5caccc5cdc6d1c8c6c6cec6c8dfd4cfcfcfcfdfaaabbcdf92c2d4c9cfd1c9ccc8cdc9cccecccffffe-CHECKSUM
  pkg/ccl/backupccl/testdata/restore_old_versions/cluster-with-tenants/v22.2.10/metadata/latest/LATEST-13cdcfcdccd2cfc9d2cfcddfcfc8c5caccc5cccfd1cdcccbcccdcedfd4cfcfcfcfdfaaabbcdf92c2d4c9ced1cfc8cdccc7c8cececefffe
  pkg/multitenant/mtinfopb/BUILD.bazel
  pkg/multitenant/mtinfopb/info.go
Labels: backport-23.1.x

#104307 ui: fix Filter dropdown menu on Latency page
  pkg/ui/workspaces/db-console/src/views/reports/containers/network/filter/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/dropdown/index.tsx
Labels: O-community, backport-23.1.x

#104291 kvstreamer: resolve a deadlock in an edge case
  pkg/kv/kvclient/kvstreamer/results_buffer.go
  pkg/kv/kvclient/kvstreamer/streamer.go
Labels: backport-22.2.x, backport-23.1.x

#104281 roachtest: adjust tpch_concurrency a bit
  pkg/cmd/roachtest/tests/tpch_concurrency.go
Labels: backport-23.1.x

#103759 sql: add `sql.log.user_audit.reduced_config.enabled` to support single role checks for role-based audit logs
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/settings/registry.go
  pkg/sql/audit_logging.go
  pkg/sql/audit_logging_test.go
  pkg/sql/auditlogging/audit_log.go
  pkg/sql/auditlogging/audit_log_config.go
  pkg/sql/conn_executor.go
  pkg/sql/planner.go
Labels: release-blocker, branch-release-23.1, backport-23.1.x

#104372 release-23.1: sql: add `sql.log.user_audit.reduced_config.enabled` to support single role checks for role-based audit logs
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/settings/registry.go
  pkg/sql/audit_logging.go
  pkg/sql/audit_logging_test.go
  pkg/sql/auditlogging/audit_log.go
  pkg/sql/auditlogging/audit_log_config.go
  pkg/sql/conn_executor.go
  pkg/sql/planner.go
Labels: release-blocker, branch-release-23.1

#104235 pgwire: add gauge for connections throttled by semaphore
  pkg/security/auth.go
  pkg/security/password.go
  pkg/sql/pgwire/auth.go
  pkg/sql/pgwire/auth_methods.go
  pkg/sql/pgwire/server.go
Labels: backport-22.2.x, backport-23.1.x

#104410 revert flush of buffered log sinks in `log.Flush`
  pkg/util/log/doc.go
  pkg/util/log/log_flush.go
  pkg/util/log/registry.go
Labels: backport-23.1.x

#104433 kvstreamer: fix invalid concurrent calls to disk buffer
  pkg/kv/kvclient/kvstreamer/results_buffer.go
  pkg/kv/kvclient/kvstreamer/streamer.go
Labels: backport-22.2.x, backport-23.1.x

#104294 pgwire: ignore all messages after extended protocol error
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_internal_test.go
  pkg/sql/conn_io.go
  pkg/sql/conn_io_test.go
  pkg/sql/internal.go
  pkg/sql/pgwire/conn.go
  pkg/sql/pgwire/testdata/pgtest/aborted_txn
Labels: backport-22.2.x, backport-23.1.x

#104424 sql: avoid a race condition in `sqlActivityUpdateJob`
  pkg/sql/sql_activity_update_job.go
Labels: backport-23.1.x

#104224 sql: Limit MODIFYSQLCLUSTERSETTING to only view sql.defaults
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/cluster_settings
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/set_cluster_setting.go
Labels: backport-23.1.x

#104543 diagnostics: Fixed a crashing bug when creating diagnostics report
  pkg/server/diagnostics/BUILD.bazel
  pkg/server/diagnostics/reporter.go
  pkg/server/diagnostics/reporter_test.go
Labels: backport-22.2.x, backport-23.1.x

#104428 ui: exclude "Idle" status from active statements view
  pkg/ui/workspaces/cluster-ui/src/activeExecutions/execTableCommon.tsx
  pkg/ui/workspaces/cluster-ui/src/selectors/activeExecutions.selectors.ts
  pkg/ui/workspaces/cluster-ui/src/statementsPage/activeStatementsPage.selectors.ts
  pkg/ui/workspaces/cluster-ui/src/statementsPage/activeStatementsView.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/activeTransactionsPage.selectors.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/activeTransactionsView.tsx
  pkg/ui/workspaces/db-console/src/selectors/activeExecutionsSelectors.ts
  pkg/ui/workspaces/db-console/src/views/statements/activeStatementsSelectors.tsx
  pkg/ui/workspaces/db-console/src/views/transactions/activeTransactionsSelectors.tsx
Labels: backport-22.2.x, backport-23.1.x

#104545 upgrades: batch the job_info backfill upgrade
  pkg/jobs/job_info_storage.go
  pkg/jobs/registry_test.go
  pkg/upgrade/upgrades/BUILD.bazel
  pkg/upgrade/upgrades/backfill_jobs_info_table_migration.go
Labels: backport-23.1.x

#104326 streamingccl: initial async flushing on the consumer
  pkg/ccl/streamingccl/streamingest/BUILD.bazel
  pkg/ccl/streamingccl/streamingest/merged_subscription.go
  pkg/ccl/streamingccl/streamingest/merged_subscription_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go
Labels: backport-23.1.x

#104383 auditloggingccl: migrate role-based audit logging as a CCL feature
  .github/CODEOWNERS
  pkg/BUILD.bazel
  pkg/ccl/BUILD.bazel
  pkg/ccl/auditloggingccl/BUILD.bazel
  pkg/ccl/auditloggingccl/audit_log_config.go
  pkg/ccl/auditloggingccl/audit_logging_test.go
  pkg/ccl/auditloggingccl/main_test.go
  pkg/ccl/ccl_init.go
  pkg/server/server_sql.go
  pkg/sql/BUILD.bazel
  pkg/sql/audit_logging.go
  pkg/sql/auditlogging/BUILD.bazel
  pkg/sql/auditlogging/audit_log.go
  pkg/sql/auditlogging/audit_log_test.go
  pkg/sql/auditlogging/parser.go
  pkg/sql/auditlogging/testdata/parse
Labels: release-blocker, branch-release-23.1

#104453 release-23.1: auditloggingccl: migrate role-based audit logging as a CCL feature
  .github/CODEOWNERS
  pkg/BUILD.bazel
  pkg/ccl/BUILD.bazel
  pkg/ccl/auditloggingccl/BUILD.bazel
  pkg/ccl/auditloggingccl/audit_log_config.go
  pkg/ccl/auditloggingccl/audit_logging_test.go
  pkg/ccl/auditloggingccl/main_test.go
  pkg/ccl/ccl_init.go
  pkg/server/server_sql.go
  pkg/sql/BUILD.bazel
  pkg/sql/audit_logging.go
  pkg/sql/auditlogging/BUILD.bazel
  pkg/sql/auditlogging/audit_log.go
  pkg/sql/auditlogging/audit_log_test.go
  pkg/sql/auditlogging/parser.go
  pkg/sql/auditlogging/testdata/parse
Labels: release-blocker, branch-release-23.1

#104119 sql: SHOW GRANTS includes inherited roles
  pkg/bench/rttanalysis/grant_revoke_role_bench_test.go
  pkg/bench/rttanalysis/testdata/benchmark_expectations
  pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant
  pkg/cli/zip_test.go
  pkg/sql/crdb_internal.go
  pkg/sql/delegate/show_grants.go
  pkg/sql/delegate/show_role_grants.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/logictest/testdata/logic_test/grant_inherited
  pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option
  pkg/sql/logictest/testdata/logic_test/grant_schema
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/mixed_version_role_members_user_ids
  pkg/sql/logictest/testdata/logic_test/pg_builtins
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/role
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/exec/execbuilder/testdata/virtual
  pkg/sql/opt/xform/testdata/external/activerecord
  pkg/sql/sem/catconstants/constants.go
Labels: O-community, backport-22.2.x, backport-23.1.x

#104512 upgrade: improve delete dropped udf upgrade job efficiency
  pkg/upgrade/upgrades/delete_descriptors_of_dropped_functions.go
Labels: backport-23.1.x

#104450 logictest: deflake guardrails
  pkg/sql/logictest/testdata/logic_test/guardrails
Labels: backport-22.2.x, backport-23.1.x

#104565 sql: delegate SHOW SYSTEM GRANTS to new crdb_internal.system_privileges vtable
  pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/partial1_excluded
  pkg/cli/testdata/zip/partial2
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/testzip_concurrent
  pkg/cli/testdata/zip/testzip_include_range_info
  pkg/cli/testdata/zip/testzip_shared_process_tenant
  pkg/cli/testdata/zip/testzip_tenant_separate_process
  pkg/cli/testdata/zip/unavailable
  pkg/cli/zip_table_registry.go
  pkg/sql/crdb_internal.go
  pkg/sql/delegate/show_grants.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_builtins
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_grants_synthetic
  pkg/sql/logictest/testdata/logic_test/table
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/xform/testdata/external/activerecord
  pkg/sql/sem/catconstants/constants.go
Labels: backport-22.2.x, backport-23.1.x

#104601 upgrademanager: deflake TestConcurrentMigrationAttempts
  pkg/upgrade/upgrademanager/BUILD.bazel
  pkg/upgrade/upgrademanager/manager_external_test.go
Labels: backport-23.1.x

#102953 kvserverpb: mark probe requests' replicated cmds as IsTrivial
  pkg/kv/kvserver/kvserverpb/proposer_kv.go
Labels: backport-22.2.x, backport-23.1.x

#104635 democluster: deflake TestTransientClusterSimulateLatencies
  pkg/cli/BUILD.bazel
  pkg/cli/demo_locality_test.go
  pkg/cli/democluster/demo_cluster.go
  pkg/cli/democluster/demo_cluster_test.go
Labels: backport-23.1.x

#104595 upgrades: Zero out CompositeColumnIDs when comparing two indexes
  pkg/upgrade/upgrades/schema_changes.go
Labels: backport-22.2.x, backport-23.1.x

#104419 roachtest: upgrade GCE to n2 and AWS to m6id and c6id
  pkg/BUILD.bazel
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/spec/machine_type.go
  pkg/roachprod/vm/aws/aws.go
  pkg/roachprod/vm/gce/BUILD.bazel
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/gce/gcloud_test.go
Labels: backport-22.2.x, backport-23.1.x

#104497 cli/sql: fix virtual cluster switch via `\c` under `options=-ccluster`
  pkg/acceptance/generated_cli_test.go
  pkg/cli/clisqlshell/sql.go
  pkg/cli/interactive_tests/test_demo_cli_integration.tcl
  pkg/server/pgurl/extended_options.go
  pkg/server/pgurl/pgurl_test.go
Labels: A-multitenancy, backport-23.1.x

#104727 cluster-ui: increase payload size when retrieving statement diagnostics
  pkg/ui/workspaces/cluster-ui/src/api/statementDiagnosticsApi.ts
Labels: backport-23.1.x

#104670 ui: fix columns selector being cut
  pkg/ui/workspaces/cluster-ui/src/jobs/jobs.module.scss
Labels: backport-22.2.x, backport-23.1.x

#104219 c2c: allow user to pass start time as a decimal to crdb_internal.fingerprint()
  docs/generated/sql/functions.md
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fingerprint_builtin_test.go
  pkg/sql/sem/builtins/fingerprint_builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
Labels: T-disaster-recovery

#104768 testutils: skip TestRestart
  pkg/testutils/testcluster/BUILD.bazel
  pkg/testutils/testcluster/testcluster_test.go
Labels: T-testeng

#104766 loqrecovery: check meta range completeness before usage
  pkg/kv/kvserver/loqrecovery/plan.go
  pkg/kv/kvserver/loqrecovery/recovery_env_test.go
  pkg/kv/kvserver/loqrecovery/testdata/ignore_partial_meta
Labels: backport-23.1.x

#104622 ui: hide tenant dropdown when unneeded
  pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.spec.tsx
  pkg/ui/workspaces/db-console/src/views/app/components/tenantDropdown/tenantDropdown.tsx
Labels: backport-23.1.x

#104688 ui: show alert on DB Console overview when upgrade is not finalized
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/clusterSettings/clusterSettings.selectors.ts
  pkg/ui/workspaces/db-console/src/redux/nodes.spec.ts
  pkg/ui/workspaces/db-console/src/redux/nodes.ts
Labels: backport-22.2.x, backport-23.1.x

#104813 scrun: don't include plan details for pgerrors
  pkg/sql/logictest/testdata/logic_test/hash_sharded_index
  pkg/sql/schemachanger/scerrors/errors.go
  pkg/sql/schemachanger/scrun/scrun.go
Labels: backport-22.2.x, backport-23.1.x

#104908 ui: adjust labels for SQL Connection Rate chart
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/sql.tsx
Labels: backport-22.2.x, backport-23.1.x

#104913 schemafeed: Fix initialization race in schema feed fast path
  pkg/ccl/changefeedccl/schemafeed/schema_feed.go
Labels: backport-23.1.x

#104920 sql: refrain from performing invalid splits during tenant creation
  pkg/keys/sql.go
  pkg/rpc/auth_tenant.go
  pkg/sql/catalog/bootstrap/BUILD.bazel
  pkg/sql/catalog/bootstrap/bootstrap_test.go
  pkg/sql/catalog/bootstrap/main_test.go
  pkg/sql/catalog/bootstrap/metadata.go
  pkg/sql/catalog/bootstrap/splits_test.go
  pkg/sql/tenant_creation.go
Labels: backport-23.1.x

#104320 kvserver: add metric for Raft leader removals
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica_application_result.go
Labels: backport-22.2.x, backport-23.1.x

#104885 roachtest: reduce rebalance-by-load noise
  pkg/cmd/roachtest/tests/rebalance_load.go
Labels: backport-22.2.x, backport-23.1.x

#104981 ui: fix job details refresh when executing job
  pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobDetails.tsx
Labels: backport-22.2.x, backport-23.1.x

#104998 ui: add learn more to alert
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/index.tsx
Labels: backport-22.2.x, backport-23.1.x

#104924 opt: fix ambiguous column error for computed column expressions
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/opt/optbuilder/project.go
  pkg/sql/opt/optbuilder/testdata/upsert
Labels: backport-22.2.x, backport-23.1.x

#105014 roachtest: revert skipping cdc tests locally on arm64
  pkg/cmd/roachtest/tests/cdc.go
Labels: backport-22.2.x, backport-23.1.x

#104896 cli: capture logs from demo tests
  pkg/cli/BUILD.bazel
  pkg/cli/demo_locality_test.go
  pkg/cli/demo_test.go
  pkg/cli/testdata/demo/test_demo
  pkg/cli/testdata/demo/test_demo_locality
Labels: backport-23.1.x

#105036 roachtest: skip some local tests on ARM64
  pkg/cmd/roachtest/registry/registry_interface.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/tests/cdc.go
Labels: C-bug, A-testing, T-testeng, backport-22.2.x, backport-23.1.x

#105015 ui: update latency info tooltips
  pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx
Labels: backport-23.1.x

#105016 server: add missing sort option
  pkg/server/combined_statement_stats.go
Labels: backport-23.1.x

#105051 ui: add more precision to small percentages
  pkg/ui/workspaces/cluster-ui/src/barCharts/barCharts.tsx
  pkg/ui/workspaces/cluster-ui/src/util/format.spec.ts
  pkg/ui/workspaces/cluster-ui/src/util/format.ts
Labels: backport-22.2.x, backport-23.1.x

#105147 ui: fix crash on `DurationToNumber`
  pkg/ui/workspaces/cluster-ui/src/util/convert.ts
Labels: backport-22.2.x, backport-23.1.x

#105117 sql/parser: improve the inline help text for ALTER TENANT
  pkg/sql/parser/help_test.go
  pkg/sql/parser/sql.y
Labels: A-multitenancy, backport-23.1.x

#104345 telemetry: add cluster setting to include internal queries
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/exec_log.go
  pkg/sql/telemetry_logging.go
  pkg/sql/telemetry_logging_test.go
Labels: backport-23.1.x

#105223 roachtest: prevent post-test connection error for rust-postgres
  pkg/cmd/roachtest/tests/rust_postgres.go
Labels: backport-23.1.x

#105234 roachprod: add aws AZ override for c6id.24xlarge
  pkg/roachprod/vm/aws/aws.go
Labels: backport-22.2.x, backport-23.1.x

#105237 logictest: unify updating SQL testing knobs in logic tests
  pkg/sql/logictest/BUILD.bazel
  pkg/sql/logictest/logic.go
Labels: backport-23.1.x

#105224 roachtest: relax tpch_concurrency a bit
  pkg/cmd/roachtest/tests/tpch_concurrency.go
Labels: backport-23.1.x

#105233 sql: fix COPY when it accesses TxnTimestamp
  pkg/sql/copy_file_upload.go
  pkg/sql/copy_from.go
  pkg/sql/pgwire/testdata/pgtest/copy
Labels: backport-23.1.x

#105324 sql: fix CTAS when selecting from some internal virtual tables
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/create_table
  pkg/sql/planner.go
Labels: backport-22.2.x, backport-23.1.x

#105344 ci: remove old stuff from agent image
  build/packer/teamcity-agent.sh
Labels: C-enhancement, T-dev-inf, A-ci

#105390 ci: allow apt background update to finish before updating packages
  build/packer/teamcity-agent.sh
Labels: C-bug, T-dev-inf, A-ci

#105394 build: add google-cloud-cli-gke-gcloud-auth-plugin to builder image
  build/builder.sh
  build/builder/Dockerfile
Labels: C-enhancement, T-dev-inf, A-ci

#105392 util/mon: fix deadlock
  pkg/util/mon/bytes_usage.go
Labels: backport-22.2.x, backport-23.1.x

#104449 sql: add default_value and origin to show cluster settings
  pkg/ccl/logictestccl/testdata/logic_test/crdb_internal_tenant
  pkg/server/settings_test.go
  pkg/server/settingswatcher/settings_watcher.go
  pkg/settings/common.go
  pkg/settings/setting.go
  pkg/settings/updater.go
  pkg/settings/values.go
  pkg/sql/crdb_internal.go
  pkg/sql/delegate/show_all_cluster_settings.go
  pkg/sql/logictest/testdata/logic_test/cluster_settings
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
Labels: backport-23.1.x

#104897 sql: add system privileges to crdb_internal queries tables
  pkg/sql/authorization.go
  pkg/sql/crdb_internal.go
  pkg/sql/show_test.go
Labels: backport-22.2.x, backport-23.1.x

#105463 packer: fix go symlinks
  build/packer/teamcity-agent.sh
Labels: C-bug, T-dev-inf, A-ci

#105364 stats: automatically delete stats for dropped tables
  pkg/sql/stats/BUILD.bazel
  pkg/sql/stats/automatic_stats.go
  pkg/sql/stats/delete_stats.go
  pkg/sql/stats/delete_stats_dropped_table_test.go
Labels: backport-22.2.x, backport-23.1.x

#105108 sql: add telemetry for schema changer mode
  docs/generated/eventlog.md
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/sql/exec_log.go
  pkg/sql/instrumentation.go
  pkg/sql/logictest/testdata/logic_test/event_log
  pkg/sql/logictest/testdata/logic_test/event_log_legacy
  pkg/sql/logictest/testdata/logic_test/schema_change_feature_flags
  pkg/sql/plan_opt.go
  pkg/sql/schema_change_plan_node.go
  pkg/sql/schema_changer.go
  pkg/sql/sem/tree/stmt.go
  pkg/sql/sqltelemetry/schema.go
  pkg/sql/testdata/telemetry/schema
  pkg/util/log/eventpb/json_encode_generated.go
  pkg/util/log/eventpb/telemetry.proto
Labels: backport-22.2.x, backport-23.1.x

#105465 tree,optbuilder: store annotations for each UDF body statement
  pkg/sql/function_resolver_test.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/opt/optbuilder/create_function.go
  pkg/sql/opt/optbuilder/testdata/create_function
  pkg/sql/schemachanger/scbuild/builder_state.go
  pkg/sql/sem/tree/udf.go
Labels: backport-22.2.x, backport-23.1.x

#104857 sql/stats: better sentry report for NumRange=0 assertion failure
  pkg/sql/show_stats.go
  pkg/sql/stats/BUILD.bazel
  pkg/sql/stats/forecast.go
  pkg/sql/stats/forecast_test.go
  pkg/sql/stats/stats_cache.go
Labels: backport-22.2.x, backport-23.1.x

#105588 ccl/sqlproxyccl: fix TestACLWatcher flake
  pkg/ccl/sqlproxyccl/acl/watcher_test.go
  pkg/ccl/sqlproxyccl/tenantdirsvr/test_static_directory_svr.go
Labels: backport-23.1.x

#105566 kvtenant,settingswatcher: ensure overrides are applied during start
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/kv/kvclient/kvtenant/connector_test.go
  pkg/kv/kvclient/kvtenant/setting_overrides.go
  pkg/kv/kvclient/kvtenant/setting_overrides_test.go
  pkg/kv/kvpb/api.go
  pkg/kv/kvpb/api.proto
  pkg/server/node.go
  pkg/server/settingswatcher/overrides.go
  pkg/server/settingswatcher/settings_watcher.go
  pkg/server/settingswatcher/settings_watcher_external_test.go
Labels: backport-23.1.x

#105629 server: unskip TestStatusEngineStatsJson
  pkg/server/status_test.go
Labels: backport-23.1.x

#105609 sql: convenience syntax ALTER TENANT GRANT/REVOKE ALL CAPABILITIES
  pkg/ccl/logictestccl/testdata/logic_test/tenant_capability
  pkg/configprofiles/profiles.go
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/alter_tenant
  pkg/sql/sem/tree/alter_tenant.go
  pkg/sql/tenant_capability.go
Labels: A-multitenancy, backport-23.1.x

#105571 roachtest: deflake backupFixture/tpce/15GB/aws
  pkg/cmd/roachtest/tests/backup_fixtures.go
Labels: T-disaster-recovery

#105674 opt/xform: increase timeout of xform_test
  pkg/sql/opt/xform/BUILD.bazel
Labels: backport-22.2.x, backport-23.1.x

#105648 backupccl: schedule test appears flaky around midnight
  pkg/ccl/backupccl/schedule_pts_chaining_test.go
Labels: backport-23.1.x

#105530 builtins: Implement ST_AsMVTGeom sql function
  docs/generated/sql/functions.md
  pkg/geo/geomfn/BUILD.bazel
  pkg/geo/geomfn/mvtgeom.go
  pkg/geo/geomfn/mvtgeom_test.go
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/opt/xform/coster.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community

#105533 sql: enable TestDropTableDeleteData test
  pkg/sql/drop_test.go
  pkg/sql/tests/BUILD.bazel
  pkg/sql/tests/data.go
Labels: backport-23.1.x

#105681 roachtest: move awsdms test ownership to migrations
  TEAMS.yaml
  pkg/cmd/roachtest/registry/owners.go
  pkg/cmd/roachtest/tests/awsdms.go
Labels: backport-22.1.x, backport-22.2.x, backport-23.1.x

#105745 sql/importer: remove unused skip.WithIssue from TestImportData
  pkg/sql/importer/import_stmt_test.go
Labels: backport-22.2.x, backport-23.1.x

#105677 roachtest: skip c2c/BulkOps and add the new c2c/BulkOps/SingleImport
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: T-disaster-recovery

#105653 roachtest: remove interleaved tpcc config that was being skipped
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/tpcc.go
Labels: backport-22.2.x, backport-23.1.x

#105788 ci: install Azure CLI
  build/.bazelbuilderversion
  build/.bazelbuilderversion-fips
  build/bazelbuilder/Dockerfile
  build/builder.sh
  build/builder/Dockerfile
  build/packer/teamcity-agent.sh
Labels: C-enhancement, T-dev-inf, A-ci

#105766 auditloggingccl: fix TestRoleBasedAuditEnterpriseGated
  pkg/ccl/auditloggingccl/audit_logging_test.go
Labels: backport-23.1.x

#105789 geo: fix nan handling in bounding box comparison
  pkg/geo/bbox.go
  pkg/geo/bbox_test.go
  pkg/sql/logictest/testdata/logic_test/geospatial_bbox
Labels: backport-22.2.x, backport-23.1.x

#105842 sqlproxyccl: deflake TestResume
  pkg/ccl/sqlproxyccl/tenant/directory_cache_test.go
Labels: A-multiregion, backport-23.1.x

#105816 kvserver: propagate `ReplicaUnavailableError` from intent resolution
  pkg/kv/kvserver/client_replica_circuit_breaker_test.go
  pkg/kv/kvserver/replica_send.go
Labels: backport-22.2.x, backport-23.1.x

#105376 c2c: checkpoint cutover progress
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go
  pkg/jobs/jobspb/jobs.proto
  pkg/sql/exec_util.go
Labels: T-disaster-recovery

#105610 kvserver: deflake `TestLeaderAfterSplit`
  pkg/kv/kvserver/client_split_test.go
Labels: backport-22.2.x, backport-23.1.x

#105892 sql: initialize job collection for internal planner
  pkg/sql/logictest/testdata/logic_test/create_as
  pkg/sql/planner.go
Labels: backport-23.1.x

#105917 persistedsqlstats: de-flake TestSQLStatsPersistedLimitReached
  pkg/sql/sqlstats/persistedsqlstats/flush_test.go
Labels: backport-23.1.x
