Repository cockroachdb/cockroach, pull requests merged in 2023-01, with the labels that each got.

#94618 cli: fix references to `kvadmission.store.provisioned_bandwidth`
  pkg/base/store_spec.go
  pkg/cli/cliflags/flags.go
Labels: backport-22.2.x

#93449 backupccl: add tpcc cluster replication roachtest
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: T-disaster-recovery

#94677 sql: cleanup independent error messages for missing users
  pkg/cli/interactive_tests/test_password.tcl
  pkg/sql/alter_role.go
  pkg/sql/authorization.go
  pkg/sql/create_schema.go
  pkg/sql/delegate/BUILD.bazel
  pkg/sql/delegate/show_grants.go
  pkg/sql/drop_role.go
  pkg/sql/grant_revoke.go
  pkg/sql/grant_role.go
  pkg/sql/logictest/testdata/logic_test/alter_default_privileges_for_table
  pkg/sql/logictest/testdata/logic_test/alter_default_privileges_with_grant_option
  pkg/sql/logictest/testdata/logic_test/alter_role_set
  pkg/sql/logictest/testdata/logic_test/drop_user
  pkg/sql/logictest/testdata/logic_test/grant_database
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/role
  pkg/sql/logictest/testdata/logic_test/schema
  pkg/sql/logictest/testdata/logic_test/user
  pkg/sql/reassign_owned_by.go
  pkg/sql/revoke_role.go
  pkg/sql/sqlerrors/BUILD.bazel
  pkg/sql/sqlerrors/errors.go
Labels: backport-22.2.x

#94622 release: save local copy of archives
  build/teamcity/internal/release/process/publish-cockroach-release.sh
  pkg/cmd/publish-provisional-artifacts/main.go
  pkg/release/upload.go
Labels: C-enhancement, A-release, T-release, backport-22.1.x, backport-22.2.x

#94851 build,release: rename ARM64 binaries and archives
  build/release/teamcity-support.sh
  build/teamcity/internal/cockroach/release/publish/sign_macos_release.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts.sh
  build/teamcity/internal/release/process/publish-cockroach-release.sh
  pkg/cmd/publish-artifacts/main_test.go
  pkg/cmd/publish-provisional-artifacts/main_test.go
  pkg/release/build.go
  pkg/release/upload.go
Labels: C-enhancement, A-release, T-release, backport-22.2.x

#94143 backupccl: introduce new restore roachtest framework
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#94651 c2c: log roachtest throughput metrics during initial scan and cutover
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: T-disaster-recovery

#92580 server,pgwire: use a single SQL listener for multiple tenants
  docs/generated/settings/settings.html
  pkg/bench/BUILD.bazel
  pkg/bench/foreachdb.go
  pkg/ccl/serverccl/server_controller_test.go
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/cli/democluster/demo_cluster.go
  pkg/cli/democluster/demo_cluster_test.go
  pkg/cli/democluster/session_persistence.go
  pkg/cli/interactive_tests/test_copy.tcl
  pkg/cli/interactive_tests/test_demo.tcl
  pkg/cli/interactive_tests/test_demo_cli_integration.tcl
  pkg/cli/interactive_tests/test_demo_multitenant.tcl
  pkg/cli/interactive_tests/test_demo_networking.tcl
  pkg/cli/interactive_tests/test_demo_node_cmds.tcl
  pkg/server/api_v2_auth.go
  pkg/server/authentication.go
  pkg/server/authentication_test.go
  pkg/server/config.go
  pkg/server/server.go
  pkg/server/server_controller.go
  pkg/server/server_sql.go
  pkg/server/start_listen.go
  pkg/server/status.go
  pkg/server/tenant.go
  pkg/server/testserver.go
  pkg/sql/pgwire/BUILD.bazel
  pkg/sql/pgwire/auth_test.go
  pkg/sql/pgwire/conn.go
  pkg/sql/pgwire/conn_test.go
  pkg/sql/pgwire/pgwire_test.go
  pkg/sql/pgwire/pgwirecancel/BUILD.bazel
  pkg/sql/pgwire/pgwirecancel/cancel_semaphore.go
  pkg/sql/pgwire/pre_serve.go
  pkg/sql/pgwire/pre_serve_options.go
  pkg/sql/pgwire/server.go
  pkg/ts/catalog/chart_catalog.go
  pkg/util/mon/bytes_usage.go
Labels: A-multitenancy

#89970 cloud: buffer and put uploader for azure
  pkg/ccl/backupccl/backup_cloud_test.go
  pkg/cloud/azure/azure_storage.go
Labels: backport-22.1.x, backport-22.2.x

#94776 roachtest: fix ruby-pg test
  pkg/cmd/roachtest/tests/ruby_pg.go
Labels: backport-22.2.x

#94954 kv/server: skip a bunch of flakey tests
  pkg/kv/kvserver/client_split_test.go
  pkg/kv/kvserver/replica_learner_test.go
  pkg/sql/logictest/testdata/logic_test/testserver_test_22.1_22.2
  pkg/sql/logictest/testdata/logic_test/testserver_upgrade_node
Labels: C-test-failure

#92596 ui: fix polling for statement and transaction details pages
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.selectors.ts
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts
  pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.reducer.ts
  pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.sagas.spec.ts
  pkg/ui/workspaces/cluster-ui/src/store/statementDetails/statementDetails.sagas.ts
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetailsConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx
  pkg/ui/workspaces/db-console/src/redux/apiReducers.ts
  pkg/ui/workspaces/db-console/src/views/statements/statementDetails.tsx
  pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx
Labels: backport-22.1.x, backport-22.2.x

#94928 codeowners: mark `pkg/sql/sqlstats` as owned by SQL O11y
  .github/CODEOWNERS
Labels: backport-22.2.x

#94739 backupccl: add link to privilege docs
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/backupccl/testdata/backup-restore/backup-permissions
  pkg/ccl/backupccl/testdata/backup-restore/backup-permissions-deprecated
  pkg/ccl/backupccl/testdata/backup-restore/drop-schedule-backup
  pkg/ccl/backupccl/testdata/backup-restore/external-connections-privileges
  pkg/ccl/backupccl/testdata/backup-restore/restore-grants
  pkg/ccl/backupccl/testdata/backup-restore/restore-permissions
  pkg/ccl/backupccl/testdata/backup-restore/restore-permissions-deprecated
  pkg/ccl/backupccl/testdata/backup-restore/schedule-privileges
Labels: backport-22.2.x

#94866 sql/stats: fix a few small bugs in histogram.adjustCounts
  pkg/sql/opt/exec/execbuilder/testdata/forecast
  pkg/sql/opt/exec/execbuilder/testdata/forecast1401
  pkg/sql/opt/exec/execbuilder/testdata/partial_stats
  pkg/sql/stats/forecast.go
  pkg/sql/stats/forecast_test.go
  pkg/sql/stats/histogram.go
  pkg/sql/stats/histogram_test.go
  pkg/sql/stats/quantile_test.go
  pkg/sql/stats/stats_cache.go
Labels: backport-22.2.x

#94949 sql: propagate the settings properly into the stmt bundle builder
  pkg/sql/explain_bundle.go
  pkg/sql/instrumentation.go
  pkg/sql/opt_exec_factory.go
Labels: backport-22.2.x

#94974 tree: improve type-checking of ParenExprs
  pkg/sql/logictest/testdata/logic_test/collatedstring
  pkg/sql/logictest/testdata/logic_test/tuple
  pkg/sql/sem/tree/type_check.go
Labels: backport-22.1.x, backport-22.2.x

#94764 storage: Refactor resolve write intent options
  pkg/kv/kvserver/batch_spanset_test.go
  pkg/kv/kvserver/batcheval/cmd_end_transaction.go
  pkg/kv/kvserver/batcheval/cmd_refresh_range_test.go
  pkg/kv/kvserver/batcheval/cmd_refresh_test.go
  pkg/kv/kvserver/batcheval/cmd_resolve_intent.go
  pkg/kv/kvserver/batcheval/cmd_resolve_intent_range.go
  pkg/kv/kvserver/gc/gc_random_test.go
  pkg/kv/kvserver/loqrecovery/apply.go
  pkg/storage/bench_data_test.go
  pkg/storage/bench_test.go
  pkg/storage/metamorphic/operations.go
  pkg/storage/mvcc.go
  pkg/storage/mvcc_history_test.go
  pkg/storage/mvcc_incremental_iterator_test.go
  pkg/storage/mvcc_logical_ops_test.go
  pkg/storage/mvcc_stats_test.go
  pkg/storage/mvcc_test.go
Labels: O-community, X-blathers-triaged

#94938 sql: add telemetry for non-atomic copy usage
  pkg/sql/conn_executor.go
  pkg/sql/exec_util.go
  pkg/ts/catalog/chart_catalog.go
Labels: backport-22.2.x

#94803 ui: update transaction insight details SQL query to not select from crdb_internal.ranges
  pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts
Labels: backport-22.2.x

#94921 c2c: fix roachtest typo
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: T-disaster-recovery

#94963 backupccl: change restore/tpce roachtest names and run tests on aws
  build/teamcity/util/roachtest_util.sh
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#94860 import: add logging to import cancellation
  pkg/cmd/roachtest/tests/backup.go
  pkg/sql/gcjob/table_garbage_collection.go
  pkg/sql/importer/import_job.go
  pkg/sql/revert.go
Labels: T-disaster-recovery, backport-22.2.x

#95012 authors: add Shivs11 to authors
  AUTHORS
Labels: O-community, X-blathers-untriaged

#94814 storage: Add support for TargetBytes for resolve intent + range cmd
  pkg/kv/kvserver/batcheval/cmd_resolve_intent.go
  pkg/kv/kvserver/batcheval/cmd_resolve_intent_range.go
  pkg/kv/kvserver/batcheval/cmd_resolve_intent_test.go
  pkg/kv/kvserver/spanset/batch.go
  pkg/roachpb/api.proto
  pkg/storage/engine.go
  pkg/storage/mvcc.go
  pkg/storage/mvcc_history_test.go
  pkg/storage/pebble.go
  pkg/storage/pebble_batch.go
  pkg/storage/sst_writer.go
  pkg/storage/testdata/mvcc_histories/resolve_intent_pagination
Labels: O-community, X-blathers-triaged

#94698 storage: Refactor pagination for the Get command into the MVCC layer
  pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go
  pkg/kv/kvserver/batcheval/cmd_end_transaction_test.go
  pkg/kv/kvserver/batcheval/cmd_get.go
  pkg/kv/kvserver/batcheval/cmd_refresh.go
  pkg/kv/kvserver/batcheval/cmd_refresh_range_test.go
  pkg/kv/kvserver/batcheval/cmd_resolve_intent_test.go
  pkg/kv/kvserver/batcheval/cmd_subsume.go
  pkg/kv/kvserver/batcheval/intent.go
  pkg/kv/kvserver/client_merge_test.go
  pkg/kv/kvserver/client_replica_test.go
  pkg/kv/kvserver/client_split_test.go
  pkg/kv/kvserver/loqrecovery/apply.go
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_rangefeed.go
  pkg/server/node_tombstone_storage.go
  pkg/storage/bench_test.go
  pkg/storage/engine_test.go
  pkg/storage/metamorphic/operations.go
  pkg/storage/mvcc.go
  pkg/storage/mvcc_history_test.go
  pkg/storage/mvcc_test.go
  pkg/storage/testdata/mvcc_histories/get_pagination
  pkg/testutils/testcluster/testcluster.go
Labels: O-community

#94791 norm: inline constants only when type of column to replace is equivalent
  pkg/sql/opt/norm/inline_funcs.go
  pkg/sql/opt/xform/testdata/rules/select
Labels: backport-22.2.x

#95038 sql: add more copy error logging
  pkg/sql/conn_executor.go
  pkg/sql/copy_in_test.go
Labels: backport-22.1.x, backport-22.2.x

#94946 norm: fix folding binary and comparison operators with NULLs
  pkg/sql/opt/exec/execbuilder/testdata/scalar
  pkg/sql/opt/norm/fold_constants_funcs.go
  pkg/sql/opt/norm/rules/comp.opt
  pkg/sql/opt/norm/testdata/rules/bool
  pkg/sql/opt/norm/testdata/rules/comp
Labels: backport-22.1.x, backport-22.2.x

#90618 server, tenant: add tenantHotRanges api
  docs/generated/http/full.md
  docs/generated/http/hotranges-request.md
  pkg/ccl/kvccl/kvtenantccl/connector.go
  pkg/ccl/serverccl/statusccl/BUILD.bazel
  pkg/ccl/serverccl/statusccl/tenant_status_test.go
  pkg/rpc/auth_tenant.go
  pkg/server/serverpb/status.go
  pkg/server/serverpb/status.proto
  pkg/server/status.go
Labels: O-community

#95271 ui: proper call of sql user for CC
  pkg/ui/workspaces/cluster-ui/src/api/userApi.ts
  pkg/ui/workspaces/cluster-ui/src/store/sagas.ts
  pkg/ui/workspaces/cluster-ui/src/store/uiConfig/index.ts
  pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts
  pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.sagas.ts
  pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.selector.ts
Labels: backport-22.1.x, backport-22.2.x

#95287 server: add viewactivityredacted permission
  pkg/server/index_usage_stats.go
Labels: backport-22.2.x

#95303 ui: hide reset options for non-admins
  pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.stories.tsx
  pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePage.tsx
  pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetails.selectors.ts
  pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsConnected.ts
  pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.stories.tsx
  pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPageConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.reducer.ts
  pkg/ui/workspaces/cluster-ui/src/store/uiConfig/uiConfig.selector.ts
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.stories.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx
  pkg/ui/workspaces/db-console/src/redux/user/userSagas.ts
  pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.ts
  pkg/ui/workspaces/db-console/src/views/databases/indexDetailsPage/redux.ts
  pkg/ui/workspaces/db-console/src/views/statements/statementsPage.tsx
Labels: backport-22.2.x

#95323 streamingccl: display fraction progressed when cutting over
  pkg/ccl/streamingccl/streamingest/BUILD.bazel
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go
  pkg/sql/backfill.go
  pkg/sql/exec_util.go
  pkg/sql/job_exec_context_test_util.go
Labels: T-disaster-recovery

#95275 sql: add retries on COPY under certain conditions
  pkg/sql/conn_executor.go
  pkg/sql/copy.go
  pkg/sql/copy_in_test.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-22.1.x, backport-22.2.x

#94705 sql/pgwire: support for decoding JSON[] OID by aliasing to JSONB[] OID
  pkg/sql/conn_executor_prepare.go
  pkg/sql/logictest/testdata/logic_test/json
  pkg/sql/pgwire/conn.go
  pkg/sql/pgwire/pgwirebase/encoding.go
  pkg/sql/pgwire/testdata/pgtest/json
  pkg/sql/pgwire/testdata/pgtest/json_array
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/tree/pgwire_encode.go
  pkg/sql/session_state.go
  pkg/sql/types/oid.go
  pkg/sql/types/types.go
Labels: backport-22.2.x

#95532 sql: standardize column names in SHOW GRANTS
  pkg/sql/delegate/show_grants.go
  pkg/sql/logictest/testdata/logic_test/external_connection_privileges
  pkg/sql/logictest/testdata/logic_test/show_grants_synthetic
Labels: backport-22.2.x

#95592 workflow: backport cluster-ui autopublishing
  .github/workflows/cluster-ui-release.yml
Labels: A-ci, T-crux

#95600 workflow: backporting cluster-ui autopublishing
  .github/workflows/cluster-ui-release.yml
Labels: A-ci, T-crux

#95674 sql: assorted fixes for bugs found via TestRandomSyntaxGeneration
  pkg/ccl/logictestccl/testdata/logic_test/tenant
  pkg/sql/parser/testdata/alter_tenant
  pkg/sql/parser/testdata/backup_restore
  pkg/sql/sem/tree/alter_tenant.go
  pkg/sql/sem/tree/walk.go
Labels: A-multitenancy

#95894 sql: correctly handle COLLATEd columns in COPY
  pkg/jobs/registry_external_test.go
  pkg/sql/copy_in_test.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/eval/context.go
  pkg/sql/sem/tree/constant.go
  pkg/sql/sem/tree/datum.go
  pkg/sql/sem/tree/datum_integration_test.go
  pkg/sql/sem/tree/fuzz.go
  pkg/sql/sem/tree/parse_array.go
  pkg/sql/sem/tree/parse_array_test.go
  pkg/sql/sem/tree/parse_string.go
  pkg/sql/sem/tree/parse_tuple.go
  pkg/sql/user.go
Labels: backport-22.1.x, backport-22.2.x

#96023 multiregion: skip TestColdStartLatency
  pkg/ccl/multiregionccl/cold_start_latency_test.go
Labels: skipped-test

#96001 sql/logictest: fix flaky test in unique
  pkg/sql/logictest/testdata/logic_test/unique
Labels: backport-22.1.x, backport-22.2.x

#95851 kvcoord: Increment catchup counter prior to blocking
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
Labels: backport-22.2.x

#95658 server: only run tenants with service mode 'shared'
  .github/CODEOWNERS
  docs/generated/eventlog.md
  pkg/bench/foreachdb.go
  pkg/ccl/serverccl/admin_test.go
  pkg/ccl/serverccl/server_controller_test.go
  pkg/server/BUILD.bazel
  pkg/server/admin.go
  pkg/server/node.go
  pkg/server/server.go
  pkg/server/server_controller.go
  pkg/server/server_controller_accessors.go
  pkg/server/server_controller_http.go
  pkg/server/server_controller_new_server.go
  pkg/server/server_controller_orchestration.go
  pkg/server/server_controller_sql.go
  pkg/server/server_controller_test.go
  pkg/server/testserver.go
  pkg/util/log/eventpb/cluster_events.proto
  pkg/util/log/eventpb/eventlog_channels_generated.go
  pkg/util/log/eventpb/json_encode_generated.go
Labels: A-multitenancy

#96143 bench: adjust the secondary tenant initialization
  pkg/bench/foreachdb.go
Labels: A-multitenancy

#96161 ccl/sqlproxyccl: fix possible NPE within the connector
  pkg/ccl/sqlproxyccl/connector.go
  pkg/ccl/sqlproxyccl/connector_test.go
Labels: backport-22.2.x

#96168 server: sanitize the behavior of runtime stats sampling / dumps for secondary tenants
  pkg/ccl/serverccl/tenant_vars_test.go
  pkg/server/config.go
  pkg/server/server.go
  pkg/server/server_controller_new_server.go
  pkg/server/tenant.go
Labels: A-multitenancy

#96268 server: remove possible causes of deadlocks
  pkg/ccl/kvccl/kvtenantccl/connector.go
  pkg/server/server_controller_new_server.go
  pkg/server/server_controller_orchestration.go
  pkg/server/start_listen.go
Labels: A-multitenancy

#96159 roachtest/tpcc: retry prometheus query during DRT
  pkg/cmd/roachtest/tests/drt.go
  pkg/cmd/roachtest/tests/tpcc.go
Labels: backport-22.1.x, backport-22.2.x

#94711 roachtest: expose prometheus endpoint
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/registry/BUILD.bazel
  pkg/cmd/roachtest/registry/registry_interface.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/roachstress.sh
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/test_registry_test.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/test_test.go
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery, T-testeng
