Repository cockroachdb/cockroach, pull requests merged in 2024-11, with the labels that each got.

#133958 release-24.2: roachprod: redirect CRDB logs utility
  pkg/BUILD.bazel
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/run.go
  pkg/roachprod/logger/BUILD.bazel
  pkg/roachprod/logger/log_redirect.go
  pkg/roachprod/logger/log_redirect_test.go
Labels: backport

#133957 release-24.3: roachprod: redirect CRDB logs utility
  pkg/BUILD.bazel
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/run.go
  pkg/roachprod/logger/BUILD.bazel
  pkg/roachprod/logger/log_redirect.go
  pkg/roachprod/logger/log_redirect_test.go
Labels: backport

#133961 release-24.1: roachprod: redirect CRDB logs utility
  pkg/BUILD.bazel
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/run.go
  pkg/roachprod/logger/BUILD.bazel
  pkg/roachprod/logger/log_redirect.go
  pkg/roachprod/logger/log_redirect_test.go
Labels: backport

#133968 release-23.1: roachprod: redirect CRDB logs utility
  pkg/BUILD.bazel
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/run.go
  pkg/roachprod/logger/BUILD.bazel
  pkg/roachprod/logger/log_redirect.go
  pkg/roachprod/logger/log_redirect_test.go
Labels: backport

#133962 release-23.2: roachprod: redirect CRDB logs utility
  pkg/BUILD.bazel
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/run.go
  pkg/roachprod/logger/BUILD.bazel
  pkg/roachprod/logger/log_redirect.go
  pkg/roachprod/logger/log_redirect_test.go
Labels: backport

#133979 crosscluster/producer: poll for lagging ranges
  pkg/ccl/crosscluster/producer/range_stats.go
  pkg/ccl/crosscluster/producer/range_stats_test.go
  pkg/repstream/streampb/stream.proto
Labels: T-disaster-recovery

#133986 catalog/replication: deflake TestReaderCatalogTSAdvance
  pkg/sql/catalog/replication/BUILD.bazel
  pkg/sql/catalog/replication/reader_catalog_test.go
Labels: backport-24.3.x

#133991 kvclient: fix rangefeed retry reason counters
  docs/generated/metrics/metrics.html
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/util/metric/registry.go
  pkg/util/metric/registry_test.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#133863 server, ui: tweak language for throttling, remove obsolete alerts, add test probe
  pkg/server/license/enforcer.go
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.spec.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#134074 bazel-github-helper: correct typo
  pkg/cmd/bazci/bazel-github-helper/main.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x

#134078 release-24.3: server, ui: tweak language for throttling, remove obsolete alerts, add test probe
  pkg/server/license/enforcer.go
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.spec.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx
Labels: backport

#134077 release-24.2: server, ui: tweak language for throttling, remove obsolete alerts, add test probe
  pkg/server/license/enforcer.go
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.spec.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx
Labels: backport

#134075 release-24.1: server, ui: tweak language for throttling, remove obsolete alerts, add test probe
  pkg/server/license/enforcer.go
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.spec.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx
Labels: backport

#134073 release-23.2: server, ui: tweak language for throttling, remove obsolete alerts, add test probe
  pkg/server/license/enforcer.go
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.spec.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx
Labels: backport

#134070 release-23.1: server, ui: tweak language for throttling, remove obsolete alerts, add test probe
  pkg/server/license/enforcer.go
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.spec.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx
Labels: backport

#133075 apiv2,server: filter expensive db queries from sql-over-http
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/server/api_v2_sql.go
  pkg/server/api_v2_sql_test.go
  pkg/server/testdata/api_v2_sql
  pkg/ui/ui.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#133512 sql/schemachanger: add dep rules between trigger element and its dependents
  pkg/sql/schemachanger/scplan/internal/rules/current/BUILD.bazel
  pkg/sql/schemachanger/scplan/internal/rules/current/assertions_test.go
  pkg/sql/schemachanger/scplan/internal/rules/current/dep_add_trigger.go
  pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_trigger.go
  pkg/sql/schemachanger/scplan/internal/rules/current/helpers.go
  pkg/sql/schemachanger/scplan/internal/rules/current/testdata/deprules
  pkg/sql/schemachanger/scplan/internal/rules/helpers.go
  pkg/sql/schemachanger/scplan/internal/rules/release_24_3/BUILD.bazel
  pkg/sql/schemachanger/scplan/internal/rules/release_24_3/dep_add_trigger.go
  pkg/sql/schemachanger/scplan/internal/rules/release_24_3/dep_drop_trigger.go
  pkg/sql/schemachanger/scplan/internal/rules/release_24_3/helpers.go
  pkg/sql/schemachanger/scplan/internal/rules/release_24_3/testdata/deprules
  pkg/sql/schemachanger/scplan/testdata/create_trigger
  pkg/sql/schemachanger/scplan/testdata/drop_table
  pkg/sql/schemachanger/scplan/testdata/drop_trigger
Labels: backport-24.3.x

#134064 release-24.3: go.mod: bump Pebble to 405b4e1228d5
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  build/teamcity/cockroach/nightlies/pebble_nightly_common.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_race.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_two_instance.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_race_common.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_ycsb_race.sh
  go.mod
  go.sum
  scripts/bump-pebble.sh
Labels: backport

#134080 kv: ensure leader election is not delayed for quiesced ranges on restart
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/raft/raft.go
  pkg/testutils/serverutils/test_cluster_shim.go
Labels: backport-24.3.x

#134063 release-23.1: settings: redact all string settings for diagnostics
  pkg/ccl/serverccl/diagnosticsccl/BUILD.bazel
  pkg/ccl/serverccl/diagnosticsccl/main_test.go
  pkg/ccl/serverccl/diagnosticsccl/reporter_test.go
  pkg/settings/registry.go
Labels: backport

#134092 kvcoord: add a metric for number of partial batches in progress
  docs/generated/metrics/metrics.html
  pkg/kv/kvclient/kvcoord/dist_sender.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#134121 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#134122 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#134123 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#134125 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#134126 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#134105 release-24.1: tree: optionally treat string constants as collated
  pkg/sql/logictest/testdata/logic_test/collatedstring
  pkg/sql/sem/tree/constant.go
  pkg/sql/sem/tree/constant_test.go
Labels: backport

#134114 release-23.2: tree: optionally treat string constants as collated
  pkg/sql/logictest/testdata/logic_test/collatedstring
  pkg/sql/sem/tree/constant.go
  pkg/sql/sem/tree/constant_test.go
Labels: backport

#134179 util/log: avoid heap allocation on no-op VEvent call
  pkg/util/log/gen/main.go
  pkg/util/log/log_channels_generated.go
  pkg/util/log/trace.go
  pkg/util/log/trace_test.go
Labels: o-perf-efficiency, backport-24.3.x

#133330 sql: do not use fast-path-checks if there are row-level BEFORE triggers
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/opt/optbuilder/testdata/trigger
  pkg/sql/opt/optbuilder/trigger.go
Labels: backport-24.3.x

#134220 testutils: use race duration in a few places
  pkg/sql/show_ranges_test.go
  pkg/testutils/sqlutils/sql_runner.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#134157 changefeedccl: disable non-enterprise feeds in TestChangefeedTimelyRe…
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport-24.3.x

#134232 sql: include tombstone-enforced uniqueness constraints in upsert explain
  pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit_read_committed
  pkg/sql/opt/exec/explain/emit.go
Labels: backport-24.3.x

#134268 kv: fix `handleRaftReady` leadership change detection
  pkg/kv/kvserver/replica_raft.go
Labels: backport-24.3.x

#134206 ldapccl: fix ldap connection timeout due to idleness
  pkg/ccl/ldapccl/authentication_ldap_test.go
  pkg/ccl/ldapccl/ldap_test_util.go
  pkg/ccl/ldapccl/ldap_util.go
Labels: backport-24.3.x

#134306 release-24.3: backport all changes from master
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go
  pkg/ccl/crosscluster/logical/lww_kv_processor.go
  pkg/ccl/crosscluster/logical/lww_row_processor.go
  pkg/ccl/crosscluster/producer/event_stream.go
  pkg/ccl/crosscluster/producer/range_stats.go
  pkg/ccl/crosscluster/producer/range_stats_test.go
  pkg/ccl/crosscluster/producer/replication_manager.go
  pkg/ccl/crosscluster/producer/span_config_event_stream.go
  pkg/ccl/crosscluster/producer/stream_lifetime.go
  pkg/ccl/crosscluster/streamclient/client.go
  pkg/ccl/crosscluster/streamclient/partitioned_stream_client.go
  pkg/cli/zip_table_registry.go
  pkg/repstream/streampb/BUILD.bazel
  pkg/repstream/streampb/empty.go
  pkg/repstream/streampb/stream.proto
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/sem/eval/context.go
Labels: backport

#134099 release-24.2: roachtest: small mvt test fixes
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/tpcc_test.go
Labels: backport

#134115 crosscluster/producer: lock producer side tables from schema changes
  pkg/ccl/crosscluster/logical/BUILD.bazel
  pkg/ccl/crosscluster/logical/create_logical_replication_stmt.go
  pkg/ccl/crosscluster/logical/logical_replication_job.go
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/producer/producer_job.go
  pkg/ccl/crosscluster/producer/replication_manager.go
  pkg/ccl/crosscluster/replicationtestutils/testutils.go
  pkg/ccl/crosscluster/replicationutils/BUILD.bazel
  pkg/ccl/crosscluster/replicationutils/utils.go
  pkg/jobs/jobspb/jobs.proto
Labels: T-disaster-recovery, backport-24.3.x

#134226 ui: db styling adjustments
  pkg/ui/workspaces/cluster-ui/src/components/grantsTable/index.tsx
  pkg/ui/workspaces/cluster-ui/src/layouts/pageSection.module.scss
  pkg/ui/workspaces/cluster-ui/src/tableDetailsV2/tableIndexesView.tsx
  pkg/ui/workspaces/cluster-ui/src/tableDetailsV2/tableOverview.tsx
Labels: backport-24.3.x

#134117 release-24.3: sql/schemachanger: add dep rules between trigger element and its dependents
  pkg/sql/schemachanger/scplan/internal/rules/current/BUILD.bazel
  pkg/sql/schemachanger/scplan/internal/rules/current/assertions_test.go
  pkg/sql/schemachanger/scplan/internal/rules/current/dep_add_trigger.go
  pkg/sql/schemachanger/scplan/internal/rules/current/dep_drop_trigger.go
  pkg/sql/schemachanger/scplan/internal/rules/current/helpers.go
  pkg/sql/schemachanger/scplan/internal/rules/current/testdata/deprules
  pkg/sql/schemachanger/scplan/internal/rules/helpers.go
  pkg/sql/schemachanger/scplan/testdata/create_trigger
  pkg/sql/schemachanger/scplan/testdata/drop_table
  pkg/sql/schemachanger/scplan/testdata/drop_trigger
Labels: backport

#134337 release-24.3: go.mod: bump Pebble to 82802590e8eb
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#134341 release-24.3: cluster-ui: publish cluster-ui 24.3.1
  pkg/ui/workspaces/cluster-ui/package.json
Labels: backport

#134360 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#134356 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#134359 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#134354 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#134320 tablemetadatacache: update bucket config for job duration metric
  pkg/sql/tablemetadatacache/update_table_metadata_cache_job.go
Labels: backport-24.3.x

#134358 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#134334 sql: avoid expensive errors with empty database name lookups
  pkg/sql/catalog/descs/BUILD.bazel
  pkg/sql/catalog/descs/collection_test.go
  pkg/sql/catalog/descs/getters.go
  pkg/sql/schema_resolver.go
Labels: o-perf-efficiency

#133998 changefeedccl: increase buffer size for mixed versions roachtest
  pkg/cmd/roachtest/tests/mixed_version_cdc.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#134274 sql: blank pad character datums more efficiently
  pkg/sql/pgwire/BUILD.bazel
  pkg/sql/pgwire/types.go
  pkg/sql/sem/tree/BUILD.bazel
  pkg/sql/sem/tree/pgwire_encode.go
  pkg/util/system/BUILD.bazel
  pkg/util/system/cache_line.go
Labels: o-perf-efficiency

#134421 server: fix flaking TestTriggerMetadataUpdateJob test
  pkg/server/api_v2_databases_metadata_test.go
  pkg/sql/tablemetadatacache/update_table_metadata_cache_job_test.go
  pkg/sql/tablemetadatacache/util/util.go
Labels: backport-24.3.x

#134453 release-24.3: storage: backport columnar KeySchema updates
  pkg/storage/engine_key_test.go
  pkg/storage/pebble_key_schema.go
  pkg/storage/pebble_key_schema_test.go
  pkg/storage/testdata/key_schema_key_seeker
  pkg/storage/testdata/key_schema_key_writer
Labels: backport, branch-release-24.3

#134441 storage: disable multilevel compactions
  pkg/storage/pebble.go
Labels: backport-24.3.x

#134469 release-24.1.7-rc: opt: make `max-stack` opt tester option more reliable
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/testdata/rules/select
Labels: backport

#134468 release-24.2.5-rc: opt: make `max-stack` opt tester option more reliable
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/testdata/rules/select
Labels: backport

#133328 sql: fix trigger interaction with computed columns
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/sql/opt/optbuilder/testdata/trigger
  pkg/sql/opt/optbuilder/trigger.go
Labels: backport-24.3.x

#133300 gossip: adjust recovery timings to tolerate shorter lease expiration
  pkg/base/config.go
  pkg/base/testdata/raft_config
  pkg/gossip/gossip.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#134454 sql/schemachanger: fix logic in decomp for index/partition zone configs
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs
  pkg/ccl/schemachangerccl/testdata/decomp/multiregion
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go
  pkg/sql/schemachanger/scdecomp/decomp.go
Labels: backport-24.3.x

#134442 memo: add unique w/tombstone indexes to EXPLAIN (OPT) output
  pkg/ccl/logictestccl/testdata/logic_test/partitioning_implicit_read_committed
  pkg/sql/opt/memo/expr_format.go
Labels: backport-24.3.x

#134444 release-24.3: opt: plan row-level BEFORE triggers for cascading mutations
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/sql/distsql_running.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/optbuilder/delete.go
  pkg/sql/opt/optbuilder/fk_cascade.go
  pkg/sql/opt/optbuilder/insert.go
  pkg/sql/opt/optbuilder/plpgsql.go
  pkg/sql/opt/optbuilder/testdata/trigger
  pkg/sql/opt/optbuilder/trigger.go
  pkg/sql/opt/optbuilder/update.go
  pkg/sql/opt/optbuilder/util.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#134407 schemachange/mixed-versions: handle possible syntax error for BIT(0) column usage
  pkg/workload/schemachange/operation_generator.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#134377 sql/schemachanger: fix a misattributed metric and noisy log
  pkg/sql/conn_executor.go
  pkg/sql/schemachanger/scbuild/build.go
  pkg/sql/schemachanger/scbuild/event_log.go
  pkg/sql/schemachanger/scerrors/errors.go
  pkg/sql/schemachanger/scplan/plan.go
  pkg/sql/schemachanger/scrun/scrun.go
  pkg/sql/sem/tree/stmt.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#134467 release-24.3: cluster-ui: bump npm pkg to v24.3.2
  pkg/ui/pnpm-lock.yaml
  pkg/ui/workspaces/cluster-ui/package.json
Labels: backport

#134324 cloud: fix missing shared config profile error on kms backups
  pkg/cloud/amazon/aws_kms.go
  pkg/cloud/amazon/aws_kms_test.go
  pkg/cloud/amazon/s3_storage_test.go
Labels: backport-24.3.x

#134512 amazon: fix s3 client caching
  pkg/cloud/amazon/s3_storage.go
Labels: backport-23.2.15-rc

#134541 release-24.1: go.mod: bump Pebble to 98ed66b2cad0
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#134526 release-23.2: bump Pebble and split snapshot sstables
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cli/debug.go
  pkg/kv/kvserver/BUILD.bazel
  pkg/kv/kvserver/client_merge_test.go
  pkg/kv/kvserver/kvserverpb/raft.proto
  pkg/kv/kvserver/rditer/replica_data_iter.go
  pkg/kv/kvserver/rditer/replica_data_iter_test.go
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/all/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/all/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/all/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/replicatedOnly/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/replicatedOnly/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/replicatedOnly/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/all/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/all/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/all/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/replicatedOnly/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/replicatedOnly/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/replicatedOnly/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/all/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/all/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/all/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/replicatedOnly/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/replicatedOnly/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/replicatedOnly/user-only/output
  pkg/kv/kvserver/replica_command.go
  pkg/kv/kvserver/replica_learner_test.go
  pkg/kv/kvserver/replica_sst_snapshot_storage_test.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/store_snapshot.go
  pkg/storage/engine_key.go
  pkg/storage/sst_writer.go
Labels: backport

#134511 release-24.1: schemachange/mixed-versions: handle possible syntax error for BIT(0) column usage
  pkg/workload/schemachange/operation_generator.go
Labels: backport

#134513 release-23.2: schemachange/mixed-versions: handle possible syntax error for BIT(0) column usage
  pkg/workload/schemachange/operation_generator.go
Labels: backport

#134472 release-24.2: schemachanger: add PartitionName to IndexZoneConfig attr
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs
  pkg/sql/schemachanger/screl/attr.go
  pkg/sql/schemachanger/screl/attr_string.go
Labels: backport

#134522 release-24.1: schemachanger: add PartitionName to IndexZoneConfig attr
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs
  pkg/sql/schemachanger/screl/attr.go
  pkg/sql/schemachanger/screl/attr_string.go
Labels: backport

#134523 release-23.2: schemachanger: add PartitionName to IndexZoneConfig attr
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs
  pkg/sql/schemachanger/screl/attr.go
  pkg/sql/schemachanger/screl/attr_string.go
Labels: backport

#134463 release-24.3: kvserver: add storage.compactions.cancelled.{count,bytes}
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
Labels: backport, branch-release-24.3

#134517 release-23.2: changefeedccl: increase buffer size for mixed versions roachtest
  pkg/cmd/roachtest/tests/mixed_version_cdc.go
Labels: backport

#134307 crosscluster/streamclient: attempt to reconnect conn in heartbeat call
  pkg/ccl/crosscluster/streamclient/partitioned_stream_client.go
  pkg/ccl/crosscluster/streamclient/partitioned_stream_client_test.go
Labels: T-disaster-recovery, backport-24.3.x

#134352 raft: don't remember leader after stepping down if not fortified
  pkg/raft/raft.go
  pkg/raft/testdata/mixedversions/checkquorum.txt
Labels: backport-24.3.x

#134575 sql: disallow replacing a referenced trigger function
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/sql/create_function.go
Labels: backport-24.3.x

#134524 release-23.1: schemachanger: add PartitionName to IndexZoneConfig attr
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs
  pkg/sql/schemachanger/screl/attr.go
  pkg/sql/schemachanger/screl/attr_string.go
Labels: backport

#134585 rac2: clear scratchEvent after using
  pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go
Labels: backport-24.3.x

#134654 upgrade: corrupt descriptor repair does not handle GC timestamp errors
  pkg/upgrade/upgrades/BUILD.bazel
  pkg/upgrade/upgrades/first_upgrade.go
Labels: backport-24.3.x

#134632 sql: update trigger back-references for legacy schema changer drop table
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/sql/drop_table.go
Labels: backport-24.3.x

#134670 publish-provisional-artifacts: add licenses to THIRD-PARTY-NOTICES.txt
  build/teamcity/internal/release/process/build-cockroach-release-per-platform.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-per-platform.sh
  pkg/cmd/publish-provisional-artifacts/main.go
Labels: C-enhancement, A-release, T-release, backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x, backport-23.1.29-rc, backport-23.2.15-rc, backport-24.1.7-rc, backport-24.2.5-rc

#134641 release-23.1: authccl: remove console API auth tests on 23.1
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/ccl/testccl/authccl/testdata/jwt
Labels: backport

#134651 release-23.1.29-rc: authccl: remove console API auth tests on 23.1
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/ccl/testccl/authccl/testdata/jwt
Labels: backport

#134726 opt/idxconstraint: optimize computed column constraint derivation
  pkg/sql/opt/bench/bench_test.go
  pkg/sql/opt/idxconstraint/index_constraints.go
  pkg/sql/opt/idxconstraint/testdata/computed
Labels: o-perf-efficiency

#134594 release-23.2: jobs: don't redact job ID in log tags
  pkg/jobs/registry.go
Labels: backport

#134592 release-24.1: jobs: don't redact job ID in log tags
  pkg/jobs/registry.go
Labels: backport

#134483 release-24.3: sql: fix trigger interaction with computed columns
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/sql/opt/optbuilder/testdata/trigger
  pkg/sql/opt/optbuilder/trigger.go
Labels: backport

#134595 release-23.1: jobs: don't redact job ID in log tags
  pkg/jobs/registry.go
Labels: backport

#134672 kvserver: fix MsgApp leak in RACv2
  pkg/kv/kvserver/replica_raft.go
Labels: backport-24.3.x

#134721 crosscluster/logical: don't set fraction once resolved ts exists
  pkg/ccl/crosscluster/logical/logical_replication_job.go
  pkg/ccl/crosscluster/logical/range_stats.go
  pkg/ccl/crosscluster/logical/range_stats_test.go
  pkg/ccl/crosscluster/producer/range_stats.go
  pkg/ui/workspaces/cluster-ui/src/jobs/util/jobOptions.tsx
Labels: backport-24.3.x

#134835 release-24.3: storage: propagate KeySchemas to debug tools
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cli/debug.go
  pkg/server/debug/server.go
  pkg/storage/pebble.go
  pkg/storage/pebble_key_schema.go
Labels: backport

#134613 ccl/sqlproxyccl: improve connection logging behavior
  pkg/ccl/sqlproxyccl/balancer/conn_tracker.go
  pkg/ccl/sqlproxyccl/proxy_handler.go
  pkg/ccl/sqlproxyccl/server.go
  pkg/ccl/sqlproxyccl/throttler/local.go
  pkg/ccl/sqlproxyccl/throttler/local_test.go
  pkg/ccl/sqlproxyccl/throttler/service.go
  pkg/ccl/sqlproxyccl/throttler/throttle.go
Labels: backport-24.2.x, backport-24.3.x

#133734 release-24.2: sql: properly annotate errors in the internal executor in some cases
  pkg/sql/internal.go
Labels: backport

#134860 licenses: fixing license notice filenames
  licenses/LGPL-github.com-cockroachdb.geos.txt
  licenses/MIT-github.com-cockroachdb.proj.txt
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x, backport-23.2.15-rc, backport-24.1.7-rc, backport-24.2.5-rc

#134863 release-23.1: licenses: add third-party notices for the c-deps
  licenses/BSD2-github.com-cockroachdb.jemalloc.txt
  licenses/BSD2-github.com-cockroachdb.krb5.txt
  licenses/BSD3-github.com-cockroachdb.libedit.txt
  licenses/LGPL-github.com-cockroachdb.geos.txt
  licenses/MIT-github.com-cockroachdb.proj.txt
Labels: backport-23.1.29-rc

#134868 licenses: remove unneeded notice file
  licenses/LevelDB.AUTHORS
Labels: backport-24.3.x

#134888 crosscluster/logical: drop leases at each checkpoint
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go
  pkg/ccl/crosscluster/logical/lww_kv_processor.go
  pkg/ccl/crosscluster/logical/lww_row_processor.go
Labels: backport-24.3.x, backport-24.3.0-rc.1-rc

#134498 sql: correctly handle triggers with cyclical dependencies
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/sql/distsql_running.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/scalar.go
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/optbuilder/builder.go
  pkg/sql/opt/optbuilder/testdata/trigger
  pkg/sql/opt/optbuilder/trigger.go
  pkg/sql/routine.go
  pkg/sql/sem/tree/routine.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/sqltelemetry/exec.go
  pkg/sql/vars.go
Labels: backport-24.3.x

#134218 kvserver: add leader lease type to TestLeaseRenewer
  pkg/kv/kvserver/leases/build.go
  pkg/kv/kvserver/replica_lease_renewal_test.go
Labels: backport-24.3.x

#134850 sql: Drop Role does not properly check if target user does not exist
  pkg/sql/drop_role.go
  pkg/sql/logictest/testdata/logic_test/drop_role_with_default_privileges
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#134730 release-24.2: roachtest: apply default mvt start opts to tenants
  pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go
Labels: backport

#134729 release-24.3: roachtest: apply default mvt start opts to tenants
  pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go
Labels: backport

#134600 release-24.2: gossip: adjust recovery timings to tolerate shorter lease expiration
  pkg/base/config.go
  pkg/base/testdata/raft_config
  pkg/gossip/gossip.go
Labels: backport

#134601 release-24.1: gossip: adjust recovery timings to tolerate shorter lease expiration
  pkg/base/config.go
  pkg/base/testdata/raft_config
  pkg/gossip/gossip.go
Labels: backport

#134602 release-23.2: gossip: adjust recovery timings to tolerate shorter lease expiration
  pkg/base/config.go
  pkg/base/testdata/raft_config
  pkg/gossip/gossip.go
Labels: backport

#134603 release-23.1: gossip: adjust recovery timings to tolerate shorter lease expiration
  pkg/base/config.go
  pkg/base/testdata/raft_config
  pkg/gossip/gossip.go
Labels: backport

#134722 release-23.2: catalog/lease: Improve reliability of TestLeaseRenewedAutomatically
  pkg/sql/catalog/lease/lease_test.go
Labels: backport

#134869 release-24.3: upgrade: corrupt descriptor repair does not handle GC timestamp errors
  pkg/upgrade/upgrades/BUILD.bazel
  pkg/upgrade/upgrades/first_upgrade.go
Labels: backport

#134836 release-24.1: changefeedccl: add PTS to system.users
  pkg/ccl/changefeedccl/protected_timestamps.go
  pkg/ccl/changefeedccl/protected_timestamps_test.go
  pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go
Labels: backport

#134985 release-23.2: lease: dump stacks if TestDescriptorRefreshOnRetry fails
  pkg/sql/catalog/lease/BUILD.bazel
  pkg/sql/catalog/lease/lease_test.go
Labels: backport

#134980 scbuild: run test on two cores
  pkg/sql/schemachanger/scbuild/BUILD.bazel
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x

#135003 release-23.2: sql: avoid role existence check in DROP ROLE when it's not necessary
  pkg/sql/drop_role.go
Labels: backport

#131437 sql/stats: fix the incorrect data range in "randBounds"
  pkg/sql/pgwire/pgwirebase/encoding.go
  pkg/sql/sem/tree/datum.go
  pkg/sql/sem/tree/parse_string.go
  pkg/sql/stats/quantile.go
  pkg/sql/stats/quantile_test.go
  pkg/util/timeutil/pgdate/parsing.go
Labels: O-community, backport-24.3.x

#134891 opt: correctly type lookup join constant projections
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/opt/lookupjoin/constraint_builder.go
  pkg/sql/opt/lookupjoin/constraint_builder_test.go
  pkg/sql/opt/lookupjoin/testdata/computed
  pkg/sql/opt/lookupjoin/testdata/key_cols
  pkg/sql/opt/lookupjoin/testdata/lookup_expr
  pkg/sql/opt/xform/testdata/rules/join
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#134344 dev: suggest crosslinuxarm on arm64
  dev
  pkg/cmd/dev/doctor.go
Labels: backport-24.3.x

#135028 sql,authorization: use proper method for escaping SQL identifiers
  pkg/ccl/testccl/authccl/testdata/ldap
  pkg/sql/authorization.go
Labels: backport-24.3.x, backport-24.3.0-rc

#133789 kvserver,changefeeds,crosscluster: set per-consumer catchup scan limit
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed_test.go
  pkg/ccl/changefeedccl/kvfeed/physical_kv_feed.go
  pkg/ccl/crosscluster/producer/event_stream.go
  pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvclient/rangefeed/config.go
  pkg/kv/kvclient/rangefeed/rangefeed.go
  pkg/kv/kvclient/rangefeed/rangefeed_external_test.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvserver/client_replica_circuit_breaker_test.go
  pkg/kv/kvserver/replica_rangefeed.go
  pkg/kv/kvserver/replica_rangefeed_test.go
  pkg/kv/kvserver/store.go
  pkg/kv/kvserver/stores.go
  pkg/server/BUILD.bazel
  pkg/server/node.go
Labels: backport-24.2.x, backport-24.3.x

#134664 server: remove seemingly unnecessary log entries
  pkg/server/status/recorder.go
Labels: O-testcluster, backport-24.3.x, O-24.3-scale-testing

#134905 release-24.2: colexec: add session variable to disable eager cancellation
  pkg/sql/colexec/BUILD.bazel
  pkg/sql/colexec/parallel_unordered_synchronizer.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#135047 release-24.3: tablemetadatacache,ui: change error messaging for failed tmj update
  pkg/sql/tablemetadatacache/table_metadata_batch_iterator.go
  pkg/sql/tablemetadatacache/table_metadata_updater.go
  pkg/sql/tablemetadatacache/testdata/update_table_metadata_errors
  pkg/ui/workspaces/cluster-ui/src/components/tooltipMessages/tableMetadataLastUpdatedTooltip.tsx
  pkg/ui/workspaces/cluster-ui/src/tableDetailsV2/tableOverview.tsx
Labels: backport

#135095 storage: fix incorrect assumption about empty suffixes
  pkg/storage/pebble_key_schema.go
  pkg/storage/pebble_key_schema_test.go
Labels: backport-24.3.x

#135076 release-24.2: opt: correctly type lookup join constant projections
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/opt/lookupjoin/constraint_builder.go
  pkg/sql/opt/lookupjoin/constraint_builder_test.go
  pkg/sql/opt/lookupjoin/testdata/computed
  pkg/sql/opt/lookupjoin/testdata/key_cols
  pkg/sql/opt/lookupjoin/testdata/lookup_expr
  pkg/sql/opt/xform/testdata/rules/join
Labels: backport

#135042 kv: acquire clock reading for lease request under lock
  pkg/kv/kvserver/batcheval/cmd_lease_request.go
  pkg/kv/kvserver/batcheval/cmd_lease_test.go
  pkg/kv/kvserver/batcheval/cmd_lease_transfer.go
  pkg/kv/kvserver/leases/build.go
  pkg/kv/kvserver/leases/build_test.go
  pkg/kv/kvserver/replica_range_lease.go
Labels: backport-24.3.x

#135123 staging-v23.2.15: bump Pebble and split snapshot sstables
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cli/debug.go
  pkg/kv/kvserver/BUILD.bazel
  pkg/kv/kvserver/client_merge_test.go
  pkg/kv/kvserver/kvserverpb/raft.proto
  pkg/kv/kvserver/rditer/replica_data_iter.go
  pkg/kv/kvserver/rditer/replica_data_iter_test.go
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/all/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/all/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/all/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/replicatedOnly/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/replicatedOnly/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/replicatedOnly/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/all/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/all/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/all/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/replicatedOnly/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/replicatedOnly/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/replicatedOnly/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/all/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/all/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/all/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/replicatedOnly/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/replicatedOnly/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/replicatedOnly/user-only/output
  pkg/kv/kvserver/replica_command.go
  pkg/kv/kvserver/replica_learner_test.go
  pkg/kv/kvserver/replica_sst_snapshot_storage_test.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/store_snapshot.go
  pkg/storage/engine_key.go
  pkg/storage/sst_writer.go
Labels: backport

#135111 release-24.1: opt: correctly type lookup join constant projections
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/opt/lookupjoin/constraint_builder.go
  pkg/sql/opt/lookupjoin/constraint_builder_test.go
  pkg/sql/opt/lookupjoin/testdata/computed
  pkg/sql/opt/lookupjoin/testdata/key_cols
  pkg/sql/opt/lookupjoin/testdata/lookup_expr
  pkg/sql/opt/xform/testdata/rules/join
Labels: backport

#135113 release-23.2: opt: correctly type lookup join constant projections
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/opt/lookupjoin/constraint_builder.go
  pkg/sql/opt/lookupjoin/constraint_builder_test.go
  pkg/sql/opt/lookupjoin/testdata/computed
  pkg/sql/opt/lookupjoin/testdata/key_cols
  pkg/sql/opt/lookupjoin/testdata/lookup_expr
  pkg/sql/opt/xform/testdata/rules/join
Labels: backport

#135086 pgwire,authccl: use pgx for TestAuthenticationAndHBARules
  pkg/ccl/testccl/authccl/BUILD.bazel
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/sql/pgwire/BUILD.bazel
  pkg/sql/pgwire/auth_test.go
  pkg/sql/pgwire/pre_serve.go
  pkg/sql/pgwire/testdata/auth/conn_log
  pkg/sql/pgwire/testdata/auth/empty_hba
  pkg/sql/pgwire/testdata/auth/hba_default_equivalence
  pkg/sql/pgwire/testdata/auth/identity_map
  pkg/sql/pgwire/testdata/auth/insecure
  pkg/sql/pgwire/testdata/auth/scram
  pkg/sql/pgwire/testdata/auth/special_cases
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#135142 ttljob: update fraction completed in TTL job
  pkg/jobs/jobspb/jobs.proto
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
  pkg/sql/ttl/ttljob/ttljob_test.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x

#135112 kv/kvnemesis: add leader lease config
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
  pkg/kv/kvnemesis/kvnemesis_test.go
  pkg/kv/kvserver/client_raft_epoch_leases_test.go
  pkg/kv/kvserver/client_raft_helpers_test.go
  pkg/kv/kvserver/client_raft_test.go
  pkg/kv/kvserver/replica_lease_renewal_test.go
  pkg/kv/kvserver/replica_range_lease.go
Labels: backport-24.3.x

#134851 release-23.2: changefeedccl: don't log error on context cancel
  pkg/ccl/changefeedccl/batching_sink.go
Labels: backport

#135156 roachtest: fix health and consistency checks
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/test_runner.go
Labels: backport-24.3.x

#135174 release-24.1: pgwire,authccl: use pgx for TestAuthenticationAndHBARules
  pkg/ccl/testccl/authccl/BUILD.bazel
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/sql/pgwire/BUILD.bazel
  pkg/sql/pgwire/auth_test.go
  pkg/sql/pgwire/pre_serve.go
  pkg/sql/pgwire/testdata/auth/conn_log
  pkg/sql/pgwire/testdata/auth/empty_hba
  pkg/sql/pgwire/testdata/auth/hba_default_equivalence
  pkg/sql/pgwire/testdata/auth/identity_map
  pkg/sql/pgwire/testdata/auth/insecure
  pkg/sql/pgwire/testdata/auth/scram
  pkg/sql/pgwire/testdata/auth/special_cases
Labels: backport

#135175 release-23.2: pgwire,authccl: use pgx for TestAuthenticationAndHBARules
  pkg/ccl/testccl/authccl/BUILD.bazel
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/sql/pgwire/BUILD.bazel
  pkg/sql/pgwire/auth_test.go
  pkg/sql/pgwire/pre_serve.go
  pkg/sql/pgwire/testdata/auth/conn_log
  pkg/sql/pgwire/testdata/auth/empty_hba
  pkg/sql/pgwire/testdata/auth/hba_default_equivalence
  pkg/sql/pgwire/testdata/auth/identity_map
  pkg/sql/pgwire/testdata/auth/insecure
  pkg/sql/pgwire/testdata/auth/scram
  pkg/sql/pgwire/testdata/auth/special_cases
Labels: backport

#135178 release-23.1: pgwire,authccl: use pgx for TestAuthenticationAndHBARules
  pkg/ccl/testccl/authccl/BUILD.bazel
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/sql/pgwire/BUILD.bazel
  pkg/sql/pgwire/auth_test.go
  pkg/sql/pgwire/pre_serve.go
  pkg/sql/pgwire/testdata/auth/conn_log
  pkg/sql/pgwire/testdata/auth/empty_hba
  pkg/sql/pgwire/testdata/auth/hba_default_equivalence
  pkg/sql/pgwire/testdata/auth/identity_map
  pkg/sql/pgwire/testdata/auth/insecure
  pkg/sql/pgwire/testdata/auth/scram
  pkg/sql/pgwire/testdata/auth/special_cases
Labels: backport

#135184 sysbench: use 2GB pebble cache
  pkg/sql/tests/sysbench_test.go
Labels: o-perf-efficiency

#135119 release-24.2: roachtest: allow adding extra github parameters
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/test/test_interface.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/testdata/github/arbitrary_transient_failure
  pkg/cmd/roachtest/testdata/github/basic_test_create_post_request
  pkg/cmd/roachtest/testdata/github/cluster_provisioning_error
  pkg/cmd/roachtest/testdata/github/coverage-enabled-build
  pkg/cmd/roachtest/testdata/github/dns_flake_and_error_with_ownership
  pkg/cmd/roachtest/testdata/github/dns_flake_error
  pkg/cmd/roachtest/testdata/github/extra_labels
  pkg/cmd/roachtest/testdata/github/extra_parameters
  pkg/cmd/roachtest/testdata/github/lost_error_object_and_transient_error
  pkg/cmd/roachtest/testdata/github/nested_errors_with_ownership
  pkg/cmd/roachtest/testdata/github/nested_transient_failures
  pkg/cmd/roachtest/testdata/github/non_release_blocker_create_post_request
  pkg/cmd/roachtest/testdata/github/require_no_error_transient_error
  pkg/cmd/roachtest/testdata/github/runtime_assertions_build
  pkg/cmd/roachtest/testdata/github/ssh_flake_error
  pkg/cmd/roachtest/testdata/github/vm_host_error
  pkg/cmd/roachtest/testdata/github/vm_host_error_and_other_error
  pkg/cmd/roachtest/testdata/github/vm_preemption_and_other_error
  pkg/cmd/roachtest/testdata/github/vm_preemption_flake
Labels: backport

#135187 release-24.1: roachtest: allow adding extra github parameters
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/test/test_interface.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/testdata/github/arbitrary_transient_failure
  pkg/cmd/roachtest/testdata/github/basic_test_create_post_request
  pkg/cmd/roachtest/testdata/github/cluster_provisioning_error
  pkg/cmd/roachtest/testdata/github/coverage-enabled-build
  pkg/cmd/roachtest/testdata/github/dns_flake_and_error_with_ownership
  pkg/cmd/roachtest/testdata/github/dns_flake_error
  pkg/cmd/roachtest/testdata/github/extra_labels
  pkg/cmd/roachtest/testdata/github/extra_parameters
  pkg/cmd/roachtest/testdata/github/lost_error_object_and_transient_error
  pkg/cmd/roachtest/testdata/github/nested_errors_with_ownership
  pkg/cmd/roachtest/testdata/github/nested_transient_failures
  pkg/cmd/roachtest/testdata/github/non_release_blocker_create_post_request
  pkg/cmd/roachtest/testdata/github/require_no_error_transient_error
  pkg/cmd/roachtest/testdata/github/runtime_assertions_build
  pkg/cmd/roachtest/testdata/github/ssh_flake_error
  pkg/cmd/roachtest/testdata/github/vm_host_error
  pkg/cmd/roachtest/testdata/github/vm_host_error_and_other_error
  pkg/cmd/roachtest/testdata/github/vm_preemption_and_other_error
  pkg/cmd/roachtest/testdata/github/vm_preemption_flake
Labels: backport

#135127 kvserver: include lease acquisition type when printing a lease
  pkg/kv/kvpb/errors_test.go
  pkg/kv/kvserver/batcheval/cmd_lease_test.go
  pkg/roachpb/data.go
  pkg/roachpb/data_test.go
Labels: backport-24.3.x, backport-24.3.0-rc

#135168 sql: validate zone config before multi region database DDL
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs
  pkg/sql/alter_database.go
Labels: backport-24.2.x, backport-24.3.x

#135117 release-24.3: roachtest: allow adding extra github parameters
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/clusterstats/mocks_generated_test_test.go
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/test/test_interface.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/testdata/github/arbitrary_transient_failure
  pkg/cmd/roachtest/testdata/github/basic_test_create_post_request
  pkg/cmd/roachtest/testdata/github/cluster_provisioning_error
  pkg/cmd/roachtest/testdata/github/coverage-enabled-build
  pkg/cmd/roachtest/testdata/github/dns_flake_and_error_with_ownership
  pkg/cmd/roachtest/testdata/github/dns_flake_error
  pkg/cmd/roachtest/testdata/github/extra_labels
  pkg/cmd/roachtest/testdata/github/extra_parameters
  pkg/cmd/roachtest/testdata/github/lost_error_object_and_transient_error
  pkg/cmd/roachtest/testdata/github/nested_errors_with_ownership
  pkg/cmd/roachtest/testdata/github/nested_transient_failures
  pkg/cmd/roachtest/testdata/github/non_release_blocker_create_post_request
  pkg/cmd/roachtest/testdata/github/require_no_error_transient_error
  pkg/cmd/roachtest/testdata/github/runtime_assertions_build
  pkg/cmd/roachtest/testdata/github/ssh_flake_error
  pkg/cmd/roachtest/testdata/github/vm_host_error
  pkg/cmd/roachtest/testdata/github/vm_host_error_and_other_error
  pkg/cmd/roachtest/testdata/github/vm_preemption_and_other_error
  pkg/cmd/roachtest/testdata/github/vm_preemption_flake
Labels: backport

#135207 release-24.3: go.mod: bump Pebble to dddf880b083f
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#135167 cmd/roachprod: skip cost calculation in list
  pkg/cmd/roachprod/flags.go
Labels: T-testeng

#135209 release-24.3: server: decrease nodes_ui response size
  pkg/server/nodes_response.go
  pkg/server/status_test.go
Labels: backport

#135195 release-24.1: scbuild: fix unhandled case during DROP SCHEMA
  pkg/sql/drop_schema.go
  pkg/sql/logictest/testdata/logic_test/drop_schema
  pkg/sql/schemachanger/scbuild/builder_state.go
Labels: backport

#135222 sql/tests: add remote sysbench microbenchmark configs
  pkg/sql/tests/BUILD.bazel
  pkg/sql/tests/sysbench_test.go
Labels: o-perf-efficiency

#135255 reports: skip TestCriticalLocalitiesReportIntegration under stress/race
  pkg/kv/kvserver/reports/reporter_test.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x

#135129 kvserver: add logging if a lease {request, transfer} is not applied
  pkg/kv/kvserver/kvserverbase/forced_error.go
Labels: backport-24.3.x, backport-24.3.0-rc

#133757 kvserver: add rac2 send queue functionality test
  pkg/kv/kvserver/flow_control_integration_test.go
  pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go
  pkg/kv/kvserver/kvflowcontrol/testing_knobs.go
  pkg/kv/kvserver/testdata/flow_control_integration/raft_snapshot
  pkg/kv/kvserver/testdata/flow_control_integration_v2/raft_snapshot_v1_encoding_apply_to_all
  pkg/kv/kvserver/testdata/flow_control_integration_v2/raft_snapshot_v1_encoding_apply_to_elastic
  pkg/kv/kvserver/testdata/flow_control_integration_v2/raft_snapshot_v2_encoding_apply_to_all
  pkg/kv/kvserver/testdata/flow_control_integration_v2/raft_snapshot_v2_encoding_apply_to_elastic
  pkg/kv/kvserver/testdata/flow_control_integration_v2/send_queue
Labels: backport-24.3.x
