Repository cockroachdb/cockroach, pull requests merged in 2024-09, with the labels that each got.

#129983 backupccl: fix TestProtectedTimestampsFailDueToLimits
  pkg/ccl/backupccl/backup_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-23.2.10-rc, backport-24.2.1-rc, backport-23.1.26-rc

#129995 failover: retry deadlock sql query
  pkg/cmd/roachtest/tests/failover.go
Labels: backport-24.1.x, backport-24.2.x

#129939 tenantcostclient: use source and destination labels
  pkg/ccl/multitenantccl/tenantcostclient/metrics.go
  pkg/ccl/multitenantccl/tenantcostclient/testdata/estimated-cpu
Labels: backport-24.2.x

#129931 release-23.1: server: add latest telemetry contact timestamp
  pkg/ccl/serverccl/diagnosticsccl/BUILD.bazel
  pkg/ccl/serverccl/diagnosticsccl/reporter_test.go
  pkg/server/diagnostics/reporter.go
  pkg/testutils/diagutils/diag_test_server.go
Labels: backport

#130037 release-23.2: released CockroachDB version 23.2.10. Next version: 23.2.11
  pkg/build/version.txt
Labels: backport

#129896 release-24.2: go.mod: bump Pebble to 782261424af1
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#128957 release-24.2: rpc: add locality to dialing
  docs/generated/metrics/metrics.html
  pkg/acceptance/localcluster/cluster.go
  pkg/blobs/client_test.go
  pkg/ccl/serverccl/statusccl/tenant_grpc_test.go
  pkg/gossip/client.go
  pkg/gossip/client_test.go
  pkg/gossip/gossip.go
  pkg/gossip/gossip_test.go
  pkg/kv/kvclient/kvcoord/send_test.go
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/kv/kvserver/loqrecovery/server.go
  pkg/kv/kvserver/raft_transport.go
  pkg/kv/kvserver/raft_transport_unit_test.go
  pkg/rpc/BUILD.bazel
  pkg/rpc/client.go
  pkg/rpc/context.go
  pkg/rpc/context_test.go
  pkg/rpc/datadriven_test.go
  pkg/rpc/down_node_test.go
  pkg/rpc/metrics.go
  pkg/rpc/metrics_test.go
  pkg/rpc/mocks_generated_test.go
  pkg/rpc/nodedialer/nodedialer.go
  pkg/rpc/nodedialer/nodedialer_test.go
  pkg/rpc/peer.go
  pkg/server/connectivity_test.go
  pkg/server/fanout_clients.go
  pkg/server/node_http_router.go
  pkg/server/server.go
  pkg/server/server_sql.go
  pkg/server/status.go
  pkg/server/tenant.go
  pkg/server/testserver.go
  pkg/sql/crdb_internal.go
  pkg/sql/distsql/inbound_test.go
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/flowinfra/cluster_test.go
  pkg/sql/flowinfra/outbox_test.go
  pkg/sql/flowinfra/utils_test.go
  pkg/testutils/testcluster/testcluster.go
Labels: backport

#130052 pkg/sql/logictest: TestLogic_alter_table failed with 10 seconds
  pkg/sql/logictest/testdata/logic_test/alter_table
Labels: backport-24.1.x

#130080 release-24.1: roachtest: delay verification of disagg-rebalance condition
  pkg/cmd/roachtest/tests/disagg_rebalance.go
Labels: backport

#129806 release-23.1: server/license: store cluster init time in the KV system keyspace
  pkg/BUILD.bazel
  pkg/config/system_test.go
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/server/BUILD.bazel
  pkg/server/license/BUILD.bazel
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/license/main_test.go
  pkg/server/server_sql.go
  pkg/server/testing_knobs.go
  pkg/sql/BUILD.bazel
  pkg/sql/exec_util.go
Labels: backport

#129797 release-23.2: server/license: store cluster init time in the KV system keyspace
  pkg/BUILD.bazel
  pkg/config/system_test.go
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/server/BUILD.bazel
  pkg/server/license/BUILD.bazel
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/license/main_test.go
  pkg/server/server_sql.go
  pkg/server/testing_knobs.go
  pkg/sql/BUILD.bazel
  pkg/sql/exec_util.go
Labels: backport

#129791 release-24.1: server/license: store cluster init time in the KV system keyspace
  pkg/BUILD.bazel
  pkg/config/system_test.go
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/server/BUILD.bazel
  pkg/server/license/BUILD.bazel
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/license/main_test.go
  pkg/server/server_sql.go
  pkg/server/testing_knobs.go
  pkg/sql/BUILD.bazel
  pkg/sql/exec_util.go
Labels: backport

#130046 release-24.1: go.mod: upgrade `grpc` to 1.56.3
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cloud/gcp/error_test.go
  pkg/server/storage_api/decommission_test.go
Labels: backport

#130062 release-24.1: roachprod: split start-up script logic for disks
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/vm/aws/support.go
  pkg/roachprod/vm/azure/azure.go
  pkg/roachprod/vm/azure/utils.go
  pkg/roachprod/vm/gce/utils.go
  pkg/roachprod/vm/vm.go
Labels: backport

#129793 release-24.2: server/license: store cluster init time in the KV system keyspace
  pkg/BUILD.bazel
  pkg/config/system_test.go
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/server/BUILD.bazel
  pkg/server/license/BUILD.bazel
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/license/main_test.go
  pkg/server/server_sql.go
  pkg/server/testing_knobs.go
  pkg/sql/BUILD.bazel
  pkg/sql/exec_util.go
Labels: backport

#130090 release-24.1: roachprod: add ZFS option for AWS
  pkg/roachprod/roachprod.go
  pkg/roachprod/vm/aws/aws.go
  pkg/roachprod/vm/aws/support.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport

#130100 release-24.1: roachtest: don't run SQL against the draining node
  pkg/cmd/roachtest/tests/kv.go
Labels: backport

#130104 release-24.2.1-rc: roachtest: don't run SQL against the draining node
  pkg/cmd/roachtest/tests/kv.go
Labels: backport

#128068 release-23.1: roachtest: selective test as a part of nightly run
  build/teamcity/cockroach/coverage/roachtest_nightly_gce.sh
  build/teamcity/cockroach/coverage/roachtest_nightly_gce_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  go.mod
  go.sum
  pkg/BUILD.bazel
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/roachtestflags/flags.go
  pkg/cmd/roachtest/testselector/BUILD.bazel
  pkg/cmd/roachtest/testselector/selector.go
  pkg/cmd/roachtest/testselector/snowflake_query.sql
Labels: backport

#130128 release-24.2: [roachtest] Opt-out of test selection for DR tests
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/online_restore.go
  pkg/cmd/roachtest/tests/restore.go
Labels: backport

#130129 release-24.1: [roachtest] Opt-out of test selection for DR tests
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/online_restore.go
  pkg/cmd/roachtest/tests/restore.go
Labels: backport

#130132 release-23.2: [roachtest] Opt-out of test selection for DR tests
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/restore.go
Labels: backport

#130130 release-23.1: [roachtest] Opt-out of test selection for DR tests
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/restore.go
Labels: backport

#130124 release-23.1: kv: prevent lease interval regression during expiration-to-epoch promotion
  pkg/kv/kvserver/batcheval/cmd_lease_request.go
  pkg/kv/kvserver/client_lease_test.go
  pkg/kv/kvserver/client_split_test.go
  pkg/kv/kvserver/replica_range_lease.go
  pkg/kv/kvserver/replica_rangefeed_test.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/replicate_queue.go
  pkg/testutils/testcluster/testcluster.go
Labels: backport

#130106 roachtest/mixedversion: improvements for multiple clusters
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
  pkg/cmd/roachtest/tests/acceptance.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#130156 release-23.2: roachtest: label randomized tests
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/costfuzz.go
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_cdc.go
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
  pkg/cmd/roachtest/tests/mixed_version_import.go
  pkg/cmd/roachtest/tests/mixed_version_schemachange.go
  pkg/cmd/roachtest/tests/rebalance_load.go
  pkg/cmd/roachtest/tests/secondary_indexes.go
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/cmd/roachtest/tests/tlp.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/unoptimized_query_oracle.go
Labels: backport

#130134 release-24.1: roachtest: label randomized tests
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/costfuzz.go
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_cdc.go
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
  pkg/cmd/roachtest/tests/mixed_version_import.go
  pkg/cmd/roachtest/tests/mixed_version_multi_region.go
  pkg/cmd/roachtest/tests/mixed_version_schemachange.go
  pkg/cmd/roachtest/tests/rebalance_load.go
  pkg/cmd/roachtest/tests/secondary_indexes.go
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/cmd/roachtest/tests/tlp.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/unoptimized_query_oracle.go
Labels: backport

#130157 release-23.1: roachtest: label randomized tests
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/costfuzz.go
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_cdc.go
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
  pkg/cmd/roachtest/tests/mixed_version_import.go
  pkg/cmd/roachtest/tests/mixed_version_schemachange.go
  pkg/cmd/roachtest/tests/rebalance_load.go
  pkg/cmd/roachtest/tests/secondary_indexes.go
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/cmd/roachtest/tests/tlp.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/unoptimized_query_oracle.go
Labels: backport

#130089 sql: make sql.txn.repeatable_read_isolation.enabled public
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/conn_executor.go
Labels: docs-todo

#129880 server/license: Add core throttling logic for license policy enforcement
  pkg/ccl/BUILD.bazel
  pkg/ccl/ccl_init.go
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/ccl/utilccl/license_test.go
  pkg/ccl/utilccl/main_test.go
  pkg/keys/constants.go
  pkg/server/initial_sql.go
  pkg/server/license/BUILD.bazel
  pkg/server/license/cclbridge.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/server.go
  pkg/server/server_sql.go
  pkg/server/tenant.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#130161 licenseccl: rename usage to environment
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/ccl/utilccl/licenseccl/license.go
  pkg/ccl/utilccl/licenseccl/license.proto
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#130119 release-23.2: roachprod: split start-up script logic for disks
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/vm/aws/support.go
  pkg/roachprod/vm/azure/azure.go
  pkg/roachprod/vm/azure/utils.go
  pkg/roachprod/vm/gce/utils.go
  pkg/roachprod/vm/vm.go
Labels: backport

#130117 kvserver: enqueue decom ranges at an interval behind a setting
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_init.go
  pkg/kv/kvserver/replica_metrics.go
  pkg/kv/kvserver/replica_metrics_test.go
  pkg/kv/kvserver/replicate_queue.go
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/kv/kvserver/store.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#130061 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130060 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130059 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130158 pkg/util/log: Fix FileSink iteration logic
  pkg/util/log/registry.go
  pkg/util/log/registry_test.go
Labels: O-support, backport-23.2.x, backport-24.1.x, backport-24.2.x

#130057 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130188 release-24.2: roachtest: ensure workload node has same zone as cluster if unspecified
  .gitignore
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/test_test.go
  pkg/roachprod/vm/aws/aws.go
  pkg/roachprod/vm/azure/azure.go
  pkg/roachprod/vm/azure/flags.go
  pkg/roachprod/vm/gce/gcloud.go
Labels: backport

#130189 release-24.1: roachtest: ensure workload node has same zone as cluster if unspecified
  .gitignore
  pkg/cmd/roachtest/.DS_Store
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/test_test.go
  pkg/cmd/roachtest/testdata/.DS_Store
  pkg/roachprod/vm/aws/aws.go
  pkg/roachprod/vm/gce/gcloud.go
Labels: backport

#130084 raft: fix flaky leader index in waitLeader function
  pkg/raft/rafttest/BUILD.bazel
  pkg/raft/rafttest/node_test.go
Labels: backport-24.1.x, backport-24.2.x

#130051 release-24.1: metric: add cidr based routing
  pkg/BUILD.bazel
  pkg/ccl/storageccl/BUILD.bazel
  pkg/ccl/storageccl/external_sst_reader_test.go
  pkg/cli/BUILD.bazel
  pkg/cli/debug.go
  pkg/cloud/BUILD.bazel
  pkg/cloud/amazon/aws_kms.go
  pkg/cloud/amazon/s3_storage.go
  pkg/cloud/amazon/s3_storage_test.go
  pkg/cloud/azure/azure_storage.go
  pkg/cloud/azure/azure_storage_test.go
  pkg/cloud/cloud_io.go
  pkg/cloud/external_storage.go
  pkg/cloud/gcp/gcs_storage.go
  pkg/cloud/httpsink/http_storage.go
  pkg/cloud/impl_registry.go
  pkg/cloud/metrics.go
  pkg/server/BUILD.bazel
  pkg/server/config.go
  pkg/server/config_test.go
  pkg/server/server.go
  pkg/server/server_sql.go
  pkg/sql/BUILD.bazel
  pkg/sql/conn_executor.go
  pkg/sql/exec_util.go
  pkg/sql/pgwire/BUILD.bazel
  pkg/sql/pgwire/command_result_test.go
  pkg/sql/pgwire/conn.go
  pkg/sql/pgwire/conn_test.go
  pkg/sql/pgwire/encoding_test.go
  pkg/sql/pgwire/pre_serve.go
  pkg/sql/pgwire/server.go
  pkg/sql/pgwire/types_test.go
  pkg/sql/pgwire/write_buffer.go
  pkg/sql/sem/eval/BUILD.bazel
  pkg/sql/sem/eval/context.go
  pkg/util/cidr/BUILD.bazel
  pkg/util/cidr/cidr.go
  pkg/util/cidr/cidr_test.go
Labels: backport

#130050 release-24.1: rpc: add locality to dialing
  docs/generated/metrics/metrics.html
  pkg/acceptance/localcluster/cluster.go
  pkg/blobs/client_test.go
  pkg/ccl/serverccl/statusccl/tenant_grpc_test.go
  pkg/gossip/client.go
  pkg/gossip/client_test.go
  pkg/gossip/gossip.go
  pkg/gossip/gossip_test.go
  pkg/kv/kvclient/kvcoord/send_test.go
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/kv/kvserver/loqrecovery/server.go
  pkg/kv/kvserver/raft_transport.go
  pkg/kv/kvserver/raft_transport_unit_test.go
  pkg/rpc/BUILD.bazel
  pkg/rpc/client.go
  pkg/rpc/context.go
  pkg/rpc/context_test.go
  pkg/rpc/datadriven_test.go
  pkg/rpc/down_node_test.go
  pkg/rpc/metrics.go
  pkg/rpc/metrics_test.go
  pkg/rpc/mocks_generated_test.go
  pkg/rpc/nodedialer/nodedialer.go
  pkg/rpc/nodedialer/nodedialer_test.go
  pkg/rpc/peer.go
  pkg/server/connectivity_test.go
  pkg/server/fanout_clients.go
  pkg/server/node_http_router.go
  pkg/server/server.go
  pkg/server/server_sql.go
  pkg/server/status.go
  pkg/server/tenant.go
  pkg/server/testserver.go
  pkg/sql/crdb_internal.go
  pkg/sql/distsql/inbound_test.go
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/flowinfra/cluster_test.go
  pkg/sql/flowinfra/outbox_test.go
  pkg/sql/flowinfra/utils_test.go
  pkg/testutils/testcluster/testcluster.go
Labels: backport

#130126 release-23.2: obs: export metrics about Go GC Assist work; add chart
  docs/generated/metrics/metrics.html
  pkg/server/status/runtime.go
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/runtime.tsx
Labels: backport

#130259 release-24.2: raft: fix flaky leader index in waitLeader function
  pkg/raft/rafttest/BUILD.bazel
  pkg/raft/rafttest/node_test.go
Labels: backport

#130260 release-24.1: raft: fix flaky leader index in waitLeader function
  pkg/raft/rafttest/BUILD.bazel
  pkg/raft/rafttest/node_test.go
Labels: backport

#130202 release-23.2: roachprod: add ZFS option for AWS
  pkg/roachprod/roachprod.go
  pkg/roachprod/vm/aws/aws.go
  pkg/roachprod/vm/aws/support.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport

#130273 gssapiccl: fix kerberos memory leak
  pkg/ccl/gssapiccl/get_user.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-23.1.26-rc

#130173 release-24.1: roachtest: remove libGEOS requirement from acceptance/version-upgrade
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
  pkg/cmd/roachtest/tests/acceptance.go
Labels: backport

#130228 release-24.1: pkg/util/log: Fix FileSink iteration logic
  pkg/util/log/registry.go
  pkg/util/log/registry_test.go
Labels: backport

#130326 release-23.1: licenseccl: rename usage to environment
  pkg/ccl/utilccl/licenseccl/license.proto
Labels: backport

#130324 release-24.1: licenseccl: rename usage to environment
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/ccl/utilccl/licenseccl/license.go
  pkg/ccl/utilccl/licenseccl/license.proto
Labels: backport

#130323 release-24.2: licenseccl: rename usage to environment
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/ccl/utilccl/licenseccl/license.go
  pkg/ccl/utilccl/licenseccl/license.proto
Labels: backport

#130339 release-24.2: released CockroachDB version 24.2.1. Next version: 24.2.2
  pkg/build/version.txt
Labels: backport

#129948 server: remove server.shutdown.jobs.timeout from public docs
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/server/drain.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#130351 workload/schemachanger: ignore unique violation errors for CREATE INDEX
  pkg/workload/schemachange/operation_generator.go
Labels: backport-24.1.x, backport-24.2.x

#129420 ui: add license change notification to db console
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/alertbox.styl
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/icons/index.tsx
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-23.1.26-rc

#129946 changefeedccl: update changefeed.sink_io_workers description
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/changefeedccl/changefeedbase/settings.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#130379 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130377 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130376 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130380 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130247 release-24.2: kvserver: enqueue decom ranges at an interval behind a setting
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_init.go
  pkg/kv/kvserver/replica_metrics.go
  pkg/kv/kvserver/replica_metrics_test.go
  pkg/kv/kvserver/replicate_queue.go
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/kv/kvserver/store.go
Labels: backport

#130248 release-24.1: kvserver: enqueue decom ranges at an interval behind a setting
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_init.go
  pkg/kv/kvserver/replica_metrics.go
  pkg/kv/kvserver/replica_metrics_test.go
  pkg/kv/kvserver/replicate_queue.go
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/kv/kvserver/store.go
Labels: backport

#130103 opt: add NOWAIT to unlocked scans below NOWAIT
  pkg/ccl/logictestccl/testdata/logic_test/select_for_update_read_committed
  pkg/sql/logictest/testdata/logic_test/select_for_update
  pkg/sql/opt/locking.go
  pkg/sql/opt/optbuilder/locking.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/testdata/select_for_update
Labels: backport-24.1.x, backport-24.2.x

#130335 release-24.2: opt: add PushLimitIntoProjectFilteredScan
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/xform/limit_funcs.go
  pkg/sql/opt/xform/rules/limit.opt
  pkg/sql/opt/xform/testdata/rules/limit
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#130336 release-24.1: opt: add PushLimitIntoProjectFilteredScan
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/xform/limit_funcs.go
  pkg/sql/opt/xform/rules/limit.opt
  pkg/sql/opt/xform/testdata/rules/limit
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#130251 release-23.2: kvserver: enqueue decom ranges at an interval behind a setting
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_init.go
  pkg/kv/kvserver/replica_metrics.go
  pkg/kv/kvserver/replica_metrics_test.go
  pkg/kv/kvserver/replicate_queue.go
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/kv/kvserver/store.go
Labels: backport

#130413 release-23.2.11-rc: kvserver: enqueue decom ranges at an interval behind a setting
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_init.go
  pkg/kv/kvserver/replica_metrics.go
  pkg/kv/kvserver/replica_metrics_test.go
  pkg/kv/kvserver/replicate_queue.go
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/kv/kvserver/store.go
Labels: backport

#130254 release-23.1: kvserver: enqueue decom ranges at an interval behind a setting
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_init.go
  pkg/kv/kvserver/replica_metrics.go
  pkg/kv/kvserver/replica_metrics_test.go
  pkg/kv/kvserver/replicate_queue.go
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/kv/kvserver/store.go
  pkg/ts/catalog/chart_catalog.go
Labels: backport

#130064 upgrade: dynamically adjust batch size for automatic descriptor repair
  pkg/upgrade/upgrades/BUILD.bazel
  pkg/upgrade/upgrades/first_upgrade.go
  pkg/upgrade/upgrades/first_upgrade_test.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#130435 roachtest/ruby-pg: mark connection timeout test as flaky
  pkg/cmd/roachtest/tests/ruby_pg_blocklist.go
Labels: branch-release-24.1, branch-release-24.2

#130443 backupccl: deflake TestDataDriven/system-pivileges-table
  pkg/ccl/backupccl/testdata/backup-restore/system-privileges-table
Labels: T-disaster-recovery, backport-23.2.x, backport-24.1.x, backport-24.2.x

#130271 workload/schemachange: enable alter pk
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/sem/builtins/BUILD.bazel
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/workload/schemachange/operation_generator.go
  pkg/workload/schemachange/optype.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#130448 release-23.1: Revert "release-23.1: storage: fix comparison of suffixes"
  pkg/storage/pebble.go
  pkg/storage/pebble_test.go
Labels: backport

#130457 release-24.1.5-rc: Revert "release-24.1: storage: fix comparison of suffixes"
  pkg/storage/pebble.go
  pkg/storage/pebble_test.go
Labels: backport

#130540 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130538 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130541 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130537 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130366 opt: do not plan uniqueness checks for partial, hash-sharded indexes
  pkg/sql/opt/exec/execbuilder/testdata/hash_sharded_index
  pkg/sql/opt/optbuilder/mutation_builder_unique.go
Labels: backport-24.1.x, backport-24.2.x

#130343 release-23.2: sqlliveness: handle AmbiguousResultError gracefully on insert
  pkg/sql/sqlliveness/slinstance/BUILD.bazel
  pkg/sql/sqlliveness/slinstance/slinstance.go
  pkg/sql/sqlliveness/slinstance/slinstance_test.go
Labels: backport

#130511 release-24.2.2-rc: ui: add license change notification to db console
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/alertbox.styl
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/icons/index.tsx
Labels: backport

#130417 release-24.2: ui: add license change notification to db console
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/alertbox.styl
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/icons/index.tsx
Labels: backport

#129878 release-23.1: base, licenseccl: Revise resolution strategy for LicenseTTL
  pkg/base/license.go
  pkg/ccl/ccl_init.go
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/server.go
  pkg/ts/catalog/chart_catalog.go
Labels: backport

#130510 release-24.1.5-rc: ui: add license change notification to db console
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/alertbox.styl
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/icons/index.tsx
Labels: backport

#130426 release-24.1: ui: add license change notification to db console
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/alertbox.styl
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/icons/index.tsx
Labels: backport

#130509 release-23.2.11-rc: ui: add license change notification to db console
  pkg/server/server_http.go
  pkg/server/server_test.go
  pkg/ui/BUILD.bazel
  pkg/ui/ui.go
  pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/state.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/dataFromServer.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/alertbox.styl
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/icons/index.tsx
Labels: backport

#130425 release-23.2: ui: add license change notification to db console
  pkg/server/server_http.go
  pkg/server/server_test.go
  pkg/ui/BUILD.bazel
  pkg/ui/ui.go
  pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/state.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/dataFromServer.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/alertbox.styl
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/icons/index.tsx
Labels: backport

#130439 release-23.1: ui: add license change notification to db console
  pkg/server/server_http.go
  pkg/server/server_test.go
  pkg/ui/BUILD.bazel
  pkg/ui/ui.go
  pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.spec.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/state.ts
  pkg/ui/workspaces/db-console/src/redux/uiData.ts
  pkg/ui/workspaces/db-console/src/util/dataFromServer.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/alertbox.styl
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBox/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/icons/index.tsx
Labels: backport

#130204 changefeedccl: fix memory leak in cloud storage sink with fast gzip
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/sink_cloudstorage.go
  pkg/ccl/changefeedccl/sink_cloudstorage_test.go
  pkg/ccl/changefeedccl/testing_knobs.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.2.2-rc, backport-23.2.11, backport-24.1.5-rc

#129879 release-23.2: base, licenseccl: Revise resolution strategy for LicenseTTL
  pkg/base/license.go
  pkg/ccl/ccl_init.go
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/server.go
Labels: backport

#130517 release-24.2: upgrade: dynamically adjust batch size for automatic descriptor repair
  pkg/kv/txn.go
  pkg/upgrade/upgrades/BUILD.bazel
  pkg/upgrade/upgrades/first_upgrade.go
  pkg/upgrade/upgrades/first_upgrade_test.go
Labels: backport

#130518 release-24.1: upgrade: dynamically adjust batch size for automatic descriptor repair
  pkg/kv/txn.go
  pkg/upgrade/upgrades/BUILD.bazel
  pkg/upgrade/upgrades/first_upgrade.go
  pkg/upgrade/upgrades/first_upgrade_test.go
Labels: backport

#130519 release-23.2: upgrade: dynamically adjust batch size for automatic descriptor repair
  pkg/upgrade/upgrades/BUILD.bazel
  pkg/upgrade/upgrades/first_upgrade.go
  pkg/upgrade/upgrades/first_upgrade_test.go
Labels: backport

#130627 Revert "release-24.2: storage: fix comparison of suffixes"
  pkg/storage/pebble.go
  pkg/storage/pebble_test.go
Labels: backport, backport-24.2.3-rc

#130623 release-23.1: kv: retry liveness heartbeat on race with insufficient expiration
  pkg/kv/kvserver/liveness/liveness.go
  pkg/kv/kvserver/replica_range_lease.go
Labels: backport

#130621 release-24.1: fix cidr lookup issues
  pkg/util/cidr/cidr.go
Labels: backport

#130521 release-23.2: rpc: add locality to dialing
  docs/generated/metrics/metrics.html
  pkg/acceptance/localcluster/cluster.go
  pkg/blobs/client_test.go
  pkg/ccl/serverccl/statusccl/tenant_grpc_test.go
  pkg/gossip/client.go
  pkg/gossip/client_test.go
  pkg/gossip/gossip.go
  pkg/gossip/gossip_test.go
  pkg/kv/kvclient/kvcoord/send_test.go
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/kv/kvserver/loqrecovery/server.go
  pkg/kv/kvserver/raft_transport.go
  pkg/kv/kvserver/raft_transport_unit_test.go
  pkg/rpc/BUILD.bazel
  pkg/rpc/client.go
  pkg/rpc/context.go
  pkg/rpc/context_test.go
  pkg/rpc/datadriven_test.go
  pkg/rpc/down_node_test.go
  pkg/rpc/metrics.go
  pkg/rpc/metrics_test.go
  pkg/rpc/mocks_generated_test.go
  pkg/rpc/nodedialer/nodedialer.go
  pkg/rpc/nodedialer/nodedialer_test.go
  pkg/rpc/peer.go
  pkg/server/connectivity_test.go
  pkg/server/fanout_clients.go
  pkg/server/node_http_router.go
  pkg/server/server.go
  pkg/server/server_sql.go
  pkg/server/status.go
  pkg/server/tenant.go
  pkg/server/testserver.go
  pkg/sql/crdb_internal.go
  pkg/sql/distsql/inbound_test.go
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/flowinfra/cluster_test.go
  pkg/sql/flowinfra/outbox_test.go
  pkg/sql/flowinfra/utils_test.go
  pkg/testutils/testcluster/testcluster.go
Labels: backport

#130528 release-23.2: metric: add cidr based routing
  pkg/BUILD.bazel
  pkg/cloud/BUILD.bazel
  pkg/cloud/amazon/aws_kms.go
  pkg/cloud/amazon/s3_storage.go
  pkg/cloud/amazon/s3_storage_test.go
  pkg/cloud/azure/azure_storage.go
  pkg/cloud/azure/azure_storage_test.go
  pkg/cloud/cloud_io.go
  pkg/cloud/gcp/BUILD.bazel
  pkg/cloud/gcp/gcs_storage.go
  pkg/cloud/httpsink/http_storage.go
  pkg/cloud/metrics.go
  pkg/server/BUILD.bazel
  pkg/server/config.go
  pkg/server/config_test.go
  pkg/server/external_storage_builder.go
  pkg/server/server.go
  pkg/server/server_sql.go
  pkg/server/tenant.go
  pkg/sql/BUILD.bazel
  pkg/sql/conn_executor.go
  pkg/sql/exec_util.go
  pkg/sql/pgwire/BUILD.bazel
  pkg/sql/pgwire/command_result_test.go
  pkg/sql/pgwire/conn.go
  pkg/sql/pgwire/conn_test.go
  pkg/sql/pgwire/encoding_test.go
  pkg/sql/pgwire/pre_serve.go
  pkg/sql/pgwire/server.go
  pkg/sql/pgwire/types_test.go
  pkg/sql/pgwire/write_buffer.go
  pkg/sql/sem/eval/BUILD.bazel
  pkg/sql/sem/eval/context.go
  pkg/util/cidr/BUILD.bazel
  pkg/util/cidr/cidr.go
  pkg/util/cidr/cidr_test.go
Labels: backport

#130620 release-24.1.5-rc: fix cidr lookup issues
  pkg/util/cidr/cidr.go
Labels: backport

#130595 release-24.1: remove TestPauseReason
  pkg/jobs/jobs_test.go
Labels: T-disaster-recovery, backport

#130677 release-24.1: sqlproxyccl: skip TestFailedConnection under stress
  pkg/ccl/sqlproxyccl/BUILD.bazel
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
Labels: backport

#130676 release-24.2: sqlproxyccl: skip TestFailedConnection under stress
  pkg/ccl/sqlproxyccl/BUILD.bazel
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
Labels: backport

#129007 opt: fix BPCHAR type and CASE typing
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/local-read-committed/generated_test.go
  pkg/ccl/logictestccl/tests/local-repeatable-read/generated_test.go
  pkg/sql/logictest/testdata/logic_test/bpchar
  pkg/sql/logictest/testdata/logic_test/case
  pkg/sql/logictest/testdata/logic_test/cast
  pkg/sql/logictest/testdata/logic_test/decimal
  pkg/sql/logictest/testdata/logic_test/drop_function
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/pg_builtins
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-mixed-24.1/generated_test.go
  pkg/sql/logictest/tests/local-mixed-24.2/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/opt/optbuilder/scalar.go
  pkg/sql/opt/optbuilder/testdata/scalar
  pkg/sql/opt/xform/testdata/external/tpcc
  pkg/sql/opt/xform/testdata/external/tpcc-later-stats
  pkg/sql/opt/xform/testdata/external/tpcc-no-stats
  pkg/sql/opt/xform/testdata/external/tpcc-read-committed
  pkg/sql/opt/xform/testdata/rules/select
  pkg/sql/schemachanger/comparator_generated_test.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/tree/overload.go
  pkg/sql/types/types.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#130664 release-23.2: changefeedccl: add network metrics
  docs/generated/metrics/metrics.html
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/changefeedccl/schema_registry_test.go
  pkg/ccl/changefeedccl/sink_external_connection.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_pubsub.go
  pkg/ccl/changefeedccl/sink_pubsub_v2.go
  pkg/ccl/changefeedccl/sink_sql.go
  pkg/ccl/changefeedccl/sink_webhook.go
  pkg/ccl/changefeedccl/sink_webhook_v2.go
  pkg/ccl/changefeedccl/telemetry.go
  pkg/jobs/BUILD.bazel
  pkg/jobs/metrics.go
  pkg/jobs/registry.go
  pkg/server/server_sql.go
  pkg/util/cidr/BUILD.bazel
  pkg/util/cidr/cidr.go
  pkg/util/cidr/cidr_test.go
Labels: backport

#130584 release-24.1.5-rc: changefeedccl: add network metrics
  docs/generated/metrics/metrics.html
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/changefeedccl/schema_registry_test.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_pubsub.go
  pkg/ccl/changefeedccl/sink_pubsub_v2.go
  pkg/ccl/changefeedccl/sink_sql.go
  pkg/ccl/changefeedccl/sink_webhook.go
  pkg/ccl/changefeedccl/sink_webhook_v2.go
  pkg/ccl/changefeedccl/telemetry.go
  pkg/jobs/BUILD.bazel
  pkg/jobs/metrics.go
  pkg/jobs/registry.go
  pkg/server/server_sql.go
  pkg/util/cidr/BUILD.bazel
  pkg/util/cidr/cidr.go
  pkg/util/cidr/cidr_test.go
Labels: backport

#130583 release-24.1: changefeedccl: add network metrics
  docs/generated/metrics/metrics.html
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/changefeedccl/schema_registry_test.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_pubsub.go
  pkg/ccl/changefeedccl/sink_pubsub_v2.go
  pkg/ccl/changefeedccl/sink_sql.go
  pkg/ccl/changefeedccl/sink_webhook.go
  pkg/ccl/changefeedccl/sink_webhook_v2.go
  pkg/ccl/changefeedccl/telemetry.go
  pkg/jobs/BUILD.bazel
  pkg/jobs/metrics.go
  pkg/jobs/registry.go
  pkg/server/server_sql.go
  pkg/util/cidr/BUILD.bazel
  pkg/util/cidr/cidr.go
  pkg/util/cidr/cidr_test.go
Labels: backport

#130582 release-24.2.3-rc: changefeedccl: add network metrics
  docs/generated/metrics/metrics.html
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/changefeedccl/schema_registry_test.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_pubsub.go
  pkg/ccl/changefeedccl/sink_pubsub_v2.go
  pkg/ccl/changefeedccl/sink_sql.go
  pkg/ccl/changefeedccl/sink_webhook.go
  pkg/ccl/changefeedccl/sink_webhook_v2.go
  pkg/ccl/changefeedccl/telemetry.go
  pkg/jobs/BUILD.bazel
  pkg/jobs/metrics.go
  pkg/jobs/registry.go
  pkg/server/server_sql.go
  pkg/util/cidr/BUILD.bazel
  pkg/util/cidr/cidr.go
  pkg/util/cidr/cidr_test.go
Labels: backport

#130578 release-24.2: changefeedccl: add network metrics
  docs/generated/metrics/metrics.html
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/changefeedccl/schema_registry_test.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_pubsub.go
  pkg/ccl/changefeedccl/sink_pubsub_v2.go
  pkg/ccl/changefeedccl/sink_sql.go
  pkg/ccl/changefeedccl/sink_webhook.go
  pkg/ccl/changefeedccl/sink_webhook_v2.go
  pkg/ccl/changefeedccl/telemetry.go
  pkg/jobs/BUILD.bazel
  pkg/jobs/metrics.go
  pkg/jobs/registry.go
  pkg/server/server_sql.go
  pkg/util/cidr/BUILD.bazel
  pkg/util/cidr/cidr.go
  pkg/util/cidr/cidr_test.go
Labels: backport

#130591 release-23.2: kvserver: compact liveness range periodically
  pkg/kv/kvserver/liveness/client_test.go
  pkg/server/node.go
Labels: backport

#130665 changefeedccl: skip TestCloudStorageSinkFastGzip under race
  pkg/ccl/changefeedccl/sink_cloudstorage_test.go
Labels: backport-24.1.x, backport-24.2.x

#130717 CODEOWNERS: update multitenant_admin_function_test.go to sql-foundations
  .github/CODEOWNERS
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#130654 release-23.1: server: fix race in `TestCachedSettingsServerRestart`.
  pkg/server/settings_cache_test.go
Labels: backport

#130709 util: publish cidr metrics for tenants
  pkg/server/tenant.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.2.3-rc, backport-23.2.12-rc, backport-24.1.5-rc

#130789 release-23.2: released CockroachDB version 23.2.11. Next version: 23.2.12
  pkg/build/version.txt
Labels: backport

#130796 roachtest: improve observability in kv/gracefuldraining
  pkg/cmd/roachtest/tests/kv.go
  pkg/kv/kvserver/liveness/liveness.go
Labels: backport-24.2.x

#130819 release-23.1: released CockroachDB version 23.1.26. Next version: 23.1.27
  pkg/build/version.txt
Labels: backport

#130698 release-23.2: scjob: treat descriptor not found as permanent job error
  pkg/jobs/errors.go
  pkg/sql/schemachanger/scjob/BUILD.bazel
  pkg/sql/schemachanger/scjob/job.go
Labels: backport

#130823 logictest: handle flake when cluster initializes
  pkg/sql/logictest/logic.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#130718 crosscluster/logical: check for empty DLQ and fingerprint in ldr roachtests
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/logical/udf_row_processor_test.go
  pkg/ccl/crosscluster/replicationtestutils/BUILD.bazel
  pkg/ccl/crosscluster/replicationtestutils/logical.go
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/logical_data_replication.go
Labels: T-disaster-recovery

#130849 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130848 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130847 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#130850 server, util: fix failing TestServerController
  pkg/server/server.go
  pkg/server/server_controller_channel_orchestrator.go
  pkg/server/tenant.go
  pkg/util/cidr/cidr.go
  pkg/util/cidr/cidr_test.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.2.3-rc, backport-23.2.12-rc, backport-24.1.5-rc

#130878 release-24.1.5-rc: telemetryccl_test: fix TestTelemetry
  pkg/ccl/telemetryccl/testdata/telemetry/generic
Labels: backport

#130877 release-23.2.12-rc: telemetryccl_test: fix TestTelemetry
  pkg/ccl/telemetryccl/testdata/telemetry/generic
Labels: backport

#130875 release-24.1: telemetryccl_test: fix TestTelemetry
  pkg/ccl/telemetryccl/testdata/telemetry/generic
Labels: backport

#130892 ccl/sqlproxyccl: add proxy.sql.routing_method_count metric
  pkg/ccl/sqlproxyccl/BUILD.bazel
  pkg/ccl/sqlproxyccl/metrics.go
  pkg/ccl/sqlproxyccl/proxy_handler.go
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
Labels: backport-24.2.x

#130622 changefeedccl: protect system.comments and system.zones
  pkg/ccl/changefeedccl/protected_timestamps.go
  pkg/ccl/changefeedccl/protected_timestamps_test.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#130891 release-24.1.5-rc: server/license: fix race in concurrent test-server startup
  pkg/server/license/BUILD.bazel
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/server_sql.go
Labels: backport

#130869 release-24.1: server/license: Integrate license throttle with SQL
  pkg/ccl/utilccl/license_check.go
  pkg/server/diagnostics/reporter.go
  pkg/server/license/BUILD.bazel
  pkg/server/license/cclbridge.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/server_sql.go
  pkg/sql/BUILD.bazel
  pkg/sql/conn_executor_exec.go
  pkg/sql/conn_executor_internal_test.go
Labels: backport

#130872 release-23.1: server/license: Integrate license throttle with SQL
  pkg/ccl/utilccl/license_check.go
  pkg/server/diagnostics/reporter.go
  pkg/server/license/BUILD.bazel
  pkg/server/license/cclbridge.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/server_sql.go
  pkg/sql/BUILD.bazel
  pkg/sql/conn_executor_exec.go
  pkg/sql/conn_executor_internal_test.go
Labels: backport

#130871 release-23.2: server/license: Integrate license throttle with SQL
  pkg/ccl/utilccl/license_check.go
  pkg/server/diagnostics/reporter.go
  pkg/server/license/BUILD.bazel
  pkg/server/license/cclbridge.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/server_sql.go
  pkg/sql/BUILD.bazel
  pkg/sql/conn_executor_exec.go
  pkg/sql/conn_executor_internal_test.go
Labels: backport

#130907 sqlproxyccl: static directory server lists pods when watch starts
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
  pkg/ccl/sqlproxyccl/tenantdirsvr/BUILD.bazel
  pkg/ccl/sqlproxyccl/tenantdirsvr/test_static_directory_svr.go
Labels: backport-24.2.x

#130966 release-23.1: changefeedccl: deflake TestChangefeedSchemaChangeBackfillCheckpoint
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport

#130954 changefeedccl: set debugUseAfterFinish option in a test
  pkg/base/test_server_args.go
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/encoder_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/server/testserver.go
Labels: backport-23.2.x

#130950 release-24.1: storage: GC range keys by unsetting identical suffixes
  pkg/ccl/streamingccl/replicationutils/utils.go
  pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go
  pkg/kv/kvserver/batcheval/cmd_delete_range_test.go
  pkg/kv/kvserver/batcheval/knobs_use_range_tombstones_test.go
  pkg/kv/kvserver/gc/gc_random_test.go
  pkg/kv/kvserver/gc/gc_test.go
  pkg/storage/mvcc_history_test.go
  pkg/storage/mvcc_key.go
  pkg/storage/mvcc_key_test.go
  pkg/storage/mvcc_test.go
  pkg/storage/pebble.go
  pkg/storage/pebble_batch.go
  pkg/storage/pebble_iterator.go
  pkg/storage/sst_writer.go
  pkg/storage/testdata/mvcc_histories/range_key_clear_synthetic_bit
  pkg/testutils/storageutils/kv.go
Labels: backport

#130897 changefeedccl: add changefeed.total_ranges metric
  docs/generated/metrics/metrics.html
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/kvfeed/physical_kv_feed.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#130925 opt: do not remap columns under a grouping operator
  pkg/sql/logictest/testdata/logic_test/subquery
  pkg/sql/opt/norm/decorrelate_funcs.go
  pkg/sql/opt/norm/testdata/rules/decorrelate
  pkg/sql/opt/xform/testdata/external/hibernate
  pkg/sql/opt/xform/testdata/rules/disjunction_in_join
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#130970 backupccl: clarify timeout error message
  pkg/ccl/backupccl/backup_processor.go
Labels: backport-24.1.x, backport-24.2.x

#130964 release-23.2: sql: handle dropped descriptors when waiting for schema changes
  pkg/sql/conn_executor.go
  pkg/sql/schema_change_plan_node.go
Labels: backport

#130725 opt: do not include virtual computed columns in lock columns
  pkg/ccl/logictestccl/testdata/logic_test/read_committed
  pkg/sql/logictest/logic.go
  pkg/sql/opt/exec/execbuilder/testdata/select_for_update_read_committed
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/norm/testdata/rules/limit
  pkg/sql/opt/norm/testdata/rules/mutation
  pkg/sql/opt/optbuilder/locking.go
  pkg/sql/opt/optbuilder/testdata/read-committed
  pkg/sql/opt/optbuilder/testdata/select_for_update
  pkg/sql/opt/xform/testdata/external/tpcc-read-committed
  pkg/sql/opt/xform/testdata/rules/limit
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#129070 changefeedccl: don't hide error encountered during table resolution
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#131018 multiregionccl: deflake TestMrSystemDatabase
  pkg/ccl/multiregionccl/multiregion_system_table_test.go
Labels: backport-23.2.x, backport-24.1.x

#131034 release-23.1: sql/catalog/lease: collect stats in TestDescriptorRefreshOnRetry
  pkg/sql/catalog/lease/lease_test.go
Labels: backport

#131033 release-23.2: sql/catalog/lease: collect stats in TestDescriptorRefreshOnRetry
  pkg/sql/catalog/lease/lease_test.go
Labels: backport

#131047 release-23.2: multiregionccl: deflake TestMrSystemDatabase
  pkg/ccl/multiregionccl/multiregion_system_table_test.go
Labels: backport

#131044 release-24.1: multiregionccl: deflake TestMrSystemDatabase
  pkg/ccl/multiregionccl/multiregion_system_table_test.go
Labels: backport

#129732 dev: also build `ts_project` for `eslint-plugin-crdb` in `gen js`
  pkg/cmd/dev/generate.go
Labels: backport-24.1.x, backport-24.2.x
