Repository cockroachdb/cockroach, pull requests merged in 2024-12, with the labels that each got.

#136226 release-24.3: security: bugfix, ensure cert expiry metrics reflect reloaded certs
  pkg/security/certificate_manager.go
  pkg/security/certificate_metrics.go
  pkg/security/certificate_metrics_test.go
Labels: backport

#136227 release-24.3.1-rc: security: bugfix, ensure cert expiry metrics reflect reloaded certs
  pkg/security/certificate_manager.go
  pkg/security/certificate_metrics.go
  pkg/security/certificate_metrics_test.go
Labels: backport

#136326 release-24.3: roachprod: add sufficient tenant ids when creating v22.2 client certs
  pkg/roachprod/install/cluster_synced.go
Labels: backport

#136074 release-24.1: upgrades: fix destructive upgrade bug that was introduced when permanent upgrades were flattened
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/idempotent_permanent_upgrades.go
  pkg/cmd/roachtest/tests/registry.go
  pkg/upgrade/upgrademanager/BUILD.bazel
  pkg/upgrade/upgrademanager/manager.go
Labels: backport

#136507 cockroach-oss: delete build target
  .github/CODEOWNERS
  BUILD.bazel
  build/github/build.sh
  build/teamcity/cockroach/ci/builds/build_impl.sh
  pkg/BUILD.bazel
  pkg/cmd/cockroach-oss/BUILD.bazel
  pkg/cmd/cockroach-oss/main.go
  pkg/cmd/dev/build.go
  pkg/cmd/dev/ui.go
  pkg/gen/genbzl/targets.go
  pkg/gen/ui.bzl
  pkg/ui/distoss/BUILD.bazel
  pkg/ui/distoss/assets/.gitkeep
  pkg/ui/distoss/distoss.go
  pkg/ui/distoss/distoss_no_bazel.go
  pkg/ui/ui.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#136589 release-23.1: cockroach-oss: delete build target
  .github/CODEOWNERS
  BUILD.bazel
  build/teamcity/cockroach/ci/builds/build_impl.sh
  pkg/BUILD.bazel
  pkg/cmd/cockroach-oss/BUILD.bazel
  pkg/cmd/cockroach-oss/main.go
  pkg/cmd/dev/build.go
  pkg/cmd/dev/ui.go
  pkg/gen/genbzl/targets.go
  pkg/gen/ui.bzl
  pkg/ui/distoss/BUILD.bazel
  pkg/ui/distoss/assets/.gitkeep
  pkg/ui/distoss/distoss.go
  pkg/ui/distoss/distoss_no_bazel.go
  pkg/ui/ui.go
Labels: backport

#136586 release-23.2: cockroach-oss: delete build target
  .github/CODEOWNERS
  BUILD.bazel
  build/teamcity/cockroach/ci/builds/build_impl.sh
  pkg/BUILD.bazel
  pkg/cmd/cockroach-oss/BUILD.bazel
  pkg/cmd/cockroach-oss/main.go
  pkg/cmd/dev/build.go
  pkg/cmd/dev/ui.go
  pkg/gen/genbzl/targets.go
  pkg/gen/ui.bzl
  pkg/ui/distoss/BUILD.bazel
  pkg/ui/distoss/assets/.gitkeep
  pkg/ui/distoss/distoss.go
  pkg/ui/distoss/distoss_no_bazel.go
  pkg/ui/ui.go
Labels: backport

#136585 release-24.1: cockroach-oss: delete build target
  .github/CODEOWNERS
  BUILD.bazel
  build/github/build.sh
  build/teamcity/cockroach/ci/builds/build_impl.sh
  pkg/BUILD.bazel
  pkg/cmd/cockroach-oss/BUILD.bazel
  pkg/cmd/cockroach-oss/main.go
  pkg/cmd/dev/build.go
  pkg/cmd/dev/ui.go
  pkg/gen/genbzl/targets.go
  pkg/gen/ui.bzl
  pkg/ui/distoss/BUILD.bazel
  pkg/ui/distoss/assets/.gitkeep
  pkg/ui/distoss/distoss.go
  pkg/ui/distoss/distoss_no_bazel.go
  pkg/ui/ui.go
Labels: backport

#136584 release-24.2: cockroach-oss: delete build target
  .github/CODEOWNERS
  BUILD.bazel
  build/github/build.sh
  build/teamcity/cockroach/ci/builds/build_impl.sh
  pkg/BUILD.bazel
  pkg/cmd/cockroach-oss/BUILD.bazel
  pkg/cmd/cockroach-oss/main.go
  pkg/cmd/dev/build.go
  pkg/cmd/dev/ui.go
  pkg/gen/genbzl/targets.go
  pkg/gen/ui.bzl
  pkg/ui/distoss/BUILD.bazel
  pkg/ui/distoss/assets/.gitkeep
  pkg/ui/distoss/distoss.go
  pkg/ui/distoss/distoss_no_bazel.go
  pkg/ui/ui.go
Labels: backport

#136502 release-24.2: sql/schemachanger: Exclude schema change wait time from idle session timeout
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/run_control_test.go
Labels: backport

#136503 release-24.1: sql/schemachanger: Exclude schema change wait time from idle session timeout
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/run_control_test.go
Labels: backport

#136508 release-23.2: sql/schemachanger: Exclude schema change wait time from idle session timeout
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/run_control_test.go
Labels: backport

#136523 kv: only declare abort span key when txn has locks
  pkg/kv/kvserver/batcheval/declare.go
Labels: o-perf-efficiency

#136261 ui: updates useSWR hooks to include clusterId in key
  pkg/ui/pnpm-lock.yaml
  pkg/ui/workspaces/cluster-ui/package.json
  pkg/ui/workspaces/cluster-ui/src/api/clusterSettingsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/databases/getDatabaseMetadataApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/databases/getTableMetadataApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/databases/grantsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/databases/tableIndexesApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/databases/tableMetaUpdateJobApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/nodesApi.ts
  pkg/ui/workspaces/cluster-ui/src/contexts/clusterDetailsContext.tsx
  pkg/ui/workspaces/cluster-ui/src/util/hooks.spec.tsx
  pkg/ui/workspaces/cluster-ui/src/util/hooks.ts
  pkg/ui/workspaces/cluster-ui/src/util/index.ts
Labels: backport-24.3.x

#136631 colexec: add cancellation check to top K sort and merge join
  pkg/sql/colexec/colexecjoin/mergejoiner.go
  pkg/sql/colexec/colexecjoin/mergejoiner_exceptall.eg.go
  pkg/sql/colexec/colexecjoin/mergejoiner_fullouter.eg.go
  pkg/sql/colexec/colexecjoin/mergejoiner_inner.eg.go
  pkg/sql/colexec/colexecjoin/mergejoiner_intersectall.eg.go
  pkg/sql/colexec/colexecjoin/mergejoiner_leftanti.eg.go
  pkg/sql/colexec/colexecjoin/mergejoiner_leftouter.eg.go
  pkg/sql/colexec/colexecjoin/mergejoiner_leftsemi.eg.go
  pkg/sql/colexec/colexecjoin/mergejoiner_rightanti.eg.go
  pkg/sql/colexec/colexecjoin/mergejoiner_rightouter.eg.go
  pkg/sql/colexec/colexecjoin/mergejoiner_rightsemi.eg.go
  pkg/sql/colexec/colexecjoin/mergejoiner_tmpl.go
  pkg/sql/colexec/sorttopk.eg.go
  pkg/sql/colexec/sorttopk.go
  pkg/sql/colexec/sorttopk_tmpl.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#136639 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#136640 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#136642 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#136643 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#136644 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#136243 crosscluster/logical: move job txn into helper
  pkg/crosscluster/logical/create_logical_replication_stmt.go
Labels: T-disaster-recovery

#136683 crosscluster/logical: type check dest tenant spec in planHookFn
  pkg/crosscluster/physical/alter_replication_job.go
  pkg/crosscluster/physical/alter_replication_job_test.go
Labels: T-disaster-recovery, backport-24.2.x, backport-24.3.x

#136162 release-24.3: sql: avoid unnecessary singleflight requests for role membership cache
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/bench/rttanalysis/testdata/benchmark_expectations
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/logictestccl/testdata/logic_test/as_of
  pkg/settings/registry.go
  pkg/sql/authorization.go
  pkg/sql/crdb_internal.go
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
  pkg/sql/user_test.go
Labels: backport

#136161 release-24.2: sql: avoid unnecessary singleflight requests for role membership cache
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/bench/rttanalysis/testdata/benchmark_expectations
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/logictestccl/testdata/logic_test/as_of
  pkg/settings/registry.go
  pkg/sql/authorization.go
  pkg/sql/crdb_internal.go
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
  pkg/sql/user_test.go
Labels: backport

#136483 release-24.1: logictest: remove unnecessary flaky assertion from synthetic_privileges test
  pkg/sql/logictest/testdata/logic_test/synthetic_privileges
Labels: backport

#136625 release-24.3: go.mod: bump Pebble to a7d74870cb20
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#136121 release-24.1: sql: avoid unnecessary singleflight requests for role membership cache
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/bench/rttanalysis/testdata/benchmark_expectations
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/logictestccl/testdata/logic_test/as_of
  pkg/settings/registry.go
  pkg/sql/authorization.go
  pkg/sql/crdb_internal.go
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
  pkg/sql/user_test.go
Labels: backport

#136608 dev: remove stale reference to `cockroach-oss`
  pkg/cmd/dev/build.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#136618 release-23.2: changefeedccl: change cdc latency hist bucket sizes
  pkg/ccl/changefeedccl/metrics.go
  pkg/util/metric/histogram_buckets.go
Labels: backport

#136698 release-24.3: crosscluster/logical: type check dest tenant spec in planHookFn
  pkg/ccl/crosscluster/physical/alter_replication_job.go
  pkg/ccl/crosscluster/physical/alter_replication_job_test.go
Labels: T-disaster-recovery, backport

#136699 release-24.2: crosscluster/logical: type check dest tenant spec in planHookFn
  pkg/ccl/crosscluster/physical/alter_replication_job.go
  pkg/ccl/crosscluster/physical/alter_replication_job_test.go
Labels: backport

#136725 roachtest: properly surface workload error in c2c tests
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: T-disaster-recovery, backport-24.3.x

#136241 sql: remove anonymous function allocation isPausiblePortal
  pkg/sql/conn_executor_exec.go
  pkg/sql/prepared_stmt.go
Labels: o-perf-efficiency

#136708 release-24.1: roachprod: add sufficient tenant ids when creating v22.2 client certs
  pkg/roachprod/install/cluster_synced.go
Labels: backport

#136688 roachtest: deflake activerecord test
  pkg/cmd/roachtest/tests/activerecord_blocklist.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#136491 catalog/replication: cleanup reader catalog tests
  pkg/sql/catalog/replication/reader_catalog_test.go
Labels: backport-24.3.x

#136724 changefeedccl: skip TestParallelIOMetrics under duress
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#136745 release-23.2: changefeedccl: support for multiple seed brokers in kafka v2 sink
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_kafka_v2_test.go
Labels: backport

#136746 release-24.1: changefeedccl: support for multiple seed brokers in kafka v2 sink
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_kafka_v2_test.go
Labels: backport

#136748 release-24.2: changefeedccl: support for multiple seed brokers in kafka v2 sink
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_kafka_v2_test.go
Labels: backport

#136822 release-24.3: go.mod: bump Pebble to cd54cd095c48
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/storage/pebble_key_schema_test.go
Labels: backport

#136139 colflow: skip TestVectorizedFlowDeadlocksWhenSpilling under duress
  pkg/sql/colflow/vectorized_flow_deadlock_test.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x

#136895 release-24.3: sql: inline `addActiveQuery` anonymous function
  pkg/sql/opt/bench/bench_test.go
Labels: backport

#136832 release-23.2: sql/stats: skip over histogram buckets for dropped enum values
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/stats/json.go
  pkg/sql/stats/stats_cache.go
  pkg/sql/types/types.go
Labels: backport

#136498 release-23.1: diagnostics: ignore timeout errors; extend client timeout
  pkg/ccl/serverccl/diagnosticsccl/reporter_test.go
  pkg/server/diagnostics/diagnostics.go
  pkg/server/diagnostics/reporter.go
  pkg/server/server_sql.go
  pkg/testutils/diagutils/diag_test_server.go
Labels: backport

#136831 release-24.1: sql/stats: skip over histogram buckets for dropped enum values
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/stats/json.go
  pkg/sql/stats/stats_cache.go
  pkg/sql/types/types.go
Labels: backport

#134988 release-24.3: ui, apiutil, server: surface multiple indexes within a range in the hot ranges page
  docs/generated/http/full.md
  pkg/BUILD.bazel
  pkg/roachpb/BUILD.bazel
  pkg/roachpb/data.go
  pkg/roachpb/key_test.go
  pkg/roachpb/metadata.go
  pkg/roachpb/metadata_test.go
  pkg/roachpb/span_test.go
  pkg/server/BUILD.bazel
  pkg/server/apiutil/BUILD.bazel
  pkg/server/apiutil/index_names.go
  pkg/server/apiutil/index_names_test.go
  pkg/server/apiutil/rangeutil.go
  pkg/server/apiutil/rangeutil_test.go
  pkg/server/serverpb/status.proto
  pkg/server/status.go
  pkg/sql/catalog/descs/collection.go
  pkg/sql/catalog/internal/catkv/BUILD.bazel
  pkg/sql/catalog/internal/catkv/catalog_reader.go
  pkg/sql/catalog/internal/catkv/catalog_reader_cached.go
  pkg/sql/catalog/internal/catkv/catalog_reader_test.go
  pkg/sql/catalog/internal/catkv/testdata/testdata_app
  pkg/sql/catalog/internal/catkv/testdata/testdata_system
  pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx
Labels: backport

#136907 rowinfra: clamp default-batch-bytes-limit under duress
  pkg/sql/rowinfra/base.go
  pkg/testutils/skip/constants.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#136809 CODEOWNERS: fine tune roachtest package-level ownership
  .github/CODEOWNERS
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#136076 sql: check for multiple mutations to the same table by triggers
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/sql/opt/optbuilder/fk_cascade.go
  pkg/sql/opt/optbuilder/mutation_builder_fk.go
  pkg/sql/opt/optbuilder/statement_tree.go
  pkg/sql/opt/optbuilder/statement_tree_test.go
  pkg/sql/opt/optbuilder/trigger.go
Labels: backport-24.3.x

#136953 release-24.2: CODEOWNERS: don't tag SQL Foundations for workload unit test failures
  .github/CODEOWNERS
Labels: backport

#136954 release-24.1: CODEOWNERS: don't tag SQL Foundations for workload unit test failures
  .github/CODEOWNERS
Labels: backport

#136955 release-23.2: CODEOWNERS: don't tag SQL Foundations for workload unit test failures
  .github/CODEOWNERS
Labels: backport

#136756 release-24.2: TestAllRegisteredSetup: skip test under deadlock
  pkg/ccl/workloadccl/allccl/all_test.go
Labels: backport

#136951 release-24.1: sql/schemachanger: log schema change job latency in structured log
  docs/generated/eventlog.md
  pkg/sql/logictest/testdata/logic_test/event_log
  pkg/sql/logictest/testdata/logic_test/event_log_legacy
  pkg/sql/logictest/testdata/logic_test/new_schema_changer
  pkg/sql/schema_changer.go
  pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go
  pkg/sql/schemachanger/scjob/job.go
  pkg/sql/schemachanger/scrun/BUILD.bazel
  pkg/sql/schemachanger/scrun/scrun.go
  pkg/sql/schemachanger/sctest/BUILD.bazel
  pkg/sql/schemachanger/sctest/end_to_end.go
  pkg/util/log/eventpb/ddl_events.proto
  pkg/util/log/eventpb/json_encode_generated.go
Labels: backport

#136952 release-23.2: sql/schemachanger: log schema change job latency in structured log
  docs/generated/eventlog.md
  pkg/sql/logictest/testdata/logic_test/event_log
  pkg/sql/logictest/testdata/logic_test/event_log_legacy
  pkg/sql/logictest/testdata/logic_test/new_schema_changer
  pkg/sql/schema_changer.go
  pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go
  pkg/sql/schemachanger/scjob/BUILD.bazel
  pkg/sql/schemachanger/scjob/job.go
  pkg/sql/schemachanger/scrun/BUILD.bazel
  pkg/sql/schemachanger/scrun/scrun.go
  pkg/sql/schemachanger/sctest/BUILD.bazel
  pkg/sql/schemachanger/sctest/end_to_end.go
  pkg/util/log/eventpb/ddl_events.proto
  pkg/util/log/eventpb/json_encode_generated.go
Labels: backport

#136785 sql: fix a race in TestShowTenantFingerprintsProtectsTimestamp
  pkg/sql/show_fingerprints_test.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#136978 catalog/descs: avoid log.Fatal for invalid descriptor error
  pkg/sql/catalog/descs/leased_descriptors.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#136941 rpc: avoid allocation of `TracingInternalClient` when tracing disabled
  pkg/rpc/nodedialer/nodedialer.go
Labels: o-perf-efficiency

#137051 release-24.3: roachtest: set waitForReplication to true by default for mvt
  build/teamcity/cockroach/nightlies/roachtest_weekly.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/tests/mixed_version_c2c.go
Labels: backport

#137025 pkg/cloud: Add no-op AWS_USE_PATH_STYLE param for forwards compatibility
  pkg/cloud/amazon/s3_storage.go
  pkg/cloud/amazon/s3_storage_test.go
Labels: backport-24.1.x

#137054 release-24.1: crosscluster/logical: type check dest tenant spec in planHookFn
  pkg/ccl/streamingccl/streamingest/alter_replication_job.go
  pkg/ccl/streamingccl/streamingest/alter_replication_job_test.go
Labels: T-disaster-recovery, backport

#137134 build: publish build metadata as a part of Make and Publish Build
  build/teamcity/internal/release/process/make-and-publish-build-tagging.sh
Labels: C-enhancement, A-release, T-release, backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#137108 kv: allocate Batch{Request|Response} header and {requests|responses} together
  pkg/kv/kvpb/batch_generated.go
  pkg/kv/kvpb/gen/main.go
  pkg/server/node.go
Labels: o-perf-efficiency

#137267 release: generate cloud-only images automatically
  build/teamcity/internal/release/process/build-cockroach-release-cloud-only.sh
Labels: C-enhancement, A-release, T-release, backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#137269 release-23.2: catalog/lease: deflake TestDescriptorRefreshOnRetry
  pkg/sql/catalog/lease/BUILD.bazel
  pkg/sql/catalog/lease/lease_test.go
Labels: backport

#135864 release-24.3: sql: display triggers in EXPLAIN output
  pkg/ccl/logictestccl/testdata/logic_test/generic
  pkg/ccl/logictestccl/testdata/logic_test/triggers_explain
  pkg/ccl/logictestccl/tests/local/generated_test.go
  pkg/sql/explain_plan.go
  pkg/sql/instrumentation.go
  pkg/sql/opt/cat/BUILD.bazel
  pkg/sql/opt/cat/trigger.go
  pkg/sql/opt/exec/execbuilder/post_queries.go
  pkg/sql/opt/exec/explain/emit.go
  pkg/sql/opt/exec/explain/explain_factory.go
  pkg/sql/opt/exec/explain/plan_gist_factory.go
  pkg/sql/opt/exec/explain/plan_gist_test.go
  pkg/sql/opt/exec/factory.go
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/opt/optbuilder/mutation_builder_fk.go
  pkg/sql/opt/optbuilder/testdata/trigger
  pkg/sql/opt/optbuilder/trigger.go
  pkg/sql/plan_opt.go
  pkg/sql/sem/tree/create_trigger.go
Labels: backport

#137242 backup: rewrite UDT oids in histograms when restoring table stats
  pkg/backup/restore_job.go
  pkg/backup/testdata/backup-restore/user-defined-types
  pkg/sql/catalog/rewrite/rewrite.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#137270 release-23.1: catalog/lease: deflake TestDescriptorRefreshOnRetry
  pkg/sql/catalog/lease/BUILD.bazel
  pkg/sql/catalog/lease/lease_test.go
Labels: backport

#137305 release-24.2: roachtest: disable 23.1 -> 23.2 testing for follower reads
  pkg/cmd/roachtest/tests/follower_reads.go
Labels: backport

#137306 release-24.1: roachtest: disable 23.1 -> 23.2 testing for follower reads
  pkg/cmd/roachtest/tests/follower_reads.go
Labels: backport

#137307 release-23.2: roachtest: disable 23.1 -> 23.2 testing for follower reads
  pkg/cmd/roachtest/tests/follower_reads.go
Labels: backport

#137316 release-23.2: roachtest: update mt-upgrade test owner to db-server
  pkg/cmd/roachtest/registry/owners.go
  pkg/cmd/roachtest/tests/multitenant_upgrade.go
Labels: backport

#137315 release-24.1: roachtest: update mt-upgrade test owner to db-server
  pkg/cmd/roachtest/registry/owners.go
  pkg/cmd/roachtest/tests/multitenant_upgrade.go
  pkg/kv/kvclient/.DS_Store
Labels: backport

#137314 release-24.2: roachtest: update mt-upgrade test owner to db-server
  pkg/cmd/roachtest/registry/owners.go
  pkg/cmd/roachtest/tests/multitenant_upgrade.go
Labels: backport

#137091 raft: add counters for flow state changes
  docs/generated/metrics/metrics.html
  pkg/raft/metrics.go
  pkg/raft/raft.go
Labels: backport-24.3.x

#137089 crosscluster/logical: create new tables if specified
  pkg/crosscluster/logical/BUILD.bazel
  pkg/crosscluster/logical/create_logical_replication_stmt.go
  pkg/crosscluster/logical/logical_replication_job_test.go
  pkg/jobs/jobspb/jobs.proto
  pkg/sql/catalog/externalcatalog/BUILD.bazel
  pkg/sql/catalog/externalcatalog/external_catalog.go
  pkg/sql/catalog/externalcatalog/external_catalog_test.go
Labels: T-disaster-recovery

#137361 optbuilder: always select tombstone index using the index ordinal
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_read_committed
  pkg/sql/opt/cat/table.go
  pkg/sql/opt/optbuilder/mutation_builder_unique.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/opt_catalog.go
Labels: backport-24.3.x, backport-24.3.1-rc

#137353 release-24.3: backup: rewrite UDT oids in histograms when restoring table stats
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/testdata/backup-restore/user-defined-types
  pkg/sql/catalog/rewrite/rewrite.go
Labels: backport

#137354 release-24.2: backup: rewrite UDT oids in histograms when restoring table stats
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/testdata/backup-restore/user-defined-types
  pkg/sql/catalog/rewrite/rewrite.go
Labels: backport

#137309 release-24.1: roachtest: deflake c2c tests
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: backport

#137398 release-24.3: send schema workload flakes in backup-restore tests directly to foundations
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
Labels: T-disaster-recovery, backport

#137400 release-24.2: send schema workload flakes in backup-restore tests directly to foundations
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
Labels: backport

#137399 release-24.1: send schema workload flakes in backup-restore tests directly to foundations
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
Labels: backport

#137219 tests/cdc: remove initial scan from changefeed assume role tests
  pkg/cmd/roachtest/tests/cdc.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#137356 release-23.2: backup: rewrite UDT oids in histograms when restoring table stats
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/testdata/backup-restore/user-defined-types
  pkg/sql/catalog/rewrite/rewrite.go
Labels: backport

#137355 release-24.1: backup: rewrite UDT oids in histograms when restoring table stats
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/testdata/backup-restore/user-defined-types
  pkg/sql/catalog/rewrite/rewrite.go
Labels: backport

#137453 release-23.2: jobspb: mark ResolvedSpan_BoundaryType as SafeValue
  pkg/jobs/jobspb/jobs.go
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
Labels: backport

#137468 oneof: batch allocate oneof wrapper and field messages
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: o-perf-efficiency

#137153 server,metrics: stop recording GaugeVec and CounterVec to tsdb
  docs/generated/metrics/metrics.html
  pkg/crosscluster/logical/metrics.go
  pkg/server/status/recorder.go
  pkg/server/status/recorder_test.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_test.go
Labels: backport-24.3.x

#137528 release-24.3: roachtest: disable rate limiters in mixedversion
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/separate_process
Labels: backport

#136837 release-23.2: kv: add a metric for rangefeeds waiting to perform catchup scans client-side
  docs/generated/metrics/metrics.html
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
Labels: backport

#137371 release-23.1: docgen: update BEGIN and SET TRANSACTION diagrams without iso level
  docs/generated/sql/bnf/BUILD.bazel
  docs/generated/sql/bnf/begin_stmt.bnf
  docs/generated/sql/bnf/legacy_begin_stmt.bnf
  docs/generated/sql/bnf/nonpreparable_set_stmt.bnf
  docs/generated/sql/bnf/set_transaction.bnf
  docs/generated/sql/bnf/set_transaction_stmt.bnf
  pkg/cmd/docgen/diagrams.go
  pkg/gen/bnf.bzl
  pkg/gen/diagrams.bzl
  pkg/gen/docs.bzl
Labels: backport

#137544 release-23.1: released CockroachDB version 23.1.30. Next version: 23.1.31
  pkg/build/version.txt
Labels: backport

#137546 release-23.2: log: deflake TestHTTPSinkTimeout
  pkg/util/log/http_sink_test.go
Labels: backport

#137525 sql/row: reduce allocations in initialization functions
  pkg/sql/row/kv_batch_fetcher.go
  pkg/sql/row/kv_batch_streamer.go
  pkg/sql/row/kv_fetcher.go
Labels: o-perf-efficiency

#137556 distsql: reduce allocations in setupFlow
  pkg/sql/distsql/server.go
Labels: o-perf-efficiency

#137577 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#137576 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#137574 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#137573 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#137572 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#137591 release-24.2: released CockroachDB version 24.2.6. Next version: 24.2.7
  pkg/build/version.txt
Labels: backport

#137600 release-24.3: raft: add raft fortification metrics
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/replica_init.go
  pkg/kv/kvserver/store.go
  pkg/raft/BUILD.bazel
  pkg/raft/metrics.go
  pkg/raft/node_test.go
  pkg/raft/raft.go
  pkg/raft/raft_test.go
  pkg/raft/raftstoreliveness/mock_store_liveness.go
  pkg/raft/rafttest/interaction_env_handler_add_nodes.go
  pkg/raft/rafttest/node.go
  pkg/roachprod/opentelemetry/cockroachdb_metrics.go
Labels: backport

#137599 release-24.3: kvserver: add metrics for replication flow states
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica_metrics.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/store.go
  pkg/raft/tracker/state.go
Labels: backport

#137563 sql: add cluster setting for autocommit_before_ddl default
  pkg/settings/registry.go
  pkg/sql/conn_executor_ddl.go
  pkg/sql/vars.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x

#137612 release-24.3: released CockroachDB version 24.3.1. Next version: 24.3.2
  pkg/build/version.txt
Labels: backport

#136973 opt: minimize the number of buckets allocated when filtering histograms
  pkg/sql/opt/bench/bench_test.go
  pkg/sql/opt/props/histogram.go
  pkg/sql/opt/props/histogram_test.go
Labels: o-perf-efficiency

#137130 release-23.2: opt: propagate extra columns for lock operators
  pkg/sql/logictest/testdata/logic_test/dangerous_statements
  pkg/sql/opt/optbuilder/locking.go
  pkg/sql/opt/optbuilder/scope.go
Labels: backport

#137376 release-24.3: sql: do not limit set-returning UDF when it has OUT parameters
  pkg/sql/logictest/testdata/logic_test/udf_setof
  pkg/sql/opt/optbuilder/create_function.go
  pkg/sql/opt/testutils/testcat/function.go
Labels: backport

#137568 distsql: eliminate ctx allocation in setupFlow
  pkg/sql/colfetcher/index_join.go
  pkg/sql/colflow/explain_vec.go
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/distsql/server.go
  pkg/sql/execinfra/flow_context.go
  pkg/sql/execinfra/readerbase.go
  pkg/sql/flowinfra/flow.go
  pkg/sql/rowexec/joinreader.go
  pkg/sql/rowflow/row_based_flow.go
Labels: o-perf-efficiency

#137377 release-24.2: sql: do not limit set-returning UDF when it has OUT parameters
  pkg/sql/logictest/testdata/logic_test/udf_setof
  pkg/sql/opt/optbuilder/create_function.go
  pkg/sql/opt/testutils/testcat/function.go
Labels: backport

#137378 release-24.1: sql: do not limit set-returning UDF when it has OUT parameters
  pkg/sql/logictest/testdata/logic_test/udf_setof
  pkg/sql/opt/optbuilder/create_function.go
  pkg/sql/opt/testutils/testcat/function.go
Labels: backport

#137129 release-24.2: opt: propagate extra columns for lock operators
  pkg/sql/logictest/testdata/logic_test/dangerous_statements
  pkg/sql/opt/optbuilder/locking.go
  pkg/sql/opt/optbuilder/scope.go
Labels: backport

#137633 sql/schemachanger: Fix early exit for IF NOT EXISTS when adding existing columns
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#135945 kvserver: add setting to reject overly large transactions
  docs/generated/metrics/metrics.html
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go
  pkg/kv/kvclient/kvcoord/txn_metrics.go
Labels: backport-24.3.x

#137675 release-24.3: sql/schemachanger: Fix early exit for IF NOT EXISTS when adding existing columns
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go
Labels: backport

#137676 release-24.2: sql/schemachanger: Fix early exit for IF NOT EXISTS when adding existing columns
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go
Labels: backport

#137677 release-24.1: sql/schemachanger: Fix early exit for IF NOT EXISTS when adding existing columns
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go
Labels: backport

#137678 release-23.2: sql/schemachanger: Fix early exit for IF NOT EXISTS when adding existing columns
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go
Labels: backport

#137567 changefeedccl: fix schema change boundary race condition
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/resolved_span_frontier.go
  pkg/cmd/roachtest/tests/cdc.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#137679 release-23.1: sql/schemachanger: Fix early exit for IF NOT EXISTS when adding existing columns
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go
Labels: backport

#137741 sql: reduce context allocations related to pausable portals
  pkg/sql/conn_executor_exec.go
  pkg/sql/distsql_running.go
  pkg/sql/prepared_stmt.go
Labels: o-perf-efficiency

#137766 rac2,kvflowcontrol: fix redaction safety for a few types
  pkg/kv/kvserver/kvflowcontrol/kvflowcontrolpb/kvflowcontrol.go
  pkg/kv/kvserver/kvflowcontrol/kvflowcontrolpb/kvflowcontrol.proto
  pkg/kv/kvserver/kvflowcontrol/rac2/log_tracker.go
  pkg/raft/raftpb/raft.go
  pkg/util/admission/admissionpb/admissionpb.go
Labels: backport-24.3.x

#137768 release-24.2: sql: SHOW CREATE now uses two-part names for composite types
  pkg/sql/logictest/testdata/logic_test/composite_types
  pkg/sql/logictest/testdata/logic_test/drop_function
  pkg/sql/logictest/testdata/logic_test/show_create
  pkg/sql/logictest/testdata/logic_test/tuple
  pkg/sql/logictest/testdata/logic_test/udf_star
  pkg/sql/types/types.go
  pkg/sql/types/types_test.go
Labels: backport

#137755 server: remove alloc in setupSpanForIncomingRPC
  pkg/server/node.go
Labels: o-perf-efficiency

#137775 release-24.3: kvflowcontrol: fix logging redaction for a few types
  pkg/kv/kvserver/kvflowcontrol/BUILD.bazel
  pkg/kv/kvserver/kvflowcontrol/kvflowcontrol.go
  pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go
Labels: backport

#137767 release-23.1: ccl/oidcccl: TestOIDCEnabled failed under stress
  pkg/ccl/oidcccl/BUILD.bazel
  pkg/ccl/oidcccl/authentication_oidc_test.go
Labels: backport

#137774 workload/schemachange: turn on exec logging for all statements
  pkg/workload/cli/run.go
  pkg/workload/schemachange/operation_generator.go
  pkg/workload/schemachange/schemachange.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#137804 dev: remove `--strip=never` configuration from `.bazelrc.user`
  .bazelrc
Labels: backport-24.3.x

#137628 sql: TestReacquireLeaseOnRestart fix
  pkg/sql/catalog/lease/descriptor_state.go
  pkg/sql/catalog/lease/lease.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x

#137867 release-24.1: rolemembershipcache: fix timestamp calculation in RunAtCacheReadTS
  pkg/sql/authorization.go
Labels: backport

#137866 release-24.2: rolemembershipcache: fix timestamp calculation in RunAtCacheReadTS
  pkg/sql/authorization.go
Labels: backport

#137865 release-24.3: rolemembershipcache: fix timestamp calculation in RunAtCacheReadTS
  pkg/sql/authorization.go
Labels: backport

#137870 roachtest: mark more activerecord tests as flaky
  pkg/cmd/roachtest/tests/activerecord_blocklist.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x

#137864 release-23.2: scbuild: block adding UNIQUE json col in mixed version state
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go
Labels: backport

#137844 sql: add session setting for legacy VARCHAR typing behavior
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/optbuilder/builder.go
  pkg/sql/pgwire/testdata/pgtest/typing
  pkg/sql/sem/tree/overload.go
  pkg/sql/sem/tree/type_check.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#137860 sql: Skip constraints in pg_constraint that are being dropped.
  pkg/sql/pg_catalog.go
  pkg/sql/schemachanger/dml_injection_test.go
Labels: backport-24.3.x

#137868 sql: Check for concurrent DSC job in legacy schema changer
  pkg/sql/schema_changer.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x

#137908 release-24.2: raft: bump proposal timeout for TestNodeProposeWaitDropped
  pkg/raft/node_test.go
Labels: backport

#137754 sql: avoid some vevent-related allocs
  pkg/sql/exec_util.go
Labels: o-perf-efficiency

#137909 release-24.3: rangefeed: track testing caughtUp state with an atomic
  pkg/kv/kvserver/rangefeed/buffered_registration.go
Labels: backport

#137632 ctxutil: bundle up fastValueCtx allocs in Batch
  pkg/server/node.go
  pkg/util/ctxutil/fast_value.go
  pkg/util/log/ambient_context.go
Labels: o-perf-efficiency

#137919 release-24.3: sql: add session setting for legacy VARCHAR typing behavior
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/optbuilder/builder.go
  pkg/sql/pgwire/testdata/pgtest/typing
  pkg/sql/sem/tree/overload.go
  pkg/sql/sem/tree/type_check.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#137920 release-24.2: sql: add session setting for legacy VARCHAR typing behavior
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/optbuilder/builder.go
  pkg/sql/pgwire/testdata/pgtest/typing
  pkg/sql/sem/tree/overload.go
  pkg/sql/sem/tree/type_check.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#137925 release 24-2: skip TestStreamingRegionalConstraint
  pkg/ccl/crosscluster/physical/replication_stream_e2e_test.go
Labels: backport-23.2.x, backport-24.1.x

#137927 roachtest: add sysbench flavor with cluster settings
  pkg/cmd/roachtest/tests/sysbench.go
Labels: o-perf-efficiency

#137922 release-23.2: sql: add session setting for legacy VARCHAR typing behavior
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/optbuilder/builder.go
  pkg/sql/pgwire/testdata/pgtest/typing
  pkg/sql/sem/tree/overload.go
  pkg/sql/sem/tree/type_check.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#137928 sql: remove NULL values from REGPROC columns of pg_catalog.pg_type
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: backport-24.3.x

#137921 release-24.1: sql: add session setting for legacy VARCHAR typing behavior
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/optbuilder/builder.go
  pkg/sql/pgwire/testdata/pgtest/typing
  pkg/sql/sem/tree/overload.go
  pkg/sql/sem/tree/type_check.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport
