Repository cockroachdb/cockroach, pull requests merged in 2024-10, with the labels that each got.

#131580 sql: fix TestAuthenticationAndHBARules for special_cases data-driven test
  pkg/sql/pgwire/auth_test.go
  pkg/sql/pgwire/testdata/auth/secure_non_tls
Labels: backport-23.1.x, backport-23.2.x

#131634 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#131635 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#131637 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#131638 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#131447 release-24.2: logictest: fix flakes in select_for_share
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/select_for_share
  pkg/sql/logictest/testdata/logic_test/txn
Labels: backport

#131448 release-24.1: logictest: fix flakes in select_for_share
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/select_for_share
  pkg/sql/logictest/testdata/logic_test/txn
Labels: backport

#131420 release-23.2: server/license: Add notice for upcoming throttling
  .github/CODEOWNERS
  pkg/server/license/BUILD.bazel
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/sql/conn_executor_exec.go
Labels: backport

#131421 release-23.1: server/license: Add notice for upcoming throttling
  .github/CODEOWNERS
  pkg/server/license/BUILD.bazel
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/sql/conn_executor_exec.go
Labels: backport

#130956 sql/sql_test: fix timeout in TestRaceWithBackfill
  pkg/sql/schema_changer_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#131694 release-23.2: sql/sem/builtins: validate engine keys in storage builtins
  pkg/sql/sem/builtins/BUILD.bazel
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/generator_builtins.go
  pkg/storage/pebble.go
Labels: backport

#131739 release-24.2: sql: Exempt SET CLUSTER SETTING from throttling
  pkg/server/license/enforcer_test.go
  pkg/sql/conn_executor_exec.go
Labels: backport

#131740 release-24.1: sql: Exempt SET CLUSTER SETTING from throttling
  pkg/server/license/enforcer_test.go
  pkg/sql/conn_executor_exec.go
Labels: backport

#131742 release-23.1: sql: Exempt SET CLUSTER SETTING from throttling
  pkg/server/license/enforcer_test.go
  pkg/sql/conn_executor_exec.go
Labels: backport

#131097 logcrash, ccl: fail if setting incompatible license and reporting cfg
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/settings/bool.go
  pkg/settings/options.go
  pkg/settings/validation_test.go
  pkg/sql/set_cluster_setting.go
  pkg/util/log/logcrash/BUILD.bazel
  pkg/util/log/logcrash/crash_reporting.go
  pkg/util/log/logcrash/crash_reporting_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#131741 release-23.2: sql: Exempt SET CLUSTER SETTING from throttling
  pkg/server/license/enforcer_test.go
  pkg/sql/conn_executor_exec.go
Labels: backport

#129018 release-24.1: kvserver: split snapshot SSTables for mvcc keys into multiple SSTs
  pkg/cli/debug.go
  pkg/kv/kvserver/BUILD.bazel
  pkg/kv/kvserver/client_merge_test.go
  pkg/kv/kvserver/kvserverpb/raft.proto
  pkg/kv/kvserver/rditer/replica_data_iter.go
  pkg/kv/kvserver/rditer/replica_data_iter_test.go
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/all/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/all/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/all/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/replicatedOnly/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/replicatedOnly/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r1/replicatedOnly/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/all/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/all/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/all/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/replicatedOnly/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/replicatedOnly/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r2/replicatedOnly/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/all/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/all/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/all/user-only/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/replicatedOnly/all/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/replicatedOnly/exclude-user/output
  pkg/kv/kvserver/rditer/testdata/TestReplicaDataIterator/r3/replicatedOnly/user-only/output
  pkg/kv/kvserver/replica_command.go
  pkg/kv/kvserver/replica_learner_test.go
  pkg/kv/kvserver/replica_sst_snapshot_storage_test.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/store_snapshot.go
  pkg/storage/engine_key.go
  pkg/storage/sst_writer.go
Labels: backport

#131764 roachtest: move more tpcc bytes to lower level in disagg-rebalance
  pkg/cmd/roachtest/tests/disagg_rebalance.go
Labels: backport-24.1.x, backport-24.2.x

#131795 release-24.1: changefeedccl: enable verbose logs for a few schema change unit tests
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
Labels: backport

#131796 release-23.2: changefeedccl: enable verbose logs for a few schema change unit tests
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
Labels: backport

#131798 release-23.1: changefeedccl: enable verbose logs for a few schema change unit tests
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
Labels: backport

#131837 release-23.1: released CockroachDB version 23.1.27. Next version: 23.1.28
  pkg/build/version.txt
Labels: backport

#131864 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#131866 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#131833 release-23.1: server/license: Initial support for serverless
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/config.go
  pkg/server/config_test.go
  pkg/server/license/BUILD.bazel
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/license/opts.go
  pkg/server/server_controller_new_server.go
  pkg/server/server_sql.go
  pkg/server/testserver.go
  pkg/sql/conn_executor_internal_test.go
Labels: backport

#131826 release-23.2: server/license: Initial support for serverless
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/config.go
  pkg/server/config_test.go
  pkg/server/license/BUILD.bazel
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/license/opts.go
  pkg/server/server_controller_new_server.go
  pkg/server/server_sql.go
  pkg/server/testserver.go
  pkg/sql/conn_executor_internal_test.go
Labels: backport

#131825 release-24.1: server/license: Initial support for serverless
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/config.go
  pkg/server/config_test.go
  pkg/server/license/BUILD.bazel
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/license/opts.go
  pkg/server/server_controller_new_server.go
  pkg/server/server_sql.go
  pkg/server/testserver.go
  pkg/sql/conn_executor_internal_test.go
Labels: backport

#131824 release-24.2: server/license: Initial support for serverless
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/config.go
  pkg/server/config_test.go
  pkg/server/license/BUILD.bazel
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/license/opts.go
  pkg/server/server_controller_new_server.go
  pkg/server/server_sql.go
  pkg/server/testserver.go
  pkg/sql/conn_executor_internal_test.go
Labels: backport

#131867 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#131874 release-23.1: license lint: make license header linter accept CockroachDB Software License
  pkg/testutils/lint/lint_test.go
Labels: backport

#131882 release-24.1: sql: disable lease and merge queue in relocate tests
  pkg/sql/multitenant_admin_function_test.go
  pkg/testutils/serverutils/test_cluster_shim.go
  pkg/testutils/testcluster/testcluster.go
Labels: backport

#131873 release-23.2: license lint: make license header linter accept CockroachDB Software License
  pkg/testutils/lint/lint_test.go
Labels: backport

#131868 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#131872 release-24.1: license lint: make license header linter accept CockroachDB Software License
  pkg/testutils/lint/lint_test.go
Labels: backport

#131878 release-24.1: license: change Cockroach Labs, Inc to The Cockroach Authors
  pkg/raft/bootstrap.go
  pkg/raft/confchange/confchange.go
  pkg/raft/confchange/datadriven_test.go
  pkg/raft/confchange/quick_test.go
  pkg/raft/confchange/restore.go
  pkg/raft/confchange/restore_test.go
  pkg/raft/doc.go
  pkg/raft/example_test.go
  pkg/raft/interaction_test.go
  pkg/raft/log.go
  pkg/raft/log_test.go
  pkg/raft/log_unstable.go
  pkg/raft/log_unstable_test.go
  pkg/raft/node.go
  pkg/raft/node_test.go
  pkg/raft/node_util_test.go
  pkg/raft/quorum/quorum.go
  pkg/raft/raft.go
  pkg/raft/raft_flow_control_test.go
  pkg/raft/raft_paper_test.go
  pkg/raft/raft_snap_test.go
  pkg/raft/raft_test.go
  pkg/raft/raftpb/confstate_test.go
  pkg/raft/rafttest/doc.go
  pkg/raft/rafttest/interaction_env.go
  pkg/raft/rafttest/interaction_env_handler_add_nodes.go
  pkg/raft/rafttest/interaction_env_handler_deliver_msgs.go
  pkg/raft/rafttest/interaction_env_handler_process_append_thread.go
  pkg/raft/rafttest/interaction_env_handler_process_apply_thread.go
  pkg/raft/rafttest/interaction_env_handler_process_ready.go
  pkg/raft/rafttest/interaction_env_handler_propose_conf_change.go
  pkg/raft/rafttest/interaction_env_handler_raft_log.go
  pkg/raft/rafttest/interaction_env_handler_raftstate.go
  pkg/raft/rafttest/interaction_env_handler_report_unreachable.go
  pkg/raft/rafttest/interaction_env_handler_send_snapshot.go
  pkg/raft/rafttest/interaction_env_handler_stabilize.go
  pkg/raft/rafttest/interaction_env_handler_status.go
  pkg/raft/rafttest/interaction_env_logger.go
  pkg/raft/rafttest/network.go
  pkg/raft/rafttest/network_test.go
  pkg/raft/rafttest/node.go
  pkg/raft/rafttest/node_bench_test.go
  pkg/raft/rafttest/node_test.go
  pkg/raft/rawnode.go
  pkg/raft/rawnode_test.go
  pkg/raft/read_only.go
  pkg/raft/status.go
  pkg/raft/storage.go
  pkg/raft/storage_test.go
  pkg/raft/tracker/tracker.go
  pkg/raft/types.go
  pkg/raft/types_test.go
  pkg/raft/util.go
  pkg/raft/util_test.go
  pkg/testutils/lint/lint_test.go
Labels: backport

#131249 diagnostics: send along license information on diag report
  pkg/base/testing_knobs.go
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/application_api/telemetry_test.go
  pkg/server/diagnostics/BUILD.bazel
  pkg/server/diagnostics/diagnostics.go
  pkg/server/diagnostics/reporter.go
  pkg/server/diagnostics/reporter_test.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/server_sql.go
  pkg/server/testing_knobs.go
  pkg/server/testserver.go
  pkg/upgrade/upgrades/v24_3_check_license_violation_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#131916 release-23.1: license: code gen uses the CSL instead of CCL
  pkg/ccl/logictestccl/tests/3node-tenant-multiregion/generated_test.go
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/5node/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-disk/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist/generated_test.go
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/generated_test.go
  pkg/ccl/logictestccl/tests/local-mixed-22.2-23.1/generated_test.go
  pkg/ccl/logictestccl/tests/local-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/local/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-15node-5region-3azs/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-3node-3superlongregions/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/ccl/schemachangerccl/backup_base_generated_test.go
  pkg/ccl/schemachangerccl/backup_base_mixed_generated_test.go
  pkg/ccl/schemachangerccl/ccl_generated_test.go
  pkg/ccl/sqlitelogictestccl/tests/3node-tenant/generated_test.go
  pkg/cmd/generate-logictest/templates.go
  pkg/sql/schemachanger/sctest/sctestgen/gen.go
Labels: backport

#131927 release-23.2: license: code gen uses the CSL instead of CCL
  pkg/ccl/backupccl/testgen/templates.go
  pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/testgen/template.go
  pkg/ccl/logictestccl/tests/3node-tenant-multiregion/generated_test.go
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/5node/generated_test.go
  pkg/ccl/logictestccl/tests/cockroach-go-testserver-upgrade-to-master/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-disk/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist/generated_test.go
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/generated_test.go
  pkg/ccl/logictestccl/tests/local-mixed-23.1/generated_test.go
  pkg/ccl/logictestccl/tests/local-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/local/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-15node-5region-3azs/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-3node-3superlongregions/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/ccl/schemachangerccl/backup_base_generated_test.go
  pkg/ccl/schemachangerccl/ccl_generated_test.go
  pkg/ccl/sqlitelogictestccl/tests/3node-tenant/generated_test.go
  pkg/cmd/generate-logictest/templates.go
  pkg/sql/schemachanger/sctest/sctestgen/gen.go
Labels: backport

#131933 release-23.2: license: code gen uses the CSL instead of BSL
  pkg/acceptance/generated_cli_test.go
  pkg/cmd/generate-acceptance-tests/cli_test_template.go
  pkg/cmd/generate-logictest/templates.go
  pkg/sql/colexec/colexecbase/distinct.eg.go
  pkg/sql/colexec/colexecproj/default_cmp_proj_op.eg.go
  pkg/sql/colexec/colexecprojconst/default_cmp_proj_const_op.eg.go
  pkg/sql/colexec/colexecprojconst/proj_like_ops.eg.go
  pkg/sql/colexec/colexecsel/sel_like_ops.eg.go
  pkg/sql/colexec/execgen/cmd/execgen/default_cmp_proj_ops_gen.go
  pkg/sql/colexec/execgen/cmd/execgen/distinct_gen.go
  pkg/sql/colexec/execgen/cmd/execgen/like_ops_gen.go
  pkg/sql/colexec/sort_partitioner.eg.go
  pkg/sql/logictest/tests/5node-disk/generated_test.go
  pkg/sql/logictest/tests/5node/generated_test.go
  pkg/sql/logictest/tests/cockroach-go-testserver-upgrade-to-master/generated_test.go
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-mixed-23.1/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/logictest/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/sql/logictest/tests/multiregion-invalid-locality/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/5node/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/fakedist-disk/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/fakedist-vec-off/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/fakedist/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local-mixed-23.1/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local-vec-off/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local/generated_test.go
  pkg/sql/schemachanger/comparator_generated_test.go
  pkg/sql/schemachanger/scop/backfill_visitor_generated.go
  pkg/sql/schemachanger/scop/deferred_mutation_visitor_generated.go
  pkg/sql/schemachanger/scop/generate_visitor.go
  pkg/sql/schemachanger/scop/immediate_mutation_visitor_generated.go
  pkg/sql/schemachanger/scop/validation_visitor_generated.go
  pkg/sql/schemachanger/scpb/element_generator.go
  pkg/sql/schemachanger/scpb/elements_generated.go
  pkg/sql/schemachanger/sctest/sccomparatortestgen/main.go
  pkg/sql/schemachanger/sctest/sctestgen/gen.go
  pkg/sql/schemachanger/sctest_generated_test.go
  pkg/sql/sem/tree/eval_expr_generated.go
  pkg/sql/sem/tree/eval_op_generated.go
  pkg/sql/sem/tree/evalgen/eval_gen.go
  pkg/sql/sqlitelogictest/tests/fakedist-disk/generated_test.go
  pkg/sql/sqlitelogictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/sqlitelogictest/tests/fakedist/generated_test.go
  pkg/sql/sqlitelogictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/sqlitelogictest/tests/local-mixed-23.1/generated_test.go
  pkg/sql/sqlitelogictest/tests/local-vec-off/generated_test.go
  pkg/sql/sqlitelogictest/tests/local/generated_test.go
  pkg/util/timeutil/gen/main.go
  pkg/util/timeutil/lowercase_timezones_generated.go
Labels: backport

#131939 release-24.1: license: code gen uses the CSL instead of CCL
  pkg/ccl/backupccl/testgen/templates.go
  pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/testgen/template.go
  pkg/ccl/logictestccl/tests/3node-tenant-multiregion/generated_test.go
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/5node/generated_test.go
  pkg/ccl/logictestccl/tests/cockroach-go-testserver-23.1/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-disk/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist/generated_test.go
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/generated_test.go
  pkg/ccl/logictestccl/tests/local-mixed-23.1/generated_test.go
  pkg/ccl/logictestccl/tests/local-mixed-23.2/generated_test.go
  pkg/ccl/logictestccl/tests/local-read-committed/generated_test.go
  pkg/ccl/logictestccl/tests/local-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/local/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-15node-5region-3azs/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-3node-3superlongregions/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/ccl/schemachangerccl/backup_base_generated_test.go
  pkg/ccl/schemachangerccl/ccl_generated_test.go
  pkg/ccl/sqlitelogictestccl/tests/3node-tenant/generated_test.go
  pkg/cmd/generate-logictest/templates.go
  pkg/sql/schemachanger/sctest/sctestgen/gen.go
Labels: backport

#131950 release-24.1: license: code gen uses the CSL instead of BSL
  pkg/acceptance/generated_cli_test.go
  pkg/cmd/generate-acceptance-tests/cli_test_template.go
  pkg/cmd/generate-logictest/templates.go
  pkg/sql/colexec/colexecbase/distinct.eg.go
  pkg/sql/colexec/colexecproj/default_cmp_proj_op.eg.go
  pkg/sql/colexec/colexecprojconst/default_cmp_proj_const_op.eg.go
  pkg/sql/colexec/colexecprojconst/proj_like_ops.eg.go
  pkg/sql/colexec/colexecsel/sel_like_ops.eg.go
  pkg/sql/colexec/execgen/cmd/execgen/default_cmp_proj_ops_gen.go
  pkg/sql/colexec/execgen/cmd/execgen/distinct_gen.go
  pkg/sql/colexec/execgen/cmd/execgen/like_ops_gen.go
  pkg/sql/colexec/sort_partitioner.eg.go
  pkg/sql/logictest/tests/5node-disk/generated_test.go
  pkg/sql/logictest/tests/5node/generated_test.go
  pkg/sql/logictest/tests/cockroach-go-testserver-23.1/generated_test.go
  pkg/sql/logictest/tests/cockroach-go-testserver-23.2/generated_test.go
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-mixed-23.1/generated_test.go
  pkg/sql/logictest/tests/local-mixed-23.2/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/logictest/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/sql/logictest/tests/multiregion-invalid-locality/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/5node/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/fakedist-disk/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/fakedist-vec-off/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/fakedist/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local-mixed-23.1/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local-mixed-23.2/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local-vec-off/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local/generated_test.go
  pkg/sql/schemachanger/comparator_generated_test.go
  pkg/sql/schemachanger/scop/backfill_visitor_generated.go
  pkg/sql/schemachanger/scop/deferred_mutation_visitor_generated.go
  pkg/sql/schemachanger/scop/generate-visitors/generate_visitor.go
  pkg/sql/schemachanger/scop/immediate_mutation_visitor_generated.go
  pkg/sql/schemachanger/scop/validation_visitor_generated.go
  pkg/sql/schemachanger/scpb/element-generator/element_generator.go
  pkg/sql/schemachanger/scpb/elements_generated.go
  pkg/sql/schemachanger/sctest/sccomparatortestgen/main.go
  pkg/sql/schemachanger/sctest/sctestgen/gen.go
  pkg/sql/schemachanger/sctest_generated_test.go
  pkg/sql/sem/tree/eval_expr_generated.go
  pkg/sql/sem/tree/eval_op_generated.go
  pkg/sql/sem/tree/evalgen/eval_gen.go
  pkg/sql/sqlitelogictest/tests/fakedist-disk/generated_test.go
  pkg/sql/sqlitelogictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/sqlitelogictest/tests/fakedist/generated_test.go
  pkg/sql/sqlitelogictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/sqlitelogictest/tests/local-mixed-23.1/generated_test.go
  pkg/sql/sqlitelogictest/tests/local-mixed-23.2/generated_test.go
  pkg/sql/sqlitelogictest/tests/local-read-committed/generated_test.go
  pkg/sql/sqlitelogictest/tests/local-vec-off/generated_test.go
  pkg/sql/sqlitelogictest/tests/local/generated_test.go
  pkg/util/timeutil/gen/main.go
  pkg/util/timeutil/lowercase_timezones_generated.go
Labels: backport

#131956 release-24.2: license: code gen uses the CSL instead of CCL
  pkg/ccl/backupccl/testgen/templates.go
  pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/testgen/template.go
  pkg/ccl/logictestccl/tests/3node-tenant-multiregion/generated_test.go
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/5node/generated_test.go
  pkg/ccl/logictestccl/tests/cockroach-go-testserver-23.2/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-disk/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist/generated_test.go
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/generated_test.go
  pkg/ccl/logictestccl/tests/local-mixed-23.2/generated_test.go
  pkg/ccl/logictestccl/tests/local-read-committed/generated_test.go
  pkg/ccl/logictestccl/tests/local-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/local/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-15node-5region-3azs/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-3node-3superlongregions/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/ccl/schemachangerccl/backup_base_generated_test.go
  pkg/ccl/schemachangerccl/ccl_generated_test.go
  pkg/ccl/sqlitelogictestccl/tests/3node-tenant/generated_test.go
  pkg/cmd/generate-logictest/templates.go
  pkg/sql/schemachanger/sctest/sctestgen/gen.go
Labels: backport

#131961 release-24.2: license: code gen uses the CSL instead of BSL
  pkg/acceptance/generated_cli_test.go
  pkg/cmd/generate-acceptance-tests/cli_test_template.go
  pkg/cmd/generate-logictest/templates.go
  pkg/sql/colexec/colexecbase/distinct.eg.go
  pkg/sql/colexec/colexecproj/default_cmp_proj_op.eg.go
  pkg/sql/colexec/colexecprojconst/default_cmp_proj_const_op.eg.go
  pkg/sql/colexec/colexecprojconst/proj_like_ops.eg.go
  pkg/sql/colexec/colexecsel/sel_like_ops.eg.go
  pkg/sql/colexec/execgen/cmd/execgen/default_cmp_proj_ops_gen.go
  pkg/sql/colexec/execgen/cmd/execgen/distinct_gen.go
  pkg/sql/colexec/execgen/cmd/execgen/like_ops_gen.go
  pkg/sql/colexec/sort_partitioner.eg.go
  pkg/sql/logictest/tests/5node-disk/generated_test.go
  pkg/sql/logictest/tests/5node/generated_test.go
  pkg/sql/logictest/tests/cockroach-go-testserver-23.2/generated_test.go
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-mixed-23.2/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/logictest/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/sql/logictest/tests/multiregion-invalid-locality/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/5node/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/fakedist-disk/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/fakedist-vec-off/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/fakedist/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local-mixed-23.2/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local-vec-off/generated_test.go
  pkg/sql/opt/exec/execbuilder/tests/local/generated_test.go
  pkg/sql/schemachanger/comparator_generated_test.go
  pkg/sql/schemachanger/scop/backfill_visitor_generated.go
  pkg/sql/schemachanger/scop/deferred_mutation_visitor_generated.go
  pkg/sql/schemachanger/scop/generate-visitors/generate_visitor.go
  pkg/sql/schemachanger/scop/immediate_mutation_visitor_generated.go
  pkg/sql/schemachanger/scop/validation_visitor_generated.go
  pkg/sql/schemachanger/scpb/element-generator/element_generator.go
  pkg/sql/schemachanger/scpb/elements_generated.go
  pkg/sql/schemachanger/sctest/sccomparatortestgen/main.go
  pkg/sql/schemachanger/sctest/sctestgen/gen.go
  pkg/sql/schemachanger/sctest_generated_test.go
  pkg/sql/sem/tree/eval_expr_generated.go
  pkg/sql/sem/tree/eval_op_generated.go
  pkg/sql/sem/tree/evalgen/eval_gen.go
  pkg/sql/sqlitelogictest/tests/fakedist-disk/generated_test.go
  pkg/sql/sqlitelogictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/sqlitelogictest/tests/fakedist/generated_test.go
  pkg/sql/sqlitelogictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/sqlitelogictest/tests/local-mixed-23.2/generated_test.go
  pkg/sql/sqlitelogictest/tests/local-read-committed/generated_test.go
  pkg/sql/sqlitelogictest/tests/local-vec-off/generated_test.go
  pkg/sql/sqlitelogictest/tests/local/generated_test.go
  pkg/util/timeutil/gen/main.go
  pkg/util/timeutil/lowercase_timezones_generated.go
Labels: backport

#131869 sql/row: fix updates of single-composite-column families
  pkg/sql/colenc/encode.go
  pkg/sql/logictest/testdata/logic_test/column_families
  pkg/sql/row/deleter.go
  pkg/sql/row/helper.go
  pkg/sql/row/writer.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#131963 kvserver: add w-amp metric for each store
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
Labels: backport-24.1.x, backport-24.2.x

#131758 opt/exec/explain: gracefully handle unknown indexes in plan gists
  pkg/sql/opt/exec/execbuilder/testdata/explain_gist
  pkg/sql/opt/exec/explain/plan_gist_factory.go
Labels: backport-24.1.x, backport-24.2.x

#132017 release-24.1: license: change BSL file headers to CSL for last cases
  build/deploy/cockroach.sh
  pkg/cmd/prereqs/testdata/src/example.com/specialchars/.ignore.go
  pkg/internal/rsg/yacc/lex.go
  pkg/internal/rsg/yacc/node.go
  pkg/internal/rsg/yacc/parse.go
  pkg/internal/sqlsmith/sampler.go
  pkg/kv/kvserver/tscache/interval_skl.go
  pkg/kv/kvserver/tscache/interval_skl_test.go
  pkg/roachprod/install/scripts/download.sh
  pkg/roachprod/install/scripts/open_ports.sh
  pkg/roachprod/install/scripts/start.sh
  pkg/roachprod/install/scripts/start_test.sh
  pkg/roachprod/install/testdata/start/start.txt
  pkg/sql/lex/encode.go
  pkg/sql/lexbase/encode.go
  pkg/sql/parser/parse.go
  pkg/sql/sem/tree/create.go
  pkg/sql/sem/tree/delete.go
  pkg/sql/sem/tree/drop.go
  pkg/sql/sem/tree/grant.go
  pkg/sql/sem/tree/insert.go
  pkg/sql/sem/tree/rename.go
  pkg/sql/sem/tree/revoke.go
  pkg/sql/sem/tree/select.go
  pkg/sql/sem/tree/set.go
  pkg/sql/sem/tree/show.go
  pkg/sql/sem/tree/stmt.go
  pkg/sql/sem/tree/truncate.go
  pkg/sql/sem/tree/union.go
  pkg/sql/sem/tree/update.go
  pkg/sql/sem/tree/values.go
  pkg/testutils/lint/passes/nilness/nilness.go
  pkg/testutils/lint/passes/nilness/nilness_test.go
  pkg/testutils/lint/passes/nilness/testdata/src/a/a.go
  pkg/ui/workspaces/cluster-ui/.jest/fileMock.js
  pkg/ui/workspaces/cluster-ui/.storybook/main.js
  pkg/ui/workspaces/cluster-ui/.storybook/middleware.js
  pkg/ui/workspaces/cluster-ui/.storybook/preview.js
  pkg/ui/workspaces/db-console/.storybook/decorators/index.ts
  pkg/ui/workspaces/db-console/.storybook/decorators/withBackground.tsx
  pkg/ui/workspaces/db-console/.storybook/decorators/withRouterProvider.tsx
  pkg/ui/workspaces/db-console/.storybook/webpack.config.js
  pkg/ui/workspaces/db-console/scripts/topo.js
  pkg/util/interval/interval.go
  pkg/util/interval/llrb_based_interval.go
  pkg/util/leaktest/leaktest.go
  pkg/util/log/clog.go
  pkg/util/log/clog_test.go
  pkg/util/log/file.go
  pkg/util/log/file_test.go
  pkg/util/sort/sort.go
  pkg/util/stringencoding/string_encoding.go
Labels: backport

#132054 release-24.2: license: change BSL file headers to CSL for last cases
  pkg/cmd/prereqs/testdata/src/example.com/specialchars/.ignore.go
  pkg/internal/rsg/yacc/lex.go
  pkg/internal/rsg/yacc/node.go
  pkg/internal/rsg/yacc/parse.go
  pkg/internal/sqlsmith/sampler.go
  pkg/kv/kvserver/tscache/interval_skl.go
  pkg/kv/kvserver/tscache/interval_skl_test.go
  pkg/sql/lex/encode.go
  pkg/sql/lexbase/encode.go
  pkg/sql/parser/parse.go
  pkg/sql/sem/tree/create.go
  pkg/sql/sem/tree/delete.go
  pkg/sql/sem/tree/drop.go
  pkg/sql/sem/tree/grant.go
  pkg/sql/sem/tree/insert.go
  pkg/sql/sem/tree/rename.go
  pkg/sql/sem/tree/revoke.go
  pkg/sql/sem/tree/select.go
  pkg/sql/sem/tree/set.go
  pkg/sql/sem/tree/show.go
  pkg/sql/sem/tree/stmt.go
  pkg/sql/sem/tree/truncate.go
  pkg/sql/sem/tree/union.go
  pkg/sql/sem/tree/update.go
  pkg/sql/sem/tree/values.go
  pkg/testutils/lint/passes/nilness/nilness.go
  pkg/testutils/lint/passes/nilness/nilness_test.go
  pkg/testutils/lint/passes/nilness/testdata/src/a/a.go
  pkg/ui/workspaces/cluster-ui/.jest/fileMock.js
  pkg/ui/workspaces/cluster-ui/.storybook/main.js
  pkg/ui/workspaces/cluster-ui/.storybook/middleware.js
  pkg/ui/workspaces/cluster-ui/.storybook/preview.js
  pkg/ui/workspaces/db-console/.storybook/decorators/index.ts
  pkg/ui/workspaces/db-console/.storybook/decorators/withBackground.tsx
  pkg/ui/workspaces/db-console/.storybook/decorators/withRouterProvider.tsx
  pkg/ui/workspaces/db-console/.storybook/main.js
  pkg/ui/workspaces/db-console/.storybook/webpack.config.js
  pkg/ui/workspaces/db-console/scripts/topo.js
  pkg/util/interval/interval.go
  pkg/util/interval/llrb_based_interval.go
  pkg/util/leaktest/leaktest.go
  pkg/util/log/clog.go
  pkg/util/log/clog_test.go
  pkg/util/log/file.go
  pkg/util/log/file_test.go
  pkg/util/sort/sort.go
  pkg/util/stringencoding/string_encoding.go
Labels: backport

#132053 release-23.2: license: change BSL file headers to CSL for last cases
  build/deploy/cockroach.sh
  pkg/cmd/prereqs/testdata/src/example.com/specialchars/.ignore.go
  pkg/internal/rsg/yacc/lex.go
  pkg/internal/rsg/yacc/node.go
  pkg/internal/rsg/yacc/parse.go
  pkg/internal/sqlsmith/sampler.go
  pkg/kv/kvserver/tscache/interval_skl.go
  pkg/kv/kvserver/tscache/interval_skl_test.go
  pkg/roachprod/install/scripts/download.sh
  pkg/roachprod/install/scripts/open_ports.sh
  pkg/roachprod/install/scripts/start.sh
  pkg/roachprod/install/scripts/start_test.sh
  pkg/roachprod/install/testdata/start/start.txt
  pkg/sql/lex/encode.go
  pkg/sql/lexbase/encode.go
  pkg/sql/parser/parse.go
  pkg/sql/sem/tree/create.go
  pkg/sql/sem/tree/delete.go
  pkg/sql/sem/tree/drop.go
  pkg/sql/sem/tree/grant.go
  pkg/sql/sem/tree/insert.go
  pkg/sql/sem/tree/rename.go
  pkg/sql/sem/tree/revoke.go
  pkg/sql/sem/tree/select.go
  pkg/sql/sem/tree/set.go
  pkg/sql/sem/tree/show.go
  pkg/sql/sem/tree/stmt.go
  pkg/sql/sem/tree/truncate.go
  pkg/sql/sem/tree/union.go
  pkg/sql/sem/tree/update.go
  pkg/sql/sem/tree/values.go
  pkg/testutils/lint/passes/nilness/nilness.go
  pkg/testutils/lint/passes/nilness/nilness_test.go
  pkg/testutils/lint/passes/nilness/testdata/src/a/a.go
  pkg/ui/workspaces/cluster-ui/.jest/fileMock.js
  pkg/ui/workspaces/cluster-ui/.storybook/main.js
  pkg/ui/workspaces/cluster-ui/.storybook/middleware.js
  pkg/ui/workspaces/cluster-ui/.storybook/preview.js
  pkg/ui/workspaces/db-console/.storybook/decorators/index.ts
  pkg/ui/workspaces/db-console/.storybook/decorators/withBackground.tsx
  pkg/ui/workspaces/db-console/.storybook/decorators/withRouterProvider.tsx
  pkg/ui/workspaces/db-console/.storybook/webpack.config.js
  pkg/ui/workspaces/db-console/scripts/topo.js
  pkg/util/interval/interval.go
  pkg/util/interval/llrb_based_interval.go
  pkg/util/leaktest/leaktest.go
  pkg/util/log/clog.go
  pkg/util/log/clog_test.go
  pkg/util/log/file.go
  pkg/util/log/file_test.go
  pkg/util/sort/sort.go
  pkg/util/stringencoding/string_encoding.go
Labels: backport

#132052 release-23.1: license: change BSL file headers to CSL for last cases
  build/deploy/cockroach.sh
  pkg/cmd/prereqs/testdata/src/example.com/specialchars/.ignore.go
  pkg/internal/rsg/yacc/lex.go
  pkg/internal/rsg/yacc/node.go
  pkg/internal/rsg/yacc/parse.go
  pkg/internal/sqlsmith/sampler.go
  pkg/kv/kvserver/tscache/interval_skl.go
  pkg/kv/kvserver/tscache/interval_skl_test.go
  pkg/roachprod/install/scripts/download.sh
  pkg/roachprod/install/scripts/open_ports.sh
  pkg/roachprod/install/scripts/start.sh
  pkg/roachprod/install/scripts/start_test.sh
  pkg/roachprod/install/testdata/start/start.txt
  pkg/sql/lex/encode.go
  pkg/sql/lexbase/encode.go
  pkg/sql/parser/parse.go
  pkg/sql/sem/tree/create.go
  pkg/sql/sem/tree/delete.go
  pkg/sql/sem/tree/drop.go
  pkg/sql/sem/tree/grant.go
  pkg/sql/sem/tree/insert.go
  pkg/sql/sem/tree/rename.go
  pkg/sql/sem/tree/revoke.go
  pkg/sql/sem/tree/select.go
  pkg/sql/sem/tree/set.go
  pkg/sql/sem/tree/show.go
  pkg/sql/sem/tree/stmt.go
  pkg/sql/sem/tree/truncate.go
  pkg/sql/sem/tree/union.go
  pkg/sql/sem/tree/update.go
  pkg/sql/sem/tree/values.go
  pkg/testutils/lint/passes/nilness/nilness.go
  pkg/testutils/lint/passes/nilness/nilness_test.go
  pkg/testutils/lint/passes/nilness/testdata/src/a/a.go
  pkg/ui/workspaces/cluster-ui/.jest/fileMock.js
  pkg/ui/workspaces/cluster-ui/.storybook/main.js
  pkg/ui/workspaces/cluster-ui/.storybook/middleware.js
  pkg/ui/workspaces/cluster-ui/.storybook/preview.js
  pkg/ui/workspaces/db-console/.storybook/decorators/index.ts
  pkg/ui/workspaces/db-console/.storybook/decorators/withBackground.tsx
  pkg/ui/workspaces/db-console/.storybook/decorators/withRouterProvider.tsx
  pkg/ui/workspaces/db-console/.storybook/webpack.config.js
  pkg/ui/workspaces/db-console/scripts/topo.js
  pkg/util/interval/interval.go
  pkg/util/interval/llrb_based_interval.go
  pkg/util/leaktest/leaktest.go
  pkg/util/log/clog.go
  pkg/util/log/clog_test.go
  pkg/util/log/file.go
  pkg/util/log/file_test.go
  pkg/util/sort/sort.go
  pkg/util/stringencoding/string_encoding.go
Labels: backport

#132037 roachtest: update expected failures for activerecord
  pkg/cmd/roachtest/tests/activerecord_blocklist.go
Labels: backport-24.2.x

#132036 sql/copy: use the proper interface for internal queries
  pkg/sql/copy/BUILD.bazel
  pkg/sql/copy/copy_test.go
  pkg/sql/copy/testdata/copy_to_read_committed
  pkg/sql/copy_to.go
  pkg/sql/isql/isql_db.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.1.6-rc

#131970 release-24.2: server/license: Limit enterprise trial license usage to once per cluster
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/gen/stringer.bzl
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/server/license/BUILD.bazel
  pkg/server/license/cclbridge.go
  pkg/server/license/enforcer.go
  pkg/server/license/lictype_string.go
Labels: backport

#131972 release-24.1: server/license: Limit enterprise trial license usage to once per cluster
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/gen/stringer.bzl
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/server/license/BUILD.bazel
  pkg/server/license/cclbridge.go
  pkg/server/license/enforcer.go
  pkg/server/license/lictype_string.go
Labels: backport

#131973 release-23.2: server/license: Limit enterprise trial license usage to once per cluster
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/gen/stringer.bzl
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/server/license/BUILD.bazel
  pkg/server/license/cclbridge.go
  pkg/server/license/enforcer.go
  pkg/server/license/lictype_string.go
Labels: backport

#131977 release-23.1: server/license: Limit enterprise trial license usage to once per cluster
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/gen/stringer.bzl
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/server/license/BUILD.bazel
  pkg/server/license/cclbridge.go
  pkg/server/license/enforcer.go
  pkg/server/license/lictype_string.go
Labels: backport

#131456 sql: plumb LDR originTimestamp from session var to TableWriter
  pkg/sql/internal.go
  pkg/sql/sessiondata/BUILD.bazel
  pkg/sql/sessiondata/internal.go
  pkg/sql/sessiondatapb/BUILD.bazel
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/tablewriter.go
Labels: T-disaster-recovery

#132107 release-24.2: sql: disallow ordering by VECTOR columns
  pkg/ccl/logictestccl/testdata/logic_test/vector
  pkg/sql/opt/optbuilder/orderby.go
  pkg/sql/opt/optbuilder/testdata/orderby
  pkg/sql/rowcontainer/disk_row_container.go
Labels: backport

#131782 catalog: validate/repair default privs with orphan roles
  pkg/sql/catalog/dbdesc/database_desc_builder.go
  pkg/sql/catalog/schemadesc/schema_desc_builder.go
  pkg/sql/catalog/validate.go
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#132055 release-24.1: license lint: only lint on the CockroachDB Software License (CSL)
  pkg/testutils/lint/lint_test.go
  pkg/ui/workspaces/db-console/.storybook/config.tsx
Labels: backport

#132057 release-24.1: license: Remove the BSL and CCL license files
  licenses/BSL.txt
  licenses/CCL.txt
  licenses/LICENSE.txt
Labels: backport

#132127 release-23.1: license lint: only lint on the CockroachDB Software License (CSL)
  pkg/testutils/lint/lint_test.go
  pkg/ui/workspaces/db-console/.storybook/config.tsx
Labels: backport

#132128 release-23.2: license lint: only lint on the CockroachDB Software License (CSL)
  pkg/testutils/lint/lint_test.go
  pkg/ui/workspaces/db-console/.storybook/config.tsx
Labels: backport

#132059 release-23.1: license: Remove the BSL and CCL license files
  licenses/BSL.txt
  licenses/CCL.txt
  licenses/LICENSE.txt
Labels: backport

#132058 release-23.2: license: Remove the BSL and CCL license files
  licenses/BSL.txt
  licenses/CCL.txt
  licenses/LICENSE.txt
Labels: backport

#132126 release-24.2: license lint: only lint on the CockroachDB Software License (CSL)
  pkg/testutils/lint/lint_test.go
Labels: backport

#131454 release-24.1: crosscluster/physical: use correct lag replan cluster setting
  pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go
Labels: backport

#132169 release-23.2: catalog: validate/repair default privs with orphan roles
  pkg/sql/catalog/dbdesc/database_desc_builder.go
  pkg/sql/catalog/schemadesc/schema_desc_builder.go
  pkg/sql/catalog/validate.go
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_default_privileges
Labels: backport

#132168 workload/schemachanger: fix failure in foreign key operation generation
  pkg/workload/schemachange/error_screening.go
  pkg/workload/schemachange/operation_generator.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#132178 logictest: deflake test by increase timestamp delta
  pkg/sql/logictest/testdata/logic_test/alter_table
Labels: backport-24.1.x, backport-24.2.x

#132185 logictest: attempt to deflake test by using a different table
  pkg/sql/logictest/testdata/logic_test/synthetic_privileges
Labels: backport-24.2.x

#131605 crosscluster: destroy reader tenant
  pkg/ccl/crosscluster/physical/alter_replication_job.go
  pkg/ccl/crosscluster/physical/standby_read_ts_poller_job_test.go
  pkg/ccl/crosscluster/physical/stream_ingestion_job.go
  pkg/jobs/jobspb/jobs.proto
Labels: T-disaster-recovery

#131944 server/license: Enable the License Enforcer
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/application_api/telemetry_test.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/upgrade/upgradebase/testing_knobs.go
  pkg/upgrade/upgrademanager/manager.go
  pkg/upgrade/upgrades/BUILD.bazel
  pkg/upgrade/upgrades/v24_3_check_license_violation.go
  pkg/upgrade/upgrades/v24_3_check_license_violation_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#132144 release-24.1: release: use license from its new location
  build/README.md
  build/deploy/Dockerfile
  build/github/docker-image.sh
  build/teamcity/internal/release/process/build-cockroach-release-per-platform.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-per-platform.sh
  pkg/cmd/publish-provisional-artifacts/main.go
  pkg/cmd/publish-provisional-artifacts/main_test.go
Labels: backport

#132239 release-24.2: release: use license from its new location
  build/README.md
  build/deploy/Dockerfile
  build/github/docker-image.sh
  build/teamcity/internal/release/process/build-cockroach-release-per-platform.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-per-platform.sh
  pkg/cmd/publish-provisional-artifacts/main.go
  pkg/cmd/publish-provisional-artifacts/main_test.go
Labels: backport

#132145 release-23.2: release: use license from its new location
  build/README.md
  build/deploy/.gitignore
  build/deploy/Dockerfile
  build/teamcity/cockroach/ci/builds/build_docker_image.sh
  build/teamcity/internal/release/process/build-cockroach-release-per-platform.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-per-platform.sh
  pkg/cmd/publish-provisional-artifacts/main.go
  pkg/cmd/publish-provisional-artifacts/main_test.go
Labels: backport

#132226 release-24.2: server/license: Change how trial license usage is tracked
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/server/license/enforcer.go
Labels: backport

#132227 release-24.1: server/license: Change how trial license usage is tracked
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/server/license/enforcer.go
Labels: backport

#132228 release-23.2: server/license: Change how trial license usage is tracked
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/server/license/enforcer.go
Labels: backport

#132233 release-23.1: server/license: Change how trial license usage is tracked
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/keys/constants.go
  pkg/keys/doc.go
  pkg/server/license/enforcer.go
Labels: backport

#132222 release-24.2: server/license: Flow cluster init timestamp through tenant connector
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/kv/kvclient/kvtenant/setting_overrides.go
  pkg/kv/kvpb/api.proto
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/license/opts.go
  pkg/server/node.go
  pkg/server/server.go
  pkg/server/server_sql.go
Labels: backport

#132223 release-24.1: server/license: Flow cluster init timestamp through tenant connector
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/kv/kvclient/kvtenant/setting_overrides.go
  pkg/kv/kvpb/api.proto
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/license/opts.go
  pkg/server/node.go
  pkg/server/server.go
  pkg/server/server_sql.go
Labels: backport

#132224 release-23.2: server/license: Flow cluster init timestamp through tenant connector
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/kv/kvclient/kvtenant/setting_overrides.go
  pkg/kv/kvpb/api.proto
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/license/opts.go
  pkg/server/node.go
  pkg/server/server.go
  pkg/server/server_sql.go
Labels: backport

#132256 logictest: fix skip logic so it shuts down cluster first
  pkg/sql/logictest/logic.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#132259 release-24.1: backupccl: do restore chunk work dispatch/wait in group
  pkg/ccl/backupccl/generative_split_and_scatter_processor.go
  pkg/ccl/backupccl/generative_split_and_scatter_processor_test.go
Labels: backport

#132309 release-23.1: server/license: Enable the License Enforcer
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
Labels: backport

#132308 release-23.2: server/license: Enable the License Enforcer
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
Labels: backport

#132306 release-24.1: server/license: Enable the License Enforcer
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
Labels: backport

#132305 release-24.2: server/license: Enable the License Enforcer
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
Labels: backport

#132211 sql/delegate: refactor comments table code and remove usage of `system.comments` table
  pkg/sql/delegate/BUILD.bazel
  pkg/sql/delegate/delegate.go
  pkg/sql/delegate/show_databases.go
  pkg/sql/delegate/show_schemas.go
  pkg/sql/delegate/show_types.go
Labels: C-enhancement

#132240 release-23.2: changefeedccl: reduce use of errors during pauseOrResumePolling
  pkg/ccl/changefeedccl/changefeedbase/target.go
  pkg/ccl/changefeedccl/schemafeed/schema_feed.go
  pkg/ccl/changefeedccl/schemafeed/schema_feed_test.go
Labels: backport

#130890 release-24.1: opt: fix BPCHAR type and CASE typing
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/sql/logictest/testdata/logic_test/bpchar
  pkg/sql/logictest/testdata/logic_test/case
  pkg/sql/logictest/testdata/logic_test/cast
  pkg/sql/logictest/testdata/logic_test/decimal
  pkg/sql/logictest/testdata/logic_test/drop_function
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/pg_builtins
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-mixed-23.1/generated_test.go
  pkg/sql/logictest/tests/local-mixed-23.2/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/opt/optbuilder/scalar.go
  pkg/sql/opt/optbuilder/testdata/scalar
  pkg/sql/opt/xform/testdata/external/tpcc
  pkg/sql/opt/xform/testdata/external/tpcc-later-stats
  pkg/sql/opt/xform/testdata/external/tpcc-no-stats
  pkg/sql/opt/xform/testdata/external/tpcc-read-committed
  pkg/sql/opt/xform/testdata/rules/select
  pkg/sql/schemachanger/comparator_generated_test.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/tree/overload.go
  pkg/sql/types/types.go
Labels: backport

#132092 changefeedccl: improve sink error observability
  docs/generated/metrics/metrics.html
  pkg/ccl/changefeedccl/event_processing.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/changefeedccl/sink_webhook.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#126345 opt: check type and composite sensitivity before remapping computed expressions
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/opt/lookupjoin/constraint_builder.go
  pkg/sql/opt/lookupjoin/testdata/computed
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#131858 release-23.1: server,ui: show throttle metadata from cluster in db console
  docs/generated/http/full.md
  pkg/ccl/serverccl/statusccl/BUILD.bazel
  pkg/ccl/serverccl/statusccl/tenant_status_test.go
  pkg/server/diagnostics/reporter.go
  pkg/server/serverpb/status.proto
  pkg/server/status.go
  pkg/ui/workspaces/db-console/src/app.spec.tsx
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/util/api.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/app/containers/layout/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.module.styl
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.spec.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.stories.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx
Labels: backport

#131859 release-23.2: server,ui: show throttle metadata from cluster in db console
  docs/generated/http/full.md
  pkg/ccl/serverccl/statusccl/BUILD.bazel
  pkg/ccl/serverccl/statusccl/tenant_status_test.go
  pkg/server/diagnostics/reporter.go
  pkg/server/serverpb/status.proto
  pkg/server/status.go
  pkg/ui/workspaces/db-console/src/app.spec.tsx
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/util/api.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/app/containers/layout/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.module.styl
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.spec.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.stories.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx
Labels: backport

#132354 release-24.1: lint: fix `TestForbiddenImports`
  pkg/raft/BUILD.bazel
  pkg/raft/bootstrap.go
  pkg/raft/confchange/BUILD.bazel
  pkg/raft/confchange/confchange.go
  pkg/raft/confchange/datadriven_test.go
  pkg/raft/node.go
  pkg/raft/raft.go
  pkg/raft/rafttest/BUILD.bazel
  pkg/raft/rafttest/interaction_env_handler_add_nodes.go
  pkg/raft/rafttest/interaction_env_handler_process_append_thread.go
  pkg/raft/rafttest/interaction_env_handler_report_unreachable.go
  pkg/raft/rawnode.go
  pkg/raft/storage.go
  pkg/testutils/lint/lint_test.go
Labels: backport

#132351 release-23.2: lint: fix `TestForbiddenImports`
  pkg/testutils/lint/lint_test.go
Labels: backport

#132350 release-23.1: lint: fix `TestForbiddenImports`
  pkg/testutils/lint/lint_test.go
Labels: backport

#132093 release-24.2: server,ui: show throttle metadata from cluster in db console
  docs/generated/http/full.md
  pkg/server/application_api/BUILD.bazel
  pkg/server/application_api/telemetry_test.go
  pkg/server/diagnostics/reporter.go
  pkg/server/serverpb/status.proto
  pkg/server/status.go
  pkg/ui/workspaces/db-console/src/app.spec.tsx
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/util/api.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/app/containers/layout/index.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.module.styl
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.spec.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.stories.tsx
  pkg/ui/workspaces/db-console/src/views/shared/components/alertBar/alertBar.tsx
Labels: backport

#132200 release-24.1: raft: bump proposal timeout for TestNodeProposeWaitDropped
  pkg/raft/node_test.go
Labels: backport

#132491 release-23.2.13-rc: changefeedccl: add parallel io metrics
  docs/generated/metrics/metrics.html
  pkg/ccl/changefeedccl/batching_sink.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/changefeedccl/parallel_io.go
  pkg/ccl/changefeedccl/telemetry.go
  pkg/ccl/changefeedccl/testfeed_test.go
Labels: backport

#132484 release-23.2: changefeedccl: add parallel io metrics
  docs/generated/metrics/metrics.html
  pkg/ccl/changefeedccl/batching_sink.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/changefeedccl/parallel_io.go
  pkg/ccl/changefeedccl/telemetry.go
  pkg/ccl/changefeedccl/testfeed_test.go
Labels: backport

#130898 release-23.2: opt: fix BPCHAR type and CASE typing
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/sql/logictest/testdata/logic_test/bpchar
  pkg/sql/logictest/testdata/logic_test/case
  pkg/sql/logictest/testdata/logic_test/cast
  pkg/sql/logictest/testdata/logic_test/decimal
  pkg/sql/logictest/testdata/logic_test/drop_function
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/pg_builtins
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-mixed-23.1/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/opt/optbuilder/scalar.go
  pkg/sql/opt/optbuilder/testdata/scalar
  pkg/sql/opt/xform/testdata/external/tpcc
  pkg/sql/opt/xform/testdata/external/tpcc-later-stats
  pkg/sql/opt/xform/testdata/external/tpcc-no-stats
  pkg/sql/opt/xform/testdata/external/tpcc-read-committed
  pkg/sql/opt/xform/testdata/rules/select
  pkg/sql/schemachanger/comparator_generated_test.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/tree/overload.go
  pkg/sql/types/types.go
Labels: backport

#130736 cli: CLI prints out previous error message when executing a quit command
  pkg/cli/clisqlshell/sql.go
  pkg/cli/clisqlshell/sql_test.go
  pkg/cli/interactive_tests/test_last_statement.tcl
Labels: O-community

#132347 release-23.1: utilccl, diagnostics - report license information, ensure that telemetry is sent for certain licenses
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/base/testing_knobs.go
  pkg/ccl/serverccl/statusccl/tenant_status_test.go
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/ccl/utilccl/licenseccl/license.go
  pkg/ccl/utilccl/licenseccl/license.proto
  pkg/server/diagnostics/BUILD.bazel
  pkg/server/diagnostics/diagnostics.go
  pkg/server/diagnostics/reporter.go
  pkg/server/diagnostics/reporter_test.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/server_sql.go
  pkg/server/testing_knobs.go
  pkg/server/testserver.go
  pkg/util/log/logcrash/crash_reporting.go
Labels: backport

#132461 release-23.2: utilccl, diagnostics - report license information, ensure that telemetry is sent for certain licenses
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/base/testing_knobs.go
  pkg/ccl/serverccl/statusccl/tenant_status_test.go
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/diagnostics/BUILD.bazel
  pkg/server/diagnostics/diagnostics.go
  pkg/server/diagnostics/reporter.go
  pkg/server/diagnostics/reporter_test.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/server_sql.go
  pkg/server/testing_knobs.go
  pkg/server/testserver.go
  pkg/util/log/logcrash/crash_reporting.go
Labels: backport

#132463 release-24.1: utilccl, diagnostics - report license information, ensure that telemetry is sent for certain licenses
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/base/testing_knobs.go
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/server/application_api/telemetry_test.go
  pkg/server/diagnostics/BUILD.bazel
  pkg/server/diagnostics/diagnostics.go
  pkg/server/diagnostics/reporter.go
  pkg/server/diagnostics/reporter_test.go
  pkg/server/license/enforcer.go
  pkg/server/license/enforcer_test.go
  pkg/server/server_sql.go
  pkg/server/testing_knobs.go
  pkg/server/testserver.go
  pkg/util/log/logcrash/crash_reporting.go
Labels: backport

#132507 release-23.2: opt: relax assertion for lookup join columns
  pkg/sql/opt/memo/check_expr.go
Labels: backport

#132508 release-24.2: opt: check type and composite sensitivity before remapping computed expressions
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/opt/lookupjoin/constraint_builder.go
  pkg/sql/opt/lookupjoin/testdata/computed
Labels: backport

#132509 release-24.1: opt: check type and composite sensitivity before remapping computed expressions
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/opt/lookupjoin/constraint_builder.go
  pkg/sql/opt/lookupjoin/testdata/computed
Labels: backport

#132587 release-23.1: released CockroachDB version 23.1.28. Next version: 23.1.29
  pkg/build/version.txt
Labels: backport

#132510 release-23.2: opt: check type and composite sensitivity before remapping computed expressions
  pkg/sql/logictest/testdata/logic_test/lookup_join
  pkg/sql/opt/lookupjoin/constraint_builder.go
  pkg/sql/opt/lookupjoin/testdata/computed
Labels: backport

#132593 release-23.1: obsservice: remove the package
  .github/CODEOWNERS
  .gitignore
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/BUILD.bazel
  pkg/base/constants.go
  pkg/base/test_server_args.go
  pkg/cli/cliflags/flags.go
  pkg/cli/flags.go
  pkg/cmd/dev/build.go
  pkg/cmd/dev/lint.go
  pkg/cmd/dev/testdata/datadriven/lint
  pkg/gen/protobuf.bzl
  pkg/obs/BUILD.bazel
  pkg/obs/doc.go
  pkg/obs/event_exporter.go
  pkg/obsservice/README.md
  pkg/obsservice/cmd/obsservice/BUILD.bazel
  pkg/obsservice/cmd/obsservice/main.go
  pkg/obsservice/obslib/httpproxy/BUILD.bazel
  pkg/obsservice/obslib/httpproxy/reverseproxy.go
  pkg/obsservice/obslib/ingest/BUILD.bazel
  pkg/obsservice/obslib/ingest/ingest.go
  pkg/obsservice/obslib/ingest/ingest_test.go
  pkg/obsservice/obslib/ingest/main_test.go
  pkg/obsservice/obslib/migrations/BUILD.bazel
  pkg/obsservice/obslib/migrations/migrations.go
  pkg/obsservice/obslib/migrations/sqlmigrations/0001_init.sql
  pkg/obsservice/obspb/BUILD.bazel
  pkg/obsservice/obspb/README.md
  pkg/obsservice/obspb/event_types.go
  pkg/obsservice/obspb/opentelemetry-proto.patch
  pkg/obsservice/obspb/opentelemetry-proto/collector/logs/v1/BUILD.bazel
  pkg/obsservice/obspb/opentelemetry-proto/collector/logs/v1/logs_service.proto
  pkg/obsservice/obspb/opentelemetry-proto/common/v1/BUILD.bazel
  pkg/obsservice/obspb/opentelemetry-proto/common/v1/common.proto
  pkg/obsservice/obspb/opentelemetry-proto/logs/v1/BUILD.bazel
  pkg/obsservice/obspb/opentelemetry-proto/logs/v1/logs.proto
  pkg/obsservice/obspb/opentelemetry-proto/resource/v1/BUILD.bazel
  pkg/obsservice/obspb/opentelemetry-proto/resource/v1/resource.proto
  pkg/obsservice/obspb/resource.go
  pkg/obsservice/obspb/update-opentelemetry-proto.sh
  pkg/server/BUILD.bazel
  pkg/server/config.go
  pkg/server/initial_sql.go
  pkg/server/server.go
  pkg/server/server_obs_service.go
  pkg/server/server_sql.go
  pkg/server/tenant.go
  pkg/server/testserver.go
  pkg/sql/BUILD.bazel
  pkg/sql/event_log.go
  pkg/sql/exec_util.go
  pkg/testutils/lint/lint_test.go
Labels: backport

#132314 release-24.2: server/license: Make enterprise license check a no-op
  pkg/acceptance/compose/gss/docker-compose-python.yml
  pkg/acceptance/compose/gss/docker-compose.yml
  pkg/acceptance/compose/gss/psql/gss_test.go
  pkg/acceptance/compose/gss/python/start.sh
  pkg/ccl/BUILD.bazel
  pkg/ccl/auditloggingccl/BUILD.bazel
  pkg/ccl/auditloggingccl/audit_logging_test.go
  pkg/ccl/backupccl/create_scheduled_backup_test.go
  pkg/ccl/ccl_init.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go
  pkg/ccl/logictestccl/testdata/logic_test/mixed_version_pgvector
  pkg/ccl/multiregionccl/multiregion_test.go
  pkg/ccl/partitionccl/partition_test.go
  pkg/ccl/pgcryptoccl/BUILD.bazel
  pkg/ccl/pgcryptoccl/pgcryptoccl_test.go
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/ccl/utilccl/license_test.go
  pkg/cli/interactive_tests/test_demo_partitioning.tcl
  pkg/server/application_api/config_test.go
  pkg/sql/catalog/lease/lease_test_utils.go
  pkg/sql/crdb_internal_test.go
  pkg/sql/delete_preserving_index_test.go
  pkg/sql/descriptor_mutation_test.go
  pkg/sql/index_mutation_test.go
  pkg/sql/schema_changer_test.go
  pkg/sql/temporary_schema_test.go
Labels: backport

#132330 release-24.1: server/license: Make enterprise license check a no-op
  pkg/acceptance/compose/gss/docker-compose-python.yml
  pkg/acceptance/compose/gss/docker-compose.yml
  pkg/acceptance/compose/gss/psql/gss_test.go
  pkg/acceptance/compose/gss/python/start.sh
  pkg/ccl/BUILD.bazel
  pkg/ccl/auditloggingccl/BUILD.bazel
  pkg/ccl/auditloggingccl/audit_logging_test.go
  pkg/ccl/backupccl/create_scheduled_backup_test.go
  pkg/ccl/ccl_init.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go
  pkg/ccl/multiregionccl/multiregion_test.go
  pkg/ccl/partitionccl/partition_test.go
  pkg/ccl/pgcryptoccl/BUILD.bazel
  pkg/ccl/pgcryptoccl/pgcryptoccl_test.go
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/ccl/utilccl/license_test.go
  pkg/cli/interactive_tests/test_demo_partitioning.tcl
  pkg/server/application_api/config_test.go
  pkg/sql/catalog/lease/lease_test_utils.go
  pkg/sql/crdb_internal_test.go
  pkg/sql/delete_preserving_index_test.go
  pkg/sql/descriptor_mutation_test.go
  pkg/sql/index_mutation_test.go
  pkg/sql/schema_changer_test.go
  pkg/sql/temporary_schema_test.go
Labels: backport

#132342 release-23.2: server/license: Make enterprise license check a no-op
  pkg/acceptance/compose/gss/docker-compose-python.yml
  pkg/acceptance/compose/gss/docker-compose.yml
  pkg/acceptance/compose/gss/psql/gss_test.go
  pkg/acceptance/compose/gss/python/start.sh
  pkg/ccl/BUILD.bazel
  pkg/ccl/auditloggingccl/BUILD.bazel
  pkg/ccl/auditloggingccl/audit_logging_test.go
  pkg/ccl/backupccl/create_scheduled_backup_test.go
  pkg/ccl/ccl_init.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go
  pkg/ccl/multiregionccl/multiregion_test.go
  pkg/ccl/partitionccl/partition_test.go
  pkg/ccl/pgcryptoccl/BUILD.bazel
  pkg/ccl/pgcryptoccl/pgcryptoccl_test.go
  pkg/ccl/streamingccl/streamproducer/replication_manager_test.go
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/ccl/utilccl/license_test.go
  pkg/cli/interactive_tests/test_demo_partitioning.tcl
  pkg/sql/catalog/lease/lease_test_utils.go
  pkg/sql/crdb_internal_test.go
  pkg/sql/delete_preserving_index_test.go
  pkg/sql/descriptor_mutation_test.go
  pkg/sql/index_mutation_test.go
  pkg/sql/schema_changer_test.go
  pkg/sql/temporary_schema_test.go
Labels: backport

#132427 release-23.1: server/license: Make enterprise license check a no-op
  pkg/acceptance/compose/gss/docker-compose-python.yml
  pkg/acceptance/compose/gss/docker-compose.yml
  pkg/acceptance/compose/gss/psql/gss_test.go
  pkg/acceptance/compose/gss/python/start.sh
  pkg/base/license.go
  pkg/ccl/BUILD.bazel
  pkg/ccl/auditloggingccl/BUILD.bazel
  pkg/ccl/auditloggingccl/audit_logging_test.go
  pkg/ccl/backupccl/create_scheduled_backup_test.go
  pkg/ccl/ccl_init.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go
  pkg/ccl/multiregionccl/multiregion_test.go
  pkg/ccl/partitionccl/partition_test.go
  pkg/ccl/streamingccl/streamproducer/replication_manager_test.go
  pkg/ccl/utilccl/BUILD.bazel
  pkg/ccl/utilccl/license_check.go
  pkg/ccl/utilccl/license_check_test.go
  pkg/ccl/utilccl/license_test.go
  pkg/cli/interactive_tests/test_demo_partitioning.tcl.disabled
  pkg/server/testserver.go
  pkg/sql/catalog/lease/lease_test_utils.go
  pkg/sql/crdb_internal_test.go
  pkg/sql/delete_preserving_index_test.go
  pkg/sql/descriptor_mutation_test.go
  pkg/sql/index_mutation_test.go
  pkg/sql/schema_changer_test.go
  pkg/sql/temporary_schema_test.go
Labels: backport

#132662 release-23.1: *: update kv teams
  .github/CODEOWNERS
  TEAMS.yaml
  pkg/cmd/roachtest/registry/filter_test.go
  pkg/cmd/roachtest/registry/owners.go
  pkg/cmd/roachtest/registry/testdata/filter/describe
  pkg/cmd/roachtest/registry/testdata/filter/errors
  pkg/cmd/roachtest/tests/inconsistency.go
  pkg/cmd/roachtest/tests/kv.go
  pkg/cmd/roachtest/tests/loss_of_quorum_recovery.go
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
  pkg/cmd/roachtest/tests/replicagc.go
Labels: backport

#132680 release-24.2: server: Fix NPE in spanStatsFanOut
  pkg/server/BUILD.bazel
  pkg/server/span_stats_server.go
  pkg/server/span_stats_server_test.go
Labels: backport

#132681 release-24.1: server: Fix NPE in spanStatsFanOut
  pkg/server/BUILD.bazel
  pkg/server/span_stats_server.go
  pkg/server/span_stats_server_test.go
Labels: backport

#132685 release-23.1: server: Fix NPE in spanStatsFanOut
  pkg/server/span_stats_server.go
  pkg/server/span_stats_server_test.go
Labels: backport

#132621 release-24.2: roachtest: disable zone config evacuation for v22.2 nodes
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
Labels: backport

#132620 release-24.1: roachtest: disable zone config evacuation for v22.2 nodes
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
Labels: backport

#132619 release-23.2: roachtest: disable zone config evacuation for v22.2 nodes
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
Labels: backport

#132721 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#132720 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#132719 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#132683 release-23.2: server: Fix NPE in spanStatsFanOut
  pkg/server/BUILD.bazel
  pkg/server/span_stats_server.go
  pkg/server/span_stats_server_test.go
Labels: backport

#132748 release-24.2: ldapccl,sql: validate ldap options provided in HBA config entry
  pkg/ccl/ldapccl/BUILD.bazel
  pkg/ccl/ldapccl/authentication_ldap.go
  pkg/ccl/ldapccl/authentication_ldap_test.go
  pkg/ccl/ldapccl/ldap_test_util.go
  pkg/ccl/testccl/authccl/BUILD.bazel
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/ccl/testccl/authccl/testdata/ldap
  pkg/sql/pgwire/auth_methods.go
Labels: backport

#132817 release-24.2: testccl: fix TestAuthenticationAndHBARules due to updated HBA options format
  pkg/ccl/testccl/authccl/testdata/ldap
Labels: backport

#132784 release-23.2: changefeedccl: bump franz-go dependency to fix deadlock
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#132785 release-24.1: changefeedccl: bump franz-go dependency to fix deadlock
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#132787 release-24.2: changefeedccl: bump franz-go dependency to fix deadlock
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#132774 release-23.2: changefeedccl: fix failure to updating PTS in retryable errors
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/jobs/update.go
Labels: backport

#132775 release-24.1: changefeedccl: fix failure to updating PTS in retryable errors
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/jobs/update.go
Labels: backport

#132810 release-24.1: stringer: add license header to stringer-generated files
  pkg/base/testclusterreplicationmode_string.go
  pkg/build/bazel/util/tinystringer/main.go
  pkg/ccl/backupccl/targetscope_string.go
  pkg/ccl/changefeedccl/schemafeed/tableeventtype_string.go
  pkg/ccl/sqlproxyccl/errorcode_string.go
  pkg/cli/keytype_string.go
  pkg/config/field_string.go
  pkg/kv/kvclient/kvcoord/txnstate_string.go
  pkg/kv/kvpb/errordetailtype_string.go
  pkg/kv/kvpb/method_string.go
  pkg/kv/kvserver/closedts/sidetransport/cantclosereason_string.go
  pkg/kv/kvserver/refreshraftreason_string.go
  pkg/multitenant/tenantcapabilities/id_string.go
  pkg/raft/quorum/voteresult_string.go
  pkg/server/license/lictype_string.go
  pkg/sql/advancecode_string.go
  pkg/sql/catalog/catalogkeys/commenttype_string.go
  pkg/sql/catalog/catpb/privilegedescversion_string.go
  pkg/sql/catalog/descpb/formatversion_string.go
  pkg/sql/catalog/lease/sessionbasedleasingmode_string.go
  pkg/sql/colfetcher/fetcherstate_string.go
  pkg/sql/execinfra/consumerstatus_string.go
  pkg/sql/execinfra/procstate_string.go
  pkg/sql/nodestatus_string.go
  pkg/sql/opt/optgen/lang/operator_string.go
  pkg/sql/opt/optgen/lang/token_string.go
  pkg/sql/pgwire/pgwirebase/clientmessagetype_string.go
  pkg/sql/pgwire/pgwirebase/formatcode_string.go
  pkg/sql/pgwire/pgwirebase/pgnumericsign_string.go
  pkg/sql/pgwire/pgwirebase/preparetype_string.go
  pkg/sql/pgwire/pgwirebase/servererrfieldtype_string.go
  pkg/sql/pgwire/pgwirebase/servermessagetype_string.go
  pkg/sql/roleoption/option_string.go
  pkg/sql/schemachange/columnconversionkind_string.go
  pkg/sql/schemachanger/rel/internal/comparetest/testattr_string.go
  pkg/sql/schemachanger/rel/internal/cyclegraphtest/testattr_string.go
  pkg/sql/schemachanger/rel/internal/entitynodetest/testattr_string.go
  pkg/sql/schemachanger/rel/systemattribute_string.go
  pkg/sql/schemachanger/scop/phase_string.go
  pkg/sql/schemachanger/scop/type_string.go
  pkg/sql/schemachanger/scplan/internal/scgraph/depedgekind_string.go
  pkg/sql/schemachanger/screl/attr_string.go
  pkg/sql/schemachanger/sctest/stageexectype_string.go
  pkg/sql/sem/tree/createtypevariety_string.go
  pkg/sql/sem/tree/statementreturntype_string.go
  pkg/sql/sem/tree/statementtype_string.go
  pkg/sql/txneventtype_string.go
  pkg/sql/txntype_string.go
  pkg/util/encoding/type_string.go
  pkg/util/timeutil/pgdate/field_string.go
  pkg/workload/schemachange/optype_string.go
Labels: backport

#132809 release-24.2: stringer: add license header to stringer-generated files
  pkg/base/testclusterreplicationmode_string.go
  pkg/build/bazel/util/tinystringer/main.go
  pkg/ccl/backupccl/targetscope_string.go
  pkg/ccl/changefeedccl/schemafeed/tableeventtype_string.go
  pkg/ccl/sqlproxyccl/errorcode_string.go
  pkg/cli/keytype_string.go
  pkg/config/field_string.go
  pkg/kv/kvclient/kvcoord/txnstate_string.go
  pkg/kv/kvpb/errordetailtype_string.go
  pkg/kv/kvpb/method_string.go
  pkg/kv/kvserver/closedts/sidetransport/cantclosereason_string.go
  pkg/kv/kvserver/refreshraftreason_string.go
  pkg/multitenant/tenantcapabilities/id_string.go
  pkg/raft/quorum/voteresult_string.go
  pkg/server/license/lictype_string.go
  pkg/sql/advancecode_string.go
  pkg/sql/catalog/catalogkeys/commenttype_string.go
  pkg/sql/catalog/catpb/privilegedescversion_string.go
  pkg/sql/catalog/descpb/formatversion_string.go
  pkg/sql/catalog/lease/sessionbasedleasingmode_string.go
  pkg/sql/colfetcher/fetcherstate_string.go
  pkg/sql/execinfra/consumerstatus_string.go
  pkg/sql/execinfra/procstate_string.go
  pkg/sql/nodestatus_string.go
  pkg/sql/opt/optgen/lang/operator_string.go
  pkg/sql/opt/optgen/lang/token_string.go
  pkg/sql/pgwire/pgwirebase/clientmessagetype_string.go
  pkg/sql/pgwire/pgwirebase/formatcode_string.go
  pkg/sql/pgwire/pgwirebase/pgnumericsign_string.go
  pkg/sql/pgwire/pgwirebase/preparetype_string.go
  pkg/sql/pgwire/pgwirebase/servererrfieldtype_string.go
  pkg/sql/pgwire/pgwirebase/servermessagetype_string.go
  pkg/sql/roleoption/option_string.go
  pkg/sql/schemachange/columnconversionkind_string.go
  pkg/sql/schemachanger/rel/internal/comparetest/testattr_string.go
  pkg/sql/schemachanger/rel/internal/cyclegraphtest/testattr_string.go
  pkg/sql/schemachanger/rel/internal/entitynodetest/testattr_string.go
  pkg/sql/schemachanger/rel/systemattribute_string.go
  pkg/sql/schemachanger/scop/phase_string.go
  pkg/sql/schemachanger/scop/type_string.go
  pkg/sql/schemachanger/scplan/internal/scgraph/depedgekind_string.go
  pkg/sql/schemachanger/screl/attr_string.go
  pkg/sql/schemachanger/sctest/stageexectype_string.go
  pkg/sql/sem/tree/createtypevariety_string.go
  pkg/sql/sem/tree/statementreturntype_string.go
  pkg/sql/sem/tree/statementtype_string.go
  pkg/sql/txneventtype_string.go
  pkg/sql/txntype_string.go
  pkg/util/encoding/type_string.go
  pkg/util/timeutil/pgdate/field_string.go
  pkg/workload/schemachange/optype_string.go
Labels: backport

#132804 release-23.1: lint: require license headers for all scss files
  pkg/testutils/lint/lint_test.go
  pkg/ui/workspaces/cluster-ui/src/NotificationMessage/notificationMessage.module.scss
  pkg/ui/workspaces/cluster-ui/src/anchor/anchor.module.scss
  pkg/ui/workspaces/cluster-ui/src/badge/badge.module.scss
  pkg/ui/workspaces/cluster-ui/src/barCharts/barCharts.module.scss
  pkg/ui/workspaces/cluster-ui/src/button/button.module.scss
  pkg/ui/workspaces/cluster-ui/src/columnsSelector/columnsSelector.module.scss
  pkg/ui/workspaces/cluster-ui/src/common/styles.module.scss
  pkg/ui/workspaces/cluster-ui/src/core/base.module.scss
  pkg/ui/workspaces/cluster-ui/src/core/colors.module.scss
  pkg/ui/workspaces/cluster-ui/src/core/index.module.scss
  pkg/ui/workspaces/cluster-ui/src/core/typography.module.scss
  pkg/ui/workspaces/cluster-ui/src/dateRangeMenu/dateRangeMenu.module.scss
  pkg/ui/workspaces/cluster-ui/src/dropdown/dropdown.module.scss
  pkg/ui/workspaces/cluster-ui/src/empty/emptyPanel/emptyPanel.module.scss
  pkg/ui/workspaces/cluster-ui/src/empty/emptyTable/emptyTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bargraph.module.scss
  pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.module.scss
  pkg/ui/workspaces/cluster-ui/src/insights/indexActionBtn.module.scss
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/insightsDetails.module.scss
  pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/loading/loading.module.scss
  pkg/ui/workspaces/cluster-ui/src/modal/modal.module.scss
  pkg/ui/workspaces/cluster-ui/src/multiSelectCheckbox/multiSelectCheckbox.module.scss
  pkg/ui/workspaces/cluster-ui/src/outsideEventHandler/outsideEventHandler.module.scss
  pkg/ui/workspaces/cluster-ui/src/pageConfig/pageConfig.module.scss
  pkg/ui/workspaces/cluster-ui/src/pagination/pagination.module.scss
  pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.module.scss
  pkg/ui/workspaces/cluster-ui/src/recentExecutions/executionStatusIcon.module.scss
  pkg/ui/workspaces/cluster-ui/src/search/search.module.scss
  pkg/ui/workspaces/cluster-ui/src/searchCriteria/searchCriteria.module.scss
  pkg/ui/workspaces/cluster-ui/src/settings/booleanSetting.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/table.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/tableHead/tableHead.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/tableRow/tableRow.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/tableSpinner/tableSpinner.module.scss
  pkg/ui/workspaces/cluster-ui/src/sqlActivity/sqlActivity.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsDiagnostics/activateStatementDiagnosticsModal.scss
  pkg/ui/workspaces/cluster-ui/src/statementsDiagnostics/diagnosticStatusBadge.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementTypeSelect.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTableContent.module.scss
  pkg/ui/workspaces/cluster-ui/src/summaryCard/summaryCard.module.scss
  pkg/ui/workspaces/cluster-ui/src/table/table.module.scss
  pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.module.scss
  pkg/ui/workspaces/cluster-ui/src/text/text.module.scss
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/rangeSelector.module.scss
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeFrameControls.module.scss
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScale.module.scss
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.modules.scss
  pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsCells/transactionsCells.module.scss
Labels: backport

#132803 release-23.2: lint: require license headers for all scss files
  pkg/testutils/lint/lint_test.go
  pkg/ui/workspaces/cluster-ui/src/NotificationMessage/notificationMessage.module.scss
  pkg/ui/workspaces/cluster-ui/src/activeExecutions/executionStatusIcon.module.scss
  pkg/ui/workspaces/cluster-ui/src/anchor/anchor.module.scss
  pkg/ui/workspaces/cluster-ui/src/badge/badge.module.scss
  pkg/ui/workspaces/cluster-ui/src/barCharts/barCharts.module.scss
  pkg/ui/workspaces/cluster-ui/src/button/button.module.scss
  pkg/ui/workspaces/cluster-ui/src/columnsSelector/columnsSelector.module.scss
  pkg/ui/workspaces/cluster-ui/src/common/styles.module.scss
  pkg/ui/workspaces/cluster-ui/src/core/base.module.scss
  pkg/ui/workspaces/cluster-ui/src/core/colors.module.scss
  pkg/ui/workspaces/cluster-ui/src/core/index.module.scss
  pkg/ui/workspaces/cluster-ui/src/core/typography.module.scss
  pkg/ui/workspaces/cluster-ui/src/dateRangeMenu/dateRangeMenu.module.scss
  pkg/ui/workspaces/cluster-ui/src/dropdown/dropdown.module.scss
  pkg/ui/workspaces/cluster-ui/src/empty/emptyPanel/emptyPanel.module.scss
  pkg/ui/workspaces/cluster-ui/src/empty/emptyTable/emptyTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bargraph.module.scss
  pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.module.scss
  pkg/ui/workspaces/cluster-ui/src/insights/indexActionBtn.module.scss
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/insightsDetails.module.scss
  pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobProfilerView.module.scss
  pkg/ui/workspaces/cluster-ui/src/loading/loading.module.scss
  pkg/ui/workspaces/cluster-ui/src/modal/modal.module.scss
  pkg/ui/workspaces/cluster-ui/src/multiSelectCheckbox/multiSelectCheckbox.module.scss
  pkg/ui/workspaces/cluster-ui/src/outsideEventHandler/outsideEventHandler.module.scss
  pkg/ui/workspaces/cluster-ui/src/pageConfig/pageConfig.module.scss
  pkg/ui/workspaces/cluster-ui/src/pagination/pagination.module.scss
  pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.module.scss
  pkg/ui/workspaces/cluster-ui/src/search/search.module.scss
  pkg/ui/workspaces/cluster-ui/src/searchCriteria/searchCriteria.module.scss
  pkg/ui/workspaces/cluster-ui/src/settings/booleanSetting.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/table.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/tableHead/tableHead.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/tableRow/tableRow.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/tableSpinner/tableSpinner.module.scss
  pkg/ui/workspaces/cluster-ui/src/sqlActivity/sqlActivity.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsDiagnostics/activateStatementDiagnosticsModal.scss
  pkg/ui/workspaces/cluster-ui/src/statementsDiagnostics/diagnosticStatusBadge.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementTypeSelect.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTableContent.module.scss
  pkg/ui/workspaces/cluster-ui/src/summaryCard/summaryCard.module.scss
  pkg/ui/workspaces/cluster-ui/src/table/table.module.scss
  pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.module.scss
  pkg/ui/workspaces/cluster-ui/src/text/text.module.scss
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/rangeSelector.module.scss
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeFrameControls.module.scss
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScale.module.scss
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.modules.scss
  pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsCells/transactionsCells.module.scss
Labels: backport

#132802 release-24.1: lint: require license headers for all scss files
  pkg/testutils/lint/lint_test.go
  pkg/ui/workspaces/cluster-ui/src/NotificationMessage/notificationMessage.module.scss
  pkg/ui/workspaces/cluster-ui/src/activeExecutions/executionStatusIcon.module.scss
  pkg/ui/workspaces/cluster-ui/src/anchor/anchor.module.scss
  pkg/ui/workspaces/cluster-ui/src/badge/badge.module.scss
  pkg/ui/workspaces/cluster-ui/src/barCharts/barCharts.module.scss
  pkg/ui/workspaces/cluster-ui/src/button/button.module.scss
  pkg/ui/workspaces/cluster-ui/src/columnsSelector/columnsSelector.module.scss
  pkg/ui/workspaces/cluster-ui/src/common/styles.module.scss
  pkg/ui/workspaces/cluster-ui/src/core/base.module.scss
  pkg/ui/workspaces/cluster-ui/src/core/colors.module.scss
  pkg/ui/workspaces/cluster-ui/src/core/index.module.scss
  pkg/ui/workspaces/cluster-ui/src/core/typography.module.scss
  pkg/ui/workspaces/cluster-ui/src/dateRangeMenu/dateRangeMenu.module.scss
  pkg/ui/workspaces/cluster-ui/src/dropdown/dropdown.module.scss
  pkg/ui/workspaces/cluster-ui/src/empty/emptyPanel/emptyPanel.module.scss
  pkg/ui/workspaces/cluster-ui/src/empty/emptyTable/emptyTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/graphs/bargraph/bargraph.module.scss
  pkg/ui/workspaces/cluster-ui/src/highlightedText/highlightedText.module.scss
  pkg/ui/workspaces/cluster-ui/src/insights/indexActionBtn.module.scss
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/insightsDetails.module.scss
  pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/jobs/jobDetailsPage/jobProfilerView.module.scss
  pkg/ui/workspaces/cluster-ui/src/loading/loading.module.scss
  pkg/ui/workspaces/cluster-ui/src/modal/modal.module.scss
  pkg/ui/workspaces/cluster-ui/src/multiSelectCheckbox/multiSelectCheckbox.module.scss
  pkg/ui/workspaces/cluster-ui/src/outsideEventHandler/outsideEventHandler.module.scss
  pkg/ui/workspaces/cluster-ui/src/pageConfig/pageConfig.module.scss
  pkg/ui/workspaces/cluster-ui/src/pagination/pagination.module.scss
  pkg/ui/workspaces/cluster-ui/src/queryFilter/filter.module.scss
  pkg/ui/workspaces/cluster-ui/src/search/search.module.scss
  pkg/ui/workspaces/cluster-ui/src/searchCriteria/searchCriteria.module.scss
  pkg/ui/workspaces/cluster-ui/src/settings/booleanSetting.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/sortedtable.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/table.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/tableHead/tableHead.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/tableRow/tableRow.module.scss
  pkg/ui/workspaces/cluster-ui/src/sortedtable/tableSpinner/tableSpinner.module.scss
  pkg/ui/workspaces/cluster-ui/src/sqlActivity/sqlActivity.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsView.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planView/planView.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsDiagnostics/activateStatementDiagnosticsModal.scss
  pkg/ui/workspaces/cluster-ui/src/statementsDiagnostics/diagnosticStatusBadge.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementTypeSelect.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTableContent.module.scss
  pkg/ui/workspaces/cluster-ui/src/summaryCard/summaryCard.module.scss
  pkg/ui/workspaces/cluster-ui/src/table/table.module.scss
  pkg/ui/workspaces/cluster-ui/src/tableStatistics/tableStatistics.module.scss
  pkg/ui/workspaces/cluster-ui/src/text/text.module.scss
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/rangeSelector.module.scss
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeFrameControls.module.scss
  pkg/ui/workspaces/cluster-ui/src/timeScaleDropdown/timeScale.module.scss
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.modules.scss
  pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsCells/transactionsCells.module.scss
Labels: backport

#131655 release-23.2: changefeedccl: protect system.role_members using protected timestamps
  pkg/ccl/changefeedccl/protected_timestamps.go
  pkg/ccl/changefeedccl/protected_timestamps_test.go
Labels: backport

#132120 release-24.2: sql/row: fix updates of single-composite-column families
  pkg/sql/colenc/encode.go
  pkg/sql/logictest/testdata/logic_test/column_families
  pkg/sql/row/helper.go
  pkg/sql/row/writer.go
Labels: backport

#132122 release-24.1: sql/row: fix updates of single-composite-column families
  pkg/sql/colenc/encode.go
  pkg/sql/logictest/testdata/logic_test/column_families
  pkg/sql/row/helper.go
  pkg/sql/row/writer.go
Labels: backport

#132123 release-23.2: sql/row: fix updates of single-composite-column families
  pkg/sql/colenc/encode.go
  pkg/sql/logictest/testdata/logic_test/column_families
  pkg/sql/row/helper.go
  pkg/sql/row/writer.go
Labels: backport

#132124 release-23.1: sql/row: fix updates of single-composite-column families
  pkg/sql/colenc/encode.go
  pkg/sql/logictest/testdata/logic_test/column_families
  pkg/sql/row/helper.go
  pkg/sql/row/writer.go
Labels: backport

#132812 release-23.1: stringer: add license header to stringer-generated files
  pkg/base/testclusterreplicationmode_string.go
  pkg/build/bazel/util/tinystringer/main.go
  pkg/ccl/backupccl/targetscope_string.go
  pkg/ccl/changefeedccl/schemafeed/tableeventtype_string.go
  pkg/ccl/sqlproxyccl/errorcode_string.go
  pkg/cli/keytype_string.go
  pkg/config/field_string.go
  pkg/kv/kvclient/kvcoord/txnstate_string.go
  pkg/kv/kvpb/errordetailtype_string.go
  pkg/kv/kvpb/method_string.go
  pkg/kv/kvserver/closedts/sidetransport/cantclosereason_string.go
  pkg/kv/kvserver/refreshraftreason_string.go
  pkg/multitenant/tenantcapabilities/id_string.go
  pkg/server/license/lictype_string.go
  pkg/sql/advancecode_string.go
  pkg/sql/catalog/catalogkeys/commenttype_string.go
  pkg/sql/catalog/catpb/privilegedescversion_string.go
  pkg/sql/catalog/descpb/formatversion_string.go
  pkg/sql/colfetcher/fetcherstate_string.go
  pkg/sql/execinfra/consumerstatus_string.go
  pkg/sql/execinfra/procstate_string.go
  pkg/sql/nodestatus_string.go
  pkg/sql/opt/optgen/lang/operator_string.go
  pkg/sql/opt/optgen/lang/token_string.go
  pkg/sql/pgwire/pgwirebase/clientmessagetype_string.go
  pkg/sql/pgwire/pgwirebase/formatcode_string.go
  pkg/sql/pgwire/pgwirebase/pgnumericsign_string.go
  pkg/sql/pgwire/pgwirebase/preparetype_string.go
  pkg/sql/pgwire/pgwirebase/servererrfieldtype_string.go
  pkg/sql/pgwire/pgwirebase/servermessagetype_string.go
  pkg/sql/privilege/kind_string.go
  pkg/sql/roleoption/option_string.go
  pkg/sql/schemachange/columnconversionkind_string.go
  pkg/sql/schemachanger/rel/internal/comparetest/testattr_string.go
  pkg/sql/schemachanger/rel/internal/cyclegraphtest/testattr_string.go
  pkg/sql/schemachanger/rel/internal/entitynodetest/testattr_string.go
  pkg/sql/schemachanger/rel/systemattribute_string.go
  pkg/sql/schemachanger/scop/phase_string.go
  pkg/sql/schemachanger/scop/type_string.go
  pkg/sql/schemachanger/scplan/internal/scgraph/depedgekind_string.go
  pkg/sql/schemachanger/screl/attr_string.go
  pkg/sql/sem/tree/createtypevariety_string.go
  pkg/sql/sem/tree/statementreturntype_string.go
  pkg/sql/sem/tree/statementtype_string.go
  pkg/sql/txneventtype_string.go
  pkg/sql/txntype_string.go
  pkg/util/encoding/type_string.go
  pkg/util/timeutil/pgdate/field_string.go
  pkg/workload/schemachange/optype_string.go
Labels: backport

#132853 sql: fix pg_catalog.pg_proc(proretset) column
  pkg/sql/logictest/testdata/logic_test/json_builtins
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/pg_catalog.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#132863 cloud: add WithClientName option
  pkg/ccl/backupccl/backup_processor.go
  pkg/ccl/changefeedccl/sink_cloudstorage.go
  pkg/ccl/changefeedccl/sink_cloudstorage_test.go
  pkg/cloud/BUILD.bazel
  pkg/cloud/amazon/aws_kms.go
  pkg/cloud/amazon/s3_storage.go
  pkg/cloud/amazon/s3_storage_test.go
  pkg/cloud/azure/azure_storage.go
  pkg/cloud/cloud_io.go
  pkg/cloud/external_storage.go
  pkg/cloud/gcp/gcs_storage.go
  pkg/cloud/httpsink/http_storage.go
  pkg/cloud/metrics.go
  pkg/cloud/options.go
  pkg/cloud/options_test.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#132895 release-24.2: sql: add old zone config in zone config logs
  docs/generated/eventlog.md
  pkg/sql/logictest/testdata/logic_test/event_log
  pkg/sql/logictest/testdata/logic_test/event_log_legacy
  pkg/sql/schemachanger/scbuild/event_log.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/configure_zone.go
  pkg/sql/schemachanger/testdata/end_to_end/alter_database_configure_zone/alter_database_configure_zone.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/alter_database_configure_zone_multiple/alter_database_configure_zone_multiple.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_configure_zone/alter_table_configure_zone.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_configure_zone_multiple/alter_table_configure_zone_multiple.side_effects
  pkg/sql/set_zone_config.go
  pkg/util/log/eventpb/json_encode_generated.go
  pkg/util/log/eventpb/zone_events.proto
Labels: backport
