Repository cockroachdb/cockroach, pull requests merged in 2024-08, with the labels that each got.

#127892 release-24.2: crosscluster: heartbeat retained time to source cluster
  pkg/ccl/crosscluster/physical/alter_replication_job_test.go
  pkg/ccl/crosscluster/physical/stream_ingestion_dist.go
  pkg/ccl/crosscluster/physical/stream_ingestion_frontier_processor.go
  pkg/ccl/crosscluster/physical/stream_ingestion_job_test.go
  pkg/ccl/crosscluster/replicationtestutils/BUILD.bazel
  pkg/ccl/crosscluster/replicationtestutils/testutils.go
  pkg/ccl/crosscluster/replicationutils/utils.go
Labels: backport

#128056 release-24.2: backport changes needed for Cloud 2.0
  docs/generated/metrics/metrics.html
  pkg/ccl/multitenantccl/tenantcostclient/BUILD.bazel
  pkg/ccl/multitenantccl/tenantcostclient/limiter_test.go
  pkg/ccl/multitenantccl/tenantcostclient/metrics.go
  pkg/ccl/multitenantccl/tenantcostclient/metrics_test.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side_test.go
  pkg/ccl/multitenantccl/tenantcostclient/testdata/consumption
  pkg/ccl/multitenantccl/tenantcostclient/testdata/estimated-cpu
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker_test.go
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvclient/kvcoord/transport_test.go
  pkg/kv/kvserver/replica_rate_limit.go
  pkg/kv/kvserver/tenantrate/limiter_test.go
  pkg/multitenant/tenantcostmodel/BUILD.bazel
  pkg/multitenant/tenantcostmodel/ecpu_model.go
  pkg/multitenant/tenantcostmodel/ecpu_model_test.go
  pkg/multitenant/tenantcostmodel/ru_model.go
  pkg/server/tenant.go
Labels: backport

#128079 release-24.2: roachtest: label randomized tests
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/costfuzz.go
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_cdc.go
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
  pkg/cmd/roachtest/tests/mixed_version_import.go
  pkg/cmd/roachtest/tests/mixed_version_multi_region.go
  pkg/cmd/roachtest/tests/mixed_version_schemachange.go
  pkg/cmd/roachtest/tests/mixed_version_sql_stats.go
  pkg/cmd/roachtest/tests/rebalance_load.go
  pkg/cmd/roachtest/tests/secondary_indexes.go
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/cmd/roachtest/tests/tlp.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/unoptimized_query_oracle.go
Labels: backport

#127816 support SHOW SCHEMAS WITH COMMENT
  docs/generated/sql/bnf/show_schemas.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/delegate/show_schemas.go
  pkg/sql/logictest/testdata/logic_test/comment_on
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/show
  pkg/sql/sem/tree/show.go
Labels: O-community

#127718 opt: fix SKIP LOCKED under Read Committed isolation
  pkg/ccl/logictestccl/testdata/logic_test/select_for_update_read_committed
  pkg/sql/exec_factory_util.go
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/locking.go
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/memo/logical_props_builder.go
  pkg/sql/opt/norm/BUILD.bazel
  pkg/sql/opt/norm/lock_funcs.go
  pkg/sql/opt/norm/rules/limit.opt
  pkg/sql/opt/norm/testdata/rules/limit
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/testdata/select_for_update
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#127927 release-24.1: roachtest: ignore 3 flaky ruby tests
  pkg/cmd/roachtest/tests/ruby_pg_blocklist.go
Labels: backport

#128086 release-24.2: roachtest/mixedversion: add support for shared-process deployments
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/context.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/basic_test_mixed_version_hooks
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/cluster_setting
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/conflicting_mutators
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/local_runs_reduced_wait_time
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/minimum_supported_version
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/multiple_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/mutator_probabilities
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/preserve_downgrade_option_randomizer
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/shared_process
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/skip_version_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/step_stages
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/test_releases.yaml
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_cdc.go
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
  pkg/cmd/roachtest/tests/mixed_version_import.go
  pkg/cmd/roachtest/tests/mixed_version_sql_stats.go
  pkg/cmd/roachtest/tests/rebalance_load.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go
  pkg/cmd/roachtest/tests/versionupgrade.go
  pkg/roachprod/install/expander.go
  pkg/testutils/release/releases.go
Labels: backport

#127817 release-24.2: clusterversion: mint 24.2
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/build/version.txt
  pkg/clusterversion/cockroach_versions.go
  pkg/sql/catalog/bootstrap/testdata/testdata
  pkg/sql/catalog/systemschema/system.go
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_system
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_tenant
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
Labels: backport

#127508 jwtauthccl: add mapper for issuer url to jwks URI
  pkg/ccl/jwtauthccl/BUILD.bazel
  pkg/ccl/jwtauthccl/authentication_jwt.go
  pkg/ccl/jwtauthccl/authentication_jwt_test.go
  pkg/ccl/jwtauthccl/settings.go
  pkg/ccl/jwtauthccl/settings_test.go
  pkg/ccl/oidcccl/authentication_oidc_test.go
  pkg/ccl/testccl/authccl/auth_test.go
Labels: 24.2

#128131 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#128132 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#128134 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#128135 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#127654 release-23.1: pgwire: unify serialization error handling
  pkg/sql/pgwire/conn.go
Labels: backport

#127862 release-24.2: sql/stats: fix some flaky partial stats tests
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/opt/exec/execbuilder/testdata/partial_stats
Labels: backport

#127837 roachtest: add RequiresDeprecatedWorkload testSpec
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/test/test_interface.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/admission_control_index_overload.go
  pkg/cmd/roachtest/tests/admission_control_tpcc_overload.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/cdc.go
  pkg/cmd/roachtest/tests/connection_latency.go
  pkg/cmd/roachtest/tests/indexes.go
  pkg/cmd/roachtest/tests/inverted_index.go
  pkg/cmd/roachtest/tests/ledger.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_schemachange.go
  pkg/cmd/roachtest/tests/queue.go
  pkg/cmd/roachtest/tests/roachmart.go
  pkg/cmd/roachtest/tests/schemachange_random_load.go
  pkg/cmd/roachtest/tests/tpchbench.go
Labels: backport-24.1.x, backport-24.2.x

#128186 roachtest: increase internal query timeout in mixedversion
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
Labels: backport-24.2.x

#128119 roachtest: change-replicas/mixed-version supports shared-process
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
Labels: backport-24.2.x

#128009 release-24.2: storage: per-store categorized write metrics
  docs/generated/metrics/metrics.html
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/cli/debug.go
  pkg/cli/log_flags.go
  pkg/cmd/roachtest/run.go
  pkg/kv/kvserver/metrics.go
  pkg/server/BUILD.bazel
  pkg/server/config.go
  pkg/server/config_test.go
  pkg/server/server_sql.go
  pkg/sql/admin_audit_log_test.go
  pkg/sql/event_log_test.go
  pkg/sql/pgwire/auth_test.go
  pkg/storage/BUILD.bazel
  pkg/storage/disk/BUILD.bazel
  pkg/storage/disk/monitor.go
  pkg/storage/disk/platform_darwin.go
  pkg/storage/disk/platform_default.go
  pkg/storage/disk/stats_collector.go
  pkg/storage/disk_map_test.go
  pkg/storage/fs/BUILD.bazel
  pkg/storage/fs/fs.go
  pkg/storage/metamorphic/generator.go
  pkg/storage/open.go
  pkg/storage/pebble.go
  pkg/storage/temp_engine.go
  pkg/storage/temp_engine_test.go
  pkg/util/log/clog_test.go
  pkg/util/log/file_log_gc_test.go
  pkg/util/log/flags.go
  pkg/util/log/flags_test.go
  pkg/util/log/fluent_client_test.go
  pkg/util/log/formats_test.go
  pkg/util/log/http_sink_test.go
  pkg/util/log/logtestutils/log_test_utils.go
  pkg/util/log/redact_test.go
  pkg/util/log/registry_test.go
  pkg/util/log/secondary_log_test.go
  pkg/util/log/test_log_scope.go
  pkg/util/log/testshout/shout_test.go
  pkg/workload/cli/run.go
Labels: backport

#128198 ldr: send frontier updates to heartbeater
  pkg/ccl/crosscluster/logical/BUILD.bazel
  pkg/ccl/crosscluster/logical/logical_replication_job.go
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/replicationutils/BUILD.bazel
  pkg/ccl/crosscluster/replicationutils/utils.go
Labels: T-disaster-recovery, backport-24.2.x

#127925 backupccl: distribute restore validation work
  pkg/ccl/backupccl/generative_split_and_scatter_processor.go
  pkg/ccl/backupccl/generative_split_and_scatter_processor_test.go
  pkg/ccl/backupccl/restore_processor_planning.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#128189 release-24.1: roachtest: add RequiresDeprecatedWorkload testSpec
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/test/test_interface.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/admission_control_tpcc_overload.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/cdc.go
  pkg/cmd/roachtest/tests/connection_latency.go
  pkg/cmd/roachtest/tests/indexes.go
  pkg/cmd/roachtest/tests/inverted_index.go
  pkg/cmd/roachtest/tests/ledger.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_schemachange.go
  pkg/cmd/roachtest/tests/queue.go
  pkg/cmd/roachtest/tests/roachmart.go
  pkg/cmd/roachtest/tests/schemachange_random_load.go
  pkg/cmd/roachtest/tests/tpchbench.go
Labels: backport

#128188 release-24.2: roachtest: add RequiresDeprecatedWorkload testSpec
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/test/test_interface.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/admission_control_tpcc_overload.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/cdc.go
  pkg/cmd/roachtest/tests/connection_latency.go
  pkg/cmd/roachtest/tests/indexes.go
  pkg/cmd/roachtest/tests/inverted_index.go
  pkg/cmd/roachtest/tests/ledger.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_schemachange.go
  pkg/cmd/roachtest/tests/queue.go
  pkg/cmd/roachtest/tests/roachmart.go
  pkg/cmd/roachtest/tests/schemachange_random_load.go
  pkg/cmd/roachtest/tests/tpchbench.go
Labels: backport

#128207 dev: in `doctor`, add `--sandbox_add_mount_pair` if relevant
  dev
  pkg/cmd/dev/doctor.go
Labels: backport-24.1.x, backport-24.2.x

#128211 dev: refactor prompts for autofix permission
  dev
  pkg/cmd/dev/doctor.go
Labels: backport-24.1.x, backport-24.2.x

#128229 dev: in `dev doctor` in remote mode, add the `--jobs` parameter
  pkg/cmd/dev/doctor.go
Labels: backport-24.1.x, backport-24.2.x

#128215 schemachanger: assorted fixes to CREATE INDEX
  pkg/sql/logictest/testdata/logic_test/create_index
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#128116 workload/schemachange: fix constraintIsPrimary name escaping
  pkg/workload/schemachange/error_screening.go
  pkg/workload/schemachange/operation_generator.go
  pkg/workload/schemachange/optype.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#128203 logictestccl: deflake select_for_update_read_committed
  pkg/ccl/logictestccl/testdata/logic_test/select_for_update_read_committed
  pkg/sql/exec_factory_util.go
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/locking.go
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/memo/logical_props_builder.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#128178 release-24.2: jwtauthccl: add mapper for issuer url to jwks URI
  pkg/ccl/jwtauthccl/BUILD.bazel
  pkg/ccl/jwtauthccl/authentication_jwt.go
  pkg/ccl/jwtauthccl/authentication_jwt_test.go
  pkg/ccl/jwtauthccl/settings.go
  pkg/ccl/jwtauthccl/settings_test.go
  pkg/ccl/oidcccl/authentication_oidc_test.go
  pkg/ccl/testccl/authccl/auth_test.go
Labels: backport, branch-release-24.2.0-rc

#128264 crosscluster/logical: add failure cause to DLQ'ed row
  pkg/ccl/crosscluster/logical/dead_letter_queue.go
  pkg/ccl/crosscluster/logical/dead_letter_queue_test.go
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go
  pkg/ccl/crosscluster/logical/purgatory.go
Labels: backport-24.2.x

#128018 release-24.1: changefeedccl: add kafka sink v2
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/alter_changefeed_test.go
  pkg/ccl/changefeedccl/batching_sink.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/encoder_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/ccl/changefeedccl/mocks/BUILD.bazel
  pkg/ccl/changefeedccl/mocks/kafka_admin_v2_generated.go
  pkg/ccl/changefeedccl/mocks/kafka_client_v2_generated.go
  pkg/ccl/changefeedccl/show_changefeed_jobs_test.go
  pkg/ccl/changefeedccl/sink.go
  pkg/ccl/changefeedccl/sink_external_connection.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_kafka_connection_test.go
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_kafka_v2_test.go
  pkg/ccl/changefeedccl/sink_pubsub.go
  pkg/ccl/changefeedccl/sink_pubsub_v2.go
  pkg/ccl/changefeedccl/sink_test.go
  pkg/ccl/changefeedccl/sink_webhook_v2.go
  pkg/ccl/changefeedccl/testfeed_test.go
  pkg/gen/gomock.bzl
  pkg/testutils/sqlutils/sql_runner.go
Labels: backport

#128245 workload/schemachange: enable create index / unique constraint
  pkg/sql/alter_table.go
  pkg/workload/schemachange/error_screening.go
  pkg/workload/schemachange/operation_generator.go
  pkg/workload/schemachange/optype.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#128230 dev: remove unnecessary testing knobs
  pkg/cmd/dev/build.go
  pkg/cmd/dev/datadriven_test.go
  pkg/cmd/dev/dev.go
  pkg/cmd/dev/doctor.go
  pkg/cmd/dev/recorderdriven_test.go
Labels: backport-24.1.x, backport-24.2.x

#128340 sql: allow creating the "vector" extension
  pkg/ccl/logictestccl/testdata/logic_test/vector
  pkg/sql/create_extension.go
Labels: backport-24.2.x

#128236 dev: refactor and augment cache check logic
  dev
  pkg/cmd/dev/build.go
  pkg/cmd/dev/dev.go
Labels: backport-24.1.x, backport-24.2.x

#128334 roachtest: fix ycsb regression by giving workload node more cpu
  pkg/cmd/roachtest/tests/ycsb.go
  pkg/workload/cli/run.go
Labels: backport-24.1.x, backport-24.2.x

#127866 cdcevent: prevent misleading log when ErrUnwatchedFamily is encountered
  pkg/ccl/changefeedccl/cdcevent/event.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#127726 crosscluster/logical: avoid error handling race
  pkg/BUILD.bazel
  pkg/ccl/crosscluster/event.go
  pkg/ccl/crosscluster/logical/BUILD.bazel
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go
  pkg/ccl/crosscluster/physical/BUILD.bazel
  pkg/ccl/crosscluster/physical/replication_random_client_test.go
  pkg/ccl/crosscluster/physical/stream_ingestion_job.go
  pkg/ccl/crosscluster/physical/stream_ingestion_processor_test.go
  pkg/ccl/crosscluster/streamclient/BUILD.bazel
  pkg/ccl/crosscluster/streamclient/client.go
  pkg/ccl/crosscluster/streamclient/client_test.go
  pkg/ccl/crosscluster/streamclient/randclient/BUILD.bazel
  pkg/ccl/crosscluster/streamclient/randclient/random_stream_client.go
  pkg/ccl/crosscluster/streamclient/randclient/random_stream_client_test.go
  pkg/ccl/crosscluster/streamclient/random_client.go
  pkg/testutils/soon.go
Labels: backport-24.2.x

#128322 release-24.1: released CockroachDB version 24.1.3. Next version: 24.1.4
  pkg/build/version.txt
Labels: backport

#128354 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#128353 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#128350 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#128110 release-23.1: sql,server: avoid conn routing memory leak with invalid virtual cluster name
  pkg/server/server.go
  pkg/server/server_controller_test.go
  pkg/server/server_sql.go
  pkg/server/tenant.go
  pkg/sql/conn_executor.go
  pkg/sql/pgwire/conn.go
  pkg/sql/pgwire/pre_serve.go
  pkg/sql/pgwire/server.go
  pkg/util/mon/bytes_usage.go
Labels: backport

#128120 release-24.1: roachtest/mixedversion: add support for shared-process deployments
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/context.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/basic_test_mixed_version_hooks
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/cluster_setting
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/conflicting_mutators
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/local_runs_reduced_wait_time
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/minimum_supported_version
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/multiple_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/mutator_probabilities
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/preserve_downgrade_option_randomizer
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/shared_process
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/skip_version_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/step_stages
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/test_releases.yaml
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_cdc.go
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
  pkg/cmd/roachtest/tests/mixed_version_import.go
  pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go
  pkg/cmd/roachtest/tests/rebalance_load.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go
  pkg/cmd/roachtest/tests/versionupgrade.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/expander.go
  pkg/testutils/release/releases.go
Labels: backport

#124365 release-23.2: cli/doctor, doctor: use right jobs table, skip dropped descs
  pkg/cli/BUILD.bazel
  pkg/cli/decode.go
  pkg/cli/doctor.go
  pkg/cli/doctor_test.go
  pkg/cli/testdata/doctor/debugzip-json/crdb_internal.system_jobs.json
  pkg/cli/testdata/doctor/debugzip-with-quotes/crdb_internal.system_jobs.txt
  pkg/cli/testdata/doctor/debugzip-with-quotes/system.descriptor.txt
  pkg/cli/testdata/doctor/debugzip/crdb_internal.system_jobs.txt
  pkg/cli/testdata/doctor/debugzip/system.descriptor.txt
  pkg/cli/testdata/doctor/debugzip/system.jobs.txt
  pkg/cli/testdata/doctor/debugzip/system.namespace.txt
  pkg/cli/testdata/doctor/test_examine_cluster_dropped
  pkg/cli/testdata/doctor/test_examine_cluster_jobs
  pkg/cli/testdata/doctor/test_examine_zipdir
  pkg/cli/testdata/doctor/test_examine_zipdir_verbose
  pkg/cli/testdata/doctor/test_examine_zipdir_with_quotes
  pkg/cli/testdata/doctor/test_recreate_zipdir
  pkg/cli/testutils.go
  pkg/sql/doctor/doctor.go
  pkg/sql/doctor/doctor_test.go
Labels: backport

#128048 release-23.2: changefeedccl: add kafka sink v2
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  build/bazelutil/nogo_config.json
  go.mod
  go.sum
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/alter_changefeed_test.go
  pkg/ccl/changefeedccl/batching_sink.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/encoder_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/ccl/changefeedccl/mocks/BUILD.bazel
  pkg/ccl/changefeedccl/mocks/kafka_admin_v2_generated.go
  pkg/ccl/changefeedccl/mocks/kafka_client_v2_generated.go
  pkg/ccl/changefeedccl/show_changefeed_jobs_test.go
  pkg/ccl/changefeedccl/sink.go
  pkg/ccl/changefeedccl/sink_external_connection.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_kafka_connection_test.go
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_kafka_v2_test.go
  pkg/ccl/changefeedccl/sink_pubsub.go
  pkg/ccl/changefeedccl/sink_pubsub_v2.go
  pkg/ccl/changefeedccl/sink_test.go
  pkg/ccl/changefeedccl/sink_webhook_v2.go
  pkg/ccl/changefeedccl/testfeed_test.go
  pkg/gen/gomock.bzl
  pkg/testutils/sqlutils/sql_runner.go
Labels: backport

#128468 release-23.1: sql: block set default on computed col
  pkg/sql/alter_table.go
  pkg/sql/catalog/tabledesc/validate.go
  pkg/sql/logictest/testdata/logic_test/computed
Labels: backport

#128467 release-23.2: sql: block set default on computed col
  pkg/sql/alter_table.go
  pkg/sql/catalog/tabledesc/validate.go
  pkg/sql/logictest/testdata/logic_test/computed
Labels: backport

#128396 memo: redact constants in EXPLAIN (OPT, REDACT) of various CREATE stmts
  pkg/ccl/logictestccl/testdata/logic_test/explain_redact
  pkg/sql/opt/exec/execbuilder/testdata/explain_redact
  pkg/sql/opt/memo/expr_format.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#128405 release-23.2: roachtest/mixedversion: add support for shared-process deployments
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/context.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/basic_test_mixed_version_hooks
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/cluster_setting
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/conflicting_mutators
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/local_runs_reduced_wait_time
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/minimum_supported_version
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/multiple_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/mutator_probabilities
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/preserve_downgrade_option_randomizer
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/shared_process
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/skip_version_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/step_stages
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/test_releases.yaml
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_cdc.go
  pkg/cmd/roachtest/tests/mixed_version_change_replicas.go
  pkg/cmd/roachtest/tests/mixed_version_import.go
  pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go
  pkg/cmd/roachtest/tests/versionupgrade.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/expander.go
  pkg/testutils/release/releases.go
  pkg/testutils/release/releases_test.go
Labels: backport

#128235 release-23.1: cli: add fallback query support for debug zip
  pkg/cli/testdata/zip/testzip_fallback
  pkg/cli/zip.go
  pkg/cli/zip_table_registry.go
  pkg/cli/zip_table_registry_test.go
  pkg/cli/zip_test.go
Labels: backport

#128328 release-23.2: cli: add fallback query support for debug zip
  pkg/cli/testdata/zip/testzip_fallback
  pkg/cli/zip.go
  pkg/cli/zip_table_registry.go
  pkg/cli/zip_table_registry_test.go
  pkg/cli/zip_test.go
Labels: backport

#128481 release-24.2: released CRDB 24.2.0-rc.1. Next version 24.2.0
  pkg/build/info.go
  pkg/build/version.txt
Labels: backport

#128496 scbuild: handle names with special characters in hash-sharded constraint
  pkg/sql/logictest/testdata/logic_test/alter_primary_key
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
  pkg/sql/schemachanger/scbuild/testdata/create_index
  pkg/sql/schemachanger/scbuild/testdata/drop_index
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_primary_key_using_hash/alter_table_alter_primary_key_using_hash.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_primary_key_using_hash/alter_table_alter_primary_key_using_hash.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/drop_index_hash_sharded_index/drop_index_hash_sharded_index.side_effects
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#128518 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#128519 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#128520 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#128516 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#126412 release-24.1: opt: check privileges after object resolution for staleness checks
  pkg/sql/logictest/testdata/logic_test/schema
  pkg/sql/opt/metadata.go
Labels: backport

#126413 release-23.2: opt: check privileges after object resolution for staleness checks
  pkg/sql/logictest/testdata/logic_test/schema
  pkg/sql/opt/metadata.go
Labels: backport

#125203 backupccl: reduce cost of TestBackupRestoreAppend
  pkg/ccl/backupccl/backup_test.go
Labels: backport-24.1.x, backport-24.2.x

#128417 release-24.2: changefeedccl: don't fetch all kafka topics on connection check in the v2 sink
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_kafka_v2_test.go
  pkg/cmd/roachtest/tests/cdc.go
Labels: backport

#128419 release-24.1: changefeedccl: don't fetch all kafka topics on connection check in the v2 sink
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_kafka_v2_test.go
  pkg/cmd/roachtest/tests/cdc.go
Labels: backport

#128460 release-23.2: changefeedccl: don't fetch all kafka topics on connection check in the v2 sink
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_kafka_v2_test.go
Labels: backport

#128459 release-23.2: changefeedccl: make the kafka v2 and pubsub sinks display topic notices
  pkg/ccl/changefeedccl/batching_sink.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/testfeed_test.go
Labels: backport

#128501 log: deflake TestHTTPSinkTimeout
  pkg/util/log/http_sink_test.go
Labels: backport-24.1.x, backport-24.2.x

#128421 workload/schemachange: fix some alter pk setup
  pkg/workload/schemachange/operation_generator.go
  pkg/workload/schemachange/query_util.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#128586 release-23.1.25-rc: Revert "cli: add fallback query support for debug zip"
  pkg/cli/testdata/zip/testzip_fallback
  pkg/cli/zip.go
  pkg/cli/zip_table_registry.go
  pkg/cli/zip_table_registry_test.go
  pkg/cli/zip_test.go
Labels: backport

#128577 sql: restart rangefeed on descriptor table on error
  pkg/ccl/backupccl/backup_test.go
  pkg/sql/catalog/lease/lease.go
Labels: backport-24.1.x, backport-24.2.x

#128325 release-23.2: workload/schemachange: misc fixes
  pkg/workload/schemachange/BUILD.bazel
  pkg/workload/schemachange/error_screening.go
  pkg/workload/schemachange/operation_generator.go
  pkg/workload/schemachange/optype.go
Labels: backport

#128614 roachtest: revert workload cpu change for all ycsb variants
  pkg/cmd/roachtest/tests/ycsb.go
Labels: backport-24.1.x, backport-24.2.x

#128617 changefeedccl: add timing logs to newRangeDistributionTester
  pkg/ccl/changefeedccl/changefeed_dist_test.go
Labels: backport-24.1.x, backport-24.2.x

#128628 release-24.1: roachtest/acceptance: remove schemachange workload
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: backport

#128630 catalog/lease: fix incorrect version check for expiry based leases
  pkg/sql/catalog/lease/count.go
Labels: backport-24.1.x, backport-24.2.x

#128639 changefeedccl: attempt to deflake distribution strategy unit tests
  pkg/ccl/changefeedccl/changefeed_dist_test.go
Labels: backport-24.1.x, backport-24.2.x

#128634 release-23.2: roachtest/acceptance: remove schemachange workload
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: backport

#128605 release-24.1: log: update crdbV2 log decoder
  pkg/cli/zip_per_node.go
  pkg/server/status.go
  pkg/server/storage_api/logfiles_test.go
  pkg/util/log/format_crdb_v2.go
  pkg/util/log/format_crdb_v2_test.go
  pkg/util/log/testdata/parse
Labels: backport

#128637 release-23.1: roachtest/acceptance: remove schemachange workload
  pkg/cmd/roachtest/tests/versionupgrade.go
Labels: backport

#128676 release-23.2: scbuild: handle names with special characters in hash-sharded constraint
  pkg/sql/logictest/testdata/logic_test/alter_primary_key
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
  pkg/sql/schemachanger/scbuild/testdata/create_index
  pkg/sql/schemachanger/scbuild/testdata/drop_index
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_primary_key_using_hash/alter_table_alter_primary_key_using_hash.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_primary_key_using_hash/alter_table_alter_primary_key_using_hash.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/drop_index_hash_sharded_index/drop_index_hash_sharded_index.side_effects
Labels: backport

#128646 release-24.2: add provisioned_vcpus setting and metric
  docs/generated/metrics/metrics.html
  pkg/ccl/logictestccl/testdata/logic_test/tenant_usage
  pkg/ccl/multitenantccl/tenantcostclient/metrics.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side.go
  pkg/ccl/multitenantccl/tenantcostclient/tenant_side_test.go
  pkg/ccl/multitenantccl/tenantcostclient/testdata/consumption
  pkg/ccl/multitenantccl/tenantcostclient/testdata/estimated-cpu
  pkg/cmd/roachtest/tests/admission_control_multitenant_fairness.go
  pkg/sql/logictest/testdata/logic_test/tenant_builtins
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
Labels: backport

#128361 release-23.2: backupccl: distribute restore validation work
  pkg/ccl/backupccl/generative_split_and_scatter_processor.go
  pkg/ccl/backupccl/generative_split_and_scatter_processor_test.go
  pkg/ccl/backupccl/restore_processor_planning.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
Labels: backport

#128398 release-23.1: backupccl: distribute restore validation work
  pkg/ccl/backupccl/generative_split_and_scatter_processor.go
  pkg/ccl/backupccl/generative_split_and_scatter_processor_test.go
  pkg/ccl/backupccl/restore_processor_planning.go
  pkg/ccl/backupccl/split_and_scatter_processor.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
Labels: backport

#128434 catalog/lease: fix TestLeaseDescriptorRangeFeedFailure test
  pkg/sql/catalog/lease/BUILD.bazel
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/catalog/lease/testutils.go
Labels: backport-24.1.x, backport-24.2.x

#128645 kvserver: avoid redacting lease acquisition type when logging
  pkg/roachpb/data.go
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#128687 pgwire,eventpb: add structured logging for connection breakage during shutdown
  docs/generated/eventlog.md
  pkg/sql/pgwire/server.go
  pkg/util/log/eventpb/cluster_events.proto
  pkg/util/log/eventpb/eventlog_channels_generated.go
  pkg/util/log/eventpb/json_encode_generated.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#128698 retry: trace on retry backoff
  pkg/util/retry/BUILD.bazel
  pkg/util/retry/retry.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#128631 release-23.2: kvserver,status: change monotonic counter metrics to Counters
  docs/generated/metrics/metrics.html
  pkg/ccl/sqlproxyccl/acl/file_test.go
  pkg/gossip/simulation/network.go
  pkg/kv/kvserver/client_metrics_test.go
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/store.go
  pkg/server/status/runtime.go
  pkg/testutils/lint/lint_test.go
  pkg/util/metric/BUILD.bazel
  pkg/util/metric/aggmetric/counter.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_test.go
  pkg/util/syncutil/atomic.go
  pkg/util/syncutil/atomic_test.go
Labels: backport

#128708 kv: propose lease acquisition if raft leader is unknown, by default
  pkg/cmd/roachtest/tests/admission_control_latency.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/kv/kvserver/leases/build_test.go
  pkg/kv/kvserver/leases/verify.go
  pkg/kv/kvserver/leases/verify_test.go
  pkg/kv/kvserver/replica_range_lease.go
Labels: backport-24.2.x

#128670 kvserver: deflake TestGossipHandlesReplacedNode
  pkg/kv/kvserver/gossip_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#127258 roachtest: include Side-Eye link in GitHub posts
  pkg/cmd/bazci/githubpost/issues/formatter_unit.go
  pkg/cmd/bazci/githubpost/issues/issues.go
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/testdata/help_command_createpost_16.txt
Labels: O-community

#128669 release-23.1: jwtauthccl: add mapper for issuer url to jwks URI
  pkg/ccl/jwtauthccl/BUILD.bazel
  pkg/ccl/jwtauthccl/authentication_jwt.go
  pkg/ccl/jwtauthccl/authentication_jwt_test.go
  pkg/ccl/jwtauthccl/settings.go
  pkg/ccl/jwtauthccl/settings_test.go
  pkg/ccl/testccl/authccl/auth_test.go
Labels: backport

#128675 sql: SHOW CLUSTER SETTING FOR TENANT returns NULL for renamed cluster setting
  pkg/sql/logictest/testdata/logic_test/cluster_settings
  pkg/sql/tenant_settings.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#128534 backupccl: deflake TestOnlineRestoreBasic
  pkg/ccl/backupccl/restore_online_test.go
Labels: backport-24.1.x, backport-24.2.x

#128804 release-23.2: roachtest: update mixed-version follower read tests for shared-process
  pkg/cmd/roachtest/roachtestutil/httpclient.go
  pkg/cmd/roachtest/tests/follower_reads.go
Labels: backport

#128827 release-23.1: build system: use proxied docker mirror
  build/bazelbuilder/Dockerfile
  build/deploy/Dockerfile
  build/teamcity/internal/cockroach/build/ci/nightly-bazel-builder-update-check.sh
  build/teamcity/internal/release/build-and-publish-patched-go.sh
  build/toolchains/toolchainbuild/crosstool-ng/buildtoolchains.sh
  build/toolchains/toolchainbuild/osxcross/buildtoolchains.sh
  pkg/acceptance/cluster/dockercluster.go
  pkg/acceptance/compose/flyway/docker-compose.yml
  pkg/acceptance/compose/gss/docker-compose-python.yml
  pkg/acceptance/compose/gss/docker-compose.yml
  pkg/compose/compare/docker-compose.yml
Labels: backport

#128713 sqlstats: add close chan to buffer ingester
  pkg/sql/sqlstats/insights/BUILD.bazel
  pkg/sql/sqlstats/insights/ingester.go
  pkg/sql/sqlstats/insights/ingester_test.go
Labels: backport-24.2.x

#128812 dbconsole: fix legend for elastic CPU queue delay graph
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx
Labels: backport-24.2.x

#128700 release-24.2: changefeedccl: enable the new Kafka v2 sink by default
  pkg/ccl/changefeedccl/sink.go
Labels: backport

#128846 roachtest: remove `autoupgrade` test
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/autoupgrade.go
  pkg/cmd/roachtest/tests/registry.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#128874 kvserver: log status when lease requested
  pkg/kv/kvserver/replica_range_lease.go
Labels: backport-24.1.x, backport-24.2.x

#128905 release-23.2: roachtest: remove `autoupgrade` test
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/autoupgrade.go
  pkg/cmd/roachtest/tests/registry.go
Labels: backport

#126150 rpc: add locality to dialing
  docs/generated/metrics/metrics.html
  pkg/acceptance/localcluster/cluster.go
  pkg/blobs/client_test.go
  pkg/ccl/serverccl/statusccl/tenant_grpc_test.go
  pkg/gossip/client.go
  pkg/gossip/client_test.go
  pkg/gossip/gossip.go
  pkg/gossip/gossip_test.go
  pkg/kv/kvclient/kvcoord/send_test.go
  pkg/kv/kvclient/kvtenant/connector.go
  pkg/kv/kvserver/loqrecovery/server.go
  pkg/kv/kvserver/raft_transport.go
  pkg/kv/kvserver/raft_transport_unit_test.go
  pkg/rpc/BUILD.bazel
  pkg/rpc/client.go
  pkg/rpc/context.go
  pkg/rpc/context_test.go
  pkg/rpc/datadriven_test.go
  pkg/rpc/down_node_test.go
  pkg/rpc/metrics.go
  pkg/rpc/metrics_test.go
  pkg/rpc/mocks_generated_test.go
  pkg/rpc/nodedialer/nodedialer.go
  pkg/rpc/nodedialer/nodedialer_test.go
  pkg/rpc/peer.go
  pkg/server/connectivity_test.go
  pkg/server/fanout_clients.go
  pkg/server/node_http_router.go
  pkg/server/server.go
  pkg/server/server_sql.go
  pkg/server/status.go
  pkg/server/tenant.go
  pkg/server/testserver.go
  pkg/sql/crdb_internal.go
  pkg/sql/distsql/inbound_test.go
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/flowinfra/cluster_test.go
  pkg/sql/flowinfra/outbox_test.go
  pkg/sql/flowinfra/utils_test.go
  pkg/testutils/testcluster/testcluster.go
Labels: backport-24.2.x

#128966 kvserver: skip rebalance multi-store under deadlock
  pkg/kv/kvserver/replicate_queue_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#127997 kvserver: split snapshot SSTables for mvcc keys into multiple SSTs
  pkg/kv/kvserver/BUILD.bazel
  pkg/kv/kvserver/replica_sst_snapshot_storage_test.go
  pkg/kv/kvserver/store_snapshot.go
  pkg/storage/engine_key.go
  pkg/storage/sst_writer.go
Labels: backport-24.1.x, backport-24.2.x

#128579 crosscluster/logical: deflake TestRandomTable
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/logical/udf_row_processor_test.go
Labels: backport-24.2.x

#128926 restore: only run proc lag checker on fully updgraded 24.3 clusters
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/restore_data_processor.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_processor_planning.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
Labels: T-disaster-recovery

#129008 release-23.1: opt: wrap virtual computed column projections in a cast
  pkg/sql/logictest/testdata/logic_test/cast
  pkg/sql/logictest/testdata/logic_test/virtual_columns
  pkg/sql/opt/exec/execbuilder/testdata/explain_redact
  pkg/sql/opt/memo/testdata/stats/scan
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/testdata/update
  pkg/sql/opt/optbuilder/testdata/update-col-cast-bug
  pkg/sql/opt/optbuilder/testdata/upsert
  pkg/sql/opt/optbuilder/testdata/virtual-columns
  pkg/sql/types/types.go
  pkg/sql/types/types_test.go
Labels: backport

#128983 log: remove STRUCTURED_EVENT logging channel
  docs/generated/logging.md
  pkg/cli/testdata/logflags
  pkg/obs/eventagg/flush_consumer_test.go
  pkg/util/log/channel/channel_generated.go
  pkg/util/log/eventpb/eventpbgen/log_channels_generated.go
  pkg/util/log/log_channels_generated.go
  pkg/util/log/logconfig/testdata/export
  pkg/util/log/logconfig/testdata/validate
  pkg/util/log/logconfig/testdata/yaml
  pkg/util/log/logpb/log.proto
  pkg/util/log/structured_v2.go
  pkg/util/log/testdata/config
Labels: backport-24.2.x

#129006 release-23.2: roachtest: backup-restore/mixed-version support for shared-process
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go
Labels: backport

#128867 release-24.1: ui: add hovering focus behavior to metric graphs
  pkg/ui/workspaces/db-console/src/redux/nodes.spec.ts
  pkg/ui/workspaces/db-console/src/redux/nodes.ts
  pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx
  pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/linegraph.spec.tsx
  pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/linegraph.styl
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx
  pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts
  pkg/ui/workspaces/db-console/src/views/sessions/sessionDetails.tsx
Labels: backport

#128304 release-24.2.0-rc: roachtest: add RequiresDeprecatedWorkload testSpec
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/test/test_interface.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/admission_control_tpcc_overload.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/cdc.go
  pkg/cmd/roachtest/tests/connection_latency.go
  pkg/cmd/roachtest/tests/indexes.go
  pkg/cmd/roachtest/tests/inverted_index.go
  pkg/cmd/roachtest/tests/ledger.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_schemachange.go
  pkg/cmd/roachtest/tests/queue.go
  pkg/cmd/roachtest/tests/roachmart.go
  pkg/cmd/roachtest/tests/schemachange_random_load.go
  pkg/cmd/roachtest/tests/tpchbench.go
Labels: backport

#128864 release-23.2: ui: add hovering focus behavior to metric graphs
  pkg/ui/workspaces/db-console/src/redux/nodes.spec.ts
  pkg/ui/workspaces/db-console/src/redux/nodes.ts
  pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/index.tsx
  pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/linegraph.spec.tsx
  pkg/ui/workspaces/db-console/src/views/cluster/components/linegraph/linegraph.styl
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx
  pkg/ui/workspaces/db-console/src/views/cluster/util/graphs.ts
  pkg/ui/workspaces/db-console/src/views/sessions/sessionDetails.tsx
Labels: backport

#128838 release-23.2: sql: block concurrent renames with declarative schema changes
  pkg/sql/alter_schema.go
  pkg/sql/database.go
  pkg/sql/schema.go
  pkg/sql/schemachanger/schemachanger_test.go
  pkg/sql/table.go
  pkg/sql/type_change.go
Labels: backport

#129080 opt: fix resolution of CHECK expressions for ENUM expression indexes
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/testdata/select
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#128817 release-24.1: storage: fix cases of unencoded key ranges
  pkg/storage/pebble.go
Labels: backport

#128818 release-23.2: storage: fix cases of unencoded key ranges
  pkg/storage/pebble.go
Labels: backport

#128816 release-24.2: storage: fix cases of unencoded key ranges
  pkg/storage/pebble.go
Labels: backport

#129064 roachtest: allow callers to set skip-version probability
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#128941 release-23.2: workload/schemachanger: add version gates for add column
  pkg/workload/schemachange/operation_generator.go
Labels: backport

#129014 release-23.1: sql/randgen: do not generate expressions of type FLOAT4
  pkg/sql/randgen/type.go
Labels: backport

#129141 release-24.1: bump cluster-ui to 24.1.3
  pkg/ui/workspaces/cluster-ui/package.json
Labels: backport

#129142 release-24.2: bump cluster-ui to 24.2.0
  pkg/ui/workspaces/cluster-ui/package.json
Labels: backport

#129140 release-23.2: bump cluster-ui to 23.2.9
  pkg/ui/workspaces/cluster-ui/package.json
Labels: backport

#129144 release-24.2.0-rc: telemetry: deflake generic query plan test
  pkg/ccl/telemetryccl/testdata/telemetry/generic
Labels: backport

#129124 workload/schemachange: make column default errors more lenient
  pkg/workload/schemachange/operation_generator.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#129153 eval: fix hlc_to_timestamp builtin
  pkg/sql/sem/eval/context.go
  pkg/sql/sem/eval/testdata/eval/builtins
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#128902 sqlliveness: handle AmbiguousResultError gracefully on insert
  pkg/sql/sqlliveness/slinstance/BUILD.bazel
  pkg/sql/sqlliveness/slinstance/slinstance.go
  pkg/sql/sqlliveness/slinstance/slinstance_test.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#129176 release-24.2: workload/schemachange: make column default errors more lenient
  pkg/workload/schemachange/operation_generator.go
Labels: backport

#129177 release-24.1: workload/schemachange: make column default errors more lenient
  pkg/workload/schemachange/operation_generator.go
Labels: backport

#129178 release-23.2: workload/schemachange: make column default errors more lenient
  pkg/workload/schemachange/operation_generator.go
Labels: backport

#129089 roachtest: small improvements in documentation and error reporting
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#129251 workflows: enable CI for GitHub merge queue builds
  .github/workflows/github-actions-essential-ci.yml
Labels: backport-24.1.x, backport-24.2.x

#129252 backupccl: remove not null flag from SQLInstanceID field in SSP spec
  pkg/sql/execinfrapb/processors_bulk_io.proto
Labels: T-disaster-recovery, branch-release-23.1, branch-release-24.1, branch-release-23.2, branch-release-24.2

#129264 kvcoord: log replica order on nearest routing policy
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/replica_slice.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#129179 sql: don't allow VOID parameters for UDFs
  pkg/sql/logictest/testdata/logic_test/udf_params
  pkg/sql/opt/optbuilder/create_function.go
  pkg/workload/schemachange/operation_generator.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#129243 roachtest: upgrade hibernate version under test
  pkg/cmd/roachtest/tests/hibernate.go
Labels: backport-24.2.x

#129283 release-23.1: released CockroachDB version 23.1.25. Next version: 23.1.26
  pkg/build/version.txt
Labels: backport

#129292 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#129291 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#129288 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#129289 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#127896 roachtest: use spot VM for all tests
  pkg/cmd/roachtest/test_runner.go
Labels: backport-24.1.x, backport-24.2.x

#129085 roachtest: multi-region/mixed-version support for shared-process
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/mixed_version_multi_region.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#129280 release-24.1: sql: don't allow VOID parameters for UDFs
  pkg/sql/logictest/testdata/logic_test/udf_params
  pkg/sql/opt/optbuilder/create_function.go
Labels: backport

#129281 release-23.2: sql: don't allow VOID parameters for UDFs
  pkg/sql/logictest/testdata/logic_test/udf_regressions
  pkg/sql/opt/optbuilder/create_function.go
Labels: backport

#129330 release-24.1: roachtest: update rebalance-load mixed-version tests for shared-process
  pkg/cmd/roachtest/tests/admission_control_tpcc_overload.go
  pkg/cmd/roachtest/tests/disk_stall.go
  pkg/cmd/roachtest/tests/rebalance_load.go
  pkg/cmd/roachtest/tests/ts_util.go
Labels: backport

#129335 changefeedccl: add more logging around core changefeed completion
  pkg/ccl/changefeedccl/changefeed_stmt.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#129149 ui: remove unnecessary metric name prefixes
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/overload.tsx
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#129368 kvclient: improve logging in OptimizeReplicaOrder
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvclient/kvcoord/replica_slice.go
  pkg/kv/kvclient/kvcoord/replica_slice_test.go
  pkg/sql/physicalplan/replicaoracle/oracle.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x
