Repository cockroachdb/cockroach, pull requests merged in 2024-07, with the labels that each got.

#126399 kvclient/rangefeed: add WithEmitMatchingOriginIDs rangefeed client option
  pkg/kv/kvclient/kvcoord/dist_sender_mux_rangefeed.go
  pkg/kv/kvclient/kvcoord/dist_sender_rangefeed.go
  pkg/kv/kvclient/rangefeed/config.go
  pkg/kv/kvclient/rangefeed/rangefeed.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvserver/replica_rangefeed.go
  pkg/kv/kvserver/replica_rangefeed_test.go
Labels: T-kv

#126330 kvserver: add sstable compression algorithm metrics
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
Labels: backport-24.1.x

#125502 acceptance: put CRDB logs in `outputs.zip` instead of `artifacts`
  .github/workflows/github-actions-essential-ci.yml
  build/github/acceptance-test.sh
  pkg/acceptance/cluster/docker.go
  pkg/acceptance/util_cluster.go
Labels: backport-24.1.x

#126404 crosscluster/logical: prevent data looping via OriginID session variable
  pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go
  pkg/ccl/crosscluster/logical/lww_row_processor.go
  pkg/ccl/crosscluster/producer/event_stream.go
Labels: T-disaster-recovery

#126267 release-24.1: roachtest/test-selector: run selective tests
  build/teamcity/cockroach/coverage/roachtest_nightly_gce.sh
  build/teamcity/cockroach/coverage/roachtest_nightly_gce_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_azure.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  pkg/BUILD.bazel
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/roachtestflags/flags.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/testselector/BUILD.bazel
  pkg/cmd/roachtest/testselector/selector.go
  pkg/cmd/roachtest/testselector/snowflake_query.sql
Labels: backport-24.1.x

#126322 release-23.2: roachtest: remove settings related to handling 22.2
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/mixed_version_cdc.go
  pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go
Labels: backport

#126417 kvnemesis: skip validation for rolled-back locking reads in weak-isolation transactions
  pkg/kv/kvnemesis/validator.go
Labels: backport-23.2.x, backport-24.1.x

#126527 streamingccl: avoid disk full errors in c2c/import/7tb/kv0
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: T-disaster-recovery

#126421 release-23.2: sql: fix nil pointer caused by "".crdb_internal.create_statements
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/pg_catalog.go
Labels: backport

#126422 release-23.1: sql: fix nil pointer caused by "".crdb_internal.create_statements
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/pg_catalog.go
Labels: backport

#126420 release-24.1: sql: fix nil pointer caused by "".crdb_internal.create_statements
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/pg_catalog.go
Labels: backport

#126569 release-24.1: kvserver: add sstable compression algorithm metrics
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
Labels: backport

#126571 gossip: use atomic value for ready channel
  pkg/gossip/server.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#126555 sql: DROP REGION can fail if inaccessible columns exist on tables
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/sql/type_change.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#126674 sql: create_as logic test can fail when txn retries happen
  pkg/sql/logictest/testdata/logic_test/create_as
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#126591 storage: add trace statement for lock table scans
  pkg/storage/engine.go
Labels: backport-23.2.x, backport-24.1.x

#126484 sql/telemetry: include TCL statements in sampling
  pkg/sql/exec_log.go
  pkg/sql/telemetry_datadriven_test.go
  pkg/sql/testdata/telemetry_logging/logging/force_logging
Labels: backport-23.2.x, backport-24.1.x

#126724 release-24.1: set roachprod vm LoginGraceTime to 0
  pkg/roachprod/vm/aws/support.go
  pkg/roachprod/vm/azure/utils.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport

#126701 roachtest: add `MaxUpgrades` option back to `validate-system-schema`
  pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go
Labels: backport-23.2.x, backport-24.1.x

#126725 release-23.2: set roachprod vm LoginGraceTime to 0
  pkg/roachprod/vm/aws/support.go
  pkg/roachprod/vm/azure/utils.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport

#126726 release-23.1: set roachprod vm LoginGraceTime to 0
  pkg/roachprod/vm/aws/support.go
  pkg/roachprod/vm/azure/utils.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport

#126639 ui: fix expand row icons on Nodes Overview page
  pkg/ui/workspaces/cluster-ui/src/table/table.module.scss
  pkg/ui/workspaces/cluster-ui/src/table/table.tsx
Labels: O-community

#126325 release-24.1: streamingccl: keep up with bulk ops
  pkg/ccl/streamingccl/settings.go
  pkg/ccl/streamingccl/streamingest/node_lag_detector.go
  pkg/ccl/streamingccl/streamingest/node_lag_detector_test.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_frontier_processor.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/jobs/jobspb/jobs.go
Labels: T-disaster-recovery, backport

#126778 roachtest: use `CompatibleClouds` to define clouds where a test can run
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/cancel.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/copy.go
  pkg/cmd/roachtest/tests/import.go
  pkg/cmd/roachtest/tests/import_cancellation.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_decl_schemachange_compat.go
  pkg/cmd/roachtest/tests/multitenant_tpch.go
  pkg/cmd/roachtest/tests/schemachange.go
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/cmd/roachtest/tests/tpc_utils.go
  pkg/cmd/roachtest/tests/tpcdsvec.go
  pkg/cmd/roachtest/tests/tpch_concurrency.go
  pkg/cmd/roachtest/tests/tpchbench.go
  pkg/cmd/roachtest/tests/tpchvec.go
Labels: backport-23.2.x, backport-24.1.x

#126690 cli: bump default worker pool to heavy
  pkg/cli/BUILD.bazel
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#126793 cli: add --certs-dir, --user to encode-uri, fix dupe scheme printing
  pkg/cli/cert.go
Labels: backport-24.1.x

#126698 release-24.1: timeutil: don't redact operation name in TimeoutError
  pkg/ccl/backupccl/backup_processor.go
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/ccl/changefeedccl/testfeed_test.go
  pkg/cli/zip.go
  pkg/cli/zip_cluster_wide.go
  pkg/cli/zip_helpers.go
  pkg/cli/zip_per_node.go
  pkg/cloud/httpsink/BUILD.bazel
  pkg/cloud/httpsink/http_storage.go
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/jobs.go
  pkg/internal/client/requestbatcher/BUILD.bazel
  pkg/internal/client/requestbatcher/batcher.go
  pkg/jobs/job_scheduler.go
  pkg/kv/kvserver/loqrecovery/BUILD.bazel
  pkg/kv/kvserver/loqrecovery/server.go
  pkg/kv/kvserver/queue.go
  pkg/kv/kvserver/store.go
  pkg/server/admin.go
  pkg/server/api_v2_ranges.go
  pkg/server/pagination.go
  pkg/server/status.go
  pkg/sql/fingerprint_span.go
  pkg/sql/sem/builtins/generator_probe_ranges.go
  pkg/sql/show_cluster_setting.go
  pkg/sql/user.go
  pkg/testutils/docker/BUILD.bazel
  pkg/testutils/docker/single_node_docker_test.go
  pkg/util/timeutil/BUILD.bazel
  pkg/util/timeutil/timeout.go
  pkg/util/timeutil/timeout_error.go
Labels: backport

#126699 release-23.2: timeutil: don't redact operation name in TimeoutError
  pkg/ccl/backupccl/backup_processor.go
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/ccl/changefeedccl/testfeed_test.go
  pkg/cli/zip.go
  pkg/cli/zip_cluster_wide.go
  pkg/cli/zip_helpers.go
  pkg/cli/zip_per_node.go
  pkg/cloud/httpsink/BUILD.bazel
  pkg/cloud/httpsink/http_storage.go
  pkg/internal/client/requestbatcher/BUILD.bazel
  pkg/internal/client/requestbatcher/batcher.go
  pkg/jobs/job_scheduler.go
  pkg/kv/kvserver/loqrecovery/BUILD.bazel
  pkg/kv/kvserver/loqrecovery/server.go
  pkg/kv/kvserver/queue.go
  pkg/kv/kvserver/store.go
  pkg/server/admin.go
  pkg/server/api_v2_ranges.go
  pkg/server/pagination.go
  pkg/server/status.go
  pkg/sql/fingerprint_span.go
  pkg/sql/sem/builtins/generator_probe_ranges.go
  pkg/sql/show_cluster_setting.go
  pkg/sql/user.go
  pkg/testutils/docker/BUILD.bazel
  pkg/testutils/docker/single_node_docker_test.go
  pkg/util/timeutil/BUILD.bazel
  pkg/util/timeutil/timeout.go
  pkg/util/timeutil/timeout_error.go
Labels: backport

#126836 release-23.2: roachtestutil: dynamically determine block device to stall
  pkg/cmd/roachtest/tests/disk_stall.go
Labels: backport

#126838 release-23.2: released CockroachDB version 23.2.7. Next version: 23.2.8
  pkg/build/version.txt
Labels: backport

#126759 kv-obs: annotate consistency queue graph with explanation
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/queues.tsx
Labels: O-community

#126600 release-23.1: sql: DROP REGION can fail if inaccessible columns exist on tables
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/sql/type_change.go
Labels: backport

#126844 release-24.1: released CockroachDB version 24.1.2. Next version: 24.1.3
  pkg/build/version.txt
Labels: backport

#126851 release-24.1: sql: has_*_privilege functions should work on the public role
  pkg/sql/logictest/testdata/logic_test/grant_schema
  pkg/sql/sem/builtins/pg_builtins.go
Labels: backport

#126841 release-23.2: Cannot restore backup unknown type kind COMPOSITE
  pkg/ccl/backupccl/testdata/backup-restore/user-defined-types
  pkg/sql/catalog/rewrite/rewrite.go
Labels: backport

#126847 release-23.1: Cannot restore backup unknown type kind COMPOSITE
  pkg/ccl/backupccl/testdata/backup-restore/user-defined-types
  pkg/sql/catalog/rewrite/rewrite.go
Labels: backport

#126852 release-23.2: sql: has_*_privilege functions should work on the public role
  pkg/sql/logictest/testdata/logic_test/grant_schema
  pkg/sql/sem/builtins/pg_builtins.go
Labels: backport

#126853 release-23.1: sql: has_*_privilege functions should work on the public role
  pkg/sql/logictest/testdata/logic_test/grant_schema
  pkg/sql/sem/builtins/pg_builtins.go
Labels: backport

#126594 build: update go to 1.22.5
  .bazelrc
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/bootstrap/bootstrap-debian.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
  go.mod
Labels: C-enhancement, A-build-system, T-dev-inf, backport-24.1.x

#126700 release-23.2: opt: avoid generating trivial constrained scans
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_foreign_key_lookup_join
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/sql/opt/constraint/columns.go
  pkg/sql/opt/constraint/constraint.go
  pkg/sql/opt/constraint/constraint_test.go
  pkg/sql/opt/partialidx/implicator.go
  pkg/sql/opt/xform/select_funcs.go
  pkg/sql/opt/xform/testdata/rules/groupby
  pkg/sql/opt/xform/testdata/rules/insert
  pkg/sql/opt/xform/testdata/rules/join
  pkg/sql/opt/xform/testdata/rules/select
Labels: backport

#126703 release-23.1: opt: avoid generating trivial constrained scans
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_foreign_key_lookup_join
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/sql/opt/constraint/columns.go
  pkg/sql/opt/constraint/constraint.go
  pkg/sql/opt/constraint/constraint_test.go
  pkg/sql/opt/partialidx/implicator.go
  pkg/sql/opt/xform/select_funcs.go
  pkg/sql/opt/xform/testdata/rules/groupby
  pkg/sql/opt/xform/testdata/rules/select
Labels: backport

#125465 sql: improve bundle with plan-gist matching
  pkg/sql/explain_bundle_test.go
  pkg/sql/instrumentation.go
Labels: backport-23.2.x, backport-24.1.x

#126858 kvserver: skip TestGossipHandlesReplacedNode under race
  pkg/kv/kvserver/gossip_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#126869 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#126868 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#126867 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#126849 release-24.1: roachtest: clean up acceptance tests
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/multitenant.go
  pkg/cmd/roachtest/tests/registry.go
Labels: backport

#126864 release-24.1: build: update go to 1.22.5
  .bazelrc
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/bootstrap/bootstrap-debian.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
  go.mod
Labels: backport

#126463 release-23.2: sql: improve handling of contention on non-SQL keys
  pkg/sql/crdb_internal.go
  pkg/sql/crdb_internal_test.go
Labels: backport

#125745 changefeedccl: add support for IAM role-based authentication to Kafka sink
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/options.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_kafka_connection_test.go
Labels: O-community

#126510 streamingccl: skip TestStreamingAutoReplan under deadlock
  pkg/ccl/crosscluster/physical/replication_stream_e2e_test.go
Labels: T-disaster-recovery, backport-23.2.x, backport-24.1.x

#126595 release-23.2: update go to 1.21.12
  .bazelrc
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/bootstrap/bootstrap-debian.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
  pkg/cmd/roachtest/tests/go_helpers.go
Labels: C-enhancement, A-build-system, T-dev-inf, backport

#126602 build: backport Go 1.21.12 to 1.19
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/teamcity/internal/release/build-and-publish-patched-go/c9be6ae.diff
  build/teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
Labels: C-enhancement, A-build-system, T-dev-inf

#126901 colexec: fix IS NOT NULL filter for tuples with NULLs
  pkg/sql/colexec/is_null_ops.eg.go
  pkg/sql/colexec/is_null_ops_tmpl.go
  pkg/sql/logictest/testdata/logic_test/tuple
  pkg/sql/sem/eval/eval_test/BUILD.bazel
  pkg/sql/sem/eval/eval_test/eval_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#126824 storage: make pebbleLogger.Eventf also log
  pkg/storage/BUILD.bazel
  pkg/storage/pebble.go
  pkg/storage/pebble_logger_and_tracer.go
  pkg/storage/pebble_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#126862 release-23.1: sql: add cluster setting for grant option inheritance
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/authorization.go
  pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option
Labels: backport

#126854 ui/dashboard: add DLQ metrics, reorder the charts
  pkg/ccl/crosscluster/logical/purgatory.go
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/logicalDataReplication.tsx
Labels: backport-24.2.x

#126691 release-23.2: sql/schemachanger: copy splits and scatter indexes being backfilled
  pkg/bench/rttanalysis/testdata/benchmark_expectations
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error
  pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/sql/backfill.go
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/index_split_scatter.go
  pkg/sql/logictest/testdata/logic_test/hash_sharded_index
  pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist
  pkg/sql/logictest/testdata/logic_test/ranges
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/multitenant_admin_function_test.go
  pkg/sql/opt/exec/execbuilder/testdata/distsql_inverted_index
  pkg/sql/opt/exec/execbuilder/testdata/distsql_tighten_spans
  pkg/sql/opt/exec/execbuilder/testdata/inverted_filter_json_array_dist
  pkg/sql/opt/exec/execbuilder/testdata/inverted_join_json_array_dist
  pkg/sql/opt/exec/execbuilder/testdata/show_trace
  pkg/sql/truncate.go
  pkg/sql/unsplit_range_test.go
Labels: backport

#126684 release-24.1: sql/schemachanger: copy splits and scatter indexes being backfilled
  pkg/bench/rttanalysis/testdata/benchmark_expectations
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_remote_access_error
  pkg/ccl/logictestccl/testdata/logic_test/partitioning_hash_sharded_index
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/sql/backfill.go
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/index_split_scatter.go
  pkg/sql/logictest/testdata/logic_test/hash_sharded_index
  pkg/sql/logictest/testdata/logic_test/inverted_filter_geospatial_dist
  pkg/sql/logictest/testdata/logic_test/ranges
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/multitenant_admin_function_test.go
  pkg/sql/opt/exec/execbuilder/testdata/distsql_inverted_index
  pkg/sql/opt/exec/execbuilder/testdata/distsql_tighten_spans
  pkg/sql/opt/exec/execbuilder/testdata/inverted_filter_json_array_dist
  pkg/sql/opt/exec/execbuilder/testdata/inverted_join_json_array_dist
  pkg/sql/opt/exec/execbuilder/testdata/show_trace
  pkg/sql/truncate.go
  pkg/sql/unsplit_range_test.go
Labels: backport

#126973 crosscluster/logical: a couple optimizations for ingestion
  pkg/ccl/crosscluster/logical/BUILD.bazel
  pkg/ccl/crosscluster/logical/lww_row_processor.go
  pkg/sql/BUILD.bazel
  pkg/sql/internal.go
  pkg/sql/sessiondata/internal.go
Labels: backport-24.2.x

#126951 streamingccl: unskip TestStreamingReplanOnLag
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
Labels: T-disaster-recovery

#127006 kvserver,status: change monotonic counter metrics to Counters
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/server/status/runtime.go
Labels: backport-24.2.x

#125206 sql: statement_timeout should also cancel synchronous rollback
  pkg/sql/conn_executor_exec.go
  pkg/sql/conn_executor_test.go
  pkg/sql/txn_state.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#126976 distsql: Fix flaky TestDistSQLUnavailableHosts.
  pkg/sql/distsql_physical_planner.go
  pkg/sql/distsql_physical_planner_test.go
Labels: backport-24.2.x

#126678 release-24.1: server: inject cluster version when changing system visible settings
  pkg/server/node.go
  pkg/server/settingswatcher/settings_watcher.go
  pkg/server/settingswatcher/settings_watcher_external_test.go
Labels: backport

#127067 sqlliveness: detect and handle invalid SessionIDs
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/sql/catalog/lease/lease_internal_test.go
  pkg/sql/logictest/testdata/logic_test/sqlliveness
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-mixed-23.2/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/schemachanger/comparator_generated_test.go
  pkg/sql/sqlliveness/slstorage/key_encoder.go
  pkg/sql/sqlliveness/slstorage/sessionid.go
  pkg/sql/sqlliveness/slstorage/slstorage.go
Labels: backport-24.1.x

#127050 logical/crosscluster: save checkpoint during initial scan
  pkg/ccl/crosscluster/logical/logical_replication_job.go
Labels: backport-24.2.x

#125869 mixedversion: run skip-version upgrades when supported
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/basic_test_mixed_version_hooks
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/cluster_setting
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/conflicting_mutators
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/local_runs_reduced_wait_time
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/minimum_supported_version
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/multiple_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/mutator_probabilities
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/preserve_downgrade_option_randomizer
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/skip_version_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/step_stages
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go
  pkg/cmd/roachtest/tests/mixed_version_schemachange.go
  pkg/cmd/roachtest/tests/versionupgrade.go
  pkg/testutils/release/releases.go
  pkg/testutils/release/releases_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125814 opt: optimize generic query plans with stable expressions
  pkg/sql/opt/exec/execbuilder/testdata/generic
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/BUILD.bazel
  pkg/sql/opt/xform/generic_funcs.go
  pkg/sql/opt/xform/rules/generic.opt
  pkg/sql/opt/xform/testdata/rules/generic
Labels: backport-24.2.x

#126227 pgwire, ccl: add support for LDAP server authentication
  .github/CODEOWNERS
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/BUILD.bazel
  pkg/ccl/BUILD.bazel
  pkg/ccl/ccl_init.go
  pkg/ccl/ldapccl/BUILD.bazel
  pkg/ccl/ldapccl/authentication_ldap.go
  pkg/ccl/ldapccl/authentication_ldap_test.go
  pkg/ccl/ldapccl/ldap_util.go
  pkg/ccl/ldapccl/main_test.go
  pkg/ccl/ldapccl/settings.go
  pkg/ccl/ldapccl/settings_test.go
  pkg/sql/pgwire/auth_methods.go
  pkg/sql/pgwire/testdata/auth/hba_syntax
Labels: 24.2, 24.3, backport-24.2.x

#124780 roachtest: add support for Side-Eye
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_azure.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh
  pkg/cmd/roachprod/flags.go
  pkg/cmd/roachprod/main.go
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/roachtestflags/flags.go
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/test_runner.go
  pkg/roachprod/roachprod.go
Labels: O-community

#127083 crosscluster/logical: add failed row insert as json object to DLQ
  pkg/ccl/changefeedccl/cdcevent/BUILD.bazel
  pkg/ccl/changefeedccl/cdcevent/event.go
  pkg/ccl/crosscluster/logical/BUILD.bazel
  pkg/ccl/crosscluster/logical/dead_letter_queue.go
  pkg/ccl/crosscluster/logical/dead_letter_queue_test.go
Labels: T-disaster-recovery

#126676 release-23.2: server: inject cluster version when changing system visible settings
  pkg/server/node.go
  pkg/server/settingswatcher/settings_watcher.go
  pkg/server/settingswatcher/settings_watcher_external_test.go
Labels: backport

#127122 multiregionccl: split up TestRegionAddDropWithConcurrentBackupOps and TestMultiRegionDataDriven
  pkg/ccl/multiregionccl/datadriven_test.go
  pkg/ccl/multiregionccl/region_test.go
Labels: backport-24.1.x, backport-24.2.x

#127009 crosscluster/logical: add heuristic for choosing implicit vs explicit
  pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go
  pkg/ccl/crosscluster/logical/lww_row_processor.go
  pkg/ccl/crosscluster/logical/lww_row_processor_test.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
Labels: backport-24.2.x

#127128 release-23.1: storage: make pebbleLogger.Eventf also log
  pkg/storage/BUILD.bazel
  pkg/storage/pebble.go
  pkg/storage/pebble_logger_and_tracer.go
  pkg/storage/pebble_test.go
  pkg/storage/pebbleiter/crdb_test_on.go
Labels: backport

#127129 release-23.1: go.mod: bump Pebble to 4e1e7382051
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#126941 release-24.2: clusterversion: set devBranch to false, version to beta.1
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/build/version.txt
  pkg/cli/testdata/declarative-rules/deprules
  pkg/cli/testdata/declarative-rules/invalid_version
  pkg/clusterversion/cockroach_versions.go
  pkg/sql/catalog/bootstrap/testdata/testdata
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_system
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_tenant
  pkg/sql/logictest/testdata/logic_test/composite_types
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
Labels: backport

#127092 release-24.1: ui: fix query fetching store ids for db/tables
  pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/sqlApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts
  pkg/ui/workspaces/db-console/src/util/api.spec.ts
  pkg/ui/workspaces/db-console/src/util/fakeApi.ts
Labels: backport

#127167 release-23.2: mixedversion: run skip-version upgrades when supported
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/basic_test_mixed_version_hooks
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/cluster_setting
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/conflicting_mutators
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/local_runs_reduced_wait_time
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/minimum_supported_version
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/multiple_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/mutator_probabilities
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/preserve_downgrade_option_randomizer
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/skip_version_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/step_stages
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go
  pkg/cmd/roachtest/tests/mixed_version_schemachange.go
  pkg/cmd/roachtest/tests/versionupgrade.go
  pkg/testutils/release/releases.go
  pkg/testutils/release/releases_test.go
Labels: backport

#127161 release-24.2: mixedversion: run skip-version upgrades when supported
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/basic_test_mixed_version_hooks
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/cluster_setting
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/conflicting_mutators
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/local_runs_reduced_wait_time
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/minimum_supported_version
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/multiple_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/mutator_probabilities
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/preserve_downgrade_option_randomizer
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/skip_version_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/step_stages
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go
  pkg/cmd/roachtest/tests/mixed_version_schemachange.go
  pkg/cmd/roachtest/tests/versionupgrade.go
  pkg/testutils/release/releases.go
  pkg/testutils/release/releases_test.go
Labels: backport

#126942 release-23.1: colexec: fix IS NOT NULL filter for tuples with NULLs
  pkg/sql/colexec/is_null_ops.eg.go
  pkg/sql/colexec/is_null_ops_tmpl.go
  pkg/sql/logictest/testdata/logic_test/tuple
  pkg/sql/sem/eval/eval_test/BUILD.bazel
  pkg/sql/sem/eval/eval_test/eval_test.go
Labels: backport

#126753 workload/schemachange: fix unique constraint validation on inserts
  pkg/workload/schemachange/error_screening.go
Labels: backport-24.1.x, backport-24.2.x

#127195 schematelemetry: don't redact object ID or validation error in logs
  pkg/sql/catalog/schematelemetry/BUILD.bazel
  pkg/sql/catalog/schematelemetry/schema_telemetry_job.go
  pkg/sql/catalog/schematelemetry/schema_telemetry_test.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#126998 crosscluster/logical: allow replication between different table names
  pkg/ccl/crosscluster/logical/lww_row_processor.go
  pkg/ccl/crosscluster/logical/lww_row_processor_test.go
Labels: backport-24.2.x

#127138 release-23.2: go.mod: bump Pebble to 599ddd8c29b
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#127130 release-24.1: go.mod: bump Pebble to 96fb031d2065
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#127127 release-23.2: storage: make pebbleLogger.Eventf also log
  pkg/storage/BUILD.bazel
  pkg/storage/pebble.go
  pkg/storage/pebble_logger_and_tracer.go
  pkg/storage/pebble_test.go
  pkg/storage/pebbleiter/crdb_test_on.go
Labels: backport

#125456 changefeedccl: add CompressionLevel option to kafka_sink_config
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_test.go
Labels: O-community, X-blathers-triaged

#126090 roachtest/ldr: run workload on both nodes
  pkg/cmd/roachtest/tests/logical_data_replication.go
Labels: backport-24.2.x

#127003 sql: skip TestShowFingerprintsDuringSchemaChange under deadlock
  pkg/sql/show_fingerprints_test.go
Labels: backport-24.2.x

#127090 release-23.1: ui: fix query fetching store ids for db/tables
  pkg/ui/workspaces/cluster-ui/src/api/databaseDetailsApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/sqlApi.ts
  pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts
  pkg/ui/workspaces/db-console/src/util/api.spec.ts
  pkg/ui/workspaces/db-console/src/util/fakeApi.ts
Labels: backport

#126200 release-23.1: sql: CREATE TABLE can fail on txn retries
  pkg/sql/alter_table.go
  pkg/sql/create_table.go
  pkg/sql/logictest/testdata/logic_test/create_table
Labels: backport

#126201 release-23.2: sql: CREATE TABLE can fail on txn retries
  pkg/sql/alter_table.go
  pkg/sql/create_table.go
  pkg/sql/logictest/testdata/logic_test/create_table
Labels: backport

#127181 sql: fix out-of-bounds exception in insert fast path
  pkg/sql/logictest/testdata/logic_test/unique
  pkg/sql/opt/exec/execbuilder/mutation.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#127005 release-23.1: sql: add cluster setting to determine if owner has implicit GRANT OPTION
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/authorization.go
  pkg/sql/catalog/catpb/privilege.go
  pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option
Labels: backport

#127307 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#127308 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#127275 release-23.2: roachtest: skip clearrange/zfs/checks=true
  pkg/cmd/roachtest/tests/clearrange.go
Labels: backport

#127245 sql: alter type drop value can crash formatting out dependent rows
  pkg/sql/logictest/testdata/logic_test/alter_type
  pkg/sql/type_change.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#127162 release-24.2: jwtauthccl: Rename and hide `server.jwt_authentication.issuer_custom_ca`
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/jwtauthccl/settings.go
Labels: backport

#127359 release-24.2: update pebble scripts and incorporate fix for Sync race
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  build/teamcity/cockroach/nightlies/pebble_nightly_common.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_race.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_two_instance.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_race_common.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_ycsb_race.sh
  go.mod
  go.sum
  scripts/bump-pebble.sh
Labels: backport

#127375 mixedversion: don't find all predecessors if skip version is not available
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x

#127397 cli: reset `securityassets` `Loader` after test completion
  pkg/cli/demo_locality_test.go
  pkg/cli/demo_test.go
  pkg/cli/main_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#127247 sql: cannot drop enum values if referenced in index expressions
  pkg/sql/logictest/testdata/logic_test/alter_type
  pkg/sql/type_change.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#127242 crosscluter/logical: fix source-side table name parsing
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/logical/udf_row_processor_test.go
  pkg/ccl/crosscluster/producer/BUILD.bazel
  pkg/ccl/crosscluster/producer/event_stream.go
  pkg/ccl/crosscluster/producer/replication_manager.go
  pkg/ccl/crosscluster/producer/stream_lifetime.go
  pkg/ccl/crosscluster/settings.go
  pkg/sql/sem/builtins/replication_builtins.go
  pkg/sql/sem/eval/context.go
Labels: backport-24.2.x

#127402 crosscluster/logical: don't log raw spec
  pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go
Labels: backport-24.2.x

#127361 release-24.1: go.mod: bump Pebble to c864fef40a7f
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#127373 release-23.2: go.mod: bump Pebble to 22657d7def44
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#127441 release-24.2: go.mod: bump Pebble to 0cadaffcf9f4
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#127433 release-24.2: crosscluster/logical: allow replication between different table names
  pkg/ccl/crosscluster/logical/lww_row_processor.go
  pkg/ccl/crosscluster/logical/lww_row_processor_test.go
Labels: backport

#127439 release-23.1: sql: alter type drop value can crash formatting out dependent rows
  pkg/sql/logictest/testdata/logic_test/alter_type
  pkg/sql/type_change.go
Labels: backport

#127388 roachtest: update pgjdbc version under test
  pkg/cmd/roachtest/tests/pgjdbc.go
  pkg/cmd/roachtest/tests/pgjdbc_blocklist.go
Labels: backport-24.2.x

#127458 roachtest: bump up logger disk stall timeout for wal failover tests
  pkg/cmd/roachtest/tests/failover.go
Labels: backport-23.2.x

#127445 release-24.2: crosscluster/logical: initial UDF-applier implementation
  pkg/ccl/crosscluster/logical/BUILD.bazel
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go
  pkg/ccl/crosscluster/logical/lww_row_processor.go
  pkg/ccl/crosscluster/logical/lww_row_processor_test.go
  pkg/ccl/crosscluster/logical/udf_row_processor.go
  pkg/ccl/crosscluster/logical/udf_row_processor_test.go
  pkg/kv/kvserver/protectedts/ptstorage/storage_test.go
  pkg/sql/internal.go
  pkg/sql/isql/isql_db.go
  pkg/sql/randgen/schema.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
Labels: backport

#127446 release-23.2: roachtest: skip pgjdbc and hibernate test
  pkg/cmd/roachtest/tests/activerecord.go
  pkg/cmd/roachtest/tests/hibernate.go
  pkg/cmd/roachtest/tests/pgjdbc.go
Labels: backport

#127210 pkg/cli: add --locality-file to server start commands
  pkg/cli/cliflags/flags.go
  pkg/cli/flags.go
  pkg/cli/flags_test.go
  pkg/cli/start.go
  pkg/server/config.go
  pkg/server/tenant.go
  pkg/server/tenant_delayed_id_set_test.go
Labels: backport-24.1.x, backport-24.2.x

#127462 rpc: deflake TestRemoteOffsetUnhealthy
  pkg/rpc/context_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#126230 catalog/lease: monitor rangefeed and recover from failures
  pkg/server/server_sql.go
  pkg/sql/catalog/lease/BUILD.bazel
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/catalog/lease/testutils.go
Labels: backport-24.1.x, backport-24.2.x

#127437 release-23.1: go.mod: bump Pebble to b8a1596b71a3
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#127477 roachtest: bump up warehouse count in disagg-rebalance
  pkg/cmd/roachtest/tests/disagg_rebalance.go
Labels: backport-24.1.x, backport-24.2.x

#127491 release-24.2: released CockroachDB version 24.2.0-beta.1. Next version: 24.2.0-beta.2
  pkg/build/version.txt
Labels: backport

#127492 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#127493 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#127440 release-24.1: go.mod: bump Pebble to 87efd91a58b7
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#127520 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#126679 release-23.2: util/json,builtins: miscellaneous improvements around json objects
  pkg/sql/logictest/testdata/logic_test/json_builtins
  pkg/util/json/json.go
Labels: backport

#127470 crosscluster: consolidate mutation type enum
  pkg/ccl/crosscluster/logical/dead_letter_queue.go
  pkg/ccl/crosscluster/logical/dead_letter_queue_test.go
  pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go
  pkg/ccl/crosscluster/logical/udf_row_processor.go
Labels: backport-24.2.x

#127069 release-23.1: cli: add fallback query support for debug zip
  pkg/cli/testdata/zip/testzip_fallback
  pkg/cli/zip.go
  pkg/cli/zip_table_registry.go
  pkg/cli/zip_table_registry_test.go
  pkg/cli/zip_test.go
Labels: backport

#127068 release-23.2: cli: add fallback query support for debug zip
  pkg/cli/testdata/zip/testzip_fallback
  pkg/cli/zip.go
  pkg/cli/zip_table_registry.go
  pkg/cli/zip_table_registry_test.go
  pkg/cli/zip_test.go
Labels: backport

#126893 release-24.1: cli: add fallback query support for debug zip
  pkg/cli/testdata/zip/testzip_fallback
  pkg/cli/zip.go
  pkg/cli/zip_table_registry.go
  pkg/cli/zip_table_registry_test.go
  pkg/cli/zip_test.go
Labels: backport

#127535 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#127538 release-24.2: crosscluster: consolidate mutation type enum
  pkg/ccl/crosscluster/logical/dead_letter_queue.go
  pkg/ccl/crosscluster/logical/dead_letter_queue_test.go
  pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go
  pkg/ccl/crosscluster/logical/udf_row_processor.go
Labels: T-disaster-recovery, backport

#127540 release-24.2: crosscluster/logical: set UDF function name from SQL input
  pkg/ccl/crosscluster/logical/BUILD.bazel
  pkg/ccl/crosscluster/logical/create_logical_replication_stmt.go
  pkg/ccl/crosscluster/logical/logical_replication_job.go
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go
  pkg/ccl/crosscluster/logical/lww_row_processor.go
  pkg/ccl/crosscluster/logical/lww_row_processor_test.go
  pkg/ccl/crosscluster/logical/udf_row_processor.go
  pkg/ccl/crosscluster/logical/udf_row_processor_test.go
  pkg/jobs/jobspb/jobs.proto
  pkg/sql/execinfrapb/processors_bulk_io.proto
  pkg/sql/parser/parse.go
Labels: backport

#127530 changefeedccl: add log messages for when a core changefeed retries/fails
  pkg/ccl/changefeedccl/changefeed_stmt.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#127622 release-23.1: released CockroachDB version 23.1.24. Next version: 23.1.25
  pkg/build/version.txt
Labels: backport

#127625 release-24.1: roachtest: avoid pooling in DSC job compat test
  pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go
Labels: backport

#127624 release-24.2: roachtest: avoid pooling in DSC job compat test
  pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go
Labels: backport

#127605 sql: fix incorrect context capture for the internal executor
  pkg/sql/internal.go
Labels: backport-24.2.x

#127076 colexec: fix incorrect eager cancellation in parallel unordered sync
  pkg/sql/colexec/parallel_unordered_synchronizer.go
  pkg/sql/colflow/explain_vec.go
  pkg/sql/logictest/testdata/logic_test/union
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#127603 stmtdiagnostics: skip TestDiagnosticsRequest under duress
  pkg/sql/stmtdiagnostics/statement_diagnostics_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.2.x

#127637 release-24.1: roachprod: test selector for aws
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
Labels: backport

#127636 release-24.2: roachprod: test selector for aws
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
Labels: backport

#127549 release-23.1: sql: allow DISCARD in read-only transactions
  pkg/sql/logictest/testdata/logic_test/discard
  pkg/sql/opt/exec/execbuilder/relational.go
Labels: backport

#127653 release-23.2: pgwire: unify serialization error handling
  pkg/sql/pgwire/conn.go
Labels: backport

#127670 sql/sessiondatapb: fix parsing/formatting of sql_sequence_cached_node
  pkg/sql/sessiondatapb/local_only_session_data.go
  pkg/sql/sessiondatapb/session_data_test.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.1.3-rc

#127537 release-23.1: sql/sem/tree, backupccl, *: sanitize URLs during Format
  pkg/ccl/backupccl/alter_backup_schedule.go
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/backuppb/backup.go
  pkg/ccl/backupccl/create_scheduled_backup.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeedpb/marshal.go
  pkg/ccl/changefeedccl/testfeed_test.go
  pkg/ccl/telemetryccl/BUILD.bazel
  pkg/ccl/telemetryccl/telemetry_logging_test.go
  pkg/cloud/externalconn/record.go
  pkg/sql/importer/import_csv_mark_redaction_test.go
  pkg/sql/importer/import_planning.go
  pkg/sql/parser/testdata/alter_backup
  pkg/sql/parser/testdata/alter_changefeed
  pkg/sql/parser/testdata/backup_restore
  pkg/sql/parser/testdata/changefeed
  pkg/sql/parser/testdata/copy
  pkg/sql/parser/testdata/create_external_connection
  pkg/sql/parser/testdata/create_schedule
  pkg/sql/parser/testdata/import_export
  pkg/sql/parser/testdata/prepared_stmts
  pkg/sql/parser/testdata/show
  pkg/sql/sem/tree/alter_backup.go
  pkg/sql/sem/tree/alter_backup_schedule.go
  pkg/sql/sem/tree/alter_changefeed.go
  pkg/sql/sem/tree/backup.go
  pkg/sql/sem/tree/changefeed.go
  pkg/sql/sem/tree/copy.go
  pkg/sql/sem/tree/create.go
  pkg/sql/sem/tree/export.go
  pkg/sql/sem/tree/format.go
  pkg/sql/sem/tree/import.go
  pkg/sql/sem/tree/schedule.go
  pkg/sql/sem/tree/show.go
Labels: backport

#127509 release-23.2: sql/sem/tree, backupccl, *: sanitize URLs during Format
  pkg/ccl/backupccl/alter_backup_schedule.go
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/backuppb/backup.go
  pkg/ccl/backupccl/create_scheduled_backup.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeedpb/marshal.go
  pkg/ccl/changefeedccl/testfeed_test.go
  pkg/ccl/telemetryccl/BUILD.bazel
  pkg/ccl/telemetryccl/telemetry_logging_test.go
  pkg/cloud/externalconn/record.go
  pkg/sql/importer/import_csv_mark_redaction_test.go
  pkg/sql/importer/import_planning.go
  pkg/sql/parser/testdata/alter_backup
  pkg/sql/parser/testdata/alter_changefeed
  pkg/sql/parser/testdata/backup_restore
  pkg/sql/parser/testdata/changefeed
  pkg/sql/parser/testdata/copy
  pkg/sql/parser/testdata/create_external_connection
  pkg/sql/parser/testdata/create_schedule
  pkg/sql/parser/testdata/import_export
  pkg/sql/parser/testdata/prepared_stmts
  pkg/sql/parser/testdata/show
  pkg/sql/plpgsql/parser/testdata/stmt_exec_sql
  pkg/sql/sem/tree/alter_backup.go
  pkg/sql/sem/tree/alter_backup_schedule.go
  pkg/sql/sem/tree/alter_changefeed.go
  pkg/sql/sem/tree/backup.go
  pkg/sql/sem/tree/changefeed.go
  pkg/sql/sem/tree/copy.go
  pkg/sql/sem/tree/create.go
  pkg/sql/sem/tree/export.go
  pkg/sql/sem/tree/format.go
  pkg/sql/sem/tree/import.go
  pkg/sql/sem/tree/schedule.go
  pkg/sql/sem/tree/show.go
Labels: backport

#127506 release-24.1: sql/sem/tree, backupccl, *: sanitize URLs during Format
  pkg/ccl/backupccl/alter_backup_schedule.go
  pkg/ccl/backupccl/backup_planning.go
  pkg/ccl/backupccl/backuppb/backup.go
  pkg/ccl/backupccl/create_scheduled_backup.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeedpb/marshal.go
  pkg/ccl/changefeedccl/testfeed_test.go
  pkg/ccl/telemetryccl/BUILD.bazel
  pkg/ccl/telemetryccl/telemetry_logging_test.go
  pkg/cloud/externalconn/record.go
  pkg/sql/importer/import_csv_mark_redaction_test.go
  pkg/sql/importer/import_planning.go
  pkg/sql/parser/testdata/alter_backup
  pkg/sql/parser/testdata/alter_changefeed
  pkg/sql/parser/testdata/backup_restore
  pkg/sql/parser/testdata/changefeed
  pkg/sql/parser/testdata/copy
  pkg/sql/parser/testdata/create_external_connection
  pkg/sql/parser/testdata/create_schedule
  pkg/sql/parser/testdata/import_export
  pkg/sql/parser/testdata/prepared_stmts
  pkg/sql/parser/testdata/show
  pkg/sql/plpgsql/parser/testdata/stmt_exec_sql
  pkg/sql/sem/tree/alter_backup.go
  pkg/sql/sem/tree/alter_backup_schedule.go
  pkg/sql/sem/tree/alter_changefeed.go
  pkg/sql/sem/tree/backup.go
  pkg/sql/sem/tree/changefeed.go
  pkg/sql/sem/tree/copy.go
  pkg/sql/sem/tree/create.go
  pkg/sql/sem/tree/export.go
  pkg/sql/sem/tree/format.go
  pkg/sql/sem/tree/import.go
  pkg/sql/sem/tree/schedule.go
  pkg/sql/sem/tree/show.go
Labels: backport

#127554 release-23.1: changefeedccl: add log messages for when a core changefeed retries/fails
  pkg/ccl/changefeedccl/changefeed_stmt.go
Labels: backport
