Repository cockroachdb/cockroach, pull requests merged in 2024-06, with the labels that each got.

#124922 roachtest: minor improvements
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_runner.go
  pkg/roachprod/roachprod.go
Labels: O-community, X-blathers-triaged

#124941 spanconfigtestcluster: don't set SkipWaitingForMVCCGC
  pkg/spanconfig/spanconfigtestutils/spanconfigtestcluster/cluster.go
Labels: backport-24.1.x

#124921 roachtest: set link and download phase timeouts
  pkg/cmd/roachtest/tests/online_restore.go
Labels: T-disaster-recovery

#124933 roachtest: skip node distribution check on c2c/BulkOps
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: T-disaster-recovery

#124930 release-23.1: changefeedccl: use new bulk oracle for changefeed planning
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_dist.go
Labels: backport

#124983 streamingccl: unskip TestTenantStreamingReplanOnLag
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
Labels: T-disaster-recovery

#124925 release-23.2: changefeedccl: use new bulk oracle for changefeed planning
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_dist.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport

#124679 dev: move local loopback cache line from `~/.bazelrc` to `.bazelrc.user`
  dev
  pkg/cmd/dev/build.go
  pkg/cmd/dev/cache.go
  pkg/cmd/dev/doctor.go
Labels: backport-24.1.x

#122762 kv: make snapshot apply concurrency limit configurable
  pkg/base/test_server_args.go
  pkg/kv/kvserver/helpers_test.go
  pkg/kv/kvserver/multiqueue/multi_queue.go
  pkg/kv/kvserver/multiqueue/multi_queue_test.go
  pkg/kv/kvserver/replica_learner_test.go
  pkg/kv/kvserver/store.go
  pkg/kv/kvserver/store_snapshot.go
  pkg/kv/kvserver/store_test.go
  pkg/server/config.go
  pkg/server/server.go
  pkg/server/testserver.go
Labels: O-community, X-blathers-triaged, backport-23.1.x, backport-23.2.x, backport-24.1.x

#124789 server: reduce log spam on bad certificate
  pkg/server/server_sql.go
Labels: O-community, X-blathers-triaged

#124932 release-23.2: roachprod: fix update & get latest
  build/teamcity/cockroach/nightlies/roachtest_compile_bits.sh
  build/teamcity/cockroach/nightlies/roachtest_compile_component.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  build/teamcity/util/roachtest_arch_util.sh
  build/teamcity/util/roachtest_util.sh
  pkg/BUILD.bazel
  pkg/cmd/roachprod/BUILD.bazel
  pkg/cmd/roachprod/flags.go
  pkg/cmd/roachprod/main.go
  pkg/cmd/roachprod/update/BUILD.bazel
  pkg/cmd/roachprod/update/update.go
  pkg/cmd/roachprod/update/util.go
  pkg/cmd/roachprod/upgrade/BUILD.bazel
  pkg/cmd/roachprod/upgrade/teamcity.go
  pkg/cmd/roachprod/upgrade/teamcity.proto
  pkg/gen/protobuf.bzl
  scripts/roachprod-get-latest.sh
Labels: backport

#124772 catalog: improve role validation for descriptors.
  pkg/sql/catalog/dbdesc/database_desc_builder.go
  pkg/sql/catalog/dbdesc/database_test.go
  pkg/sql/catalog/funcdesc/func_desc_builder.go
  pkg/sql/catalog/funcdesc/func_desc_test.go
  pkg/sql/catalog/schemadesc/schema_desc_builder.go
  pkg/sql/catalog/schemadesc/schema_desc_test.go
  pkg/sql/catalog/tabledesc/table_desc_builder.go
  pkg/sql/catalog/tabledesc/table_desc_test.go
  pkg/sql/catalog/typedesc/type_desc_builder.go
  pkg/sql/catalog/typedesc/type_desc_test.go
  pkg/sql/catalog/validate.go
  pkg/sql/crdb_internal.go
  pkg/sql/crdb_internal_test.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/sem/builtins/builtins.go
Labels: backport-24.1.x

#124858 admission: add retry logic in TestWorkQueue
  pkg/util/admission/testdata/replicated_write_admission/tenant_fairness
  pkg/util/admission/testdata/replicated_write_admission/tenant_weights
  pkg/util/admission/testdata/work_queue
  pkg/util/admission/work_queue.go
  pkg/util/admission/work_queue_test.go
Labels: backport-24.1.x

#125017 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#125019 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#124288 upgradecluster: retry until cluster stable with unavailable nodes
  pkg/upgrade/upgradecluster/cluster.go
  pkg/upgrade/upgradecluster/helper_test.go
  pkg/upgrade/upgradecluster/nodes.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#124999 storage: calculate total capacity off of max percentage
  pkg/kv/kvserver/kvstorage/cluster_version_test.go
  pkg/kv/kvserver/store_snapshot.go
  pkg/server/config.go
  pkg/server/settings_cache_test.go
  pkg/storage/in_mem.go
  pkg/storage/mvcc_test.go
  pkg/storage/open.go
  pkg/storage/pebble.go
  pkg/storage/sst_test.go
  pkg/testutils/localtestcluster/local_test_cluster.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125012 ci: paginate all available check runs
  pkg/cmd/github-action-poller/main.go
Labels: C-bug, T-dev-inf, A-ci, backport-24.1.x

#125015 ui: add some vertical space on custom graph page
  pkg/ui/workspaces/db-console/src/views/reports/containers/customChart/index.tsx
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125031 release-24.1: opt: don't lose equality FDs when columns are constant
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/sql/opt/memo/testdata/logprops/join
  pkg/sql/opt/props/func_dep.go
Labels: backport

#125032 release-23.2: opt: don't lose equality FDs when columns are constant
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/sql/opt/memo/testdata/logprops/join
  pkg/sql/opt/props/func_dep.go
Labels: backport

#125033 release-23.1: opt: don't lose equality FDs when columns are constant
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/sql/opt/memo/testdata/logprops/join
  pkg/sql/opt/props/func_dep.go
Labels: backport

#125129 kvserver: deflake TestLeaseRenewer
  pkg/kv/kvserver/replica_lease_renewal_test.go
Labels: backport-23.2.x, backport-24.1.x

#124881 docs: update alter backup schedule diagram for execute immediately
  docs/generated/sql/bnf/alter_backup_schedule.bnf
  pkg/cmd/docgen/diagrams.go
Labels: backport-24.1.x

#124981 sql/schemachanger: fix bugs with the STORING() clause of CREATE INDEX.
  pkg/sql/logictest/testdata/logic_test/create_index
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125083 kv: print lease acquisition type in maybeLogLeaseAcquisition
  pkg/kv/kvserver/replica_proposal.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125209 release: remove old script
  build/release/teamcity-publish-redhat-release.sh
Labels: C-enhancement, A-release, T-release

#125218 logictestccl: skip TestTenantLogic_jobs/control_job_priv_inherited
  pkg/sql/logictest/testdata/logic_test/jobs
Labels: T-jobs

#125211 release-23.2: sql/schemachanger: fix bugs with the STORING() clause of CREATE INDEX.
  pkg/sql/logictest/testdata/logic_test/create_index
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
Labels: backport

#125208 release-23.1: sql/schemachanger: fix bugs with the STORING() clause of CREATE INDEX.
  pkg/sql/logictest/testdata/logic_test/create_index
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
Labels: backport

#124854 release-23.2.6-rc: sql/stats: evict stats cache entry if user-defined types have changed
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_stats
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/sql/stats/automatic_stats.go
  pkg/sql/stats/delete_stats_test.go
  pkg/sql/stats/stats_cache.go
  pkg/sql/stats/stats_cache_test.go
Labels: backport

#124979 opt: remove rowNum column from the result of TryDecorrelateLimit
  pkg/sql/opt/norm/rules/decorrelate.opt
  pkg/sql/opt/norm/testdata/rules/decorrelate
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125274 sqlstatsccl: skip TestSQLStatsRegions under duress
  pkg/ccl/testccl/sqlstatsccl/sql_stats_test.go
Labels: backport-24.1.x

#125106 release-23.1: storage: calculate total capacity off of max percentage
  pkg/base/config.go
  pkg/ccl/storageccl/engineccl/encrypted_fs_test.go
  pkg/kv/kvserver/kvstorage/cluster_version_test.go
  pkg/kv/kvserver/store_snapshot.go
  pkg/server/config.go
  pkg/server/settings_cache_test.go
  pkg/server/sticky_vfs.go
  pkg/storage/in_mem.go
  pkg/storage/mvcc_test.go
  pkg/storage/open.go
  pkg/storage/pebble.go
  pkg/storage/sst_test.go
  pkg/testutils/localtestcluster/local_test_cluster.go
Labels: backport

#124856 release-24.1.1-rc: sql/stats: evict stats cache entry if user-defined types have changed
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_stats
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/ccl/multiregionccl/multiregion_system_table_test.go
  pkg/sql/stats/automatic_stats.go
  pkg/sql/stats/delete_stats_test.go
  pkg/sql/stats/stats_cache.go
  pkg/sql/stats/stats_cache_test.go
Labels: backport

#124853 release-23.2: sql/stats: evict stats cache entry if user-defined types have changed
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_stats
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/sql/stats/automatic_stats.go
  pkg/sql/stats/delete_stats_test.go
  pkg/sql/stats/stats_cache.go
  pkg/sql/stats/stats_cache_test.go
Labels: backport

#124855 release-23.1: sql/stats: evict stats cache entry if user-defined types have changed
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_stats
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/sql/stats/automatic_stats.go
  pkg/sql/stats/delete_stats_test.go
  pkg/sql/stats/stats_cache.go
  pkg/sql/stats/stats_cache_test.go
Labels: backport

#125251 streamingccl: add LDR metrics page to db console
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/logicalDataReplication.tsx
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/index.tsx
Labels: T-disaster-recovery

#125000 release-24.1: log: change fingerprint_id type to string
  docs/generated/eventlog.md
  pkg/sql/appstatspb/app_stats.go
  pkg/sql/exec_log.go
  pkg/sql/telemetry_datadriven_test.go
  pkg/sql/telemetry_logging_test.go
  pkg/sql/testdata/telemetry_logging/logging/force_logging
  pkg/sql/testdata/telemetry_logging/logging/statement_fingerprint_id
  pkg/sql/testdata/telemetry_logging/logging/stmts_per_txn_limit
  pkg/sql/testdata/telemetry_logging/logging/transaction_mode
  pkg/util/log/eventpb/json_encode_generated.go
  pkg/util/log/eventpb/telemetry.proto
  pkg/util/log/logtestutils/structured_log_spy.go
Labels: backport

#125043 release-23.2: log: change fingerprint_id type to string
  docs/generated/eventlog.md
  pkg/sql/appstatspb/app_stats.go
  pkg/sql/exec_log.go
  pkg/sql/telemetry_datadriven_test.go
  pkg/sql/telemetry_logging_test.go
  pkg/sql/testdata/telemetry_logging/logging/force_logging
  pkg/sql/testdata/telemetry_logging/logging/statement_fingerprint_id
  pkg/sql/testdata/telemetry_logging/logging/stmts_per_txn_limit
  pkg/sql/testdata/telemetry_logging/logging/transaction_mode
  pkg/util/log/eventpb/json_encode_generated.go
  pkg/util/log/eventpb/telemetry.proto
  pkg/util/log/logtestutils/structured_log_spy.go
Labels: backport

#125284 tree: make empty array error condition stricter
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/sem/tree/type_check.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125107 release-23.2: storage: calculate total capacity off of max percentage
  pkg/base/config.go
  pkg/ccl/storageccl/engineccl/encrypted_fs_test.go
  pkg/kv/kvserver/kvstorage/cluster_version_test.go
  pkg/kv/kvserver/store_snapshot.go
  pkg/server/config.go
  pkg/server/settings_cache_test.go
  pkg/storage/in_mem.go
  pkg/storage/mvcc_test.go
  pkg/storage/open.go
  pkg/storage/pebble.go
  pkg/storage/sst_test.go
  pkg/testutils/localtestcluster/local_test_cluster.go
Labels: backport

#125282 scbuild: use proper checks when creating a virtual computed column
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
  pkg/sql/schemachanger/testdata/end_to_end/drop_index_partial_expression_index/drop_index_partial_expression_index.side_effects
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125330 release-23.2: kv: avoid O(stores) work in updatePausedFollowersLocked
  pkg/kv/kvserver/replica_raft_overload.go
Labels: backport

#125324 logictestccl: deflake TestTenantLogic_jobs
  pkg/jobs/jobs.go
  pkg/sql/logictest/testdata/logic_test/jobs
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125276 kvserver: constrain store gossip chatter
  pkg/kv/kvserver/asim/gossip/BUILD.bazel
  pkg/kv/kvserver/asim/gossip/gossip.go
  pkg/kv/kvserver/asim/gossip/gossip_test.go
  pkg/kv/kvserver/asim/state/impl.go
  pkg/kv/kvserver/asim/state/state.go
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_add_node
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_fulldisk
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_io_overload
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_multi_store
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_rebalancing
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_zone_config
  pkg/kv/kvserver/client_split_test.go
  pkg/kv/kvserver/store.go
  pkg/kv/kvserver/store_gossip.go
  pkg/kv/kvserver/store_gossip_test.go
Labels: backport-23.2.x, backport-24.1.x

#123920 codeowners: add upgrade-prs team to pkg/upgrade
  .github/CODEOWNERS
  TEAMS.yaml
  pkg/cmd/roachtest/registry/owners.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/internal/team/TEAMS.yaml
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125296 release-24.1: roachtest: export $root for roachtest weekly
  build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh
Labels: backport

#125370 ui: wrong usage of string interpolation in React component
  pkg/ui/workspaces/cluster-ui/src/loading/loading.tsx
Labels: O-community, T-observability

#125278 release-23.2: pkg/server: remove flaky assertion from TestHotRangesResponse
  pkg/server/application_api/storage_inspection_test.go
Labels: backport

#125275 release-23.1: pkg/server: remove flaky assertion from TestHotRangesResponse
  pkg/server/status_test.go
Labels: backport

#125325 release-24.1: tree: make empty array error condition stricter
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/sem/tree/type_check.go
Labels: backport

#125326 release-23.2: tree: make empty array error condition stricter
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/sem/tree/type_check.go
Labels: backport

#125328 release-23.1: tree: make empty array error condition stricter
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/logictest/testdata/logic_test/typing
  pkg/sql/sem/tree/type_check.go
Labels: backport

#125320 streamingccl: add more metrics to LDR Metrics page
  pkg/ccl/spanconfigccl/spanconfigreconcilerccl/BUILD.bazel
  pkg/ccl/spanconfigccl/spanconfigreconcilerccl/datadriven_test.go
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/logicalDataReplication.tsx
Labels: T-disaster-recovery

#125421 release-23.1: logictestccl: deflake TestTenantLogic_jobs
  pkg/jobs/jobs.go
  pkg/sql/logictest/testdata/logic_test/jobs
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
Labels: backport

#125419 release-23.2: logictestccl: deflake TestTenantLogic_jobs
  pkg/jobs/jobs.go
  pkg/sql/logictest/testdata/logic_test/jobs
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
Labels: backport

#124711 sql: clarify error message when subtracting NaN from pg_lsn
  pkg/sql/logictest/testdata/logic_test/pg_lsn
  pkg/sql/sem/eval/binary_op.go
Labels: O-community, X-blathers-triaged

#121418 cacheutil: make sql cache map generic
  pkg/sql/cacheutil/cache.go
  pkg/sql/cacheutil/cache_test.go
  pkg/sql/syntheticprivilegecache/cache.go
Labels: O-community

#124371 sql: correct error when logging timed out and cancelled queries
  pkg/sql/conn_executor_exec.go
  pkg/sql/sql_exec_log_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125417 release-24.1: scbuild: use proper checks when creating a virtual computed column
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
  pkg/sql/schemachanger/testdata/end_to_end/drop_index_partial_expression_index/drop_index_partial_expression_index.side_effects
Labels: backport

#125490 sql: deflake TestExperimentalRelocateNonVoters
  pkg/sql/multitenant_admin_function_test.go
Labels: backport-24.1.x

#125520 spanconfigsqltranslatorccl: increase test timeout
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/BUILD.bazel
Labels: backport-24.1.x

#125507 opt: build constrained scans for LIKE patterns with escaped escapes
  pkg/sql/opt/idxconstraint/index_constraints.go
  pkg/sql/opt/idxconstraint/testdata/strings
  pkg/sql/opt/memo/constraint_builder.go
  pkg/sql/opt/xform/testdata/rules/select
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-21.1.23-rc

#125534 Revert "jobs: release registration before clearing claim"
  pkg/jobs/adopt.go
  pkg/jobs/registry_test.go
Labels: T-jobs

#125420 release-23.1: scbuild: use proper checks when creating a virtual computed column
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/logictest/testdata/logic_test/expression_index
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
  pkg/sql/schemachanger/testdata/end_to_end/drop_index_partial_expression_index
Labels: backport

#125488 release-24.1: kvserver: bump max range size in TestUnsplittableRange
  pkg/kv/kvserver/client_split_test.go
Labels: backport

#125489 release-23.2: kvserver: bump max range size in TestUnsplittableRange
  pkg/kv/kvserver/client_split_test.go
Labels: backport

#125436 release-23.1: changefeedccl: Partially support CDC query in ALTER CHANGEFEED
  pkg/ccl/changefeedccl/alter_changefeed_stmt.go
  pkg/ccl/changefeedccl/alter_changefeed_test.go
Labels: backport

#124634 kv: shallow copy BatchRequest on mutate in tryBumpBatchTimestamp
  pkg/kv/kvserver/replica_batch_updates.go
  pkg/kv/kvserver/replica_evaluate.go
  pkg/kv/kvserver/replica_proposal.go
  pkg/kv/kvserver/replica_raft.go
  pkg/kv/kvserver/replica_read.go
  pkg/kv/kvserver/replica_send.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/replica_write.go
Labels: O-community, X-blathers-triaged, backport-24.1.x

#125574 release-24.1: kvserver: bump max range size in TestStoreRangeSplitBackpressureWrites
  pkg/kv/kvserver/client_split_test.go
Labels: backport

#125525 release-23.2: changefeedccl: add new table bytes metric for usage data
  docs/generated/metrics/metrics.html
  pkg/BUILD.bazel
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeedbase/settings.go
  pkg/ccl/changefeedccl/fetch_table_bytes.go
  pkg/ccl/changefeedccl/fetch_table_bytes_test.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/changefeedccl/mocks/BUILD.bazel
  pkg/ccl/changefeedccl/mocks/empty.go
  pkg/ccl/changefeedccl/mocks/tenant_status_server_generated.go
  pkg/ccl/changefeedccl/testing_knobs.go
  pkg/gen/gomock.bzl
Labels: backport

#125575 release-23.2: kvserver: bump max range size in TestStoreRangeSplitBackpressureWrites
  pkg/kv/kvserver/client_split_test.go
Labels: backport

#125517 release-24.1.1-rc: add block load semaphore, add cluster settings to control readahead
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  docs/generated/metrics/metrics.html
  go.mod
  go.sum
  pkg/kv/kvserver/metrics.go
  pkg/server/config.go
  pkg/server/server_test.go
  pkg/storage/BUILD.bazel
  pkg/storage/engine.go
  pkg/storage/engine_test.go
  pkg/storage/open.go
  pkg/storage/pebble.go
  pkg/storage/testdata/intent_interleaving_iter/basic
  pkg/storage/testdata/lock_table_iterator/basic
  pkg/storage/testdata/lock_table_iterator/filter
  pkg/storage/testdata/lock_table_iterator/iters_before_seek
Labels: backport

#125543 release-23.2: add block load semaphore, add cluster settings to control readahead
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  docs/generated/metrics/metrics.html
  go.mod
  go.sum
  pkg/kv/kvserver/metrics.go
  pkg/server/config.go
  pkg/server/server_test.go
  pkg/storage/BUILD.bazel
  pkg/storage/engine.go
  pkg/storage/engine_test.go
  pkg/storage/open.go
  pkg/storage/pebble.go
  pkg/storage/testdata/intent_interleaving_iter/basic
  pkg/storage/testdata/lock_table_iterator/basic
  pkg/storage/testdata/lock_table_iterator/filter
  pkg/storage/testdata/lock_table_iterator/iters_before_seek
Labels: backport

#125516 release-24.1: add block load semaphore, add cluster settings to control readahead
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  docs/generated/metrics/metrics.html
  go.mod
  go.sum
  pkg/kv/kvserver/metrics.go
  pkg/server/config.go
  pkg/server/server_test.go
  pkg/storage/BUILD.bazel
  pkg/storage/engine.go
  pkg/storage/engine_test.go
  pkg/storage/open.go
  pkg/storage/pebble.go
  pkg/storage/testdata/intent_interleaving_iter/basic
  pkg/storage/testdata/lock_table_iterator/basic
  pkg/storage/testdata/lock_table_iterator/filter
  pkg/storage/testdata/lock_table_iterator/iters_before_seek
Labels: backport

#125557 kvserver: deflake rebalance multi-store
  pkg/kv/kvserver/replicate_queue_test.go
Labels: backport-23.2.x, backport-24.1.x

#125430 kvstreamer: disable tenants in TestStreamerVaryingResponseSizes
  pkg/kv/kvclient/kvstreamer/streamer_test.go
Labels: backport-23.2.x, backport-24.1.x

#125592 release-23.2.6-rc: add block load semaphore, add cluster settings to control readahead
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  docs/generated/metrics/metrics.html
  go.mod
  go.sum
  pkg/kv/kvserver/metrics.go
  pkg/server/config.go
  pkg/server/server_test.go
  pkg/storage/BUILD.bazel
  pkg/storage/engine.go
  pkg/storage/engine_test.go
  pkg/storage/open.go
  pkg/storage/pebble.go
  pkg/storage/testdata/intent_interleaving_iter/basic
  pkg/storage/testdata/lock_table_iterator/basic
  pkg/storage/testdata/lock_table_iterator/filter
  pkg/storage/testdata/lock_table_iterator/iters_before_seek
Labels: backport

#125425 release-23.2: kvserver: constrain store gossip chatter
  pkg/kv/kvserver/asim/gossip/BUILD.bazel
  pkg/kv/kvserver/asim/gossip/gossip.go
  pkg/kv/kvserver/asim/gossip/gossip_test.go
  pkg/kv/kvserver/asim/state/impl.go
  pkg/kv/kvserver/asim/state/state.go
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_add_node
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_fulldisk
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_multi_store
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_rebalancing
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_zone_config
  pkg/kv/kvserver/asim/tests/testdata/rand/weighted_rand
  pkg/kv/kvserver/client_split_test.go
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/kv/kvserver/store.go
  pkg/kv/kvserver/store_gossip.go
  pkg/kv/kvserver/store_gossip_test.go
Labels: backport

#125600 release-23.2.6-rc: kvserver: constrain store gossip chatter
  pkg/kv/kvserver/asim/gossip/BUILD.bazel
  pkg/kv/kvserver/asim/gossip/gossip.go
  pkg/kv/kvserver/asim/gossip/gossip_test.go
  pkg/kv/kvserver/asim/state/impl.go
  pkg/kv/kvserver/asim/state/state.go
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_add_node
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_fulldisk
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_multi_store
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_rebalancing
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_zone_config
  pkg/kv/kvserver/asim/tests/testdata/rand/rand_ranges
  pkg/kv/kvserver/asim/tests/testdata/rand/weighted_rand
  pkg/kv/kvserver/client_split_test.go
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/kv/kvserver/store.go
  pkg/kv/kvserver/store_gossip.go
  pkg/kv/kvserver/store_gossip_test.go
Labels: backport

#125554 release-24.1: sqlstats: decrease in-memory fingerprint limit from 100000 to 7500
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/sqlstats/cluster_settings.go
Labels: backport

#125469 release-23.2: changefeedccl: fix panics when min_checkpoint_frequency is 0
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport

#125495 release-23.1: changefeedccl: fix panics when min_checkpoint_frequency is 0
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport

#125612 release-24.1.1-rc: kvserver: constrain store gossip chatter
  pkg/kv/kvserver/asim/gossip/BUILD.bazel
  pkg/kv/kvserver/asim/gossip/gossip.go
  pkg/kv/kvserver/asim/gossip/gossip_test.go
  pkg/kv/kvserver/asim/state/impl.go
  pkg/kv/kvserver/asim/state/state.go
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_add_node
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_fulldisk
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_io_overload
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_multi_store
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_rebalancing
  pkg/kv/kvserver/asim/tests/testdata/non_rand/example_zone_config
  pkg/kv/kvserver/client_split_test.go
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/kv/kvserver/store.go
  pkg/kv/kvserver/store_gossip.go
  pkg/kv/kvserver/store_gossip_test.go
Labels: backport

#125533 release-24.1: catalog: public schema should be owned by database owner
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/show_test.go
  pkg/ccl/backupccl/testdata/backup-restore/restore-grants
  pkg/ccl/backupccl/testdata/backup-restore/restore-on-fail-or-cancel-schema-objects
  pkg/cli/clisqlshell/testdata/describe
  pkg/sql/catalog/catpb/privilege.go
  pkg/sql/catalog/ingesting/privileges.go
  pkg/sql/catalog/randgen/randgen.go
  pkg/sql/catalog/schemadesc/public_schema_desc.go
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_system
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_tenant
  pkg/sql/descriptor.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/logictest/testdata/logic_test/database
  pkg/sql/logictest/testdata/logic_test/drop_database
  pkg/sql/logictest/testdata/logic_test/drop_owned_by
  pkg/sql/logictest/testdata/logic_test/event_log
  pkg/sql/logictest/testdata/logic_test/event_log_legacy
  pkg/sql/logictest/testdata/logic_test/new_schema_changer
  pkg/sql/logictest/testdata/logic_test/owner
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/show_trace
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_database.go
  pkg/sql/schemachanger/scbuild/testdata/create_database
  pkg/sql/schemachanger/scbuild/testdata/drop_database
  pkg/sql/schemachanger/scdecomp/testdata/other
  pkg/sql/schemachanger/scplan/testdata/create_database
  pkg/sql/schemachanger/testdata/end_to_end/create_complex/create_complex.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_complex/create_complex__statement_1_of_4.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_complex/create_complex__statement_2_of_4.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_complex/create_complex__statement_3_of_4.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_complex/create_complex__statement_4_of_4.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_database/create_database.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_database/create_database.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_database_drop_database_separate_statements/create_database_drop_database_separate_statements.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_database_drop_database_separate_statements/create_database_drop_database_separate_statements__statement_1_of_3.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_database_drop_database_separate_statements/create_database_drop_database_separate_statements__statement_3_of_3.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_index_create_database_separate_statements/create_index_create_database_separate_statements.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_index_create_database_separate_statements/create_index_create_database_separate_statements__statement_2_of_2.explain
Labels: backport

#125535 release-23.2: catalog: public schema should be owned by database owner
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/show_test.go
  pkg/ccl/backupccl/testdata/backup-restore/restore-grants
  pkg/ccl/backupccl/testdata/backup-restore/restore-on-fail-or-cancel-schema-objects
  pkg/cli/clisqlshell/testdata/describe
  pkg/sql/catalog/catpb/privilege.go
  pkg/sql/catalog/ingesting/privileges.go
  pkg/sql/catalog/randgen/randgen.go
  pkg/sql/catalog/schemadesc/public_schema_desc.go
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_system
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_tenant
  pkg/sql/descriptor.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/logictest/testdata/logic_test/database
  pkg/sql/logictest/testdata/logic_test/drop_database
  pkg/sql/logictest/testdata/logic_test/drop_owned_by
  pkg/sql/logictest/testdata/logic_test/event_log
  pkg/sql/logictest/testdata/logic_test/event_log_legacy
  pkg/sql/logictest/testdata/logic_test/new_schema_changer
  pkg/sql/logictest/testdata/logic_test/owner
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/show_trace
  pkg/sql/schemachanger/scbuild/testdata/drop_database
  pkg/sql/schemachanger/scdecomp/testdata/other
Labels: backport

#125643 sql,cli: use softer language for cluster setting renames; include aliases in docs
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/cli/gen.go
  pkg/sql/logictest/testdata/logic_test/cluster_settings
  pkg/sql/set_cluster_setting.go
  pkg/sql/show_cluster_setting.go
  pkg/sql/tenant_settings.go
Labels: backport-23.2.x, backport-24.1.x

#125584 util/duration: add a couple of special cases to MulFloat
  pkg/util/duration/duration.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125649 release-24.1: sql,cli: use softer language for cluster setting renames; include aliases in docs
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/cli/gen.go
  pkg/sql/logictest/testdata/logic_test/cluster_settings
  pkg/sql/set_cluster_setting.go
  pkg/sql/show_cluster_setting.go
  pkg/sql/tenant_settings.go
Labels: backport

#125532 insights: cache capacity using statement count
  pkg/sql/sqlstats/insights/store.go
  pkg/sql/sqlstats/insights/store_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125655 release-23.2: sql,cli: use softer language for cluster setting renames; include aliases in docs
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/cli/gen.go
  pkg/sql/logictest/testdata/logic_test/cluster_settings
  pkg/sql/set_cluster_setting.go
  pkg/sql/show_cluster_setting.go
  pkg/sql/tenant_settings.go
Labels: backport

#125250 release-24.1: sql: move jobs table auth checks out of hot path
  pkg/bench/rttanalysis/cluster.go
  pkg/bench/rttanalysis/jobs_test.go
  pkg/bench/rttanalysis/rtt_analysis_bench.go
  pkg/bench/rttanalysis/rtt_analysis_test.go
  pkg/bench/rttanalysis/testdata/benchmark_expectations
  pkg/ccl/benchccl/rttanalysisccl/multi_region_bench_test.go
  pkg/ccl/changefeedccl/alter_changefeed_stmt.go
  pkg/jobs/jobsauth/BUILD.bazel
  pkg/jobs/jobsauth/authorization.go
  pkg/jobs/jobsauth/authorization_test.go
  pkg/sql/control_jobs.go
  pkg/sql/crdb_internal.go
Labels: backport

#125558 release-24.1: kvstorage: speed up scan for range descriptors
  pkg/kv/kvserver/kvstorage/BUILD.bazel
  pkg/kv/kvserver/kvstorage/datadriven_test.go
  pkg/kv/kvserver/kvstorage/init.go
  pkg/kv/kvserver/kvstorage/testdata/assert_overlapping_replica
  pkg/kv/kvserver/kvstorage/testdata/assert_replicaid
  pkg/kv/kvserver/kvstorage/testdata/assert_replicaid_uninitialized
  pkg/kv/kvserver/kvstorage/testdata/init
  pkg/kv/kvserver/kvstorage/testdata/overlapping_replica
Labels: backport

#125595 sidetransport: deflake TestRPCConnUnblocksOnStopper
  pkg/kv/kvserver/closedts/sidetransport/sender_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125687 upgrade/upgrades: TestLeasingClusterVersionStarvation flake
  pkg/upgrade/upgrades/version_starvation_test.go
Labels: backport-24.1.x

#125697 pkg/server: export sql.new_conns in /_status/load
  pkg/server/BUILD.bazel
  pkg/server/load_endpoint.go
  pkg/server/load_endpoint_test.go
Labels: backport-23.2.x, backport-24.1.x

#125721 changefeedccl: add more logging around checkpointing
  pkg/ccl/changefeedccl/changefeed_dist.go
  pkg/ccl/changefeedccl/changefeed_processors.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125781 roachtest: disable c2c roachtests on Azure
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: T-disaster-recovery

#125798 release-24.1: released CockroachDB version 24.1.1. Next version: 24.1.2
  pkg/build/version.txt
Labels: backport

#125763 release-23.1: changefeedccl: add more logging around checkpointing
  pkg/ccl/changefeedccl/changefeed_dist.go
  pkg/ccl/changefeedccl/changefeed_processors.go
Labels: backport

#125805 release-23.2: released CockroachDB version 23.2.6. Next version: 23.2.7
  pkg/build/version.txt
Labels: backport

#125809 kvtenant: use manual replication mode for desc scan tests
  pkg/kv/kvclient/kvtenant/tenant_scan_range_descriptors_test.go
Labels: backport-24.1.x

#125824 release: remove unused release script
  build/teamcity/internal/release/process/publish-cockroach-release.sh
Labels: C-enhancement, A-release, T-release

#125783 roachtest: fix mixedversion context in startup functions
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125886 release-23.2: go.mod: bump Pebble to e406c9cdb433
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#125818 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#125816 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#116262 proto: add functionality to marshal protobuf binary from file descriptor
  pkg/BUILD.bazel
  pkg/gen/protobuf.bzl
  pkg/sql/protoreflect/BUILD.bazel
  pkg/sql/protoreflect/gprototest/BUILD.bazel
  pkg/sql/protoreflect/gprototest/gprototest.proto
  pkg/sql/protoreflect/utils.go
  pkg/sql/protoreflect/utils_test.go
  pkg/util/protoutil/BUILD.bazel
  pkg/util/protoutil/marshal.go
Labels: O-community

#125896 authors: add sambhav-jain-16 to authors
  AUTHORS
Labels: first-pr

#125928 roachtest: fix restore with pause roachtest
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#125894 authors: add Shailendra Patel to authors
  AUTHORS
Labels: first-pr

#125810 release-23.1: cli: remove cluster-wide insights from debug zip
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/partial1_excluded
  pkg/cli/testdata/zip/partial2
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/testzip_concurrent
  pkg/cli/testdata/zip/testzip_exclude_goroutine_stacks
  pkg/cli/testdata/zip/testzip_exclude_range_info
  pkg/cli/testdata/zip/testzip_include_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_range_info
  pkg/cli/testdata/zip/testzip_shared_process_tenant
  pkg/cli/testdata/zip/testzip_tenant_separate_process
  pkg/cli/zip_table_registry.go
  pkg/cli/zip_test.go
Labels: backport

#125807 release-24.1: cli: remove cluster-wide insights from debug zip
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/partial1_excluded
  pkg/cli/testdata/zip/partial2
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/testzip_concurrent
  pkg/cli/testdata/zip/testzip_exclude_goroutine_stacks
  pkg/cli/testdata/zip/testzip_exclude_range_info
  pkg/cli/testdata/zip/testzip_external_process_virtualization
  pkg/cli/testdata/zip/testzip_include_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_range_info
  pkg/cli/testdata/zip/testzip_shared_process_virtualization
  pkg/cli/testdata/zip/testzip_shared_process_virtualization_with_default_tenant
  pkg/cli/zip_table_registry.go
  pkg/cli/zip_test.go
Labels: backport

#125804 release-23.2: cli: remove cluster-wide insights from debug zip
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/partial1_excluded
  pkg/cli/testdata/zip/partial2
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/testzip_concurrent
  pkg/cli/testdata/zip/testzip_exclude_goroutine_stacks
  pkg/cli/testdata/zip/testzip_exclude_range_info
  pkg/cli/testdata/zip/testzip_external_process_virtualization
  pkg/cli/testdata/zip/testzip_include_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_range_info
  pkg/cli/testdata/zip/testzip_shared_process_virtualization
  pkg/cli/testdata/zip/testzip_shared_process_virtualization_with_default_tenant
  pkg/cli/zip_table_registry.go
  pkg/cli/zip_test.go
Labels: backport

#125943 kv: deflake TestWedgedReplicaDetection
  pkg/kv/kvserver/client_raft_test.go
  pkg/kv/kvserver/helpers_test.go
Labels: backport-23.2.x, backport-24.1.x

#125873 log: use httptest for http sink tests
  pkg/util/log/BUILD.bazel
  pkg/util/log/http_sink_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125860 release-23.1: compose: TestComposeCompare improvements and fixes
  pkg/compose/BUILD.bazel
  pkg/compose/compare/compare/BUILD.bazel
  pkg/compose/compare/compare/compare_test.go
  pkg/compose/compare/docker-compose.yml
  pkg/compose/compose_test.go
Labels: backport

#125528 release-23.1: changefeedccl: add new table bytes metric for usage data
  docs/generated/metrics/metrics.html
  pkg/BUILD.bazel
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeedbase/settings.go
  pkg/ccl/changefeedccl/fetch_table_bytes.go
  pkg/ccl/changefeedccl/fetch_table_bytes_test.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/ccl/changefeedccl/mocks/BUILD.bazel
  pkg/ccl/changefeedccl/mocks/empty.go
  pkg/ccl/changefeedccl/mocks/tenant_status_server_generated.go
  pkg/ccl/changefeedccl/testing_knobs.go
  pkg/gen/gomock.bzl
  pkg/settings/int.go
  pkg/ts/catalog/chart_catalog.go
  pkg/ts/catalog/metrics.go
Labels: backport

#125961 workload/schemachange: avoid selecting non-public enum members
  pkg/workload/schemachange/operation_generator.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125946 randgen: avoid overflow in computed column expressions
  pkg/sql/randgen/expr.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#125626 pkg/cli: tsdump - fix custom SQL port behaviour
  pkg/cli/tsdump.go
  pkg/cli/tsdump_test.go
Labels: backport-23.2.x, backport-24.1.x

#125836 release-24.1: sql/schemachanger: Enhanced debugging for long-running schema changes
  pkg/ccl/multiregionccl/regionliveness_test.go
  pkg/sql/catalog/descpb/BUILD.bazel
  pkg/sql/catalog/descpb/lease.proto
  pkg/sql/catalog/lease/BUILD.bazel
  pkg/sql/catalog/lease/count.go
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_internal_test.go
  pkg/sql/schemachanger/scdeps/BUILD.bazel
  pkg/sql/schemachanger/scdeps/run_deps.go
  pkg/sql/schemachanger/scdeps/sctestdeps/test_deps.go
  pkg/sql/schemachanger/scjob/BUILD.bazel
  pkg/sql/schemachanger/scjob/job.go
  pkg/sql/schemachanger/scrun/dependencies.go
  pkg/sql/schemachanger/scrun/scrun.go
Labels: backport

#125567 release-24.1: sql: harden handling of the GroupBy
  pkg/sql/colexec/colbuilder/BUILD.bazel
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/execinfra/execagg/BUILD.bazel
  pkg/sql/execinfra/execagg/base.go
  pkg/sql/logictest/testdata/logic_test/aggregate
  pkg/sql/rowexec/aggregator.go
Labels: backport

#125568 release-23.2: sql: harden handling of the GroupBy
  pkg/sql/colexec/colbuilder/BUILD.bazel
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/execinfra/execagg/BUILD.bazel
  pkg/sql/execinfra/execagg/base.go
  pkg/sql/rowexec/aggregator.go
Labels: backport

#125570 release-23.1: sql: harden handling of the GroupBy
  pkg/sql/colexec/colbuilder/BUILD.bazel
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/execinfra/execagg/BUILD.bazel
  pkg/sql/execinfra/execagg/base.go
  pkg/sql/rowexec/aggregator.go
Labels: backport

#125797 cli: fix statement-bundle recreate for cluster settings
  pkg/cli/interactive_tests/test_explain_analyze_debug.tcl
  pkg/cli/statement_bundle.go
  pkg/sql/explain_bundle.go
Labels: backport-23.2.x, backport-24.1.x

#126014 compose: don't use DebuggableTempDir helper
  pkg/compose/BUILD.bazel
  pkg/compose/compose_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#126023 release-23.1: roachtest: fix django tests; update python
  pkg/cmd/roachtest/tests/asyncpg.go
  pkg/cmd/roachtest/tests/django.go
  pkg/cmd/roachtest/tests/sqlalchemy.go
Labels: backport

#126022 release-23.2: roachtest: fix django tests; update python
  pkg/cmd/roachtest/tests/asyncpg.go
  pkg/cmd/roachtest/tests/django.go
  pkg/cmd/roachtest/tests/sqlalchemy.go
Labels: backport

#126027 release-23.1: roachtest: mark 2 asyncpg tests as flaky
  pkg/cmd/roachtest/tests/asyncpg_blocklist.go
Labels: backport

#126026 release-23.2: roachtest: mark 2 asyncpg tests as flaky
  pkg/cmd/roachtest/tests/asyncpg_blocklist.go
Labels: backport

#126030 release-23.2: compose: don't use DebuggableTempDir helper
  pkg/compose/BUILD.bazel
  pkg/compose/compose_test.go
Labels: backport

#126031 release-23.1: compose: don't use DebuggableTempDir helper
  pkg/compose/BUILD.bazel
  pkg/compose/compose_test.go
Labels: backport

#126040 kv: deflake TestNodeLivenessRetryAmbiguousResultError
  pkg/kv/kvserver/node_liveness_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#126085 changefeedccl: disable physical plan debug persistence
  pkg/ccl/changefeedccl/changefeed_dist.go
  pkg/jobs/jobsprofiler/profiler_test.go
Labels: backport-23.1.x, backport-23.2.x

#124066 kvclient: separate out proxy sending
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/server/node.go
Labels: backport-24.1.x, backport-24.1.2-rc

#125817 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#126106 liveness: grant test an additional core under `race`
  pkg/kv/kvserver/liveness/BUILD.bazel
Labels: backport-24.1.x

#126111 release-23.1: roachtest: unpin ubuntu version for asyncpg test
  pkg/cmd/roachtest/tests/asyncpg.go
Labels: backport

#126112 release-23.2: roachtest: unpin ubuntu version for asyncpg test
  pkg/cmd/roachtest/tests/asyncpg.go
Labels: backport

#123518 release-23.2: sql/opt: add error handling during query plan cache invalidation
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/opt/metadata.go
Labels: backport

#125599 release-23.2: rowcontainer: miscellaneous fixes around TSQuery, TSVector, and tuple types
  pkg/sql/logictest/testdata/logic_test/hash_join
  pkg/sql/logictest/testdata/logic_test/suboperators
  pkg/sql/logictest/testdata/logic_test/tsvector
  pkg/sql/logictest/testdata/logic_test/tuple
  pkg/sql/logictest/testdata/logic_test/void
  pkg/sql/rowcontainer/BUILD.bazel
  pkg/sql/rowcontainer/disk_row_container.go
  pkg/sql/rowcontainer/disk_row_container_test.go
  pkg/sql/rowcontainer/hash_row_container.go
  pkg/sql/rowcontainer/kvstreamer_result_disk_buffer.go
  pkg/sql/rowcontainer/row_container.go
  pkg/sql/rowenc/keyside/encode.go
Labels: backport

#126047 sql,schemachanger: pause backfill job when disk space runs out
  pkg/sql/backfill.go
  pkg/sql/schemachanger/scexec/BUILD.bazel
  pkg/sql/schemachanger/scexec/exec_backfill.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#126146 release-23.1: released CockroachDB version 23.1.23. Next version: 23.1.24
  pkg/build/version.txt
Labels: backport

#126176 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#126174 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#126173 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#126139 release-24.1: log: use httptest for http sink tests
  pkg/util/log/BUILD.bazel
  pkg/util/log/http_sink_test.go
Labels: backport

#126140 release-23.2: log: use httptest for http sink tests
  pkg/util/log/BUILD.bazel
  pkg/util/log/http_sink_test.go
Labels: backport
