Repository cockroachdb/cockroach, pull requests merged in 2024-03, with the labels that each got.

#119787 release-23.2: roachtest: port multitenant/tpch to new roachprod API
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster/cluster_interface.go
  pkg/cmd/roachtest/tests/allocation_bench.go
  pkg/cmd/roachtest/tests/autoupgrade.go
  pkg/cmd/roachtest/tests/cancel.go
  pkg/cmd/roachtest/tests/cluster_init.go
  pkg/cmd/roachtest/tests/decommission.go
  pkg/cmd/roachtest/tests/decommission_self.go
  pkg/cmd/roachtest/tests/inconsistency.go
  pkg/cmd/roachtest/tests/kv.go
  pkg/cmd/roachtest/tests/kvbench.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/multitenant_tpch.go
  pkg/cmd/roachtest/tests/query_comparison_util.go
  pkg/cmd/roachtest/tests/rapid_restart.go
  pkg/cmd/roachtest/tests/tlp.go
  pkg/cmd/roachtest/tests/tpc_utils.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/tpch_concurrency.go
  pkg/cmd/roachtest/tests/tpchbench.go
  pkg/cmd/roachtest/tests/tpchvec.go
  pkg/cmd/roachtest/tests/validate_system_schema_after_version_upgrade.go
Labels: backport

#119337 release-23.2: sql: stop ignoring internal exec for sql metrics
  pkg/sql/conn_executor_exec.go
  pkg/sql/conn_executor_test.go
  pkg/sql/sqlstats/sslocal/BUILD.bazel
  pkg/sql/sqlstats/sslocal/sql_stats_test.go
Labels: backport

#119338 release-23.1: sql: stop ignoring internal exec for sql metrics
  pkg/sql/conn_executor_exec.go
  pkg/sql/conn_executor_test.go
  pkg/sql/sqlstats/sslocal/BUILD.bazel
  pkg/sql/sqlstats/sslocal/sql_stats_test.go
Labels: backport

#119638 release-23.1: builtins: allow VIEWACTIVITY priv to use crdb_internal.request_statem…
  pkg/sql/faketreeeval/evalctx.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/eval/deps.go
Labels: backport

#119739 catalog/lease: block liveness heartbeats if leases cannot be written
  pkg/sql/catalog/lease/BUILD.bazel
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/catalog/lease/storage.go
  pkg/sql/sqlliveness/slinstance/slinstance.go
  pkg/sql/sqlliveness/sqlliveness.go
Labels: O-community

#119790 backupccl: fail online restore if target table has in-progres import
  pkg/ccl/backupccl/datadriven_test.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/testdata/backup-restore/online-restore-in-progress-imports
Labels: T-disaster-recovery

#119852 changefeedccl: deflake TestAlterChangefeedPersistSinkURI
  pkg/ccl/changefeedccl/alter_changefeed_test.go
Labels: backport-23.1.x, backport-23.2.x

#119765 storageccl: don't leak file readers in ExternalSSTReader
  pkg/ccl/storageccl/BUILD.bazel
  pkg/ccl/storageccl/external_sst_reader.go
  pkg/ccl/storageccl/external_sst_reader_test.go
Labels: backport-23.1.x, backport-23.2.x

#119889 release-23.1: changefeedccl: deflake TestAlterChangefeedPersistSinkURI
  pkg/ccl/changefeedccl/alter_changefeed_test.go
Labels: backport

#119925 release-23.1: restore: limit restore spans to 200 files
  pkg/ccl/backupccl/bench_covering_test.go
  pkg/ccl/backupccl/restore_span_covering.go
  pkg/ccl/backupccl/restore_span_covering_test.go
Labels: backport

#119985 release-23.2: update go to 1.21.8
  .bazelrc
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
Labels: C-enhancement, A-build-system, T-dev-inf, backport

#119984 build: update go to 1.22.1
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/bootstrap/bootstrap-debian.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
Labels: C-enhancement, A-build-system, T-dev-inf

#119868 roachprod: support customized builds
  pkg/cmd/roachprod/main.go
  pkg/roachprod/install/staging.go
  pkg/roachprod/install/staging_test.go
Labels: C-enhancement, A-roachprod, T-testeng

#119728 server: fix TestStructuredEventLogging test
  pkg/server/env_sampler.go
  pkg/server/server.go
  pkg/server/status/runtime_stats_test.go
  pkg/server/tenant.go
  pkg/server/testing_knobs.go
Labels: O-community, backport-23.2.x

#118456 sql: introduce `crdb_internal.execute_internally` builtin
  pkg/sql/exec_util.go
  pkg/sql/internal.go
  pkg/sql/opt/exec/execbuilder/testdata/execute_internally_builtin
  pkg/sql/opt/exec/execbuilder/tests/local/generated_test.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/builtins/generator_builtins.go
  pkg/sql/sessiondata/internal.go
  pkg/sql/sessiondata/session_data.go
  pkg/sql/sessiondata/session_data_test.go
Labels: backport-23.2.x

#119969 release-23.1: CRDB-28040 : JWKS fetch from jwks_uri
  pkg/ccl/jwtauthccl/BUILD.bazel
  pkg/ccl/jwtauthccl/authentication_jwt.go
  pkg/ccl/jwtauthccl/authentication_jwt_test.go
  pkg/ccl/jwtauthccl/settings.go
  pkg/ccl/jwtauthccl/testdata/accounts.idp1.com_.well-known_openid-configuration
  pkg/ccl/jwtauthccl/testdata/www.idp1apis.com_oauth2_v3_certs
  pkg/ccl/jwtauthccl/testdata/www.idp1apis.com_oauth2_v3_certs_private
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/ccl/testccl/authccl/testdata/jwt
  pkg/sql/pgwire/auth_methods.go
Labels: backport

#119965 release-23.2: sql: set locality for all tables on MR system database
  pkg/ccl/multiregionccl/BUILD.bazel
  pkg/ccl/multiregionccl/multiregion_system_table_test.go
  pkg/sql/region_util.go
  pkg/upgrade/upgrades/create_region_liveness.go
  pkg/upgrade/upgrades/create_task_system_tables.go
  pkg/upgrade/upgrades/descriptor_utils.go
  pkg/upgrade/upgrades/descriptor_utils_test.go
  pkg/upgrade/upgrades/key_visualizer_migration.go
  pkg/upgrade/upgrades/mvcc_statistics_migration.go
  pkg/upgrade/upgrades/system_exec_insights.go
  pkg/upgrade/upgrades/system_job_info.go
  pkg/upgrade/upgrades/system_statistics_activity.go
  pkg/upgrade/upgrades/tenant_id_sequence_for_system_tenant.go
Labels: backport

#120036 release-23.2: server: fix TestStructuredEventLogging test
  pkg/server/env_sampler.go
  pkg/server/server.go
  pkg/server/status/runtime_stats_test.go
  pkg/server/tenant.go
  pkg/server/testing_knobs.go
Labels: O-community, backport

#120020 release-23.1: sqlstats: dont block flush due to sql activity job
  pkg/sql/sqlstats/persistedsqlstats/flush_test.go
  pkg/sql/sqlstats/persistedsqlstats/provider.go
Labels: backport

#119173 admission,kvadmission: scope admission.kv.bulk_only.enabled to store …
  pkg/kv/kvserver/kvadmission/kvadmission.go
  pkg/util/admission/work_queue.go
Labels: O-support

#120133 restore: don't pass user name and password to tpce connection
  pkg/cmd/roachtest/tests/online_restore.go
  pkg/cmd/roachtest/tests/restore.go
Labels: T-disaster-recovery

#120031 release-23.2: sql: introduce `crdb_internal.execute_internally` builtin
  pkg/sql/exec_util.go
  pkg/sql/internal.go
  pkg/sql/opt/exec/execbuilder/testdata/execute_internally_builtin
  pkg/sql/opt/exec/execbuilder/tests/local/generated_test.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/builtins/generator_builtins.go
  pkg/sql/sessiondata/internal.go
  pkg/sql/sessiondata/session_data.go
  pkg/sql/sessiondata/session_data_test.go
Labels: backport

#119342 backupccl: deflake TestDataDriven_restore_on_fail_or_cancel_retry
  pkg/ccl/backupccl/datadriven_test.go
  pkg/ccl/backupccl/testdata/backup-restore/restore-on-fail-or-cancel-retry
Labels: backport-23.2.x

#120158 release-23.2: sql: mark implicit transactions with AOST as read-only
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_util.go
  pkg/sql/internal.go
  pkg/sql/logictest/testdata/logic_test/as_of
  pkg/sql/logictest/testdata/logic_test/txn
  pkg/sql/vars.go
Labels: backport

#120192 release-23.2: roachprod: use logger for `printDetails`
  pkg/roachprod/cloud/cluster_cloud.go
Labels: backport

#120328 release-23.2: roachprod: only register services when applicable
  pkg/roachprod/install/cockroach.go
  pkg/roachprod/install/services.go
Labels: backport

#120199 roachtest/cdc: increase end_time for changefeed
  pkg/cmd/roachtest/tests/cdc_bench.go
Labels: backport-23.2.x

#120345 release-23.1: roachtest: fix logic for exact replication
  pkg/cmd/roachtest/tests/util.go
Labels: backport

#120346 release-23.1.17-rc: roachtest: fix logic for exact replication
  pkg/cmd/roachtest/tests/util.go
Labels: backport

#120343 release-23.2: roachtest: restore: restart nodes with same options
  pkg/cmd/roachtest/tests/jobs.go
  pkg/cmd/roachtest/tests/restore.go
Labels: backport

#120261 release-23.2: backuppcl: pass finishesSpec field to resume span
  pkg/ccl/backupccl/backup_processor.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/jobs.go
Labels: T-disaster-recovery, backport

#120159 release-23.1: sql: mark implicit transactions with AOST as read-only
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_util.go
  pkg/sql/internal.go
  pkg/sql/logictest/testdata/logic_test/as_of
  pkg/sql/logictest/testdata/logic_test/txn
  pkg/sql/vars.go
Labels: backport

#119906 roachprod: RAID0 only network disks if both local and network are present
  pkg/cmd/roachtest/tests/restore.go
  pkg/roachprod/vm/aws/support.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport-23.1.x, backport-23.2.x

#120374 stress: enable GitHub issue posting from EngFlow nightly `stress`
  build/teamcity/cockroach/nightlies/stress_engflow_deadlock.sh
  build/teamcity/cockroach/nightlies/stress_engflow_race.sh
  build/teamcity/cockroach/nightlies/stress_trigger.sh
  build/teamcity/cockroach/nightlies/stress_trigger_impl.sh
Labels: O-community

#120372 release-23.1: backuppcl: pass finishesSpec field to resume span
  pkg/ccl/backupccl/backup_processor.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/jobs.go
Labels: T-disaster-recovery, backport

#120436 release-23.2: roachprod: avoid adding new keys to project metadata when creating clusters
  pkg/roachprod/config/BUILD.bazel
  pkg/roachprod/config/config.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/roachprod.go
  pkg/roachprod/vm/aws/BUILD.bazel
  pkg/roachprod/vm/aws/aws.go
  pkg/roachprod/vm/aws/keys.go
  pkg/roachprod/vm/azure/BUILD.bazel
  pkg/roachprod/vm/azure/azure.go
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport

#119804 backupccl: reset job level retry counter if backup progress has advanced
  pkg/ccl/backupccl/backup_job.go
  pkg/ccl/backupccl/backup_test.go
  pkg/sql/exec_util.go
Labels: O-community, X-blathers-triaged

#119900 roachtest: SelectAWSMachineType should fall back to `c6a` without loc…
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/spec/machine_type.go
  pkg/cmd/roachtest/tests/tpcc.go
Labels: backport-22.2.x, backport-23.1.x, backport-23.2.x

#120429 release-23.1: roachprod: RAID0 only network disks if both local and network are present
  pkg/cmd/roachtest/tests/restore.go
  pkg/roachprod/vm/aws/support.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport

#120465 release-23.1: roachtest: SelectAWSMachineType should fall back to `c6a` without loc…
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/spec/machine_type.go
  pkg/cmd/roachtest/tests/tpcc.go
Labels: backport

#120514 release-23.1: workload/schemachange: ignore job-rows-batch-insert error
  pkg/workload/schemachange/schemachange.go
Labels: backport

#120414 backupccl: clear InProgressImportStartTime in RESTORE
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/testdata/backup-restore/in-progress-import-rollback
Labels: backport-23.1.x, backport-23.2.x

#120466 release-22.2: roachtest: SelectAWSMachineType should fall back to `c6a` without loc…
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/spec/machine_type.go
Labels: backport

#120241 release-23.1: kv: add appBatchStats.numAddSST to handleRaftReadyStats.SafeFormat
  pkg/kv/kvserver/replica_raft.go
  pkg/kv/kvserver/replica_raft_test.go
  pkg/kv/kvserver/testdata/handle_raft_ready_stats.txt
Labels: backport

#120512 release-22.2: roachprod: avoid adding new keys to project metadata when creating clusters
  pkg/roachprod/config/BUILD.bazel
  pkg/roachprod/config/config.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/roachprod.go
  pkg/roachprod/vm/aws/BUILD.bazel
  pkg/roachprod/vm/aws/aws.go
  pkg/roachprod/vm/aws/keys.go
  pkg/roachprod/vm/azure/azure.go
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport

#120556 release-23.1: workload/schemachange: ignore job-rows-batch-insert error
  pkg/workload/schemachange/schemachange.go
Labels: backport

#120553 roachtest: add flaky django/asyncpg/npgsql tests to ignore list
  pkg/cmd/roachtest/tests/asyncpg_blocklist.go
  pkg/cmd/roachtest/tests/django_blocklist.go
  pkg/cmd/roachtest/tests/dotnet_helpers.go
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
Labels: backport-23.1.x, backport-23.2.x

#120580 release-23.2: roachtest: fix bundle collection on failure in tpchvec/mt-shared-process
  pkg/cmd/roachtest/tests/tpchvec.go
Labels: backport

#120572 release-23.1: sql: deflake TestTrackOnlyUserOpenTransactionsAndActiveStatements
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/conn_executor_test.go
  pkg/sql/exec_util.go
  pkg/sql/sqlstats/sslocal/sql_stats_test.go
Labels: backport

#120574 release-23.1: roachtest: add flaky django/asyncpg/npgsql tests to ignore list
  pkg/cmd/roachtest/tests/asyncpg_blocklist.go
  pkg/cmd/roachtest/tests/django_blocklist.go
  pkg/cmd/roachtest/tests/dotnet_helpers.go
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
Labels: backport

#120573 release-23.2: roachtest: add flaky django/asyncpg/npgsql tests to ignore list
  pkg/cmd/roachtest/tests/asyncpg_blocklist.go
  pkg/cmd/roachtest/tests/django_blocklist.go
  pkg/cmd/roachtest/tests/dotnet_helpers.go
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
Labels: backport

#120657 roachtest: don't fail on slowness in tpchvec/direct_scans/mt-shared-process
  pkg/cmd/roachtest/tests/tpchvec.go
Labels: backport-23.2.x

#119459 fix: ensure information_schema default values for identity columns without explicit sequence options
  pkg/sql/catalog/tabledesc/table.go
  pkg/sql/logictest/testdata/logic_test/information_schema
Labels: O-community

#120681 sql: update observability opt test
  pkg/sql/opt/exec/execbuilder/testdata/observability
Labels: backport-23.1.x, backport-23.2.x

#120234 release-23.1: cluster-ui, db-console: fix bug where store ids are treated as node ids
  pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsConnected.ts
  pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.stories.tsx
  pkg/ui/workspaces/cluster-ui/src/databaseDetailsPage/databaseDetailsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/databaseTablePage/databaseTablePageConnected.ts
  pkg/ui/workspaces/cluster-ui/src/databases/combiners.ts
  pkg/ui/workspaces/cluster-ui/src/databases/util.spec.ts
  pkg/ui/workspaces/cluster-ui/src/databases/util.tsx
  pkg/ui/workspaces/cluster-ui/src/databasesPage/databasesPageConnected.ts
  pkg/ui/workspaces/db-console/src/redux/timeScale.ts
  pkg/ui/workspaces/db-console/src/views/databases/databaseDetailsPage/redux.spec.ts
  pkg/ui/workspaces/db-console/src/views/databases/databaseDetailsPage/redux.ts
  pkg/ui/workspaces/db-console/src/views/databases/databaseTablePage/redux.ts
  pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.spec.ts
  pkg/ui/workspaces/db-console/src/views/databases/databasesPage/redux.ts
Labels: backport

#120684 release-23.1: sql: update observability opt test
  pkg/sql/opt/exec/execbuilder/testdata/observability
Labels: backport

#120704 release-23.2: util/mon: add env var to disable monitor tree tracking
  pkg/util/mon/bytes_usage.go
Labels: backport

#120705 release-23.1: util/mon: add env var to disable monitor tree tracking
  pkg/util/mon/bytes_usage.go
Labels: backport

#120666 roachtest: add an error to list of npgsql flakes
  pkg/cmd/roachtest/tests/dotnet_helpers.go
Labels: backport-23.1.x, backport-23.2.x

#120451 opt,plpgsql: subquery hoisting rules should not reorder PL/pgSQL subroutines
  pkg/ccl/logictestccl/testdata/logic_test/procedure_plpgsql
  pkg/sql/opt/norm/decorrelate_funcs.go
  pkg/sql/opt/norm/testdata/rules/routine
Labels: backport-23.2.x

#120741 sql: add debug info to TestInsightsIntegrationForContention test
  pkg/sql/sqlstats/insights/integration/insights_test.go
Labels: O-community

#120789 release-23.1: util/mon: lose more references on Stop
  pkg/util/mon/bytes_usage.go
Labels: backport, backport-23.1.18-rc

#120788 release-23.2: util/mon: lose more references on Stop
  pkg/util/mon/bytes_usage.go
Labels: backport, backport-23.2.4-rc

#120779 release-23.2: c2c: prevent NPE in SHOW TENANT WITH REPLICATION STATUS
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go
  pkg/ccl/streamingccl/streamingest/testdata/show_without_pts
  pkg/sql/show_tenant.go
Labels: T-disaster-recovery, backport

#120668 opt/memo: extend OutputCols with VirtualCols in statistics builder
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/bench/bench_test.go
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/exec/execbuilder/testdata/explain_redact
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/memo
  pkg/sql/opt/memo/testdata/stats/virtual
  pkg/sql/opt/optbuilder/builder_test.go
  pkg/sql/opt/props/statistics.go
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/testdata/physprops/ordering
  pkg/sql/opt/xform/testdata/rules/cycle
  pkg/sql/opt/xform/testdata/rules/groupby
  pkg/sql/opt/xform/testdata/rules/join
  pkg/sql/opt/xform/testdata/rules/join_order
  pkg/sql/opt/xform/testdata/rules/limit
  pkg/sql/opt/xform/testdata/rules/select
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/testdata/session_migration/prepared_statements
  pkg/sql/vars.go
Labels: backport-23.1.x, backport-23.2.x

#120913 release-23.2: util/mon: remove somewhat redundant numChildren field
  pkg/testutils/lint/gcassert_paths.txt
  pkg/util/mon/bytes_usage.go
Labels: backport-23.1.x, backport, backport-23.1.18-rc, backport-23.2.4-rc

#120570 kvserver: create LinkExternalSSTRequest kv rpc
  docs/generated/metrics/metrics.html
  pkg/ccl/backupccl/restore_online.go
  pkg/kv/batch.go
  pkg/kv/db.go
  pkg/kv/kvpb/api.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvpb/batch_generated.go
  pkg/kv/kvpb/method.go
  pkg/kv/kvpb/method_string.go
  pkg/kv/kvserver/app_batch.go
  pkg/kv/kvserver/batcheval/BUILD.bazel
  pkg/kv/kvserver/batcheval/cmd_add_sstable.go
  pkg/kv/kvserver/batcheval/cmd_link_external_sstable.go
  pkg/kv/kvserver/batcheval/result/result.go
  pkg/kv/kvserver/client_merge_test.go
  pkg/kv/kvserver/kvserverpb/proposer_kv.proto
  pkg/kv/kvserver/raftlog/payload.go
  pkg/kv/kvserver/replica_app_batch.go
  pkg/kv/kvserver/replica_proposal.go
  pkg/multitenant/tenantcapabilities/tenantcapabilitiesauthorizer/authorizer.go
Labels: T-disaster-recovery

#118841 release-23.2: roachprod: create MIG clusters on GCE
  pkg/roachprod/vm/gce/BUILD.bazel
  pkg/roachprod/vm/gce/gcloud.go
Labels: backport

#121022 roachtest: increase allocbench timeout
  pkg/cmd/roachtest/tests/allocation_bench.go
Labels: backport-23.1.x, backport-23.2.x

#121060 release-23.2.4-rc: released CockroachDB version 23.2.3. Next version: 23.2.4
  pkg/build/version.txt
Labels: backport

#121061 release-23.2: released CockroachDB version 23.2.3. Next version: 23.2.4
  pkg/build/version.txt
Labels: backport

#121076 release-23.1.18-rc: released CockroachDB version 23.1.17. Next version: 23.1.18
  pkg/build/version.txt
Labels: backport

#121077 release-23.1: released CockroachDB version 23.1.17. Next version: 23.1.18
  pkg/build/version.txt
Labels: backport

#120600 backupccl: allow for empty database and schema only online restore
  pkg/ccl/backupccl/backuprand/backup_rand_test.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_online.go
  pkg/ccl/backupccl/restore_online_test.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/ccl/backupccl/testdata/backup-restore/online-restore-empty-database
  pkg/jobs/jobspb/jobs.proto
Labels: T-disaster-recovery

#120875 opt/memo: use virtual column stats for matching scalar expressions
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/stats/virtual
  pkg/sql/opt/norm/factory.go
Labels: backport-23.1.x, backport-23.2.x

#121051 build: validate release branch before running roachtest nightly
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_azure.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
Labels: backport-23.1.x, backport-23.2.x, backport-23.1.18-rc, backport-23.2.4-rc

#121121 release-23.2: build: validate release branch before running roachtest nightly
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_azure.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
Labels: backport

#121123 release-23.1: build: validate release branch before running roachtest nightly
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
Labels: backport

#121125 release-23.2.4-rc: build: validate release branch before running roachtest nightly
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_azure.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
Labels: backport

#121124 release-23.1.18-rc: build: validate release branch before running roachtest nightly
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
Labels: backport

#121163 rowexec: prevent panics with UDFs in edge cases
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/rowenc/encoded_datum.go
  pkg/sql/rowexec/project_set.go
Labels: backport-23.2.x

#121135 release-23.2: sqlinstance: ensure that session expiration is up to date
  pkg/server/server_sql.go
  pkg/sql/sqlinstance/instancestorage/BUILD.bazel
  pkg/sql/sqlinstance/instancestorage/instancecache_test.go
  pkg/sql/sqlinstance/instancestorage/instancereader_test.go
  pkg/sql/sqlinstance/instancestorage/instancestorage.go
  pkg/sql/sqlinstance/instancestorage/instancestorage_internal_test.go
  pkg/sql/sqlinstance/instancestorage/instancestorage_test.go
Labels: backport

#121216 release-23.1: tests: skip some tests under `race`
  pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/BUILD.bazel
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go
  pkg/kv/kvserver/client_metrics_test.go
  pkg/kv/kvserver/client_replica_circuit_breaker_test.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/parallel_test.go
Labels: backport

#121171 opt/memo: fix optimizer_use_virtual_computed_column_stats
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/opt/memo/statistics_builder.go
Labels: backport-23.1.x, backport-23.2.x

#120923 release-23.2: sql: collect table statistics on virtual computed columns
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/create_stats.go
  pkg/sql/distsql_physical_planner.go
  pkg/sql/distsql_plan_stats.go
  pkg/sql/distsql_spec_exec_factory.go
  pkg/sql/importer/import_job.go
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/opt/exec/execbuilder/testdata/distsql_misc
Labels: backport

#121244 sql: make cluster_locks.isolation_level nullable
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
Labels: backport-23.2.x

#120830 ui: add licensing notification to Db Console
  pkg/server/server_test.go
  pkg/ui/ui.go
  pkg/ui/workspaces/cluster-ui/src/util/dataFromServer.ts
  pkg/ui/workspaces/db-console/src/redux/alerts.ts
  pkg/ui/workspaces/db-console/src/redux/state.ts
  pkg/ui/workspaces/db-console/src/util/dataFromServer.ts
  pkg/ui/workspaces/db-console/src/util/docs.ts
  pkg/ui/workspaces/db-console/src/views/app/containers/layout/index.tsx
  pkg/ui/workspaces/db-console/src/views/app/containers/licenseNotification/licenseNotification.module.styl
  pkg/ui/workspaces/db-console/src/views/app/containers/licenseNotification/licenseNotification.tsx
  pkg/util/log/BUILD.bazel
  pkg/util/log/flags.go
  pkg/util/log/redact_test.go
Labels: O-community

#121230 release-23.1: roachtest/mixedversion: wrap original errors in test failures
  go.mod
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
Labels: backport

#121231 release-23.2: roachtest/mixedversion: wrap original errors in test failures
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
Labels: backport

#121280 release-23.1: mixedversion: introduce cluster setting mutator
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/cluster_setting
Labels: backport

#121282 release-23.2: mixedversion: introduce cluster setting mutator
  pkg/cmd/roachtest/roachtestutil/mixedversion/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mutators_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/cluster_setting
Labels: backport

#121109 sql: make tail-call optimization work with nested routines
  pkg/ccl/logictestccl/testdata/logic_test/explain_call_plpgsql
  pkg/ccl/logictestccl/testdata/logic_test/nested_routines
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-disk/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist-disk/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist/generated_test.go
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/generated_test.go
  pkg/ccl/logictestccl/tests/local-read-committed/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-read-committed/generated_test.go
  pkg/ccl/logictestccl/tests/local-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/local/BUILD.bazel
  pkg/ccl/logictestccl/tests/local/generated_test.go
  pkg/sql/opt/exec/execbuilder/builder.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/scalar.go
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/memo/extract.go
  pkg/sql/opt/memo/testdata/logprops/tail-calls
  pkg/sql/opt/norm/decorrelate_funcs.go
  pkg/sql/opt/norm/testdata/rules/routine
  pkg/sql/opt/ops/scalar.opt
  pkg/sql/opt/optbuilder/plpgsql.go
  pkg/sql/opt/optbuilder/routine.go
  pkg/sql/opt/optbuilder/testdata/procedure_plpgsql
  pkg/sql/opt/optbuilder/testdata/udf_plpgsql
  pkg/sql/routine.go
  pkg/sql/sem/eval/deps.go
Labels: backport-24.1.x

#121215 release-23.2: tests: skip some tests under `race`
  pkg/ccl/kvccl/kvfollowerreadsccl/boundedstaleness_test.go
  pkg/ccl/kvccl/kvtenantccl/upgradeinterlockccl/testgen/template.go
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/BUILD.bazel
  pkg/ccl/spanconfigccl/spanconfigsqltranslatorccl/datadriven_test.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/kv/kvserver/client_metrics_test.go
  pkg/kv/kvserver/client_raft_test.go
  pkg/kv/kvserver/client_replica_circuit_breaker_test.go
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/parallel_test.go
Labels: backport

#121279 rpc: expect eventual connection in remote offset unhealthy test
  pkg/rpc/context_test.go
Labels: backport-23.2.x, backport-24.1.x

#121219 workload/schemachange: support UDFs invoking other UDFs
  pkg/sql/logictest/testdata/logic_test/udf_calling_udf
  pkg/sql/pg_catalog.go
  pkg/workload/schemachange/error_screening.go
  pkg/workload/schemachange/operation_generator.go
  pkg/workload/schemachange/query_util.go
Labels: backport-24.1.x

#116454 release-23.1: roachtest: move decl_schema_change/job-compat to new framework
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/mixed_version_backup.go
  pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go
Labels: backport

#121305 sqlstats: remove allocation of anonymous function
  pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go
  pkg/sql/sqlstats/ssmemstorage/ss_mem_storage.go
  pkg/sql/sqlstats/ssprovider.go
Labels: backport-24.1.x

#121271 storage: increase default for MaxConcurrentDownloads
  pkg/storage/open.go
  pkg/storage/pebble.go
Labels: backport-24.1.x

#120933 release-23.2.4-rc: sql: collect table statistics on virtual computed columns
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/create_stats.go
  pkg/sql/distsql_physical_planner.go
  pkg/sql/distsql_plan_stats.go
  pkg/sql/distsql_spec_exec_factory.go
  pkg/sql/importer/import_job.go
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/opt/exec/execbuilder/testdata/distsql_misc
Labels: backport

#121237 release-23.2: sql: Allow dropping enum value when referenced by UDF
  pkg/sql/BUILD.bazel
  pkg/sql/type_change.go
  pkg/sql/type_change_test.go
  pkg/workload/schemachange/optype.go
Labels: backport

#121359 changefeedccl: deflake TestAlterChangefeedAddTargetsDuringBackfill
  pkg/ccl/changefeedccl/helpers_test.go
Labels: backport-24.1.x

#120921 release-23.1: util/mon: remove somewhat redundant numChildren field
  pkg/testutils/lint/gcassert_paths.txt
  pkg/util/mon/bytes_usage.go
Labels: backport, backport-23.1.18-rc

#121287 demo: make demo MT default only on dev branch
  pkg/cli/context.go
  pkg/clusterversion/cockroach_versions.go
  pkg/clusterversion/cockroach_versions_test.go
  pkg/clusterversion/dev_offset.go
Labels: backport-24.1.x

#121179 release-23.2: opt/memo: use virtual column stats in statistics builder
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/explain_redact
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/memo
  pkg/sql/opt/memo/testdata/stats/virtual
  pkg/sql/opt/norm/factory.go
  pkg/sql/opt/props/statistics.go
  pkg/sql/opt/xform/testdata/physprops/ordering
  pkg/sql/opt/xform/testdata/rules/groupby
  pkg/sql/opt/xform/testdata/rules/join
  pkg/sql/opt/xform/testdata/rules/join_order
  pkg/sql/opt/xform/testdata/rules/limit
  pkg/sql/opt/xform/testdata/rules/select
  pkg/sql/opt/xform/testdata/rules/set
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/testdata/session_migration/prepared_statements
  pkg/sql/vars.go
Labels: backport

#121329 release-23.2.4-rc: opt/memo: use virtual column stats in statistics builder
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/explain_redact
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/memo
  pkg/sql/opt/memo/testdata/stats/virtual
  pkg/sql/opt/norm/factory.go
  pkg/sql/opt/props/statistics.go
  pkg/sql/opt/xform/testdata/physprops/ordering
  pkg/sql/opt/xform/testdata/rules/groupby
  pkg/sql/opt/xform/testdata/rules/join
  pkg/sql/opt/xform/testdata/rules/join_order
  pkg/sql/opt/xform/testdata/rules/limit
  pkg/sql/opt/xform/testdata/rules/select
  pkg/sql/opt/xform/testdata/rules/set
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/testdata/session_migration/prepared_statements
  pkg/sql/vars.go
Labels: backport

#121333 execbuilder: only apply implicit for-update locking to mutation input
  pkg/sql/opt/exec/execbuilder/builder.go
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/update
  pkg/sql/opt/exec/execbuilder/testdata/upsert
Labels: backport-24.1.x

#121376 schemachanger: handle CREATE SEQUENCE name conflicts with geo type
  pkg/sql/create_table.go
  pkg/sql/logictest/testdata/logic_test/sequences
  pkg/sql/schemachanger/scbuild/builder_state.go
Labels: backport-24.1.x

#121379 sql/schemachanger: add fallback for temp sequences
  pkg/sql/create_table.go
  pkg/sql/logictest/testdata/logic_test/sequences
  pkg/sql/schemachanger/scbuild/builder_state.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/BUILD.bazel
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_sequence.go
Labels: backport-24.1.x

#121162 sql: fix handling CALL of procedures with TxnControlExpr
  pkg/ccl/logictestccl/testdata/logic_test/explain_call_plpgsql
  pkg/ccl/logictestccl/testdata/logic_test/procedure_plpgsql
  pkg/cmd/roachtest/tests/pgjdbc_blocklist.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/scalar.go
  pkg/sql/opt/exec/execbuilder/testdata/call
  pkg/sql/opt/memo/logical_props_builder.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/logprops/call
  pkg/sql/opt/norm/factory.go
  pkg/sql/opt/norm/testdata/rules/routine
  pkg/sql/opt/ops/scalar.opt
  pkg/sql/opt/ops/statement.opt
  pkg/sql/opt/optbuilder/create_function.go
  pkg/sql/opt/optbuilder/plpgsql.go
  pkg/sql/opt/optbuilder/project.go
  pkg/sql/opt/optbuilder/routine.go
  pkg/sql/opt/optbuilder/testdata/procedure_plpgsql
  pkg/sql/pgwire/conn.go
  pkg/sql/pgwire/testdata/pgtest/procedure
  pkg/sql/routine.go
Labels: backport-24.1.x

#119345 kv: verify roachpb.Value checksums when building snapshots
  pkg/kv/kvserver/store_snapshot.go
  pkg/storage/engine_key.go
  pkg/storage/engine_key_test.go
Labels: O-community, X-blathers-triaged
