Repository cockroachdb/cockroach, pull requests merged in 2024-04, with the labels that each got.

#121403 optbuilder: subject SELECT FOR UPDATE to sql_safe_updates
  pkg/cli/interactive_tests/test_sql_safe_updates.tcl
  pkg/sql/logictest/testdata/logic_test/dangerous_statements
  pkg/sql/opt/optbuilder/delete.go
  pkg/sql/opt/optbuilder/locking.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/update.go
Labels: backport-24.1.x

#121472 release-24.1: released CockroachDB version 24.1.0-alpha.5. Next version: 24.1.0-alpha.6
  pkg/build/version.txt
Labels: backport

#121461 release-24.1: pkg/ui: properly derive XScale in statement details page
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
Labels: backport

#121458 kv: give savepoints distinct start and end sequence numbers
  pkg/kv/kvclient/kvcoord/testdata/savepoints
  pkg/kv/kvclient/kvcoord/txn_coord_sender_savepoints.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator_test.go
Labels: backport-24.1.x

#121456 ui: use dot as a milliseconds delimiter in time formatting
  pkg/ui/workspaces/cluster-ui/src/util/format.ts
Labels: O-community

#121363 kvserver: skip promo non-voter in add voter under deadlock
  pkg/kv/kvserver/replicate_queue_test.go
Labels: backport-24.1.x

#121493 release-23.2: sql: use correct context when hydrating type desc
  pkg/sql/crdb_internal.go
  pkg/sql/information_schema.go
  pkg/sql/pg_catalog.go
Labels: backport

#121559 release-24.1: go.mod: bump Pebble to 888a1185f73a
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#121556 logictest: revert incorrect test assertion update
  pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant
Labels: backport-24.1.x

#121315 coldata: batch-allocate columns of the same type
  pkg/bench/bench_test.go
  pkg/col/coldata/BUILD.bazel
  pkg/col/coldata/batch.go
  pkg/col/coldata/batch_test.go
  pkg/col/coldata/datum_vec.go
  pkg/col/coldata/nulls.go
  pkg/col/coldata/vec.go
  pkg/col/coldataext/datum_vec.go
  pkg/col/coldataext/extended_column_factory.go
Labels: backport-24.1.x

#121552 workload/schemachange: fix deadlock between watch dogs and workers
  pkg/workload/schemachange/schemachange.go
Labels: backport-24.1.x

#121088 kv: pipeline replicated lock acquisition
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/kv/kvpb/api.go
  pkg/kv/kvpb/api_test.go
  pkg/kv/kvpb/batch_test.go
  pkg/kv/kvserver/replica_raft.go
  pkg/kv/kvserver/txnrecovery/BUILD.bazel
  pkg/kv/kvserver/txnrecovery/manager.go
  pkg/roachpb/data.proto
  pkg/sql/conn_executor_exec.go
  pkg/sql/row/kv_batch_fetcher.go
Labels: branch-release-24.1

#121698 roachprod: remove abrupt exit when distributing certs
  pkg/roachprod/install/cluster_synced.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#121499 lint: fix `gcassert`
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/testutils/lint/lint_test.go
Labels: backport-24.1.x

#121716 release-23.1: roachprod: remove abrupt exit when distributing certs
  pkg/roachprod/install/BUILD.bazel
  pkg/roachprod/install/cluster_synced.go
Labels: backport

#121725 release-24.1: roachprod: remove abrupt exit when distributing certs
  pkg/roachprod/install/BUILD.bazel
  pkg/roachprod/install/cluster_synced.go
Labels: backport

#121778 kv: auto-step read sequence on savepoint rollback
  pkg/kv/kvclient/kvcoord/txn_coord_sender_savepoints.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator_test.go
Labels: backport-24.1.x

#121744 release-23.2: util/mon: add cluster setting for disabling monitor tree tracking
  pkg/util/mon/BUILD.bazel
  pkg/util/mon/bytes_usage.go
Labels: backport

#121783 release-23.1.18-rc: pkg/ui: properly derive XScale in statement details page
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
Labels: backport

#121789 kv: shallow copy {,Reverse}ScanResponse.{BatchResponses,ColBatches} when pipelining
  pkg/kv/kvpb/api.go
Labels: backport-24.1.x

#117661 roachtest: expand support for metamorphic arm64 runs in CI
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_aws_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh
  build/teamcity/util/roachtest_util.sh
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/test_runner.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/install.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#121481 workflows: make `acceptance`, `lint` GitHub Actions jobs mandatory
  .github/bors.toml
  .github/workflows/github-actions-essential-ci.yml
  build/teamcity/cockroach/ci/tests/acceptance.sh
  build/teamcity/cockroach/ci/tests/lint.sh
  build/teamcity/cockroach/ci/tests/lint_impl.sh
Labels: backport-24.1.x

#121802 backupccl: deflake desc id dependent tests
  pkg/ccl/backupccl/testdata/backup-restore/import-epoch
  pkg/ccl/backupccl/testdata/backup-restore/restore-schema-only
Labels: T-disaster-recovery, backport-24.1.x

#121800 stop: avoid logging race in Stopper.Quiesce
  pkg/util/stop/BUILD.bazel
  pkg/util/stop/stopper.go
Labels: backport-24.1.x

#121857 sql: run tenant logic tests with manual replication mode
  pkg/ccl/logictestccl/testdata/logic_test/cluster_locks_tenant
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/distsql_tenant_locality
  pkg/sql/opt/exec/execbuilder/testdata/distsql_tenant_locality
Labels: backport-24.1.x

#121847 sql: fix leak in memory accounting around TxnFingerprintIDCache
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/txn_fingerprint_id_cache.go
  pkg/sql/txn_fingerprint_id_cache_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-23.1.18-rc, backport-23.2.4-rc, backport-24.1.x

#121693 codeowners: update all obs links to use `obs-prs`
  .github/CODEOWNERS
  TEAMS.yaml
  pkg/cmd/roachtest/registry/owners.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/kv.go
  pkg/cmd/roachtest/tests/network_logging.go
  pkg/internal/team/TEAMS.yaml
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#120918 concurrency: include promotion information when printing out locks
  pkg/kv/kvserver/concurrency/lock_table.go
  pkg/kv/kvserver/concurrency/lock_table_test.go
  pkg/kv/kvserver/concurrency/testdata/lock_table/lock_promotion
  pkg/kv/kvserver/concurrency/testdata/lock_table/replicated_locks
Labels: backport-24.1.x

#121816 schemachange/leasing-benchmark: fix benchmark test flakiness
  pkg/cmd/roachtest/tests/multiregion_leasing.go
Labels: backport-24.1.x

#121840 kv: fix rare deadlock between requests in the lock table
  pkg/kv/kvserver/concurrency/lock_table.go
  pkg/kv/kvserver/concurrency/testdata/lock_table/lock_promotion
Labels: backport-24.1.x

#121865 release-23.1: roachtest: ignore 2 flaky ruby-pg tests and 1 flaky pgjdbc test
  pkg/cmd/roachtest/tests/pgjdbc_blocklist.go
  pkg/cmd/roachtest/tests/ruby_pg_blocklist.go
Labels: backport

#121864 release-23.2: roachtest: ignore 2 flaky ruby-pg tests and 1 flaky pgjdbc test
  pkg/cmd/roachtest/tests/pgjdbc_blocklist.go
  pkg/cmd/roachtest/tests/ruby_pg_blocklist.go
Labels: backport

#121928 admission: increase sleep in testGranter.grant for test determinism
  pkg/util/admission/work_queue_test.go
Labels: backport-24.1.x

#121874 release-23.1.18-rc: sql: fix leak in memory accounting around TxnFingerprintIDCache
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/txn_fingerprint_id_cache.go
  pkg/sql/txn_fingerprint_id_cache_test.go
Labels: backport

#121875 release-23.2.4-rc: sql: fix leak in memory accounting around TxnFingerprintIDCache
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/txn_fingerprint_id_cache.go
  pkg/sql/txn_fingerprint_id_cache_test.go
Labels: backport

#121904 colexec: fix evaluation of the IN expression with INT2 and INT4 types
  pkg/sql/colexec/execgen/cmd/execgen/select_in_gen.go
  pkg/sql/colexec/select_in.eg.go
  pkg/sql/colexec/select_in_tmpl.go
  pkg/sql/logictest/testdata/logic_test/select
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#121901 release-23.1: roachtest: ignore injected error in sqlsmith in some cases
  pkg/cmd/roachtest/tests/sqlsmith.go
Labels: backport

#121900 release-23.2: roachtest: ignore injected error in sqlsmith in some cases
  pkg/cmd/roachtest/tests/sqlsmith.go
Labels: backport

#121899 release-24.1: roachtest: ignore injected error in sqlsmith in some cases
  pkg/cmd/roachtest/tests/sqlsmith.go
Labels: backport

#121948 cli: deflake TestLossOfQuorumRecovery
  pkg/cli/debug_recover_loss_of_quorum_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#121964 workflows: surface error messages better for check generated code job
  build/github/check-generated-code.sh
Labels: backport-24.1.x

#121977 teamcity: remove extraneous docker image scripts
  build/teamcity/cockroach/ci/builds/build_docker_image.sh
  build/teamcity/cockroach/ci/builds/build_docker_image_arm64.sh
  build/teamcity/cockroach/ci/builds/build_docker_image_x86_64.sh
Labels: backport-24.1.x

#121952 cli: conditionally allow version skipping
  pkg/ccl/backupccl/restore_planning_test.go
  pkg/cli/context.go
  pkg/cli/debug_test.go
  pkg/clusterversion/clusterversion.go
  pkg/server/profiler/BUILD.bazel
  pkg/server/profiler/activequeryprofiler_test.go
  pkg/server/profiler/cpuprofile_test.go
  pkg/settings/cluster/cluster_settings.go
  pkg/sql/logictest/logic.go
Labels: backport-24.1.x

#120786 rpc,security, cli: Add cert-distinguished-name root/node cli flag
  build/github/acceptance-test.sh
  pkg/acceptance/BUILD.bazel
  pkg/acceptance/generated_cli_test.go
  pkg/acceptance/util_docker.go
  pkg/cli/cliflags/flags.go
  pkg/cli/context.go
  pkg/cli/flags.go
  pkg/cli/interactive_tests/test_distinguished_name_validation.tcl
  pkg/rpc/auth.go
  pkg/rpc/auth_test.go
  pkg/security/auth.go
  pkg/security/auth_test.go
  pkg/sql/roleoption/BUILD.bazel
  pkg/sql/roleoption/role_option.go
Labels: backport-24.1.x

#121946 workload: skip TestRandRun under duress
  pkg/workload/rand/BUILD.bazel
  pkg/workload/rand/rand_test.go
Labels: backport-24.1.x

#121936 loqrecovery: fix port reuse in TestReplicaCollection
  pkg/kv/kvserver/loqrecovery/server_integration_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#121813 release-23.1: roachtest: expand support for metamorphic arm64 runs in CI
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_aws_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh
  build/teamcity/util/roachtest_util.sh
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/test_runner.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/install.go
Labels: backport

#121812 release-23.2: roachtest: expand support for metamorphic arm64 runs in CI
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_aws_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh
  build/teamcity/util/roachtest_util.sh
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/test_runner.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/install.go
Labels: backport

#121955 release-23.1: colexec: fix evaluation of the IN expression with INT2 and INT4 types
  pkg/sql/colexec/execgen/cmd/execgen/select_in_gen.go
  pkg/sql/colexec/select_in.eg.go
  pkg/sql/colexec/select_in_tmpl.go
  pkg/sql/logictest/testdata/logic_test/select
Labels: backport

#122015 release-23.2: workload/schemachange: fix deadlock between watch dogs and workers
  pkg/workload/schemachange/schemachange.go
Labels: backport

#122047 roachtest: work around T2A limitations
  pkg/cmd/roachtest/cluster.go
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#122042 sql: remove an allocation in checkScanParallelizationIfLocal
  pkg/sql/distsql_physical_planner.go
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/planner.go
Labels: backport-24.1.x

#122046 application_api: run on `heavy` pool under `race`
  pkg/server/application_api/BUILD.bazel
Labels: backport-24.1.x

#121965 kvserver: fix CT regressions in reproposal tests
  pkg/kv/kvnemesis/kvnemesis_test.go
  pkg/kv/kvserver/replica_proposal_buf.go
Labels: backport-23.2.x, backport-24.1.x

#122051 roachtest: enable vmodule logging in tpcc-nowait/isolation-level=mixed/nodes=3/w=1
  pkg/cmd/roachtest/tests/tpcc.go
Labels: backport-24.1.x

#121275 mixedversion: enable experimental cluster settings
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go
Labels: backport-24.1.x

#122074 release-23.1: roachtest: work around T2A limitations
  pkg/cmd/roachtest/cluster.go
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport

#122072 release-24.1: roachtest: work around T2A limitations
  pkg/cmd/roachtest/cluster.go
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport

#122075 concurrency: correctly handle replay attempts from SKIP LOCKED requests
  pkg/kv/kvnemesis/applier.go
  pkg/kv/kvnemesis/validator.go
  pkg/kv/kvserver/concurrency/lock_table.go
  pkg/kv/kvserver/concurrency/testdata/lock_table/skip_locked
Labels: backport-24.1.x

#122090 release-23.2: roachprod: account for cost of boot partition
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/vm.go
Labels: backport

#122017 roachtest: orm tests install correct binary based on architecture
  pkg/cmd/roachtest/tests/go_helpers.go
  pkg/cmd/roachtest/tests/knex.go
  pkg/cmd/roachtest/tests/npgsql.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#121850 kv: do not overwrite Transaction fields not present in TransactionRecord
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/txn_test.go
  pkg/roachpb/data.go
  pkg/roachpb/data_test.go
Labels: backport-23.2.x, backport-24.1.x

#122056 concurrency: add lock table verification for lock promotion state
  pkg/kv/kvserver/concurrency/lock_table.go
Labels: backport-24.1.x

#122187 roachtest: run rebalance/by-load/*/mixed-version on insecure mode
  pkg/cmd/roachtest/tests/rebalance_load.go
Labels: backport-24.1.x

#122196 release: pick SHA should work for baking and extraordinary releases
  pkg/cmd/release/git.go
Labels: C-enhancement, A-release, T-release, backport-23.1.x, backport-23.2.x, backport-24.1.x

#122152 kvserver: add storage.sstable.zombie.bytes metric
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
Labels: backport-24.1.x

#122217 workflows: don't re-run GitHub Actions CI on `edited` event
  .github/workflows/github-actions-essential-ci.yml
Labels: backport-24.1.x

#122203 release-23.1: roachtest: orm tests install correct binary based on architecture
  pkg/cmd/roachtest/tests/go_helpers.go
  pkg/cmd/roachtest/tests/knex.go
  pkg/cmd/roachtest/tests/npgsql.go
Labels: backport

#122227 release-23.2: released CockroachDB version 23.2.4. Next version: 23.2.5
  pkg/build/version.txt
Labels: backport

#122234 release-23.1: released CockroachDB version 23.1.18. Next version: 23.1.19
  pkg/build/version.txt
Labels: backport

#122212 roachtest: make lease benchmark test more stable
  pkg/cmd/roachtest/tests/multiregion_leasing.go
  pkg/cmd/roachtest/tests/multitenant.go
Labels: backport-24.1.x

#121290 release-24.1: clusterversion: set devBranch to false, version to beta.1
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/build/version.txt
  pkg/cli/context.go
  pkg/cli/testdata/declarative-rules/deprules
  pkg/cli/testdata/declarative-rules/invalid_version
  pkg/clusterversion/cockroach_versions.go
  pkg/server/migration_test.go
  pkg/sql/catalog/bootstrap/bootstrap_test.go
  pkg/sql/catalog/bootstrap/testdata/testdata
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_system
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_tenant
  pkg/sql/catalog/tabledesc/validate_version_gating_test.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/storage/open_test.go
  pkg/upgrade/upgrades/v23_2_plan_gist_stmt_diagnostics_requests_test.go
Labels: backport

#122207 workload: add --conn-vars flag to all workloads
  pkg/ccl/backupccl/tenant_backup_nemesis_test.go
  pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go
  pkg/ccl/workloadccl/roachmartccl/roachmart.go
  pkg/cli/democluster/demo_cluster.go
  pkg/workload/bank/bank.go
  pkg/workload/bulkingest/bulkingest.go
  pkg/workload/cli/run.go
  pkg/workload/connection.go
  pkg/workload/connectionlatency/connectionlatency.go
  pkg/workload/indexes/indexes.go
  pkg/workload/insights/insights.go
  pkg/workload/jsonload/json.go
  pkg/workload/kv/kv.go
  pkg/workload/ledger/ledger.go
  pkg/workload/movr/movr.go
  pkg/workload/movr/workload.go
  pkg/workload/querybench/query_bench.go
  pkg/workload/querylog/querylog.go
  pkg/workload/queue/queue.go
  pkg/workload/rand/rand.go
  pkg/workload/schemachange/schemachange.go
  pkg/workload/sqlsmith/sqlsmith.go
  pkg/workload/sqlstats/sqlstats.go
  pkg/workload/tpcc/tpcc.go
  pkg/workload/tpccchecks/checks_generator.go
  pkg/workload/tpcds/tpcds.go
  pkg/workload/tpch/tpch.go
  pkg/workload/ttlbench/ttlbench.go
  pkg/workload/ttllogger/ttllogger.go
  pkg/workload/workload.go
  pkg/workload/ycsb/ycsb.go
Labels: backport-24.1.x

#122194 streamproducer: don't require rangefeeds be enabled
  pkg/ccl/streamingccl/streamproducer/stream_lifetime.go
Labels: backport-24.1.x

#121930 release-24.1: backupccl: include relevant information in online restore return statement
  pkg/ccl/backupccl/backuprand/backup_rand_test.go
  pkg/ccl/backupccl/backuptestutils/testutils.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_online.go
  pkg/ccl/backupccl/restore_online_test.go
  pkg/ccl/backupccl/restore_planning.go
  pkg/cloud/nodelocal/test_nodelocal_storage.go
  pkg/jobs/resultcols.go
Labels: backport

#122172 release-23.2: release: merge baking branch to the release branch
  build/teamcity/internal/cockroach/release/process/update_versions_impl.sh
  pkg/cmd/release/update_versions.go
Labels: backport

#122242 roachtest: use durable locking in tpcc-nowait/isolation-level=mixed
  pkg/cmd/roachtest/tests/tpcc.go
Labels: backport-24.1.x

#121861 release-24.1: sql/stats: improve query to ensure all tables
  pkg/sql/stats/automatic_stats.go
  pkg/sql/stats/automatic_stats_test.go
Labels: backport

#122239 release-23.2: roachprod: better identification of transient failures
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/test_impl.go
  pkg/cmd/roachtest/test_impl_test.go
  pkg/cmd/roachtest/testdata/help_command_createpost_10.txt
  pkg/cmd/roachtest/tests/activerecord.go
  pkg/cmd/roachtest/tests/django.go
  pkg/cmd/roachtest/tests/gopg.go
  pkg/cmd/roachtest/tests/nodejs_postgres.go
  pkg/cmd/roachtest/tests/npgsql.go
  pkg/cmd/roachtest/tests/pgx.go
  pkg/cmd/roachtest/tests/psycopg.go
  pkg/cmd/roachtest/tests/ruby_pg.go
  pkg/cmd/roachtest/tests/sqlalchemy.go
  pkg/roachprod/errors/errors.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/install.go
  pkg/roachprod/install/services.go
  pkg/roachprod/install/session.go
  pkg/roachprod/install/staging.go
  pkg/roachprod/vm/gce/BUILD.bazel
  pkg/roachprod/vm/gce/dns.go
Labels: backport

#119616 opt: correctly reconcile column definition list with RECORD-returning UDFs
  pkg/ccl/logictestccl/testdata/logic_test/plpgsql_record
  pkg/ccl/logictestccl/testdata/logic_test/udf_params
  pkg/internal/sqlsmith/plpgsql.go
  pkg/internal/sqlsmith/relational.go
  pkg/sql/catalog/funcdesc/func_desc.go
  pkg/sql/logictest/testdata/logic_test/procedure
  pkg/sql/logictest/testdata/logic_test/procedure_params
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/logictest/testdata/logic_test/udf_record
  pkg/sql/opt/exec/execbuilder/testdata/call
  pkg/sql/opt/exec/execbuilder/testdata/udf
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/optbuilder/create_function.go
  pkg/sql/opt/optbuilder/plpgsql.go
  pkg/sql/opt/optbuilder/routine.go
  pkg/sql/opt/optbuilder/scalar.go
  pkg/sql/opt/optbuilder/srfs.go
  pkg/sql/opt/optbuilder/testdata/procedure
  pkg/sql/opt/optbuilder/testdata/udf
  pkg/sql/opt/testutils/testcat/function.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go
  pkg/sql/types/types.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#121862 release-23.2: sql/stats: improve query to ensure all tables
  pkg/sql/stats/automatic_stats.go
  pkg/sql/stats/automatic_stats_test.go
Labels: backport

#121863 release-23.1: sql/stats: improve query to ensure all tables
  pkg/sql/stats/automatic_stats.go
  pkg/sql/stats/automatic_stats_test.go
Labels: backport

#122007 backup: separate tenant spans in include_all_secondary_tenants
  pkg/ccl/backupccl/backup_job.go
  pkg/ccl/backupccl/restoration_data.go
  pkg/ccl/backupccl/restore_online.go
  pkg/ccl/backupccl/show_test.go
  pkg/sql/logictest/testdata/logic_test/cross_version_tenant_backup
  pkg/sql/logictest/tests/cockroach-go-testserver-23.2/BUILD.bazel
  pkg/sql/logictest/tests/cockroach-go-testserver-23.2/generated_test.go
  pkg/sql/schemachanger/comparator_generated_test.go
Labels: T-disaster-recovery, backport-24.1.x

#119655 roachtest: skip initialization on failure restarts
  pkg/cmd/roachtest/tests/failover.go
Labels: backport-24.1.x

#122313 stats: set the type resolver when dealing with virtual comp cols
  pkg/sql/create_stats.go
  pkg/sql/distsql_plan_stats.go
  pkg/sql/logictest/testdata/logic_test/stats
Labels: backport-23.2.x, backport-24.1.x

#122301 release-23.1: sql: add FORCE_INVERTED_INDEX hint
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/inverted_index
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/interner.go
  pkg/sql/opt/memo/interner_test.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/testdata/coster/scan
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/hints
  pkg/sql/parser/testdata/select_clauses
  pkg/sql/sem/tree/select.go
Labels: backport

#121996 backupccl: attempt to deflake TestBackupRestoreAppend
  pkg/ccl/backupccl/backup_test.go
Labels: backport-24.1.x

#122188 release-24.1: codeowners: update all obs links to use `obs-prs`
  .github/CODEOWNERS
  TEAMS.yaml
  pkg/cmd/roachtest/registry/owners.go
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/kv.go
  pkg/cmd/roachtest/tests/network_logging.go
  pkg/internal/team/TEAMS.yaml
Labels: backport

#122143 roachtest: deflake splits/load roachtests
  pkg/cmd/roachtest/tests/split.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#122105 rpc,security,sql,cli: Add subject_required cluster setting
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/cli/interactive_tests/test_distinguished_name_validation.tcl
  pkg/rpc/auth.go
  pkg/rpc/auth_test.go
  pkg/rpc/helpers_test.go
  pkg/security/BUILD.bazel
  pkg/security/auth.go
  pkg/security/auth_test.go
  pkg/security/cert_settings.go
  pkg/sql/pgwire/auth_methods.go
Labels: backport-24.1.x

#122171 release-24.1: release: merge baking branch to the release branch
  build/teamcity/internal/cockroach/release/process/update_versions_impl.sh
  pkg/cmd/release/update_versions.go
Labels: backport

#122289 roachtest: mark asyncpg tests as flaky instead of expected to fail
  pkg/cmd/roachtest/tests/asyncpg_blocklist.go
Labels: backport-23.2.x, backport-24.1.x

#122202 sqlliveness: extend expiration on insertion retries
  pkg/sql/sqlliveness/slinstance/BUILD.bazel
  pkg/sql/sqlliveness/slinstance/slinstance.go
  pkg/sql/sqlliveness/slinstance/slinstance_test.go
  pkg/sql/sqlliveness/slstorage/test_helpers.go
Labels: backport-23.2.x, backport-24.1.x

#122311 release-24.1: backup: dont flush file sink mid row
  pkg/ccl/backupccl/backup_job.go
  pkg/ccl/backupccl/backup_processor.go
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/file_sst_sink.go
  pkg/ccl/backupccl/file_sst_sink_test.go
  pkg/ccl/backupccl/restoration_data.go
  pkg/ccl/backupccl/restore_online.go
  pkg/ccl/backupccl/show_test.go
  pkg/keys/keys.go
  pkg/sql/logictest/testdata/logic_test/cross_version_tenant_backup
  pkg/sql/logictest/tests/cockroach-go-testserver-23.2/BUILD.bazel
  pkg/sql/logictest/tests/cockroach-go-testserver-23.2/generated_test.go
  pkg/sql/schemachanger/comparator_generated_test.go
Labels: backport

#121296 roachtest: update version of job compat mixed-version roachtest
  pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go
Labels: backport-24.1.x

#122378 backupccl: skip online restore variant of TestBackupRestoreRandomDataRountrips
  pkg/ccl/backupccl/backuprand/backup_rand_test.go
Labels: skipped-test, backport-24.1.x

#121973 opt: add GenerateTrigramSimilarityInvertedIndexScans rule
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/bench/bench_test.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/trigram_index
  pkg/sql/opt/invertedidx/BUILD.bazel
  pkg/sql/opt/invertedidx/inverted_index_expr.go
  pkg/sql/opt/invertedidx/inverted_index_expr_test.go
  pkg/sql/opt/invertedidx/trigram.go
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/logical_props_builder.go
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/stats/inverted-trigram
  pkg/sql/opt/props/histogram.go
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/rules/select.opt
  pkg/sql/opt/xform/select_funcs.go
  pkg/sql/opt/xform/testdata/rules/generate_trigram_similarity_inverted_index_scans
  pkg/sql/opt/xform/testdata/rules/select
  pkg/sql/sem/tree/datum.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#122321 plpgsql: fix exception handling for nested blocks
  pkg/ccl/logictestccl/testdata/logic_test/plpgsql_block
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/scalar.go
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/testdata/logprops/tail-calls
  pkg/sql/opt/optbuilder/plpgsql.go
  pkg/sql/opt/optbuilder/testdata/procedure_plpgsql
  pkg/sql/opt/optbuilder/testdata/udf_plpgsql
  pkg/sql/routine.go
  pkg/sql/sem/tree/routine.go
Labels: backport-24.1.x

#122373 intentresolver: serialize race in intent resolution test
  pkg/kv/kvserver/intentresolver/intent_resolver_integration_test.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#122295 release-24.1: streamingest: allow replicating system tenants to other tenants
  pkg/ccl/backupccl/key_rewriter.go
  pkg/ccl/streamingccl/replicationtestutils/testutils.go
  pkg/ccl/streamingccl/streamingest/ingest_span_configs.go
  pkg/ccl/streamingccl/streamingest/replication_stream_e2e_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_dist.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_planning.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor.go
  pkg/ccl/streamingccl/streamingest/stream_ingestion_processor_test.go
  pkg/ccl/streamingccl/streamproducer/producer_job.go
  pkg/sql/show_fingerprints.go
Labels: backport

#122160 backuppcl: add more testing around restoring wth skip-localities-check
  pkg/ccl/backupccl/testdata/backup-restore/multiregion
  pkg/ccl/backupccl/testdata/backup-restore/multiregion-mismatch-table-locality
Labels: T-disaster-recovery

#122448 roachprod: do use use ssh-rsa
  pkg/roachprod/vm/azure/utils.go
  pkg/roachprod/vm/gce/utils.go
Labels: C-bug, A-testing, T-testeng, backport-24.1.x

#122465 release-23.1: sqlstats: simplify transaction latency test
  pkg/sql/sqlstats/sslocal/sql_stats_test.go
Labels: backport

#122467 release-23.2: upgrade go to 1.21.9
  .bazelrc
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/teamcity/internal/release/build-and-publish-patched-go/impl-fips.sh
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
Labels: C-enhancement, A-build-system, T-dev-inf, backport

#122388 opt: allow OptSplitScanLimit to be set to zero
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/xform/general_funcs.go
Labels: backport-23.2.x, backport-24.1.x

#122476 roachtest: add cdc/tpcc-1000/sink=cloudstorage test
  pkg/cmd/roachtest/tests/cdc.go
Labels: backport-23.2.x, backport-24.1.x

#122392 kvserver: add testing for txn recovery involving pipelined repl locks
  pkg/kv/kvserver/txnrecovery/BUILD.bazel
  pkg/kv/kvserver/txnrecovery/manager_test.go
Labels: backport-24.1.x

#122477 restore: fix online restore of MR backups
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_online_test.go
Labels: backport-24.1.x

#121804 release-23.2: backupccl: add backup.restore_span.max_file_count cluster setting
  pkg/ccl/backupccl/bench_covering_test.go
  pkg/ccl/backupccl/generative_split_and_scatter_processor.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/restore_processor_planning.go
  pkg/ccl/backupccl/restore_span_covering.go
  pkg/ccl/backupccl/restore_span_covering_test.go
  pkg/cmd/roachtest/tests/restore.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
Labels: T-disaster-recovery, backport

#122464 streamingccl: skip TestTenantStreamingFailback on 23.2
  pkg/ccl/streamingccl/streamingest/stream_ingestion_job_test.go
Labels: T-disaster-recovery

#122300 release-23.2: sql: add FORCE_INVERTED_INDEX hint
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/inverted_index
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/interner.go
  pkg/sql/opt/memo/interner_test.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/testdata/coster/scan
  pkg/sql/parser/parse_test.go
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/create_table
  pkg/sql/parser/testdata/hints
  pkg/sql/parser/testdata/select_clauses
  pkg/sql/plpgsql/parser/parser_test.go
  pkg/sql/sem/tree/select.go
  pkg/testutils/sqlutils/parse.go
Labels: backport

#122230 release-23.1: sql: include stopped monitors into node_memory_monitors
  pkg/cli/zip_table_registry.go
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/util/mon/bytes_usage.go
  pkg/util/mon/bytes_usage_test.go
Labels: backport

#122223 release-23.2: sql: include stopped monitors into node_memory_monitors
  pkg/cli/zip_table_registry.go
  pkg/server/profiler/memory_monitoring_profiler.go
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/util/mon/bytes_usage.go
  pkg/util/mon/bytes_usage_test.go
Labels: backport

#122538 release-24.1: released CockroachDB version 24.1.0-beta.1. Next version: 24.1.0-beta.2
  pkg/build/version.txt
Labels: backport

#122440 gossip: remove race on client peer id
  pkg/gossip/client.go
Labels: backport-24.1.x

#122057 release-23.1: sql: grant to all tables did not skip privileges on sequences
  pkg/sql/grant_revoke.go
  pkg/sql/logictest/testdata/logic_test/grant_on_all_sequences_in_schema
  pkg/sql/resolver.go
Labels: backport

#122472 release-24.1: roachprod: flag to enable cron on GCE
  pkg/roachprod/vm/gce/gcloud.go
  pkg/roachprod/vm/gce/utils.go
Labels: backport

#122566 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#122562 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#122564 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#121273 kvclient: add a testing knob to stress proxy code
  pkg/ccl/multiregionccl/datadriven_test.go
  pkg/kv/BUILD.bazel
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvclient/kvcoord/testing_knobs.go
  pkg/kv/kvserver/client_merge_test.go
  pkg/kv/kvserver/client_replica_circuit_breaker_test.go
  pkg/kv/txn_external_test.go
Labels: A-testing, GA-blocker, T-kv, branch-release-24.1, backport-24.1.x

#122570 release-24.1: sql: add version gate for UDF invoking UDFs
  pkg/ccl/logictestccl/testdata/logic_test/plpgsql_block
  pkg/ccl/logictestccl/testdata/logic_test/procedure_params
  pkg/ccl/logictestccl/testdata/logic_test/udf_params
  pkg/ccl/logictestccl/testdata/logic_test/udf_rewrite
  pkg/sql/create_function.go
  pkg/sql/logictest/testdata/logic_test/drop_function
  pkg/sql/logictest/testdata/logic_test/procedure_params
  pkg/sql/logictest/testdata/logic_test/udf_calling_udf
  pkg/sql/logictest/testdata/logic_test/udf_oid_ref
  pkg/sql/logictest/testdata/logic_test/udf_params
  pkg/sql/logictest/testdata/logic_test/udf_rewrite
  pkg/sql/logictest/testdata/logic_test/udf_unsupported
  pkg/sql/logictest/tests/local-mixed-23.2/generated_test.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_function.go
  pkg/workload/schemachange/operation_generator.go
Labels: backport

#122624 release-24.1: pkg/sql/sqlstats: de-flake TestTransactionInsightsFailOnCommit
  pkg/sql/sqlstats/insights/integration/insights_test.go
Labels: backport

#122597 release-24.1: opt: allow OptSplitScanLimit to be set to zero
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/xform/general_funcs.go
Labels: backport

#122634 release-23.1: released CockroachDB version 23.1.19. Next version: 23.1.20
  pkg/build/version.txt
Labels: backport

#122442 opt: consider limit hint when costing distinct-on expressions
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/bench/bench_test.go
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/testdata/stats/select
  pkg/sql/opt/norm/testdata/rules/limit
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/testdata/coster/groupby
  pkg/sql/opt/xform/testdata/rules/limit
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#121855 release-23.2: import: add ability to disable validation checks
  pkg/ccl/importerccl/ccl_test.go
  pkg/sql/importer/import_job.go
Labels: backport

#122646 release: move release qualification buckets
  build/release/teamcity-mark-build.sh
  build/teamcity/internal/cockroach/release/process/pick_sha_impl.sh
Labels: C-enhancement, A-release, T-release, backport-23.1.x, backport-23.2.x, backport-24.1.x

#122649 build: reduce build triggering for crdb-api-client workflow
  .github/workflows/crdb-api-client-npm-publish.yml
Labels: O-community

#122668 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#122471 backupccl: allocate work on index level
  pkg/ccl/backupccl/backup_job.go
  pkg/ccl/backupccl/backup_processor_planning.go
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/backupinfo/manifest_handling.go
  pkg/ccl/backupccl/backuprand/backup_rand_test.go
  pkg/sql/distsql_physical_planner.go
  pkg/sql/distsql_physical_planner_test.go
Labels: T-disaster-recovery, backport-24.1.x

#122652 release-24.1: roachprod: don't overwrite local cluster cache if ListCloud failed
  pkg/roachprod/cloud/cluster_cloud.go
  pkg/roachprod/clusters_cache.go
  pkg/roachprod/roachprod.go
Labels: backport

#122653 release-23.2: roachprod: don't overwrite local cluster cache if ListCloud failed
  pkg/roachprod/cloud/cluster_cloud.go
  pkg/roachprod/clusters_cache.go
  pkg/roachprod/roachprod.go
Labels: backport

#122656 release-23.1: roachprod: don't overwrite local cluster cache if ListCloud failed
  pkg/roachprod/cloud/cluster_cloud.go
  pkg/roachprod/clusters_cache.go
  pkg/roachprod/roachprod.go
Labels: backport

#122551 docker: pass `COCKROACH_ARGS` without quoting
  build/deploy/cockroach.sh
Labels: C-bug, A-release, T-release

#122716 release-23.1: sqlsmith: add DisableNondeterministicLimits option
  pkg/cmd/roachtest/tests/query_comparison_util.go
  pkg/cmd/smith/main.go
  pkg/internal/sqlsmith/relational.go
  pkg/internal/sqlsmith/scalar.go
  pkg/internal/sqlsmith/sqlsmith.go
Labels: backport

#120432 ccl, cli,server, sql, testutils: fix IdMap setting + client cert auth
  pkg/ccl/multiregionccl/cold_start_latency_test.go
  pkg/cli/interactive_tests/test_cert_advisory_validation.tcl
  pkg/cli/interactive_tests/test_distinguished_name_validation.tcl
  pkg/cli/userfiletable_test.go
  pkg/server/testserver_sqlconn.go
  pkg/sql/pgwire/auth_methods.go
  pkg/sql/pgwire/auth_test.go
  pkg/sql/pgwire/testdata/auth/identity_map
  pkg/sql/user_test.go
  pkg/testutils/sqlutils/pg_url.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-23.1.20-rc, backport-23.2.5-rc

#122729 opt: fix costing of DistinctOn with limit hint
  pkg/sql/opt/memo/testdata/stats/select
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/physical_props.go
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-23.1.20-rc

#122721 sql: capture timeout settings in explain bundles
  pkg/sql/explain_bundle.go
  pkg/sql/opt/exec/execbuilder/testdata/explain_env
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x

#122683 release-23.1.20-rc: opt: add GenerateTrigramSimilarityInvertedIndexScans rule
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/invertedidx/BUILD.bazel
  pkg/sql/opt/invertedidx/inverted_index_expr.go
  pkg/sql/opt/invertedidx/inverted_index_expr_test.go
  pkg/sql/opt/invertedidx/trigram.go
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/logical_props_builder.go
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/stats/inverted-trigram
  pkg/sql/opt/props/histogram.go
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/rules/select.opt
  pkg/sql/opt/xform/select_funcs.go
  pkg/sql/opt/xform/testdata/rules/generate_trigram_similarity_inverted_index_scans
  pkg/sql/opt/xform/testdata/rules/select
  pkg/sql/sem/tree/datum.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#122453 sql: grant admin option repeatedly on role should not trigger schema change
  pkg/sql/grant_role.go
  pkg/sql/logictest/testdata/logic_test/grant_role
Labels: O-community

#122728 release-24.1: cli: debug pebble db excise command
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cli/debug.go
Labels: backport

#122747 release-23.1: ccl, cli,server, sql, testutils: fix IdMap setting + client cert auth
  pkg/ccl/multiregionccl/cold_start_latency_test.go
  pkg/ccl/testccl/authccl/auth_test.go
  pkg/cli/interactive_tests/test_cert_advisory_validation.tcl
  pkg/cli/userfiletable_test.go
  pkg/sql/copy/copy_in_test.go
  pkg/sql/pgwire/auth_methods.go
  pkg/sql/pgwire/auth_test.go
  pkg/sql/pgwire/conn_test.go
  pkg/sql/pgwire/testdata/auth/identity_map
  pkg/sql/tests/allow_role_memberships_to_change_during_transaction_test.go
  pkg/sql/tests/copy_file_upload_test.go
  pkg/sql/user_test.go
  pkg/testutils/sqlutils/pg_url.go
Labels: backport

#122749 release-23.2: ccl, cli,server, sql, testutils: fix IdMap setting + client cert auth
  pkg/ccl/multiregionccl/cold_start_latency_test.go
  pkg/cli/interactive_tests/test_cert_advisory_validation.tcl
  pkg/cli/userfiletable_test.go
  pkg/server/testserver_sqlconn.go
  pkg/sql/pgwire/auth_methods.go
  pkg/sql/pgwire/auth_test.go
  pkg/sql/pgwire/testdata/auth/identity_map
  pkg/sql/user_test.go
  pkg/testutils/sqlutils/pg_url.go
Labels: backport

#121004 security,sql,testutils,server,cli: Add testcases for client cert authentication.
  pkg/security/certificate_loader.go
  pkg/security/certificate_loader_test.go
  pkg/security/certificate_manager_test.go
  pkg/security/securitytest/securitytest.go
  pkg/security/securitytest/test_certs/ca-client-tenant.crt
  pkg/security/securitytest/test_certs/ca-client-tenant.key
  pkg/security/securitytest/test_certs/ca.cnf
  pkg/security/securitytest/test_certs/ca.crt
  pkg/security/securitytest/test_certs/ca.key
  pkg/security/securitytest/test_certs/client-tenant.10.crt
  pkg/security/securitytest/test_certs/client-tenant.10.key
  pkg/security/securitytest/test_certs/client-tenant.11.crt
  pkg/security/securitytest/test_certs/client-tenant.11.key
  pkg/security/securitytest/test_certs/client-tenant.2.crt
  pkg/security/securitytest/test_certs/client-tenant.2.key
  pkg/security/securitytest/test_certs/client-tenant.20.crt
  pkg/security/securitytest/test_certs/client-tenant.20.key
  pkg/security/securitytest/test_certs/client.root.crt
  pkg/security/securitytest/test_certs/client.root.key
  pkg/security/securitytest/test_certs/client.testuser.crt
  pkg/security/securitytest/test_certs/client.testuser.key
  pkg/security/securitytest/test_certs/client.testuser2.crt
  pkg/security/securitytest/test_certs/client.testuser2.key
  pkg/security/securitytest/test_certs/client.testuser3.crt
  pkg/security/securitytest/test_certs/client.testuser3.key
  pkg/security/securitytest/test_certs/client.testuser_cn_and_san.crt
  pkg/security/securitytest/test_certs/client.testuser_cn_and_san.key
  pkg/security/securitytest/test_certs/client.testuser_cn_only.crt
  pkg/security/securitytest/test_certs/client.testuser_cn_only.key
  pkg/security/securitytest/test_certs/client.testuser_san_only.crt
  pkg/security/securitytest/test_certs/client.testuser_san_only.key
  pkg/security/securitytest/test_certs/node.crt
  pkg/security/securitytest/test_certs/node.key
  pkg/security/securitytest/test_certs/regenerate.sh
  pkg/security/securitytest/test_certs/tenant-signing.10.crt
  pkg/security/securitytest/test_certs/tenant-signing.10.key
  pkg/security/securitytest/test_certs/tenant-signing.11.crt
  pkg/security/securitytest/test_certs/tenant-signing.11.key
  pkg/security/securitytest/test_certs/tenant-signing.2.crt
  pkg/security/securitytest/test_certs/tenant-signing.2.key
  pkg/security/securitytest/test_certs/tenant-signing.20.crt
  pkg/security/securitytest/test_certs/tenant-signing.20.key
  pkg/server/storage_api/certs_test.go
  pkg/sql/pgwire/testdata/auth/empty_hba
  pkg/sql/pgwire/testdata/auth/identity_map
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-23.1.20-rc

#122753 release-23.2: opt: add GenerateTrigramSimilarityInvertedIndexScans rule
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/invertedidx/BUILD.bazel
  pkg/sql/opt/invertedidx/inverted_index_expr.go
  pkg/sql/opt/invertedidx/inverted_index_expr_test.go
  pkg/sql/opt/invertedidx/trigram.go
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/logical_props_builder.go
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/stats/inverted-trigram
  pkg/sql/opt/props/histogram.go
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/rules/select.opt
  pkg/sql/opt/xform/select_funcs.go
  pkg/sql/opt/xform/testdata/rules/generate_trigram_similarity_inverted_index_scans
  pkg/sql/opt/xform/testdata/rules/select
  pkg/sql/sem/tree/datum.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#122761 cluster-ui: fix "stats last created" query in table details using sql-over-http
  pkg/server/admin.go
  pkg/server/application_api/schema_inspection_test.go
  pkg/ui/workspaces/cluster-ui/src/api/tableDetailsApi.ts
Labels: backport-23.1.x, O-testcluster, backport-23.2.x, backport-24.1.x

#122718 release-23.1: sql: add external connection info to show grants
  pkg/ccl/backupccl/testdata/backup-restore/restore-grants
  pkg/sql/delegate/show_grants.go
  pkg/sql/logictest/testdata/logic_test/grant_on_all_sequences_in_schema
  pkg/sql/logictest/testdata/logic_test/grant_on_all_tables_in_schema
  pkg/sql/logictest/testdata/logic_test/grant_revoke_with_grant_option
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/grant_type
  pkg/sql/logictest/testdata/logic_test/role
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/exec/execbuilder/testdata/virtual
Labels: backport

#122825 release-23.1.20-rc: opt: improve trigram similarity filter selectivity
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/stats/inverted-trigram
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#122833 release-23.2: c-deps: set `sysconfdir` to `/etc` for `libkrb5`
  build/bazelutil/distdir_files.bzl
  c-deps/BUILD.bazel
  c-deps/REPOSITORIES.bzl
  c-deps/archived.bzl
Labels: backport
