Repository cockroachdb/cockroach, pull requests merged in 2024-01, with the labels that each got.

#116102 release-23.1: cluster-ui: allow multiple transaction details to show multiple apps
  pkg/ui/workspaces/cluster-ui/src/api/testUtils.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetailsConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/index.ts
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.spec.ts
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/utils.ts
  pkg/ui/workspaces/cluster-ui/src/transactionsTable/transactionsTable.tsx
  pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts
  pkg/ui/workspaces/db-console/src/views/transactions/transactionDetails.tsx
Labels: backport

#117250 release-23.1: multiregionccl: deflake TestMultiRegionDataDriven
  pkg/ccl/multiregionccl/BUILD.bazel
  pkg/ccl/multiregionccl/datadriven_test.go
Labels: backport

#117247 pkg/util/log: include buffered httpSinks in iterHTTPSinks
  pkg/util/log/BUILD.bazel
  pkg/util/log/log_flush.go
  pkg/util/log/registry.go
  pkg/util/log/registry_test.go
Labels: backport-23.2.x

#117244 release-23.1: roachtest: mark npgsql and hibernate tests as flaky
  pkg/cmd/roachtest/tests/hibernate_blocklist.go
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
Labels: backport

#116903 release-23.1: backupccl: replace UDT IDs within routine bodies and views
  pkg/ccl/backupccl/testdata/backup-restore/user-defined-functions
  pkg/ccl/backupccl/testdata/backup-restore/views
  pkg/sql/catalog/rewrite/rewrite.go
Labels: backport

#116274 release-23.2: sql: make CALL statements explainable
  docs/generated/sql/bnf/explainable_stmt.bnf
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/ccl/logictestccl/testdata/logic_test/explain_call_plpgsql
  pkg/ccl/logictestccl/tests/local/BUILD.bazel
  pkg/ccl/logictestccl/tests/local/generated_test.go
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
  pkg/sql/logictest/testdata/logic_test/prepare
  pkg/sql/opt/exec/execbuilder/testdata/call
  pkg/sql/opt/exec/execbuilder/tests/local/generated_test.go
  pkg/sql/opt/exec/explain/emit.go
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/optbuilder/plpgsql.go
  pkg/sql/opt/optbuilder/routine.go
  pkg/sql/opt/optbuilder/testdata/procedure
  pkg/sql/opt/optbuilder/testdata/procedure_plpgsql
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/explain
  pkg/sql/sem/tree/overload.go
Labels: backport

#116824 release-23.1: pkg/util/metric: reduce allocations used when recording histogram metrics
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/sqlproxyccl/connector_test.go
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
  pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go
  pkg/kv/kvserver/scheduler_test.go
  pkg/server/status/recorder.go
  pkg/server/status/recorder_test.go
  pkg/sql/sqlstats/persistedsqlstats/bench_test.go
  pkg/util/asciitsdb/BUILD.bazel
  pkg/util/asciitsdb/asciitsdb.go
  pkg/util/metric/BUILD.bazel
  pkg/util/metric/aggmetric/agg_metric_test.go
  pkg/util/metric/aggmetric/histogram.go
  pkg/util/metric/hdrhistogram.go
  pkg/util/metric/histogram_snapshot.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_test.go
  pkg/util/schedulerlatency/histogram.go
  pkg/util/schedulerlatency/histogram_test.go
  pkg/util/schedulerlatency/scheduler_latency_test.go
Labels: backport

#116818 release-23.2: pkg/util/metric: reduce allocations used when recording histogram metrics
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/sqlproxyccl/connector_test.go
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
  pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go
  pkg/kv/kvserver/scheduler_test.go
  pkg/server/status/recorder.go
  pkg/server/status/recorder_test.go
  pkg/sql/sqlstats/persistedsqlstats/bench_test.go
  pkg/util/asciitsdb/BUILD.bazel
  pkg/util/asciitsdb/asciitsdb.go
  pkg/util/metric/BUILD.bazel
  pkg/util/metric/aggmetric/agg_metric_test.go
  pkg/util/metric/aggmetric/histogram.go
  pkg/util/metric/hdrhistogram.go
  pkg/util/metric/histogram_snapshot.go
  pkg/util/metric/metric.go
  pkg/util/metric/metric_test.go
  pkg/util/schedulerlatency/histogram.go
  pkg/util/schedulerlatency/histogram_test.go
  pkg/util/schedulerlatency/scheduler_latency_test.go
Labels: backport

#117271 release-23.2: kvnemesis: add Raft application assertions
  pkg/kv/kvnemesis/BUILD.bazel
  pkg/kv/kvnemesis/kvnemesis_test.go
  pkg/kv/kvserver/apply/BUILD.bazel
  pkg/kv/kvserver/apply/asserter.go
  pkg/kv/kvserver/kvserverbase/BUILD.bazel
  pkg/kv/kvserver/kvserverbase/base.go
  pkg/kv/kvserver/replica_app_batch.go
  pkg/kv/kvserver/replica_application_result.go
  pkg/kv/kvserver/replica_application_state_machine.go
  pkg/kv/kvserver/replica_closedts_test.go
  pkg/kv/kvserver/replica_init.go
  pkg/kv/kvserver/replica_raft.go
  pkg/kv/kvserver/replica_raftstorage.go
  pkg/kv/kvserver/testing_knobs.go
Labels: backport

#117251 test: fix index usage TenantAPI tests
  pkg/ccl/serverccl/statusccl/tenant_status_test.go
Labels: backport-23.2.x

#117324 release-23.2: Revert "kv: stop encoding or decoding synthetic timestamp bit in/from mvcc keys"
  pkg/storage/batch_test.go
  pkg/storage/engine_key.go
  pkg/storage/engine_key_test.go
  pkg/storage/enginepb/decode.go
  pkg/storage/mvcc_key.go
  pkg/storage/mvcc_key_test.go
  pkg/storage/mvcc_value_test.go
  pkg/storage/pebble_test.go
  pkg/storage/testdata/mvcc_histories/uncertainty_interval_with_local_uncertainty_limit_and_synthetic_timestamps
Labels: backport, backport-23.2.0-rc

#116641 teamcity: use crl-release-23.2 branch for pebble tests
  build/teamcity/cockroach/nightlies/pebble_nightly_common.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_race.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_race_common.sh
Labels: backport-23.2.0-rc

#117327 release-23.2: roachtest: port follower-reads/mixed-version/single-region to new framework
  pkg/cmd/roachtest/tests/follower_reads.go
Labels: backport

#117328 release-23.1: roachtest: port follower-reads/mixed-version/single-region to new framework
  pkg/cmd/roachtest/tests/follower_reads.go
Labels: backport

#117295 release-23.1: logstore: sync sideloaded storage directories
  pkg/kv/kvserver/logstore/BUILD.bazel
  pkg/kv/kvserver/logstore/sideload_disk.go
  pkg/kv/kvserver/logstore/sideload_test.go
  pkg/kv/kvserver/replica_application_result.go
  pkg/kv/kvserver/replica_destroy.go
Labels: backport

#117383 release-23.1: logstore: sync sideloaded storage directories
  pkg/kv/kvserver/logstore/sideload.go
  pkg/kv/kvserver/logstore/sideload_disk.go
  pkg/kv/kvserver/logstore/sideload_test.go
Labels: backport

#117412 release-23.1: roachtest: fix follower-reads backport skew
  pkg/cmd/roachtest/tests/follower_reads.go
Labels: backport

#117298 release-23.1: release, ci: split builds by platform
  build/teamcity/cockroach/post-merge/publish-bleeding-edge-darwin-amd64.sh
  build/teamcity/cockroach/post-merge/publish-bleeding-edge-darwin-arm64.sh
  build/teamcity/cockroach/post-merge/publish-bleeding-edge-linux-amd64-fips.sh
  build/teamcity/cockroach/post-merge/publish-bleeding-edge-linux-amd64.sh
  build/teamcity/cockroach/post-merge/publish-bleeding-edge-linux-arm64.sh
  build/teamcity/cockroach/post-merge/publish-bleeding-edge-per-platform.sh
  build/teamcity/cockroach/post-merge/publish-bleeding-edge-win-amd64.sh
  build/teamcity/internal/release/process/build-cockroach-release-darwin-amd64.sh
  build/teamcity/internal/release/process/build-cockroach-release-darwin-arm64.sh
  build/teamcity/internal/release/process/build-cockroach-release-docker.sh
  build/teamcity/internal/release/process/build-cockroach-release-linux-amd64-fips.sh
  build/teamcity/internal/release/process/build-cockroach-release-linux-amd64.sh
  build/teamcity/internal/release/process/build-cockroach-release-linux-arm64.sh
  build/teamcity/internal/release/process/build-cockroach-release-per-platform.sh
  build/teamcity/internal/release/process/build-cockroach-release-win-amd64.sh
  build/teamcity/internal/release/process/build-cockroach-release.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-darwin-amd64.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-darwin-arm64.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-docker.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-linux-amd64-fips.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-linux-amd64.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-linux-arm64.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-per-platform.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-win-amd64.sh
  build/teamcity/internal/release/process/make-and-publish-build-tagging.sh
  pkg/cmd/publish-artifacts/main.go
  pkg/cmd/publish-artifacts/main_test.go
  pkg/cmd/publish-provisional-artifacts/main.go
  pkg/cmd/publish-provisional-artifacts/main_test.go
  pkg/release/build.go
  pkg/release/gcs.go
  scripts/tag-custom-build.sh
Labels: backport

#116676 release-23.1: roachtest: clean up command-line flags
  pkg/BUILD.bazel
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/roachtestflags/BUILD.bazel
  pkg/cmd/roachtest/roachtestflags/flags.go
  pkg/cmd/roachtest/roachtestflags/manager.go
  pkg/cmd/roachtest/roachtestflags/manager_test.go
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/slack.go
  pkg/cmd/roachtest/test_filter.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/test_test.go
Labels: backport

#117319 release-22.2: roachtest: replace gs://cockroach-fixtures with gs://cockroach-fixtures-us-east1
  pkg/ccl/workloadccl/cliccl/fixtures.go
  pkg/cli/interactive_tests/test_workload.tcl
  pkg/cloud/gcp/gcs_storage_test.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/copy.go
  pkg/cmd/roachtest/tests/copyfrom.go
  pkg/cmd/roachtest/tests/import.go
  pkg/cmd/roachtest/tests/import_cancellation.go
  pkg/cmd/roachtest/tests/restore.go
  pkg/cmd/roachtest/tests/schemachange.go
  pkg/cmd/roachtest/tests/sqlsmith.go
  pkg/cmd/roachtest/tests/tpc_utils.go
  pkg/cmd/roachtest/tests/tpcdsvec.go
  pkg/roachprod/install/download.go
  pkg/roachprod/prometheus/prometheus.go
  pkg/workload/querybench/2.1-sql-20
  pkg/workload/tpcds/import.sql
  pkg/workload/tpch/import-sf1.sql
  pkg/workload/tpch/import-sf10.sql
  pkg/workload/tpch/tpch.go
Labels: T-disaster-recovery, backport

#117433 sql: do not re-run optbuild before collecting index recommendations
  pkg/sql/instrumentation.go
  pkg/sql/logictest/testdata/logic_test/index_recommendations
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/schemachanger/comparator_generated_test.go
Labels: backport-23.2.x, backport-23.2.0-rc

#115511 kv: include conflicting request information in latch manager traces/logs
  pkg/kv/kvserver/concurrency/concurrency_control.go
  pkg/kv/kvserver/concurrency/concurrency_manager.go
  pkg/kv/kvserver/concurrency/concurrency_manager_test.go
  pkg/kv/kvserver/concurrency/latch_manager.go
  pkg/kv/kvserver/concurrency/lock_table_test.go
  pkg/kv/kvserver/concurrency/lock_table_waiter_test.go
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/barrier
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/basic
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/optimistic
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/poison_policy_err
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/poison_policy_err_indirect
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/poison_policy_wait_disjoint
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/poison_policy_wait_overlapping
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/range_state_listener
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/shared_locks_latches
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/slow_latch_observability
  pkg/kv/kvserver/replica_send.go
  pkg/kv/kvserver/spanlatch/BUILD.bazel
  pkg/kv/kvserver/spanlatch/manager.go
  pkg/kv/kvserver/spanlatch/manager_test.go
Labels: O-community, X-blathers-triaged

#117388 release-23.1: sql: skip tests under race that may trigger a fixed race in conn executor
  pkg/ccl/testccl/sqlccl/BUILD.bazel
  pkg/ccl/testccl/sqlccl/temp_table_clean_test.go
Labels: backport

#117333 release-23.2: metric: fix windowing for manual histograms
  pkg/util/metric/metric.go
  pkg/util/metric/metric_test.go
Labels: backport

#117335 release-23.1: metric: fix windowing for manual histograms
  pkg/util/metric/metric.go
  pkg/util/metric/metric_test.go
Labels: backport

#116988 ttljob: fix job to handle composite PKs
  pkg/ccl/streamingccl/replicationtestutils/encoding.go
  pkg/sql/randgen/datum.go
  pkg/sql/rowenc/BUILD.bazel
  pkg/sql/rowenc/index_encoding.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
  pkg/sql/ttl/ttljob/ttljob_processor_test.go
  pkg/sql/ttl/ttljob/ttljob_test.go
Labels: backport-23.1.x, backport-23.2.x

#117496 release-23.1: server: fix total latency time on sql stats call
  pkg/server/combined_statement_stats.go
  pkg/server/status_test.go
Labels: backport

#117497 release-23.1.14-rc: server: fix total latency time on sql stats call
  pkg/server/combined_statement_stats.go
  pkg/server/status_test.go
Labels: backport

#117011 gossip: Include highWaterStamps map in gossip debug info
  pkg/gossip/gossip.go
  pkg/gossip/gossip.proto
Labels: O-community

#116525 release-23.2: roachtest: update multitenant/distsql to use new roachprod service APIs
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster/cluster_interface.go
  pkg/cmd/roachtest/option/connection_options.go
  pkg/cmd/roachtest/option/options.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/tests/multitenant_distsql.go
  pkg/cmd/roachtest/tests/multitenant_utils.go
  pkg/roachprod/install/cockroach.go
Labels: backport

#117538 release-23.2.0-rc: released CockroachDB version 23.2.0-rc.2. Next version: 23.2.0-rc.3
  pkg/build/version.txt
Labels: backport

#117539 release-23.2: released CockroachDB version 23.2.0-rc.2. Next version: 23.2.0-rc.3
  pkg/build/version.txt
Labels: backport

#116884 release-23.1: backupccl: add backup checkpointing test
  pkg/ccl/backupccl/backup_job.go
  pkg/ccl/backupccl/backup_test.go
Labels: T-disaster-recovery, backport

#117460 release-23.1: roachtest: move quota inside test runner
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/work_pool.go
Labels: backport

#117519 roachtest: fail the latency verifier immediately if latency is too high
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/latency_verifier.go
Labels: T-disaster-recovery

#117523 release-23.1: server: refactor the sticky engine registry into a VFS registry
  pkg/base/store_spec.go
  pkg/cli/debug_recover_loss_of_quorum_test.go
  pkg/cli/democluster/demo_cluster.go
  pkg/cli/democluster/demo_cluster_test.go
  pkg/kv/kvserver/client_lease_test.go
  pkg/kv/kvserver/client_metrics_test.go
  pkg/kv/kvserver/client_raft_test.go
  pkg/kv/kvserver/client_replica_circuit_breaker_test.go
  pkg/kv/kvserver/client_replica_test.go
  pkg/kv/kvserver/client_split_test.go
  pkg/kv/kvserver/consistency_queue_test.go
  pkg/kv/kvserver/loqrecovery/server_integration_test.go
  pkg/kv/kvserver/node_liveness_test.go
  pkg/kv/kvserver/replicate_queue_test.go
  pkg/server/BUILD.bazel
  pkg/server/config.go
  pkg/server/loss_of_quorum.go
  pkg/server/server_startup_test.go
  pkg/server/settings_cache_test.go
  pkg/server/sticky_engine.go
  pkg/server/sticky_vfs.go
  pkg/server/sticky_vfs_test.go
  pkg/server/testing_knobs.go
  pkg/testutils/testcluster/testcluster.go
  pkg/testutils/testcluster/testcluster_test.go
  pkg/util/startup/startup_test.go
Labels: backport

#116727 release-23.1: status: add network packet dropped and error metrics
  pkg/server/status/runtime.go
  pkg/server/status/runtime_test.go
  pkg/ts/catalog/chart_catalog.go
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/hardware.tsx
Labels: O-community, backport

#117529 release-23.2: cluster-ui: enable statement bundles in tenant clusters
  pkg/ui/workspaces/cluster-ui/package.json
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.spec.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetailsConnected.ts
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx
Labels: backport

#110950 builtins: add fuzzystrmatch metaphone() built-in
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/fuzzystrmatch
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/util/fuzzystrmatch/BUILD.bazel
  pkg/util/fuzzystrmatch/metaphone.go
  pkg/util/fuzzystrmatch/metaphone_test.go
  pkg/util/fuzzystrmatch/soundex.go
Labels: O-community, X-blathers-triaged

#117511 plpgsql: allow assigning to routine parameters
  pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql
  pkg/sql/opt/optbuilder/plpgsql.go
Labels: backport-23.2.x

#117607 release-23.2: roachtest: run consistency checks after tests
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/roachtestutil/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/validation_check.go
Labels: backport

#116961 roachtest: update fixture generation code
  pkg/cmd/roachtest/tests/backup_fixtures.go
Labels: T-disaster-recovery

#117573 release-23.1: sql: fix an exported gist out of bounds error
  pkg/sql/opt/exec/explain/result_columns.go
  pkg/sql/opt/exec/explain/testdata/gists
Labels: backport

#116957 backupccl: wrap restore processor errors as retryable after progress is made
  pkg/ccl/backupccl/backup_test.go
  pkg/ccl/backupccl/full_cluster_backup_restore_test.go
  pkg/ccl/backupccl/restore_data_processor.go
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/utils_test.go
  pkg/jobs/joberror/errors.go
  pkg/sql/exec_util.go
Labels: T-disaster-recovery

#117235 roachtest: take storage checkpoints on failed consistency checks
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/roachtestutil/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/validation_check.go
  pkg/cmd/roachtest/test_runner.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/expander.go
  pkg/sql/sem/builtins/generator_builtins.go
Labels: backport-23.2.x

#117631 release-23.1.14-rc: sql: fix an exported gist out of bounds error
  pkg/sql/opt/exec/explain/result_columns.go
  pkg/sql/opt/exec/explain/testdata/gists
Labels: backport

#117644 release-23.1: storage: fix a series of intent resolution bugs with ignored seq nums
  pkg/storage/mvcc.go
  pkg/storage/mvcc_history_test.go
  pkg/storage/testdata/mvcc_histories/ignored_seq_nums
  pkg/storage/testdata/mvcc_histories/ignored_seq_nums_abort
  pkg/storage/testdata/mvcc_histories/ignored_seq_nums_commit
Labels: backport

#117646 release-23.2: storage: fix a series of intent resolution bugs with ignored seq nums
  pkg/storage/mvcc.go
  pkg/storage/testdata/mvcc_histories/ignored_seq_nums
  pkg/storage/testdata/mvcc_histories/ignored_seq_nums_abort
  pkg/storage/testdata/mvcc_histories/ignored_seq_nums_commit
Labels: backport

#117556 release-23.1: sql: allow empty search path parameters
  pkg/sql/conn_executor.go
  pkg/sql/internal.go
  pkg/sql/logictest/testdata/logic_test/pg_builtins
  pkg/sql/pgwire/conn_test.go
  pkg/sql/sessiondata/parse_search_path.go
  pkg/sql/sessiondata/search_path_test.go
Labels: backport

#117557 release-23.2: sql: allow empty search path parameters
  pkg/sql/conn_executor.go
  pkg/sql/internal.go
  pkg/sql/logictest/testdata/logic_test/pg_builtins
  pkg/sql/pgwire/conn_test.go
  pkg/sql/sessiondata/parse_search_path.go
  pkg/sql/sessiondata/search_path_test.go
Labels: backport

#117561 release-23.1: roachtest: remove cloud from registry and ClusterSpec
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster_test.go
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/main.go
  pkg/cmd/roachtest/main_test.go
  pkg/cmd/roachtest/registry/registry_interface.go
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/spec/cluster_spec.go
  pkg/cmd/roachtest/spec/option.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/test_registry_test.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/test_test.go
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/cdc.go
  pkg/cmd/roachtest/tests/import_cancellation.go
  pkg/cmd/roachtest/tests/tpcc_test.go
Labels: backport

#117705 release-23.2: ci: migrate CI docker images to GCP
  build/.bazelbuilderversion
  build/.bazelbuilderversion-fips
  build/README.md
  build/packer/teamcity-agent.sh
  build/teamcity-bazel-support.sh
  build/teamcity/internal/cockroach/build/ci/build-and-push-bazel-builder-image-fips.sh
  build/teamcity/internal/cockroach/build/ci/build-and-push-bazel-builder-image.sh
  build/teamcity/internal/cockroach/build/ci/nightly-bazel-builder-update-check.sh
  build/toolchains/BUILD.bazel
  build/toolchains/toolchainbuild/crosstool-ng/buildtoolchains.sh
  build/toolchains/toolchainbuild/osxcross/buildtoolchains.sh
  pkg/acceptance/cluster/docker.go
  pkg/acceptance/compose/gss/build-push-gss.sh
  pkg/acceptance/compose/gss/docker-compose-python.yml
  pkg/acceptance/compose/gss/docker-compose.yml
  pkg/acceptance/testdata/README.md
  pkg/acceptance/util_docker.go
  pkg/cmd/dev/testdata/recorderdriven/builder
  pkg/cmd/dev/testdata/recorderdriven/builder.rec
Labels: backport

#117706 release-23.1: ci: migrate CI docker images to GCP
  build/.bazelbuilderversion
  build/.bazelbuilderversion-fips
  build/packer/teamcity-agent.sh
  build/teamcity-bazel-support.sh
  build/teamcity/internal/cockroach/build/ci/build-and-push-bazel-builder-image-fips.sh
  build/teamcity/internal/cockroach/build/ci/build-and-push-bazel-builder-image.sh
  build/teamcity/internal/cockroach/build/ci/nightly-bazel-builder-update-check.sh
  build/toolchains/toolchainbuild/crosstool-ng/buildtoolchains.sh
  build/toolchains/toolchainbuild/osxcross/buildtoolchains.sh
  pkg/acceptance/cluster/docker.go
  pkg/acceptance/compose/gss/build-push-gss.sh
  pkg/acceptance/compose/gss/docker-compose-python.yml
  pkg/acceptance/compose/gss/docker-compose.yml
  pkg/acceptance/testdata/README.md
  pkg/acceptance/util_docker.go
  pkg/cmd/dev/testdata/recorderdriven/builder
  pkg/cmd/dev/testdata/recorderdriven/builder.rec
Labels: backport

#117093 explain: include plan of cascades in the output
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/sql/conn_executor_exec.go
  pkg/sql/distsql_plan_changefeed.go
  pkg/sql/distsql_running.go
  pkg/sql/execinfrapb/BUILD.bazel
  pkg/sql/execinfrapb/component_stats.go
  pkg/sql/explain_plan.go
  pkg/sql/explain_tree_test.go
  pkg/sql/faketreeeval/evalctx.go
  pkg/sql/instrumentation.go
  pkg/sql/opt/bench/bench_test.go
  pkg/sql/opt/exec/execbuilder/builder.go
  pkg/sql/opt/exec/execbuilder/cascades.go
  pkg/sql/opt/exec/execbuilder/format.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/scalar.go
  pkg/sql/opt/exec/execbuilder/statement.go
  pkg/sql/opt/exec/execbuilder/testdata/cascade
  pkg/sql/opt/exec/execbuilder/testdata/fk
  pkg/sql/opt/exec/execbuilder/testdata/not_visible_index
  pkg/sql/opt/exec/execbuilder/testdata/unique
  pkg/sql/opt/exec/explain/BUILD.bazel
  pkg/sql/opt/exec/explain/emit.go
  pkg/sql/opt/exec/explain/explain_factory.go
  pkg/sql/opt/exec/explain/explain_factory_test.go
  pkg/sql/opt/exec/explain/plan_gist_factory.go
  pkg/sql/opt/exec/explain/plan_gist_test.go
  pkg/sql/opt/exec/factory.go
  pkg/sql/opt/idxconstraint/index_constraints_test.go
  pkg/sql/opt/lookupjoin/constraint_builder_test.go
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/optbuilder/mutation_builder_fk.go
  pkg/sql/opt/partialidx/implicator_test.go
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/plan_opt.go
  pkg/sql/sem/builtins/generator_builtins.go
  pkg/sql/sem/eval/deps.go
  pkg/sql/sem/eval/eval_test.go
  pkg/sql/sql_cursor.go
Labels: backport-23.2.x

#117718 release-23.1: roachtest: pull tpc-e image from GAR
  pkg/cmd/roachtest/tests/tpce.go
Labels: backport

#116526 release-23.1: roachtest: update multitenant/distsql to use new roachprod service APIs
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster/cluster_interface.go
  pkg/cmd/roachtest/option/connection_options.go
  pkg/cmd/roachtest/option/options.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/tests/multitenant_distsql.go
  pkg/cmd/roachtest/tests/multitenant_utils.go
  pkg/roachprod/install/cockroach.go
Labels: backport

#117680 roachtest: fetch virtual cluster logs on failure
  pkg/cmd/roachtest/cluster.go
Labels: backport-23.1.x, backport-23.2.x

#117715 release-23.2: plpgsql: allow assigning to routine parameters
  pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql
  pkg/sql/opt/optbuilder/plpgsql.go
Labels: backport

#117745 roachprod: use csv when upserting virtual cluster metadata
  pkg/roachprod/install/cockroach.go
Labels: backport-23.2.x

#117667 release-23.2: roachtest: take storage checkpoints on failed consistency checks
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/roachtestutil/BUILD.bazel
  pkg/cmd/roachtest/roachtestutil/validation_check.go
  pkg/cmd/roachtest/test_runner.go
  pkg/roachprod/install/cluster_synced.go
  pkg/roachprod/install/expander.go
  pkg/sql/sem/builtins/generator_builtins.go
Labels: backport

#117783 kvserver: fix `TestRaftForceCampaignPreVoteCheckQuorum`
  pkg/kv/kvserver/client_raft_test.go
Labels: backport-23.1.x, backport-23.2.x

#117732 release-23.1: roachtest: use backup cloud to set CompatibleClouds
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/restore.go
Labels: backport

#117299 release-23.1: kvserver: sync before removing sideloaded files
  pkg/kv/kvserver/client_raft_log_queue_test.go
  pkg/kv/kvserver/logstore/logstore.go
  pkg/kv/kvserver/logstore/sideload.go
  pkg/kv/kvserver/logstore/sideload_disk.go
  pkg/kv/kvserver/logstore/sideload_test.go
  pkg/kv/kvserver/raft_log_queue.go
  pkg/kv/kvserver/replica_app_batch.go
  pkg/kv/kvserver/replica_application_state_machine.go
  pkg/kv/kvserver/replica_raft.go
  pkg/kv/kvserver/testing_knobs.go
  pkg/server/sticky_vfs.go
Labels: backport

#117498 mixedversion: remove ID() function from singleStepProtocol
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/runner_test.go
Labels: backport-23.1.x, backport-23.2.x

#117795 roachtest: use 'master' tag for tpc-e docker images
  pkg/cmd/roachtest/tests/tpce.go
Labels: backport-23.1.x, backport-23.2.x

#117513 release-23.1: ttljob: fix job to handle composite PKs
  pkg/ccl/streamingccl/replicationtestutils/encoding.go
  pkg/sql/randgen/datum.go
  pkg/sql/rowenc/BUILD.bazel
  pkg/sql/rowenc/index_encoding.go
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/ttljob_processor.go
  pkg/sql/ttl/ttljob/ttljob_processor_test.go
  pkg/sql/ttl/ttljob/ttljob_test.go
Labels: backport

#117816 release-23.1: roachtest: use 'master' tag for tpc-e docker images
  pkg/cmd/roachtest/tests/tpce.go
Labels: backport

#117818 release-23.2: roachtest: use 'master' tag for tpc-e docker images
  pkg/cmd/roachtest/tests/tpce.go
Labels: backport

#117642 release-23.1: changfeedccl: Fix schema feed test flake
  pkg/ccl/changefeedccl/schemafeed/schema_feed.go
Labels: backport

#117846 sql: fix trigram inverted index on NAME type
  pkg/sql/logictest/testdata/logic_test/trigram_indexes
  pkg/sql/opt/invertedidx/trigram.go
Labels: backport-23.1.x, backport-23.2.x

#115733 telemetry: track telemetry transactions through conn executor
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/BUILD.bazel
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_log.go
  pkg/sql/telemetry_datadriven_test.go
  pkg/sql/telemetry_logging.go
  pkg/sql/telemetry_logging_test.go
  pkg/sql/testdata/telemetry_logging/logging/stmts_per_txn_limit
  pkg/sql/testdata/telemetry_logging/logging/transaction_mode
  pkg/sql/testdata/telemetry_logging/logging_decisions/shouldEmitStatementLog
  pkg/sql/testdata/telemetry_logging/logging_decisions/shouldEmitTransactionLog
  pkg/util/log/logtestutils/telemetry_logging_test_utils.go
Labels: backport-23.2.x

#116560 release-23.1: go.mod: bump Pebble to 78ab2ba86c80
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#114865 schemafeed: ensure highwater is updated even when polling is paused
  pkg/ccl/changefeedccl/schemafeed/BUILD.bazel
  pkg/ccl/changefeedccl/schemafeed/schema_feed.go
  pkg/ccl/changefeedccl/schemafeed/schema_feed_test.go
Labels: backport-23.1.x, backport-23.2.x

#116556 release-23.2: sql: attempt to unsplit ranges in GC job for secondary tenants
  pkg/sql/gcjob/BUILD.bazel
  pkg/sql/gcjob/gc_job.go
  pkg/sql/gcjob/gc_job_test.go
Labels: backport

#117982 release-23.2: roachprod: elide expiration notification for GCed dangling resources (in Azure)
  pkg/roachprod/cloud/gc.go
  pkg/roachprod/roachprod.go
Labels: backport

#117981 release-23.1: roachprod: elide expiration notification for GCed dangling resources (in Azure)
  pkg/roachprod/cloud/gc.go
  pkg/roachprod/roachprod.go
Labels: backport

#117699 release-23.1: roachtest: segregate issues for coverage and metamorphic builds and related changes
  pkg/cmd/internal/issues/formatter_unit.go
  pkg/cmd/internal/issues/issues.go
  pkg/cmd/internal/issues/issues_test.go
  pkg/cmd/internal/issues/render.go
  pkg/cmd/internal/issues/testdata/post/failure-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-with-url-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-with-url-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-with-url-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/failure-with-url-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/fatal-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/fatal-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/fatal-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/fatal-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/infrastructure-flake-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/infrastructure-flake-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/infrastructure-flake-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/infrastructure-flake-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/panic-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/panic-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/panic-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/panic-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/rsg-crash-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/rsg-crash-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/rsg-crash-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/rsg-crash-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/with-artifacts-matching-and-related-issue.txt
  pkg/cmd/internal/issues/testdata/post/with-artifacts-matching-issue.txt
  pkg/cmd/internal/issues/testdata/post/with-artifacts-no-issue.txt
  pkg/cmd/internal/issues/testdata/post/with-artifacts-related-issue.txt
Labels: backport

#117895 release-23.2: copy: improve behavior of non-atomic COPY
  pkg/sql/copy/copy_in_test.go
  pkg/sql/copy/copy_test.go
  pkg/sql/copy_file_upload.go
  pkg/sql/copy_from.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#118152 release-23.1: released CockroachDB version 23.1.14. Next version: 23.1.15
  pkg/build/version.txt
Labels: backport

#118100 kv/bulk: add guardrails to createSplitSSTable
  pkg/kv/bulk/BUILD.bazel
  pkg/kv/bulk/split_sst_test.go
  pkg/kv/bulk/sst_batcher.go
Labels: T-disaster-recovery

#118204 release-23.2: backport pkg/cmd/release changes
  pkg/cmd/release/testdata/release_data.yaml
  pkg/cmd/release/update_releases.go
  pkg/cmd/release/update_releases_test.go
Labels: backport

#118205 release-23.1: backport pkg/cmd/release changes
  pkg/cmd/release/testdata/release_data.yaml
  pkg/cmd/release/update_releases.go
  pkg/cmd/release/update_releases_test.go
Labels: backport

#118154 release-23.2: docs: properly generate HTML files for updated SQL diagrams
  docs/generated/sql/bnf/BUILD.bazel
  docs/generated/sql/bnf/alter_proc.bnf
  docs/generated/sql/bnf/alter_proc_stmt.bnf
  docs/generated/sql/bnf/call.bnf
  docs/generated/sql/bnf/call_stmt.bnf
  docs/generated/sql/bnf/create_func.bnf
  docs/generated/sql/bnf/create_func_stmt.bnf
  docs/generated/sql/bnf/create_proc.bnf
  docs/generated/sql/bnf/create_proc_stmt.bnf
  docs/generated/sql/bnf/drop_proc.bnf
  docs/generated/sql/bnf/drop_proc_stmt.bnf
  pkg/cmd/docgen/diagrams.go
  pkg/gen/bnf.bzl
  pkg/gen/docs.bzl
Labels: backport

#117612 rangefeed: fix premature checkpoint due to intent resolution race
  pkg/kv/kvclient/rangefeed/BUILD.bazel
  pkg/kv/kvclient/rangefeed/rangefeed_external_test.go
  pkg/kv/kvserver/rangefeed/BUILD.bazel
  pkg/kv/kvserver/rangefeed/processor.go
  pkg/kv/kvserver/rangefeed/processor_test.go
  pkg/kv/kvserver/rangefeed/resolved_timestamp.go
  pkg/kv/kvserver/rangefeed/resolved_timestamp_test.go
  pkg/kv/kvserver/rangefeed/scheduled_processor.go
  pkg/kv/kvserver/rangefeed/task.go
  pkg/kv/kvserver/rangefeed/task_test.go
  pkg/kv/kvserver/replica_rangefeed.go
Labels: backport-23.1.x, backport-23.2.x

#118255 docs: unlink custom param names from SQL diagrams
  pkg/cmd/docgen/diagrams.go
Labels: backport-23.2.x

#118276 release-23.2: rpc: remove TestGRPCKeepaliveFailureFailsInflightRPCs
  pkg/rpc/BUILD.bazel
  pkg/rpc/context_test.go
  pkg/rpc/heartbeat_test.go
  pkg/rpc/keepalive.go
Labels: backport

#117865 release-23.2: sqlproxyccl: add proxy protocol listener
  pkg/ccl/cliccl/flags.go
  pkg/ccl/cliccl/mt_proxy.go
  pkg/ccl/sqlproxyccl/proxy_handler.go
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
  pkg/ccl/sqlproxyccl/server.go
  pkg/cli/cliflags/flags_mt.go
Labels: backport

#117866 release-23.1: sqlproxyccl: add proxy protocol listener
  pkg/ccl/cliccl/flags.go
  pkg/ccl/cliccl/mt_proxy.go
  pkg/ccl/sqlproxyccl/proxy_handler.go
  pkg/ccl/sqlproxyccl/proxy_handler_test.go
  pkg/ccl/sqlproxyccl/server.go
  pkg/cli/cliflags/flags_mt.go
Labels: backport

#118345 release-23.1: sql: include referencing tables into the bundle schema
  pkg/sql/explain_bundle_test.go
  pkg/sql/opt/exec/execbuilder/testdata/explain_env
  pkg/sql/opt/metadata.go
Labels: backport

#118270 roachtest: remove Flowable test
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/flowable.go
  pkg/cmd/roachtest/tests/registry.go
Labels: backport-23.1.x, backport-23.2.x

#118354 roachetest/mixedversion: reduce wait times in local runs
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/local_runs_reduced_wait_time
Labels: backport-23.1.x, backport-23.2.x

#118332 roachtest,floatcmp: fix float comparison so 0 always matches -0
  pkg/cmd/roachtest/tests/query_comparison_util.go
  pkg/cmd/roachtest/tests/query_comparison_util_test.go
  pkg/testutils/floatcmp/floatcmp.go
Labels: backport-23.1.x, backport-23.2.x

#116583 kvclient: correctly handle node shutdown
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvclient/kvcoord/range_iter.go
  pkg/kv/kvclient/kvcoord/txn_test.go
  pkg/kv/kvserver/client_merge_test.go
Labels: A-kv, backport-23.1.x, backport-23.2.x

#116712 release-23.2: status: add network packet dropped and error metrics
  docs/generated/metrics/metrics.html
  pkg/server/status/runtime.go
  pkg/server/status/runtime_test.go
  pkg/ui/workspaces/cluster-ui/src/store/nodes/nodes.fixtures.ts
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/networking.tsx
Labels: backport

#118438 release-23.2: stats: skip TSQuery until stats collection is fixed
  pkg/sql/stats/stats_test.go
Labels: backport

#118439 release-23.1: stats: skip TSQuery until stats collection is fixed
  pkg/sql/stats/stats_test.go
Labels: backport

#117325 release-23.2: logmetrics: add metrics for fluent write error, attempts
  docs/generated/metrics/metrics.html
  pkg/util/log/fluent_client.go
  pkg/util/log/logmetrics/BUILD.bazel
  pkg/util/log/logmetrics/metrics.go
  pkg/util/log/logmetrics/metrics_test.go
  pkg/util/log/metric.go
Labels: backport

#118010 sql: support copy encoding utf8 syntax
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/copy_from.go
  pkg/sql/parser/parse_test.go
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/copy
  pkg/sql/sem/tree/copy.go
Labels: O-community, X-blathers-triaged

#118169 release-23.2: cluster-ui: enable Explain Plan for tenant clusters
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/statementInsightDetailsConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsView.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/workloadInsightsPageConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/activeStatementDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/activeStatementDetailsConnected.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsTable/statementsTable.tsx
Labels: backport

#118146 release-23.1: roachtest: remove tags
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/registry/filter.go
  pkg/cmd/roachtest/registry/test_spec.go
  pkg/cmd/roachtest/registry/testdata/filter/describe
  pkg/cmd/roachtest/registry/testdata/filter/matches
  pkg/cmd/roachtest/test_filter.go
  pkg/cmd/roachtest/test_filter_test.go
  pkg/cmd/roachtest/test_registry.go
  pkg/cmd/roachtest/testdata/test-filter-tag-compat
  pkg/cmd/roachtest/tests/acceptance.go
  pkg/cmd/roachtest/tests/activerecord.go
  pkg/cmd/roachtest/tests/admission_control_elastic_backup.go
  pkg/cmd/roachtest/tests/admission_control_elastic_cdc.go
  pkg/cmd/roachtest/tests/admission_control_index_overload.go
  pkg/cmd/roachtest/tests/admission_control_multi_store_overload.go
  pkg/cmd/roachtest/tests/admission_control_snapshot_overload.go
  pkg/cmd/roachtest/tests/admission_control_tpcc_overload.go
  pkg/cmd/roachtest/tests/asyncpg.go
  pkg/cmd/roachtest/tests/awsdms.go
  pkg/cmd/roachtest/tests/backup.go
  pkg/cmd/roachtest/tests/cdc.go
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
  pkg/cmd/roachtest/tests/costfuzz.go
  pkg/cmd/roachtest/tests/django.go
  pkg/cmd/roachtest/tests/failover.go
  pkg/cmd/roachtest/tests/fixtures.go
  pkg/cmd/roachtest/tests/gopg.go
  pkg/cmd/roachtest/tests/gorm.go
  pkg/cmd/roachtest/tests/hibernate.go
  pkg/cmd/roachtest/tests/jasyncsql.go
  pkg/cmd/roachtest/tests/knex.go
  pkg/cmd/roachtest/tests/kv.go
  pkg/cmd/roachtest/tests/kvbench.go
  pkg/cmd/roachtest/tests/libpq.go
  pkg/cmd/roachtest/tests/liquibase.go
  pkg/cmd/roachtest/tests/nodejs_postgres.go
  pkg/cmd/roachtest/tests/npgsql.go
  pkg/cmd/roachtest/tests/pebble_write_throughput.go
  pkg/cmd/roachtest/tests/pebble_ycsb.go
  pkg/cmd/roachtest/tests/pgjdbc.go
  pkg/cmd/roachtest/tests/pgx.go
  pkg/cmd/roachtest/tests/pop.go
  pkg/cmd/roachtest/tests/psycopg.go
  pkg/cmd/roachtest/tests/restore.go
  pkg/cmd/roachtest/tests/roachtest.go
  pkg/cmd/roachtest/tests/ruby_pg.go
  pkg/cmd/roachtest/tests/rust_postgres.go
  pkg/cmd/roachtest/tests/schemachange_random_load.go
  pkg/cmd/roachtest/tests/sequelize.go
  pkg/cmd/roachtest/tests/smoketest_secure.go
  pkg/cmd/roachtest/tests/sqlalchemy.go
  pkg/cmd/roachtest/tests/tlp.go
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/cmd/roachtest/tests/tpce.go
  pkg/cmd/roachtest/tests/typeorm.go
  pkg/cmd/roachtest/tests/unoptimized_query_oracle.go
  pkg/cmd/roachtest/tests/ycsb.go
Labels: backport

#118427 release-23.1: sqlstats: fix update job to top sql activity stats
  pkg/sql/sql_activity_update_job.go
  pkg/sql/sql_activity_update_job_test.go
  pkg/sql/testdata/sql_activity_update_job
Labels: backport

#118371 release-23.1: server/structlogging: log local node HotRanges
  pkg/server/structlogging/BUILD.bazel
  pkg/server/structlogging/hot_ranges_log.go
  pkg/server/structlogging/hot_ranges_log_test.go
Labels: backport

#118365 release-23.1: roachtest: remove Flowable test
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/flowable.go
  pkg/cmd/roachtest/tests/registry.go
Labels: backport

#118363 release-23.2: roachtest: remove Flowable test
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/flowable.go
  pkg/cmd/roachtest/tests/registry.go
Labels: backport

#118429 release-23.2: sql,cli: improve statement bundles for prepared statements
  pkg/cli/interactive_tests/test_explain_analyze_debug.tcl
  pkg/cli/statement_bundle.go
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
Labels: backport

#118430 release-23.1: sql,cli: improve statement bundles for prepared statements
  pkg/cli/interactive_tests/test_explain_analyze_debug.tcl
  pkg/cli/statement_bundle.go
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
Labels: backport

#118468 kvserver: deflake `TestRaftPreVote`
  pkg/kv/kvserver/client_raft_test.go
Labels: backport-23.2.x

#118333 mixedversion: introduce longer delays in concurrent steps
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/helper.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/basic_test_mixed_version_hooks
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/local_runs_reduced_wait_time
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/minimum_supported_version
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/multiple_upgrades
  pkg/cmd/roachtest/roachtestutil/mixedversion/testdata/planner/step_stages
Labels: backport-23.1.x, backport-23.2.x

#118455 workload/schemachanger: fix intermittent transaction re-use errors
  pkg/workload/schemachange/error_screening.go
  pkg/workload/schemachange/operation_generator.go
Labels: backport-23.1.x, backport-23.2.x

#118544 release-23.2: workload/schemachanger: fix intermittent transaction re-use errors
  pkg/workload/schemachange/error_screening.go
  pkg/workload/schemachange/operation_generator.go
Labels: backport

#118442 release-23.2: stats: fix collection on TSQuery
  pkg/sql/randgen/BUILD.bazel
  pkg/sql/randgen/mutator.go
  pkg/sql/stats/BUILD.bazel
  pkg/sql/stats/histogram.go
  pkg/sql/stats/json.go
  pkg/sql/stats/stats_cache.go
  pkg/sql/stats/stats_test.go
Labels: backport-23.1.x, backport
