Repository cockroachdb/cockroach, pull requests merged in 2025-02, with the labels that each got.

#140259 release-24.1: opt: add new optimizer session settings
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/select
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/distribution/distribution_test.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/delete
  pkg/sql/opt/exec/execbuilder/testdata/explain_redact
  pkg/sql/opt/exec/execbuilder/testdata/update
  pkg/sql/opt/exec/execbuilder/testdata/upsert
  pkg/sql/opt/memo/cost.go
  pkg/sql/opt/memo/cost_test.go
  pkg/sql/opt/memo/expr.go
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/memo/interner.go
  pkg/sql/opt/memo/interner_test.go
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/statistics_builder_test.go
  pkg/sql/opt/memo/testdata/format
  pkg/sql/opt/memo/testdata/memo
  pkg/sql/opt/memo/testdata/stats/inverted-geo
  pkg/sql/opt/opbench/opbench_test.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optgen/exprgen/expr_gen.go
  pkg/sql/opt/props/statistics.go
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/opt/xform/coster.go
  pkg/sql/opt/xform/memo_format.go
  pkg/sql/opt/xform/optimizer.go
  pkg/sql/opt/xform/placeholder_fast_path.go
  pkg/sql/opt/xform/testdata/coster/join
  pkg/sql/opt/xform/testdata/coster/outside-histogram
  pkg/sql/opt/xform/testdata/coster/scan
  pkg/sql/opt/xform/testdata/coster/select
  pkg/sql/opt/xform/testdata/rules/groupby
  pkg/sql/opt/xform/testdata/rules/join
  pkg/sql/opt/xform/testdata/rules/join_order
  pkg/sql/opt/xform/testdata/rules/select
  pkg/sql/opt/xform/testdata/rules/set
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/hints
  pkg/sql/plan_opt.go
  pkg/sql/prepared_stmt.go
  pkg/sql/prepared_stmt_test.go
  pkg/sql/sem/tree/select.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#140299 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#140305 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#140301 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#140300 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#140285 release-24.2: released CockroachDB version 24.2.9. Next version: 24.2.10
  pkg/build/version.txt
Labels: backport

#140302 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#140280 release-24.1: released CockroachDB version 24.1.11. Next version: 24.1.12
  pkg/build/version.txt
Labels: backport

#140304 release-25.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#140282 release-24.3: released CockroachDB version 24.3.4. Next version: 24.3.5
  pkg/build/version.txt
Labels: backport

#140274 release-24.3: crosscluster/logical: use large test pool
  pkg/ccl/crosscluster/logical/BUILD.bazel
Labels: backport

#140381 release-25.1: released CockroachDB version 25.1.0-beta.3. Next version: 25.1.0-beta.4
  pkg/build/version.txt
Labels: backport

#140338 colfetcher: include column family ID in tracing
  pkg/sql/colfetcher/cfetcher.go
  pkg/sql/logictest/testdata/logic_test/column_families
  pkg/sql/opt/exec/execbuilder/testdata/aggregate
  pkg/sql/opt/exec/execbuilder/testdata/ddl
  pkg/sql/opt/exec/execbuilder/testdata/insert
  pkg/sql/opt/exec/execbuilder/testdata/orderby
  pkg/sql/opt/exec/execbuilder/testdata/secondary_index_column_families
  pkg/sql/opt/exec/execbuilder/testdata/select
  pkg/sql/opt/exec/execbuilder/testdata/select_index
  pkg/sql/opt/exec/execbuilder/testdata/update
  pkg/sql/opt/exec/execbuilder/testdata/window
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x, backport-25.1.x

#140426 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#140427 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#140428 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#140430 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#140405 release-25.1: sql: add `sql.defaults.plan_cache_mode` cluster setting and default to `force_custom_plan`
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/testutils/opttester/BUILD.bazel
  pkg/sql/opt/testutils/opttester/opt_tester.go
  pkg/sql/vars.go
Labels: backport

#140456 changefeedccl: fix proprietary OAuth SASL mechanism registration
  pkg/ccl/changefeedccl/kafkaauth/BUILD.bazel
  pkg/ccl/changefeedccl/kafkaauth/kafkaauth.go
  pkg/ccl/changefeedccl/kafkaauth/sasl_proprietary_oauth.go
  pkg/ccl/changefeedccl/kafkaauth/sasl_proprietary_oauth_test.go
Labels: backport-24.1.x

#140386 sql: avoid sql.exec.latency.detail observation if setting is disabled
  pkg/sql/executor_statement_metrics.go
  pkg/sql/executor_statement_metrics_test.go
Labels: backport-25.1.x

#139528 server/debug: don't panic on empty goroutine dumps
  pkg/server/debug/goroutineui/BUILD.bazel
  pkg/server/debug/goroutineui/dump.go
  pkg/server/debug/goroutineui/dump_test.go
Labels: backport-25.1.x

#140472 release-24.2: go.mod: bump Pebble to ee4c9351eb11
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#140404 release-24.3: catalog/lease: disallow leases until range feed starts
  pkg/server/server_sql.go
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_test.go
Labels: backport

#140444 release-24.1: colfetcher: include column family ID in tracing
  pkg/sql/colfetcher/cfetcher.go
  pkg/sql/logictest/testdata/logic_test/column_families
  pkg/sql/opt/exec/execbuilder/testdata/aggregate
  pkg/sql/opt/exec/execbuilder/testdata/ddl
  pkg/sql/opt/exec/execbuilder/testdata/insert
  pkg/sql/opt/exec/execbuilder/testdata/orderby
  pkg/sql/opt/exec/execbuilder/testdata/secondary_index_column_families
  pkg/sql/opt/exec/execbuilder/testdata/select
  pkg/sql/opt/exec/execbuilder/testdata/select_index
  pkg/sql/opt/exec/execbuilder/testdata/update
  pkg/sql/opt/exec/execbuilder/testdata/window
Labels: backport

#140484 release-24.3: sql: address crash retrying schema change transactions
  pkg/sql/conn_executor.go
Labels: backport

#140481 release-24.1: go.mod: bump Pebble to 15b2aa8a3e6c
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#139747 release-25.1: testcluster: deflake TestManualReplication
  pkg/testutils/testcluster/testcluster_test.go
Labels: backport

#140535 crosscluster/logical: persist frontier on update that compeletes initial scan
  pkg/crosscluster/logical/logical_replication_job.go
Labels: backport-25.1.x

#140540 upgrade_manager: fix ListBetweenOverride for some tests
  pkg/upgrade/upgradebase/testing_knobs.go
  pkg/upgrade/upgrademanager/manager.go
  pkg/upgrade/upgrademanager/manager_external_test.go
  pkg/upgrade/upgrades/schema_changes_external_test.go
Labels: backport-25.1.x

#140564 catalog/externalcatalog: delete namespace entries during clean up
  pkg/sql/catalog/externalcatalog/external_catalog.go
Labels: backport-25.1.x

#138361 release-24.3: sql: check for multiple mutations to the same table by triggers
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/sql/opt/optbuilder/fk_cascade.go
  pkg/sql/opt/optbuilder/mutation_builder_fk.go
  pkg/sql/opt/optbuilder/statement_tree.go
  pkg/sql/opt/optbuilder/statement_tree_test.go
  pkg/sql/opt/optbuilder/trigger.go
Labels: backport

#140613 release-24.1: workload/schemachanger: set session variables on all connections
  pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go
  pkg/workload/schemachange/schemachange.go
Labels: backport

#140612 release-24.2: workload/schemachanger: set session variables on all connections
  pkg/ccl/testccl/workload/schemachange/schema_change_external_test.go
  pkg/workload/schemachange/schemachange.go
Labels: backport

#140607 logictest: raise TxnLivenessThreshold for multitenant configs
  pkg/sql/logictest/BUILD.bazel
  pkg/sql/logictest/logic.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x, backport-25.1.x

#140512 changefeedccl: increase ChangefeedTimelyResolvedTimestampUpdatePostRollingRestart verbosity
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport-24.3.x, backport-25.1.x

#140562 kvcoord: deflake TestWaiterOnRejectedCommit
  pkg/kv/kvclient/kvcoord/integration_test.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.2.x, backport-24.3.x, backport-25.1.x

#140066 server: do not use MustBeDString on nullable result col
  pkg/server/admin.go
  pkg/server/application_api/storage_inspection_test.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x, backport-25.1.x

#140666 release-24.3: roachtest: allow for overriding mvt planner params through env vars
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_azure.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  pkg/cmd/roachtest/roachtestutil/clusterupgrade/clusterupgrade.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
Labels: backport

#140665 release-24.3: roachtest/mixedversion: `WaitForReplication` must ensure SQL is ready
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/steps.go
  pkg/cmd/roachtest/roachtestutil/replication.go
  pkg/cmd/roachtest/roachtestutil/utils.go
  pkg/cmd/roachtest/test_runner.go
Labels: backport

#140496 release-24.3: colexec: improve some benchmarks a bit
  pkg/sql/colexec/aggregators_test.go
  pkg/sql/colexec/colexecargs/monitor_registry.go
  pkg/sql/colexec/crossjoiner_test.go
  pkg/sql/colexec/distinct_test.go
  pkg/sql/colexec/external_distinct_test.go
  pkg/sql/colexec/external_hash_aggregator_test.go
  pkg/sql/colexec/external_hash_joiner_test.go
  pkg/sql/colexec/external_sort_test.go
  pkg/sql/colflow/colbatch_scan_test.go
Labels: backport

#140646 release-24.3: opt: type check wildcard-typed VALUES rows after building them
  pkg/ccl/testccl/sqlccl/explain_test.go
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/opt/optbuilder/values.go
  pkg/sql/sem/tree/type_check.go
Labels: backport

#140647 release-24.2: opt: type check wildcard-typed VALUES rows after building them
  pkg/ccl/testccl/sqlccl/explain_test.go
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/opt/optbuilder/values.go
  pkg/sql/sem/tree/type_check.go
Labels: backport

#140648 release-24.1: opt: type check wildcard-typed VALUES rows after building them
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/opt/optbuilder/values.go
  pkg/sql/sem/tree/type_check.go
Labels: backport

#140674 release-24.3: roachtest/mixedversion: upgrade plan should be bounded
  pkg/cmd/roachtest/roachtestutil/mixedversion/mixedversion.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner_test.go
  pkg/cmd/roachtest/tests/mixed_version_cdc.go
  pkg/cmd/roachtest/tests/tpcc.go
Labels: backport

#140694 sql/catalog/lease: Skip TestLeaseRenewedPeriodically in race
  pkg/sql/catalog/lease/lease_test.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x, backport-25.1.x

#140986 release-23.2: released CockroachDB version 23.2.20. Next version: 23.2.21
  pkg/build/version.txt
Labels: backport

#140680 docgen: add DO statement diagram
  docs/generated/sql/bnf/BUILD.bazel
  docs/generated/sql/bnf/do.bnf
  docs/generated/sql/bnf/do_stmt.bnf
  pkg/cmd/docgen/diagrams.go
  pkg/gen/bnf.bzl
  pkg/gen/docs.bzl
Labels: backport-25.1.x

#140993 release-24.2: released CockroachDB version 24.2.10. Next version: 24.2.11
  pkg/build/version.txt
Labels: backport

#140996 release-24.3: released CockroachDB version 24.3.5. Next version: 24.3.6
  pkg/build/version.txt
Labels: backport

#141005 ci: build in fewer configurations in CI
  .github/bors.toml
  .github/workflows/github-actions-essential-ci.yml
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x, backport-25.1.x

#141012 release-25.1: released CockroachDB version 25.1.0-rc.1. Next version: 25.1.0-rc.2
  pkg/build/version.txt
Labels: backport

#141017 release-24.2: ci: build in fewer configurations in CI
  .github/bors.toml
  .github/workflows/github-actions-essential-ci.yml
Labels: backport

#141019 release-24.3: ci: build in fewer configurations in CI
  .github/bors.toml
  .github/workflows/github-actions-essential-ci.yml
Labels: backport

#141016 release-24.1: ci: build in fewer configurations in CI
  .github/bors.toml
  .github/workflows/github-actions-essential-ci.yml
Labels: backport

#141039 nightlies: for nightly stress decrease `RUNS_PER_TEST` to 10
  build/teamcity/cockroach/nightlies/stress_engflow_impl.sh
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x, backport-25.1.x

#141103 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#141104 release-24.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#141108 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#141107 release-25.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#141106 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#141006 backup: deflake TestEncryptedBackupRestoreSystemJobs
  pkg/testutils/jobutils/BUILD.bazel
  pkg/testutils/jobutils/jobs_verification.go
Labels: backport-24.3.x, backport-25.1.x

#141102 release-23.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#141022 backup: set autoddl to false universially in test driver
  pkg/backup/backuptestutils/testutils.go
  pkg/backup/testdata/backup-restore/backup-permissions-deprecated
  pkg/backup/testdata/backup-restore/in-progress-imports
  pkg/backup/testdata/backup-restore/in-progress-restores
  pkg/backup/testdata/backup-restore/multiregion
  pkg/backup/testdata/backup-restore/regression-tests
  pkg/backup/testdata/backup-restore/restore-grants
  pkg/backup/testdata/backup-restore/restore-schema-only-multiregion
Labels: backport-25.1.x

#141123 ci: do not wait on disabled builds
  build/teamcity/internal/release/process/check-gha.sh
Labels: C-bug, T-dev-inf, A-ci, backport-24.1.x, backport-24.2.x, backport-24.3.x, backport-25.1.x

#141135 release-25.1: roachtest: mark polled VM preemptions as non reportable
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/test_test.go
Labels: backport

#141138 release-24.1: roachtest: mark polled VM preemptions as non reportable
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/test_test.go
Labels: backport

#141137 release-24.2: roachtest: mark polled VM preemptions as non reportable
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/test_test.go
Labels: backport

#141136 release-24.3: roachtest: mark polled VM preemptions as non reportable
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/test_test.go
Labels: backport

#141040 docs: update diagrams.go for removed restore syntax
  docs/generated/sql/bnf/restore.bnf
  pkg/cmd/docgen/diagrams.go
Labels: backport-25.1.x

#141205 ci: do not update releases YAML on 23.1
  .github/workflows/update_releases.yaml
Labels: C-enhancement, A-testing, T-dev-inf

#141121 kvserver: more logging in TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer
  pkg/kv/kvserver/client_replica_test.go
Labels: backport-24.1.x, backport-24.2.x, backport-24.3.x, backport-25.1.x, T-microbench-post

#139239 release-24.1: changefeedccl: add scoping support for max_behind_nanos
  docs/generated/metrics/metrics.html
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/metrics.go
  pkg/util/metric/prometheus_exporter.go
Labels: backport

#141189 sql: concurrent DML can prevent PK swaps from succeeding
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/testutils.go
  pkg/sql/opt/cat/catalog.go
  pkg/sql/opt/cat/object.go
  pkg/sql/opt/exec/explain/plan_gist_factory.go
  pkg/sql/opt/indexrec/hypothetical_table.go
  pkg/sql/opt/metadata.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/opt_catalog.go
  pkg/sql/schema_changer_test.go
  pkg/sql/syntheticprivilege/global_privilege.go
Labels: backport-25.1.x

#141375 release-24.3: opt: set min row count of 1 for FK and uniqueness check WithScans
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/stats/insert
  pkg/sql/opt/ops/relational.opt
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#141366 release-24.3: rac2,kvserver: start the StreamCloseScheduler
  pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler.go
  pkg/kv/kvserver/kvflowcontrol/replica_rac2/close_scheduler_test.go
  pkg/kv/kvserver/kvflowcontrol/replica_rac2/processor.go
  pkg/kv/kvserver/store.go
Labels: backport

#141369 sql: fix auto-retry behavior with autocommit_before_ddl by buffering notices
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_ddl.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/conn_executor_test.go
  pkg/sql/conn_io.go
  pkg/sql/faketreeeval/evalctx.go
  pkg/sql/logictest/BUILD.bazel
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/upsert
  pkg/sql/logictest/testdata/logic_test/virtual_columns
  pkg/sql/notice.go
  pkg/sql/pgwire/command_result.go
  pkg/sql/planhook.go
  pkg/sql/sem/builtins/notice.go
  pkg/sql/sem/eval/deps.go
Labels: backport-25.1.x

#141394 release-23.2: dev: add extra startup flag to fix breakage on Darwin/ARM64 machines
  build/bazelutil/darwinarm64cross.bazelrc
  dev
  pkg/cmd/dev/builder.go
Labels: backport

#141398 release-25.1: dev: add extra startup flag to fix breakage on Darwin/ARM64 machines
  build/bazelutil/darwinarm64cross.bazelrc
  dev
  pkg/cmd/dev/builder.go
Labels: backport

#141397 release-24.3: dev: add extra startup flag to fix breakage on Darwin/ARM64 machines
  build/bazelutil/darwinarm64cross.bazelrc
  dev
  pkg/cmd/dev/builder.go
Labels: backport

#141396 release-24.2: dev: add extra startup flag to fix breakage on Darwin/ARM64 machines
  build/bazelutil/darwinarm64cross.bazelrc
  dev
  pkg/cmd/dev/builder.go
Labels: backport

#141395 release-24.1: dev: add extra startup flag to fix breakage on Darwin/ARM64 machines
  build/bazelutil/darwinarm64cross.bazelrc
  dev
  pkg/cmd/dev/builder.go
Labels: backport

#140601 rowexec: add encoded datums to HLL sketch
  pkg/sql/create_stats_test.go
  pkg/sql/distsql_running.go
  pkg/sql/execversion/version.go
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/opt/exec/execbuilder/testdata/partial_stats
  pkg/sql/randgen/encdatum.go
  pkg/sql/rowexec/BUILD.bazel
  pkg/sql/rowexec/sample_aggregator_test.go
  pkg/sql/rowexec/sampler.go
  pkg/sql/rowexec/sampler_test.go
Labels: o-perf-efficiency

#141374 release-25.1: opt: set min row count of 1 for FK and uniqueness check WithScans
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/stats/insert
  pkg/sql/opt/ops/relational.opt
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#141376 release-24.2: opt: set min row count of 1 for FK and uniqueness check WithScans
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/stats/insert
  pkg/sql/opt/ops/relational.opt
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#141378 release-24.1: opt: set min row count of 1 for FK and uniqueness check WithScans
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/memo/testdata/stats/insert
  pkg/sql/opt/ops/relational.opt
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#140621 release-25.1: server: cleanup TestAdminAPIDataDistribution
  pkg/server/application_api/storage_inspection_test.go
Labels: backport

#141441 release-25.1: roachtest: add mixed version jobs test
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/mixed_version_jobs.go
  pkg/cmd/roachtest/tests/registry.go
Labels: backport

#141431 workload/schemachanger: handle not null violations for new tables
  pkg/workload/schemachange/operation_generator.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#141033 catalog/lease: remove expiry based leasing code
  pkg/gen/stringer.bzl
  pkg/settings/registry.go
  pkg/sql/catalog/lease/BUILD.bazel
  pkg/sql/catalog/lease/count.go
  pkg/sql/catalog/lease/descriptor_state.go
  pkg/sql/catalog/lease/descriptor_version_state.go
  pkg/sql/catalog/lease/ie_writer_test.go
  pkg/sql/catalog/lease/kv_writer.go
  pkg/sql/catalog/lease/kv_writer_test.go
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_internal_test.go
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/catalog/lease/sessionbasedleasingmode_string.go
  pkg/sql/catalog/lease/storage.go
  pkg/sql/catalog/systemschema/system.go
  pkg/sql/conn_executor_test.go
  pkg/sql/crdb_internal.go
Labels: T-microbench-post

#141390 uuid: unredact UUID, Short, and Timestamp
  pkg/kv/kvpb/api_test.go
  pkg/kv/kvserver/concurrency/lock/lock_waiter_test.go
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/basic
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/clear_abandoned_intents
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/clear_abandoned_intents_wait_policy_error
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/clear_abandoned_intents_without_adding_to_lock_table
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/deadlocks
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/discover_lock_after_lease_race
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/discovered_lock
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/isolation_level
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/lock_timeout
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/optimistic
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/priority
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/queue_length_exceeded
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/range_state_listener
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/refresh
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/replicated
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/resolve_pushed_intents
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/resolve_pushed_intents_without_adding_to_lock_table
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/shared_locks
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/uncertainty
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/update
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/wait_elsewhere
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/wait_policy_error
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/wait_policy_skip
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/wait_self
  pkg/roachpb/data_test.go
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
  pkg/util/uuid/BUILD.bazel
  pkg/util/uuid/uuid.go
  pkg/util/uuid/uuid_wrapper.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#141427 db-console: rm paused follower graph on repl dashboard
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/graphTooltips.tsx
  pkg/ui/workspaces/db-console/src/views/cluster/containers/nodeGraphs/dashboards/replication.tsx
Labels: backport-25.1.x

#141195 sql: crdb_internal.zones no longer fails with offline database
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#141419 microbench-ci: merge profiles
  pkg/cmd/microbench-ci/BUILD.bazel
  pkg/cmd/microbench-ci/benchmark.go
  pkg/cmd/microbench-ci/compare_test.go
  pkg/cmd/microbench-ci/config/pull-request-suite.yml
  pkg/cmd/microbench-ci/run.go
  pkg/cmd/microbench-ci/testdata/summary.txt
Labels: T-microbench-post

#141507 release-25.1: uuid: unredact UUID, Short, and Timestamp
  pkg/kv/kvpb/api_test.go
  pkg/kv/kvserver/concurrency/lock/lock_waiter_test.go
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/basic
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/clear_abandoned_intents
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/clear_abandoned_intents_wait_policy_error
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/clear_abandoned_intents_without_adding_to_lock_table
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/deadlocks
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/discover_lock_after_lease_race
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/discovered_lock
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/isolation_level
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/lock_timeout
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/optimistic
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/priority
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/queue_length_exceeded
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/range_state_listener
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/refresh
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/replicated
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/resolve_pushed_intents
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/resolve_pushed_intents_without_adding_to_lock_table
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/shared_locks
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/uncertainty
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/update
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/wait_elsewhere
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/wait_policy_error
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/wait_policy_skip
  pkg/kv/kvserver/concurrency/testdata/concurrency_manager/wait_self
  pkg/roachpb/data_test.go
  pkg/testutils/lint/passes/redactcheck/redactcheck.go
  pkg/util/uuid/BUILD.bazel
  pkg/util/uuid/uuid.go
  pkg/util/uuid/uuid_wrapper.go
Labels: backport

#141155 release-25.1: changefeedccl: support proprietary oauth varient for kafka
  pkg/BUILD.bazel
  pkg/ccl/changefeedccl/changefeedbase/options.go
  pkg/ccl/changefeedccl/kafkaauth/BUILD.bazel
  pkg/ccl/changefeedccl/kafkaauth/kafkaauth.go
  pkg/ccl/changefeedccl/kafkaauth/sasl_proprietary_oauth.go
  pkg/ccl/changefeedccl/kafkaauth/sasl_proprietary_oauth_test.go
Labels: backport

#141509 release-24.3: sql: crdb_internal.zones no longer fails with offline database
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
Labels: backport

#141617 crosscluster/logical: remove useless log line
  pkg/crosscluster/logical/offline_initial_scan_processor.go
Labels: backport-25.1.x

#141635 release-24.3: roachtest: run post test health checks on system
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/roachtestutil/httpclient.go
Labels: backport

#141634 crosscluster/logical: avoid panic in multi-table streams involving UDTs
  pkg/crosscluster/logical/logical_replication_job_test.go
  pkg/crosscluster/producer/replication_manager.go
  pkg/sql/catalog/externalcatalog/external_catalog.go
Labels: backport-24.3.x, backport-25.1.x

#141627 release-24.1: sql: deflake TestBackfillWithProtectedTS
  pkg/sql/backfill_protected_timestamp_test.go
Labels: backport

#141626 release-24.3: sql: deflake TestBackfillWithProtectedTS
  pkg/sql/backfill_protected_timestamp_test.go
Labels: backport

#141640 release-24.3: roachtest: skip online restore tests on released versions
  pkg/ccl/backupccl/backuptestutils/BUILD.bazel
  pkg/ccl/backupccl/backuptestutils/testutils.go
  pkg/cmd/roachtest/tests/BUILD.bazel
  pkg/cmd/roachtest/tests/online_restore.go
Labels: backport

#141675 release-24.3: rowexec: use BulkNormalPri for backfill constructIndexEntries
  pkg/sql/rowexec/indexbackfiller.go
Labels: backport

#141718 release-24.3: released CockroachDB version 24.3.6. Next version: 24.3.7
  pkg/build/version.txt
Labels: backport, backport-24.3.7-rc

#141721 release-24.1: released CockroachDB version 24.1.13. Next version: 24.1.14
  pkg/build/version.txt
Labels: backport, backport-24.1.14-rc

#141726 release: do not skip rc branches when bump version
  pkg/cmd/release/update_versions.go
Labels: C-enhancement, A-release, T-release

#141688 schemachangerccl: make alter_table_multiple_commands less expensive
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands.definition
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands.explain_shape
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_10_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_11_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_12_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_13_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_14_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_15_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_1_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_2_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_3_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_4_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_5_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_6_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_7_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_8_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_9_of_15.explain
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#141760 release-25.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#141759 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#141757 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#141762 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#140650 Make docker init script respect COCKROACH_DATABASE when processing SQL files
  build/deploy/cockroach.sh
Labels: O-community, T-sql-foundations

#141764 workflows: do not update releases YAML on 24.2
  .github/workflows/update_releases.yaml
Labels: C-enhancement, A-release, T-release

#141647 sql/schemachanger: Fix test flake in triggers logic test
  pkg/ccl/logictestccl/testdata/logic_test/triggers
Labels: backport-24.3.x, backport-25.1.x

#141747 release-25.1: schemachangerccl: make alter_table_multiple_commands less expensive
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands.definition
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands.explain_shape
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_10_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_11_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_12_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_13_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_14_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_15_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_1_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_2_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_3_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_4_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_5_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_6_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_7_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_8_of_15.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_multiple_commands/alter_table_multiple_commands__rollback_9_of_15.explain
Labels: backport

#141666 release-23.2: opt: copy UDF body statements when assigning placeholders
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/opt/norm/factory.go
Labels: backport

#141728 opt/execbuilder: pick correct canary column ordinal
  pkg/sql/opt/column_meta.go
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/testdata/upsert
Labels: backport-23.2.x, backport-24.1.x, backport-24.3.x, backport-25.1.x

#141755 release-23.2: kvserver: show store number when printing metrics
  pkg/kv/kvserver/store.go
Labels: backport

#141793 release-24.3: crosscluster/logical: avoid panic in multi-table streams involving UDTs
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/producer/replication_manager.go
Labels: backport

#141673 roachtest: make retry loop in copyfrom/atomic unconditional
  pkg/cmd/roachtest/tests/copyfrom.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.3.x, backport-25.1.x

#141738 sql: fix confusing error message for create trigger in transaction
  pkg/sql/BUILD.bazel
  pkg/sql/create_trigger.go
  pkg/sql/logictest/testdata/logic_test/row_level_security
  pkg/sql/logictest/testdata/logic_test/unimplemented
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/unimplemented.go
Labels: backport-24.3.x, backport-25.1.x

#141684 crosscluster/physical: add intitial scan replication status
  pkg/crosscluster/physical/stream_ingestion_dist.go
  pkg/crosscluster/physical/stream_ingestion_frontier_processor.go
  pkg/jobs/jobspb/wrap.go
Labels: backport-24.3.x, backport-25.1.x

#141519 release-24.3: sqlstats: clarify latency percentile limitations
  pkg/sql/appstatspb/app_stats.go
  pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx
Labels: backport-23.2.x, backport-24.1.x

#141822 release-25.1: opt/execbuilder: pick correct canary column ordinal
  pkg/sql/opt/column_meta.go
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/testdata/upsert
Labels: backport

#141824 release-24.1: opt/execbuilder: pick correct canary column ordinal
  pkg/sql/opt/column_meta.go
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/testdata/upsert
Labels: backport

#141825 release-23.2: opt/execbuilder: pick correct canary column ordinal
  pkg/sql/opt/column_meta.go
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/testdata/upsert
Labels: backport

#141823 release-24.3: opt/execbuilder: pick correct canary column ordinal
  pkg/sql/opt/column_meta.go
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/testdata/upsert
Labels: backport

#141763 storage: fix TestPebbleIterator_ExternalCorruption flake
  pkg/storage/pebble_iterator_test.go
Labels: backport-25.1.x

#141864 kvserver: deflake TestStoreRangeSplitWithConcurrentWrites
  pkg/kv/kvserver/client_split_test.go
Labels: backport-24.3.x, backport-25.1.x

#141963 teams: map cockroachdb/server to T-db-server team label
  TEAMS.yaml
  pkg/internal/team/TEAMS.yaml
Labels: backport-23.1.x, backport-23.2.x, backport-24.1.x, backport-24.3.x

#142017 logictest: deflake regression test for #138809 in distsql_stats
  pkg/sql/logictest/testdata/logic_test/distsql_stats
Labels: backport-23.2.x, backport-24.1.x, backport-24.3.x, backport-25.1.x

#139874 release-23.2: opt/memo: silence error in factorOutVirtualCols for mutation columns
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/opt/memo/statistics_builder.go
Labels: backport

#141665 release-23.2: cli: change jemalloc defaults, report settings
  pkg/cli/start.go
  pkg/cli/start_jemalloc.go
  pkg/server/status/runtime_jemalloc.go
Labels: backport

#141664 release-24.1: cli: change jemalloc defaults, report settings
  pkg/cli/start.go
  pkg/cli/start_jemalloc.go
  pkg/server/status/runtime_jemalloc.go
Labels: backport

#141663 release-24.3: cli: change jemalloc defaults, report settings
  pkg/cli/start.go
  pkg/cli/start_jemalloc.go
  pkg/server/status/runtime_jemalloc.go
Labels: backport

#141154 release-24.3: changefeedccl: support proprietary oauth varient for kafka
  pkg/BUILD.bazel
  pkg/ccl/changefeedccl/changefeedbase/options.go
  pkg/ccl/changefeedccl/kafkaauth/BUILD.bazel
  pkg/ccl/changefeedccl/kafkaauth/kafkaauth.go
  pkg/ccl/changefeedccl/kafkaauth/sasl_proprietary_oauth.go
  pkg/ccl/changefeedccl/kafkaauth/sasl_proprietary_oauth_test.go
Labels: backport

#142080 storage/metamorphic: reduce default op count
  pkg/storage/metamorphic/meta_test.go
Labels: backport-25.1.x

#142058 multiregionccl: make sure sleep is longer than timeout when simulating failure in test
  pkg/ccl/multiregionccl/regionliveness_test.go
  pkg/sql/regionliveness/prober.go
Labels: backport-25.1.x

#141872 release-25.1: sql: fix confusing error message for create trigger in transaction
  pkg/sql/BUILD.bazel
  pkg/sql/create_trigger.go
  pkg/sql/logictest/testdata/logic_test/row_level_security
  pkg/sql/logictest/testdata/logic_test/unimplemented
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/unimplemented.go
Labels: backport

#142003 release-23.2: teams: map cockroachdb/server to T-db-server team label
  TEAMS.yaml
Labels: backport

#142137 release-24.1: sql/types: preserve tuple labels in `(*T).WithoutTypeModifiers`
  pkg/sql/logictest/testdata/logic_test/case
  pkg/sql/types/types.go
Labels: backport

#139859 release-24.3: roachtest: inc wait to 10m for token return in perturbation tests
  pkg/cmd/roachtest/tests/admission_control_latency.go
Labels: backport

#142145 release-23.2: changefeedccl: Avoid logging when context may be canceled
  pkg/ccl/changefeedccl/batching_sink.go
  pkg/ccl/changefeedccl/event_processing.go
Labels: backport

#142094 changefeedccl: improve print notice when changefeed has resolved < min_checkpoint_frequency
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport-25.1.x
