Repository cockroachdb/cockroach, pull requests merged in 2025-10, with the labels that each got.

#154480 sql/copy: deflake copy datadriven test
  pkg/sql/copy/testdata/copy_from
Labels: backport-25.2.x, backport-25.3.x, backport-25.4.x

#154472 release-25.4: ui: add transaction diagnostics api client and page
  pkg/ui/pnpm-lock.yaml
  pkg/ui/workspaces/cluster-ui/src/api/index.ts
  pkg/ui/workspaces/cluster-ui/src/api/transactionDiagnosticsApi.ts
  pkg/ui/workspaces/cluster-ui/src/statementDetails/diagnostics/diagnosticsUtils.ts
  pkg/ui/workspaces/db-console/package.json
  pkg/ui/workspaces/db-console/src/app.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/debug/index.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/diagnosticsHistoryPage/index.spec.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/diagnosticsHistoryPage/index.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/statementDiagnosticsHistory/index.spec.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/statementDiagnosticsHistory/index.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/transactionDiagnosticsHistory/index.spec.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/transactionDiagnosticsHistory/index.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/transactionDiagnosticsHistory/transactionDiagnosticsHistoryView.styl
Labels: O-robot, blathers-backport, backport

#153797 release-25.3: sql: fix a few edge case bugs with CHECK EXTERNAL CONNECTION
  pkg/sql/BUILD.bazel
  pkg/sql/check_external_connection.go
  pkg/sql/check_external_connection_test.go
  pkg/sql/cloud_check_processor.go
  pkg/sql/execinfra/processorsbase.go
Labels: O-robot, T-sql-queries, blathers-backport, backport

#154530 release-25.3: roachtest: disable create_table_with_schema_locked in ORM tests
  pkg/cmd/roachtest/tests/orm_helpers.go
Labels: T-sql-foundations, backport, backport-test-only

#154491 release-25.4: sql: add setting to gate leased descriptors for vtables
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/cmd/roachtest/tests/large_schema_benchmark.go
  pkg/sql/catalog/descs/BUILD.bazel
  pkg/sql/catalog/descs/collection.go
  pkg/sql/crdb_internal.go
  pkg/sql/information_schema.go
  pkg/sql/pg_catalog.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#154534 release-25.2: sql: harden hookFnNode
  pkg/sql/planhook.go
Labels: O-robot, T-sql-queries, blathers-backport, backport

#154538 release-25.4: changefeedccl: remove fixed latency checks from pts benchmark test
  pkg/cmd/roachtest/tests/cdc.go
Labels: O-robot, T-cdc, blathers-backport, backport, backport-test-only

#154446 release-25.4: sql: disable DistSQL when txn buffered writes and MVCC decoding is required
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/mock_transactional_sender.go
  pkg/kv/sender.go
  pkg/kv/txn.go
  pkg/sql/apply_join.go
  pkg/sql/colfetcher/cfetcher.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/delete_range.go
  pkg/sql/distsql_physical_planner.go
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/distsql_running.go
  pkg/sql/distsql_spec_exec_factory.go
  pkg/sql/exec_util.go
  pkg/sql/explain_plan.go
  pkg/sql/explain_vec.go
  pkg/sql/logictest/testdata/logic_test/distsql_buffered_writes
  pkg/sql/logictest/testdata/logic_test/do
  pkg/sql/logictest/tests/5node/BUILD.bazel
  pkg/sql/logictest/tests/5node/generated_test.go
  pkg/sql/row/fetcher.go
  pkg/sql/scan.go
  pkg/sql/schema_changer.go
Labels: O-robot, T-sql-queries, blathers-backport, backport

#154448 release-25.3: sql: disable DistSQL when txn buffered writes and MVCC decoding is required
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/mock_transactional_sender.go
  pkg/kv/sender.go
  pkg/kv/txn.go
  pkg/sql/apply_join.go
  pkg/sql/colfetcher/cfetcher.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/delete_range.go
  pkg/sql/distsql_physical_planner.go
  pkg/sql/distsql_physical_planner_test.go
  pkg/sql/distsql_running.go
  pkg/sql/distsql_spec_exec_factory.go
  pkg/sql/exec_util.go
  pkg/sql/explain_plan.go
  pkg/sql/explain_vec.go
  pkg/sql/logictest/testdata/logic_test/distsql_buffered_writes
  pkg/sql/logictest/testdata/logic_test/do
  pkg/sql/logictest/tests/5node/BUILD.bazel
  pkg/sql/logictest/tests/5node/generated_test.go
  pkg/sql/row/fetcher.go
  pkg/sql/scan.go
  pkg/sql/schema_changer.go
Labels: T-sql-queries, backport

#154568 release-24.1: stmtdiagnostics: fix bizarre flake in TestDiagnosticsRequest
  pkg/sql/stmtdiagnostics/statement_diagnostics_test.go
Labels: O-robot, T-sql-queries, blathers-backport, backport, backport-test-only

#152367 sql: log AST and plan gist for most sentry reports
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/conn_executor_internal_test.go
  pkg/sql/conn_executor_test.go
  pkg/sql/exec_factory_util.go
  pkg/sql/exec_util.go
  pkg/sql/exec_util_test.go
  pkg/sql/opt/exec/execbuilder/post_queries.go
  pkg/sql/opt_exec_factory.go
  pkg/sql/pg_catalog.go
  pkg/sql/statement_mark_redaction_test.go
  pkg/sql/virtual_schema.go
  pkg/util/log/logcrash/crash_reporting_packet_test.go
Labels: backport-24.3.x, backport-25.2.x, backport-25.3.x, backport-25.4.x

#154580 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#154581 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#154577 release-25.4: WORKSPACE: update pgo profile
  WORKSPACE
Labels: O-robot, blathers-backport, backport

#154628 release-25.3: roachtest: deflake drop/tpcc/w=100,nodes=9
  pkg/cmd/roachtest/tests/drop.go
Labels: O-robot, T-kv, blathers-backport, backport, backport-test-only

#150793 sql/jsonpath: index accelerate jsonb_path_exists filters
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/local-read-committed/generated_test.go
  pkg/ccl/logictestccl/tests/local-repeatable-read/generated_test.go
  pkg/sql/logictest/testdata/logic_test/jsonb_path_exists_index_acceleration
  pkg/sql/logictest/testdata/logic_test/jsonb_path_query
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-mixed-25.2/generated_test.go
  pkg/sql/logictest/tests/local-mixed-25.3/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/opt/exec/execbuilder/testdata/jsonb_path_query
  pkg/sql/opt/exec/execbuilder/tests/local/generated_test.go
  pkg/sql/opt/invertedidx/BUILD.bazel
  pkg/sql/opt/invertedidx/json_array.go
  pkg/sql/opt/invertedidx/json_array_test.go
  pkg/sql/opt/xform/testdata/rules/select
  pkg/util/json/encoded.go
  pkg/util/json/json.go
  pkg/util/jsonpath/BUILD.bazel
  pkg/util/jsonpath/path.go
Labels: backport-25.4.x

#153723 kvserver: deflake TestClosedTimestampFrozenAfterSubsumption
  pkg/kv/kvserver/closed_timestamp_test.go
  pkg/testutils/testcluster/testcluster.go
Labels: backport-24.3.x, backport-25.2.x, backport-25.3.x

#154641 kvserver: deflake TestWriteLoadStatsAccounting
  pkg/kv/kvserver/replica_rankings_test.go
Labels: backport-25.4.x

#154569 release-25.4: cli: remove duplicate `stmt` column from `node_distsql_flows`
  pkg/cli/zip_table_registry.go
Labels: O-robot, blathers-backport, backport, T-observability

#154034 release-24.3: partitionccl: skip TestAlterPrimaryKeyCorrectZoneConfigBeforeBackfill under deadlock
  pkg/ccl/partitionccl/BUILD.bazel
  pkg/ccl/partitionccl/alter_primary_key_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#154659 release-25.4: backup: re-apply SECONDARY zone config during RESTORE DATABASE
  pkg/backup/restore_job.go
  pkg/backup/testdata/backup-restore/multiregion
Labels: T-disaster-recovery, backport

#154658 release-25.3: backup: re-apply SECONDARY zone config during RESTORE DATABASE
  pkg/backup/restore_job.go
  pkg/backup/testdata/backup-restore/multiregion
Labels: T-disaster-recovery, backport

#154373 dev-inf: First cut of Claude Code review GH action
  .github/workflows/pr-analyzer-threestage.yml
Labels: O-AI-Review

#154701 release-25.4: sql/inspect: add checkpointing tracking to INSPECT
  pkg/sql/inspect/BUILD.bazel
  pkg/sql/inspect/inspect_job.go
  pkg/sql/inspect/inspect_processor.go
  pkg/sql/inspect/progress.go
  pkg/sql/inspect/progress_test.go
Labels: T-sql-foundations, backport

#154696 release-25.4: metric: permit counter resets in update assertion
  pkg/util/metric/metric.go
Labels: O-robot, blathers-backport, backport, T-observability

#154478 release-25.4: changefeedccl: force-disable per-table PTS
  pkg/ccl/changefeedccl/changefeed_dist.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/settings.go
  pkg/ccl/changefeedccl/protected_timestamps_test.go
  pkg/cmd/roachtest/tests/cdc.go
Labels: T-cdc, backport

#154657 release-24.3: backup: re-apply SECONDARY zone config during RESTORE DATABASE
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/testdata/backup-restore/multiregion
Labels: T-disaster-recovery, backport

#154741 release-25.3.3-rc: roachtest: deflake drop/tpcc/w=100,nodes=9
  pkg/cmd/roachtest/tests/drop.go
Labels: O-robot, T-kv, blathers-backport, backport, backport-test-only

#154656 release-25.2: backup: re-apply SECONDARY zone config during RESTORE DATABASE
  pkg/backup/restore_job.go
  pkg/backup/testdata/backup-restore/multiregion
Labels: T-disaster-recovery, backport

#154664 release-24.1: backup: re-apply SECONDARY zone config during RESTORE DATABASE
  pkg/ccl/backupccl/restore_job.go
  pkg/ccl/backupccl/testdata/backup-restore/multiregion
Labels: T-disaster-recovery, backport

#154748 release-24.1: backupsink: fix ooming in TestFileSSTSinkWrite
  pkg/ccl/backupccl/file_sst_sink.go
  pkg/ccl/backupccl/file_sst_sink_test.go
Labels: T-disaster-recovery, backport

#154766 release-25.4: go.mod: bump Pebble to 294e91fb9c3c
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/storage/bench_cloud_io_test.go
Labels: backport

#154770 release-25.3.3-rc: roachtest: disable create_table_with_schema_locked for ORM tests
  pkg/cmd/roachtest/tests/orm_helpers.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#154775 release-25.4: server: check for isMeta1Leaseholder later in loop
  pkg/server/auto_upgrade.go
Labels: O-robot, blathers-backport, backport

#154759 release-25.3: workflows: update names of GitHub Action runner groups
  .github/workflows/github-actions-essential-ci.yml
  .github/workflows/microbenchmarks-ci.yaml
Labels: O-robot, blathers-backport, backport

#154795 release-25.4: sql: skip a big test that ooms on the race detector
  pkg/sql/sem/tree/pretty_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#154753 release-25.4: sql/inspect: add job metrics for INSPECT jobs
  docs/generated/metrics/metrics.yaml
  pkg/jobs/metrics.go
  pkg/sql/inspect/BUILD.bazel
  pkg/sql/inspect/inspect_job.go
  pkg/sql/inspect/inspect_logger.go
  pkg/sql/inspect/inspect_metrics.go
  pkg/sql/inspect/inspect_metrics_test.go
  pkg/sql/inspect/inspect_processor.go
Labels: T-sql-foundations, backport

#154832 release 25.4: roachtest: remove per-table PTS setting from frontier persistence tests
  pkg/cmd/roachtest/tests/cdc.go
Labels: T-cdc, backport, backport-test-only

#154842 rpc: respect interceptors ServerOption in NewDRPCServer
  pkg/rpc/drpc.go
  pkg/rpc/drpc_test.go
Labels: backport-25.4.x

#154845 release-25.4: rpc: respect interceptors ServerOption in NewDRPCServer
  pkg/rpc/drpc.go
  pkg/rpc/drpc_test.go
Labels: O-robot, blathers-backport, backport

#154898 release-25.2: roachtest: increase closed TS lag in copyfrom roachtest
  pkg/cmd/roachtest/tests/copyfrom.go
Labels: O-robot, T-sql-queries, blathers-backport, backport, backport-test-only

#154907 release-25.4: roachtest: increase closed TS lag in copyfrom roachtest
  pkg/cmd/roachtest/tests/copyfrom.go
Labels: O-robot, T-sql-queries, blathers-backport, backport, backport-test-only

#154910 release-24.3: roachtest: increase closed TS lag in copyfrom roachtest
  pkg/cmd/roachtest/tests/copyfrom.go
Labels: O-robot, T-sql-queries, blathers-backport, backport, backport-test-only

#154911 release-24.1: roachtest: increase closed TS lag in copyfrom roachtest
  pkg/cmd/roachtest/tests/copyfrom.go
Labels: O-robot, T-sql-queries, blathers-backport, backport, backport-test-only

#154756 release-25.4: sql: update stats for descriptor table
  pkg/sql/catalog/descs/collection.go
  pkg/sql/catalog/schematelemetry/BUILD.bazel
  pkg/sql/catalog/schematelemetry/schema_telemetry_job.go
  pkg/sql/conn_executor.go
  pkg/sql/schema_changer.go
  pkg/sql/schema_changer_metrics.go
  pkg/sql/schemachanger/schemachanger_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#154802 changefeedccl: fix unwatched column families memory monitoring bug
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_memory_test.go
  pkg/ccl/changefeedccl/event_processing.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.2.x, backport-25.3.x, backport-25.4.x

#154797 release-25.4: partitionccl: skip TestAlterPrimaryKeyCorrectZoneConfigBeforeBackfill under deadlock
  pkg/ccl/partitionccl/BUILD.bazel
  pkg/ccl/partitionccl/alter_primary_key_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#154921 release-25.2: roachtest: update liquibase test harness
  pkg/cmd/roachtest/tests/liquibase.go
  pkg/cmd/roachtest/tests/liquibase_blocklist.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#154867 go.mod: bump datadriven
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport-25.4.x

#154906 release-25.4: crosscluster/physical: add alter connection watcher
  pkg/crosscluster/logical/logical_replication_job.go
  pkg/crosscluster/physical/replication_stream_e2e_test.go
  pkg/crosscluster/physical/stream_ingestion_dist.go
  pkg/crosscluster/replicationutils/BUILD.bazel
  pkg/crosscluster/replicationutils/connection_checker.go
  pkg/sql/exec_util.go
Labels: T-disaster-recovery, backport

#154967 release-25.3.3-rc: roachtest: disable schema_locked for ORM tests using root
  pkg/cmd/roachtest/tests/orm_helpers.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#154953 release-25.4: changefeedccl: make bulk delivery of rangefeed events optional
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeedbase/settings.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed_test.go
  pkg/ccl/changefeedccl/kvfeed/physical_kv_feed.go
Labels: T-cdc, backport

#154974 release-25.3: go.mod: bump Pebble to be8f5f5a9e13
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: T-storage, backport

#154355 release-25.3: server: only auto-upgrade system tenant from meta1 leaseholder
  pkg/clusterversion/setting.go
  pkg/server/auto_upgrade.go
Labels: O-robot, T-kv, blathers-backport, backport

#154353 release-24.3: server: only auto-upgrade system tenant from meta1 leaseholder
  pkg/clusterversion/setting.go
  pkg/server/auto_upgrade.go
Labels: O-robot, T-kv, blathers-backport, backport

#154352 release-24.1: server: only auto-upgrade system tenant from meta1 leaseholder
  pkg/clusterversion/setting.go
  pkg/server/auto_upgrade.go
Labels: O-robot, T-kv, blathers-backport, backport

#155011 release-25.3: roachtest: deflake c2c/disconnect
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: O-robot, T-disaster-recovery, blathers-backport, backport, backport-test-only

#155010 release-25.2: roachtest: deflake c2c/disconnect
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: O-robot, T-disaster-recovery, blathers-backport, backport, backport-test-only

#154794 release-24.3: workflows: update names of GitHub Action runner groups
  .github/workflows/github-actions-essential-ci.yml
Labels: backport

#154793 release-24.1: workflows: update names of GitHub Action runner groups
  .github/workflows/github-actions-essential-ci.yml
Labels: backport

#155022 kvserver: disable buffered sender
  pkg/kv/kvserver/replica_rangefeed.go
Labels: backport, T-cli

#155024 release-24.3: changefeedccl: fix unwatched column families memory monitoring bug
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_memory_test.go
  pkg/ccl/changefeedccl/event_processing.go
Labels: T-cdc, backport

#155025 release-24.1: changefeedccl: fix unwatched column families memory monitoring bug
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_memory_test.go
  pkg/ccl/changefeedccl/event_processing.go
Labels: T-cdc, backport
