Repository cockroachdb/cockroach, pull requests merged in 2025-04, with the labels that each got.

#143772 release-25.1: explain: fix recently added TestRetryFields
  pkg/sql/opt/exec/explain/output_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#143770 release-24.1: explain: fix recently added TestRetryFields
  pkg/sql/opt/exec/explain/output_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#143771 release-24.3: explain: fix recently added TestRetryFields
  pkg/sql/opt/exec/explain/output_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#141767 insights: insights and sqlstats subsystem should consume the same types
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_util.go
  pkg/sql/executor_statement_metrics.go
  pkg/sql/instrumentation_test.go
  pkg/sql/sqlstats/insights/BUILD.bazel
  pkg/sql/sqlstats/insights/detector.go
  pkg/sql/sqlstats/insights/detector_test.go
  pkg/sql/sqlstats/insights/ingester.go
  pkg/sql/sqlstats/insights/ingester_test.go
  pkg/sql/sqlstats/insights/insights_test.go
  pkg/sql/sqlstats/insights/registry.go
  pkg/sql/sqlstats/insights/registry_test.go
  pkg/sql/sqlstats/insights/test_utils.go
  pkg/sql/sqlstats/insights/util.go
  pkg/sql/sqlstats/persistedsqlstats/bench_test.go
  pkg/sql/sqlstats/sslocal/sql_stats_test.go
  pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go
  pkg/sql/sqlstats/ssmemstorage/ss_mem_writer.go
  pkg/sql/sqlstats/ssmemstorage/ss_mem_writer_test.go
Labels: o-perf-efficiency, T-microbench-post

#143735 jsonpath: validate regular expression during parsing
  pkg/sql/logictest/testdata/logic_test/jsonpath
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/generator_builtins.go
  pkg/util/jsonpath/eval/BUILD.bazel
  pkg/util/jsonpath/eval/eval.go
  pkg/util/jsonpath/eval/operation.go
  pkg/util/jsonpath/parser/jsonpath.y
  pkg/util/jsonpath/parser/parse.go
  pkg/util/jsonpath/parser/testdata/jsonpath
Labels: target-release-25.2.0

#143777 colflow: fix flow-level stats for some dist plans in EXPLAIN ANALYZE
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/opt/exec/explain/output_test.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#143773 logical: require matching column ids when using the kv writer
  pkg/crosscluster/logical/create_logical_replication_stmt.go
  pkg/crosscluster/logical/logical_replication_job_test.go
  pkg/sql/catalog/tabledesc/logical_replication_helpers.go
Labels: branch-release-24.3, branch-release-25.1

#143790 microbench-ci: fix marker file name
  pkg/cmd/microbench-ci/run.go
  pkg/cmd/microbench-ci/testdata/regression.txt
Labels: target-release-25.2.0

#143797 WORKSPACE: upgrade `zlib`
  WORKSPACE
  build/bazelutil/distdir_files.bzl
Labels: backport-all

#139450 builtins: implement ST_3DLength
  docs/generated/sql/functions.md
  pkg/geo/geomfn/unary_operators.go
  pkg/geo/geomfn/unary_operators_test.go
  pkg/sql/logictest/testdata/logic_test/geospatial_zm
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/builtins/geo_builtins.go
Labels: O-community

#143803 build: update to fork of `knz/strtime`
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport-all

#143788 roachtest: tune leader lease kv/splits tests
  pkg/cmd/roachtest/tests/kv.go
Labels: target-release-25.2.0

#143798 release-24.3: go.mod: bump Pebble to 2e6f94506115
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#143799 release-24.1: go.mod: bump Pebble to efb9d76923c5
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#143843 release-23.2: build: update to fork of `knz/strtime`
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#143848 release-24.3: build: update to fork of `knz/strtime`
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#143840 release-25.1: build: update to fork of `knz/strtime`
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#143846 release-24.1: build: update to fork of `knz/strtime`
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#142068 sql: fix CDC expression planning for tables without columns
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/sql/distsql_plan_changefeed.go
Labels: O-community

#143853 release-25.1: crosscluster/logical: fix ALTER .. SET REPLICATION READ VIRTUAL CLUSTER
  pkg/crosscluster/physical/alter_replication_job.go
  pkg/crosscluster/physical/alter_replication_job_test.go
  pkg/crosscluster/physical/stream_ingestion_planning.go
Labels: backport, backport-24.3.x

#143905 release-24.3: release-25.1: crosscluster/logical: fix ALTER .. SET REPLICATION READ VIRTUAL CLUSTER
  pkg/ccl/crosscluster/physical/alter_replication_job.go
  pkg/ccl/crosscluster/physical/alter_replication_job_test.go
  pkg/ccl/crosscluster/physical/stream_ingestion_planning.go
Labels: backport

#143816 release-25.1: kvfeed: fix writer being closed with wrong error when drain fails
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/ccl/changefeedccl/kvevent/BUILD.bazel
  pkg/ccl/changefeedccl/kvevent/blocking_buffer.go
  pkg/ccl/changefeedccl/kvevent/testing_knobs.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/testing_knobs.go
Labels: backport

#143817 release-24.3: kvfeed: fix writer being closed with wrong error when drain fails
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/ccl/changefeedccl/kvevent/BUILD.bazel
  pkg/ccl/changefeedccl/kvevent/blocking_buffer.go
  pkg/ccl/changefeedccl/kvevent/testing_knobs.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/testing_knobs.go
Labels: backport

#143818 release-24.1: kvfeed: fix writer being closed with wrong error when drain fails
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/ccl/changefeedccl/kvevent/BUILD.bazel
  pkg/ccl/changefeedccl/kvevent/blocking_buffer.go
  pkg/ccl/changefeedccl/kvevent/testing_knobs.go
  pkg/ccl/changefeedccl/kvfeed/kv_feed.go
  pkg/ccl/changefeedccl/testing_knobs.go
Labels: backport

#143898 release-25.1: memo: check `insert_fast_path` for staleness
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
Labels: backport

#143821 kvserver: add test TestRangeFeedWithExcise
  pkg/kv/kvserver/deleted_external_sstable_test.go
Labels: target-release-25.2.0

#143952 release-25.1: stats: harden bucket adjustment for over-estimates
  pkg/sql/stats/histogram.go
  pkg/sql/stats/histogram_test.go
Labels: O-robot, blathers-backport, backport

#143953 release-24.3: stats: harden bucket adjustment for over-estimates
  pkg/sql/stats/histogram.go
  pkg/sql/stats/histogram_test.go
Labels: O-robot, blathers-backport, backport

#143954 release-24.1: stats: harden bucket adjustment for over-estimates
  pkg/sql/stats/histogram.go
  pkg/sql/stats/histogram_test.go
Labels: O-robot, blathers-backport, backport

#143794 release-25.1: colflow: fix flow-level stats for some dist plans in EXPLAIN ANALYZE
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/opt/exec/explain/BUILD.bazel
  pkg/sql/opt/exec/explain/output_test.go
Labels: O-robot, blathers-backport, backport

#143792 release-24.1: colflow: fix flow-level stats for some dist plans in EXPLAIN ANALYZE
  pkg/sql/colflow/vectorized_flow.go
  pkg/sql/opt/exec/explain/BUILD.bazel
  pkg/sql/opt/exec/explain/output_test.go
Labels: O-robot, blathers-backport, backport

#143992 release-24.3: released CockroachDB version 24.3.9. Next version: 24.3.10
  pkg/build/version.txt
Labels: backport

#143994 release-24.1: released CockroachDB version 24.1.15. Next version: 24.1.16
  pkg/build/version.txt
Labels: backport

#143997 release-23.2: released CockroachDB version 23.2.22. Next version: 23.2.23
  pkg/build/version.txt
Labels: backport

#143999 release-25.1: released CockroachDB version 25.1.3. Next version: 25.1.4
  pkg/build/version.txt
Labels: backport

#144027 sql: fix infinite loop in prepare/execute of PL/pgSQL loop
  pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql
  pkg/sql/opt/norm/factory.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.3.x, backport-25.1.x

#143895 release-25.1: explain: show "execution time" on EXPLAIN ANALYZE output
  pkg/ccl/logictestccl/testdata/logic_test/explain_call_plpgsql
  pkg/ccl/logictestccl/testdata/logic_test/triggers_explain
  pkg/sql/instrumentation.go
  pkg/sql/logictest/testdata/logic_test/generic
  pkg/sql/opt/exec/execbuilder/testdata/call
  pkg/sql/opt/exec/execbuilder/testdata/cascade
  pkg/sql/opt/exec/execbuilder/testdata/delete
  pkg/sql/opt/exec/execbuilder/testdata/dist_vectorize
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/exec/execbuilder/testdata/explain_analyze_plans
  pkg/sql/opt/exec/execbuilder/testdata/explain_analyze_read_committed
  pkg/sql/opt/exec/execbuilder/testdata/inverted_index_geospatial
  pkg/sql/opt/exec/execbuilder/testdata/inverted_join_geospatial
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join_limit
  pkg/sql/opt/exec/execbuilder/testdata/unique
  pkg/sql/opt/exec/execbuilder/testdata/update
  pkg/sql/opt/exec/execbuilder/testdata/upsert
  pkg/sql/opt/exec/execbuilder/testdata/vectorize_local
  pkg/sql/opt/exec/explain/emit.go
  pkg/sql/opt/exec/factory.go
Labels: backport

#143897 release-24.3: explain: show "execution time" on EXPLAIN ANALYZE output
  pkg/ccl/logictestccl/testdata/logic_test/explain_call_plpgsql
  pkg/ccl/logictestccl/testdata/logic_test/generic
  pkg/ccl/logictestccl/testdata/logic_test/triggers_explain
  pkg/sql/instrumentation.go
  pkg/sql/opt/exec/execbuilder/testdata/call
  pkg/sql/opt/exec/execbuilder/testdata/cascade
  pkg/sql/opt/exec/execbuilder/testdata/dist_vectorize
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/opt/exec/execbuilder/testdata/explain_analyze_plans
  pkg/sql/opt/exec/execbuilder/testdata/explain_analyze_read_committed
  pkg/sql/opt/exec/execbuilder/testdata/inverted_index_geospatial
  pkg/sql/opt/exec/execbuilder/testdata/inverted_join_geospatial
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join_limit
  pkg/sql/opt/exec/execbuilder/testdata/unique
  pkg/sql/opt/exec/execbuilder/testdata/vectorize_local
  pkg/sql/opt/exec/explain/emit.go
  pkg/sql/opt/exec/factory.go
Labels: backport

#144022 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144023 release-25.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144025 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144026 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144035 release-24.1: sql: fix infinite loop in prepare/execute of PL/pgSQL loop
  pkg/ccl/logictestccl/testdata/logic_test/udf_plpgsql
  pkg/sql/opt/norm/factory.go
Labels: backport, target-release-24.1.16

#143729 release-25.1: client cert expirations cached by usage
  pkg/BUILD.bazel
  pkg/security/BUILD.bazel
  pkg/security/auth.go
  pkg/security/cert_expiry_cache.go
  pkg/security/cert_expiry_cache_test.go
  pkg/security/certificate_manager.go
  pkg/security/clientcert/BUILD.bazel
  pkg/security/clientcert/cert_expiry_cache.go
  pkg/security/clientcert/cert_expiry_cache_test.go
  pkg/server/server_sql.go
  pkg/util/metric/aggmetric/agg_metric.go
  pkg/util/metric/aggmetric/counter.go
  pkg/util/metric/aggmetric/gauge.go
  pkg/util/metric/aggmetric/histogram.go
Labels: backport

#144075 release-23.2: released CockroachDB version 23.2.23. Next version: 23.2.24
  pkg/build/version.txt
Labels: backport

#144078 release-24.1: released CockroachDB version 24.1.16. Next version: 24.1.17
  pkg/build/version.txt
Labels: backport

#144082 release-24.3: released CockroachDB version 24.3.10. Next version: 24.3.11
  pkg/build/version.txt
Labels: backport

#144085 release-25.1: released CockroachDB version 25.1.4. Next version: 25.1.5
  pkg/build/version.txt
Labels: backport

#144072 ci: reduce concurrency of remote execution builds
  build/github/acceptance-test.sh
  build/github/build.sh
  build/github/check-generated-code.sh
  build/github/cockroach-microbench-ci.sh
  build/github/docker-image.sh
  build/github/examples-orms.sh
  build/github/lint.sh
  build/github/local-roachtest.sh
  build/github/microbenchmarks/build.sh
  build/github/microbenchmarks/util.sh
  build/github/prepare-summarize-build.sh
  build/github/unit-tests.sh
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#144095 release-23.2: schemachange/mixed-versions-compat: disable 23.1 corpus
  pkg/cmd/roachtest/tests/mixed_version_decl_schemachange_compat.go
Labels: backport

#144090 kvserver: add Store metrics for raft log size
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica_metrics.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/store.go
Labels: backport-all

#144047 sql: fix handle index expressions in declarative schema changer
  pkg/ccl/schemachangerccl/backup_base_generated_test.go
  pkg/sql/schemachanger/scbuild/builder_state.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_column.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go
  pkg/sql/schemachanger/scbuild/testdata/drop_index
  pkg/sql/schemachanger/scplan/testdata/drop_index
  pkg/sql/schemachanger/sctest_generated_test.go
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression.definition
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression.explain_shape
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression__rollback_1_of_8.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression__rollback_2_of_8.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression__rollback_3_of_8.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression__rollback_4_of_8.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression__rollback_5_of_8.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression__rollback_6_of_8.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression__rollback_7_of_8.explain
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression__rollback_8_of_8.explain
  pkg/sql/schemachanger/testdata/end_to_end/drop_index_partial_expression_index/drop_index_partial_expression_index.side_effects
Labels: target-release-25.2.0

#144055 release-24.3: pkg/cli: allow system.zones in debug zip
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/partial1_excluded
  pkg/cli/testdata/zip/partial2
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/testzip_concurrent
  pkg/cli/testdata/zip/testzip_exclude_goroutine_stacks
  pkg/cli/testdata/zip/testzip_exclude_range_info
  pkg/cli/testdata/zip/testzip_external_process_virtualization
  pkg/cli/testdata/zip/testzip_fallback
  pkg/cli/testdata/zip/testzip_include_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_range_info
  pkg/cli/testdata/zip/testzip_redacted
  pkg/cli/testdata/zip/testzip_shared_process_virtualization
  pkg/cli/testdata/zip/testzip_shared_process_virtualization_with_default_tenant
  pkg/cli/zip_table_registry.go
  pkg/cli/zip_table_registry_test.go
Labels: backport, target-release-24.3.11

#142579 release-23.2: configprofiles: remove flaky `TestProfilesValidSQL`
  pkg/configprofiles/BUILD.bazel
  pkg/configprofiles/profiles_test.go
  pkg/configprofiles/testdata/virtual-app
  pkg/configprofiles/testdata/virtual-app-repl
  pkg/configprofiles/testdata/virtual-noapp
  pkg/configprofiles/testdata/virtual-noapp-repl
Labels: backport, backport-23.2.x

#144159 release-24.1: go.mod: bump Pebble to 431a23b680c1
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#144158 release-23.2: go.mod: bump Pebble to 43942af2ec47
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#144155 release-24.3: go.mod: bump Pebble to 0bfd4a266588
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#144154 release-25.1: go.mod: bump Pebble to d25896594ff8
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#144174 release-24.1: ci: prioritize `staging-*` builds higher
  build/github/engflow-args.sh
Labels: backport

#144175 release-24.3: ci: prioritize `staging-*` builds higher
  build/github/engflow-args.sh
Labels: backport

#144176 release-25.1: ci: prioritize `staging-*` builds higher
  build/github/engflow-args.sh
Labels: backport

#144056 release-24.1: pkg/cli: allow system.zones in debug zip
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/partial1_excluded
  pkg/cli/testdata/zip/partial2
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/testzip_concurrent
  pkg/cli/testdata/zip/testzip_exclude_goroutine_stacks
  pkg/cli/testdata/zip/testzip_exclude_range_info
  pkg/cli/testdata/zip/testzip_external_process_virtualization
  pkg/cli/testdata/zip/testzip_fallback
  pkg/cli/testdata/zip/testzip_include_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_range_info
  pkg/cli/testdata/zip/testzip_shared_process_virtualization
  pkg/cli/testdata/zip/testzip_shared_process_virtualization_with_default_tenant
  pkg/cli/zip_table_registry.go
  pkg/cli/zip_table_registry_test.go
Labels: backport

#144057 release-23.2: pkg/cli: allow system.zones in debug zip
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/partial1_excluded
  pkg/cli/testdata/zip/partial2
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/testzip_concurrent
  pkg/cli/testdata/zip/testzip_exclude_goroutine_stacks
  pkg/cli/testdata/zip/testzip_exclude_range_info
  pkg/cli/testdata/zip/testzip_external_process_virtualization
  pkg/cli/testdata/zip/testzip_include_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_range_info
  pkg/cli/testdata/zip/testzip_shared_process_virtualization
  pkg/cli/testdata/zip/testzip_shared_process_virtualization_with_default_tenant
  pkg/cli/zip_table_registry.go
  pkg/cli/zip_table_registry_test.go
Labels: backport

#144173 release-25.2: run-pgo-build: select 1 profile late into the test per node per test
  pkg/cmd/run-pgo-build/main.go
Labels: O-robot, blathers-backport, backport

#144018 release-25.1: row: harden inconsistent scan machinery
  pkg/sql/create_stats_test.go
  pkg/sql/distsql_plan_stats.go
  pkg/sql/execinfra/server_config.go
  pkg/sql/execinfrapb/processors_sql.proto
  pkg/sql/row/fetcher.go
  pkg/sql/rowexec/tablereader.go
Labels: O-robot, blathers-backport, backport

#144017 release-24.3: row: harden inconsistent scan machinery
  pkg/sql/create_stats_test.go
  pkg/sql/distsql_plan_stats.go
  pkg/sql/execinfra/server_config.go
  pkg/sql/execinfrapb/processors_sql.proto
  pkg/sql/row/fetcher.go
  pkg/sql/rowexec/tablereader.go
Labels: O-robot, blathers-backport, backport

#143935 release-24.3: sql: rerun execbuilder for gist matching
  pkg/sql/conn_executor_exec.go
  pkg/sql/distsql_plan_changefeed.go
  pkg/sql/explain_bundle_test.go
  pkg/sql/instrumentation.go
  pkg/sql/opt/exec/execbuilder/builder.go
  pkg/sql/plan_opt.go
  pkg/sql/sql_cursor.go
Labels: backport

#144192 release-25.2: logictest: increase GC job interval for multi_region_zone_configs test
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_configs
Labels: O-robot, blathers-backport, backport, backport-test-only

#144191 release-25.2: build: update PGO profile
  WORKSPACE
Labels: O-robot, blathers-backport, backport

#144171 kvclient,sql: address a couple of TODOs for buffered writes
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
  pkg/kv/sender.go
  pkg/sql/txn_state.go
Labels: backport-25.2.x

#144197 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144198 release-25.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144199 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144200 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144202 release-25.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144203 release-25.2: kvclient,sql: address a couple of TODOs for buffered writes
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner_test.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
  pkg/kv/sender.go
  pkg/sql/txn_state.go
Labels: O-robot, blathers-backport, backport

#143923 jsonpath: add @ and LAST semantic checks over AST during parsing
  pkg/sql/logictest/testdata/logic_test/jsonb_path_query
  pkg/sql/logictest/testdata/logic_test/jsonpath
  pkg/util/jsonpath/parser/parse.go
  pkg/util/jsonpath/parser/testdata/jsonpath
Labels: backport-25.2.x

#144160 kvcoord: avoid erroneous rollback of buffered write
  pkg/kv/kvclient/kvcoord/txn_coord_sender_savepoints.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_test.go
Labels: backport-25.2.x

#144089 changefeedccl: fix test
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport-all

#144193 release-24.1: ci: reduce concurrency of remote execution builds
  build/github/acceptance-test.sh
  build/github/build.sh
  build/github/check-generated-code.sh
  build/github/docker-image.sh
  build/github/examples-orms.sh
  build/github/lint.sh
  build/github/local-roachtest.sh
  build/github/prepare-summarize-build.sh
  build/github/unit-tests.sh
Labels: backport

#144195 release-25.1: ci: reduce concurrency of remote execution builds
  build/github/acceptance-test.sh
  build/github/build.sh
  build/github/check-generated-code.sh
  build/github/cockroach-microbench-ci.sh
  build/github/docker-image.sh
  build/github/examples-orms.sh
  build/github/lint.sh
  build/github/local-roachtest.sh
  build/github/prepare-summarize-build.sh
  build/github/unit-tests.sh
Labels: backport

#144221 kvcoord: support stateful txn retries in txnWriteBuffer
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
  pkg/kv/kvclient/kvcoord/txn_test.go
Labels: A-buffered-writes, backport-25.2.x

#144006 builtins: add `jsonb_path_query_array`, `jsonb_path_query_first`, `jsonb_path_match`
  docs/generated/sql/functions.md
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/local-read-committed/generated_test.go
  pkg/ccl/logictestccl/tests/local-repeatable-read/generated_test.go
  pkg/sql/logictest/testdata/logic_test/jsonb_path_match
  pkg/sql/logictest/testdata/logic_test/jsonb_path_query_array
  pkg/sql/logictest/testdata/logic_test/jsonb_path_query_first
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/builtins/generator_builtins.go
  pkg/util/jsonpath/eval/eval.go
Labels: backport-25.2.x

#144180 fix: ttl job description doesnot quote key column
  pkg/sql/ttl/ttlschedule/BUILD.bazel
  pkg/sql/ttl/ttlschedule/ttlschedule.go
Labels: O-community

#144295 release-25.2: kvcoord: support stateful txn retries in txnWriteBuffer
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
  pkg/kv/kvclient/kvcoord/txn_test.go
Labels: backport

#144307 logictest: raise TxnLivenessThreshold for multitenant configs
  pkg/sql/logictest/BUILD.bazel
  pkg/sql/logictest/logic.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x

#143932 backup: add cluster setting to skip compacted backups during restore
  pkg/backup/backupdest/backup_destination.go
  pkg/backup/backupinfo/BUILD.bazel
  pkg/backup/backupinfo/manifest_handling.go
  pkg/backup/backupinfo/manifest_handling_test.go
  pkg/backup/backuppb/backup.proto
  pkg/backup/compaction_job.go
  pkg/backup/compaction_test.go
  pkg/backup/restore_planning.go
  pkg/backup/show.go
Labels: backport-25.2.x

#144306 sql: disable buffered writes for internal executor
  pkg/sql/internal.go
Labels: backport-25.2.x

#144299 release-25.2: go.mod: bump Pebble to 9ffebb81407b
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#144323 workflows: double GitHub Actions Essential CI timeouts
  .github/workflows/github-actions-essential-ci.yml
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x

#144327 release-25.2: kvclient: let QueryLocks and LeaseInfo requests through txnWriteBuffer
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
Labels: backport

#144330 release-25.2: sql: disable buffered writes for internal executor
  pkg/sql/internal.go
Labels: O-robot, blathers-backport, backport

#144382 release-25.2: go.mod: bump Pebble to c7d64e9108fd
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#144117 storage: enable new format major version
  pkg/cli/testdata/ear-list
  pkg/storage/pebble.go
Labels: backport-25.2.x

#144313 release-25.2: logictest: raise TxnLivenessThreshold for multitenant configs
  pkg/sql/logictest/BUILD.bazel
  pkg/sql/logictest/logic.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#144312 release-25.1: logictest: raise TxnLivenessThreshold for multitenant configs
  pkg/sql/logictest/BUILD.bazel
  pkg/sql/logictest/logic.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#144387 release-25.2: released CockroachDB version 25.2.0-beta.1. Next version: 25.2.0-beta.2
  pkg/build/version.txt
Labels: backport

#144309 jobs: add jobs.avoid_full_scans.enabled
  pkg/jobs/BUILD.bazel
  pkg/jobs/utils.go
  pkg/spanconfig/spanconfigmanager/manager.go
  pkg/spanconfig/spanconfigmanager/manager_test.go
  pkg/spanconfig/spanconfigmanager/test_helpers.go
  pkg/sql/create_stats.go
Labels: backport-all

#144356 release-25.1: go.mod: bump Pebble to 006ab63f0087
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#144413 release-25.2: logictestccl: wait for tenant overrides to propagate in multi_region_secondary_tenants_abstractions_allowed
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_secondary_tenants_abstractions_allowed
Labels: O-robot, blathers-backport, backport, backport-test-only

#144260 sql: store JSONPath AST in Datum
  pkg/sql/logictest/testdata/logic_test/jsonb_path_query
  pkg/sql/opt/memo/interner.go
  pkg/sql/parser/statements/statement.go
  pkg/sql/pgwire/pgwirebase/BUILD.bazel
  pkg/sql/pgwire/pgwirebase/encoding.go
  pkg/sql/randgen/datum.go
  pkg/sql/sem/eval/cast.go
  pkg/sql/sem/tree/BUILD.bazel
  pkg/sql/sem/tree/datum.go
  pkg/sql/sem/tree/datum_alloc.go
  pkg/util/jsonpath/BUILD.bazel
  pkg/util/jsonpath/eval/eval.go
  pkg/util/jsonpath/expr.go
  pkg/util/jsonpath/parser/parse.go
  pkg/util/jsonpath/parser/parser_test.go
Labels: backport-25.2.x

#144331 release-24.1: workflows: double GitHub Actions Essential CI timeouts
  .github/workflows/github-actions-essential-ci.yml
Labels: O-robot, blathers-backport, backport

#144332 release-24.3: workflows: double GitHub Actions Essential CI timeouts
  .github/workflows/github-actions-essential-ci.yml
Labels: O-robot, blathers-backport, backport

#144333 release-25.1: workflows: double GitHub Actions Essential CI timeouts
  .github/workflows/github-actions-essential-ci.yml
Labels: O-robot, blathers-backport, backport

#144345 ci: sign nightly and customized darwin builds
  build/teamcity/internal/cockroach/release/publish/sign_staged_macos_release_on_linux.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-darwin-sign.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-per-platform.sh
  build/teamcity/internal/release/process/make-and-publish-build-tagging.sh
  build/teamcity/internal/release/sign-patched-go.sh
  scripts/tag-custom-build.sh
Labels: C-enhancement, A-ci, T-release, backport-all

#144435 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144434 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144433 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144440 release-25.1: toolchain: sign MacOS Go binaries on Linux
  build/teamcity/internal/release/sign-patched-go.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#144439 release-24.3: toolchain: sign MacOS Go binaries on Linux
  build/teamcity/internal/release/sign-patched-go.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#144377 metrics: add SQLCounter to support high cardinality metrics
  pkg/util/metric/aggmetric/agg_metric.go
  pkg/util/metric/aggmetric/agg_metric_test.go
  pkg/util/metric/aggmetric/counter.go
  pkg/util/metric/aggmetric/counter_test.go
  pkg/util/metric/aggmetric/testdata/SQLCounter_post_eviction.txt
  pkg/util/metric/aggmetric/testdata/SQLCounter_pre_eviction.txt
  pkg/util/metric/aggmetric/testdata/aggCounter_post_eviction.txt
  pkg/util/metric/aggmetric/testdata/aggCounter_pre_eviction.txt
  pkg/util/metric/aggmetric/testdata/aggMetric_pre_clear.txt
Labels: backport, backport-25.2.x

#144461 kvserver: skip TestLeasePreferencesDuringOutage under duress
  pkg/kv/kvserver/client_lease_test.go
Labels: backport-25.1.x, backport-25.2.x

#144381 release-24.1: kvserver: add Store metrics for raft log size
  docs/generated/metrics/metrics.html
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/replica_metrics.go
  pkg/kv/kvserver/replica_test.go
  pkg/kv/kvserver/store.go
Labels: backport

#144460 kvserver: skip TestLeaseQueueShedsOnIOOverload under duress
  pkg/kv/kvserver/lease_queue_test.go
Labels: backport-25.1.x, backport-25.2.x

#144467 release-25.2: kvserver: skip TestLeaseQueueShedsOnIOOverload under duress
  pkg/kv/kvserver/lease_queue_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#144300 authors: Add Abhishek Munnolimath to Authors
  AUTHORS
Labels: first-pr

#144484 release-25.2: workflows: double GitHub Actions Essential CI timeouts
  .github/workflows/github-actions-essential-ci.yml
Labels: O-robot, blathers-backport, backport

#144501 schemachange: run test on `heavy` pool
  pkg/ccl/testccl/workload/schemachange/BUILD.bazel
Labels: backport-25.1.x, backport-25.2.x

#144507 release-25.2: schemachange: run test on `heavy` pool
  pkg/ccl/testccl/workload/schemachange/BUILD.bazel
Labels: O-robot, blathers-backport, backport

#144217 sql,optbuilder: route descriptor lookups for triggers through cache
  pkg/bench/rttanalysis/BUILD.bazel
  pkg/bench/rttanalysis/testdata/benchmark_expectations
  pkg/bench/rttanalysis/trigger_resolution_test.go
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/sql/opt/cat/catalog.go
  pkg/sql/opt/cat/table.go
  pkg/sql/opt/exec/explain/plan_gist_factory.go
  pkg/sql/opt/optbuilder/trigger.go
  pkg/sql/opt/testutils/testcat/create_table.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/opt_catalog.go
  pkg/sql/planner.go
Labels: backport-25.2.x

#144464 release-25.1: kvserver: skip TestLeasePreferencesDuringOutage under duress
  pkg/kv/kvserver/client_lease_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#144465 release-25.2: kvserver: skip TestLeasePreferencesDuringOutage under duress
  pkg/kv/kvserver/client_lease_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#144534 release-25.1: roachtest: provision admission-control/database-drop with 800GiB/node
  pkg/cmd/roachtest/tests/admission_control_database_drop.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#144538 release-25.2: roachtest: provision admission-control/database-drop with 800GiB/node
  pkg/cmd/roachtest/tests/admission_control_database_drop.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#144551 release-25.2: sql: only use side-effect splitter if locking durability = guaranteed
  pkg/ccl/logictestccl/testdata/logic_test/read_committed
  pkg/sql/distsql_physical_planner.go
Labels: backport

#144549 release-25.2: sql: revert "builtins: implement ST_3DLength"
  docs/generated/sql/functions.md
  pkg/geo/geomfn/unary_operators.go
  pkg/geo/geomfn/unary_operators_test.go
  pkg/sql/logictest/testdata/logic_test/geospatial_zm
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/builtins/geo_builtins.go
Labels: target-release-25.2.0

#144550 release-24.1: sql: avoid unnecessary version bumps for UDTs during ALTER TABLE
  pkg/ccl/backupccl/restore_job.go
  pkg/sql/alter_table_locality.go
  pkg/sql/catalog/typedesc/type_desc.go
  pkg/sql/create_table.go
  pkg/sql/drop_type.go
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schema_changer.go
Labels: backport

#144552 release-23.2: sql: avoid unnecessary version bumps for UDTs during ALTER TABLE
  pkg/ccl/backupccl/restore_job.go
  pkg/sql/alter_table_locality.go
  pkg/sql/catalog/typedesc/type_desc.go
  pkg/sql/create_table.go
  pkg/sql/drop_type.go
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schema_changer.go
Labels: backport

#144536 opt: allow additional projections in vector search rule
  pkg/sql/opt/xform/limit_funcs.go
  pkg/sql/opt/xform/rules/limit.opt
  pkg/sql/opt/xform/testdata/rules/limit
Labels: backport-25.2.x

#144519 release-24.1: row: harden inconsistent scan machinery
  pkg/sql/create_stats_test.go
  pkg/sql/distsql_plan_stats.go
  pkg/sql/execinfra/server_config.go
  pkg/sql/execinfrapb/processors_sql.proto
  pkg/sql/row/fetcher.go
  pkg/sql/rowexec/tablereader.go
Labels: O-robot, blathers-backport, backport

#144581 release-25.2: vector index non-transactional fixups
  pkg/cmd/vecbench/main.go
  pkg/cmd/vecbench/mem_provider.go
  pkg/sql/backfill/backfill.go
  pkg/sql/rowenc/index_encoding_test.go
  pkg/sql/vecindex/cspann/BUILD.bazel
  pkg/sql/vecindex/cspann/childkey_dedup.go
  pkg/sql/vecindex/cspann/childkey_dedup_test.go
  pkg/sql/vecindex/cspann/commontest/BUILD.bazel
  pkg/sql/vecindex/cspann/commontest/storetests.go
  pkg/sql/vecindex/cspann/commontest/utils.go
  pkg/sql/vecindex/cspann/fixup_worker.go
  pkg/sql/vecindex/cspann/fixup_worker_test.go
  pkg/sql/vecindex/cspann/index.go
  pkg/sql/vecindex/cspann/index_test.go
  pkg/sql/vecindex/cspann/memstore/memstore.go
  pkg/sql/vecindex/cspann/memstore/memstore_test.go
  pkg/sql/vecindex/cspann/memstore/memstore_txn.go
  pkg/sql/vecindex/cspann/partition.go
  pkg/sql/vecindex/cspann/partition_metadata.go
  pkg/sql/vecindex/cspann/partition_test.go
  pkg/sql/vecindex/cspann/search_set.go
  pkg/sql/vecindex/cspann/search_set_test.go
  pkg/sql/vecindex/cspann/searcher.go
  pkg/sql/vecindex/cspann/split_data.go
  pkg/sql/vecindex/cspann/store.go
  pkg/sql/vecindex/cspann/testdata/delete.ddt
  pkg/sql/vecindex/cspann/testdata/merge.ddt
  pkg/sql/vecindex/cspann/testdata/search-features.ddt
  pkg/sql/vecindex/cspann/testdata/search.ddt
  pkg/sql/vecindex/cspann/testdata/split-non-root-step.ddt
  pkg/sql/vecindex/cspann/testdata/split-root-step.ddt
  pkg/sql/vecindex/cspann/testdata/split.ddt
  pkg/sql/vecindex/cspann/testdata/test.ddt
  pkg/sql/vecindex/searcher.go
  pkg/sql/vecindex/searcher_test.go
  pkg/sql/vecindex/vecencoding/BUILD.bazel
  pkg/sql/vecindex/vecencoding/encoding.go
  pkg/sql/vecindex/vecencoding/encoding_test.go
  pkg/sql/vecindex/vecstore/BUILD.bazel
  pkg/sql/vecindex/vecstore/codec.go
  pkg/sql/vecindex/vecstore/codec_test.go
  pkg/sql/vecindex/vecstore/store.go
  pkg/sql/vecindex/vecstore/store_test.go
  pkg/sql/vecindex/vecstore/store_txn.go
Labels: backport

#144008 sqlstats,ui: collect and display count of generic query plans
  pkg/sql/appstatspb/app_stats.go
  pkg/sql/appstatspb/app_stats.proto
  pkg/sql/executor_statement_metrics.go
  pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_encoding_test.go
  pkg/sql/sqlstats/persistedsqlstats/sqlstatsutil/json_impl.go
  pkg/sql/sqlstats/ssmemstorage/ss_mem_writer.go
  pkg/sql/sqlstats/ssmemstorage/ss_mem_writer_test.go
  pkg/sql/sqlstats/ssprovider.go
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/planDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx
  pkg/ui/workspaces/cluster-ui/src/statementDetails/statementDetails.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/util/appStats/appStats.ts
  pkg/ui/workspaces/db-console/src/views/statements/statements.spec.tsx
Labels: backport-25.2.x

#144596 release-25.2: backfill: handle transaction retry for vector index backfill
  pkg/sql/backfill/BUILD.bazel
  pkg/sql/backfill/backfill.go
  pkg/sql/backfill/backfill_test.go
  pkg/sql/backfill/index_backfiller_cols_test.go
  pkg/sql/backfill/main_test.go
  pkg/sql/backfill/mvcc_index_merger_test.go
  pkg/sql/execinfra/server_config.go
  pkg/sql/rowexec/indexbackfiller.go
Labels: backport

#144561 sql: disable buffered writes for EXPLAIN of a DDL statement
  pkg/sql/conn_executor_ddl.go
  pkg/sql/logictest/testdata/logic_test/buffered_writes
  pkg/sql/sem/tree/stmt.go
Labels: backport-25.2.x

#144405 release-25.2: jsonpath: add support for `.size()`, `.type()` methods
  pkg/sql/logictest/testdata/logic_test/jsonb_path_query
  pkg/sql/logictest/testdata/logic_test/jsonpath
  pkg/sql/scanner/jsonpath_scan.go
  pkg/util/jsonpath/BUILD.bazel
  pkg/util/jsonpath/eval/BUILD.bazel
  pkg/util/jsonpath/eval/eval.go
  pkg/util/jsonpath/eval/method.go
  pkg/util/jsonpath/method.go
  pkg/util/jsonpath/parser/jsonpath.y
  pkg/util/jsonpath/parser/parse.go
  pkg/util/jsonpath/parser/testdata/jsonpath
Labels: backport

#144602 release-25.2: sql: disable buffered writes for EXPLAIN of a DDL statement
  pkg/sql/conn_executor_ddl.go
  pkg/sql/logictest/testdata/logic_test/buffered_writes
  pkg/sql/sem/tree/stmt.go
Labels: O-robot, blathers-backport, backport

#144510 release-25.2: sql: store JSONPath AST in Datum
  pkg/sql/logictest/testdata/logic_test/jsonb_path_query
  pkg/sql/opt/memo/interner.go
  pkg/sql/parser/statements/statement.go
  pkg/sql/pgwire/pgwirebase/BUILD.bazel
  pkg/sql/pgwire/pgwirebase/encoding.go
  pkg/sql/randgen/datum.go
  pkg/sql/sem/eval/cast.go
  pkg/sql/sem/tree/BUILD.bazel
  pkg/sql/sem/tree/datum.go
  pkg/sql/sem/tree/datum_alloc.go
  pkg/util/jsonpath/BUILD.bazel
  pkg/util/jsonpath/eval/eval.go
  pkg/util/jsonpath/expr.go
  pkg/util/jsonpath/parser/parse.go
  pkg/util/jsonpath/parser/parser_test.go
Labels: backport

#144556 ui: fix table page size option bug
  pkg/ui/workspaces/cluster-ui/src/indexDetailsPage/indexDetailsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/schemaInsights/schemaInsightsView.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsView.tsx
  pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsView.tsx
  pkg/ui/workspaces/cluster-ui/src/jobs/jobsPage/jobsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/schedules/schedulesPage/scheduleTable.tsx
  pkg/ui/workspaces/cluster-ui/src/sessions/sessionsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsPage/activeStatementsView.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionDetails/transactionDetails.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/activeTransactionsView.tsx
  pkg/ui/workspaces/cluster-ui/src/transactionsPage/transactionsPage.tsx
  pkg/ui/workspaces/cluster-ui/src/util/hooks.ts
  pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x

#144653 release-25.2: sql/schemachanger: gate CREATE POLICY in DSC prior to 25.2
  pkg/sql/logictest/testdata/logic_test/mixed_version_row_level_security
  pkg/sql/logictest/tests/local-mixed-25.1/generated_test.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_policy.go
Labels: O-robot, blathers-backport, backport

#144516 backup: integrate hot loop AC into backup compactions
  pkg/backup/backup_processor.go
  pkg/backup/backupsink/sst_sink_key_writer.go
  pkg/backup/backupsink/sst_sink_key_writer_test.go
  pkg/backup/compaction_processor.go
Labels: backport-25.2.x

#144588 backfill: cleanup vector index backfill
  pkg/sql/backfill/backfill.go
  pkg/sql/rowexec/indexbackfiller.go
Labels: backport-25.2.x

#144706 release-24.3: upgrademanager: skip TestPrecondition under race
  pkg/upgrade/upgrademanager/manager_external_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#144004 changefeedccl: fix premature shutdown due to schema change bug
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/resolvedspan/BUILD.bazel
  pkg/ccl/changefeedccl/resolvedspan/frontier.go
  pkg/ccl/changefeedccl/resolvedspan/frontier_test.go
Labels: backport-25.1.x, backport-25.2.x

#144601 release-25.2: optbuilder: disable mutation of vector indexes while backfilling
  pkg/sql/alter_primary_key.go
  pkg/sql/backfill/backfill_test.go
  pkg/sql/catalog/tabledesc/index.go
  pkg/sql/create_index.go
  pkg/sql/logictest/testdata/logic_test/vector_index
  pkg/sql/opt/cat/index.go
  pkg/sql/opt/exec/explain/plan_gist_factory.go
  pkg/sql/opt/indexrec/hypothetical_index.go
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/opt_catalog.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
Labels: backport

#144712 rowenc: handle encoding of NULL or missing vectors
  pkg/sql/logictest/testdata/logic_test/vector_index
  pkg/sql/row/vector_index.go
  pkg/sql/rowenc/index_encoding.go
  pkg/sql/rowexec/vector_search.go
  pkg/sql/vecindex/BUILD.bazel
  pkg/sql/vecindex/vecindex_test.go
Labels: backport-25.2.x

#144635 sql: disable buffered writes if ReturnRawMVCCValues needed
  pkg/sql/colfetcher/cfetcher.go
  pkg/sql/colfetcher/cfetcher_wrapper.go
  pkg/sql/colfetcher/colbatch_scan.go
  pkg/sql/colfetcher/index_join.go
  pkg/sql/logictest/testdata/logic_test/buffered_writes
  pkg/sql/row/fetcher.go
Labels: backport-25.2.x

#144644 backup: prevent compactions on locality aware backups
  pkg/backup/compaction_job.go
  pkg/backup/compaction_test.go
Labels: backport-25.2.x

#144722 release-25.2: sql: disable buffered writes if ReturnRawMVCCValues needed
  pkg/sql/colfetcher/cfetcher.go
  pkg/sql/colfetcher/cfetcher_wrapper.go
  pkg/sql/colfetcher/colbatch_scan.go
  pkg/sql/colfetcher/index_join.go
  pkg/sql/logictest/testdata/logic_test/buffered_writes
  pkg/sql/row/fetcher.go
Labels: O-robot, blathers-backport, backport

#144736 kvclient,sql: harden the code for buffered writes
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/sql/internal.go
Labels: backport-25.2.x

#144737 release-25.2: kvclient,sql: harden the code for buffered writes
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/sql/internal.go
Labels: O-robot, blathers-backport, backport
