Repository cockroachdb/cockroach, pull requests merged in 2025-08, with the labels that each got.

#150960 release-25.2: kvpb: avoid over redaction of prev_err field
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/kvpb/errors.proto
Labels: O-robot, blathers-backport, backport

#150956 release-24.3: kvpb: avoid over redaction of prev_err field
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/kvpb/errors.proto
Labels: O-robot, blathers-backport, backport

#150954 release-24.1: kvpb: avoid over redaction of prev_err field
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/kvpb/errors.proto
Labels: O-robot, blathers-backport, backport

#151148 backupinfo: fix error handling in desciter
  pkg/backup/backupinfo/BUILD.bazel
  pkg/backup/backupinfo/desc_sst.go
  pkg/backup/backupinfo/desc_sst_test.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x, backport-25.3.x

#151141 release-24.3: security: fix memory accounting issue in client certificate cache
  pkg/security/clientcert/cert_expiry_cache.go
  pkg/security/clientcert/cert_expiry_cache_test.go
Labels: backport

#151146 release-25.2: security: fix memory accounting issue in client certificate cache
  pkg/security/clientcert/cert_expiry_cache.go
  pkg/security/clientcert/cert_expiry_cache_test.go
Labels: backport

#151206 release-25.1: released CockroachDB version v25.1.10. Next version: v25.1.11
  pkg/build/version.txt
Labels: backport, backport-test-only

#151203 release-24.3: released CockroachDB version v24.3.17. Next version: v24.3.18
  pkg/build/version.txt
Labels: backport, backport-test-only

#151161 release-25.2: colexec: fix column type when ConstNullOp is used
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/colexec/colexecbase/const.eg.go
  pkg/sql/colexec/colexecbase/const_tmpl.go
  pkg/sql/sem/eval/eval_test/BUILD.bazel
  pkg/sql/sem/eval/eval_test/eval_test.go
  pkg/sql/sem/eval/testdata/eval/boolean
  pkg/sql/sem/tree/type_check.go
Labels: backport

#151264 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#151265 release-25.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#151267 release-25.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#151268 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#151269 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#151262 release-25.3: go.mod: bump Pebble to d7e89db0ec0e
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/kv/kvserver/kvstorage/snaprecv/testdata/echotest/TestMultiSSTWriterInitSST_interesting=false
  pkg/kv/kvserver/kvstorage/snaprecv/testdata/echotest/TestMultiSSTWriterInitSST_interesting=true
Labels: backport

#151127 workload/schemachanger: address drop column flake
  pkg/workload/schemachange/error_screening.go
Labels: backport-25.1.x, backport-25.2.x, backport-25.3.x

#151367 kv: include tracing for split QueryIntent requests
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/txn_test.go
  pkg/sql/opt/exec/execbuilder/testdata/show_trace
  pkg/sql/opt/exec/execbuilder/testdata/upsert
Labels: backport-all

#151371 release-25.1: workload/schemachanger: address drop column flake
  pkg/workload/schemachange/error_screening.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#151404 roachtest: disable skip upgrades for rebalance load mixed version tests
  pkg/cmd/roachtest/tests/rebalance_load.go
Labels: backport, backport-test-only

#151343 release-24.1: changefeedccl: protobuf encoder randomized test for all types
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/sql/crdb_internal.go
Labels: backport

#151346 release-25.1: changefeedccl: protobuf encoder randomized test for all types
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/sql/crdb_internal.go
Labels: backport

#151348 release-25.3: changefeedccl: protobuf encoder randomized test for all types
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/helpers_test.go
  pkg/sql/crdb_internal.go
Labels: backport

#151418 release-25.3: sctest: decrease sampling rate for random BACKUPs
  pkg/sql/schemachanger/sctest/backup.go
Labels: backport

#151247 release-25.3: cli: explicitly set disallow_full_table_scans for debug.zips
  pkg/cli/testdata/zip/testzip_disallow_full_scans
  pkg/cli/zip.go
  pkg/cli/zip_test.go
Labels: backport

#151437 release-25.3: roachtest: deflake psycopg
  pkg/cmd/roachtest/tests/psycopg_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#151435 release-25.2: roachtest: deflake psycopg
  pkg/cmd/roachtest/tests/psycopg_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#151282 unify publish-artifacts and publish-provisional-artifacts commands
  build/teamcity/cockroach/post-merge/publish-bleeding-edge-per-platform.sh
  build/teamcity/internal/release/process/build-cockroach-release-per-platform.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-per-platform.sh
  pkg/BUILD.bazel
  pkg/cmd/publish-artifacts/BUILD.bazel
  pkg/cmd/publish-artifacts/main.go
  pkg/cmd/publish-artifacts/main_test.go
  pkg/cmd/publish-provisional-artifacts/BUILD.bazel
  pkg/cmd/publish-provisional-artifacts/main.go
  pkg/cmd/publish-provisional-artifacts/main_test.go
  pkg/release/build.go
  pkg/release/upload.go
Labels: C-enhancement, A-release, T-release, backport-25.3.x

#151443 release-25.3: unify publish-artifacts and publish-provisional-artifacts commands
  build/teamcity/cockroach/post-merge/publish-bleeding-edge-per-platform.sh
  build/teamcity/internal/release/process/build-cockroach-release-per-platform.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-per-platform.sh
  pkg/BUILD.bazel
  pkg/cmd/publish-artifacts/BUILD.bazel
  pkg/cmd/publish-artifacts/main.go
  pkg/cmd/publish-artifacts/main_test.go
  pkg/cmd/publish-provisional-artifacts/BUILD.bazel
  pkg/cmd/publish-provisional-artifacts/main.go
  pkg/cmd/publish-provisional-artifacts/main_test.go
  pkg/release/build.go
  pkg/release/upload.go
Labels: O-robot, blathers-backport, backport

#151475 release-25.3: workflow: check PR base branch
  .github/bors.toml
  .github/workflows/check-pr-base.yml
Labels: O-robot, blathers-backport, backport

#151476 release-24.3: workflow: check PR base branch
  .github/bors.toml
  .github/workflows/check-pr-base.yml
Labels: O-robot, blathers-backport, backport

#151445 release-24.1: workflow: check PR base branch
  .github/bors.toml
  .github/workflows/check-pr-base.yml
Labels: O-robot, blathers-backport, backport

#151464 release-25.2: workload/schemachanger: enhance logging for hung queries
  pkg/workload/schemachange/schemachange.go
  pkg/workload/schemachange/watch_dog.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#151490 release-24.1: sql/ttl: improve TTL replan decision logic
  pkg/cmd/roachtest/tests/ttl_restart.go
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_internal_test.go
Labels: backport

#151485 release-25.2: sql/ttl: improve TTL replan decision logic
  pkg/cmd/roachtest/tests/ttl_restart.go
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_internal_test.go
Labels: backport

#151483 release-25.3: sql/ttl: improve TTL replan decision logic
  pkg/cmd/roachtest/tests/ttl_restart.go
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_internal_test.go
Labels: backport

#151431 sql/lease: add progress logging to orphaned lease cleanup
  pkg/sql/catalog/lease/lease.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.2.x, backport-25.3.x

#151531 release-24.3: sql/lease: add progress logging to orphaned lease cleanup
  pkg/sql/catalog/lease/lease.go
Labels: O-robot, blathers-backport, backport

#151530 release-25.3: sql/lease: add progress logging to orphaned lease cleanup
  pkg/sql/catalog/lease/lease.go
Labels: O-robot, blathers-backport, backport

#151532 release-25.2: make and publish: tag staging repo early in process
  build/teamcity/internal/release/process/make-and-publish-build-start.sh
  build/teamcity/internal/release/process/make-and-publish-build.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#151535 release-24.1: make and publish: tag staging repo early in process
  build/teamcity/internal/release/process/make-and-publish-build-start.sh
  build/teamcity/internal/release/process/make-and-publish-build.sh
Labels: backport, backport-test-only

#151534 release-24.3: make and publish: tag staging repo early in process
  build/teamcity/internal/release/process/make-and-publish-build-start.sh
  build/teamcity/internal/release/process/make-and-publish-build.sh
Labels: backport, backport-test-only

#151533 release-25.3: make and publish: tag staging repo early in process
  build/teamcity/internal/release/process/make-and-publish-build-start.sh
  build/teamcity/internal/release/process/make-and-publish-build.sh
Labels: backport, backport-test-only

#151544 release-25.3: colexecerror: further optimize BenchmarkSQLCatchVectorizedRuntimeError
  pkg/sql/colexecerror/error_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#151561 release-24.3.19-rc: released CockroachDB version v24.3.18. Next version: v24.3.19
  pkg/build/version.txt
Labels: backport, backport-test-only

#151562 release-24.3: released CockroachDB version v24.3.18. Next version: v24.3.19
  pkg/build/version.txt
Labels: backport, backport-test-only

#151558 release-25.3: roachtest/asyncpg: ignore flaky TestExecuteMany test
  pkg/cmd/roachtest/tests/asyncpg_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#151554 release-24.1: roachtest/asyncpg: ignore flaky TestExecuteMany test
  pkg/cmd/roachtest/tests/asyncpg_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#151546 sql/schemachanger: fix sequence dependency tracking for triggers
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/sql/catalog/BUILD.bazel
  pkg/sql/catalog/funcdesc/func_desc.go
  pkg/sql/catalog/funcdesc/func_desc_test.go
  pkg/sql/catalog/tabledesc/validate.go
  pkg/sql/catalog/validate.go
  pkg/sql/schemachanger/scexec/scmutationexec/references.go
Labels: backport-25.3.x

#151593 release-25.3: sql/schemachanger: fix sequence dependency tracking for triggers
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/sql/catalog/BUILD.bazel
  pkg/sql/catalog/funcdesc/func_desc.go
  pkg/sql/catalog/funcdesc/func_desc_test.go
  pkg/sql/catalog/tabledesc/validate.go
  pkg/sql/catalog/validate.go
  pkg/sql/schemachanger/scexec/scmutationexec/references.go
Labels: O-robot, blathers-backport, backport

#151569 release-25.3: roachtest: Skip rangelog endpoint in db-console/endpoints roachtest
  pkg/cmd/roachtest/tests/db-console/admin_endpoints.json
Labels: O-robot, blathers-backport, backport, backport-test-only

#151573 interactive_tests: wait for liveness upreplication
  pkg/cli/interactive_tests/test_demo_node_cmds.tcl
Labels: backport-all

#151596 release-25.3: compose: deflake TestComposeCompare
  pkg/compose/compare/compare/compare_test.go
  pkg/sql/randgen/mutator.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#151617 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#151619 release-25.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#151622 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#144735 changefeedccl: support camelCase parameter names for Azure Event Hub sink configuration
  pkg/ccl/changefeedccl/changefeed.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/changefeedbase/options.go
  pkg/ccl/changefeedccl/sink_external_connection.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_kafka_connection_test.go
Labels: O-community

#151541 stmtdiagnostics: de-flake TestDiagnosticsRequest
  pkg/sql/stmtdiagnostics/statement_diagnostics_test.go
Labels: backport-25.3.x

#151704 release-25.3: stmtdiagnostics: de-flake TestDiagnosticsRequest
  pkg/sql/stmtdiagnostics/statement_diagnostics_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#151764 release-25.3: roachtest: deflake hibernate timeouts
  pkg/cmd/roachtest/tests/hibernate.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#151762 release-25.2: roachtest: deflake hibernate timeouts
  pkg/cmd/roachtest/tests/hibernate.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#151729 release-25.2: roachtest: Deprecating Snowflake User DATA_ENG_USER
  build/teamcity/cockroach/coverage/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_gce_force_profile.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_azure.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_perturbation.sh
  build/teamcity/internal/cockroach/nightlies/private_roachtest.sh
  pkg/cmd/roachtest/main_test.go
  pkg/cmd/roachtest/testselector/selector.go
  pkg/cmd/roachtest/testselector/selector_test.go
Labels: backport, backport-test-only

#151730 release-24.3: roachtest: Deprecating Snowflake User DATA_ENG_USER
  build/teamcity/cockroach/coverage/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_azure.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_perturbation.sh
  build/teamcity/internal/cockroach/nightlies/private_roachtest.sh
  pkg/cmd/roachtest/main_test.go
  pkg/cmd/roachtest/testselector/selector.go
  pkg/cmd/roachtest/testselector/selector_test.go
Labels: T-testeng, backport, backport-test-only

#151788 release-25.2: kvcoord: deflake TestDistSenderReplicaStall
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker_test.go
Labels: T-kv, backport

#151783 release-25.3: kvcoord: add regression test for buffered writes bug
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_client_test.go
Labels: backport

#151527 release-25.3: address change feed failure with drop column on a schema_locked table
  pkg/ccl/changefeedccl/cdcevent/BUILD.bazel
  pkg/ccl/changefeedccl/cdcevent/event.go
  pkg/ccl/changefeedccl/cdcevent/event_test.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/schemafeed/table_event_filter.go
  pkg/ccl/changefeedccl/schemafeed/testdata/drop_column
  pkg/sql/catalog/BUILD.bazel
  pkg/sql/catalog/descriptor.go
Labels: backport

#151792 release-25.3: catalog/lease: fix hang on range feed restart
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_test.go
Labels: T-sql-foundations, backport

#151815 release-25.3: go.mod: bump Pebble to caa9a3bf64fa
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#151814 release-25.2: go.mod: bump Pebble to cfa5233c966b
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#151528 release-25.2: address change feed failure with drop column on a schema_locked table
  pkg/ccl/changefeedccl/cdcevent/BUILD.bazel
  pkg/ccl/changefeedccl/cdcevent/event.go
  pkg/ccl/changefeedccl/cdcevent/event_test.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/schemafeed/table_event_filter.go
  pkg/ccl/changefeedccl/schemafeed/testdata/drop_column
  pkg/sql/catalog/BUILD.bazel
  pkg/sql/catalog/descriptor.go
Labels: backport

#151822 release-25.2: scplan: unredact logs for unable to make progress error
  pkg/sql/schemachanger/scplan/internal/scstage/build.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#151761 release-25.3: sctestbackupccl: deflake schemachanger tests during BACKUP
  pkg/sql/schemachanger/sctest/backup.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#151784 release-25.3.0-rc: disable replicated locking Get transforms
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_client_test.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
Labels: backport

#151873 release-25.3: amazon: add settings to control retry behavior
  pkg/cloud/amazon/BUILD.bazel
  pkg/cloud/amazon/aws_kms.go
  pkg/cloud/amazon/s3_storage.go
  pkg/cloud/amazon/s3_storage_test.go
Labels: T-disaster-recovery, backport

#151874 release-25.2: amazon: add settings to control retry behavior
  pkg/cloud/amazon/BUILD.bazel
  pkg/cloud/amazon/aws_kms.go
  pkg/cloud/amazon/s3_storage.go
  pkg/cloud/amazon/s3_storage_test.go
Labels: T-disaster-recovery, backport

#151875 release-24.3: amazon: add settings to control retry behavior
  pkg/cloud/amazon/BUILD.bazel
  pkg/cloud/amazon/aws_kms.go
  pkg/cloud/amazon/s3_storage.go
  pkg/cloud/amazon/s3_storage_test.go
Labels: T-disaster-recovery, backport

#151889 release-24.3: bazel: enable remote build on mesolite from linux
  .bazelrc
Labels: backport

#151885 release-25.3: bazel: enable remote build on mesolite from linux
  .bazelrc
Labels: backport

#151933 release-25.3: kvclient: de-flake tests due to metamorphic max_buffer_size
  pkg/ccl/logictestccl/testdata/logic_test/buffered_writes_lock_loss
  pkg/ccl/logictestccl/testdata/logic_test/cluster_locks_tenant_write_buffering
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_client_test.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
  pkg/kv/kvclient/kvcoord/txn_test.go
  pkg/sql/logictest/testdata/logic_test/as_of
  pkg/sql/logictest/testdata/logic_test/buffered_writes
  pkg/sql/logictest/testdata/logic_test/cluster_locks_write_buffering
  pkg/sql/opt/exec/execbuilder/testdata/autocommit
  pkg/sql/txn_restart_test.go
  pkg/sql/upsert_test.go
Labels: T-sql-queries, backport

#151938 release-25.2: status: add sys.host.net.send.tcp.retrans_segs (and friends)
  docs/generated/metrics/metrics.html
  pkg/server/status/BUILD.bazel
  pkg/server/status/runtime.go
  pkg/server/status/runtime_test.go
Labels: T-kv, backport

#151828 release-25.3: status: add sys.host.net.send.tcp.retrans_segs (and friends)
  docs/generated/metrics/metrics.yaml
  pkg/server/status/BUILD.bazel
  pkg/server/status/runtime.go
  pkg/server/status/runtime_test.go
Labels: T-kv, backport

#151923 kvserver: deflake TestTxnReadWithinUncertaintyIntervalAfterLeaseTransfer
  pkg/kv/kvserver/client_replica_test.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.2.x, backport-25.3.x

#151942 release-25.3.1-rc: kvclient: de-flake tests due to metamorphic max_buffer_size
  pkg/ccl/logictestccl/testdata/logic_test/buffered_writes_lock_loss
  pkg/ccl/logictestccl/testdata/logic_test/cluster_locks_tenant_write_buffering
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_client_test.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
  pkg/kv/kvclient/kvcoord/txn_test.go
  pkg/sql/logictest/testdata/logic_test/as_of
  pkg/sql/logictest/testdata/logic_test/buffered_writes
  pkg/sql/logictest/testdata/logic_test/cluster_locks_write_buffering
  pkg/sql/opt/exec/execbuilder/testdata/autocommit
  pkg/sql/txn_restart_test.go
  pkg/sql/upsert_test.go
Labels: O-robot, T-sql-queries, blathers-backport, backport

#151702 rpc: add RTT metrics to different RPC classes
  docs/generated/metrics/metrics.yaml
  pkg/ccl/kvccl/kvfollowerreadsccl/BUILD.bazel
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go
  pkg/roachprod/opentelemetry/cockroachdb_metrics.go
  pkg/rpc/BUILD.bazel
  pkg/rpc/clock_offset.go
  pkg/rpc/clock_offset_test.go
  pkg/rpc/heartbeat.go
  pkg/rpc/peer.go
Labels: backport-24.3.x, backport-25.2.x, backport-25.3.x

#151964 release-25.3: changefeedccl: disable schema_locked in TestChangefeedTruncateOrDrop
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: T-cdc, backport, backport-test-only

#151963 release-25.2: rpc: add RTT metrics to different RPC classes
  docs/generated/metrics/metrics.html
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go
  pkg/roachprod/opentelemetry/cockroachdb_metrics.go
  pkg/rpc/BUILD.bazel
  pkg/rpc/clock_offset.go
  pkg/rpc/clock_offset_test.go
  pkg/rpc/heartbeat.go
  pkg/rpc/peer.go
Labels: backport

#151965 release-24.3: rpc: add RTT metrics to different RPC classes
  docs/generated/metrics/metrics.html
  pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go
  pkg/roachprod/opentelemetry/cockroachdb_metrics.go
  pkg/rpc/BUILD.bazel
  pkg/rpc/clock_offset.go
  pkg/rpc/clock_offset_test.go
  pkg/rpc/heartbeat.go
  pkg/rpc/peer.go
Labels: backport

#151793 authors: add rudrakshsisodia to authors
  AUTHORS
Labels: first-pr

#152028 *: upgrade to Go 1.23.12
  .bazelrc
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/bootstrap/bootstrap-debian.sh
  build/teamcity/internal/release/build-and-publish-patched-go/commit.txt
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
  go.mod
  pkg/cmd/roachtest/tests/cdc.go
Labels: backport

#152093 release-25.2: *: upgrade to Go 1.23.12
  .bazelrc
  WORKSPACE
  build/bazelutil/distdir_files.bzl
  build/bootstrap/bootstrap-debian.sh
  build/teamcity/internal/release/build-and-publish-patched-go/commit.txt
  build/teamcity/internal/release/build-and-publish-patched-go/impl.sh
  go.mod
  pkg/cmd/roachtest/tests/cdc.go
Labels: backport

#152025 logictest: add retry before all ALTER TABLE EXPERIMENTAL_RELOCATE
  pkg/sql/logictest/testdata/logic_test/distsql_agg
  pkg/sql/logictest/testdata/logic_test/distsql_crdb_internal
  pkg/sql/opt/exec/execbuilder/testdata/dist_vectorize
  pkg/sql/opt/exec/execbuilder/testdata/distsql_agg
  pkg/sql/opt/exec/execbuilder/testdata/distsql_distinct_on
  pkg/sql/opt/exec/execbuilder/testdata/distsql_group_join
  pkg/sql/opt/exec/execbuilder/testdata/distsql_inverted_index
  pkg/sql/opt/exec/execbuilder/testdata/distsql_join
  pkg/sql/opt/exec/execbuilder/testdata/distsql_merge_join
  pkg/sql/opt/exec/execbuilder/testdata/distsql_misc
  pkg/sql/opt/exec/execbuilder/testdata/distsql_numtables
  pkg/sql/opt/exec/execbuilder/testdata/distsql_ordinality
  pkg/sql/opt/exec/execbuilder/testdata/distsql_single_flow
  pkg/sql/opt/exec/execbuilder/testdata/distsql_tighten_spans
  pkg/sql/opt/exec/execbuilder/testdata/distsql_union
  pkg/sql/opt/exec/execbuilder/testdata/distsql_window
  pkg/sql/opt/exec/execbuilder/testdata/experimental_distsql_planning_5node
  pkg/sql/opt/exec/execbuilder/testdata/explain_analyze_plans
  pkg/sql/opt/exec/execbuilder/testdata/inverted_join_geospatial_dist
  pkg/sql/opt/exec/execbuilder/testdata/inverted_join_geospatial_dist_vec
  pkg/sql/opt/exec/execbuilder/testdata/inverted_join_json_array_dist
  pkg/sql/opt/exec/execbuilder/testdata/inverted_join_multi_column_dist
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
  pkg/sql/opt/exec/execbuilder/testdata/merge_join_dist_vec
  pkg/sql/opt/exec/execbuilder/testdata/scan_parallel
Labels: backport-all

#152096 release-25.2.5-rc: kvcoord: fix txnWriteBuffer for batches with limits and Dels
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
  pkg/kv/kvpb/api.proto
Labels: O-robot, T-sql-queries, blathers-backport, backport

#151763 release-25.3: kvcoord: fix txnWriteBuffer for batches with limits and Dels
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
  pkg/kv/kvpb/api.proto
Labels: O-robot, T-sql-queries, blathers-backport, backport

#152130 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#152132 release-25.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#152131 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#152134 release-25.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#152135 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#152138 release-25.3: kv,sql: explicitly set IsReverse on the Header
  pkg/kv/batch.go
  pkg/kv/db.go
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/kv/kvnemesis/applier_test.go
  pkg/kv/kvnemesis/generator.go
  pkg/kv/kvnemesis/testdata/TestApplier/batch-mixed-err
  pkg/kv/kvnemesis/testdata/TestApplier/batch-mixed-err-fwd
  pkg/kv/kvnemesis/testdata/TestApplier/batch-mixed-err-rev
  pkg/kv/kvnemesis/testdata/TestApplier/batch-mixed-fwd
  pkg/kv/kvnemesis/testdata/TestApplier/batch-mixed-rev
  pkg/kv/kvpb/api.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvpb/batch.go
  pkg/kv/kvpb/batch_test.go
  pkg/kv/txn.go
  pkg/sql/logictest/testdata/logic_test/select
  pkg/sql/row/kv_batch_fetcher.go
Labels: T-sql-queries, backport

#152183 release-25.3.1-rc: kv,sql: explicitly set IsReverse on the Header
  pkg/kv/batch.go
  pkg/kv/db.go
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/dist_sender_server_test.go
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/kv/kvnemesis/applier_test.go
  pkg/kv/kvnemesis/generator.go
  pkg/kv/kvnemesis/testdata/TestApplier/batch-mixed-err
  pkg/kv/kvnemesis/testdata/TestApplier/batch-mixed-err-fwd
  pkg/kv/kvnemesis/testdata/TestApplier/batch-mixed-err-rev
  pkg/kv/kvnemesis/testdata/TestApplier/batch-mixed-fwd
  pkg/kv/kvnemesis/testdata/TestApplier/batch-mixed-rev
  pkg/kv/kvpb/api.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvpb/batch.go
  pkg/kv/kvpb/batch_test.go
  pkg/kv/txn.go
  pkg/sql/logictest/testdata/logic_test/select
  pkg/sql/row/kv_batch_fetcher.go
Labels: T-sql-queries, backport

#152217 release-25.3: catalog/rewrite: handle UDF references from computed columns and ON UPDATE
  pkg/backup/testdata/backup-restore/user-defined-functions-in-computed
  pkg/backup/testdata/backup-restore/user-defined-functions-in-defaults
  pkg/sql/catalog/rewrite/rewrite.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#152228 release-25.3: logictest: fix flake in a recently added test
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_foreign_key
Labels: O-robot, T-sql-queries, blathers-backport, backport, backport-test-only

#152214 release-24.3: backup: only flush per-node progress every 15s
  pkg/ccl/backupccl/backup_job.go
Labels: backport

#152215 release-24.1: backup: only flush per-node progress every 15s
  pkg/ccl/backupccl/backup_job.go
Labels: backport

#152220 release-25.3: kvpb: register error decoder for KeyCollisionError
  pkg/kv/kvpb/BUILD.bazel
  pkg/kv/kvpb/errors.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#152219 release-25.2: kvpb: register error decoder for KeyCollisionError
  pkg/kv/kvpb/BUILD.bazel
  pkg/kv/kvpb/errors.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#152218 release-24.3: kvpb: register error decoder for KeyCollisionError
  pkg/kv/kvpb/BUILD.bazel
  pkg/kv/kvpb/errors.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#152311 release-25.3.1-rc: release: add FIPS with no-telemetry wrapper
  build/teamcity/internal/release/process/build-cockroach-release-linux-amd64-fips-no-telemetry.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#151959 sql,opt: add session variable to disable optimizer rules
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/disable_optimizer_rules
  pkg/sql/opt/exec/execbuilder/tests/local/generated_test.go
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/rule_name.go
  pkg/sql/opt/xform/optimizer.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-25.2.x, backport-25.3.x

#152341 release-25.3: pgwire: publish authentication latency internal metrics
  docs/generated/metrics/metrics.yaml
  pkg/sql/pgwire/auth.go
  pkg/sql/pgwire/auth_behaviors.go
  pkg/sql/pgwire/auth_methods.go
  pkg/sql/pgwire/conn_test.go
  pkg/sql/pgwire/server.go
Labels: O-robot, T-product-security, blathers-backport, backport

#152349 release-25.2: sql,opt: add session variable to disable optimizer rules
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/disable_optimizer_rules
  pkg/sql/opt/exec/execbuilder/tests/local/generated_test.go
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/rule_name.go
  pkg/sql/opt/xform/optimizer.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: T-sql-queries, backport

#152350 release-25.3: sql,opt: add session variable to disable optimizer rules
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/disable_optimizer_rules
  pkg/sql/opt/exec/execbuilder/tests/local/generated_test.go
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/rule_name.go
  pkg/sql/opt/xform/optimizer.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: T-sql-queries, backport

#152282 release-25.2: sql/schemachanger: add decoder for schemaChangerUserError
  pkg/BUILD.bazel
  pkg/sql/schemachanger/scerrors/BUILD.bazel
  pkg/sql/schemachanger/scerrors/errors.go
  pkg/sql/schemachanger/scerrors/errors_test.go
  pkg/testutils/lint/lint_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#152283 release-25.3: sql/schemachanger: add decoder for schemaChangerUserError
  pkg/BUILD.bazel
  pkg/sql/schemachanger/scerrors/BUILD.bazel
  pkg/sql/schemachanger/scerrors/errors.go
  pkg/sql/schemachanger/scerrors/errors_test.go
  pkg/testutils/lint/lint_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#152280 release-24.1: sql/schemachanger: add decoder for schemaChangerUserError
  pkg/BUILD.bazel
  pkg/sql/schemachanger/scerrors/BUILD.bazel
  pkg/sql/schemachanger/scerrors/errors.go
  pkg/sql/schemachanger/scerrors/errors_test.go
  pkg/testutils/lint/lint_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#152245 optbuilder: take FOR SHARE locking during RC FK child checks
  pkg/ccl/logictestccl/testdata/logic_test/fk_read_committed
  pkg/sql/opt/exec/execbuilder/testdata/fk_read_committed
  pkg/sql/opt/optbuilder/mutation_builder_fk.go
Labels: backport-all

#152312 release-24.1: sql/schemachanger: fix incorrect clean up of sequence ownership
  pkg/sql/logictest/testdata/logic_test/sequences
  pkg/sql/schemachanger/scexec/scmutationexec/helpers.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#152314 release-25.2: sql/schemachanger: fix incorrect clean up of sequence ownership
  pkg/sql/logictest/testdata/logic_test/sequences
  pkg/sql/schemachanger/scexec/scmutationexec/helpers.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport

#104649 builtins: add levenshtein_less_equal function
  docs/generated/sql/functions.md
  pkg/sql/logictest/testdata/logic_test/fuzzystrmatch
  pkg/sql/pgwire/testdata/pgtest/procedure
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/util/fuzzystrmatch/leven.go
  pkg/util/fuzzystrmatch/leven_test.go
Labels: O-community, X-noremind, X-blathers-triaged

#152376 release-24.3: optbuilder: take FOR SHARE locking during RC FK child checks
  pkg/ccl/logictestccl/testdata/logic_test/fk_read_committed
  pkg/sql/opt/exec/execbuilder/testdata/fk_read_committed
  pkg/sql/opt/optbuilder/mutation_builder_fk.go
Labels: T-sql-queries, backport

#152394 schemachanger: don't run TestAlterTableDMLInjection with t.Parallel
  pkg/sql/schemachanger/dml_injection_test.go
Labels: backport-24.3.x, backport-25.2.x, backport-25.3.x, backport-25.3.1-rc

#152465 release-25.3.1-rc: schemachanger: don't run TestAlterTableDMLInjection with t.Parallel
  pkg/sql/schemachanger/dml_injection_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#152462 release-24.3: schemachanger: don't run TestAlterTableDMLInjection with t.Parallel
  pkg/sql/schemachanger/dml_injection_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#152467 release-25.2: gossip: parallelize callback handling
  pkg/gossip/gossip.go
  pkg/gossip/gossip_test.go
  pkg/gossip/infostore.go
  pkg/gossip/infostore_test.go
  pkg/kv/kvserver/allocator/allocatorimpl/allocator_test.go
  pkg/testutils/gossiputil/BUILD.bazel
  pkg/testutils/gossiputil/store_gossiper.go
Labels: backport

#152463 release-25.2: schemachanger: don't run TestAlterTableDMLInjection with t.Parallel
  pkg/sql/schemachanger/dml_injection_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#152449 backport, docs: Update cluster settings to use correct product labels
  docs/generated/settings/BUILD.bazel
  docs/generated/settings/settings.html
Labels: backport

#152476 release-25.3.1-rc: sql: prohibit CITEXT as column type in 25.2-25.3 mixed version state
  pkg/sql/catalog/colinfo/BUILD.bazel
  pkg/sql/catalog/colinfo/col_type_info.go
  pkg/sql/logictest/testdata/logic_test/mixed_version_citext
  pkg/sql/logictest/tests/cockroach-go-testserver-25.2/BUILD.bazel
  pkg/sql/logictest/tests/cockroach-go-testserver-25.2/generated_test.go
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/ttljob_test.go
Labels: backport

#152300 sql: use soft limit if available to decide on scan distribution
  pkg/sql/distsql_physical_planner.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/distsql_auto_mode
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-25.2.x, backport-25.3.x

#150887 sql/opt: improve HoistJoinProjectLeft to hoist more projections
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_foreign_key
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/inverted_join_multi_column
  pkg/sql/opt/exec/execbuilder/testdata/unique
  pkg/sql/opt/exec/execbuilder/testdata/upsert
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/norm/project_funcs.go
  pkg/sql/opt/norm/rules/join.opt
  pkg/sql/opt/norm/testdata/rules/groupby
  pkg/sql/opt/norm/testdata/rules/join
  pkg/sql/opt/xform/join_funcs.go
  pkg/sql/opt/xform/testdata/physprops/limit_hint
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-all

#152550 release-24.1: roachtest: mark more activerecord tests as flaky
  pkg/cmd/roachtest/tests/activerecord_blocklist.go
Labels: T-sql-foundations, backport, backport-test-only

#152549 release-24.3: roachtest: mark more activerecord tests as flaky
  pkg/cmd/roachtest/tests/activerecord_blocklist.go
Labels: T-sql-foundations, backport, backport-test-only

#152553 release-24.3: cli/interactive_tests: use interrupt_and_wait helper everywhere
  pkg/cli/interactive_tests/test_encryption.tcl
  pkg/cli/interactive_tests/test_flags.tcl
  pkg/cli/interactive_tests/test_missing_log_output.tcl
  pkg/cli/interactive_tests/test_socket_name.tcl
  pkg/cli/interactive_tests/test_sql_mem_monitor.tcl
  pkg/cli/interactive_tests/test_temp_dir.tcl
Labels: T-sql-foundations, backport, backport-test-only

#152554 release-24.1: cli/interactive_tests: use interrupt_and_wait helper everywhere
  pkg/cli/interactive_tests/test_encryption.tcl
  pkg/cli/interactive_tests/test_flags.tcl
  pkg/cli/interactive_tests/test_missing_log_output.tcl
  pkg/cli/interactive_tests/test_socket_name.tcl
  pkg/cli/interactive_tests/test_sql_mem_monitor.tcl
  pkg/cli/interactive_tests/test_temp_dir.tcl
Labels: T-sql-foundations, backport, backport-test-only

#152231 release-25.2: execinfra: fix procState redaction
  pkg/sql/execinfra/processorsbase.go
Labels: O-robot, T-sql-queries, blathers-backport, backport

#152303 cloud: fix aws client option handling
  pkg/cloud/amazon/s3_storage.go
Labels: backport-24.3.x, backport-25.2.x, backport-25.3.x

#152603 release-24.1: sql: block ALTER TABLE LOCALITY to RBR with sql_safe_updates
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_safe_updates
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/sql/alter_table_locality.go
Labels: T-sql-foundations, backport

#152628 release-25.3: ccl/multiregionccl: deflake TestRegionLivenessProber
  pkg/ccl/multiregionccl/regionliveness_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#152627 release-25.2: ccl/multiregionccl: deflake TestRegionLivenessProber
  pkg/ccl/multiregionccl/regionliveness_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#152626 release-24.3: ccl/multiregionccl: deflake TestRegionLivenessProber
  pkg/ccl/multiregionccl/regionliveness_test.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#152556 release-25.3: sql: use soft limit if available to decide on scan distribution
  pkg/sql/distsql_physical_planner.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/distsql_auto_mode
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: O-robot, T-sql-queries, blathers-backport, backport

#152639 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#152641 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#152642 release-25.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#152468 release-24.3: sql: add support for automatically repairing dangling comments
  pkg/sql/crdb_internal.go
  pkg/sql/faketreeeval/evalctx.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/repair.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/eval/deps.go
  pkg/upgrade/upgrades/first_upgrade_test.go
Labels: T-sql-foundations, backport

#152738 sql/ttl: clarify TTL rate limiter notice
  pkg/sql/logictest/testdata/logic_test/cluster_settings
  pkg/sql/logictest/testdata/logic_test/row_level_ttl
  pkg/sql/set_cluster_setting.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
Labels: backport-all

#152739 roachtest: test with sqlalchemy 2.0.43
  pkg/cmd/roachtest/tests/sqlalchemy.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.2.x, backport-25.3.x, backport-25.3.1-rc

#152758 release-24.1: roachtest: test with sqlalchemy 2.0.43
  pkg/cmd/roachtest/tests/sqlalchemy.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#152761 release-25.3: roachtest: test with sqlalchemy 2.0.43
  pkg/cmd/roachtest/tests/sqlalchemy.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#152759 release-24.3: roachtest: test with sqlalchemy 2.0.43
  pkg/cmd/roachtest/tests/sqlalchemy.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#152760 release-25.2: roachtest: test with sqlalchemy 2.0.43
  pkg/cmd/roachtest/tests/sqlalchemy.go
Labels: O-robot, T-sql-foundations, blathers-backport, backport, backport-test-only

#152743 sql: fix a flake in TestSavepoints
  pkg/sql/conn_executor_savepoints_test.go
Labels: backport-25.3.x
