Repository cockroachdb/cockroach, pull requests merged in 2025-07, with the labels that each got.

#149293 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#149295 release-25.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#149297 release-25.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#149298 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#149223 release-25.3: jwtauthccl: turn off cluster settings visibility for jwt authorization
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/jwtauthccl/settings.go
Labels: O-robot, blathers-backport, backport

#149308 release-25.3: logictest: skip upsert_non_metamorphic under race
  pkg/sql/logictest/testdata/logic_test/upsert_non_metamorphic
Labels: O-robot, blathers-backport, backport, backport-test-only

#149307 release-25.2: logictest: skip upsert_non_metamorphic under race
  pkg/sql/logictest/testdata/logic_test/upsert_non_metamorphic
Labels: O-robot, blathers-backport, backport, backport-test-only

#149306 release-25.1: logictest: skip upsert_non_metamorphic under race
  pkg/sql/logictest/testdata/logic_test/upsert_non_metamorphic
Labels: O-robot, blathers-backport, backport, backport-test-only

#149328 release-25.1: kvserver: do not cancel while in HandleRaftResponse
  pkg/kv/kvserver/raft_transport.go
Labels: backport

#149303 release-23.2: logictest: skip upsert_non_metamorphic under race
  pkg/sql/logictest/testdata/logic_test/upsert_non_metamorphic
Labels: O-robot, blathers-backport, backport

#149302 release-25.3: execbuilder: fix locked indexes info in an edge case
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/testdata/delete
  pkg/sql/opt/exec/execbuilder/testdata/update
Labels: O-robot, blathers-backport, backport

#149268 release-25.2: roachtest: add variants of cdc/bank test
  pkg/cmd/roachtest/tests/cdc.go
Labels: backport, backport-test-only

#149270 release-24.3: roachtest: add variants of cdc/bank test
  pkg/cmd/roachtest/tests/cdc.go
Labels: backport, backport-test-only

#149343 release-23.2: roachtest: add build branch to roachprod's labels
  pkg/cmd/roachtest/spec/cluster_spec.go
Labels: backport

#149344 release-24.1: roachtest: add build branch to roachprod's labels
  pkg/cmd/roachtest/spec/cluster_spec.go
Labels: backport, backport-test-only

#149355 release-25.2: go.mod: bump Pebble to f76e07d43b83
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#149357 release-25.1: go.mod: bump Pebble to 13a067954045
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#149280 release-25.3: structlogging: properly register hot ranges logging job
  pkg/server/structlogging/BUILD.bazel
  pkg/server/structlogging/hot_ranges_log.go
  pkg/server/structlogging/hot_ranges_log_job.go
Labels: backport

#149366 release-25.3: go.mod: bump Pebble to e3d11e721fa3
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#149292 release-25.3: optbuilder: prohibit some operations on REFCURSOR
  pkg/ccl/logictestccl/testdata/logic_test/refcursor
  pkg/sql/opt/optbuilder/groupby.go
  pkg/sql/opt/optbuilder/join.go
  pkg/sql/opt/optbuilder/orderby.go
  pkg/sql/sem/tree/eval.go
  pkg/sql/sem/tree/type_check.go
Labels: O-robot, blathers-backport, backport

#147923 sql: do not attempt to re-execute portal after PL/pgSQL txn control
  pkg/sql/conn_executor.go
  pkg/sql/conn_io.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/pgwire/testdata/pgtest/procedure
  pkg/sql/routine.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-25.3.x

#149348 release-24.1: changefeedccl: fix race advancing frontier in schemafeed
  pkg/ccl/changefeedccl/schemafeed/schema_feed.go
Labels: O-robot, blathers-backport, backport

#149351 release-25.2: changefeedccl: fix race advancing frontier in schemafeed
  pkg/ccl/changefeedccl/schemafeed/schema_feed.go
Labels: O-robot, blathers-backport, backport

#149350 release-25.1: changefeedccl: fix race advancing frontier in schemafeed
  pkg/ccl/changefeedccl/schemafeed/schema_feed.go
Labels: O-robot, blathers-backport, backport

#149301 release-25.2: execbuilder: fix locked indexes info in an edge case
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/testdata/delete
  pkg/sql/opt/exec/execbuilder/testdata/update
Labels: O-robot, blathers-backport, backport

#148770 sql: ignore some session variables in RESET ALL
  pkg/ccl/logictestccl/testdata/logic_test/read_committed
  pkg/sql/discard.go
  pkg/sql/logictest/testdata/logic_test/discard
  pkg/sql/logictest/testdata/logic_test/reset
  pkg/sql/logictest/testdata/logic_test/set_role
  pkg/sql/set_var.go
  pkg/sql/vars.go
Labels: backport-all

#148200 sql,provisioning: enable provisioning during LDAP authentication
  docs/generated/eventlog.md
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/testccl/authccl/testdata/ldap
  pkg/security/provisioning/BUILD.bazel
  pkg/security/provisioning/provisioning_source.go
  pkg/security/provisioning/settings.go
  pkg/sql/create_role.go
  pkg/sql/logictest/BUILD.bazel
  pkg/sql/logictest/logic.go
  pkg/sql/logictest/testdata/logic_test/user
  pkg/sql/logictest/tests/local-mixed-25.2/generated_test.go
  pkg/sql/pgwire/BUILD.bazel
  pkg/sql/pgwire/auth.go
  pkg/sql/pgwire/auth_behaviors.go
  pkg/sql/pgwire/auth_methods.go
  pkg/util/log/eventpb/session_events.proto
Labels: backport-25.3.x

#149231 release-25.2: cli/doctor: handle truncated rows gracefully in zipdir
  pkg/cli/doctor.go
  pkg/cli/doctor_test.go
  pkg/cli/testdata/doctor/debugzip-bad-descriptors/crdb_internal.system_jobs.txt
  pkg/cli/testdata/doctor/debugzip-bad-descriptors/system.descriptor.txt
  pkg/cli/testdata/doctor/debugzip-bad-descriptors/system.jobs.txt.err.txt
  pkg/cli/testdata/doctor/debugzip-bad-descriptors/system.namespace.txt
  pkg/cli/testdata/doctor/debugzip-bad-jobs/crdb_internal.system_jobs.txt
  pkg/cli/testdata/doctor/debugzip-bad-jobs/system.descriptor.txt
  pkg/cli/testdata/doctor/debugzip-bad-jobs/system.jobs.txt.err.txt
  pkg/cli/testdata/doctor/debugzip-bad-jobs/system.namespace.txt
  pkg/cli/testdata/doctor/debugzip-bad-namespace/crdb_internal.system_jobs.txt
  pkg/cli/testdata/doctor/debugzip-bad-namespace/system.descriptor.txt
  pkg/cli/testdata/doctor/debugzip-bad-namespace/system.jobs.txt.err.txt
  pkg/cli/testdata/doctor/debugzip-bad-namespace/system.namespace.txt
  pkg/cli/testdata/doctor/test_examine_zipdir_bad_descriptors
  pkg/cli/testdata/doctor/test_examine_zipdir_bad_jobs
  pkg/cli/testdata/doctor/test_examine_zipdir_bad_namespace
Labels: O-robot, blathers-backport, backport

#149227 release-23.2: cli/doctor: handle truncated rows gracefully in zipdir
  pkg/cli/doctor.go
  pkg/cli/doctor_test.go
  pkg/cli/testdata/doctor/debugzip-bad-descriptors/crdb_internal.system_jobs.txt
  pkg/cli/testdata/doctor/debugzip-bad-descriptors/system.descriptor.txt
  pkg/cli/testdata/doctor/debugzip-bad-descriptors/system.jobs.txt.err.txt
  pkg/cli/testdata/doctor/debugzip-bad-descriptors/system.namespace.txt
  pkg/cli/testdata/doctor/debugzip-bad-jobs/crdb_internal.system_jobs.txt
  pkg/cli/testdata/doctor/debugzip-bad-jobs/system.descriptor.txt
  pkg/cli/testdata/doctor/debugzip-bad-jobs/system.jobs.txt.err.txt
  pkg/cli/testdata/doctor/debugzip-bad-jobs/system.namespace.txt
  pkg/cli/testdata/doctor/debugzip-bad-namespace/crdb_internal.system_jobs.txt
  pkg/cli/testdata/doctor/debugzip-bad-namespace/system.descriptor.txt
  pkg/cli/testdata/doctor/debugzip-bad-namespace/system.jobs.txt.err.txt
  pkg/cli/testdata/doctor/debugzip-bad-namespace/system.namespace.txt
  pkg/cli/testdata/doctor/test_examine_zipdir_bad_descriptors
  pkg/cli/testdata/doctor/test_examine_zipdir_bad_jobs
  pkg/cli/testdata/doctor/test_examine_zipdir_bad_namespace
Labels: O-robot, blathers-backport, backport

#149369 roachprod: scrape workload metrics via promhelperservice
  pkg/roachprod/roachprod.go
  pkg/roachprod/vm/startup.go
Labels: backport-25.3.x

#149249 release-25.3: sql: fix cancel leak in happy case in fingerprint_span
  pkg/sql/fingerprint_span.go
Labels: O-robot, blathers-backport, backport

#149420 release-25.3: released CockroachDB version v25.3.0-beta.1. Next version: v25.3.0-beta.2
  pkg/build/version.txt
Labels: backport, backport-test-only

#148943 release-23.2: kv: add more tracing on the commit path
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvserver/batcheval/cmd_end_transaction.go
  pkg/kv/kvserver/replica_tscache.go
Labels: backport

#148957 release-25.2: kv: add more tracing on the commit path
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvserver/batcheval/cmd_end_transaction.go
  pkg/kv/kvserver/replica_tscache.go
Labels: backport

#149283 roachtest: deflake splits/largerange/size=32GiB
  pkg/cmd/roachtest/tests/split.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x, backport-25.3.x

#149443 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#149335 release-25.3: sql: reset schema_locked correctly in a mixed version state
  pkg/sql/logictest/testdata/logic_test/schema_locked
  pkg/sql/storageparam/tablestorageparam/BUILD.bazel
  pkg/sql/storageparam/tablestorageparam/table_storage_param.go
Labels: O-robot, blathers-backport, backport

#149464 release-24.1: roachtest: deflake splits/largerange/size=32GiB
  pkg/cmd/roachtest/tests/split.go
Labels: backport, backport-test-only

#148955 release-24.3: kv: add more tracing on the commit path
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvserver/batcheval/cmd_end_transaction.go
  pkg/kv/kvserver/replica_tscache.go
Labels: backport

#148956 release-25.1: kv: add more tracing on the commit path
  pkg/kv/kvclient/kvcoord/dist_sender.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvserver/batcheval/cmd_end_transaction.go
  pkg/kv/kvserver/replica_tscache.go
Labels: backport

#149228 release-24.1: cli/doctor: handle truncated rows gracefully in zipdir
  pkg/cli/doctor.go
  pkg/cli/doctor_test.go
  pkg/cli/testdata/doctor/debugzip-bad-descriptors/crdb_internal.system_jobs.txt
  pkg/cli/testdata/doctor/debugzip-bad-descriptors/system.descriptor.txt
  pkg/cli/testdata/doctor/debugzip-bad-descriptors/system.jobs.txt.err.txt
  pkg/cli/testdata/doctor/debugzip-bad-descriptors/system.namespace.txt
  pkg/cli/testdata/doctor/debugzip-bad-jobs/crdb_internal.system_jobs.txt
  pkg/cli/testdata/doctor/debugzip-bad-jobs/system.descriptor.txt
  pkg/cli/testdata/doctor/debugzip-bad-jobs/system.jobs.txt.err.txt
  pkg/cli/testdata/doctor/debugzip-bad-jobs/system.namespace.txt
  pkg/cli/testdata/doctor/debugzip-bad-namespace/crdb_internal.system_jobs.txt
  pkg/cli/testdata/doctor/debugzip-bad-namespace/system.descriptor.txt
  pkg/cli/testdata/doctor/debugzip-bad-namespace/system.jobs.txt.err.txt
  pkg/cli/testdata/doctor/debugzip-bad-namespace/system.namespace.txt
  pkg/cli/testdata/doctor/test_examine_zipdir_bad_descriptors
  pkg/cli/testdata/doctor/test_examine_zipdir_bad_jobs
  pkg/cli/testdata/doctor/test_examine_zipdir_bad_namespace
Labels: O-robot, blathers-backport, backport

#149431 release-24.3: sql: ignore some session variables in RESET ALL
  pkg/ccl/logictestccl/testdata/logic_test/read_committed
  pkg/sql/discard.go
  pkg/sql/logictest/testdata/logic_test/discard
  pkg/sql/logictest/testdata/logic_test/reset
  pkg/sql/logictest/testdata/logic_test/set_role
  pkg/sql/set_var.go
  pkg/sql/vars.go
Labels: backport

#149429 release-25.1: sql: ignore some session variables in RESET ALL
  pkg/ccl/logictestccl/testdata/logic_test/read_committed
  pkg/sql/discard.go
  pkg/sql/logictest/testdata/logic_test/discard
  pkg/sql/logictest/testdata/logic_test/reset
  pkg/sql/logictest/testdata/logic_test/set_role
  pkg/sql/set_var.go
  pkg/sql/vars.go
Labels: backport

#148886 workload_generator: parse DDLs and build schema structs for debug-zip…
  pkg/BUILD.bazel
  pkg/workload/workload_generator/BUILD.bazel
  pkg/workload/workload_generator/constants.go
  pkg/workload/workload_generator/ddl_generator.go
  pkg/workload/workload_generator/ddl_generator_test.go
  pkg/workload/workload_generator/schema_designs.go
  pkg/workload/workload_generator/test_data/debug/crdb_internal.create_statements.txt
Labels: O-community, X-blathers-untriaged

#148616 sql: support referencing a routine from a view query
  pkg/sql/alter_function.go
  pkg/sql/catalog/descpb/structured.proto
  pkg/sql/catalog/funcdesc/func_desc.go
  pkg/sql/create_view.go
  pkg/sql/distsql_spec_exec_factory.go
  pkg/sql/drop_view.go
  pkg/sql/logictest/testdata/logic_test/drop_function
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/logictest/testdata/logic_test/udf_calling_udf
  pkg/sql/logictest/testdata/logic_test/udf_unsupported
  pkg/sql/opt/exec/execbuilder/statement.go
  pkg/sql/opt/exec/factory.opt
  pkg/sql/opt/memo/expr_format.go
  pkg/sql/opt/ops/statement.opt
  pkg/sql/opt/optbuilder/BUILD.bazel
  pkg/sql/opt/optbuilder/create_trigger.go
  pkg/sql/opt/optbuilder/create_view.go
  pkg/sql/opt/optbuilder/routine.go
  pkg/sql/opt/optbuilder/testdata/create_trigger
  pkg/sql/opt/optbuilder/testdata/create_view
  pkg/sql/opt/optbuilder/testdata/view
  pkg/sql/opt/schema_dependencies.go
  pkg/sql/opt_exec_factory.go
  pkg/sql/schemachanger/scdecomp/decomp.go
  pkg/sql/schemachanger/scdecomp/testdata/other
  pkg/sql/schemachanger/scpb/elements.proto
  pkg/sql/schemachanger/scpb/uml/table.puml
  pkg/sql/schemachanger/scplan/internal/opgen/opgen_view.go
Labels: backport-25.3.x

#148532 sql: update SHOW users/roles to support provisioned users
  pkg/backup/backup_test.go
  pkg/backup/testdata/backup-restore/system-users
  pkg/ccl/testccl/authccl/testdata/ldap
  pkg/sql/delegate/BUILD.bazel
  pkg/sql/delegate/show_roles.go
  pkg/sql/logictest/testdata/logic_test/drop_user
  pkg/sql/logictest/testdata/logic_test/role
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/logictest/testdata/logic_test/user
  pkg/sql/opt/exec/execbuilder/testdata/explain
  pkg/sql/pgwire/pgwire_test.go
Labels: backport-25.3.x

#149416 logictest: fix user logictest for provisioning gating validation
  pkg/sql/logictest/testdata/logic_test/user
Labels: backport-25.3.x

#149356 release-25.2: tpcc: use explicit decimals when initializing items
  pkg/ccl/workloadccl/allccl/all_test.go
  pkg/cmd/roachtest/tests/mixed_version_import.go
  pkg/sql/importer/read_import_workload.go
  pkg/testutils/lint/lint_test.go
  pkg/workload/BUILD.bazel
  pkg/workload/bench_test.go
  pkg/workload/csv.go
  pkg/workload/csv_test.go
  pkg/workload/tpcc/BUILD.bazel
  pkg/workload/tpcc/generate.go
  pkg/workload/tpcc/random.go
  pkg/workload/tpcc/tpcc.go
  pkg/workload/workload.go
Labels: backport

#149533 roachtest: increase backupRestoreRoundTrip split_queue verbosity
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
Labels: backport-all

#149504 logictest: deflake partial_stats
  pkg/sql/opt/exec/execbuilder/testdata/partial_stats
Labels: backport-24.3.x, backport-25.1.x, backport-25.2.x, backport-25.3.x

#149513 Ddl and yaml
  pkg/workload/workload_generator/BUILD.bazel
  pkg/workload/workload_generator/schema_designs.go
  pkg/workload/workload_generator/schema_generator.go
  pkg/workload/workload_generator/schema_generator_test.go
  pkg/workload/workload_generator/utils.go
  pkg/workload/workload_generator/utils_test.go
Labels: O-community, X-blathers-untriaged

#149661 kvserver: skip TestFlowControlRaftMembership{,RemoveSelf}V2 under duress
  pkg/kv/kvserver/flow_control_integration_test.go
Labels: backport-25.1.x, backport-25.2.x, backport-25.3.x

#149617 release-23.2: restore: add retry loop to AdminSplit in split and scatterer
  pkg/ccl/backupccl/generative_split_and_scatter_processor.go
  pkg/ccl/backupccl/generative_split_and_scatter_processor_test.go
Labels: backport

#149619 release-24.3: restore: add retry loop to AdminSplit in split and scatterer
  pkg/ccl/backupccl/generative_split_and_scatter_processor.go
  pkg/ccl/backupccl/generative_split_and_scatter_processor_test.go
Labels: backport

#149748 release-25.3: sql: prevent auth failure when no roles are granted during sync
  pkg/sql/authorization.go
  pkg/sql/authorization_test.go
Labels: O-robot, blathers-backport, backport

#149676 perf: faster allocator on sysbench settings
  pkg/cmd/roachtest/tests/sysbench.go
Labels: o-perf-efficiency

#149707 release-25.3: go.mod: bump Pebble to cd488b24ace9
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cli/interactive_tests/test_encryption.tcl
Labels: backport

#149822 release-25.2.3-rc: roachtest: fix hibernate nightly test
  pkg/cmd/roachtest/tests/hibernate.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#149700 release-25.2: sqlccl: log cancelled stmts in TestExplainGist
  pkg/ccl/testccl/sqlccl/explain_test.go
Labels: backport, backport-test-only

#149701 release-25.1: sqlccl: log cancelled stmts in TestExplainGist
  pkg/ccl/testccl/sqlccl/explain_test.go
Labels: backport, backport-test-only

#149832 release-25.1: logictest: add back assertion that was rewritten accidentally
  pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant
Labels: O-robot, blathers-backport, backport, backport-test-only

#149831 release-24.3: logictest: add back assertion that was rewritten accidentally
  pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant
Labels: O-robot, blathers-backport, backport, backport-test-only

#149828 release-23.2: logictest: add back assertion that was rewritten accidentally
  pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant
Labels: O-robot, blathers-backport, backport

#149843 release-24.3: multiregionccl: skip TestMultiRegionTenantRegions under duress
  pkg/ccl/multiregionccl/multiregion_system_table_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#149846 release-25.3: multiregionccl: skip TestMultiRegionTenantRegions under duress
  pkg/ccl/multiregionccl/multiregion_system_table_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#149845 release-25.2: multiregionccl: skip TestMultiRegionTenantRegions under duress
  pkg/ccl/multiregionccl/multiregion_system_table_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#149840 release-25.1: sql: don't throw errors for skipped auto stats jobs
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/create_stats.go
  pkg/sql/stats/create_stats_job_test.go
Labels: backport

#149834 release-25.3: logictest: add back assertion that was rewritten accidentally
  pkg/sql/logictest/testdata/logic_test/zone_config_system_tenant
Labels: O-robot, blathers-backport, backport, backport-test-only

#149796 storage: avoid value retrieval of sys keys during ComputeStats
  pkg/storage/mvcc.go
Labels: X-perf-gain

#149841 release-24.3: sql: don't throw errors for skipped auto stats jobs
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/create_stats.go
  pkg/sql/stats/create_stats_job_test.go
Labels: backport

#147113 release-25.1: changefeedccl: fix mvcc_timestamp being zero when used with cdc queries
  pkg/ccl/changefeedccl/cdcevent/projection.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport

#147110 release-24.1: changefeedccl: fix mvcc_timestamp being zero when used with cdc queries
  pkg/ccl/changefeedccl/cdcevent/projection.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport

#149850 release-24.3.16-rc: sql: don't throw errors for skipped auto stats jobs
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/sql/create_stats.go
  pkg/sql/stats/create_stats_job_test.go
Labels: backport

#149705 release-25.3: tracing: add background execution tracer (+ debug zip export)
  pkg/BUILD.bazel
  pkg/base/constants.go
  pkg/cli/interactive_tests/test_log_flags.tcl
  pkg/cli/log_flags.go
  pkg/cli/testdata/zip/partial1
  pkg/cli/testdata/zip/partial1_excluded
  pkg/cli/testdata/zip/partial2
  pkg/cli/testdata/zip/testzip
  pkg/cli/testdata/zip/testzip_concurrent
  pkg/cli/testdata/zip/testzip_exclude_goroutine_stacks
  pkg/cli/testdata/zip/testzip_exclude_range_info
  pkg/cli/testdata/zip/testzip_external_process_virtualization
  pkg/cli/testdata/zip/testzip_fallback
  pkg/cli/testdata/zip/testzip_include_goroutine_stacks
  pkg/cli/testdata/zip/testzip_include_range_info
  pkg/cli/testdata/zip/testzip_redacted
  pkg/cli/testdata/zip/testzip_shared_process_virtualization
  pkg/cli/testdata/zip/testzip_shared_process_virtualization_with_default_tenant
  pkg/cli/zip_per_node.go
  pkg/cli/zip_test.go
  pkg/server/BUILD.bazel
  pkg/server/config.go
  pkg/server/env_sampler.go
  pkg/server/get_local_files_test.go
  pkg/server/server_controller_new_server.go
  pkg/server/serverpb/status.proto
  pkg/server/status.go
  pkg/server/status_local_file_retrieval.go
  pkg/server/tenant.go
  pkg/server/testserver.go
  pkg/util/tracing/goexectrace/BUILD.bazel
  pkg/util/tracing/goexectrace/simple_flight_recorder.go
  pkg/util/tracing/goexectrace/simple_flight_recorder_test.go
Labels: backport

#149937 release-25.2: metric: Report aggregate metric when no child metrics are present
  pkg/server/status/recorder.go
  pkg/util/metric/aggmetric/agg_metric_test.go
  pkg/util/metric/prometheus_exporter.go
Labels: backport

#149985 release-25.3: vecindex: improve vector reranking
  pkg/cmd/vecbench/mem_provider.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/logictest/testdata/logic_test/vector_index
  pkg/sql/rowexec/vector_search.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
  pkg/sql/vecindex/cspann/index.go
  pkg/sql/vecindex/cspann/index_test.go
  pkg/sql/vecindex/cspann/searcher.go
  pkg/sql/vecindex/cspann/testdata/clip-512d-1050.gob
  pkg/sql/vecindex/cspann/testdata/delete.ddt
  pkg/sql/vecindex/cspann/testdata/glove-100d-1k.gob
  pkg/sql/vecindex/cspann/testdata/read-only.ddt
  pkg/sql/vecindex/cspann/testdata/search-embeddings.ddt
  pkg/sql/vecindex/cspann/testdata/search.ddt
  pkg/sql/vecindex/cspann/testdata/split-non-root-step.ddt
  pkg/sql/vecindex/cspann/testdata/split-root-step.ddt
  pkg/sql/vecindex/cspann/testdata/split.ddt
  pkg/sql/vecindex/cspann/testdata/tree-key.ddt
  pkg/sql/vecindex/cspann/testutils/testutils.go
  pkg/sql/vecindex/searcher.go
  pkg/sql/vecindex/searcher_test.go
Labels: backport

#149687 codeowners: move ownership of tenantcostclient/server to sql queries
  .github/CODEOWNERS
Labels: backport-all

#149921 release-25.2.3-rc: distsql: fix recently introduced leak of CancelFunc
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/sql/distsql/server.go
Labels: O-robot, blathers-backport, backport

#148186 execbuilder: add "average lookup ratio" parallelization heuristic for lookup joins
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_cascade
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
  pkg/sql/opt/exec/factory.go
  pkg/sql/opt/lookupjoin/constraint_builder.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/ops/relational.opt
  pkg/sql/opt/props/histogram.go
  pkg/sql/opt/props/histogram_test.go
  pkg/sql/opt/xform/join_funcs.go
  pkg/sql/opt/xform/testdata/rules/join
  pkg/sql/recursive_cte.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport-25.3.x

#149932 release-25.3: profiler: add environment variable to enable continuous profiling
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cli/start.go
  pkg/server/profiler/BUILD.bazel
  pkg/server/profiler/google_cloud_profiler.go
Labels: backport

#150007 release-25.3: structlogging: fix hot ranges logging job exit mechanism
  pkg/server/structlogging/BUILD.bazel
  pkg/server/structlogging/hot_ranges_log_job.go
  pkg/server/structlogging/hot_ranges_log_job_test.go
Labels: backport

#150016 release-25.3: execbuilder: add "average lookup ratio" parallelization heuristic for lookup joins
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_cascade
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
  pkg/sql/opt/exec/factory.go
  pkg/sql/opt/lookupjoin/constraint_builder.go
  pkg/sql/opt/memo/statistics_builder.go
  pkg/sql/opt/ops/relational.opt
  pkg/sql/opt/props/histogram.go
  pkg/sql/opt/props/histogram_test.go
  pkg/sql/opt/xform/join_funcs.go
  pkg/sql/opt/xform/testdata/rules/join
  pkg/sql/recursive_cte.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: O-robot, blathers-backport, backport

#150135 release-25.1: roachtest: skip online restore roachtests
  pkg/cmd/roachtest/tests/backup_restore_roundtrip.go
  pkg/cmd/roachtest/tests/online_restore.go
Labels: backport, backport-24.1.x, backport-24.3.x, backport-test-only, backport-24.2.x

#150153 release-25.3: roachtest: skip many perturbation tests
  pkg/cmd/roachtest/tests/perturbation/framework.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#149078 sql: de-flake TestDistSQLReceiverReportsContention/contention=false
  pkg/sql/distsql_running_test.go
Labels: backport-all

#150207 release-25.2: sql: de-flake TestDistSQLReceiverReportsContention/contention=false
  pkg/sql/distsql_running_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#150206 release-25.1: sql: de-flake TestDistSQLReceiverReportsContention/contention=false
  pkg/sql/distsql_running_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#150205 release-24.3: sql: de-flake TestDistSQLReceiverReportsContention/contention=false
  pkg/sql/distsql_running_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#150204 release-24.1: sql: de-flake TestDistSQLReceiverReportsContention/contention=false
  pkg/sql/distsql_running_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#150222 ccl/oidcccl: increase client timeout to fix flaky test
  pkg/ccl/oidcccl/authentication_oidc_test.go
Labels: backport-25.1.x, backport-25.2.x, backport-25.3.x, backport-25.1.9-rc

#150176 sql: block DROP NOT NULL on generated identity columns
  pkg/sql/alter_table.go
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_drop_not_null.go
Labels: backport-25.3.x

#150159 release-25.1: changefeedccl: gate Kafka v2 message too large error detail behind cluster setting
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/changefeedccl/batching_sink.go
  pkg/ccl/changefeedccl/changefeedbase/settings.go
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_kafka_v2_test.go
  pkg/ccl/changefeedccl/sink_pubsub_v2.go
  pkg/ccl/changefeedccl/sink_webhook_v2.go
Labels: backport

#150180 roachtest: ignore testInsertWithManyToOne in hibernate test
  pkg/cmd/roachtest/tests/hibernate_blocklist.go
Labels: backport-24.3.x, backport-25.1.x, backport-25.2.x, backport-25.3.x, backport-24.3.16-rc, backport-25.1.9-rc, backport-25.2.3-rc

#150152 release-25.3: ui: fix text overflow on job details page
  pkg/ui/workspaces/cluster-ui/src/jobs/jobs.module.scss
Labels: O-robot, blathers-backport, backport

#150196 release-25.3: backup/rewrite: handle UDF references from views when restoring
  pkg/backup/backup_test.go
  pkg/backup/restore_planning.go
  pkg/backup/testdata/backup-restore/views
  pkg/sql/catalog/rewrite/rewrite.go
Labels: O-robot, blathers-backport, backport

#150240 release-24.3: roachtest: ignore testInsertWithManyToOne in hibernate test
  pkg/cmd/roachtest/tests/hibernate_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#150245 release-25.1.9-rc: roachtest: ignore testInsertWithManyToOne in hibernate test
  pkg/cmd/roachtest/tests/hibernate_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#150194 release: add linux-s390x support
  build/teamcity/internal/release/process/build-cockroach-release-linux-s390x.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-linux-s390x.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-per-platform.sh
  pkg/cmd/publish-artifacts/main.go
  pkg/cmd/publish-artifacts/main_test.go
  pkg/cmd/publish-provisional-artifacts/main_test.go
  pkg/release/build.go
  pkg/release/upload.go
  scripts/tag-custom-build.sh
Labels: C-enhancement, A-release, T-release, backport-25.3.x

#150244 release-24.3.16-rc: roachtest: ignore testInsertWithManyToOne in hibernate test
  pkg/cmd/roachtest/tests/hibernate_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#150272 release-24.1: tests/cdc: start chaos testing after changefeed
  pkg/cmd/roachtest/tests/cdc.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#149851 release-25.2: sql: do not attempt to re-execute portal after PL/pgSQL txn control
  pkg/sql/conn_executor.go
  pkg/sql/conn_io.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/pgwire/testdata/pgtest/procedure
  pkg/sql/routine.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#149853 release-25.1: sql: do not attempt to re-execute portal after PL/pgSQL txn control
  pkg/sql/conn_executor.go
  pkg/sql/conn_io.go
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/pgwire/testdata/pgtest/procedure
  pkg/sql/routine.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#150215 changefeedccl: fix TestNoBackfillAfterNonTargetColumnDrop
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x, backport-25.3.x

#150232 release: GPG signing for custom releases
  build/teamcity/internal/cockroach/release/publish/sign-custom-release.sh
Labels: C-enhancement, A-release, T-release, backport-25.3.x

#150293 release-25.3: release: GPG signing for custom releases
  build/teamcity/internal/cockroach/release/publish/sign-custom-release.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#150237 release-25.3: sql: block DROP NOT NULL on generated identity columns
  pkg/sql/alter_table.go
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_drop_not_null.go
Labels: O-robot, blathers-backport, backport

#149463 sql: restrict ALTER user password for provisioned users
  pkg/ccl/logictestccl/testdata/logic_test/provisioning
  pkg/sql/alter_role.go
  pkg/sql/authorization.go
  pkg/sql/logictest/testdata/logic_test/role
  pkg/sql/roleoption/role_option.go
Labels: backport-25.3.x

#150284 release-25.2: changefeedccl: fix TestNoBackfillAfterNonTargetColumnDrop
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport, backport-test-only

#150288 release-24.1: changefeedccl: fix TestNoBackfillAfterNonTargetColumnDrop
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport, backport-test-only

#150338 release-25.2.3-rc: opt: take exclusive locks for foreign key cascades under read-committed
  pkg/ccl/logictestccl/testdata/logic_test/fk_read_committed
  pkg/sql/opt/exec/execbuilder/testdata/fk_read_committed
  pkg/sql/opt/optbuilder/fk_cascade.go
Labels: backport

#150335 release-25.1: opt: take exclusive locks for foreign key cascades under read-committed
  pkg/ccl/logictestccl/testdata/logic_test/fk_read_committed
  pkg/sql/opt/exec/execbuilder/testdata/fk_read_committed
  pkg/sql/opt/optbuilder/fk_cascade.go
Labels: backport

#150339 release-25.1.9-rc: opt: take exclusive locks for foreign key cascades under read-committed
  pkg/ccl/logictestccl/testdata/logic_test/fk_read_committed
  pkg/sql/opt/exec/execbuilder/testdata/fk_read_committed
  pkg/sql/opt/optbuilder/fk_cascade.go
Labels: backport

#150342 release-24.3.16-rc: opt: take exclusive locks for foreign key cascades under read-committed
  pkg/ccl/logictestccl/testdata/logic_test/fk_read_committed
  pkg/sql/opt/exec/execbuilder/testdata/fk_read_committed
  pkg/sql/opt/optbuilder/fk_cascade.go
Labels: backport

#150366 release-25.3: sql,opt: implement region-column inference
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_foreign_key
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-no-los/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs/generated_test.go
  pkg/cli/testdata/doctor/test_recreate_zipdir
  pkg/cli/testdata/doctor/test_recreate_zipdir-json
  pkg/sql/alter_table.go
  pkg/sql/alter_table_locality.go
  pkg/sql/catalog/bootstrap/testdata/testdata
  pkg/sql/catalog/catpb/catalog.go
  pkg/sql/catalog/descpb/structured.proto
  pkg/sql/catalog/descriptor.go
  pkg/sql/catalog/schemaexpr/computed_column.go
  pkg/sql/catalog/tabledesc/structured.go
  pkg/sql/catalog/tabledesc/validate.go
  pkg/sql/catalog/tabledesc/validate_test.go
  pkg/sql/create_table.go
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/logictest/testdata/logic_test/create_table
  pkg/sql/opt/cat/table.go
  pkg/sql/opt/exec/execbuilder/testdata/show_trace
  pkg/sql/opt/exec/explain/plan_gist_factory.go
  pkg/sql/opt/optbuilder/insert.go
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/opt/optbuilder/testdata/region_lookup
  pkg/sql/opt/optbuilder/update.go
  pkg/sql/opt/testutils/testcat/create_table.go
  pkg/sql/opt/testutils/testcat/test_catalog.go
  pkg/sql/opt/testutils/testcat/types.go
  pkg/sql/opt_catalog.go
  pkg/sql/pg_catalog.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_constraint.go
  pkg/sql/schemachanger/scdecomp/decomp.go
  pkg/sql/schemachanger/scpb/elements.proto
  pkg/sql/schemachanger/scpb/elements_generated.go
  pkg/sql/schemachanger/scpb/uml/table.puml
  pkg/sql/schemachanger/scplan/internal/opgen/BUILD.bazel
  pkg/sql/schemachanger/scplan/internal/opgen/opgen_table_locality_regional_by_row_using_constraint.go
  pkg/sql/schemachanger/scplan/internal/rules/current/helpers.go
  pkg/sql/schemachanger/scplan/internal/rules/current/testdata/deprules
  pkg/sql/schemachanger/scplan/internal/rules/release_25_2/helpers.go
  pkg/sql/schemachanger/screl/attr.go
  pkg/sql/schemachanger/screl/scalars.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/show_create.go
  pkg/sql/sqlerrors/errors.go
  pkg/sql/storageparam/tablestorageparam/BUILD.bazel
  pkg/sql/storageparam/tablestorageparam/table_storage_param.go
Labels: backport

#149819 release-25.3: sql: add CITEXT column data type
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/local-read-committed/generated_test.go
  pkg/ccl/logictestccl/tests/local-repeatable-read/generated_test.go
  pkg/cli/clisqlshell/testdata/describe
  pkg/sql/logictest/testdata/logic_test/citext
  pkg/sql/logictest/testdata/logic_test/grant_table
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/tests/fakedist-disk/generated_test.go
  pkg/sql/logictest/tests/fakedist-vec-off/generated_test.go
  pkg/sql/logictest/tests/fakedist/generated_test.go
  pkg/sql/logictest/tests/local-legacy-schema-changer/generated_test.go
  pkg/sql/logictest/tests/local-mixed-25.2/generated_test.go
  pkg/sql/logictest/tests/local-vec-off/generated_test.go
  pkg/sql/logictest/tests/local/generated_test.go
  pkg/sql/oidext/oidext.go
  pkg/sql/parser/testdata/create_table
  pkg/sql/parser/testdata/select_exprs
  pkg/sql/pg_catalog.go
  pkg/sql/pgwire/pgwirebase/encoding.go
  pkg/sql/pgwire/testdata/pgtest/citext
  pkg/sql/randgen/datum.go
  pkg/sql/rowenc/valueside/BUILD.bazel
  pkg/sql/rowenc/valueside/decode.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/builtins/pgformat/format_test.go
  pkg/sql/sem/cast/cast_map.go
  pkg/sql/sem/eval/cast.go
  pkg/sql/sem/eval/match.go
  pkg/sql/sem/tree/BUILD.bazel
  pkg/sql/sem/tree/constant.go
  pkg/sql/sem/tree/datum.go
  pkg/sql/sem/tree/datum_alloc.go
  pkg/sql/sem/tree/expr.go
  pkg/sql/sem/tree/parse_string.go
  pkg/sql/sem/tree/pretty.go
  pkg/sql/types/BUILD.bazel
  pkg/sql/types/oid.go
  pkg/sql/types/types.go
  pkg/sql/types/types.proto
  pkg/sql/types/types_test.go
  pkg/util/collatedstring/collatedstring.go
  pkg/workload/rand/schema.go
Labels: backport

#150375 release-25.3: sql: populate estimated_last_login_time for all authenticating users
  pkg/backup/backup_test.go
  pkg/backup/full_cluster_backup_restore_test.go
  pkg/backup/testdata/backup-restore/restore-mixed-version
  pkg/ccl/multiregionccl/cold_start_latency_test.go
  pkg/sql/logictest/testdata/logic_test/drop_user
  pkg/sql/logictest/testdata/logic_test/role
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/logictest/testdata/logic_test/user
  pkg/sql/pgwire/auth.go
  pkg/sql/user.go
Labels: O-robot, blathers-backport, backport

#150360 release-25.3: sql/schemachanger: properly discard zone configs for sequences
  pkg/sql/logictest/testdata/logic_test/zone_config
  pkg/sql/schemachanger/scdecomp/decomp.go
Labels: O-robot, blathers-backport, backport

#149925 release-25.1.9-rc: distsql: fix recently introduced leak of CancelFunc
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/sql/distsql/server.go
Labels: backport

#149919 release-25.2: distsql: fix recently introduced leak of CancelFunc
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/sql/distsql/server.go
Labels: O-robot, blathers-backport, backport

#149924 release-25.1: distsql: fix recently introduced leak of CancelFunc
  pkg/kv/kvclient/kvstreamer/streamer.go
  pkg/sql/distsql/server.go
Labels: backport

#150415 roachtest: fix nodejs install helper function
  pkg/cmd/roachtest/tests/javascript_helpers.go
Labels: backport-25.3.x

#150183 release-24.1: changefeedccl: add detailed Kafka v2 message too large error logs gated by cluster setting
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/ccl/changefeedccl/batching_sink.go
  pkg/ccl/changefeedccl/changefeedbase/settings.go
  pkg/ccl/changefeedccl/sink_kafka_v2.go
  pkg/ccl/changefeedccl/sink_kafka_v2_test.go
  pkg/ccl/changefeedccl/sink_pubsub_v2.go
  pkg/ccl/changefeedccl/sink_webhook_v2.go
Labels: backport

#150445 gssapiccl: revert "link with `keyutils` on `s390x`"
  build/toolchains/BUILD.bazel
  pkg/ccl/gssapiccl/BUILD.bazel
Labels: backport-25.3.x

#150442 release-25.3: upgradeccl: ensure multiple releases for TestTenantUpgradeFailure test
  pkg/ccl/kvccl/kvtenantccl/upgradeccl/tenant_upgrade_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#150453 release-25.3: gssapiccl: revert "link with `keyutils` on `s390x`"
  build/toolchains/BUILD.bazel
  pkg/ccl/gssapiccl/BUILD.bazel
Labels: O-robot, blathers-backport, backport

#150449 release-25.3: go.mod: bump Pebble to 36d0909a10db
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#150447 release-25.3: kvcoord: disallow pipelining while write buffering is enabled
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_client_test.go
Labels: O-robot, blathers-backport, backport

#150446 release-25.2: kvcoord: disallow pipelining while write buffering is enabled
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/txn_coord_sender.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_client_test.go
Labels: O-robot, blathers-backport, backport

#150463 release-25.3: roachtest: unblock rust-postgres test case fixed by #22463
  pkg/cmd/roachtest/tests/rust_postgres_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#150457 release-24.3: bazel: don't `lintonbuild` in `ci` configuration
  .bazelrc
Labels: O-robot, blathers-backport, backport

#150441 release-25.2.3-rc: catalog: allow offline descriptors for type hydrations
  pkg/sql/catalog/descs/BUILD.bazel
  pkg/sql/catalog/descs/descriptor.go
  pkg/sql/catalog/descs/hydrate.go
  pkg/sql/catalog/resolver/resolver_test.go
Labels: O-robot, blathers-backport, backport

#150148 release-23.2: server: do not use MustBeDString on nullable result col
  pkg/server/admin.go
  pkg/server/application_api/storage_inspection_test.go
Labels: backport

#150503 release-25.3: teamcity: add `s390x` unit tests build configuration
  build/teamcity/cockroach/ci/tests-ibm-cloud-linux-s390x/unit_tests.sh
  build/teamcity/cockroach/ci/tests-ibm-cloud-linux-s390x/unit_tests_impl.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#150516 release-25.3: workload/schemachange: don't use CITEXT in mixed version cluster
  pkg/workload/schemachange/BUILD.bazel
  pkg/workload/schemachange/operation_generator.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#150440 release-25.3: catalog: allow offline descriptors for type hydrations
  pkg/sql/catalog/descs/BUILD.bazel
  pkg/sql/catalog/descs/descriptor.go
  pkg/sql/catalog/descs/hydrate.go
  pkg/sql/catalog/resolver/resolver_test.go
Labels: O-robot, blathers-backport, backport

#150406 kvcoord: make GetRequest transforms configurable
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
Labels: backport-25.3.x

#150558 util/log: fix data race in (*StructuredLogSpy).Intercept
  pkg/jobs/jobs_test.go
  pkg/sql/event_log_test.go
  pkg/sql/sql_exec_log_test.go
  pkg/util/log/event_log_test.go
  pkg/util/log/logtestutils/structured_log_spy.go
Labels: backport-25.3.x

#150476 provisioning: add usability counters for enabling ldap provisioning
  pkg/security/provisioning/BUILD.bazel
  pkg/security/provisioning/settings.go
  pkg/sql/pgwire/auth.go
  pkg/sql/pgwire/auth_methods.go
Labels: backport-25.3.x

#150581 release-25.3: util/log: fix data race in (*StructuredLogSpy).Intercept
  pkg/jobs/jobs_test.go
  pkg/sql/sql_exec_log_test.go
  pkg/util/log/logtestutils/structured_log_spy.go
Labels: backport

#150429 roachtest: add flaky test cases to ruby-pg ignoreList
  pkg/cmd/roachtest/tests/ruby_pg_blocklist.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x, backport-25.3.x

#150591 release-25.3: roachtest: add flaky test cases to ruby-pg ignoreList
  pkg/cmd/roachtest/tests/ruby_pg_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#150589 release-25.1: roachtest: add flaky test cases to ruby-pg ignoreList
  pkg/cmd/roachtest/tests/ruby_pg_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#150688 release: add support for no-telemetry build for FIPS
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-linux-amd64-fips-no-telemetry.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-per-platform.sh
Labels: C-enhancement, A-release, T-release, backport-25.2.x, backport-25.3.x

#150705 release-25.3: release: add linux-amd64-fips to GPG signing script
  build/teamcity/internal/cockroach/release/publish/sign-custom-release.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#150714 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#150713 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#150711 release-25.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#150620 release-25.3: sql: fix super region placement in 3-region database with secondary region
  pkg/ccl/logictestccl/testdata/logic_test/secondary_region
  pkg/ccl/logictestccl/testdata/logic_test/super_regions
  pkg/sql/regions/region_util.go
Labels: O-robot, blathers-backport, backport

#150528 release-25.3: teamcity: add `s390x-test-failure` label for relevant unit test failures
  build/teamcity/cockroach/ci/tests-ibm-cloud-linux-s390x/unit_tests_impl.sh
  pkg/cmd/bazci/bazci.go
  pkg/cmd/bazci/githubpost/githubpost.go
Labels: O-robot, blathers-backport, backport

#150781 release-25.3: teamcity: fix extra labels logic
  pkg/cmd/bazci/githubpost/githubpost.go
Labels: O-robot, blathers-backport, backport
