Repository cockroachdb/cockroach, pull requests merged in 2025-06, with the labels that each got.

#146331 kvserver: introduce setting to periodically reset split samples
  pkg/kv/kvserver/asim/state/split_decider.go
  pkg/kv/kvserver/replica_split_load.go
  pkg/kv/kvserver/split/decider.go
  pkg/kv/kvserver/split/decider_test.go
Labels: backport-24.3.x, backport-25.1.x, backport-25.2.x

#147468 release-25.2.1-rc: sql: do not rewrite UDF body statement slice while assigning placeholders
  pkg/sql/logictest/testdata/logic_test/udf_prepare
  pkg/sql/opt/norm/factory.go
Labels: backport

#147580 release-25.2: go.mod: bump Pebble to 55b3232677a3
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/storage/testdata/wal_failover_config
Labels: backport

#147583 release-24.1: go.mod: bump Pebble to d66731e169ea
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/storage/testdata/wal_failover_config
Labels: backport

#147582 release-24.3: go.mod: bump Pebble to 2b6d7dd769b3
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/storage/testdata/wal_failover_config
Labels: backport

#147556 randgen: increase pool size for "heavy" configs
  pkg/sql/randgen/BUILD.bazel
Labels: backport-25.1.x, backport-25.2.x

#147610 release-25.1: randgen: increase pool size for "heavy" configs
  pkg/sql/randgen/BUILD.bazel
Labels: O-robot, blathers-backport, backport, backport-test-only

#147433 ui: fix index link from sql activity plan details page
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x

#147638 release-25.2: ui: fix index link from sql activity plan details page
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.module.scss
  pkg/ui/workspaces/cluster-ui/src/statementDetails/planDetails/plansTable.tsx
Labels: O-robot, blathers-backport, backport

#147658 sql/schemachanger: fix nil pointer preparing a schema changer statement
  pkg/sql/schema_change_plan_node.go
  pkg/sql/sql_prepare_test.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x

#147678 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#147677 release-25.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#147675 release-25.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#147673 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#147613 release-23.2: released CockroachDB version 23.2.26. Next version: 23.2.27
  pkg/build/version.txt
Labels: backport

#147614 release-24.1: released CockroachDB version 24.1.19. Next version: 24.1.20
  pkg/build/version.txt
Labels: backport, backport-test-only

#147616 release-25.1: released CockroachDB version 25.1.7. Next version: 25.1.8
  pkg/build/version.txt
Labels: backport, backport-test-only

#143738 roachprod-microbench: post github issues
  build/teamcity/cockroach/nightlies/microbenchmark_weekly.sh
  pkg/cmd/bazci/githubpost/githubpost.go
  pkg/cmd/roachprod-microbench/BUILD.bazel
  pkg/cmd/roachprod-microbench/executor.go
  pkg/cmd/roachprod-microbench/github.go
  pkg/cmd/roachprod-microbench/github_test.go
  pkg/cmd/roachprod-microbench/main.go
  pkg/cmd/roachprod-microbench/testdata/github/issue.txt
Labels: target-release-25.3.0

#147716 roachtest: skip test in ActiveRecord
  pkg/cmd/roachtest/tests/activerecord_blocklist.go
Labels: backport-25.2.x

#147246 release-25.2: xform: increase pool size for "heavy" configs
  pkg/sql/opt/xform/BUILD.bazel
Labels: O-robot, blathers-backport, backport

#147245 release-25.1: xform: increase pool size for "heavy" configs
  pkg/sql/opt/xform/BUILD.bazel
Labels: O-robot, blathers-backport, backport

#147609 pkg/kv/kvpb: Add SafeFormat method to BatchResponse struct
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvpb/batch.go
Labels: backport-24.3.x, backport-25.1.x, backport-25.2.x, backport-24.2.x

#147734 kvserver: fix data race in (*Replica).State
  pkg/kv/kvserver/replica.go
Labels: target-release-25.3.0

#147726 release-25.2: workload/schemachanger: expect errors during secondary index recreation
  pkg/workload/schemachange/operation_generator.go
Labels: backport, backport-test-only

#147803 cli: harden `debug sb recreate` a bit
  pkg/cli/statement_bundle.go
Labels: backport-all

#147711 release-25.2: sql: block ALTER TABLE of identity columns not backed by a sequence
  pkg/sql/alter_table.go
  pkg/sql/logictest/testdata/logic_test/alter_table
Labels: O-robot, blathers-backport, backport

#147710 release-25.1: sql: block ALTER TABLE of identity columns not backed by a sequence
  pkg/sql/alter_table.go
  pkg/sql/logictest/testdata/logic_test/alter_table
Labels: O-robot, blathers-backport, backport

#147778 release-25.2: db-console: add client side hot range filtering by node
  pkg/ui/workspaces/cluster-ui/src/api/nodesApi.ts
  pkg/ui/workspaces/cluster-ui/src/components/index.ts
  pkg/ui/workspaces/cluster-ui/src/components/nodeSelector/nodeSelector.module.scss
  pkg/ui/workspaces/cluster-ui/src/components/nodeSelector/nodeSelector.spec.tsx
  pkg/ui/workspaces/cluster-ui/src/components/nodeSelector/nodeSelector.tsx
  pkg/ui/workspaces/cluster-ui/src/index.ts
  pkg/ui/workspaces/cluster-ui/src/loading/loading.module.scss
  pkg/ui/workspaces/cluster-ui/src/loading/loading.tsx
  pkg/ui/workspaces/cluster-ui/src/pages/databases/components/index.ts
  pkg/ui/workspaces/cluster-ui/src/pages/databases/components/nodeRegionsSelector/nodeRegionsSelector.tsx
  pkg/ui/workspaces/cluster-ui/src/pages/databases/databasesPageRoot.tsx
  pkg/ui/workspaces/cluster-ui/src/pages/databases/index.ts
  pkg/ui/workspaces/cluster-ui/src/pages/databases/utils.ts
  pkg/ui/workspaces/cluster-ui/src/pages/databases/views/databaseDetails/tablesView.tsx
  pkg/ui/workspaces/cluster-ui/src/statementsPage/statementsPage.fixture.ts
  pkg/ui/workspaces/cluster-ui/src/types/index.ts
  pkg/ui/workspaces/db-console/src/redux/apiReducers.ts
  pkg/ui/workspaces/db-console/src/views/hotRanges/hotRanges.module.styl
  pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesFilter.tsx
  pkg/ui/workspaces/db-console/src/views/hotRanges/hotRangesTable.tsx
  pkg/ui/workspaces/db-console/src/views/hotRanges/index.tsx
  pkg/ui/workspaces/db-console/src/views/hotRanges/useFilters.ts
Labels: backport

#147682 sql: increase observability of automatic statement retries
  docs/generated/metrics/metrics.yaml
  pkg/ccl/kvccl/kvfollowerreadsccl/testdata/boundedstaleness/single_row
  pkg/ccl/logictestccl/testdata/logic_test/txn_retry
  pkg/ccl/logictestccl/tests/3node-tenant/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-disk/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist-disk/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/fakedist/BUILD.bazel
  pkg/ccl/logictestccl/tests/fakedist/generated_test.go
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-legacy-schema-changer/generated_test.go
  pkg/ccl/logictestccl/tests/local-mixed-25.2/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-mixed-25.2/generated_test.go
  pkg/ccl/logictestccl/tests/local-read-committed/generated_test.go
  pkg/ccl/logictestccl/tests/local-repeatable-read/generated_test.go
  pkg/ccl/logictestccl/tests/local-schema-locked/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-schema-locked/generated_test.go
  pkg/ccl/logictestccl/tests/local-vec-off/BUILD.bazel
  pkg/ccl/logictestccl/tests/local-vec-off/generated_test.go
  pkg/ccl/logictestccl/tests/local/generated_test.go
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_util.go
  pkg/sql/executor_statement_metrics.go
  pkg/sql/faketreeeval/evalctx.go
  pkg/sql/instrumentation.go
  pkg/sql/logictest/testdata/logic_test/txn_retry
  pkg/sql/opt/exec/explain/BUILD.bazel
  pkg/sql/opt/exec/explain/main_test.go
  pkg/sql/opt/exec/explain/output.go
  pkg/sql/opt/exec/explain/output_test.go
  pkg/sql/planner.go
  pkg/sql/prepared_stmt.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/eval/deps.go
  pkg/sql/sessionphase/session_phase.go
  pkg/sql/txn_state.go
Labels: backport-24.3.x, backport-25.1.x, backport-25.2.x

#147812 release-25.1: cli: harden `debug sb recreate` a bit
  pkg/cli/statement_bundle.go
Labels: O-robot, blathers-backport, backport

#147467 release-25.2: ui: fix activate diagnostics modal infinite render bug
  pkg/ui/workspaces/cluster-ui/src/statementsDiagnostics/activateStatementDiagnosticsModal.tsx
Labels: O-robot, blathers-backport, backport

#147466 release-25.1: ui: fix activate diagnostics modal infinite render bug
  pkg/ui/workspaces/cluster-ui/src/statementsDiagnostics/activateStatementDiagnosticsModal.tsx
Labels: O-robot, blathers-backport, backport

#147465 release-25.2: ui: fix live data percentage on table overview
  pkg/ui/workspaces/cluster-ui/src/pages/databases/views/tableDetailsV2/tableOverview.tsx
Labels: O-robot, blathers-backport, backport

#147652 regionliveness: avoid region_liveness can when disabled
  pkg/sql/regionliveness/prober.go
Labels: backport-all

#147842 release-25.2: sql: decode all plan gists in test builds
  pkg/sql/conn_executor_exec.go
Labels: O-robot, blathers-backport, backport

#147865 release-25.1: sql: fix maybeAdjustVirtualIndexScanForExplain for good
  pkg/sql/opt/exec/execbuilder/testdata/explain_gist
  pkg/sql/virtual_schema.go
Labels: O-robot, blathers-backport, backport

#147866 release-25.2: sql: fix maybeAdjustVirtualIndexScanForExplain for good
  pkg/sql/opt/exec/execbuilder/testdata/explain_gist
  pkg/sql/virtual_schema.go
Labels: O-robot, blathers-backport, backport

#147771 release-24.1: sql: block ALTER TABLE of identity columns not backed by a sequence
  pkg/sql/alter_table.go
  pkg/sql/logictest/testdata/logic_test/alter_table
Labels: backport

#147768 release-24.3: sql: block ALTER TABLE of identity columns not backed by a sequence
  pkg/sql/alter_table.go
  pkg/sql/logictest/testdata/logic_test/alter_table
Labels: backport

#147899 release-25.2: roachtest: end sysbench's bench.txt with newline
  pkg/cmd/roachtest/tests/sysbench.go
  pkg/cmd/roachtest/tests/sysbench_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#147696 sql/rls: retain function backrefs when updating policy dependencies
  pkg/sql/catalog/funcdesc/func_desc.go
  pkg/sql/logictest/testdata/logic_test/row_level_security
Labels: backport-25.2.x

#147504 release-25.2: kvserver: improve logs during adminScatter
  pkg/kv/kvserver/replica_command.go
Labels: backport

#147503 release-25.1: kvserver: improve logs during adminScatter
  pkg/kv/kvserver/replica_command.go
Labels: backport

#147502 release-24.3: kvserver: improve logs during adminScatter
  pkg/kv/kvserver/replica_command.go
Labels: backport

#147983 release-25.2: released CockroachDB version 25.2.1. Next version: 25.2.2
  pkg/build/version.txt
Labels: backport, backport-test-only

#147973 release: fix verify_docker_image call in publish-staged-cockroach-release.sh
  build/teamcity/internal/cockroach/release/publish/publish-staged-cockroach-release.sh
Labels: C-bug, A-release, T-release, backport-25.2.x

#148003 release-25.2: release: fix verify_docker_image call in publish-staged-cockroach-release.sh
  build/teamcity/internal/cockroach/release/publish/publish-staged-cockroach-release.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#147905 release-25.2: sql/rls: retain function backrefs when updating policy dependencies
  pkg/sql/catalog/funcdesc/func_desc.go
  pkg/sql/logictest/testdata/logic_test/row_level_security
Labels: O-robot, blathers-backport, backport

#148053 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#148054 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#148051 release-25.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#148049 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#148050 release-25.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#148039 release-23.2: release: retry rcodesign notary-submit in macos signing scripts
  build/teamcity/internal/cockroach/release/publish/sign_staged_macos_release_on_linux.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-darwin-sign.sh
Labels: O-robot, blathers-backport, backport, target-release-23.2.28

#148042 release-24.3: release: retry rcodesign notary-submit in macos signing scripts
  build/teamcity/internal/cockroach/release/publish/sign_staged_macos_release_on_linux.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-darwin-sign.sh
Labels: O-robot, blathers-backport, backport, backport-test-only, target-release-24.3.16

#148044 release-25.2: release: retry rcodesign notary-submit in macos signing scripts
  build/teamcity/internal/cockroach/release/publish/sign_staged_macos_release_on_linux.sh
  build/teamcity/internal/release/process/make-and-publish-build-artifacts-darwin-sign.sh
Labels: O-robot, blathers-backport, backport, backport-test-only, target-release-25.2.2

#148010 release-24.3.15-rc: release-24.3: crosscluster/logical: zero catchup/initial scan metrics on flow shutdown
  pkg/ccl/crosscluster/logical/logical_replication_job.go
Labels: backport, target-release-24.3.15

#148024 workload/rand: refactor schema handling for reuse
  pkg/workload/rand/BUILD.bazel
  pkg/workload/rand/rand.go
  pkg/workload/rand/rand_test.go
  pkg/workload/rand/schema.go
Labels: target-release-25.3.0

#148082 release-25.2: go.mod: bump Pebble to 4f5d42f6d69f
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/storage/testdata/wal_failover_config
Labels: backport, target-release-25.2.2

#148006 release-24.1: restore: fix split race in split and scatter processor
  pkg/ccl/backupccl/generative_split_and_scatter_processor.go
  pkg/ccl/backupccl/generative_split_and_scatter_processor_test.go
Labels: backport, target-release-24.1.21

#148083 release-23.2: release-24.1: restore: fix split race in split and scatter processor
  pkg/ccl/backupccl/generative_split_and_scatter_processor.go
  pkg/ccl/backupccl/generative_split_and_scatter_processor_test.go
Labels: backport, target-release-23.2.28

#147875 release-25.2: sql: verify correct query vector length when building a vector search
  pkg/sql/logictest/testdata/logic_test/vector_index
  pkg/sql/opt/exec/execbuilder/relational.go
Labels: backport

#147914 cloud/amazon: add option to skip TLS verification for backup/restore
  pkg/cloud/amazon/aws_kms.go
  pkg/cloud/amazon/s3_storage.go
  pkg/cloud/amazon/s3_storage_test.go
  pkg/cloud/azure/azure_storage.go
  pkg/cloud/cloud_io.go
  pkg/cloud/cloudpb/external_storage.proto
  pkg/cloud/gcp/gcs_storage.go
  pkg/cloud/httpsink/http_storage.go
  pkg/cmd/roachtest/tests/s3_clone_backup_restore.go
  pkg/cmd/roachtest/tests/s3_microceph.go
Labels: backport-24.3.x, backport-25.1.x, backport-25.2.x

#147998 sql/schemachanger: prevent runtime errors adding multiple columns
  pkg/ccl/schemachangerccl/testdata/end_to_end/alter_table_alter_primary_key_rbr/alter_table_alter_primary_key_rbr.explain
  pkg/cli/testdata/declarative-rules/deprules
  pkg/sql/logictest/testdata/logic_test/schema_locked
  pkg/sql/schemachanger/scplan/internal/rules/current/dep_add_index_and_column.go
  pkg/sql/schemachanger/scplan/internal/rules/current/testdata/deprules
  pkg/sql/schemachanger/scplan/internal/rules/release_25_2/dep_add_index_and_column.go
  pkg/sql/schemachanger/scplan/internal/rules/release_25_2/testdata/deprules
  pkg/sql/schemachanger/scplan/testdata/alter_table_alter_primary_key
  pkg/sql/schemachanger/scplan/testdata/alter_table_drop_column
  pkg/sql/schemachanger/scplan/testdata/create_index
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_add_primary_key_drop_rowid_with_secondary_idx/alter_table_add_primary_key_drop_rowid_with_secondary_idx.explain
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_primary_key_using_hash/alter_table_alter_primary_key_using_hash.explain
Labels: backport-25.2.x

#147977 release-25.2: sql: handle dropped schemas in crdb_internal.table_spans
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/resolver.go
Labels: O-robot, blathers-backport, backport

#148153 release-25.2: workload/schemachanger: treat dependency error as potential error in column rename
  pkg/workload/schemachange/error_screening.go
  pkg/workload/schemachange/operation_generator.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148169 release: install helm for generating PRs
  build/teamcity/internal/cockroach/release/process/update_versions_impl.sh
Labels: C-bug, A-release, T-release, backport-25.2.x, backport-25.2.2-rc

#148021 release-25.1: crosscluster/logical: wipe status on clean pause
  pkg/crosscluster/logical/logical_replication_job.go
Labels: backport

#148022 release-24.3: crosscluster/logical: wipe status on clean pause
  pkg/ccl/crosscluster/logical/logical_replication_job.go
Labels: backport

#148161 githubpost: remove triage column card
  TEAMS.yaml
  pkg/cmd/bazci/githubpost/githubpost.go
  pkg/cmd/bazci/githubpost/githubpost_test.go
  pkg/cmd/bazci/githubpost/issues/issues.go
  pkg/cmd/roachprod-microbench/github_test.go
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/internal/team/TEAMS.yaml
  pkg/internal/team/team.go
  pkg/internal/team/team_test.go
Labels: backport-all

#148173 release-25.2: release: install helm for generating PRs
  build/teamcity/internal/cockroach/release/process/update_versions_impl.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#148030 admission: use flush duration instead of utilization to ignore low va…
  pkg/util/admission/io_load_listener.go
  pkg/util/admission/testdata/io_load_listener
Labels: backport-24.3.x, backport-25.1.x, backport-25.2.x

#148225 aceeptance: add script to build and push the acceptance image
  pkg/acceptance/testdata/README.md
  pkg/acceptance/testdata/build-push-acceptance.sh
  pkg/cmd/roachtest/tests/backup_fixtures.go
Labels: C-enhancement, A-build-system, T-dev-inf

#148228 release-24.3: sql: add exponential backoff to read committed stmt retry loop
  docs/generated/metrics/metrics.html
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_util.go
  pkg/sql/executor_statement_metrics.go
  pkg/sql/explain_bundle.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
  pkg/workload/kv/kv.go
Labels: backport

#148229 release-24.3.15: sql: add exponential backoff to read committed stmt retry loop
  docs/generated/metrics/metrics.html
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_util.go
  pkg/sql/executor_statement_metrics.go
  pkg/sql/explain_bundle.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
  pkg/workload/kv/kv.go
Labels: backport

#148048 release-24.3: sql: handle dropped schemas in crdb_internal.table_spans
  pkg/sql/information_schema.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal
  pkg/sql/resolver.go
Labels: backport

#148309 release-25.2.2-rc: changefeedccl: fix table drop shutdown for enriched envelope
  pkg/ccl/changefeedccl/enriched_source_provider.go
Labels: O-robot, blathers-backport, backport

#148409 WORKSPACE: update pgo profile
  WORKSPACE
Labels: C-performance, A-build-system, A-release, T-release

#148325 release-25.2: go.mod: bump Pebble to b85e063b4c9e
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#148327 release-24.3: go.mod: bump Pebble to b41537d0a925
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#148394 release-25.2: execbuilder: fix a silly bug around finding the most recent full stat
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/partial_stats
Labels: O-robot, blathers-backport, backport

#148393 release-25.1: execbuilder: fix a silly bug around finding the most recent full stat
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/partial_stats
Labels: O-robot, blathers-backport, backport

#148392 release-24.3: execbuilder: fix a silly bug around finding the most recent full stat
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/partial_stats
Labels: O-robot, blathers-backport, backport

#148098 restore: gracefully handle lookup of dropped temp system tables
  pkg/backup/restore_job.go
  pkg/backup/restore_online.go
  pkg/backup/restore_online_test.go
  pkg/backup/restore_test.go
Labels: backport-25.2.x

#148352 kvserver: register `SideTransport` service with DRPC server
  pkg/kv/kvserver/closedts/sidetransport/receiver.go
  pkg/server/server.go
Labels: target-release-25.3.0

#147927 db-console: update hot ranges link to understanding hotspots page in …
  pkg/ui/workspaces/db-console/src/util/docs.ts
Labels: backport-25.1.x, backport-25.2.x

#148526 release-24.1: roachtest: deflake gopg
  pkg/cmd/roachtest/tests/gopg_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148466 benchprof: fix nil pointer exception
  pkg/bench/benchprof/benchprof.go
Labels: o-perf-efficiency

#148529 release-25.2: roachtest: deflake gopg
  pkg/cmd/roachtest/tests/gopg_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148595 storeliveness: skip TestStoreLivenessRestart under duress
  pkg/kv/kvserver/storeliveness/BUILD.bazel
  pkg/kv/kvserver/storeliveness/multi_store_test.go
Labels: backport-25.2.x

#148670 release-25.2: kvserver: deflake TestReplicateQueueUpReplicateOddVoters
  pkg/kv/kvserver/replicate_queue_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148671 release-25.2: storage_api: don't check raft status in test
  pkg/server/storage_api/ranges_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148666 release-24.3: kvserver: deflake TestReplicateQueueUpReplicateOddVoters
  pkg/kv/kvserver/replicate_queue_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148669 release-25.1: storage_api: don't check raft status in test
  pkg/server/storage_api/ranges_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148662 release-23.2: kvserver: deflake TestReplicateQueueUpReplicateOddVoters
  pkg/kv/kvserver/replicate_queue_test.go
Labels: O-robot, blathers-backport, backport

#148663 release-23.2: storage_api: don't check raft status in test
  pkg/server/storage_api/ranges_test.go
Labels: O-robot, blathers-backport, backport

#148664 release-24.1: kvserver: deflake TestReplicateQueueUpReplicateOddVoters
  pkg/kv/kvserver/replicate_queue_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148665 release-24.1: storage_api: don't check raft status in test
  pkg/server/storage_api/ranges_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148677 release-25.1: roachtest: more CPU profiling in rebalancing tests
  pkg/cmd/roachtest/tests/rebalance_load.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148470 release-24.3: pgwire: limit size of SSL frames sent
  pkg/acceptance/adapter_test.go
  pkg/acceptance/testdata/Dockerfile
  pkg/acceptance/testdata/node/base-test.js
  pkg/acceptance/testdata/python/test_pyscopg3.py
  pkg/acceptance/util_docker.go
  pkg/sql/pgwire/conn.go
Labels: backport

#148472 release-24.1: pgwire: limit size of SSL frames sent
  pkg/acceptance/adapter_test.go
  pkg/acceptance/testdata/Dockerfile
  pkg/acceptance/testdata/node/base-test.js
  pkg/acceptance/testdata/python/test_pyscopg3.py
  pkg/acceptance/util_docker.go
  pkg/sql/pgwire/conn.go
Labels: backport

#148702 release-25.2: roachtest: mark psycopg test as flaky
  pkg/cmd/roachtest/tests/psycopg_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148477 release-24.1: execbuilder: fix a silly bug around finding the most recent full stat
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/testdata/partial_stats
Labels: backport

#148692 storage: bump Pebble, fix up code, prefer fast compression for local keys
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cli/debug.go
  pkg/storage/metamorphic/options.go
  pkg/storage/open.go
  pkg/storage/pebble.go
Labels: X-perf-gain

#148712 release-25.2: kvcoord: fix memory leak on rollbacks in txnWriteBuffer in some cases
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
Labels: O-robot, blathers-backport, backport

#148699 catalog/lease: handle range feed recovery for dropped descriptors
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_test.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x

#146526 kvserver: improve tenant_id CPU observability
  docs/generated/metrics/metrics.yaml
  pkg/kv/kvserver/metrics.go
  pkg/kv/kvserver/metrics_test.go
  pkg/kv/kvserver/mvcc_gc_queue.go
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_rate_limit.go
  pkg/kv/kvserver/replica_send.go
  pkg/kv/kvserver/replica_test.go
Labels: O-support

#147160 release-24.1: changefeed: fix race in cloudstorage sink
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/sink_cloudstorage.go
  pkg/ccl/changefeedccl/sink_cloudstorage_test.go
  pkg/testutils/skip/skip.go
Labels: backport

#147161 release-24.3: changefeed: fix race in cloudstorage sink
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/sink_cloudstorage.go
  pkg/ccl/changefeedccl/sink_cloudstorage_test.go
  pkg/testutils/skip/skip.go
Labels: backport

#147162 release-25.1: changefeed: fix race in cloudstorage sink
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/ccl/changefeedccl/sink_cloudstorage.go
  pkg/ccl/changefeedccl/sink_cloudstorage_test.go
  pkg/testutils/skip/skip.go
Labels: backport

#148716 release-25.1: catalog/lease: handle range feed recovery for dropped descriptors
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_test.go
Labels: O-robot, blathers-backport, backport

#148570 kvclient: update error formatting in BatchResponse and improve test expectations in dist_sender_test
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvpb/batch.go
Labels: backport-24.3.x, backport-25.1.x, backport-25.2.x, backport-24.2.x

#148382 release-25.3: clusterversion: set devBranch to false
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  pkg/build/version.txt
  pkg/cli/testdata/declarative-rules/deprules
  pkg/cli/testdata/declarative-rules/invalid_version
  pkg/clusterversion/README.md
  pkg/clusterversion/cockroach_versions.go
  pkg/sql/catalog/bootstrap/bootstrap_test.go
  pkg/sql/catalog/bootstrap/testdata/testdata
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_system
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_tenant
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
Labels: A-release, T-release

#148719 pgwire: support decoding VECTOR and BOX2D from binary
  pkg/sql/pgwire/pgwirebase/BUILD.bazel
  pkg/sql/pgwire/pgwirebase/encoding.go
  pkg/sql/pgwire/testdata/pgtest/box2d
  pkg/sql/pgwire/testdata/pgtest/pgvector
  pkg/util/vector/vector.go
Labels: backport-25.3.x

#148776 release-25.1: workload/schemachanger: apply statement_timeout out to CTAS
  pkg/workload/schemachange/operation_generator.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148774 release-24.1: workload/schemachanger: apply statement_timeout out to CTAS
  pkg/workload/schemachange/operation_generator.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148824 logictest: deflake drop_database
  pkg/sql/logictest/testdata/logic_test/drop_database
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x, backport-25.3.x

#148848 server/profiler: bump heap profiler size limit from 256MiB to 512MiB
  pkg/server/profiler/heapprofiler.go
Labels: backport-25.3.x

#148852 release-24.1: logictest: deflake drop_database
  pkg/sql/logictest/testdata/logic_test/drop_database
Labels: O-robot, blathers-backport, backport, backport-test-only

#148856 release-25.3: logictest: deflake drop_database
  pkg/sql/logictest/testdata/logic_test/drop_database
Labels: O-robot, blathers-backport, backport, backport-test-only

#148860 release-25.3: server/profiler: bump heap profiler size limit from 256MiB to 512MiB
  pkg/server/profiler/heapprofiler.go
Labels: O-robot, blathers-backport, backport

#148849 storage: bump Pebble, add new experimental compression settings
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  docs/generated/settings/settings-for-tenants.txt
  docs/generated/settings/settings.html
  go.mod
  go.sum
  pkg/kv/kvserver/kvstorage/snaprecv/sst_snapshot_storage_test.go
  pkg/kv/kvserver/rangefeed/event_size_test.go
  pkg/storage/pebble.go
  pkg/storage/sst_writer.go
  pkg/storage/sst_writer_test.go
Labels: backport-25.3.x

#148751 kvcoord: transform replicated, locking [Reverse]Scan requests
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
Labels: backport-25.3.x

#148877 release-24.3: pkg/kv/kvpb: Add SafeFormat method to BatchResponse struct
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvpb/batch.go
Labels: backport

#148889 release-25.1: pkg/kv/kvpb: Add SafeFormat method to BatchResponse struct
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvpb/batch.go
Labels: backport

#148890 release-25.2: pkg/kv/kvpb: Add SafeFormat method to BatchResponse struct
  pkg/kv/kvclient/kvcoord/dist_sender_test.go
  pkg/kv/kvpb/batch.go
Labels: backport

#148870 release-25.3: logictest: adjust a few of geo tests for s390x
  pkg/sql/logictest/testdata/logic_test/distsql_stats
  pkg/sql/logictest/testdata/logic_test/geospatial
  pkg/sql/opt/exec/execbuilder/testdata/geospatial
Labels: O-robot, blathers-backport, backport, backport-test-only

#147133 sqlstats: fix data race between collector and ingester
  pkg/sql/sqlstats/sslocal/BUILD.bazel
  pkg/sql/sqlstats/sslocal/doc.go
  pkg/sql/sqlstats/sslocal/sql_stats_ingester_test.go
  pkg/sql/sqlstats/sslocal/sql_stats_ingestor.go
  pkg/sql/sqlstats/sslocal/sslocal_stats_collector.go
Labels: backport-25.3.x

#148929 release-23.2: changefeedccl: add cluster setting for changefeed max retry backoff
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeedbase/settings.go
  pkg/ccl/changefeedccl/retry.go
Labels: backport

#148938 release-24.3: changefeedccl: add cluster setting for changefeed max retry backoff
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeedbase/settings.go
  pkg/ccl/changefeedccl/retry.go
Labels: backport

#148941 release-25.2: changefeedccl: add cluster setting for changefeed max retry backoff
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeedbase/settings.go
  pkg/ccl/changefeedccl/retry.go
Labels: backport

#148931 release-24.1: changefeedccl: add cluster setting for changefeed max retry backoff
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeedbase/settings.go
  pkg/ccl/changefeedccl/retry.go
Labels: backport

#148958 colserde,rowcontainer: prohibit writing very large keys
  pkg/col/colserde/BUILD.bazel
  pkg/col/colserde/arrowbatchconverter.go
  pkg/sql/rowcontainer/disk_row_container.go
Labels: backport-25.3.x

#148694 types: remove downgradeType function to fix data race
  pkg/cli/testdata/doctor/test_recreate_zipdir
  pkg/cli/testdata/doctor/test_recreate_zipdir-json
  pkg/sql/catalog/bootstrap/testdata/testdata
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_system
  pkg/sql/catalog/systemschema_test/testdata/bootstrap_tenant
  pkg/sql/crdb_internal_test.go
  pkg/sql/logictest/testdata/logic_test/crdb_internal_catalog
  pkg/sql/logictest/testdata/logic_test/udf_in_index
  pkg/sql/schemachanger/scbuild/testdata/alter_table_alter_column_type
  pkg/sql/schemachanger/scbuild/testdata/drop_database
  pkg/sql/schemachanger/scbuild/testdata/drop_owned_by
  pkg/sql/schemachanger/scbuild/testdata/drop_schema
  pkg/sql/schemachanger/scbuild/testdata/drop_type
  pkg/sql/schemachanger/scbuild/testdata/drop_view
  pkg/sql/schemachanger/scdecomp/testdata/type
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type_trivial/alter_table_alter_column_type_trivial.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/alter_table_alter_column_type_validation/alter_table_alter_column_type_validation.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_index_with_expression/create_index_with_expression.side_effects
  pkg/sql/types/types.go
  pkg/sql/types/types_jsonpb.go
  pkg/sql/types/types_test.go
Labels: backport-25.3.x

#148843 release-25.3: pgwire: support decoding VECTOR and BOX2D from binary
  pkg/sql/pgwire/pgwirebase/BUILD.bazel
  pkg/sql/pgwire/pgwirebase/encoding.go
  pkg/sql/pgwire/testdata/pgtest/box2d
  pkg/sql/pgwire/testdata/pgtest/pgvector
  pkg/util/vector/vector.go
Labels: O-robot, blathers-backport, backport

#149083 release-25.3: roachtest: disable create_table_with_schema_locked for certain tests
  pkg/ccl/changefeedccl/nemeses_test.go
  pkg/cmd/roachtest/tests/follower_reads.go
  pkg/cmd/roachtest/tests/sqlsmith.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#148854 release-25.1: logictest: deflake drop_database
  pkg/sql/logictest/testdata/logic_test/drop_database
Labels: O-robot, blathers-backport, backport, backport-test-only

#149102 roachtest: deflake tpcc/multiregion
  pkg/workload/tpcc/tpcc.go
Labels: backport-25.3.x

#148974 util/bufalloc: fix misuse and improve ByteAllocator API
  pkg/BUILD.bazel
  pkg/ccl/changefeedccl/event_processing.go
  pkg/ccl/changefeedccl/sink.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_sql.go
  pkg/crosscluster/streamclient/randclient/random_stream_client.go
  pkg/kv/kvnemesis/engine.go
  pkg/kv/kvserver/gc/gc.go
  pkg/kv/kvserver/gc/gc_iterator.go
  pkg/kv/kvserver/rangefeed/catchup_scan.go
  pkg/sql/rowcontainer/disk_row_container.go
  pkg/storage/mvcc.go
  pkg/storage/mvcc_logical_ops.go
  pkg/util/bufalloc/BUILD.bazel
  pkg/util/bufalloc/byte_allocator.go
  pkg/util/bufalloc/byte_allocator_test.go
  pkg/workload/bank/bank.go
  pkg/workload/bulkingest/bulkingest.go
  pkg/workload/kv/kv.go
  pkg/workload/tpcc/generate.go
  pkg/workload/tpcc/random.go
  pkg/workload/tpch/random.go
Labels: backport-25.3.x

#149113 release-25.3: switch to release branch in Pebble teamcity scripts
  build/teamcity/cockroach/nightlies/pebble_nightly_common.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_race.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_metamorphic_two_instance.sh
  build/teamcity/cockroach/nightlies/pebble_nightly_race_common.sh
Labels: backport, backport-test-only

#149114 release-25.3: util/bufalloc: fix misuse and improve ByteAllocator API
  pkg/BUILD.bazel
  pkg/ccl/changefeedccl/event_processing.go
  pkg/ccl/changefeedccl/sink.go
  pkg/ccl/changefeedccl/sink_kafka.go
  pkg/ccl/changefeedccl/sink_sql.go
  pkg/crosscluster/streamclient/randclient/random_stream_client.go
  pkg/kv/kvnemesis/engine.go
  pkg/kv/kvserver/gc/gc.go
  pkg/kv/kvserver/gc/gc_iterator.go
  pkg/kv/kvserver/rangefeed/catchup_scan.go
  pkg/sql/rowcontainer/disk_row_container.go
  pkg/storage/mvcc.go
  pkg/storage/mvcc_logical_ops.go
  pkg/util/bufalloc/BUILD.bazel
  pkg/util/bufalloc/byte_allocator.go
  pkg/util/bufalloc/byte_allocator_test.go
  pkg/workload/bank/bank.go
  pkg/workload/bulkingest/bulkingest.go
  pkg/workload/kv/kv.go
  pkg/workload/tpcc/generate.go
  pkg/workload/tpcc/random.go
  pkg/workload/tpch/random.go
Labels: O-robot, blathers-backport, backport

#149120 logictest: add missing ORDER BY to query that lists all session vars
  pkg/sql/logictest/testdata/logic_test/pg_catalog
Labels: backport-25.3.x

#149152 release-25.3: logictest: add missing ORDER BY to query that lists all session vars
  pkg/sql/logictest/testdata/logic_test/pg_catalog
Labels: O-robot, blathers-backport, backport, backport-test-only

#149215 release-24.3: released CockroachDB version v24.3.15. Next version: v24.3.16
  pkg/build/version.txt
Labels: backport, backport-test-only

#149221 release-23.2: released CockroachDB version v23.2.27. Next version: v23.2.28
  pkg/build/version.txt
Labels: backport

#149105 release-24.1: nightly-stress: move engflow stress jobs to run on mesolite
  build/teamcity/cockroach/nightlies/stress_engflow_impl.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#149108 release-25.2: nightly-stress: move engflow stress jobs to run on mesolite
  build/teamcity/cockroach/nightlies/stress_engflow_impl.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#149226 release-25.3: roachtest: adding defensive code in ceph/reef test
  pkg/cmd/roachtest/tests/s3_microceph.go
Labels: backport, backport-test-only

#149237 release-25.3: schemachanger: attempt to deflake schemachanger integration tests
  pkg/ccl/schemachangerccl/BUILD.bazel
  pkg/ccl/schemachangerccl/multiregion_testcluster_factory.go
  pkg/sql/schemachanger/sctest/BUILD.bazel
  pkg/sql/schemachanger/sctest/cumulative.go
  pkg/sql/schemachanger/sctest/decomp.go
  pkg/sql/schemachanger/sctest/end_to_end.go
  pkg/sql/schemachanger/sctest/test_server_factory.go
Labels: O-robot, blathers-backport, backport

#149233 release-25.3: roachtest: use multiple SSDs in schemachange/bulkingest
  pkg/cmd/roachtest/tests/schemachange.go
Labels: O-robot, blathers-backport, backport, backport-test-only
