Repository cockroachdb/cockroach, pull requests merged in 2025-05, with the labels that each got.

#145568 release-25.2: go.mod: bump Pebble to 0e8db0006a47
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cli/interactive_tests/test_encryption.tcl
Labels: backport

#145576 release-25.2: stats: fix "non-nullable col with no value" for multiple column families
  pkg/sql/create_stats_test.go
  pkg/sql/row/fetcher.go
Labels: O-robot, blathers-backport, backport

#145478 release-25.2: fix various backup compaction bugs
  go.mod
  pkg/backup/BUILD.bazel
  pkg/backup/backupinfo/BUILD.bazel
  pkg/backup/backupinfo/manifest_handling.go
  pkg/backup/backupinfo/manifest_handling_test.go
  pkg/backup/compaction_job.go
  pkg/backup/compaction_processor.go
  pkg/backup/compaction_test.go
  pkg/backup/datadriven_test.go
  pkg/backup/testdata/backup-restore/rangekeys
Labels: backport

#145257 workload: add a literal implementation of tpcc
  pkg/cmd/roachtest/tests/tpcc.go
  pkg/workload/tpcc/new_order.go
  pkg/workload/tpcc/payment.go
  pkg/workload/tpcc/tpcc.go
Labels: o-perf-efficiency

#145392 release-24.3: schemachanger: check dependents when dropping hash-sharded index
  pkg/sql/drop_index.go
  pkg/sql/logictest/testdata/logic_test/drop_index
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
Labels: backport

#145384 release-25.1: schemachanger: check dependents when dropping hash-sharded index
  pkg/sql/drop_index.go
  pkg/sql/logictest/testdata/logic_test/drop_index
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
Labels: O-robot, blathers-backport, backport

#145386 release-25.2: schemachanger: check dependents when dropping hash-sharded index
  pkg/sql/drop_index.go
  pkg/sql/logictest/testdata/logic_test/drop_index
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/drop_index.go
Labels: O-robot, blathers-backport, backport

#144544 release-25.2: sql: avoid unnecessary version bumps for UDTs during ALTER TABLE
  pkg/backup/restore_job.go
  pkg/sql/alter_table_locality.go
  pkg/sql/catalog/typedesc/type_desc.go
  pkg/sql/create_table.go
  pkg/sql/drop_type.go
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schema_changer.go
Labels: backport

#145342 release-25.2: sql/explain: show RLS info for empty VALUES plans
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/explain/emit.go
  pkg/sql/opt/exec/explain/testdata/row_level_security
  pkg/sql/opt/exec/factory.go
  pkg/sql/opt/optbuilder/testdata/row_level_security
Labels: O-robot, blathers-backport, backport

#145530 vecindex: add vector search cases to canWrap
  pkg/sql/colexec/colbuilder/execplan.go
  pkg/sql/opt/exec/execbuilder/testdata/not_visible_index
  pkg/sql/opt/exec/execbuilder/testdata/vector_search
Labels: backport-25.2.x

#145561 ui: fix pagination page size selector
  pkg/ui/workspaces/cluster-ui/src/pagination/pagination.tsx
Labels: backport-all

#145374 ttljob: avoid using different versions of enum; use a desc.Collection tied to the correct txn
  pkg/sql/schema_changer_test.go
  pkg/sql/sem/tree/datum.go
  pkg/sql/ttl/ttlbase/BUILD.bazel
  pkg/sql/ttl/ttlbase/ttl_helpers.go
  pkg/sql/ttl/ttlbase/ttl_helpers_test.go
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/testdata/ttljob_plans
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_plans_test.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
  pkg/sql/ttl/ttljob/ttljob_processor_internal_test.go
  pkg/sql/ttl/ttljob/ttljob_query_builder.go
  pkg/sql/ttl/ttljob/ttljob_query_builder_test.go
  pkg/sql/ttl/ttljob/ttljob_test.go
  pkg/sql/ttl/ttlschedule/BUILD.bazel
  pkg/sql/ttl/ttlschedule/ttlschedule.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x

#145575 release-25.1: stats: fix "non-nullable col with no value" for multiple column families
  pkg/sql/create_stats_test.go
  pkg/sql/row/fetcher.go
Labels: O-robot, blathers-backport, backport

#145574 release-24.3: stats: fix "non-nullable col with no value" for multiple column families
  pkg/sql/create_stats_test.go
  pkg/sql/row/fetcher.go
Labels: O-robot, blathers-backport, backport

#145577 release-24.1: stats: fix "non-nullable col with no value" for multiple column families
  pkg/sql/create_stats_test.go
  pkg/sql/row/fetcher.go
Labels: backport

#145581 release-24.1: storage: bump Pebble and add compaction concurrency cluster settings
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cli/interactive_tests/test_encryption.tcl
  pkg/kv/kvserver/stores_server.go
  pkg/storage/engine.go
  pkg/storage/metamorphic/options.go
  pkg/storage/mvcc.go
  pkg/storage/open.go
  pkg/storage/pebble.go
  pkg/storage/pebble_test.go
Labels: backport

#145899 roachtest: start workload after initial scan
  pkg/cmd/roachtest/tests/logical_data_replication.go
Labels: backport-25.2.x

#145895 backup: enforce a minimum compaction window size of 3
  pkg/backup/compaction_job.go
  pkg/backup/compaction_policy.go
  pkg/backup/compaction_test.go
Labels: backport-25.2.x

#145957 admission: improve ioLoadListener logging
  pkg/util/admission/io_load_listener.go
  pkg/util/admission/testdata/format_adjust_tokens_stats.txt
  pkg/util/admission/testdata/io_load_listener
Labels: backport-24.3.x, backport-25.1.x, backport-25.2.x

#145668 release-25.2: storage: bump Pebble and add cluster settings for compaction concurrency
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/kv/kvserver/stores_server.go
  pkg/storage/engine.go
  pkg/storage/metamorphic/options.go
  pkg/storage/mvcc.go
  pkg/storage/open.go
  pkg/storage/pebble.go
  pkg/storage/pebble_test.go
Labels: backport

#145972 catalog/replication: fix validation errors when updating catalog
  pkg/sql/catalog/descs/collection.go
  pkg/sql/catalog/replication/reader_catalog.go
  pkg/sql/catalog/replication/reader_catalog_test.go
Labels: backport-24.3.x, backport-25.1.x, backport-25.2.x

#145983 backfill: fix a panic when backfilling a NULL vector
  pkg/sql/backfill/backfill.go
  pkg/sql/logictest/testdata/logic_test/vector_index
Labels: backport-25.2.x

#146004 release-24.3: admission: account for large flush backlog
  pkg/server/node.go
  pkg/storage/engine.go
  pkg/storage/pebble.go
  pkg/util/admission/granter.go
  pkg/util/admission/io_load_listener.go
  pkg/util/admission/io_load_listener_test.go
  pkg/util/admission/store_token_estimation.go
  pkg/util/admission/store_token_estimation_test.go
  pkg/util/admission/testdata/io_load_listener
  pkg/util/admission/testdata/store_per_work_token_estimator
Labels: backport

#144871 backup: refactor compaction tests to use query constructor
  pkg/backup/compaction_test.go
Labels: backport-25.2.x

#146012 release-24.1: admission: account for large flush backlog
  pkg/server/node.go
  pkg/storage/engine.go
  pkg/storage/pebble.go
  pkg/util/admission/granter.go
  pkg/util/admission/io_load_listener.go
  pkg/util/admission/io_load_listener_test.go
  pkg/util/admission/store_token_estimation.go
  pkg/util/admission/store_token_estimation_test.go
  pkg/util/admission/testdata/io_load_listener
  pkg/util/admission/testdata/store_per_work_token_estimator
Labels: backport

#145986 release-25.2: vecindex: reset result index when Search is repeatedly called
  pkg/sql/logictest/testdata/logic_test/vector_index
  pkg/sql/vecindex/searcher.go
  pkg/sql/vecindex/searcher_test.go
Labels: backport

#146047 admission: improve ioLoadListener logging
  pkg/util/admission/io_load_listener.go
  pkg/util/admission/testdata/format_adjust_tokens_stats.txt
  pkg/util/admission/testdata/io_load_listener
Labels: backport

#146078 release-24.1: released CockroachDB version 24.1.18. Next version: 24.1.19
  pkg/build/version.txt
Labels: backport, backport-test-only

#146077 release-23.2: released CockroachDB version 23.2.25. Next version: 23.2.26
  pkg/build/version.txt
Labels: backport

#146075 release-24.3: released CockroachDB version 24.3.12. Next version: 24.3.13
  pkg/build/version.txt
Labels: backport, backport-test-only

#145551 sql: fix internal failure with temp tables during ALTER operations
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/sql/database.go
  pkg/sql/logictest/testdata/logic_test/temp_table
Labels: backport-all

#145917 release-25.2: ttljob: avoid using different versions of enum; use a desc.Collection tied to the correct txn
  pkg/sql/schema_changer_test.go
  pkg/sql/sem/tree/datum.go
  pkg/sql/ttl/ttlbase/BUILD.bazel
  pkg/sql/ttl/ttlbase/ttl_helpers.go
  pkg/sql/ttl/ttlbase/ttl_helpers_test.go
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/testdata/ttljob_plans
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_plans_test.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
  pkg/sql/ttl/ttljob/ttljob_processor_internal_test.go
  pkg/sql/ttl/ttljob/ttljob_query_builder.go
  pkg/sql/ttl/ttljob/ttljob_query_builder_test.go
  pkg/sql/ttl/ttljob/ttljob_test.go
  pkg/sql/ttl/ttlschedule/BUILD.bazel
  pkg/sql/ttl/ttlschedule/ttlschedule.go
Labels: O-robot, blathers-backport, backport

#146023 release-24.3: admission: improve ioLoadListener logging
  pkg/util/admission/io_load_listener.go
  pkg/util/admission/testdata/format_adjust_tokens_stats.txt
  pkg/util/admission/testdata/io_load_listener
Labels: backport

#145928 roachprod/azure: use premium ssdv2 by default
  pkg/roachprod/vm/azure/azure.go
Labels: backport-all

#145964 release-24.1: ui: fix pagination page size selector
  pkg/ui/workspaces/cluster-ui/package.json
  pkg/ui/workspaces/cluster-ui/src/pagination/pagination.tsx
Labels: O-robot, blathers-backport, backport

#145966 release-25.1: ui: fix pagination page size selector
  pkg/ui/workspaces/cluster-ui/package.json
  pkg/ui/workspaces/cluster-ui/src/pagination/pagination.tsx
Labels: O-robot, blathers-backport, backport

#146143 release-25.2: sql: fix DROP REGION error messages
  pkg/sql/alter_database.go
Labels: O-robot, blathers-backport, backport

#146152 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#146150 release-25.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#146148 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#146147 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#146153 release-25.2: vecindex: bump test size under `race`
  pkg/sql/vecindex/BUILD.bazel
Labels: O-robot, blathers-backport, backport

#146149 release-25.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport, backport-test-only

#146157 util/leaktest: ignore util/goschedstats.init goroutine
  pkg/util/leaktest/leaktest.go
Labels: backport-all

#146169 release-25.1: util/leaktest: ignore util/goschedstats.init goroutine
  pkg/util/leaktest/leaktest.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#146168 release-24.3: util/leaktest: ignore util/goschedstats.init goroutine
  pkg/util/leaktest/leaktest.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#146088 release-25.1: catalog/lease: clean up orphaned session based leases
  pkg/server/server_sql.go
  pkg/sql/catalog/lease/BUILD.bazel
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/distsql/server.go
  pkg/sql/execinfra/server_config.go
  pkg/sql/planner.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/eval/context.go
Labels: backport

#146096 release-24.3: catalog/lease: clean up orphaned session based leases
  pkg/server/server_sql.go
  pkg/sql/catalog/lease/BUILD.bazel
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/distsql/server.go
  pkg/sql/execinfra/server_config.go
  pkg/sql/planner.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/eval/context.go
Labels: backport

#146111 release-24.1: catalog/lease: clean up orphaned session based leases
  pkg/server/server_sql.go
  pkg/sql/catalog/lease/BUILD.bazel
  pkg/sql/catalog/lease/lease.go
  pkg/sql/catalog/lease/lease_test.go
  pkg/sql/distsql/server.go
  pkg/sql/execinfra/server_config.go
  pkg/sql/planner.go
  pkg/sql/sem/builtins/builtins.go
  pkg/sql/sem/builtins/fixed_oids.go
  pkg/sql/sem/eval/context.go
Labels: backport

#146140 release-24.1: sql: fix DROP REGION error messages
  pkg/sql/alter_database.go
Labels: O-robot, blathers-backport, backport

#146170 release-25.2: util/leaktest: ignore util/goschedstats.init goroutine
  pkg/util/leaktest/leaktest.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#146166 release-23.2: util/leaktest: ignore util/goschedstats.init goroutine
  pkg/util/leaktest/leaktest.go
Labels: O-robot, blathers-backport, backport

#146141 release-24.3: sql: fix DROP REGION error messages
  pkg/sql/alter_database.go
Labels: O-robot, blathers-backport, backport

#146142 release-25.1: sql: fix DROP REGION error messages
  pkg/sql/alter_database.go
Labels: O-robot, blathers-backport, backport

#146136 logictest: increase closed ts in buffered_writes further
  pkg/sql/logictest/testdata/logic_test/buffered_writes
Labels: backport-25.2.x

#146212 release-25.2: logictest: increase closed ts in buffered_writes further
  pkg/sql/logictest/testdata/logic_test/buffered_writes
Labels: O-robot, blathers-backport, backport, backport-test-only

#146167 release-24.1: util/leaktest: ignore util/goschedstats.init goroutine
  pkg/util/leaktest/leaktest.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#145371 release-25.1: sql,kv: set the admission control header for leaf transactions
  pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go
  pkg/kv/kvclient/kvcoord/txn_test.go
  pkg/kv/kvclient/kvstreamer/streamer_accounting_test.go
  pkg/kv/kvclient/kvstreamer/streamer_test.go
  pkg/kv/txn.go
  pkg/kv/txn_external_test.go
  pkg/sql/colflow/colbatch_scan_test.go
  pkg/sql/distsql/server.go
  pkg/sql/distsql_running.go
  pkg/sql/exec_util.go
  pkg/sql/execinfrapb/api.proto
  pkg/sql/internal_test.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
  pkg/sql/rowexec/inverted_joiner_test.go
  pkg/sql/rowexec/joinreader_test.go
  pkg/sql/rowexec/tablereader_test.go
  pkg/sql/rowexec/zigzagjoiner_test.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#145915 release-24.3: ttljob: avoid using different versions of enum; use a desc.Collection tied to the correct txn
  pkg/sql/schema_changer_test.go
  pkg/sql/sem/tree/datum.go
  pkg/sql/ttl/ttlbase/BUILD.bazel
  pkg/sql/ttl/ttlbase/ttl_helpers.go
  pkg/sql/ttl/ttlbase/ttl_helpers_test.go
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/testdata/ttljob_plans
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_plans_test.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
  pkg/sql/ttl/ttljob/ttljob_processor_internal_test.go
  pkg/sql/ttl/ttljob/ttljob_query_builder.go
  pkg/sql/ttl/ttljob/ttljob_query_builder_test.go
  pkg/sql/ttl/ttljob/ttljob_test.go
  pkg/sql/ttl/ttlschedule/BUILD.bazel
  pkg/sql/ttl/ttlschedule/ttlschedule.go
Labels: O-robot, blathers-backport, backport

#146018 release-25.2: go.mod: bump Pebble to 29283a7e456f
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#145916 release-25.1: ttljob: avoid using different versions of enum; use a desc.Collection tied to the correct txn
  pkg/sql/schema_changer_test.go
  pkg/sql/sem/tree/datum.go
  pkg/sql/ttl/ttlbase/BUILD.bazel
  pkg/sql/ttl/ttlbase/ttl_helpers.go
  pkg/sql/ttl/ttlbase/ttl_helpers_test.go
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/testdata/ttljob_plans
  pkg/sql/ttl/ttljob/ttljob.go
  pkg/sql/ttl/ttljob/ttljob_plans_test.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
  pkg/sql/ttl/ttljob/ttljob_processor_internal_test.go
  pkg/sql/ttl/ttljob/ttljob_query_builder.go
  pkg/sql/ttl/ttljob/ttljob_query_builder_test.go
  pkg/sql/ttl/ttljob/ttljob_test.go
  pkg/sql/ttl/ttlschedule/BUILD.bazel
  pkg/sql/ttl/ttlschedule/ttlschedule.go
Labels: O-robot, blathers-backport, backport

#146210 release-24.3: sql: validate undesired zone configs for secondary tenants
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_secondary_tenants_abstractions_allowed
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/generated_test.go
  pkg/config/zonepb/BUILD.bazel
  pkg/config/zonepb/zone.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go
  pkg/sql/set_zone_config.go
Labels: backport

#146209 release-25.1: sql: validate undesired zone configs for secondary tenants
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_secondary_tenants_abstractions_allowed
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/BUILD.bazel
  pkg/ccl/logictestccl/tests/multiregion-9node-3region-3azs-tenant/generated_test.go
  pkg/config/zonepb/BUILD.bazel
  pkg/config/zonepb/zone.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/named_range_zone_config.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go
  pkg/sql/set_zone_config.go
Labels: backport

#145582 release-24.3: storage: bump Pebble and add compaction concurrency cluster settings
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cli/interactive_tests/test_encryption.tcl
  pkg/kv/kvserver/stores_server.go
  pkg/storage/engine.go
  pkg/storage/metamorphic/options.go
  pkg/storage/mvcc.go
  pkg/storage/open.go
  pkg/storage/pebble.go
  pkg/storage/pebble_test.go
Labels: backport

#145583 release-25.1: storage: bump Pebble and add compaction concurrency cluster settings
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
  pkg/cli/interactive_tests/test_encryption.tcl
  pkg/kv/kvserver/stores_server.go
  pkg/storage/engine.go
  pkg/storage/metamorphic/options.go
  pkg/storage/mvcc.go
  pkg/storage/open.go
  pkg/storage/pebble.go
  pkg/storage/pebble_test.go
Labels: backport

#146200 release-23.2: sql: fix internal failure with temp tables during ALTER operations
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/sql/database.go
  pkg/sql/logictest/testdata/logic_test/temp_table
Labels: backport

#146199 release-24.1: sql: fix internal failure with temp tables during ALTER operations
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/sql/database.go
  pkg/sql/logictest/testdata/logic_test/temp_table
Labels: backport

#146128 release-25.2: sql/rls: apply SELECT policies for UPDATE only if columns are referenced
  pkg/sql/logictest/testdata/logic_test/row_level_security
  pkg/sql/opt/exec/explain/testdata/row_level_security
  pkg/sql/opt/optbuilder/fk_cascade.go
  pkg/sql/opt/optbuilder/insert.go
  pkg/sql/opt/optbuilder/limit.go
  pkg/sql/opt/optbuilder/mutation_builder.go
  pkg/sql/opt/optbuilder/select.go
  pkg/sql/opt/optbuilder/testdata/row_level_security
  pkg/sql/opt/optbuilder/update.go
  pkg/sql/opt/optbuilder/util.go
Labels: O-robot, blathers-backport, backport

#146194 release-25.1: roachtest: fix tenant auto upgrade scheduling user hooks during setup
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
Labels: backport, backport-test-only

#146195 release-24.3: roachtest: fix tenant auto upgrade scheduling user hooks during setup
  pkg/cmd/roachtest/roachtestutil/mixedversion/planner.go
Labels: backport, backport-test-only

#146282 release-25.2.0-rc: logical: set origin id in tombstone updater
  pkg/crosscluster/logical/BUILD.bazel
  pkg/crosscluster/logical/tombstone_updater.go
  pkg/crosscluster/logical/tombstone_updater_test.go
Labels: backport

#146281 release-25.2.0-rc: revert "kv: use origin timestamp to validate lww semantics"
  pkg/crosscluster/logical/logical_replication_job_test.go
  pkg/crosscluster/logical/logical_replication_writer_processor.go
  pkg/crosscluster/logical/lww_row_processor_test.go
  pkg/crosscluster/logical/table_batch_handler_test.go
  pkg/kv/BUILD.bazel
  pkg/kv/kv_client_lww_test.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvserver/batcheval/cmd_conditional_put.go
  pkg/storage/mvcc.go
  pkg/storage/mvcc_history_test.go
  pkg/storage/mvcc_test.go
  pkg/storage/testdata/mvcc_histories/delete_range_with_origin_timestamps
  pkg/storage/testdata/mvcc_histories/delete_with_origin_timestamp
  pkg/storage/testdata/mvcc_histories/put_with_origin_timestamp
Labels: backport

#145243 release-24.3: exec/explain: bump test timeout to 5 minutes
  pkg/sql/opt/exec/explain/BUILD.bazel
Labels: O-robot, blathers-backport, backport

#146279 release-25.2: revert "kv: use origin timestamp to validate lww semantics"
  pkg/crosscluster/logical/logical_replication_job_test.go
  pkg/crosscluster/logical/logical_replication_writer_processor.go
  pkg/crosscluster/logical/lww_row_processor_test.go
  pkg/crosscluster/logical/table_batch_handler_test.go
  pkg/kv/BUILD.bazel
  pkg/kv/kv_client_lww_test.go
  pkg/kv/kvpb/api.proto
  pkg/kv/kvserver/batcheval/cmd_conditional_put.go
  pkg/storage/mvcc.go
  pkg/storage/mvcc_history_test.go
  pkg/storage/mvcc_test.go
  pkg/storage/testdata/mvcc_histories/delete_range_with_origin_timestamps
  pkg/storage/testdata/mvcc_histories/delete_with_origin_timestamp
  pkg/storage/testdata/mvcc_histories/put_with_origin_timestamp
Labels: backport

#146249 release-25.2: changefeedccl: disable unsafe sql updates in nemeses test
  pkg/ccl/changefeedccl/cdctest/nemeses.go
  pkg/internal/sqlsmith/sqlsmith.go
Labels: O-robot, blathers-backport, backport

#146222 release-24.3: sql,kv: set the admission control header for leaf transactions
  pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go
  pkg/kv/kvclient/kvcoord/txn_test.go
  pkg/kv/kvclient/kvstreamer/streamer_accounting_test.go
  pkg/kv/kvclient/kvstreamer/streamer_test.go
  pkg/kv/txn.go
  pkg/kv/txn_external_test.go
  pkg/sql/colflow/colbatch_scan_test.go
  pkg/sql/distsql/server.go
  pkg/sql/distsql_running.go
  pkg/sql/exec_util.go
  pkg/sql/execinfrapb/api.proto
  pkg/sql/internal_test.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
  pkg/sql/rowexec/inverted_joiner_test.go
  pkg/sql/rowexec/joinreader_test.go
  pkg/sql/rowexec/tablereader_test.go
  pkg/sql/rowexec/zigzagjoiner_test.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#146308 release-25.1: colenc: harden TestEncoderEqualityRand
  pkg/sql/colenc/encode_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#146307 release-24.3: colenc: harden TestEncoderEqualityRand
  pkg/sql/colenc/encode_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#146306 release-24.1: colenc: harden TestEncoderEqualityRand
  pkg/sql/colenc/encode_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#146304 release-23.2: colenc: harden TestEncoderEqualityRand
  pkg/sql/colenc/encode_test.go
Labels: O-robot, blathers-backport, backport

#146164 release-25.2: explain: deflake TestMaximumMemoryUsage for good
  pkg/sql/opt/exec/explain/BUILD.bazel
  pkg/sql/opt/exec/explain/output_test.go
Labels: O-robot, blathers-backport, backport

#146163 release-25.1: explain: deflake TestMaximumMemoryUsage for good
  pkg/sql/opt/exec/explain/BUILD.bazel
  pkg/sql/opt/exec/explain/output_test.go
Labels: O-robot, blathers-backport, backport

#146162 release-24.3: explain: deflake TestMaximumMemoryUsage for good
  pkg/sql/opt/exec/explain/BUILD.bazel
  pkg/sql/opt/exec/explain/output_test.go
Labels: O-robot, blathers-backport, backport

#146309 release-25.2: colenc: harden TestEncoderEqualityRand
  pkg/sql/colenc/encode_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#146310 release-24.1: sql,kv: set the admission control header for leaf transactions
  pkg/kv/kvclient/kvcoord/txn_coord_sender_test.go
  pkg/kv/kvclient/kvcoord/txn_test.go
  pkg/kv/kvclient/kvstreamer/streamer_accounting_test.go
  pkg/kv/kvclient/kvstreamer/streamer_test.go
  pkg/kv/txn.go
  pkg/kv/txn_external_test.go
  pkg/sql/colflow/colbatch_scan_test.go
  pkg/sql/distsql/server.go
  pkg/sql/distsql_running.go
  pkg/sql/exec_util.go
  pkg/sql/execinfrapb/api.proto
  pkg/sql/internal_test.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/exec/execbuilder/testdata/lookup_join
  pkg/sql/rowexec/inverted_joiner_test.go
  pkg/sql/rowexec/joinreader_test.go
  pkg/sql/rowexec/tablereader_test.go
  pkg/sql/rowexec/zigzagjoiner_test.go
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#146340 release-24.1: go.mod: bump Pebble to f53339d17908
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#146341 kvcoord: fix QueryLocks and LeaseInfo handling in txnWriteBuffer
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
Labels: backport-25.2.x

#146339 release-24.3: go.mod: bump Pebble to 01a1caeef0a9
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#146338 release-25.1: go.mod: bump Pebble to b7f6decc7d52
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#146337 release-25.2: go.mod: bump Pebble to 2384a65cedf4
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#146342 release-25.2: kvcoord: fix QueryLocks and LeaseInfo handling in txnWriteBuffer
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer.go
  pkg/kv/kvclient/kvcoord/txn_interceptor_write_buffer_test.go
Labels: O-robot, blathers-backport, backport

#146276 release-24.1: kvcoord: add debugging for TestDistSenderReplicaStall
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker_test.go
Labels: O-robot, blathers-backport, backport

#146277 release-24.3: kvcoord: add debugging for TestDistSenderReplicaStall
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker_test.go
Labels: O-robot, blathers-backport, backport

#146278 release-25.1: kvcoord: add debugging for TestDistSenderReplicaStall
  pkg/kv/kvclient/kvcoord/BUILD.bazel
  pkg/kv/kvclient/kvcoord/dist_sender_circuit_breaker_test.go
Labels: O-robot, blathers-backport, backport

#146247 kvserver: deflake TestLossQuorumCauseLeaderlessWatcherToSignalUnavailable
  pkg/kv/kvserver/client_replica_test.go
Labels: backport-25.2.x

#146312 release-25.2: changefeedccl: add timeout to nemeses test inserts
  pkg/ccl/changefeedccl/cdctest/nemeses.go
Labels: O-robot, blathers-backport, backport

#146377 release-24.3: build: remove ssh key on exit only on TeamCity agents
  build/teamcity-support.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#146375 release-23.2: build: remove ssh key on exit only on TeamCity agents
  build/teamcity-support.sh
Labels: O-robot, blathers-backport, backport

#146378 release-25.1: build: remove ssh key on exit only on TeamCity agents
  build/teamcity-support.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#146295 release-25.2: ui: always show network page for virtual clusters
  pkg/server/tenant.go
Labels: O-robot, blathers-backport, backport

#146374 storage/disk: improve logging of device IDs
  pkg/server/config.go
  pkg/storage/disk/BUILD.bazel
  pkg/storage/disk/linux_parse.go
  pkg/storage/disk/linux_parse_test.go
  pkg/storage/disk/monitor.go
  pkg/storage/disk/monitor_test.go
  pkg/storage/disk/monitor_tracer.go
  pkg/storage/disk/platform_darwin.go
  pkg/storage/disk/platform_default.go
  pkg/storage/disk/platform_linux.go
Labels: backport-24.3.x, backport-25.1.x, backport-25.2.x

#146270 kvserver: remove UnregisterFromReplica callback
  pkg/kv/kvserver/rangefeed/processor.go
  pkg/kv/kvserver/rangefeed/scheduled_processor.go
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_rangefeed.go
Labels: backport-25.1.x, backport-25.2.x, backport-25.1.6-rc, backport-25.2.0-rc

#146391 release-25.2: smith/main: add new mutations configuration to smither options
  pkg/cmd/smith/main.go
Labels: O-robot, blathers-backport, backport

#146322 release-23.2: sql: maintain index dependencies during truncate
  pkg/sql/logictest/testdata/logic_test/truncate
  pkg/sql/truncate.go
Labels: O-robot, blathers-backport, backport

#146323 release-24.1: sql: maintain index dependencies during truncate
  pkg/sql/logictest/testdata/logic_test/truncate
  pkg/sql/truncate.go
Labels: O-robot, blathers-backport, backport

#146324 release-24.3: sql: maintain index dependencies during truncate
  pkg/sql/logictest/testdata/logic_test/truncate
  pkg/sql/truncate.go
Labels: O-robot, blathers-backport, backport

#146326 release-25.2: sql: maintain index dependencies during truncate
  pkg/sql/logictest/testdata/logic_test/truncate
  pkg/sql/truncate.go
Labels: O-robot, blathers-backport, backport

#146213 catalog: gracefully handle invalid entries in system.comments
  pkg/sql/catalog/catalogkeys/keys.go
  pkg/sql/catalog/descs/collection.go
  pkg/sql/catalog/internal/catkv/catalog_query.go
  pkg/sql/catalog/nstree/catalog_mutable.go
  pkg/sql/crdb_internal.go
  pkg/sql/logictest/testdata/logic_test/comment_on
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x

#146392 build: set version to v25.2.0
  pkg/build/version.txt
Labels: backport, backport-test-only

#146413 release-25.2: sql: prevent overflow of field position in split_part
  pkg/sql/logictest/testdata/logic_test/builtin_function
  pkg/sql/sem/builtins/builtins.go
Labels: O-robot, blathers-backport, backport

#146325 release-25.1: sql: maintain index dependencies during truncate
  pkg/sql/logictest/testdata/logic_test/truncate
  pkg/sql/truncate.go
Labels: O-robot, blathers-backport, backport

#146362 sql/distsql: preserve JobID in redacted logs
  pkg/sql/distsql/server.go
  pkg/sql/distsql_running.go
  pkg/sql/execinfrapb/api.proto
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x

#144982 roachprod: remove Side-Eye integration
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  build/teamcity/cockroach/nightlies/perturbation_nightly_metamorphic_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_gce_force_profile.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_azure.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_fips.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_gce_perturbation.sh
  build/teamcity/cockroach/nightlies/roachtest_nightly_impl.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_aws.sh
  build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh
  go.mod
  go.sum
  pkg/BUILD.bazel
  pkg/cmd/bazci/githubpost/issues/formatter_unit.go
  pkg/cmd/bazci/githubpost/issues/issues.go
  pkg/cmd/roachprod/cli/commands.go
  pkg/cmd/roachprod/cli/resgistry.go
  pkg/cmd/roachtest/BUILD.bazel
  pkg/cmd/roachtest/cluster.go
  pkg/cmd/roachtest/cluster/cluster_interface.go
  pkg/cmd/roachtest/clusterstats/mock_cluster_generated_test.go
  pkg/cmd/roachtest/github.go
  pkg/cmd/roachtest/github_test.go
  pkg/cmd/roachtest/roachtestflags/flags.go
  pkg/cmd/roachtest/run.go
  pkg/cmd/roachtest/test_runner.go
  pkg/cmd/roachtest/testdata/github/arbitrary_transient_failure
  pkg/cmd/roachtest/testdata/github/basic_test_create_post_request
  pkg/cmd/roachtest/testdata/github/cluster_provisioning_error
  pkg/cmd/roachtest/testdata/github/coverage-enabled-build
  pkg/cmd/roachtest/testdata/github/dns_flake_and_error_with_ownership
  pkg/cmd/roachtest/testdata/github/dns_flake_error
  pkg/cmd/roachtest/testdata/github/extra_labels
  pkg/cmd/roachtest/testdata/github/extra_parameters
  pkg/cmd/roachtest/testdata/github/live_migration_error
  pkg/cmd/roachtest/testdata/github/lost_error_object_and_transient_error
  pkg/cmd/roachtest/testdata/github/nested_errors_with_ownership
  pkg/cmd/roachtest/testdata/github/nested_transient_failures
  pkg/cmd/roachtest/testdata/github/non_release_blocker_create_post_request
  pkg/cmd/roachtest/testdata/github/require_no_error_transient_error
  pkg/cmd/roachtest/testdata/github/runtime_assertions_build
  pkg/cmd/roachtest/testdata/github/ssh_flake_error
  pkg/cmd/roachtest/testdata/github/vm_host_error
  pkg/cmd/roachtest/testdata/github/vm_host_error_and_other_error
  pkg/cmd/roachtest/testdata/github/vm_preemption_and_other_error
  pkg/cmd/roachtest/testdata/github/vm_preemption_flake
  pkg/cmd/roachtest/tests/online_restore.go
  pkg/roachprod/BUILD.bazel
  pkg/roachprod/install/install.go
  pkg/roachprod/roachprod.go
  pkg/testutils/lint/lint_test.go
  pkg/testutils/sideeye/BUILD.bazel
  pkg/testutils/sideeye/sideeye.go
  scripts/drtprod
Labels: O-community, backport-24.3.x, backport-25.1.x, backport-25.2.x

#146398 release-25.2: sql: Fix flaky TestInternalAppNamePrefix
  pkg/sql/conn_executor_test.go
Labels: backport, backport-test-only

#146447 release-24.1: roachtest: deflake declarative_schema_changer/job-compatibility-mixed-version
  pkg/cmd/roachtest/tests/mixed_version_job_compatibility_in_declarative_schema_changer.go
Labels: backport, backport-test-only

#144412 changefeedccl: add job tracing support to changefeeds
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/batching_sink.go
  pkg/ccl/changefeedccl/changefeed_dist.go
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/event_processing.go
Labels: backport-all

#146434 release-25.2: sql/distsql: preserve JobID in redacted logs
  pkg/sql/distsql/server.go
  pkg/sql/distsql_running.go
  pkg/sql/execinfrapb/api.proto
Labels: O-robot, blathers-backport, backport

#146433 release-25.1: sql/distsql: preserve JobID in redacted logs
  pkg/sql/distsql/server.go
  pkg/sql/distsql_running.go
  pkg/sql/execinfrapb/api.proto
Labels: O-robot, blathers-backport, backport

#146379 release-25.2: build: remove ssh key on exit only on TeamCity agents
  build/teamcity-support.sh
Labels: O-robot, blathers-backport, backport, backport-test-only

#146477 release-24.3: crosscluster/physical: add verbose logging to reader standby job
  pkg/ccl/crosscluster/physical/standby_read_ts_poller_job.go
Labels: backport

#146406 plpgsql: prevent a crash in an edge case during formatting
  pkg/sql/conn_executor_exec.go
  pkg/sql/logictest/testdata/logic_test/do
  pkg/sql/parser/testdata/do
  pkg/sql/plpgsql/parser/lexer.go
  pkg/sql/plpgsql/parser/plpgsql.y
  pkg/sql/sem/plpgsqltree/statements.go
  pkg/sql/sem/tree/BUILD.bazel
  pkg/sql/sem/tree/create_routine.go
  pkg/sql/sem/tree/format.go
Labels: backport-25.1.x, backport-25.2.x

#146363 release-24.1: kvserver: skip TestLeaseQueueShedsOnIOOverload under duress
  pkg/kv/kvserver/lease_queue_test.go
Labels: backport, backport-test-only

#146361 release-24.3: kvserver: skip TestLeaseQueueShedsOnIOOverload under duress
  pkg/kv/kvserver/lease_queue_test.go
Labels: backport, backport-test-only

#146131 kvserver: Reduce replica mutex contention Phase 2
  pkg/kv/kvserver/client_replica_test.go
  pkg/kv/kvserver/helpers_test.go
  pkg/kv/kvserver/kvserverpb/state.proto
  pkg/kv/kvserver/lease_queue_test.go
  pkg/kv/kvserver/replica.go
  pkg/kv/kvserver/replica_circuit_breaker.go
  pkg/kv/kvserver/replica_closedts.go
  pkg/kv/kvserver/replica_closedts_internal_test.go
  pkg/kv/kvserver/replica_closedts_test.go
  pkg/kv/kvserver/replica_follower_read.go
  pkg/kv/kvserver/replica_follower_read_test.go
  pkg/kv/kvserver/replica_proposal.go
  pkg/kv/kvserver/replica_proposal_buf.go
  pkg/kv/kvserver/replica_protected_timestamp_test.go
  pkg/kv/kvserver/replica_raft.go
  pkg/kv/kvserver/replica_range_lease.go
  pkg/kv/kvserver/replica_store_liveness.go
  pkg/kv/kvserver/replica_store_liveness_test.go
  pkg/kv/kvserver/store.go
  pkg/server/node.go
  pkg/sql/catalog/lease/storage.go
Labels: o-perf-efficiency

#146482 opt: stabilize end-to-end benchmarks
  pkg/sql/opt/bench/bench_test.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x

#146486 release-25.2: go.mod: bump Pebble to 695bfa83317c
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#146565 release-25.1: released CockroachDB version 25.1.6. Next version: 25.1.7
  pkg/build/version.txt
Labels: backport, backport-test-only

#146510 release-25.2: opt: add rule to pull filters out of EXISTS condition
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/testdata/stats/project
  pkg/sql/opt/norm/decorrelate_funcs.go
  pkg/sql/opt/norm/general_funcs.go
  pkg/sql/opt/norm/rules/decorrelate.opt
  pkg/sql/opt/norm/testdata/rules/decorrelate
  pkg/sql/opt/norm/testdata/rules/join
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#146467 release-24.3: sql/distsql: preserve JobID in redacted logs
  pkg/sql/distsql/server.go
  pkg/sql/distsql_running.go
  pkg/sql/execinfrapb/api.proto
Labels: backport

#146469 release-24.1: sql/distsql: preserve JobID in redacted logs
  pkg/sql/distsql/server.go
  pkg/sql/distsql_running.go
  pkg/sql/execinfrapb/api.proto
Labels: backport

#146458 docgen: expose WITH/WITHOUT HOLD syntax in SQL cursor diagram
  docs/generated/sql/bnf/declare_cursor_stmt.bnf
  pkg/cmd/docgen/diagrams.go
Labels: backport-25.2.x

#146573 release-25.2: distsql: cancel remote flows on quiesce
  pkg/sql/distsql/server.go
Labels: O-robot, blathers-backport, backport

#146501 release-25.2: plpgsql: prevent a crash in an edge case during formatting
  pkg/sql/conn_executor_exec.go
  pkg/sql/logictest/testdata/logic_test/do
  pkg/sql/parser/testdata/do
  pkg/sql/plpgsql/parser/lexer.go
  pkg/sql/plpgsql/parser/plpgsql.y
  pkg/sql/sem/plpgsqltree/statements.go
  pkg/sql/sem/tree/create_routine.go
  pkg/sql/sem/tree/format.go
Labels: O-robot, blathers-backport, backport

#146574 release-25.1: distsql: cancel remote flows on quiesce
  pkg/sql/distsql/server.go
Labels: O-robot, blathers-backport, backport

#146446 sql/sem: reject AS OF timestamps set in the future
  pkg/ccl/changefeedccl/changefeed_stmt.go
  pkg/ccl/changefeedccl/changefeed_test.go
  pkg/sql/as_of_test.go
  pkg/sql/logictest/testdata/logic_test/as_of
  pkg/sql/pgwire/testdata/pgtest/bind_and_resolve
  pkg/sql/sem/asof/as_of.go
Labels: backport-25.2.x

#146509 release-25.1: plpgsql: prevent a crash in an edge case during formatting
  pkg/sql/conn_executor_exec.go
  pkg/sql/logictest/testdata/logic_test/do
  pkg/sql/parser/testdata/do
  pkg/sql/plpgsql/parser/lexer.go
  pkg/sql/plpgsql/parser/plpgsql.y
  pkg/sql/sem/plpgsqltree/statements.go
  pkg/sql/sem/tree/create_routine.go
  pkg/sql/sem/tree/format.go
Labels: backport

#146522 security: add sql client error for TLSCipherRestrict
  pkg/security/BUILD.bazel
  pkg/security/tls_ciphersuites.go
  pkg/security/tls_test.go
  pkg/sql/pgwire/pre_serve.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-25.2.x

#146567 sql/schemchanger: skip ghost secondary indexes during alter pk
  pkg/sql/logictest/testdata/logic_test/alter_table
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_primary_key.go
Labels: backport-25.2.x

#145900 release-25.2: roachtest/tlp: randomly force generic query plans
  pkg/cmd/roachtest/tests/tlp.go
Labels: backport, backport-test-only

#146592 release-25.1: opt: add rule to pull filters out of EXISTS condition
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/testdata/stats/project
  pkg/sql/opt/norm/decorrelate_funcs.go
  pkg/sql/opt/norm/general_funcs.go
  pkg/sql/opt/norm/rules/decorrelate.opt
  pkg/sql/opt/norm/testdata/rules/decorrelate
  pkg/sql/opt/norm/testdata/rules/join
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#146595 release-24.3: opt: add rule to pull filters out of EXISTS condition
  pkg/sql/exec_util.go
  pkg/sql/logictest/testdata/logic_test/information_schema
  pkg/sql/logictest/testdata/logic_test/pg_catalog
  pkg/sql/logictest/testdata/logic_test/show_source
  pkg/sql/opt/memo/memo.go
  pkg/sql/opt/memo/memo_test.go
  pkg/sql/opt/memo/testdata/stats/project
  pkg/sql/opt/norm/decorrelate_funcs.go
  pkg/sql/opt/norm/general_funcs.go
  pkg/sql/opt/norm/rules/decorrelate.opt
  pkg/sql/opt/norm/testdata/rules/decorrelate
  pkg/sql/opt/norm/testdata/rules/join
  pkg/sql/sessiondatapb/local_only_session_data.proto
  pkg/sql/vars.go
Labels: backport

#146602 release-24.3.14-rc: released CockroachDB version 24.3.13. Next version: 24.3.14
  pkg/build/version.txt
Labels: backport, backport-test-only

#146601 release-24.3: released CockroachDB version 24.3.14. Next version: 24.3.15
  pkg/build/version.txt
Labels: backport, backport-test-only

#146672 release-25.1: logictestccl: wait for tenant overrides to propagate in multi_region_secondary_tenants_abstractions_allowed
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_secondary_tenants_abstractions_allowed
Labels: O-robot, blathers-backport, backport, backport-test-only

#146237 release-25.2: ttljob: add cluster setting to control concurrency
  pkg/sql/ttl/ttlbase/ttl_helpers.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
Labels: O-robot, blathers-backport, backport

#146236 release-25.1: ttljob: add cluster setting to control concurrency
  pkg/sql/ttl/ttlbase/ttl_helpers.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
Labels: O-robot, blathers-backport, backport

#146234 release-24.1: ttljob: add cluster setting to control concurrency
  pkg/sql/ttl/ttlbase/ttl_helpers.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
Labels: O-robot, blathers-backport, backport

#146233 release-23.2: ttljob: add cluster setting to control concurrency
  pkg/sql/ttl/ttlbase/ttl_helpers.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
Labels: O-robot, blathers-backport, backport

#146674 release-24.1: parser: fix format/parse roundtrip for unique index
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/create_table
  pkg/sql/sem/tree/create.go
  pkg/sql/sem/tree/pretty.go
  pkg/testutils/sqlutils/parse.go
  pkg/testutils/sqlutils/pretty.go
Labels: backport

#146673 release-24.3: parser: fix format/parse roundtrip for unique index
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/create_table
  pkg/sql/sem/tree/create.go
  pkg/sql/sem/tree/pretty.go
  pkg/testutils/sqlutils/parse.go
  pkg/testutils/sqlutils/pretty.go
Labels: backport
