Repository cockroachdb/cockroach, pull requests merged in 2025-03, with the labels that each got.

#142151 stmtbundle: refactor FK handling in schema.sql
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/acceptance/generated_cli_test.go
  pkg/cli/interactive_tests/test_sb_recreate_fks.tcl
  pkg/sql/delegate/show_table.go
  pkg/sql/exec_factory_util.go
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
  pkg/sql/logictest/testdata/logic_test/show_create
  pkg/sql/opt/BUILD.bazel
  pkg/sql/opt/cat/table.go
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/scalar.go
  pkg/sql/opt/exec/execbuilder/testdata/explain_env
  pkg/sql/opt/exec/factory.go
  pkg/sql/opt/metadata.go
  pkg/sql/opt/util.go
  pkg/sql/opt_exec_factory.go
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/show
  pkg/sql/plan.go
  pkg/sql/sem/tree/show.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-24.3.7-rc

#142193 release-23.2: settings: increase number of cores test can use
  pkg/settings/integration_tests/BUILD.bazel
Labels: backport

#141157 release-23.2: changefeedccl: migrate pts records to include new tables
  pkg/ccl/changefeedccl/BUILD.bazel
  pkg/ccl/changefeedccl/changefeed_processors.go
  pkg/ccl/changefeedccl/protected_timestamps_test.go
  pkg/ccl/changefeedccl/testing_knobs.go
Labels: backport

#141863 release-24.1: sqlstats: clarify latency percentile limitations
  pkg/sql/appstatspb/app_stats.go
  pkg/ui/workspaces/cluster-ui/src/statsTableUtil/statsTableUtil.tsx
Labels: backport

#141987 release-24.3: sql: Ensure we auto commit for first DDL in txn
  pkg/cmd/roachtest/tests/asyncpg_blocklist.go
  pkg/cmd/roachtest/tests/knex.go
  pkg/cmd/roachtest/tests/libpq_blocklist.go
  pkg/cmd/roachtest/tests/pgx_blocklist.go
  pkg/cmd/roachtest/tests/psycopg_blocklist.go
  pkg/sql/conn_executor_ddl.go
  pkg/sql/conn_executor_prepare.go
  pkg/sql/logictest/testdata/logic_test/schema_change_in_txn
  pkg/sql/pgwire/testdata/pgtest/schema_changes_implicit_txn
  pkg/sql/pgwire/testdata/pgtest/schema_changes_implicit_txn_with_bind
Labels: backport

#142155 release-25.1: sql: add metric for statement timeouts
  docs/generated/metrics/metrics.html
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_util.go
  pkg/sql/executor_statement_metrics.go
  pkg/sql/metric_test.go
Labels: backport

#142157 release-24.1: sql: add metric for statement timeouts
  docs/generated/metrics/metrics.html
  pkg/sql/conn_executor.go
  pkg/sql/conn_executor_exec.go
  pkg/sql/exec_util.go
  pkg/sql/executor_statement_metrics.go
  pkg/sql/metric_test.go
Labels: backport

#142150 raft: single voter campaigns without store liveness support
  pkg/kv/kvserver/client_raft_test.go
  pkg/raft/testdata/campaign_single_voter.txt
  pkg/raft/tracker/fortificationtracker.go
Labels: backport-25.1.x

#142149 roachtest: disable metamorphic perturbation tests
  pkg/cmd/roachtest/tests/perturbation/framework.go
Labels: backport-25.1.x

#142246 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#142243 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#142242 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#142238 roachtest: ramp workloads in cluster to cluster tests
  pkg/cmd/roachtest/tests/cluster_to_cluster.go
Labels: backport-25.1.x

#142274 toolchain: sign MacOS Go binaries on Linux
  build/teamcity/internal/release/sign-patched-go.sh
Labels: C-enhancement, A-build-system, T-dev-inf

#141834 tests: add warm-up to BenchmarkSysbench
  pkg/sql/tests/sysbench_test.go
Labels: T-microbench-post

#142209 logictestccl: deflake as_of
  pkg/ccl/logictestccl/testdata/logic_test/as_of
Labels: backport-25.1.x

#142202 sql: fix check to determine if declarative schema changer can be used
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/ccl/multiregionccl/region_test.go
  pkg/ccl/spanconfigccl/spanconfigreconcilerccl/datadriven_test.go
  pkg/sql/logictest/testdata/logic_test/show_create
  pkg/sql/opt/exec/execbuilder/testdata/show_trace
  pkg/sql/pgwire/testdata/pgtest/schema_changes_implicit_txn
  pkg/sql/schema_change_plan_node.go
  pkg/sql/schema_changer_test.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
  pkg/sql/schemachanger/schemachanger_test.go
  pkg/sql/testdata/telemetry/index
  pkg/sql/tests/autocommit_extended_protocol_test.go
Labels: backport-24.3.x, backport-25.1.x

#142284 upgrades: don't crash if a job is missing from vtable
  pkg/upgrade/upgrades/v25_1_add_jobs_tables.go
Labels: backport-25.1.x, backport-25.1.1-rc

#142301 upgrademanager: skip TestPrecondition under race
  pkg/upgrade/upgrademanager/manager_external_test.go
Labels: C-bug, A-testing, T-testeng

#141953 sql/ttl: add retry logic for TTL deletions
  docs/generated/metrics/metrics.html
  pkg/sql/ttl/ttljob/BUILD.bazel
  pkg/sql/ttl/ttljob/ttljob_metrics.go
  pkg/sql/ttl/ttljob/ttljob_plans_test.go
  pkg/sql/ttl/ttljob/ttljob_processor.go
  pkg/sql/ttl/ttljob/ttljob_processor_internal_test.go
  pkg/sql/ttl/ttljob/ttljob_query_builder.go
  pkg/util/retry/BUILD.bazel
  pkg/util/retry/batch.go
  pkg/util/retry/batch_test.go
Labels: backport-24.3.x, backport-25.1.x

#142334 upgrades: mark missing job error as permanent
  pkg/upgrade/upgrades/v25_1_add_jobs_tables.go
Labels: backport-25.1.x, backport-25.1.1-rc

#142355 rttanalysis: deflake alter_populated_database_alter_primary_region
  pkg/ccl/benchccl/rttanalysisccl/testdata/benchmark_expectations
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#142341 release-25.1: upgrades: remove redundant `ensureSQLSchemaTelemetrySchedule` permanent upgrade
  pkg/upgrade/upgrades/BUILD.bazel
  pkg/upgrade/upgrades/permanent_ensure_sql_schema_telemetry_schedule.go
  pkg/upgrade/upgrades/permanent_ensure_sql_schema_telemetry_schedule_test.go
  pkg/upgrade/upgrades/permanent_upgrades.go
Labels: backport

#142342 release-24.1: upgrades: remove redundant `ensureSQLSchemaTelemetrySchedule` permanent upgrade
  pkg/upgrade/upgrades/BUILD.bazel
  pkg/upgrade/upgrades/permanent_ensure_sql_schema_telemetry_schedule.go
  pkg/upgrade/upgrades/permanent_ensure_sql_schema_telemetry_schedule_test.go
  pkg/upgrade/upgrades/permanent_upgrades.go
Labels: backport

#142344 release-24.3: upgrades: remove redundant `ensureSQLSchemaTelemetrySchedule` permanent upgrade
  pkg/upgrade/upgrades/BUILD.bazel
  pkg/upgrade/upgrades/permanent_ensure_sql_schema_telemetry_schedule.go
  pkg/upgrade/upgrades/permanent_ensure_sql_schema_telemetry_schedule_test.go
  pkg/upgrade/upgrades/permanent_upgrades.go
Labels: backport

#142359 release-25.1: external catalog: support rewriting table names in IngestExternalCatalog
  pkg/crosscluster/logical/create_logical_replication_stmt.go
  pkg/crosscluster/logical/logical_replication_job_test.go
  pkg/sql/catalog/externalcatalog/external_catalog.go
  pkg/sql/catalog/externalcatalog/external_catalog_test.go
Labels: backport

#142302 release-25.1: sql: fix check to determine if declarative schema changer can be used
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/ccl/multiregionccl/region_test.go
  pkg/ccl/spanconfigccl/spanconfigreconcilerccl/datadriven_test.go
  pkg/sql/logictest/testdata/logic_test/show_create
  pkg/sql/opt/exec/execbuilder/testdata/show_trace
  pkg/sql/pgwire/testdata/pgtest/schema_changes_implicit_txn
  pkg/sql/schema_change_plan_node.go
  pkg/sql/schema_changer_test.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
  pkg/sql/schemachanger/schemachanger_test.go
  pkg/sql/testdata/telemetry/index
  pkg/sql/tests/autocommit_extended_protocol_test.go
Labels: backport

#140627 release-24.3: go.mod: bump Pebble to a59316b7e59f
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#142434 cloud/amazon/s3: Add caching to STS credentials
  pkg/cloud/amazon/s3_storage.go
Labels: C-bug, S-2-temp-unavailability, backport-24.3.x, backport-25.1.x, 24.3

#142360 release-25.1: kvserver/rangefeed: lift CrdbTestBuild on RangefeedUseBufferedSender
  pkg/kv/kvserver/BUILD.bazel
  pkg/kv/kvserver/replica_rangefeed.go
Labels: backport

#142441 roachtest: update sqlalchemy ignorelist with new tests
  pkg/cmd/roachtest/tests/sqlalchemy_blocklist.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.3.x, backport-25.1.x

#142303 release-24.3: sql: fix check to determine if declarative schema changer can be used
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/ccl/multiregionccl/region_test.go
  pkg/ccl/spanconfigccl/spanconfigreconcilerccl/datadriven_test.go
  pkg/sql/logictest/testdata/logic_test/show_create
  pkg/sql/opt/exec/execbuilder/testdata/show_trace
  pkg/sql/pgwire/testdata/pgtest/schema_changes_implicit_txn
  pkg/sql/schema_change_plan_node.go
  pkg/sql/schema_changer_test.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/create_index.go
  pkg/sql/schemachanger/schemachanger_test.go
  pkg/sql/testdata/telemetry/index
Labels: backport

#142289 roachtest: lower foreground throughput on AC disk bandwidth test
  pkg/cmd/roachtest/tests/admission_control_disk_bandwidth_overload.go
Labels: backport-25.1.x

#142240 ui: improve network latency page performance
  pkg/ui/workspaces/db-console/src/views/reports/containers/network/latency/index.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/network/latency/latency.styl
Labels: backport-25.1.x

#142584 release-23.2: released CockroachDB version 23.2.21. Next version: 23.2.22
  pkg/build/version.txt
Labels: backport

#142586 release-24.1: released CockroachDB version 24.1.14. Next version: 24.1.15
  pkg/build/version.txt
Labels: backport

#142589 release-24.3: released CockroachDB version 24.3.7. Next version: 24.3.8
  pkg/build/version.txt
Labels: backport

#142609 release-24.1: sql/schemachanger: fix create sequence schema version bump
  pkg/sql/schemachanger/scexec/scmutationexec/references.go
  pkg/sql/schemachanger/testdata/end_to_end/create_complex/create_complex.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_function/create_function.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_function_calling_function/create_function_calling_function.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_sequence/create_sequence.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_sequence_add_column/create_sequence_add_column.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/create_sequence_drop_sequence/create_sequence_drop_sequence.side_effects
  pkg/sql/schemachanger/testdata/end_to_end/drop_function/drop_function.side_effects
Labels: backport

#142635 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#142636 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#142637 release-25.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#142639 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#142632 release-24.1: backup: fix backupAndRestore test helper search for backup job query
  pkg/ccl/backupccl/backup_test.go
Labels: backport

#142633 release-24.3: backup: fix backupAndRestore test helper search for backup job query
  pkg/ccl/backupccl/backup_test.go
Labels: backport

#142631 release-23.2: backup: fix backupAndRestore test helper search for backup job query
  pkg/ccl/backupccl/backup_test.go
Labels: backport

#142693 release-25.1.2-rc: released CockroachDB version 25.1.1. Next version: 25.1.2
  pkg/build/version.txt
Labels: backport

#142700 roachtest: disable metamorphism for import-cancellation
  pkg/cmd/roachtest/tests/import_cancellation.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#142670 sql: fix db drop failure due to undropped trigger function ref
  pkg/ccl/logictestccl/testdata/logic_test/triggers
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go
Labels: backport-24.3.x, backport-25.1.x

#142731 release-24.3: released CockroachDB version 24.3.8. Next version: 24.3.9
  pkg/build/version.txt
Labels: backport

#141800 schemachanger: update subzone configs with new indexID from backfill
  pkg/ccl/schemachangerccl/ccl_generated_test.go
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones.definition
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones.side_effects
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_1_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_2_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_3_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_4_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_5_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_6_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_7_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__statement_1_of_3.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__statement_1_of_3.explain_shape
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__statement_2_of_3.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__statement_2_of_3.explain_shape
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__statement_3_of_3.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__statement_3_of_3.explain_shape
  pkg/sql/logictest/testdata/logic_test/zone_config
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go
  pkg/sql/schemachanger/scdeps/exec_deps.go
Labels: backport-25.1.x

#142781 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#142782 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#142785 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#142783 release-25.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/sql/logictest/REPOSITORIES.bzl
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#142427 release-24.1: cli: actually drain after decommission
  pkg/cli/node.go
  pkg/cmd/roachtest/tests/decommission.go
Labels: backport

#142776 release: verify Sentry issue is generated
  build/teamcity/internal/release/process/trigger-sentry-panic.sh
  pkg/BUILD.bazel
  pkg/cmd/release/sentry/BUILD.bazel
  pkg/cmd/release/sentry/main.go
Labels: C-enhancement, A-release, T-release, backport-all

#142061 sql: add notice delete rate limit is per leaseholder when configured
  pkg/sql/alter_table.go
  pkg/sql/create_table.go
  pkg/sql/logictest/testdata/logic_test/cluster_settings
  pkg/sql/logictest/testdata/logic_test/row_level_ttl
  pkg/sql/set_cluster_setting.go
Labels: backport-23.2.x, backport-24.1.x, backport-24.3.x, backport-25.1.x

#142682 security: cache certificate expiration metrics as pointers
  pkg/security/BUILD.bazel
  pkg/security/cert_expiry_cache.go
  pkg/security/cert_expiry_cache_test.go
Labels: backport-24.1.x, backport-24.3.x

#141958 release-24.3: colexecbase: remove incorrect casts to Oid types
  pkg/sql/colexec/colexecbase/cast.eg.go
  pkg/sql/colexec/colexecbase/cast_tmpl.go
  pkg/sql/colexec/proj_utils_test.go
  pkg/sql/logictest/testdata/logic_test/cast
  pkg/sql/opt/exec/execbuilder/testdata/experimental_distsql_planning_5node
  pkg/sql/opt/exec/execbuilder/testdata/vectorize_local
Labels: backport

#142838 multiregion: fix replicas leak out of configured regions
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_survival_goal
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_config_extensions
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/ccl/logictestccl/testdata/logic_test/secondary_region
  pkg/ccl/schemachangerccl/testdata/decomp/multiregion
  pkg/sql/alter_database.go
  pkg/sql/catalog/multiregion/region_config.go
  pkg/sql/region_util.go
  pkg/sql/regions/region_util.go
Labels: backport-25.1.x

#142874 release: fetch secrets before logging in to gcloud
  build/teamcity/internal/cockroach/release/publish/sign_staged_macos_release_on_linux.sh
Labels: C-bug, A-release, T-release, backport-all

#142853 release-24.3: workload/npgsql: ignore flaky test Failed_transaction_on_close_with_custom_timeout
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
Labels: backport

#142854 release-24.1: workload/npgsql: ignore flaky test Failed_transaction_on_close_with_custom_timeout
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
Labels: backport

#142855 release-23.2: workload/npgsql: ignore flaky test Failed_transaction_on_close_with_custom_timeout
  pkg/cmd/roachtest/tests/npgsql_blocklist.go
Labels: backport

#142478 server: include nice, irq, softirq in host cpu calculation
  pkg/server/status/BUILD.bazel
  pkg/server/status/runtime.go
  pkg/server/status/runtime_test.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#142919 kvserver: limit rangefeed cancel log msg
  pkg/kv/kvserver/replica_rangefeed.go
Labels: backport-25.1.x

#142913 changefeedccl: fix race in TestChangefeedSchemaChangeAllowBackfill
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#142909 sql: add test for session migration with DECLARE CURSOR
  pkg/sql/conn_executor_prepare.go
  pkg/sql/testdata/session_migration/prepared_statements
Labels: backport-25.1.x

#142915 release-24.1: security: cache certificate expiration metrics as pointers
  pkg/security/BUILD.bazel
  pkg/security/cert_expiry_cache.go
  pkg/security/cert_expiry_cache_test.go
Labels: backport

#142844 release-25.1: schemachanger: update subzone configs with new indexID from backfill
  pkg/ccl/schemachangerccl/ccl_generated_test.go
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones.definition
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones.side_effects
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_1_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_2_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_3_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_4_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_5_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_6_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__rollback_7_of_7.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__statement_1_of_3.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__statement_1_of_3.explain_shape
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__statement_2_of_3.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__statement_2_of_3.explain_shape
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__statement_3_of_3.explain
  pkg/ccl/schemachangerccl/testdata/end_to_end/add_column_subzones/add_column_subzones__statement_3_of_3.explain_shape
  pkg/sql/logictest/testdata/logic_test/zone_config
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go
  pkg/sql/schemachanger/scdeps/exec_deps.go
Labels: backport

#142988 release-25.1: scbuild: clean up unneeded subzones after index swap
  pkg/ccl/schemachangerccl/BUILD.bazel
  pkg/ccl/schemachangerccl/schemachanger_ccl_test.go
  pkg/sql/logictest/testdata/logic_test/zone_config
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go
Labels: backport

#142943 release-25.1: logictest: fix rare flake around partial stats
  pkg/sql/logictest/testdata/logic_test/distsql_stats
Labels: backport, backport-24.3.x

#143001 release-25.1: released CockroachDB version 25.1.2. Next version: 25.1.3
  pkg/build/version.txt
Labels: backport

#142980 release-25.1: multiregion: fix replicas leak out of configured regions
  pkg/ccl/logictestccl/testdata/logic_test/multi_region
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_survival_goal
  pkg/ccl/logictestccl/testdata/logic_test/multi_region_zone_config_extensions
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row
  pkg/ccl/logictestccl/testdata/logic_test/regional_by_row_query_behavior
  pkg/ccl/logictestccl/testdata/logic_test/secondary_region
  pkg/ccl/schemachangerccl/testdata/decomp/multiregion
  pkg/sql/alter_database.go
  pkg/sql/catalog/multiregion/region_config.go
  pkg/sql/region_util.go
Labels: backport

#143031 release-24.3: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#143032 release-24.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#143033 release-23.2: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#143034 release-25.1: Update pkg/testutils/release/cockroach_releases.yaml
  pkg/testutils/release/cockroach_releases.yaml
Labels: backport

#142917 sql: improve observability of index merge timestamp
  pkg/sql/backfill.go
  pkg/sql/catalog/lease/lease.go
  pkg/sql/mvcc_backfiller.go
  pkg/sql/schemachanger/scexec/BUILD.bazel
  pkg/sql/schemachanger/scexec/exec_backfill_test.go
  pkg/sql/schemachanger/scexec/exec_validation.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#143072 crosscluster/physical: actually spin up reader tenant on failback
  pkg/crosscluster/physical/standby_read_ts_poller_job_test.go
  pkg/crosscluster/physical/stream_ingestion_frontier_processor.go
  pkg/crosscluster/replicationtestutils/testutils.go
Labels: backport-24.3.x, backport-25.1.x

#143089 scbuild: clean up logic for finding temporary indexes
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go
  pkg/sql/schemachanger/scpb/elements.proto
Labels: backport-25.1.x

#143008 logictestccl: deflake as_of
  pkg/ccl/logictestccl/testdata/logic_test/as_of
Labels: backport-25.1.x

#143064 release-24.1: sql: improve observability of index merge timestamp
  pkg/sql/backfill.go
  pkg/sql/catalog/lease/lease.go
  pkg/sql/mvcc_backfiller.go
  pkg/sql/schemachanger/scexec/BUILD.bazel
  pkg/sql/schemachanger/scexec/exec_backfill_test.go
  pkg/sql/schemachanger/scexec/exec_validation.go
Labels: backport

#143062 release-24.3: sql: improve observability of index merge timestamp
  pkg/sql/backfill.go
  pkg/sql/catalog/lease/lease.go
  pkg/sql/mvcc_backfiller.go
  pkg/sql/schemachanger/scexec/BUILD.bazel
  pkg/sql/schemachanger/scexec/exec_backfill_test.go
  pkg/sql/schemachanger/scexec/exec_validation.go
Labels: backport

#143059 release-25.1: sql: improve observability of index merge timestamp
  pkg/sql/backfill.go
  pkg/sql/catalog/lease/lease.go
  pkg/sql/mvcc_backfiller.go
  pkg/sql/schemachanger/scexec/BUILD.bazel
  pkg/sql/schemachanger/scexec/exec_backfill_test.go
  pkg/sql/schemachanger/scexec/exec_validation.go
Labels: backport

#143102 changefeedccl: ensure that spans planned from cdc queries have end keys
  pkg/ccl/changefeedccl/cdceval/plan.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport-all

#143143 release-23.2: go.mod: bump Pebble to a020398d6dda
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#143142 release-25.1: scbuild: clean up logic for finding temporary indexes
  pkg/sql/schemachanger/scbuild/internal/scbuildstmt/zone_config_helpers.go
  pkg/sql/schemachanger/scpb/elements.proto
Labels: backport

#143055 roachtest: fix missing binary for TPC-C in multitenant upgrade test
  pkg/cmd/roachtest/tests/multitenant_upgrade.go
Labels: backport-25.1.x

#143191 kvserver: reset some fields of replicaAppBatch
  pkg/kv/kvserver/replica_application_state_machine.go
Labels: backport-all

#143169 mirror: fix non-determinism in case two packages have the same path
  pkg/cmd/mirror/go/mirror.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#143147 release-23.2: changefeedccl: ensure that spans planned from cdc queries have end keys
  pkg/ccl/changefeedccl/cdceval/plan.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport

#143148 release-24.1: changefeedccl: ensure that spans planned from cdc queries have end keys
  pkg/ccl/changefeedccl/cdceval/plan.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport

#143149 release-24.3: changefeedccl: ensure that spans planned from cdc queries have end keys
  pkg/ccl/changefeedccl/cdceval/plan.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport

#143150 release-25.1: changefeedccl: ensure that spans planned from cdc queries have end keys
  pkg/ccl/changefeedccl/cdceval/plan.go
  pkg/ccl/changefeedccl/changefeed_test.go
Labels: backport

#142001 rpc,server: add grpc server interceptor to instrument rpcs
  docs/generated/metrics/metrics.html
  pkg/roachprod/opentelemetry/cockroachdb_metrics.go
  pkg/rpc/BUILD.bazel
  pkg/rpc/context.go
  pkg/rpc/context_test.go
  pkg/rpc/metrics.go
  pkg/rpc/metrics_test.go
  pkg/rpc/settings.go
  pkg/server/BUILD.bazel
  pkg/server/grpc_server.go
  pkg/server/grpc_server_test.go
  pkg/server/server.go
  pkg/server/tenant.go
Labels: T-microbench-post

#143219 CODEOWNERS: mark pkg/sql/syntheticprivilege* as owned by Foundations
  .github/CODEOWNERS
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#143229 release-25.1: mirror: fix non-determinism in case two packages have the same path
  pkg/cmd/mirror/go/mirror.go
Labels: backport

#143228 release-24.3: mirror: fix non-determinism in case two packages have the same path
  pkg/cmd/mirror/go/mirror.go
Labels: backport

#143227 release-24.1: mirror: fix non-determinism in case two packages have the same path
  pkg/cmd/mirror/go/mirror.go
Labels: backport

#143245 release-23.2: mirror: fix non-determinism in case two packages have the same path
  pkg/cmd/mirror/go/mirror.go
Labels: backport

#142972 kvserver: deflake TestPromoteNonVoterInAddVoter
  pkg/kv/kvserver/replicate_queue_test.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x

#143122 kvserver: actually subject MVCC GC to IO admission control
  pkg/kv/kvserver/mvcc_gc_queue.go
Labels: backport-all

#143236 release-25.1: go.mod: bump Pebble to 164663554a99
  DEPS.bzl
  build/bazelutil/distdir_files.bzl
  go.mod
  go.sum
Labels: backport

#142929 release-24.3: sql: display retry count and time for EXPLAIN ANALYZE
  pkg/sql/conn_executor_exec.go
  pkg/sql/instrumentation.go
  pkg/sql/opt/exec/explain/output.go
  pkg/sql/opt/exec/explain/output_test.go
Labels: backport

#143297 release-25.1: release: decrease log level for preflight check
  build/teamcity/internal/cockroach/release/publish/publish-redhat-release.sh
Labels: O-robot, blathers-backport, backport, target-release-25.1.4

#143295 release-24.3: release: decrease log level for preflight check
  build/teamcity/internal/cockroach/release/publish/publish-redhat-release.sh
Labels: O-robot, blathers-backport, backport, target-release-24.3.10

#143292 release-23.2: release: decrease log level for preflight check
  build/teamcity/internal/cockroach/release/publish/publish-redhat-release.sh
Labels: O-robot, blathers-backport, backport

#143294 release-24.1: release: decrease log level for preflight check
  build/teamcity/internal/cockroach/release/publish/publish-redhat-release.sh
Labels: O-robot, blathers-backport, backport

#143303 release-23.2.22-rc: release: decrease log level for preflight check
  build/teamcity/internal/cockroach/release/publish/publish-redhat-release.sh
Labels: O-robot, blathers-backport, backport

#143302 release-24.3.9-rc: release: decrease log level for preflight check
  build/teamcity/internal/cockroach/release/publish/publish-redhat-release.sh
Labels: O-robot, blathers-backport, backport

#143301 release-24.1.15-rc: release: decrease log level for preflight check
  build/teamcity/internal/cockroach/release/publish/publish-redhat-release.sh
Labels: O-robot, blathers-backport, backport

#143230 roachtest: enable table stats histograms in sysbench
  pkg/cmd/roachtest/tests/sysbench.go
Labels: o-perf-efficiency

#143291 release-23.2: sql: avoid dangling role reference in default privileges
  pkg/sql/catalog/catprivilege/default_privilege.go
  pkg/sql/logictest/testdata/logic_test/drop_role_with_default_privileges
Labels: O-robot, blathers-backport, backport

#143298 release-25.1: sql: avoid dangling role reference in default privileges
  pkg/sql/catalog/catprivilege/default_privilege.go
  pkg/sql/logictest/testdata/logic_test/drop_role_with_default_privileges
Labels: O-robot, blathers-backport, backport

#143293 release-24.1: sql: avoid dangling role reference in default privileges
  pkg/sql/catalog/catprivilege/default_privilege.go
  pkg/sql/logictest/testdata/logic_test/drop_role_with_default_privileges
Labels: O-robot, blathers-backport, backport

#143296 release-24.3: sql: avoid dangling role reference in default privileges
  pkg/sql/catalog/catprivilege/default_privilege.go
  pkg/sql/logictest/testdata/logic_test/drop_role_with_default_privileges
Labels: O-robot, blathers-backport, backport

#143307 slstorage: reduce allocations in `(*Storage).isAlive`
  pkg/sql/sqlliveness/slstorage/slstorage.go
Labels: o-perf-efficiency

#143285 release-25.1: upgrademanager: skip TestPrecondition under race
  pkg/upgrade/upgrademanager/manager_external_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#142984 ui: fix network page rendering with decommissioned node
  pkg/ui/workspaces/db-console/src/views/reports/containers/network/index.spec.tsx
  pkg/ui/workspaces/db-console/src/views/reports/containers/network/index.tsx
Labels: backport-24.3.x, backport-25.1.x

#142162 release-24.3: stmtbundle: refactor FK handling in schema.sql
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/acceptance/generated_cli_test.go
  pkg/cli/interactive_tests/test_sb_recreate_fks.tcl
  pkg/sql/delegate/show_table.go
  pkg/sql/exec_factory_util.go
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
  pkg/sql/logictest/testdata/logic_test/show_create
  pkg/sql/opt/BUILD.bazel
  pkg/sql/opt/cat/table.go
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/scalar.go
  pkg/sql/opt/exec/execbuilder/testdata/explain_env
  pkg/sql/opt/exec/factory.go
  pkg/sql/opt/metadata.go
  pkg/sql/opt/util.go
  pkg/sql/opt_exec_factory.go
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/show
  pkg/sql/plan.go
  pkg/sql/sem/tree/show.go
Labels: backport, backport-24.3.9-rc

#142164 release-24.1: stmtbundle: refactor FK handling in schema.sql
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/acceptance/generated_cli_test.go
  pkg/cli/interactive_tests/test_sb_recreate_fks.tcl
  pkg/sql/delegate/show_table.go
  pkg/sql/exec_factory_util.go
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
  pkg/sql/logictest/testdata/logic_test/show_create
  pkg/sql/opt/BUILD.bazel
  pkg/sql/opt/cat/table.go
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/scalar.go
  pkg/sql/opt/exec/execbuilder/testdata/explain_env
  pkg/sql/opt/exec/factory.go
  pkg/sql/opt/metadata.go
  pkg/sql/opt/util.go
  pkg/sql/opt_exec_factory.go
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/show
  pkg/sql/plan.go
  pkg/sql/sem/tree/show.go
Labels: backport

#143141 release-25.1: crosscluster/physical: actually spin up reader tenant on failback
  pkg/crosscluster/physical/standby_read_ts_poller_job_test.go
  pkg/crosscluster/physical/stream_ingestion_frontier_processor.go
  pkg/crosscluster/replicationtestutils/testutils.go
Labels: backport

#141865 release-25.1: crosscluster/physical: add intitial scan replication status
  pkg/crosscluster/physical/stream_ingestion_dist.go
  pkg/crosscluster/physical/stream_ingestion_frontier_processor.go
  pkg/jobs/jobspb/wrap.go
Labels: backport

#143311 crosscluster/logical: fix crash when using UDTs in LDR on multiple nodes
  pkg/crosscluster/logical/logical_replication_dist.go
  pkg/crosscluster/logical/logical_replication_job.go
  pkg/crosscluster/logical/logical_replication_job_test.go
  pkg/crosscluster/logical/logical_replication_writer_processor.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
Labels: backport-24.3.x, backport-25.1.x

#143376 release-24.3: crosscluster/logical: fix crash when using UDTs in LDR on multiple nodes
  pkg/ccl/crosscluster/logical/logical_replication_dist.go
  pkg/ccl/crosscluster/logical/logical_replication_job.go
  pkg/ccl/crosscluster/logical/logical_replication_job_test.go
  pkg/ccl/crosscluster/logical/logical_replication_writer_processor.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
Labels: backport, backport-failed, backport-24.3.9-rc

#142165 release-23.2: stmtbundle: refactor FK handling in schema.sql
  docs/generated/sql/bnf/stmt_block.bnf
  pkg/acceptance/generated_cli_test.go
  pkg/cli/interactive_tests/test_sb_recreate_fks.tcl
  pkg/sql/delegate/show_table.go
  pkg/sql/exec_factory_util.go
  pkg/sql/explain_bundle.go
  pkg/sql/explain_bundle_test.go
  pkg/sql/logictest/testdata/logic_test/show_create
  pkg/sql/opt/BUILD.bazel
  pkg/sql/opt/cat/table.go
  pkg/sql/opt/exec/execbuilder/mutation.go
  pkg/sql/opt/exec/execbuilder/relational.go
  pkg/sql/opt/exec/execbuilder/scalar.go
  pkg/sql/opt/exec/execbuilder/testdata/explain_env
  pkg/sql/opt/exec/factory.go
  pkg/sql/opt/metadata.go
  pkg/sql/opt/util.go
  pkg/sql/opt_exec_factory.go
  pkg/sql/parser/sql.y
  pkg/sql/parser/testdata/show
  pkg/sql/plan.go
  pkg/sql/sem/tree/show.go
Labels: backport

#143170 sql: only re-use resolved routine type when flag is set
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/opt/optbuilder/values.go
  pkg/sql/sem/tree/type_check.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x, backport-24.3.9-rc, backport-24.1.15-rc, backport-25.1.3-rc

#143432 release-24.1: upgrademanager: skip TestPrecondition under race
  pkg/upgrade/upgrademanager/manager_external_test.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#143369 release-24.3: release-25.1: crosscluster/physical: actually spin up reader tenant on failback
  pkg/ccl/crosscluster/physical/standby_read_ts_poller_job_test.go
  pkg/ccl/crosscluster/physical/stream_ingestion_frontier_processor.go
  pkg/ccl/crosscluster/replicationtestutils/testutils.go
Labels: backport

#143457 roachtest: mark activerecord test as flaky
  pkg/cmd/roachtest/tests/activerecord_blocklist.go
Labels: backport-25.1.x

#143462 release-25.1: roachtest: mark activerecord test as flaky
  pkg/cmd/roachtest/tests/activerecord_blocklist.go
Labels: O-robot, blathers-backport, backport, backport-test-only

#143454 urlcheck: skip for pre-release and customized versions
  pkg/build/info.go
  pkg/testutils/lint/BUILD.bazel
  pkg/testutils/lint/nightly_lint_test.go
Labels: C-enhancement, A-release, T-release

#143416 release-23.2: jobs: remove TestPauseReason
  pkg/jobs/jobs_test.go
Labels: backport

#143529 release-24.1: build: upgrade bazel to 7.6.0
  .bazelversion
Labels: O-robot, blathers-backport, backport

#143530 release-24.3: build: upgrade bazel to 7.6.0
  .bazelversion
Labels: O-robot, blathers-backport, backport

#143532 release-25.1: build: upgrade bazel to 7.6.0
  .bazelversion
Labels: O-robot, blathers-backport, backport

#143518 rac2: reduce tokenCounter mutex contention
  pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go
Labels: o-perf-efficiency

#143395 release-24.3: sql: extend drop region for system db
  pkg/ccl/multiregionccl/multiregion_system_table_test.go
  pkg/sql/alter_database.go
  pkg/sql/type_change.go
Labels: backport

#143595 release-24.1: sql,backfill: avoid holding a protected timestamp during the backfill
  pkg/sql/backfill.go
  pkg/sql/backfill_protected_timestamp_test.go
  pkg/sql/distsql_plan_backfill.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
  pkg/sql/index_backfiller.go
  pkg/sql/rowexec/indexbackfiller.go
  pkg/sql/schema_changer_test.go
  pkg/sql/schemachanger/scexec/exec_backfill.go
Labels: backport

#143594 release-24.3: sql,backfill: avoid holding a protected timestamp during the backfill
  pkg/sql/backfill.go
  pkg/sql/backfill_protected_timestamp_test.go
  pkg/sql/distsql_plan_backfill.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
  pkg/sql/index_backfiller.go
  pkg/sql/rowexec/indexbackfiller.go
  pkg/sql/schema_changer_test.go
  pkg/sql/schemachanger/scexec/exec_backfill.go
Labels: backport

#143520 release-25.1: sql,backfill: avoid holding a protected timestamp during the backfill
  pkg/sql/backfill.go
  pkg/sql/backfill_protected_timestamp_test.go
  pkg/sql/distsql_plan_backfill.go
  pkg/sql/execinfrapb/processors_bulk_io.proto
  pkg/sql/index_backfiller.go
  pkg/sql/rowexec/indexbackfiller.go
  pkg/sql/schema_changer_test.go
  pkg/sql/schemachanger/scexec/exec_backfill.go
Labels: backport

#143591 release-24.3: client cert expirations cached by usage
  pkg/BUILD.bazel
  pkg/security/BUILD.bazel
  pkg/security/auth.go
  pkg/security/cert_expiry_cache.go
  pkg/security/cert_expiry_cache_test.go
  pkg/security/certificate_manager.go
  pkg/security/clientcert/BUILD.bazel
  pkg/security/clientcert/cert_expiry_cache.go
  pkg/security/clientcert/cert_expiry_cache_test.go
  pkg/server/server_sql.go
  pkg/util/metric/aggmetric/agg_metric.go
  pkg/util/metric/aggmetric/counter.go
  pkg/util/metric/aggmetric/gauge.go
  pkg/util/metric/aggmetric/histogram.go
Labels: backport

#143593 release-24.3.9-rc: client cert expirations cached by usage
  pkg/BUILD.bazel
  pkg/security/BUILD.bazel
  pkg/security/auth.go
  pkg/security/cert_expiry_cache.go
  pkg/security/cert_expiry_cache_test.go
  pkg/security/certificate_manager.go
  pkg/security/clientcert/BUILD.bazel
  pkg/security/clientcert/cert_expiry_cache.go
  pkg/security/clientcert/cert_expiry_cache_test.go
  pkg/server/server_sql.go
  pkg/util/metric/aggmetric/agg_metric.go
  pkg/util/metric/aggmetric/counter.go
  pkg/util/metric/aggmetric/gauge.go
  pkg/util/metric/aggmetric/histogram.go
Labels: backport

#143632 release-25.1.3-rc: sql: only re-use resolved routine type when flag is set
  pkg/sql/logictest/testdata/logic_test/udf
  pkg/sql/opt/optbuilder/values.go
  pkg/sql/sem/tree/type_check.go
Labels: backport, branch-release-25.1.3-rc

#143666 release-24.1: tests: use livebytes metric for disagg-rebalance
  pkg/cmd/roachtest/tests/disagg_rebalance.go
Labels: backport, backport-test-only

#143758 release-25.1: tree: include gist into enum comparison assertion
  pkg/sql/conn_executor.go
  pkg/sql/sem/tree/datum.go
Labels: O-robot, blathers-backport, backport

#143757 release-24.3: tree: include gist into enum comparison assertion
  pkg/sql/conn_executor.go
  pkg/sql/sem/tree/datum.go
Labels: O-robot, blathers-backport, backport

#143755 explain: fix recently added TestRetryFields
  pkg/sql/opt/exec/explain/output_test.go
Labels: backport-24.1.x, backport-24.3.x, backport-25.1.x
